---
permalink: audit/audit-log-file-rotation.html 
sidebar: sidebar 
keywords: storagegrid, audit, log file, audit.log, audit.log file, rotation, save, autosave, auto save, auto-save 
summary: 감사 로그 파일은 관리 노드의 /var/local/log 디렉토리에 저장됩니다. 활성 감사 로그 파일의 이름은 audit.log입니다. 
---
= 감사 로그 파일 회전
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 로그 파일은 관리 노드에 저장됩니다. `/var/local/log` 예배 규칙서. 활성 감사 로그 파일의 이름은 다음과 같습니다. `audit.log` .


NOTE: 선택적으로 감사 로그의 대상을 변경하고 감사 정보를 외부 syslog 서버로 보낼 수 있습니다. 외부 syslog 서버가 구성되면 감사 기록의 로컬 로그가 계속 생성되어 저장됩니다. 보다 link:../monitor/configure-audit-messages.html["감사 메시지 및 로그 대상 구성"] .

하루에 한 번, 활성 `audit.log` 파일이 저장되고 새 파일이 생성됩니다. `audit.log` 파일이 시작되었습니다.  저장된 파일의 이름은 저장된 날짜를 다음 형식으로 나타냅니다. `_yyyy-mm-dd.txt_` .  하루에 두 개 이상의 감사 로그가 생성되는 경우 파일 이름은 파일이 저장된 날짜를 사용하고 숫자는 다음 형식으로 추가됩니다. `_yyyy-mm-dd.txt.n_` .  예를 들어, `2018-04-15.txt` 그리고 `2018-04-15.txt.1` 2018년 4월 15일에 생성되어 저장된 첫 번째 및 두 번째 로그 파일입니다.

하루가 지나면 저장된 파일은 압축되어 다음 형식으로 이름이 변경됩니다. `_yyyy-mm-dd.txt.gz_` 원래 날짜를 보존합니다. 시간이 지남에 따라 관리 노드의 감사 로그에 할당된 저장 공간이 소모됩니다. 스크립트는 감사 로그 공간 소비를 모니터링하고 필요에 따라 로그 파일을 삭제하여 공간을 확보합니다. `/var/local/log` 예배 규칙서.  감사 로그는 생성된 날짜를 기준으로 삭제되며, 가장 오래된 로그가 먼저 삭제됩니다. 다음 파일에서 스크립트의 동작을 모니터링할 수 있습니다. `/var/local/log/manage-audit.log` .

이 예에서는 활성을 보여줍니다. `audit.log` 파일, 전날의 파일(`2018-04-15.txt` ), 그리고 전날의 압축 파일(`2018-04-14.txt.gz` ).

[listing]
----
audit.log
2018-04-15.txt
2018-04-14.txt.gz
----