---
permalink: audit/cbre-object-receive-end.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBRE, Object Receive End 
summary: 콘텐츠 블록이 한 노드에서 다른 노드로 전송되면 대상 엔터티에서 이 메시지가 발행됩니다. 
---
= CBRE: 객체 수신 끝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
콘텐츠 블록이 한 노드에서 다른 노드로 전송되면 대상 엔터티에서 이 메시지가 발행됩니다.

[cols="1a,1a,4a"]
|===
| 암호 | 필드 | 설명 


 a| 
CNID
 a| 
연결 식별자
 a| 
노드 간 세션/연결의 고유 식별자입니다.



 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
전송되는 콘텐츠 블록의 고유 식별자입니다.



 a| 
CTDR
 a| 
전송 방향
 a| 
CBID 전송이 푸시 방식으로 시작되었는지 풀 방식으로 시작되었는지를 나타냅니다.

PUSH: 전송 작업이 전송 엔터티에 의해 요청되었습니다.

PULL: 수신 엔터티가 전송 작업을 요청했습니다.



 a| 
CTSR
 a| 
소스 엔터티
 a| 
CBID 전송의 소스(발신자)의 노드 ID입니다.



 a| 
CTDS
 a| 
목적지 엔터티
 a| 
CBID 전송의 대상(수신자)의 노드 ID입니다.



 a| 
CTSS
 a| 
시작 시퀀스 카운트
 a| 
전송이 시작된 시퀀스 수를 나타냅니다.



 a| 
CTAS
 a| 
실제 종료 시퀀스 수
 a| 
마지막 시퀀스 수가 성공적으로 전송되었음을 나타냅니다.  실제 종료 시퀀스 수가 시작 시퀀스 수와 같고 전송 결과가 성공적이지 않은 경우 데이터가 교환되지 않았습니다.



 a| 
RSLT
 a| 
전송 결과
 a| 
전송 작업의 결과(전송 엔터티의 관점에서):

SUCS: 전송이 성공적으로 완료되었습니다. 요청된 모든 시퀀스 수가 전송되었습니다.

CONL: 전송 중 연결이 끊어졌습니다.

CTMO: 설정 또는 전송 중 연결 시간이 초과되었습니다.

UNRE: 대상 노드 ID에 도달할 수 없음

CRPT: 손상되었거나 잘못된 데이터를 수신하여 전송이 종료되었습니다.

|===
이 감사 메시지는 노드 간 데이터 전송 작업이 완료되었음을 의미합니다.  전송 결과가 성공적이면 작업은 "시작 시퀀스 수"에서 "실제 종료 시퀀스 수"로 데이터를 전송합니다.  송신 및 수신 노드는 노드 ID로 식별됩니다.  이 정보는 시스템 데이터 흐름을 추적하고 오류를 찾아 정리하고 분석하는 데 사용할 수 있습니다.  저장소 감사 메시지와 결합하면 복제본 수를 확인하는 데에도 사용할 수 있습니다.
