---
permalink: audit/cbsb-object-send-begin.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, CBSB, Object Send Begin 
summary: 일반적인 시스템 운영 중에 콘텐츠 블록은 데이터에 액세스하고 복제하고 보관하면서 여러 노드 간에 지속적으로 전송됩니다.  한 노드에서 다른 노드로 콘텐츠 블록을 전송하는 경우, 이 메시지는 소스 엔터티에서 발행됩니다. 
---
= CBSB: 객체 전송 시작
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일반적인 시스템 운영 중에 콘텐츠 블록은 데이터에 액세스하고 복제하고 보관하면서 여러 노드 간에 지속적으로 전송됩니다.  한 노드에서 다른 노드로 콘텐츠 블록을 전송하는 경우, 이 메시지는 소스 엔터티에서 발행됩니다.

[cols="1a,1a,4a"]
|===
| 암호 | 필드 | 설명 


 a| 
CNID
 a| 
연결 식별자
 a| 
노드 간 세션/연결의 고유 식별자입니다.



 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
전송되는 콘텐츠 블록의 고유 식별자입니다.



 a| 
CTDR
 a| 
전송 방향
 a| 
CBID 전송이 푸시 방식으로 시작되었는지 풀 방식으로 시작되었는지를 나타냅니다.

PUSH: 전송 작업이 전송 엔터티에 의해 요청되었습니다.

PULL: 수신 엔터티가 전송 작업을 요청했습니다.



 a| 
CTSR
 a| 
소스 엔터티
 a| 
CBID 전송의 소스(발신자)의 노드 ID입니다.



 a| 
CTDS
 a| 
목적지 엔터티
 a| 
CBID 전송의 대상(수신자)의 노드 ID입니다.



 a| 
CTSS
 a| 
시작 시퀀스 카운트
 a| 
요청된 첫 번째 시퀀스 카운트를 나타냅니다.  성공하면 이 시퀀스 카운트에서 전송이 시작됩니다.



 a| 
CTES
 a| 
예상 종료 시퀀스 수
 a| 
마지막으로 요청된 시퀀스 수를 나타냅니다.  성공하면, 이 시퀀스 카운트가 수신되었을 때 전송이 완료된 것으로 간주됩니다.



 a| 
RSLT
 a| 
전송 시작 상태
 a| 
전송이 시작될 당시의 상태:

SUCS: 전송이 성공적으로 시작되었습니다.

|===
이 감사 메시지는 콘텐츠 블록 식별자로 식별된 단일 콘텐츠에 대해 노드 간 데이터 전송 작업이 시작되었음을 의미합니다.  이 작업은 "시작 시퀀스 수"에서 "예상 종료 시퀀스 수"까지의 데이터를 요청합니다.  송신 및 수신 노드는 노드 ID로 식별됩니다.  이 정보는 시스템 데이터 흐름을 추적하는 데 사용할 수 있으며, 저장소 감사 메시지와 결합하면 복제본 수를 확인하는 데 사용할 수 있습니다.
