---
permalink: audit/common-elements-in-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message, common elements, AMID, ANID, ASES, ASQN, ATID, ATIM, ATYP, AVER, RSLT 
summary: 모든 감사 메시지에는 공통적인 요소가 포함되어 있습니다. 
---
= 감사 메시지의 공통 요소
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 감사 메시지에는 공통적인 요소가 포함되어 있습니다.

[cols="1a,1a,4a"]
|===
| 암호 | 유형 | 설명 


 a| 
가운데에
 a| 
FC32
 a| 
모듈 ID: 메시지를 생성한 모듈 ID의 4자리 식별자입니다.  이는 감사 메시지가 생성된 코드 세그먼트를 나타냅니다.



 a| 
아니드
 a| 
UI32
 a| 
노드 ID: 메시지를 생성한 서비스에 할당된 그리드 노드 ID입니다.  StorageGRID 시스템이 구성되고 설치될 때 각 서비스에는 고유한 식별자가 할당됩니다.  이 ID는 변경할 수 없습니다.



 a| 
ASES
 a| 
UI64
 a| 
감사 세션 식별자: 이전 릴리스에서는 이 요소는 서비스가 시작된 후 감사 시스템이 초기화된 시간을 나타냈습니다.  이 시간 값은 운영 체제 시대(1970년 1월 1일 00:00:00 UTC) 이후 마이크로초 단위로 측정되었습니다.

*참고:* 이 요소는 더 이상 사용되지 않으며 감사 메시지에 나타나지 않습니다.



 a| 
ASQN
 a| 
UI64
 a| 
시퀀스 카운트: 이전 릴리스에서는 이 카운터는 그리드 노드(ANID)에서 생성된 각 감사 메시지에 대해 증가하고 서비스를 다시 시작할 때 0으로 재설정되었습니다.

*참고:* 이 요소는 더 이상 사용되지 않으며 감사 메시지에 나타나지 않습니다.



 a| 
아티드
 a| 
UI64
 a| 
추적 ID: 단일 이벤트에 의해 트리거된 메시지 세트에서 공유되는 식별자입니다.



 a| 
아팀
 a| 
UI64
 a| 
타임스탬프: 감사 메시지를 트리거한 이벤트가 생성된 시간으로, 운영 체제 시대(1970년 1월 1일 00:00:00 UTC) 이후 마이크로초 단위로 측정됩니다.  타임스탬프를 로컬 날짜와 시간으로 변환하는 데 사용되는 대부분의 도구는 밀리초를 기준으로 합니다.

기록된 타임스탬프를 반올림하거나 잘라내는 것이 필요할 수 있습니다.  감사 메시지의 시작 부분에 나타나는 사람이 읽을 수 있는 시간 `audit.log` 파일은 ISO 8601 형식의 ATIM 속성입니다.  날짜와 시간은 다음과 같이 표현됩니다. `_YYYY-MMDDTHH:MM:SS.UUUUUU_` , 여기서 `T` 날짜의 시간 세그먼트 시작을 나타내는 문자열 문자입니다. `_UUUUUU_` 마이크로초입니다.



 a| 
ATYP
 a| 
FC32
 a| 
이벤트 유형: 기록되는 이벤트의 4자리 식별자입니다.  이는 메시지의 "페이로드" 내용, 즉 포함되는 속성을 관리합니다.



 a| 
단언
 a| 
UI32
 a| 
버전: 감사 메시지의 버전입니다.  StorageGRID 소프트웨어가 발전함에 따라 새로운 버전의 서비스에 감사 보고 기능이 새로 추가될 수 있습니다.  이 필드는 AMS 서비스에서 이전 버전과의 호환성을 유지하여 이전 버전 서비스에서 전송된 메시지를 처리할 수 있도록 합니다.



 a| 
RSLT
 a| 
FC32
 a| 
결과: 이벤트, 프로세스 또는 거래의 결과.  메시지와 관련이 없는 경우, 메시지가 실수로 필터링되는 것을 방지하기 위해 SUCS 대신 NONE을 사용합니다.

|===