---
permalink: audit/idel-ilm-initiated-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, IDEL, ILM Initiated Delete 
summary: 이 메시지는 ILM이 개체 삭제 프로세스를 시작할 때 생성됩니다. 
---
= IDEL: ILM에서 삭제 시작
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 메시지는 ILM이 개체 삭제 프로세스를 시작할 때 생성됩니다.

IDEL 메시지는 다음 두 상황 중 하나에서 생성됩니다.

* *규정을 준수하는 S3 버킷의 객체*: 이 메시지는 ILM이 보존 기간이 만료되어 객체를 자동으로 삭제하는 프로세스를 시작할 때 생성됩니다(자동 삭제 설정이 활성화되어 있고 법적 보존이 해제되어 있다고 가정).
* *규격을 준수하지 않는 S3 버킷의 객체의 경우*  이 메시지는 ILM이 개체 삭제 프로세스를 시작할 때 생성됩니다. 활성 ILM 정책에 현재 개체에 적용되는 배치 지침이 없기 때문입니다.


[cols="1a,1a,4a"]
|===
| 암호 | 필드 | 설명 


 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
객체의 CBID.



 a| 
CMPA
 a| 
규정 준수: 자동 삭제
 a| 
규정을 준수하는 S3 버킷의 객체에만 해당됩니다.  0(거짓) 또는 1(참)은 버킷이 법적 보류 상태에 있는 경우를 제외하고 보존 기간이 끝나면 규정을 준수하는 객체를 자동으로 삭제할지 여부를 나타냅니다.



 a| 
CMPL
 a| 
규정 준수: 법적 보존
 a| 
규정을 준수하는 S3 버킷의 객체에만 해당됩니다.  0(거짓) 또는 1(참)은 버킷이 현재 법적 보류 상태에 있는지 여부를 나타냅니다.



 a| 
CMPR
 a| 
규정 준수: 보존 기간
 a| 
규정을 준수하는 S3 버킷의 객체에만 해당됩니다.  객체의 보존 기간(분)입니다.



 a| 
CTME
 a| 
규정 준수: 수집 시간
 a| 
규정을 준수하는 S3 버킷의 객체에만 해당됩니다.  객체의 수집 시간.  이 값에 보존 기간(분)을 추가하면 버킷에서 객체를 삭제할 수 있는 시점을 결정할 수 있습니다.



 a| 
DMRK
 a| 
마커 버전 ID 삭제
 a| 
버전이 지정된 버킷에서 객체를 삭제할 때 생성된 삭제 마커의 버전 ID입니다.  버킷에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
CSIZ
 a| 
콘텐츠 크기
 a| 
객체의 크기(바이트)입니다.



 a| 
지역
 a| 
위치
 a| 
StorageGRID 시스템 내의 객체 데이터의 저장 위치입니다.  객체에 위치가 없는 경우(예: 객체가 삭제된 경우) LOCS 값은 ""입니다.

CLEC: 삭제 코딩된 객체의 경우, 객체의 데이터에 적용되는 삭제 코딩 프로필 ID와 삭제 코딩 그룹 ID입니다.

CLDI: 복제된 개체의 경우 LDR 노드 ID와 개체 위치의 볼륨 ID입니다.

CLNL: 객체 데이터가 보관된 경우 객체 위치의 ARC 노드 ID입니다.



 a| 
길
 a| 
S3 버킷/키
 a| 
S3 버킷 이름과 S3 키 이름.



 a| 
RSLT
 a| 
결과
 a| 
ILM 작업의 결과.

SUCS: ILM 작업이 성공적이었습니다.



 a| 
규칙
 a| 
규칙 라벨
 a| 
* 규정을 준수하는 S3 버킷의 객체가 보존 기간이 만료되어 자동으로 삭제되는 경우 이 필드는 비어 있습니다.
* 현재 개체에 적용되는 배치 지침이 더 이상 없어서 개체가 삭제되는 경우, 이 필드에는 개체에 적용된 마지막 ILM 규칙의 사람이 읽을 수 있는 레이블이 표시됩니다.




 a| 
SGRP
 a| 
사이트(그룹)
 a| 
해당 사이트가 존재하는 경우, 해당 사이트에서 개체가 삭제되었으며, 해당 사이트는 개체가 수집된 사이트가 아닙니다.



 a| 
UUID
 a| 
범용 고유 식별자
 a| 
StorageGRID 시스템 내의 객체 식별자입니다.



 a| 
VSID
 a| 
버전 ID
 a| 
삭제된 개체의 특정 버전의 버전 ID입니다.  버전이 지정되지 않은 버킷의 버킷 및 객체에 대한 작업에는 이 필드가 포함되지 않습니다.

|===