---
permalink: audit/orlm-object-rules-met.html 
sidebar: sidebar 
keywords: audit message, ORLM, Object Rules Met, ilm rule 
summary: 이 메시지는 ILM 규칙에 따라 개체가 성공적으로 저장되고 복사되었을 때 생성됩니다. 
---
= ORLM: 객체 규칙 충족
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 메시지는 ILM 규칙에 따라 개체가 성공적으로 저장되고 복사되었을 때 생성됩니다.


NOTE: 정책의 다른 규칙이 개체 크기 고급 필터를 사용하는 경우 기본 Make 2 Copies 규칙에 따라 개체가 성공적으로 저장되면 ORLM 메시지가 생성되지 않습니다.

[cols="1a,1a,4a"]
|===
| 암호 | 필드 | 설명 


 a| 
빌드
 a| 
버킷 헤더
 a| 
버킷 ID 필드.  내부 작업에 사용됩니다.  STAT가 PRGD인 경우에만 나타납니다.



 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
객체의 CBID.



 a| 
CSIZ
 a| 
콘텐츠 크기
 a| 
객체의 크기(바이트)입니다.



 a| 
지역
 a| 
위치
 a| 
StorageGRID 시스템 내의 객체 데이터의 저장 위치입니다.  객체에 위치가 없는 경우(예: 객체가 삭제된 경우) LOCS 값은 ""입니다.

CLEC: 삭제 코딩된 객체의 경우, 객체의 데이터에 적용되는 삭제 코딩 프로필 ID와 삭제 코딩 그룹 ID입니다.

CLDI: 복제된 개체의 경우 LDR 노드 ID와 개체 위치의 볼륨 ID입니다.

CLNL: 객체 데이터가 보관된 경우 객체 위치의 ARC 노드 ID입니다.



 a| 
길
 a| 
S3 버킷/키
 a| 
S3 버킷 이름과 S3 키 이름.



 a| 
RSLT
 a| 
결과
 a| 
ILM 작업의 결과.

SUCS: ILM 작업이 성공적이었습니다.



 a| 
규칙
 a| 
규칙 라벨
 a| 
이 개체에 적용된 ILM 규칙에 지정된 사람이 읽을 수 있는 레이블입니다.



 a| 
SEGC
 a| 
컨테이너 UUID
 a| 
분할된 객체의 컨테이너의 UUID입니다.  이 값은 객체가 분할된 경우에만 사용할 수 있습니다.



 a| 
SGCB
 a| 
컨테이너 CBID
 a| 
분할된 객체의 컨테이너의 CBID입니다.  이 값은 분할된 객체와 다중 부분 객체에만 사용할 수 있습니다.



 a| 
통계
 a| 
상태
 a| 
ILM 운영 현황

완료: 해당 객체에 대한 ILM 작업이 완료되었습니다.

DFER: 해당 객체는 향후 ILM 재평가를 위해 표시되었습니다.

PRGD: 개체가 StorageGRID 시스템에서 삭제되었습니다.

NLOC: 개체 데이터를 더 이상 StorageGRID 시스템에서 찾을 수 없습니다.  이 상태는 모든 개체 데이터 사본이 누락되었거나 손상되었음을 나타낼 수 있습니다.



 a| 
UUID
 a| 
범용 고유 식별자
 a| 
StorageGRID 시스템 내의 객체 식별자입니다.



 a| 
VSID
 a| 
버전 ID
 a| 
버전이 지정된 버킷에 생성된 새 개체의 버전 ID입니다.  버전이 지정되지 않은 버킷의 버킷 및 객체에 대한 작업에는 이 필드가 포함되지 않습니다.

|===
ORLM 감사 메시지는 단일 객체에 대해 두 번 이상 발행될 수 있습니다.  예를 들어, 다음 이벤트 중 하나가 발생할 때마다 발행됩니다.

* 해당 객체에 대한 ILM 규칙은 영구적으로 충족됩니다.
* 이 시대에는 객체에 대한 ILM 규칙이 충족됩니다.
* ILM 규칙으로 인해 개체가 삭제되었습니다.
* 백그라운드 확인 프로세스에서는 복제된 개체 데이터의 복사본이 손상되었음을 감지합니다.  StorageGRID 시스템은 손상된 객체를 교체하기 위해 ILM 평가를 수행합니다.


.관련 정보
* link:object-ingest-transactions.html["객체 수집 트랜잭션"]
* link:object-delete-transactions.html["객체 삭제 트랜잭션"]

