---
permalink: audit/s3-select-request.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, S3SL, S3 Select request 
summary: 이 메시지는 사용자가 S3 Select 작업을 시작했음을 나타냅니다. 
---
= S3SL: S3 선택 요청
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 메시지는 S3 Select 요청이 클라이언트로 반환된 후 완료를 기록합니다.  S3SL 메시지에는 오류 메시지와 오류 코드 세부 정보가 포함될 수 있습니다.  요청이 성공하지 못했을 수 있습니다.

[cols="1a,1a,4a"]
|===
| 암호 | 필드 | 설명 


 a| 
BYSC
 a| 
스캔된 바이트
 a| 
스토리지 노드에서 스캔(수신)된 바이트 수입니다.

물체가 압축된 경우 BYSC와 BYPR이 다를 가능성이 높습니다.  객체가 압축된 경우 BYSC는 압축된 바이트 수를 갖고 BYPR은 압축 해제 후의 바이트 수를 갖습니다.



 a| 
바이프로
 a| 
처리된 바이트
 a| 
처리된 바이트 수.  S3 Select 작업에서 실제로 처리되거나 적용된 "스캔된 바이트"의 바이트 수를 나타냅니다.



 a| 
바이르트
 a| 
반환된 바이트
 a| 
S3 Select 작업이 클라이언트에 반환한 바이트 수입니다.



 a| 
재생
 a| 
처리된 기록
 a| 
S3 Select 작업이 스토리지 노드에서 수신한 레코드 또는 행 수입니다.



 a| 
재전송
 a| 
반환된 기록
 a| 
S3 Select 작업이 클라이언트에 반환한 레코드 또는 행 수입니다.



 a| 
조피
 a| 
작업 완료
 a| 
S3 Select 작업 처리가 완료되었는지 여부를 나타냅니다.  이것이 거짓이면 작업이 완료되지 못했고 오류 필드에 데이터가 있을 가능성이 높습니다.  클라이언트는 일부 결과만 받았을 수도 있고, 전혀 결과를 받지 못했을 수도 있습니다.



 a| 
리드
 a| 
요청 ID
 a| 
S3 Select 요청에 대한 식별자입니다.



 a| 
외부
 a| 
실행 시간
 a| 
S3 Select Job이 완료되는 데 걸린 시간(초)입니다.



 a| 
ERMG
 a| 
오류 메시지
 a| 
S3 Select 작업에서 생성된 오류 메시지입니다.



 a| 
에르티
 a| 
오류 유형
 a| 
S3 Select 작업에서 생성된 오류 유형입니다.



 a| 
ERST
 a| 
오류 스택 추적
 a| 
S3 Select 작업에서 생성된 오류 스택 추적입니다.



 a| 
S3BK
 a| 
S3 버킷
 a| 
S3 버킷 이름.



 a| 
S3AK
 a| 
S3 액세스 키 ID(요청 발신자)
 a| 
요청을 보낸 사용자의 S3 액세스 키 ID입니다.



 a| 
S3AI
 a| 
S3 테넌트 계정 ID(요청 발신자)
 a| 
요청을 보낸 사용자의 테넌트 계정 ID입니다.



 a| 
S3KY
 a| 
S3 키
 a| 
버킷 이름을 제외한 S3 키 이름입니다.

|===