---
permalink: audit/shea-s3-head.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SHEA, S3 HEAD 
summary: S3 클라이언트가 HEAD 트랜잭션을 실행하면 객체 또는 버킷의 존재 여부를 확인하고 객체에 대한 메타데이터를 검색하라는 요청이 이루어집니다.  이 메시지는 거래가 성공하면 서버에서 발행됩니다. 
---
= 시어: S3 헤드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 클라이언트가 HEAD 트랜잭션을 실행하면 객체 또는 버킷의 존재 여부를 확인하고 객체에 대한 메타데이터를 검색하라는 요청이 이루어집니다.  이 메시지는 거래가 성공하면 서버에서 발행됩니다.

[cols="1a,1a,4a"]
|===
| 암호 | 필드 | 설명 


 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
요청된 콘텐츠 블록의 고유 식별자입니다.  CBID를 알 수 없는 경우 이 필드는 0으로 설정됩니다.  버킷에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
CNID
 a| 
연결 식별자
 a| 
TCP/IP 연결을 위한 고유 시스템 식별자입니다.



 a| 
CSIZ
 a| 
콘텐츠 크기
 a| 
검사된 객체의 크기(바이트)입니다.  버킷에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
HTRH
 a| 
HTTP 요청 헤더
 a| 
구성 중에 선택한 기록된 HTTP 요청 헤더 이름과 값의 목록입니다.

 `X-Forwarded-For`요청에 존재하고 있는 경우 자동으로 포함됩니다. `X-Forwarded-For` 값이 요청 발신자 IP 주소(SAIP 감사 필드)와 다릅니다.



 a| 
RSLT
 a| 
결과 코드
 a| 
GET 트랜잭션의 결과.  결과는 항상 다음과 같습니다.

SUCS: 성공적



 a| 
S3AI
 a| 
S3 테넌트 계정 ID(요청 발신자)
 a| 
요청을 보낸 사용자의 테넌트 계정 ID입니다.  비어 있는 값은 익명 액세스를 나타냅니다.



 a| 
S3AK
 a| 
S3 액세스 키 ID(요청 발신자)
 a| 
요청을 보낸 사용자의 해시된 S3 액세스 키 ID입니다.  비어 있는 값은 익명 액세스를 나타냅니다.



 a| 
S3BK
 a| 
S3 버킷
 a| 
S3 버킷 이름.



 a| 
S3KY
 a| 
S3 키
 a| 
버킷 이름을 제외한 S3 키 이름입니다.  버킷에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
SACC
 a| 
S3 테넌트 계정 이름(요청 발신자)
 a| 
요청을 보낸 사용자의 테넌트 계정 이름입니다.  익명 요청은 비어 있습니다.



 a| 
SAIP
 a| 
IP 주소(요청 발신자)
 a| 
요청을 한 클라이언트 애플리케이션의 IP 주소입니다.



 a| 
SBAC
 a| 
S3 테넌트 계정 이름(버킷 소유자)
 a| 
버킷 소유자의 테넌트 계정 이름입니다.  계정 간 또는 익명 액세스를 식별하는 데 사용됩니다.



 a| 
SBAI
 a| 
S3 테넌트 계정 ID(버킷 소유자)
 a| 
대상 버킷 소유자의 테넌트 계정 ID입니다.  계정 간 또는 익명 액세스를 식별하는 데 사용됩니다.



 a| 
수르
 a| 
S3 사용자 URN(요청 발신자)
 a| 
테넌트 계정 ID와 요청을 하는 사용자의 사용자 이름입니다.  사용자는 로컬 사용자이거나 LDAP 사용자일 수 있습니다. 예:  `urn:sgws:identity::03393893651506583485:root`

익명 요청은 비어 있습니다.



 a| 
시간
 a| 
시간
 a| 
요청에 대한 총 처리 시간(마이크로초)입니다.



 a| 
티립
 a| 
신뢰할 수 있는 로드 밸런서 IP 주소
 a| 
요청이 신뢰할 수 있는 Layer 7 로드 밸런서를 통해 라우팅된 경우 로드 밸런서의 IP 주소입니다.



 a| 
UUID
 a| 
범용 고유 식별자
 a| 
StorageGRID 시스템 내의 객체 식별자입니다.



 a| 
VSID
 a| 
버전 ID
 a| 
요청된 객체의 특정 버전의 버전 ID입니다.  버전이 지정되지 않은 버킷의 버킷 및 객체에 대한 작업에는 이 필드가 포함되지 않습니다.

|===