---
permalink: audit/wdel-swift-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WDEL, Swift DELETE 
summary: Swift 클라이언트가 DELETE 트랜잭션을 실행하면 지정된 객체나 컨테이너를 제거하라는 요청이 이루어집니다.  이 메시지는 거래가 성공하면 서버에서 발행됩니다. 
---
= WDEL: 신속한 삭제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Swift 클라이언트가 DELETE 트랜잭션을 실행하면 지정된 객체나 컨테이너를 제거하라는 요청이 이루어집니다.  이 메시지는 거래가 성공하면 서버에서 발행됩니다.

[cols="1a,1a,4a"]
|===
| 암호 | 필드 | 설명 


 a| 
CBID
 a| 
콘텐츠 블록 식별자
 a| 
요청된 콘텐츠 블록의 고유 식별자입니다.  CBID를 알 수 없는 경우 이 필드는 0으로 설정됩니다.  컨테이너에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
CSIZ
 a| 
콘텐츠 크기
 a| 
삭제된 객체의 크기(바이트)입니다.  컨테이너에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
HTRH
 a| 
HTTP 요청 헤더
 a| 
구성 중에 선택한 기록된 HTTP 요청 헤더 이름과 값의 목록입니다.

 `X-Forwarded-For`요청에 존재하고 있는 경우 자동으로 포함됩니다. `X-Forwarded-For` 값이 요청 발신자 IP 주소(SAIP 감사 필드)와 다릅니다.



 a| 
MTME
 a| 
마지막 수정 시간
 a| 
개체가 마지막으로 수정된 시간을 나타내는 마이크로초 단위의 Unix 타임스탬프입니다.



 a| 
RSLT
 a| 
결과 코드
 a| 
DELETE 트랜잭션의 결과입니다.  결과는 항상 다음과 같습니다.

SUCS: 성공적



 a| 
SAIP
 a| 
요청 클라이언트의 IP 주소
 a| 
요청을 한 클라이언트 애플리케이션의 IP 주소입니다.



 a| 
SGRP
 a| 
사이트(그룹)
 a| 
해당 사이트가 존재하는 경우, 해당 사이트에서 개체가 삭제되었으며, 해당 사이트는 개체가 수집된 사이트가 아닙니다.



 a| 
시간
 a| 
시간
 a| 
요청에 대한 총 처리 시간(마이크로초)입니다.



 a| 
티립
 a| 
신뢰할 수 있는 로드 밸런서 IP 주소
 a| 
요청이 신뢰할 수 있는 Layer 7 로드 밸런서를 통해 라우팅된 경우 로드 밸런서의 IP 주소입니다.



 a| 
UUID
 a| 
범용 고유 식별자
 a| 
StorageGRID 시스템 내의 객체 식별자입니다.



 a| 
WACC
 a| 
Swift 계정 ID
 a| 
StorageGRID 시스템에서 지정한 고유한 계정 ID입니다.



 a| 
WCON
 a| 
스위프트 컨테이너
 a| 
Swift 컨테이너 이름.



 a| 
와브제이
 a| 
Swift 객체
 a| 
Swift 객체 식별자.  컨테이너에 대한 작업에는 이 필드가 포함되지 않습니다.



 a| 
WUSR
 a| 
Swift 계정 사용자
 a| 
거래를 수행하는 클라이언트를 고유하게 식별하는 Swift 계정 사용자 이름입니다.

|===