---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 11.9은 Grid Management API 버전 4를 사용합니다. 버전 4에서는 버전 3이 더 이상 사용되지 않지만, 버전 1, 2, 3은 계속 지원됩니다. 
---
= 그리드 관리 API 변경 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.9은 Grid Management API 버전 4를 사용합니다. 버전 4에서는 버전 3이 더 이상 사용되지 않지만, 버전 1, 2, 3은 계속 지원됩니다.


NOTE: StorageGRID 11.9에서는 더 이상 사용되지 않는 관리 API 버전을 계속 사용할 수 있습니다. 그러나 이러한 버전의 API에 대한 지원은 StorageGRID 의 향후 릴리스에서 제거될 예정입니다. StorageGRID 11.9으로 업그레이드한 후에는 다음을 사용하여 더 이상 사용되지 않는 API를 비활성화할 수 있습니다. `PUT /grid/config/management` API.

자세한 내용을 알아보려면 다음으로 이동하세요.link:../admin/using-grid-management-api.html["그리드 관리 API 사용"] .



== 글로벌 S3 개체 잠금을 활성화한 후 규정 준수 설정을 검토하세요.

글로벌 S3 개체 잠금 설정을 활성화한 후 기존 테넌트의 규정 준수 설정을 검토합니다.  이 설정을 활성화하면 테넌트별 S3 개체 잠금 설정은 테넌트가 생성된 시점의 StorageGRID 릴리스에 따라 달라집니다.



== 레거시 mgmt-api 요청이 제거되었습니다.

다음 레거시 요청은 제거되었습니다.

`/grid/server-types`

`/grid/ntp-roles`



== 변경 사항 `GET /private/storage-usage` API

* 새로운 부동산, `usageCacheDuration` 응답 본문에 ,가 추가되었습니다.  이 속성은 사용 조회 캐시가 유효한 기간(초)을 지정합니다.  이 값은 테넌트 스토리지 할당량 및 버킷 용량 한도에 대한 사용량을 확인할 때 적용됩니다.
* 그만큼 `GET /api/v4/private/storage-usage` 스키마의 중첩과 일치하도록 동작이 수정되었습니다.
* 이러한 변경 사항은 비공개 API에만 적용됩니다.




== 변경 사항 `GET cross-grid-replication` API

*/org/containers/:name/cross-grid-replication* GET API에는 더 이상 루트 액세스가 필요하지 않습니다.(`rootAccess` ) 권한이 있어야 합니다. 그러나 모든 버킷 관리 권한이 있는 사용자 그룹에 속해야 합니다.(`manageAllContainers` ) 또는 모든 버킷 보기(`viewAllContainers` ) 허가.

*/org/containers/:name/cross-grid-replication* PUT API는 변경되지 않았으며 여전히 루트 액세스가 필요합니다.(`rootAccess` ) 허가.
