---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: StorageGRID 시스템을 업그레이드하기 전에 시스템이 업그레이드를 수용할 준비가 되었는지 확인하세요.  시스템이 정상적으로 실행되고 모든 그리드 노드가 작동하는지 확인하세요. 
---
= 시스템 상태를 확인하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템을 업그레이드하기 전에 시스템이 업그레이드를 수용할 준비가 되었는지 확인하세요.  시스템이 정상적으로 실행되고 모든 그리드 노드가 작동하는지 확인하세요.

.단계
. 다음을 사용하여 Grid Manager에 Sign in.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
. 활성 경고를 확인하고 해결합니다.
. 충돌하는 그리드 작업이 활성화되어 있거나 보류 중인지 확인하세요.
+
.. *지원* > *도구* > *그리드 토폴로지*를 선택하세요.
.. *_site_* > *_primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*을 선택합니다.
+
정보 수명 주기 관리 평가(ILME) 작업은 소프트웨어 업그레이드와 동시에 실행할 수 있는 유일한 그리드 작업입니다.

.. 다른 그리드 작업이 활성화되어 있거나 보류 중인 경우 해당 작업이 완료될 때까지 기다리거나 잠금을 해제하세요.
+

NOTE: 작업이 완료되지 않거나 잠금이 해제되지 않으면 기술 지원팀에 문의하세요.



. 참조하다link:../network/internal-grid-node-communications.html["내부 그리드 노드 통신"] 그리고link:../network/external-communications.html["외부 커뮤니케이션"] 업그레이드하기 전에 StorageGRID 11.9에 필요한 모든 포트가 열려 있는지 확인하세요.
+

NOTE: StorageGRID 11.9으로 업그레이드할 때 추가 포트는 필요하지 않습니다.

+
StorageGRID 11.7에는 다음과 같은 필수 포트가 추가되었습니다.  StorageGRID 11.9로 업그레이드하기 전에 해당 기능이 사용 가능한지 확인하세요.

+
[cols="1a,2a"]
|===
| 포트 | 설명 


 a| 
18086
 a| 
StorageGRID 로드 밸런서에서 LDR 및 새로운 LDR 서비스로의 S3 요청에 사용되는 TCP 포트입니다.

업그레이드하기 전에 모든 그리드 노드에서 모든 스토리지 노드로 이 포트가 열려 있는지 확인하세요.

이 포트를 차단하면 StorageGRID 11.9로 업그레이드한 후 S3 서비스가 중단됩니다.

|===



CAUTION: 사용자 지정 방화벽 포트를 열었다면 업그레이드 사전 검사 중에 알림이 표시됩니다.  업그레이드를 진행하기 전에 기술 지원팀에 문의해야 합니다.
