---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 업그레이드에 걸리는 시간을 고려하여 언제 업그레이드할지 고려하세요.  업그레이드의 각 단계에서 수행할 수 있는 작업과 수행할 수 없는 작업을 알아두세요. 
---
= 업그레이드 완료 시간 예상
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드에 걸리는 시간을 고려하여 언제 업그레이드할지 고려하세요.  업그레이드의 각 단계에서 수행할 수 있는 작업과 수행할 수 없는 작업을 알아두세요.

.이 작업에 관하여
StorageGRID 업그레이드를 완료하는 데 필요한 시간은 클라이언트 부하와 하드웨어 성능 등 다양한 요인에 따라 달라집니다.

이 표는 주요 업그레이드 작업을 요약하고 각 작업에 필요한 대략적인 시간을 나열합니다.  표 다음에 나오는 단계에서는 시스템 업그레이드 시간을 추정하는 데 사용할 수 있는 지침을 제공합니다.

[cols="1a,2a,2a,4a"]
|===
| 업그레이드 작업 | 설명 | 대략적인 소요 시간 | 이 작업 동안 


 a| 
사전 검사를 실행하고 기본 관리 노드를 업그레이드합니다.
 a| 
업그레이드 사전 검사가 실행되고, 기본 관리 노드가 중지되고, 업그레이드되고, 다시 시작됩니다.
 a| 
30분에서 1시간 정도 소요되며, 서비스 어플라이언스 노드에 가장 많은 시간이 소요됩니다.

해결되지 않은 사전 확인 오류는 이번에는 증가합니다.
 a| 
기본 관리 노드에 액세스할 수 없습니다.  연결 오류가 보고될 수 있지만 무시해도 됩니다.

업그레이드를 시작하기 전에 업그레이드 사전 검사를 실행하면 예약된 업그레이드 유지 관리 기간 전에 오류를 해결할 수 있습니다.



 a| 
업그레이드 서비스 시작
 a| 
소프트웨어 파일이 배포되고 업그레이드 서비스가 시작됩니다.
 a| 
그리드 노드당 3분
 a| 



 a| 
다른 그리드 노드 업그레이드
 a| 
다른 모든 그리드 노드의 소프트웨어는 노드를 승인한 순서대로 업그레이드됩니다.  시스템의 모든 노드는 한 번에 하나씩 다운됩니다.
 a| 
노드당 15분~1시간 소요, 어플라이언스 노드가 가장 많은 시간을 필요로 함

*참고*: 어플라이언스 노드의 경우 StorageGRID Appliance Installer가 최신 릴리스로 자동 업데이트됩니다.
 a| 
* 그리드 구성을 변경하지 마세요.
* 감사 수준 구성을 변경하지 마세요.
* ILM 구성을 업데이트하지 마세요.
* 핫픽스, 해체, 확장 등의 다른 유지 관리 절차를 수행할 수 없습니다.


*참고*: 복구를 수행해야 하는 경우 기술 지원팀에 문의하세요.



 a| 
기능 활성화
 a| 
새로운 버전의 새로운 기능이 활성화되었습니다.
 a| 
5분 이내
 a| 
* 그리드 구성을 변경하지 마세요.
* 감사 수준 구성을 변경하지 마세요.
* ILM 구성을 업데이트하지 마세요.
* 다른 유지관리 절차를 수행할 수 없습니다.




 a| 
데이터베이스 업그레이드
 a| 
업그레이드 프로세스에서는 각 노드를 검사하여 Cassandra 데이터베이스를 업데이트할 필요가 없는지 확인합니다.
 a| 
노드당 10초 또는 전체 그리드의 경우 몇 분
 a| 
StorageGRID 11.8에서 11.9로 업그레이드하는 데 Cassandra 데이터베이스 업그레이드는 필요하지 않습니다. 하지만 각 스토리지 노드에서 Cassandra 서비스가 중지되었다가 다시 시작됩니다.

향후 StorageGRID 기능 릴리스에서는 Cassandra 데이터베이스 업데이트 단계를 완료하는 데 며칠이 걸릴 수 있습니다.



 a| 
최종 업그레이드 단계
 a| 
임시 파일이 제거되고 새로운 릴리스로의 업그레이드가 완료됩니다.
 a| 
5분
 a| 
*최종 업그레이드 단계* 작업이 완료되면 모든 유지 관리 절차를 수행할 수 있습니다.

|===
.단계
. 모든 그리드 노드를 업그레이드하는 데 필요한 시간을 추정해 보세요.
+
.. StorageGRID 시스템의 노드 수에 1시간/노드를 곱합니다.
+
일반적으로 어플라이언스 노드는 소프트웨어 기반 노드보다 업그레이드하는 데 시간이 더 오래 걸립니다.

.. 다운로드에 필요한 시간을 고려하여 이 시간에 1시간을 더합니다. `.upgrade` 파일을 열고, 사전 검증을 실행하고, 최종 업그레이드 단계를 완료합니다.


. Linux 노드가 있는 경우 RPM 또는 DEB 패키지를 다운로드하고 설치하는 데 필요한 시간을 고려하여 노드당 15분을 추가하세요.
. 1단계와 2단계의 결과를 더하여 업그레이드에 걸리는 총 예상 시간을 계산합니다.




== 예: StorageGRID 11.9으로 업그레이드하는 데 걸리는 예상 시간

시스템에 14개의 그리드 노드가 있고 그 중 8개가 Linux 노드라고 가정해 보겠습니다.

. 14를 1시간/노드에 곱합니다.
. 다운로드, 사전 확인, 최종 단계를 고려하여 1시간을 추가하세요.
+
모든 노드를 업그레이드하는 데 걸리는 예상 시간은 15시간입니다.

. Linux 노드에 RPM이나 DEB 패키지를 설치하는 데 걸리는 시간을 고려해서 노드당 15분에 8을 곱합니다.
+
이 단계의 예상 시간은 2시간입니다.

. 값을 모두 더합니다.
+
시스템을 StorageGRID 11.9.0으로 업그레이드하는 데 최대 17시간이 걸릴 수 있습니다.




NOTE: 필요에 따라 그리드 노드의 하위 집합을 여러 세션으로 업그레이드하도록 승인하여 유지 관리 기간을 더 작은 기간으로 나눌 수 있습니다.  예를 들어, 한 세션에서 사이트 A의 노드를 업그레이드한 다음, 이후 세션에서 사이트 B의 노드를 업그레이드하는 것을 선호할 수 있습니다.  두 개 이상의 세션에 걸쳐 업그레이드를 수행하도록 선택한 경우 모든 노드가 업그레이드될 때까지 새로운 기능을 사용할 수 없다는 점에 유의하세요.
