---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 업그레이드 중에 StorageGRID 시스템에 어떤 영향이 미치는지 알아보세요. 
---
= 업그레이드 중 시스템에 미치는 영향
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드 중에 StorageGRID 시스템에 어떤 영향이 미치는지 알아보세요.



== StorageGRID 업그레이드는 중단 없이 진행됩니다.

StorageGRID 시스템은 업그레이드 프로세스 전반에 걸쳐 클라이언트 애플리케이션에서 데이터를 수집하고 검색할 수 있습니다.  동일한 유형의 모든 노드(예: 스토리지 노드)의 업그레이드를 승인하면 노드가 하나씩 다운되므로 모든 그리드 노드 또는 특정 유형의 모든 그리드 노드를 사용할 수 없는 상황이 발생하지 않습니다.

지속적인 가용성을 위해 ILM 정책에 각 개체의 여러 사본을 저장하도록 지정하는 규칙이 포함되어 있는지 확인하세요.  또한 모든 외부 S3 클라이언트가 다음 중 하나에 요청을 보내도록 구성되어 있는지 확인해야 합니다.

* 고가용성(HA) 그룹 가상 IP 주소
* 고가용성 타사 로드 밸런서
* 각 클라이언트에 대한 다중 게이트웨이 노드
* 각 클라이언트에 대한 여러 스토리지 노드




== 클라이언트 애플리케이션은 단기적인 중단을 경험할 수 있습니다.

StorageGRID 시스템은 업그레이드 프로세스 전반에 걸쳐 클라이언트 애플리케이션에서 데이터를 수집하고 검색할 수 있습니다. 그러나 업그레이드를 위해 해당 노드에서 서비스를 다시 시작해야 하는 경우 개별 게이트웨이 노드 또는 스토리지 노드에 대한 클라이언트 연결이 일시적으로 중단될 수 있습니다.  업그레이드 프로세스가 완료되고 각 노드에서 서비스가 재개되면 연결이 복구됩니다.

짧은 기간 동안 연결이 끊어지는 것이 용납될 수 없다면 업그레이드를 적용하기 위해 가동 중지 시간을 예약해야 할 수도 있습니다.  선택적 승인을 사용하면 특정 노드가 업데이트되는 시기를 예약할 수 있습니다.


NOTE: 업그레이드 프로세스 중에 자동 장애 조치를 제공하기 위해 여러 게이트웨이와 고가용성(HA) 그룹을 사용할 수 있습니다. 지침을 참조하세요link:../admin/configure-high-availability-group.html["고가용성 그룹 구성"] .



== 기기 펌웨어가 업그레이드되었습니다.

StorageGRID 11.9 업그레이드 중:

* 모든 StorageGRID 어플라이언스 노드는 StorageGRID Appliance Installer 펌웨어 버전 3.9으로 자동 업그레이드됩니다.
* SG6060 및 SGF6024 기기는 BIOS 펌웨어 버전 3B08.EX 및 BMC 펌웨어 버전 4.00.07로 자동 업그레이드됩니다.
* SG100 및 SG1000 기기는 BIOS 펌웨어 버전 3B13.EC 및 BMC 펌웨어 버전 4.74.07로 자동 업그레이드됩니다.
* SGF6112, SG6160, SG110 및 SG1100 어플라이언스는 BMC 펌웨어 버전 3.16.07로 자동 업그레이드됩니다.




== ILM 정책은 상태에 따라 다르게 처리됩니다.

* 업그레이드 후에도 활성 정책은 동일하게 유지됩니다.
* 업그레이드 시 최신 10개의 역사적 정책만 보존됩니다.
* 제안된 정책이 있는 경우 업그레이드 중에 삭제됩니다.




== 경고가 발생할 수 있습니다

서비스가 시작되고 중지될 때, 그리고 StorageGRID 시스템이 혼합 버전 환경(일부 그리드 노드는 이전 버전을 실행하고 다른 노드는 이후 버전으로 업그레이드됨)으로 작동할 때 경고가 발생할 수 있습니다.  업그레이드가 완료된 후 다른 알림이 발생할 수 있습니다.

예를 들어, 서비스가 중지되면 *노드와 통신할 수 없습니다* 경고가 표시될 수 있고, 일부 노드가 StorageGRID 11.9으로 업그레이드되었지만 다른 노드는 여전히 StorageGRID 11.8를 실행 중인 경우 *Cassandra 통신 오류* 경고가 표시될 수 있습니다. 일반적으로 이러한 알림은 업그레이드가 완료되면 사라집니다.

StorageGRID 11.9으로 업그레이드하는 동안 스토리지 노드가 중지되면 *ILM 배치 불가* 경고가 발생할 수 있습니다. 이 알림은 업그레이드가 완료된 후 1일 동안 지속될 수 있습니다.

업그레이드가 완료되면 Grid Manager 대시보드에서 *최근 해결된 알림* 또는 *현재 알림*을 선택하여 업그레이드 관련 알림을 검토할 수 있습니다.



== 많은 SNMP 알림이 생성됩니다.

업그레이드 중에 그리드 노드가 중지되었다가 다시 시작되면 많은 수의 SNMP 알림이 생성될 수 있다는 점에 유의하세요.  과도한 알림을 피하려면 업그레이드를 시작하기 전에 SNMP 알림을 비활성화하려면 *SNMP 에이전트 알림 사용* 체크박스(*구성* > *모니터링* > *SNMP 에이전트*)를 선택 취소하세요.  업그레이드가 완료된 후 알림을 다시 활성화하세요.



== 구성 변경이 제한됩니다.


NOTE: 이 목록은 StorageGRID 11.8에서 StorageGRID 11.9으로 업그레이드하는 경우에만 적용됩니다. 다른 StorageGRID 릴리스로 업그레이드하는 경우 해당 릴리스의 업그레이드 지침에서 제한된 변경 사항 목록을 참조하세요.

*새로운 기능 활성화* 작업이 완료될 때까지:

* 그리드 구성을 변경하지 마세요.
* 새로운 기능을 활성화하거나 비활성화하지 마세요.
* ILM 구성을 업데이트하지 마세요.  그렇지 않으면 일관되지 않고 예상치 못한 ILM 동작이 발생할 수 있습니다.
* 핫픽스를 적용하거나 그리드 노드를 복구하지 마세요.
+

NOTE: 업그레이드 중에 노드를 복구해야 하는 경우 기술 지원팀에 문의하세요.

* StorageGRID 11.9으로 업그레이드하는 동안 HA 그룹, VLAN 인터페이스 또는 로드 밸런서 엔드포인트를 관리해서는 안 됩니다.
* StorageGRID 11.9으로의 업그레이드가 완료될 때까지 HA 그룹을 삭제하지 마세요. 다른 HA 그룹의 가상 IP 주소에 액세스하지 못할 수 있습니다.


*최종 업그레이드 단계* 작업이 완료될 때까지:

* 확장 절차를 수행하지 마세요.
* 해체 절차를 수행하지 마세요.




== 테넌트 관리자에서 버킷 세부 정보를 보거나 버킷을 관리할 수 없습니다.

StorageGRID 11.9로 업그레이드하는 동안(즉, 시스템이 혼합 버전 환경으로 작동하는 동안) 테넌트 관리자를 사용하여 버킷 세부 정보를 보거나 버킷을 관리할 수 없습니다.  테넌트 관리자의 버킷 페이지에 다음 오류 중 하나가 나타납니다.

* 11.9로 업그레이드하는 동안에는 이 API를 사용할 수 없습니다.
* 11.9로 업그레이드하는 동안에는 테넌트 관리자에서 버킷 버전 세부 정보를 볼 수 없습니다.


이 오류는 11.9로 업그레이드가 완료되면 해결됩니다.

.해결 방법
11.9 업그레이드가 진행되는 동안 테넌트 관리자를 사용하는 대신 다음 도구를 사용하여 버킷 세부 정보를 보거나 버킷을 관리하세요.

* 버킷에서 표준 S3 작업을 수행하려면 다음 중 하나를 사용하세요.link:../s3/operations-on-buckets.html["S3 REST API"] 또는link:../tenant/understanding-tenant-management-api.html["테넌트 관리 API"] .
* 버킷에서 StorageGRID 사용자 지정 작업을 수행하려면(예: 버킷 일관성 보기 및 수정, 마지막 액세스 시간 업데이트 활성화 또는 비활성화, 검색 통합 구성) 테넌트 관리 API를 사용합니다.

