---
permalink: upgrade/performing-upgrade.html 
sidebar: sidebar 
keywords: upgrade, how to perform a software upgrade 
summary: StorageGRID 11.9으로 업그레이드하고 동시에 해당 릴리스의 최신 핫픽스를 적용할 수 있습니다. StorageGRID 업그레이드 페이지는 권장 업그레이드 경로를 제공하고 해당 다운로드 페이지로 직접 연결됩니다. 
---
= 업그레이드를 수행하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11.9으로 업그레이드하고 동시에 해당 릴리스의 최신 핫픽스를 적용할 수 있습니다. StorageGRID 업그레이드 페이지는 권장 업그레이드 경로를 제공하고 해당 다운로드 페이지로 직접 연결됩니다.

.시작하기 전에
모든 고려 사항을 검토하고 모든 계획 및 준비 단계를 완료했습니다.



== StorageGRID 업그레이드 페이지에 접속하세요

첫 번째 단계로, Grid Manager에서 StorageGRID 업그레이드 페이지에 액세스하세요.

.단계
. 다음을 사용하여 Grid Manager에 Sign in.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
. *유지관리* > *시스템* > *소프트웨어 업데이트*를 선택하세요.
. StorageGRID 업그레이드 타일에서 *업그레이드*를 선택합니다.




== 파일 선택

StorageGRID 업그레이드 페이지의 업데이트 경로는 최신 StorageGRID 릴리스를 받기 위해 설치해야 하는 주요 버전(예: 11.9.0)과 핫픽스(예: 11.9.0.1)를 나타냅니다. 표시된 순서대로 권장 버전과 핫픽스를 설치해야 합니다.


TIP: 업데이트 경로가 표시되지 않으면 브라우저가 NetApp 지원 사이트에 액세스할 수 없거나 AutoSupport 페이지(*지원* > *도구* > * AutoSupport* > *설정*)의 *소프트웨어 업데이트 확인* 확인란이 비활성화되어 있을 수 있습니다.

.단계
. *파일 선택* 단계에서 업데이트 경로를 검토하세요.
. 파일 다운로드 섹션에서 각 *다운로드* 링크를 선택하여 NetApp 지원 사이트에서 필요한 파일을 다운로드합니다.
+
업데이트 경로가 표시되지 않으면 다음으로 이동하세요. https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^] 새로운 버전이나 핫픽스가 있는지 확인하고 필요한 파일을 다운로드하세요.

+

NOTE: 모든 Linux 호스트에 RPM이나 DEB 패키지를 다운로드하여 설치해야 하는 경우 업데이트 경로에 StorageGRID 업그레이드 및 핫픽스 파일이 이미 나열되어 있을 수 있습니다.

. *찾아보기*를 선택하여 버전 업그레이드 파일을 StorageGRID 에 업로드합니다. `NetApp_StorageGRID_11.9.0_Software_uniqueID.upgrade`
+
업로드 및 검증 과정이 완료되면 파일 이름 옆에 녹색 확인 표시가 나타납니다.

. 핫픽스 파일을 다운로드한 경우 *찾아보기*를 선택하여 해당 파일을 업로드합니다.  핫픽스는 버전 업그레이드의 일부로 자동으로 적용됩니다.
. *계속*을 선택하세요.




== 사전 검사 실행

사전 검사를 실행하면 그리드 업그레이드를 시작하기 전에 업그레이드 문제를 감지하고 해결할 수 있습니다.

.단계
. *사전 검사 실행* 단계에서는 그리드의 프로비저닝 암호를 입력하여 시작합니다.
. *복구 패키지 다운로드*를 선택하세요.
+
기본 관리 노드를 업그레이드하기 전에 복구 패키지 파일의 최신 사본을 다운로드해야 합니다.  복구 패키지 파일을 사용하면 장애가 발생할 경우 시스템을 복원할 수 있습니다.

. 파일이 다운로드되면 다음을 포함한 콘텐츠에 액세스할 수 있는지 확인하세요. `Passwords.txt` 파일.
. 다운로드한 파일을 복사하세요(`.zip` ) 두 개의 안전하고 보안이 유지되는 별도 장소로 이동합니다.
+

CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 얻는 데 사용할 수 있는 암호화 키와 비밀번호가 포함되어 있으므로 보호되어야 합니다.

. *사전 검사 실행*을 선택하고 사전 검사가 완료될 때까지 기다립니다.
. 보고된 각 사전 점검에 대한 세부 정보를 검토하고 보고된 오류를 해결합니다. 를 참조하십시오 https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["StorageGRID 소프트웨어 업그레이드 해결 가이드"^] StorageGRID 11.9 릴리스에 대한 내용입니다.
+
시스템을 업그레이드하기 전에 모든 사전 검사 오류를 해결해야 합니다.  하지만 업그레이드하기 전에 사전 확인 경고를 처리할 필요는 없습니다.

+

CAUTION: 사용자 지정 방화벽 포트를 열었다면 사전 확인 검증 중에 알림을 받게 됩니다.  업그레이드를 진행하기 전에 기술 지원팀에 문의해야 합니다.

. 보고된 문제를 해결하기 위해 구성을 변경한 경우, *사전 검사 실행*을 다시 선택하면 업데이트된 결과를 얻을 수 있습니다.
+
모든 오류가 해결되면 업그레이드를 시작하라는 메시지가 표시됩니다.





== 업그레이드 시작 및 기본 관리 노드 업그레이드

업그레이드를 시작하면 업그레이드 사전 검사가 다시 실행되고 기본 관리 노드가 자동으로 업그레이드됩니다.  업그레이드의 이 부분은 최대 30분이 걸릴 수 있습니다.


NOTE: 기본 관리 노드가 업그레이드되는 동안에는 다른 Grid Manager 페이지에 액세스할 수 없습니다.  감사 로그도 사용할 수 없습니다.

.단계
. *업그레이드 시작*을 선택하세요.
+
그리드 관리자에 대한 액세스가 일시적으로 상실된다는 경고가 나타납니다.

. 경고를 확인하고 업그레이드를 시작하려면 *확인*을 선택하세요.
. 업그레이드 사전 검사가 수행되고 기본 관리 노드가 업그레이드될 때까지 기다리세요.
+

NOTE: 사전 확인 오류가 보고되면 오류를 해결하고 *업그레이드 시작*을 다시 선택하세요.

+
그리드에 온라인 상태이고 준비된 다른 관리 노드가 있는 경우, 이를 사용하여 기본 관리 노드의 상태를 모니터링할 수 있습니다.  기본 관리 노드가 업그레이드되면 다른 그리드 노드를 승인할 수 있습니다.

. 필요에 따라 *계속*을 선택하여 *다른 노드 업그레이드* 단계에 액세스합니다.




== 다른 노드 업그레이드

모든 그리드 노드를 업그레이드해야 하지만, 여러 업그레이드 세션을 수행하고 업그레이드 순서를 사용자 지정할 수 있습니다.  예를 들어, 한 세션에서 사이트 A의 노드를 업그레이드한 다음, 이후 세션에서 사이트 B의 노드를 업그레이드하는 것을 선호할 수 있습니다.  두 개 이상의 세션에 걸쳐 업그레이드를 수행하도록 선택한 경우 모든 노드가 업그레이드될 때까지 새로운 기능을 사용할 수 없다는 점에 유의하세요.

노드가 업그레이드되는 순서가 중요한 경우, 노드나 노드 그룹을 하나씩 승인하고 각 노드에서 업그레이드가 완료될 때까지 기다린 후 다음 노드나 노드 그룹을 승인합니다.


NOTE: 그리드 노드에서 업그레이드가 시작되면 해당 노드의 서비스가 중지됩니다.  나중에 그리드 노드가 재부팅됩니다.  노드와 통신하는 클라이언트 애플리케이션의 서비스 중단을 방지하려면 노드를 중지하고 재부팅할 준비가 되었는지 확인하기 전까지는 노드 업그레이드를 승인하지 마세요.  필요에 따라 유지 관리 기간을 예약하거나 고객에게 알립니다.

.단계
. *다른 노드 업그레이드* 단계의 경우, 업그레이드 전체의 시작 시간과 각 주요 업그레이드 작업의 상태를 제공하는 요약을 검토하세요.
+
** *업그레이드 서비스 시작*은 첫 번째 업그레이드 작업입니다.  이 작업 동안 소프트웨어 파일이 그리드 노드에 배포되고, 각 노드에서 업그레이드 서비스가 시작됩니다.
** *업그레이드 서비스 시작* 작업이 완료되면 *다른 그리드 노드 업그레이드* 작업이 시작되고 복구 패키지의 새 사본을 다운로드하라는 메시지가 표시됩니다.


. 메시지가 표시되면 프로비저닝 암호를 입력하고 복구 패키지의 새 사본을 다운로드합니다.
+

CAUTION: 기본 관리 노드를 업그레이드한 후 복구 패키지 파일의 새 사본을 다운로드해야 합니다.  복구 패키지 파일을 사용하면 장애가 발생할 경우 시스템을 복원할 수 있습니다.

. 각 노드 유형에 대한 상태 표를 검토하세요.  기본이 아닌 관리 노드, 게이트웨이 노드, 스토리지 노드에 대한 표가 있습니다.
+
표가 처음 나타날 때 그리드 노드는 다음 단계 중 하나에 있을 수 있습니다.

+
** 업그레이드 풀기
** 다운로드 중
** 승인을 기다리는 중


. [[approval-step]]업그레이드할 그리드 노드를 선택할 준비가 되면(또는 선택한 노드의 승인을 취소해야 하는 경우) 다음 지침을 따르세요.
+
[cols="1a,1a"]
|===
| 일 | 지침 


 a| 
특정 사이트의 모든 노드 등 승인할 특정 노드를 검색합니다.
 a| 
*검색* 필드에 검색 문자열을 입력하세요



 a| 
업그레이드할 모든 노드를 선택하세요
 a| 
*모든 노드 승인*을 선택하세요



 a| 
업그레이드를 위해 동일한 유형의 모든 노드를 선택합니다(예: 모든 스토리지 노드)
 a| 
노드 유형에 대해 *모두 승인* 버튼을 선택하세요

동일한 유형의 노드를 두 개 이상 승인하면 노드가 한 번에 하나씩 업그레이드됩니다.



 a| 
업그레이드할 개별 노드를 선택하세요
 a| 
노드에 대해 *승인* 버튼을 선택하세요



 a| 
선택한 모든 노드에서 업그레이드를 연기합니다.
 a| 
*모든 노드 승인 취소*를 선택하세요



 a| 
동일한 유형의 모든 선택된 노드에서 업그레이드를 연기합니다.
 a| 
노드 유형에 대해 *모두 승인 취소* 버튼을 선택하세요.



 a| 
개별 노드에서 업그레이드 연기
 a| 
노드에 대해 *승인 취소* 버튼을 선택하세요

|===
. 승인된 노드가 다음 업그레이드 단계를 거칠 때까지 기다리세요.
+
** 승인되었으며 업그레이드 대기 중입니다.
** 서비스 중지
+

NOTE: 스테이지가 *서비스 중지*에 도달하면 노드를 제거할 수 없습니다.  *승인 취소* 버튼이 비활성화되었습니다.

** 컨테이너 정지
** Docker 이미지 정리
** 기본 OS 패키지 업그레이드
+

NOTE: 어플라이언스 노드가 이 단계에 도달하면 어플라이언스의 StorageGRID Appliance Installer 소프트웨어가 업데이트됩니다.  이 자동화된 프로세스는 StorageGRID Appliance Installer 버전이 StorageGRID 소프트웨어 버전과 동기화된 상태를 유지하도록 보장합니다.

** 재부팅 중
+

NOTE: 일부 기기 모델은 펌웨어와 BIOS를 업그레이드하기 위해 여러 번 재부팅될 수 있습니다.

** 재부팅 후 단계 수행
** 서비스 시작
** 완료


. 반복하다<<approval-step,승인 단계>> 모든 그리드 노드가 업그레이드될 때까지 필요한 만큼 반복합니다.




== 업그레이드 완료

모든 그리드 노드가 업그레이드 단계를 완료하면 *다른 그리드 노드 업그레이드* 작업이 완료로 표시됩니다.  나머지 업그레이드 작업은 백그라운드에서 자동으로 수행됩니다.

.단계
. *기능 활성화* 작업이 완료되면(빠르게 완료됨) 사용을 시작할 수 있습니다.link:whats-new.html["새로운 기능"] 업그레이드된 StorageGRID 버전에서.
. *데이터베이스 업그레이드* 작업 중에 업그레이드 프로세스는 각 노드를 검사하여 Cassandra 데이터베이스를 업데이트할 필요가 없는지 확인합니다.
+

NOTE: StorageGRID 11.8에서 11.9로 업그레이드하는 데 Cassandra 데이터베이스 업그레이드는 필요하지 않습니다. 하지만 각 스토리지 노드에서 Cassandra 서비스가 중지되었다가 다시 시작됩니다.  향후 StorageGRID 기능 릴리스에서는 Cassandra 데이터베이스 업데이트 단계를 완료하는 데 며칠이 걸릴 수 있습니다.

. *데이터베이스 업그레이드* 작업이 완료되면 *최종 업그레이드 단계*가 완료될 때까지 몇 분간 기다리세요.
. *최종 업그레이드 단계*가 완료되면 업그레이드가 완료됩니다.  첫 번째 단계인 *파일 선택*이 녹색 성공 배너와 함께 다시 표시됩니다.
. 그리드 작업이 정상으로 돌아왔는지 확인하세요.
+
.. 서비스가 정상적으로 작동하는지, 예상치 못한 알림이 없는지 확인하세요.
.. StorageGRID 시스템에 대한 클라이언트 연결이 예상대로 작동하는지 확인합니다.



