---
permalink: upgrade/troubleshooting-upgrade-issues.html 
sidebar: sidebar 
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck 
summary: 업그레이드를 수행하는 동안 문제가 발생하면 직접 문제를 해결할 수 있습니다.  문제를 해결할 수 없는 경우 가능한 한 많은 정보를 수집한 다음 기술 지원팀에 문의하세요. 
---
= 업그레이드 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드를 수행하는 동안 문제가 발생하면 직접 문제를 해결할 수 있습니다.  문제를 해결할 수 없는 경우 가능한 한 많은 정보를 수집한 다음 기술 지원팀에 문의하세요.



== 업그레이드가 완료되지 않습니다

다음 섹션에서는 업그레이드가 부분적으로 실패한 상황에서 복구하는 방법을 설명합니다.



=== 업그레이드 사전 확인 오류

문제를 감지하고 해결하려면 실제 업그레이드를 시작하기 전에 업그레이드 사전 검사를 수동으로 실행할 수 있습니다.  대부분의 사전 확인 오류는 문제를 해결하는 방법에 대한 정보를 제공합니다.



=== 프로비저닝 실패

자동 프로비저닝 프로세스가 실패하면 기술 지원팀에 문의하세요.



=== 그리드 노드가 충돌하거나 시작에 실패합니다.

업그레이드 프로세스 중에 그리드 노드가 충돌하거나 업그레이드가 완료된 후 성공적으로 시작되지 않으면 기술 지원팀에 문의하여 조사하고 근본적인 문제를 수정하세요.



=== 데이터 수집 또는 검색이 중단되었습니다.

그리드 노드를 업그레이드하지 않을 때 데이터 수집이나 검색이 예기치 않게 중단되면 기술 지원팀에 문의하세요.



=== 데이터베이스 업그레이드 오류

데이터베이스 업그레이드가 오류로 인해 실패하면 업그레이드를 다시 시도하세요.  다시 실패하면 기술 지원팀에 문의하세요.

.관련 정보
link:checking-systems-condition-before-upgrading-software.html["소프트웨어 업그레이드 전 시스템 상태 확인"]



== 사용자 인터페이스 문제

업그레이드 중이나 업그레이드 후에 Grid Manager나 Tenant Manager에서 문제가 발생할 수 있습니다.



=== Grid Manager가 업그레이드 중에 여러 오류 메시지를 표시합니다.

기본 관리 노드가 업그레이드되는 동안 브라우저를 새로 고치거나 다른 Grid Manager 페이지로 이동하면 여러 개의 "503: 서비스를 사용할 수 없음" 및 "서버 연결 문제" 메시지가 표시될 수 있습니다.  이러한 메시지는 무시해도 됩니다. 노드가 업그레이드되면 더 이상 표시되지 않습니다.

업그레이드를 시작한 후 이러한 메시지가 1시간 이상 나타나면 기본 관리 노드가 업그레이드되지 못하게 하는 문제가 발생했을 수 있습니다.  스스로 문제를 해결할 수 없는 경우 기술 지원팀에 문의하세요.



=== 웹 인터페이스가 예상대로 응답하지 않습니다.

StorageGRID 소프트웨어가 업그레이드된 후 Grid Manager 또는 Tenant Manager가 예상대로 응답하지 않을 수 있습니다.

웹 인터페이스에 문제가 발생하는 경우:

* 당신이 사용하고 있는지 확인하십시오link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
+

NOTE: 브라우저 지원은 일반적으로 StorageGRID 릴리스마다 변경됩니다.

* 웹 브라우저 캐시를 지우세요.
+
캐시를 지우면 이전 버전의 StorageGRID 소프트웨어에서 사용하던 오래된 리소스가 제거되고 사용자 인터페이스가 다시 올바르게 작동할 수 있습니다.  자세한 내용은 웹 브라우저의 설명서를 참조하세요.





== "Docker 이미지 가용성 확인" 오류 메시지

업그레이드 프로세스를 시작하려고 할 때 "Docker 이미지 가용성 검사 유효성 검사 모음에서 다음 문제가 식별되었습니다."라는 오류 메시지가 나타날 수 있습니다.  업그레이드를 완료하기 전에 모든 문제를 해결해야 합니다.

확인된 문제를 해결하는 데 필요한 변경 사항이 확실하지 않은 경우 기술 지원팀에 문의하세요.

[cols="1a,1a,1a"]
|===
| 메시지 | 원인 | 해결책 


 a| 
업그레이드 버전을 확인할 수 없습니다.  업그레이드 버전 정보 파일 `{file_path}` 예상한 형식과 일치하지 않습니다.
 a| 
업그레이드 패키지가 손상되었습니다.
 a| 
업그레이드 패키지를 다시 업로드하고 다시 시도해 보세요.  문제가 지속되면 기술 지원팀에 문의하세요.



 a| 
업그레이드 버전 정보 파일 `{file_path}` 찾을 수 없습니다.  업그레이드 버전을 확인할 수 없습니다.
 a| 
업그레이드 패키지가 손상되었습니다.
 a| 
업그레이드 패키지를 다시 업로드하고 다시 시도해 보세요.  문제가 지속되면 기술 지원팀에 문의하세요.



 a| 
현재 설치된 릴리스 버전을 확인할 수 없습니다. `{node_name}` .
 a| 
노드의 중요한 파일이 손상되었습니다.
 a| 
기술 지원팀에 문의하세요.



 a| 
버전을 나열하는 동안 연결 오류가 발생했습니다. `{node_name}`
 a| 
노드가 오프라인이거나 연결이 중단되었습니다.
 a| 
모든 노드가 온라인 상태이고 기본 관리 노드에서 접속 가능한지 확인한 후 다시 시도하세요.



 a| 
노드의 호스트 `{node_name}` StorageGRID 가 없습니다 `{upgrade_version}` 이미지가 로드되었습니다.  업그레이드를 진행하려면 먼저 호스트에 이미지와 서비스를 설치해야 합니다.
 a| 
업그레이드를 위한 RPM 또는 DEB 패키지가 노드가 실행 중인 호스트에 설치되지 않았거나, 이미지를 가져오는 중입니다.

*참고:* 이 오류는 Linux에서 컨테이너로 실행되는 노드에만 적용됩니다.
 a| 
노드가 실행 중인 모든 Linux 호스트에 RPM 또는 DEB 패키지가 설치되었는지 확인하세요.  서비스와 이미지 파일 모두의 버전이 올바른지 확인하세요.  몇 분간 기다렸다가 다시 시도해 보세요.

보다 link:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux: 모든 호스트에 RPM 또는 DEB 패키지 설치"] .



 a| 
노드 검사 중 오류 발생 `{node_name}`
 a| 
예기치 않은 오류가 발생했습니다.
 a| 
몇 분간 기다렸다가 다시 시도해 보세요.



 a| 
사전 검사를 실행하는 동안 오류가 발생했습니다. `{error_string}`
 a| 
예기치 않은 오류가 발생했습니다.
 a| 
몇 분간 기다렸다가 다시 시도해 보세요.

|===