---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: 업그레이드를 시작하기 전에 이전 버전의 StorageGRID 최신 핫픽스가 적용되어 설치되어 있는지 확인하세요. 
---
= StorageGRID 의 설치된 버전을 확인하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드를 시작하기 전에 이전 버전의 StorageGRID 최신 핫픽스가 적용되어 설치되어 있는지 확인하세요.

.이 작업에 관하여
StorageGRID 11.9로 업그레이드하기 전에 그리드에 StorageGRID 11.8이 설치되어 있어야 합니다.  현재 StorageGRID 의 이전 버전을 사용하고 있다면 그리드의 현재 버전이 StorageGRID 11.8._x.y_가 될 때까지 모든 이전 업그레이드 파일과 최신 핫픽스를 설치해야 합니다(강력히 권장).

가능한 업그레이드 경로 중 하나는 다음과 같습니다.<<example-upgrade-path,예>> .


CAUTION: NetApp 다음 버전으로 업그레이드하기 전에 각 StorageGRID 버전에 최신 핫픽스를 적용하고, 설치하는 각 새 버전에도 최신 핫픽스를 적용할 것을 강력히 권장합니다. 어떤 경우에는 데이터 손실 위험을 방지하기 위해 핫픽스를 적용해야 합니다. 보다 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^] 자세한 내용은 각 핫픽스의 릴리스 노트를 참조하세요.

.단계
. 다음을 사용하여 Grid Manager에 Sign in.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
. 그리드 관리자 상단에서 *도움말* > *정보*를 선택합니다.
. *버전*이 11.8._x.y_인지 확인하세요.
+
StorageGRID 11.8._x.y_ 버전 번호:

+
** *주요 릴리스*의 _x_ 값은 0입니다(11.8.0).
** *핫픽스*가 적용된 경우 _y_ 값이 있습니다(예: 11.8.0.1).


. *버전*이 11.8._x.y_가 아닌 경우 다음으로 이동하세요. https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp 다운로드: StorageGRID"^] 각 릴리스의 최신 핫픽스를 포함하여 이전 릴리스의 파일을 다운로드합니다.
. 다운로드한 각 릴리스에 대한 업그레이드 지침을 받으세요.  그런 다음 해당 릴리스에 대한 소프트웨어 업그레이드 절차를 수행하고 해당 릴리스에 대한 최신 핫픽스를 적용합니다(강력히 권장).
+
를 참조하십시오link:../maintain/storagegrid-hotfix-procedure.html["StorageGRID 핫픽스 절차"] .





== [[example-upgrade-path]]예: 버전 11.6에서 StorageGRID 11.9으로 업그레이드

다음 예에서는 StorageGRID 11.9 업그레이드를 준비하기 위해 StorageGRID 버전 11.6에서 버전 11.8로 업그레이드하는 단계를 보여줍니다.

다음 순서대로 소프트웨어를 다운로드하고 설치하여 시스템 업그레이드를 준비하세요.

. StorageGRID 11.6.0 주요 릴리스로 업그레이드하세요.
. 최신 StorageGRID 11.6.0._y_ 핫픽스를 적용합니다.
. StorageGRID 11.7.0 주요 릴리스로 업그레이드하세요.
. 최신 StorageGRID 11.7.0._y_ 핫픽스를 적용합니다.
. StorageGRID 11.8.0 주요 릴리스로 업그레이드하세요.
. 최신 StorageGRID 11.8.0._y_ 핫픽스를 적용합니다.

