---
permalink: ubuntu/automating-installation.html 
sidebar: sidebar 
keywords: how to automate ubuntu or debian installation 
summary: StorageGRID 호스트 서비스의 설치와 그리드 노드 구성을 자동화할 수 있습니다. 
---
= 설치 자동화(Ubuntu 또는 Debian)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 호스트 서비스의 설치와 그리드 노드 구성을 자동화할 수 있습니다.

.이 작업에 관하여
다음과 같은 경우 배포를 자동화하는 것이 유용할 수 있습니다.

* Ansible, Puppet, Chef와 같은 표준 오케스트레이션 프레임워크를 사용하여 물리적 또는 가상 호스트를 배포하고 구성하고 있습니다.
* 여러 개의 StorageGRID 인스턴스를 배포하려고 합니다.
* 대규모의 복잡한 StorageGRID 인스턴스를 배포하고 있습니다.


StorageGRID 호스트 서비스는 패키지로 설치되고 수동 설치 중에 대화형으로 생성하거나 표준 오케스트레이션 프레임워크를 사용하여 자동 설치를 활성화하기 위해 미리(또는 프로그래밍 방식으로) 준비할 수 있는 구성 파일로 구동됩니다.  StorageGRID StorageGRID 어플라이언스와 전체 StorageGRID 시스템("그리드")의 구성을 자동화하기 위한 선택적 Python 스크립트를 제공합니다.  이러한 스크립트를 직접 사용할 수도 있고, 스크립트를 검사하여 직접 개발한 그리드 배포 및 구성 도구에서 StorageGRID 설치 REST API를 사용하는 방법을 알아볼 수 있습니다.



== StorageGRID 호스트 서비스의 설치 및 구성을 자동화합니다.

Ansible, Puppet, Chef, Fabric 또는 SaltStack과 같은 표준 오케스트레이션 프레임워크를 사용하여 StorageGRID 호스트 서비스 설치를 자동화할 수 있습니다.

StorageGRID 호스트 서비스는 DEB에 패키징되어 있으며, 사전(또는 프로그래밍 방식)으로 준비할 수 있는 구성 파일에 의해 구동되어 자동 설치가 가능합니다.  이미 Ubuntu 또는 Debian을 설치하고 구성하기 위해 표준 오케스트레이션 프레임워크를 사용하고 있다면 플레이북이나 레시피에 StorageGRID 추가하는 것은 간단할 것입니다.

다음 작업을 자동화할 수 있습니다.

. 리눅스 설치
. 리눅스 구성
. StorageGRID 요구 사항을 충족하도록 호스트 네트워크 인터페이스 구성
. StorageGRID 요구 사항을 충족하도록 호스트 스토리지 구성
. Docker 설치
. StorageGRID 호스트 서비스 설치
. StorageGRID 노드 구성 파일 생성 `/etc/storagegrid/nodes`
. StorageGRID 노드 구성 파일 검증
. StorageGRID 호스트 서비스 시작




=== Ansible 역할 및 플레이북 예시

예제 Ansible 역할 및 플레이북은 설치 아카이브와 함께 제공됩니다. `/extras` 접는 사람.  Ansible 플레이북은 다음 방법을 보여줍니다. `storagegrid` 역할은 호스트를 준비하고 대상 서버에 StorageGRID 설치합니다.  필요에 따라 역할이나 플레이북을 사용자 정의할 수 있습니다.



== StorageGRID 구성 자동화

그리드 노드를 배포한 후 StorageGRID 시스템 구성을 자동화할 수 있습니다.

.시작하기 전에
* 설치 아카이브에서 다음 파일의 위치를 알고 있습니다.
+
[cols="1a,1a"]
|===
| 파일 이름 | 설명 


| configure-storagegrid.py  a| 
구성을 자동화하는 데 사용되는 Python 스크립트



| configure-storagegrid.sample.json  a| 
스크립트와 함께 사용할 수 있는 예제 구성 파일



| configure-storagegrid.blank.json  a| 
스크립트와 함께 사용할 빈 구성 파일

|===
* 당신은 생성했습니다 `configure-storagegrid.json` 구성 파일.  이 파일을 생성하려면 예제 구성 파일을 수정할 수 있습니다.(`configure-storagegrid.sample.json` ) 또는 빈 구성 파일(`configure-storagegrid.blank.json` ).


.이 작업에 관하여
당신은 사용할 수 있습니다 `configure-storagegrid.py` Python 스크립트 및 `configure-storagegrid.json` StorageGRID 시스템 구성을 자동화하는 구성 파일입니다.


NOTE: Grid Manager나 설치 API를 사용하여 시스템을 구성할 수도 있습니다.

.단계
. Python 스크립트를 실행하기 위해 사용하는 Linux 머신에 로그인합니다.
. 설치 아카이브를 추출한 디렉토리로 변경합니다.
+
예를 들어:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
어디 `platform` ~이다 `debs` , `rpms` , 또는 `vsphere` .

. Python 스크립트를 실행하고 생성한 구성 파일을 사용합니다.
+
예를 들어:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.결과
복구 패키지 `.zip` 파일은 구성 과정 중에 생성되며, 설치 및 구성 과정을 실행하는 디렉토리에 다운로드됩니다.  하나 이상의 그리드 노드가 실패할 경우 StorageGRID 시스템을 복구할 수 있도록 복구 패키지 파일을 백업해야 합니다.  예를 들어, 안전하게 백업된 네트워크 위치와 안전한 클라우드 스토리지 위치에 복사하세요.


CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 얻는 데 사용할 수 있는 암호화 키와 비밀번호가 포함되어 있으므로 보호되어야 합니다.

임의의 비밀번호가 생성되도록 지정한 경우 다음을 엽니다. `Passwords.txt` 파일을 열고 StorageGRID 시스템에 액세스하는 데 필요한 비밀번호를 찾으세요.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID 시스템이 설치되고 구성되면 확인 메시지가 표시됩니다.

[listing]
----
StorageGRID has been configured and installed.
----
.관련 정보
link:overview-of-installation-rest-api.html["REST API 설치"]
