---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: 모든 Ubuntu 또는 Debian 그리드 호스트에 StorageGRID 설치해야 합니다. 지원되는 버전 목록을 보려면 NetApp 상호 운용성 매트릭스 도구를 사용하세요. 
---
= 리눅스 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 Ubuntu 또는 Debian 그리드 호스트에 StorageGRID 설치해야 합니다. 지원되는 버전 목록을 보려면 NetApp 상호 운용성 매트릭스 도구를 사용하세요.

.시작하기 전에
아래에 나열된 대로 운영 체제가 StorageGRID의 최소 커널 버전 요구 사항을 충족하는지 확인하세요.  명령을 사용하세요 `uname -r` 운영 체제의 커널 버전을 알아보거나 OS 공급업체에 문의하세요.

*참고:* Ubuntu 버전 18.04 및 20.04에 대한 지원이 더 이상 제공되지 않으며 향후 릴리스에서 제거될 예정입니다.

[cols="1a,2a,3a"]
|===
| 우분투 버전 | 최소 커널 버전 | 커널 패키지 이름 


 a| 
18.04.6 (더 이상 사용되지 않음)
 a| 
5.4.0-150-일반
 a| 
linux-image-5.4.0-150-generic/bionic-updates,bionic-security,현재 5.4.0-150.167~18.04.1



 a| 
20.04.5 (더 이상 사용되지 않음)
 a| 
5.4.0-131-일반
 a| 
linux-image-5.4.0-131-generic/focal-updates, 현재 5.4.0-131.147



 a| 
22.04.1
 a| 
5.15.0-47-일반
 a| 
linux-image-5.15.0-47-generic/jammy-updates,jammy-security,현재 5.15.0-47.51



 a| 
24.04
 a| 
6.8.0-31-일반
 a| 
linux-image-6.8.0-31-generic/noble, 현재 6.8.0-31.31

|===
*참고:* Debian 버전 11에 대한 지원은 더 이상 제공되지 않으며 향후 릴리스에서 제거될 예정입니다.

[cols="1a,2a,2a"]
|===
| 데비안 버전 | 최소 커널 버전 | 커널 패키지 이름 


 a| 
11 (더 이상 사용되지 않음)
 a| 
5.10.0-18-amd64
 a| 
linux-image-5.10.0-18-amd64/stable, 현재 5.10.150-1



 a| 
12
 a| 
6.1.0-9-amd64
 a| 
linux-image-6.1.0-9-amd64/stable, 현재 6.1.27-1

|===
.단계
. 배포자의 지침이나 표준 절차에 따라 모든 물리적 또는 가상 그리드 호스트에 Linux를 설치합니다.
+

NOTE: 그래픽 데스크톱 환경을 설치하지 마세요. Ubuntu를 설치할 때 *표준 시스템 유틸리티*를 선택해야 합니다. Ubuntu 호스트에 대한 ssh 액세스를 활성화하려면 *OpenSSH 서버*를 선택하는 것이 좋습니다. 다른 모든 옵션은 지워진 상태로 유지됩니다.

. 모든 호스트가 Ubuntu 또는 Debian 패키지 저장소에 액세스할 수 있는지 확인하세요.
. 스왑이 활성화된 경우:
+
.. 다음 명령을 실행하세요. `$ sudo swapoff --all`
.. 모든 스왑 항목을 제거합니다. `/etc/fstab` 설정을 유지하려면.
+

NOTE: 스왑을 완전히 비활성화하지 못하면 성능이 크게 저하될 수 있습니다.




