---
permalink: harden/hardening-guidelines-for-storagegrid-nodes.html 
sidebar: sidebar 
keywords: hardening guidelines, nodes, security 
summary: StorageGRID 노드는 VMware 가상 머신, Linux 호스트의 컨테이너 엔진 또는 전용 하드웨어 어플라이언스로 배포할 수 있습니다.  각 플랫폼 유형과 각 노드 유형에는 고유한 강화 모범 사례가 있습니다. 
---
= StorageGRID 노드에 대한 강화 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 노드는 VMware 가상 머신, Linux 호스트의 컨테이너 엔진 또는 전용 하드웨어 어플라이언스로 배포할 수 있습니다.  각 플랫폼 유형과 각 노드 유형에는 고유한 강화 모범 사례가 있습니다.



== BMC 에 대한 원격 IPMI 액세스 제어

BMC 포함된 모든 어플라이언스에 대해 원격 IPMI 액세스를 활성화하거나 비활성화할 수 있습니다. 원격 IPMI 인터페이스를 사용하면 BMC 계정과 비밀번호가 있는 모든 사람이 StorageGRID 어플라이언스에 저수준 하드웨어로 액세스할 수 있습니다. BMC 에 대한 원격 IPMI 액세스가 필요하지 않으면 이 옵션을 비활성화합니다.

* Grid Manager에서 BMC 에 대한 원격 IPMI 액세스를 제어하려면 *구성* > *보안* > *보안 설정* > *어플라이언스*로 이동합니다.
+
** BMC 에 대한 IPMI 액세스를 비활성화하려면 *원격 IPMI 액세스 활성화* 확인란을 선택 취소합니다.
** BMC 에 대한 IPMI 액세스를 활성화하려면 *원격 IPMI 액세스 활성화* 확인란을 선택합니다.






== 방화벽 구성

시스템 강화 프로세스의 일환으로 외부 방화벽 구성을 검토하고 이를 수정하여 트래픽이 반드시 필요한 IP 주소와 포트에서만 허용되도록 해야 합니다.

StorageGRID 에는 각 노드에 내부 방화벽이 포함되어 있어 노드에 대한 네트워크 액세스를 제어할 수 있어 그리드의 보안을 강화합니다.  당신은해야합니다link:../admin/manage-firewall-controls.html["내부 방화벽 제어 관리"] 특정 그리드 배포에 필요한 포트를 제외한 모든 포트에서 네트워크 액세스를 차단합니다.  방화벽 제어 페이지에서 변경한 구성은 각 노드에 배포됩니다.

구체적으로 다음 영역을 관리할 수 있습니다.

* *특권이 있는 주소*: 외부 액세스 관리 탭의 설정에 따라 닫힌 포트에 선택한 IP 주소나 서브넷이 액세스하도록 허용할 수 있습니다.
* *외부 액세스 관리*: 기본적으로 열려 있는 포트를 닫거나 이전에 닫은 포트를 다시 열 수 있습니다.
* *신뢰할 수 없는 클라이언트 네트워크*: 신뢰할 수 없는 클라이언트 네트워크가 구성된 경우 노드가 클라이언트 네트워크에서 들어오는 트래픽을 신뢰할지 여부와 추가로 열려는 포트를 지정할 수 있습니다.


이러한 내부 방화벽은 몇 가지 일반적인 위협에 대한 추가적인 보호 계층을 제공하지만 외부 방화벽의 필요성을 없애지는 않습니다.

StorageGRID 에서 사용하는 모든 내부 및 외부 포트 목록은 다음을 참조하세요.link:../network/network-port-reference.html["네트워크 포트 참조"] .



== 사용하지 않는 서비스 비활성화

모든 StorageGRID 노드에 대해 사용하지 않는 서비스에 대한 액세스를 비활성화하거나 차단해야 합니다. 예를 들어, DHCP를 사용하지 않을 계획이라면 Grid Manager를 사용하여 포트 68을 닫으세요. *구성* > *방화벽 제어* > *외부 액세스 관리*를 선택합니다. 그런 다음 포트 68의 상태 토글을 *열림*에서 *닫힘*으로 변경합니다.



== 가상화, 컨테이너 및 공유 하드웨어

모든 StorageGRID 노드의 경우 신뢰할 수 없는 소프트웨어와 동일한 물리적 하드웨어에서 StorageGRID 실행하지 마세요.  StorageGRID 와 맬웨어가 동일한 물리적 하드웨어에 존재하는 경우 하이퍼바이저 보호가 맬웨어가 StorageGRID 로 보호되는 데이터에 액세스하는 것을 차단할 수 있다고 가정하지 마세요.  예를 들어, Meltdown과 Spectre 공격은 최신 프로세서의 심각한 취약점을 악용하여 프로그램이 동일한 컴퓨터의 메모리에 있는 데이터를 훔칠 수 있도록 합니다.



== 설치 중 노드 보호

노드를 설치하는 동안 신뢰할 수 없는 사용자가 네트워크를 통해 StorageGRID 노드에 액세스하는 것을 허용하지 마세요.  노드는 그리드에 가입하기 전까지는 완전히 안전하지 않습니다.



== 관리 노드에 대한 지침

관리 노드는 시스템 구성, 모니터링, 로깅과 같은 관리 서비스를 제공합니다. Grid Manager 또는 Tenant Manager에 로그인하면 관리 노드에 연결됩니다.

StorageGRID 시스템의 관리 노드를 보호하려면 다음 지침을 따르세요.

* 개방형 인터넷 등의 신뢰할 수 없는 클라이언트로부터 모든 관리 노드를 보호합니다.  신뢰할 수 없는 클라이언트가 그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크의 관리 노드에 액세스할 수 없도록 합니다.
* StorageGRID 그룹은 Grid Manager 및 Tenant Manager 기능에 대한 액세스를 제어합니다.  각 사용자 그룹에 해당 역할에 필요한 최소한의 권한을 부여하고, 사용자가 구성을 변경하지 못하도록 읽기 전용 액세스 모드를 사용합니다.
* StorageGRID 로드 밸런서 엔드포인트를 사용하는 경우 신뢰할 수 없는 클라이언트 트래픽에 대해 관리 노드 대신 게이트웨이 노드를 사용하세요.
* 신뢰할 수 없는 테넌트가 있는 경우 테넌트 관리자나 테넌트 관리 API에 직접 액세스하도록 허용하지 마세요.  대신 신뢰할 수 없는 테넌트는 테넌트 관리 API와 상호 작용하는 테넌트 포털이나 외부 테넌트 관리 시스템을 사용하세요.
* 선택적으로, 관리 노드에서 NetApp 지원으로의 AutoSupport 통신을 보다 효과적으로 제어하기 위해 관리 프록시를 사용할 수 있습니다. 단계를 참조하세요link:../admin/configuring-admin-proxy-settings.html["관리자 프록시 생성"] .
* 선택적으로, 제한된 8443 및 9443 포트를 사용하여 Grid Manager와 Tenant Manager 통신을 분리합니다.  추가 보호를 위해 공유 포트 443을 차단하고 테넌트 요청을 포트 9443으로 제한합니다.
* 선택적으로 그리드 관리자와 테넌트 사용자에 대해 별도의 관리 노드를 사용합니다.


자세한 내용은 지침을 참조하세요.link:../admin/index.html["StorageGRID 관리"] .



== 스토리지 노드에 대한 지침

저장 노드는 개체 데이터와 메타데이터를 관리하고 저장합니다.  StorageGRID 시스템의 스토리지 노드를 보호하려면 다음 지침을 따르세요.

* 신뢰할 수 없는 클라이언트가 스토리지 노드에 직접 연결하는 것을 허용하지 마세요.  게이트웨이 노드 또는 타사 로드 밸런서가 제공하는 로드 밸런서 엔드포인트를 사용합니다.
* 신뢰할 수 없는 테넌트에 대해 아웃바운드 서비스를 활성화하지 마세요.  예를 들어, 신뢰할 수 없는 테넌트에 대한 계정을 생성할 때 테넌트가 자체 ID 소스를 사용하도록 허용하지 말고 플랫폼 서비스를 사용하도록 허용하지 마세요. 단계를 참조하세요link:../admin/creating-tenant-account.html["테넌트 계정 생성"] .
* 신뢰할 수 없는 클라이언트 트래픽에는 타사 로드 밸런서를 사용하세요.  타사 부하 분산은 공격에 대비해 더 많은 제어와 추가적인 보호 계층을 제공합니다.
* 선택적으로 스토리지 프록시를 사용하여 스토리지 노드에서 외부 서비스로의 클라우드 스토리지 풀 및 플랫폼 서비스 통신을 더욱 효과적으로 제어할 수 있습니다. 단계를 참조하세요link:../admin/configuring-storage-proxy-settings.html["스토리지 프록시 생성"] .
* 선택적으로 클라이언트 네트워크를 사용하여 외부 서비스에 연결합니다. 그런 다음 *구성* > *보안* > *방화벽 제어* > *신뢰할 수 없는 클라이언트 네트워크*를 선택하고 스토리지 노드의 클라이언트 네트워크가 신뢰할 수 없음을 표시합니다. 스토리지 노드는 더 이상 클라이언트 네트워크에서 들어오는 트래픽을 허용하지 않지만 플랫폼 서비스에 대한 아웃바운드 요청은 계속 허용합니다.




== 게이트웨이 노드에 대한 지침

게이트웨이 노드는 클라이언트 애플리케이션이 StorageGRID 에 연결하는 데 사용할 수 있는 선택적 부하 분산 인터페이스를 제공합니다.  StorageGRID 시스템의 게이트웨이 노드를 보호하려면 다음 지침을 따르세요.

* 로드 밸런서 엔드포인트를 구성하고 사용합니다. 보다 link:../admin/managing-load-balancing.html["부하 분산을 위한 고려 사항"] .
* 신뢰할 수 없는 클라이언트 트래픽의 경우 클라이언트와 게이트웨이 노드 또는 스토리지 노드 사이에 타사 로드 밸런서를 사용하세요.  타사 부하 분산은 공격에 대비해 더 많은 제어와 추가적인 보호 계층을 제공합니다.  타사 로드 밸런서를 사용하는 경우에도 네트워크 트래픽을 선택적으로 내부 로드 밸런서 엔드포인트를 통과하거나 스토리지 노드로 직접 전송하도록 구성할 수 있습니다.
* 로드 밸런서 엔드포인트를 사용하는 경우, 선택적으로 클라이언트가 클라이언트 네트워크를 통해 연결되도록 할 수 있습니다. 그런 다음 *구성* > *보안* > *방화벽 제어* > *신뢰할 수 없는 클라이언트 네트워크*를 선택하고 게이트웨이 노드의 클라이언트 네트워크가 신뢰할 수 없음을 표시합니다. 게이트웨이 노드는 로드 밸런서 엔드포인트로 명시적으로 구성된 포트에서만 인바운드 트래픽을 허용합니다.




== 하드웨어 어플라이언스 노드에 대한 지침

StorageGRID 하드웨어 어플라이언스는 StorageGRID 시스템에서 사용하도록 특별히 설계되었습니다.  일부 기기는 저장 노드로 사용할 수 있습니다.  다른 어플라이언스는 관리 노드나 게이트웨이 노드로 사용될 수 있습니다.  어플라이언스 노드를 소프트웨어 기반 노드와 결합하거나 완벽하게 설계된 모든 어플라이언스 그리드를 배포할 수 있습니다.

StorageGRID 시스템의 모든 하드웨어 어플라이언스 노드를 보호하려면 다음 지침을 따르세요.

* 어플라이언스가 스토리지 컨트롤러 관리를 위해 SANtricity System Manager를 사용하는 경우 신뢰할 수 없는 클라이언트가 네트워크를 통해 SANtricity System Manager에 액세스하는 것을 방지합니다.
* 어플라이언스에 베이스보드 관리 컨트롤러(BMC)가 있는 경우 BMC 관리 포트를 통해 저수준 하드웨어 액세스가 허용된다는 점을 알아두세요. BMC 관리 포트는 안전하고 신뢰할 수 있는 내부 관리 네트워크에만 연결하세요. 해당 네트워크를 사용할 수 없는 경우 기술 지원팀에서 BMC 연결을 요청하지 않는 한 BMC 관리 포트를 연결하지 않거나 차단된 상태로 두세요.
* 어플라이언스가 IPMI(Intelligent Platform Management Interface) 표준을 사용하여 이더넷을 통해 컨트롤러 하드웨어의 원격 관리를 지원하는 경우 포트 623에서 신뢰할 수 없는 트래픽을 차단합니다.



NOTE: BMC 포함된 모든 어플라이언스에 대해 원격 IPMI 액세스를 활성화하거나 비활성화할 수 있습니다. 원격 IPMI 인터페이스를 사용하면 BMC 계정과 비밀번호가 있는 모든 사람이 StorageGRID 어플라이언스에 저수준 하드웨어로 액세스할 수 있습니다. BMC 에 대한 원격 IPMI 액세스가 필요하지 않은 경우 다음 방법 중 하나를 사용하여 이 옵션을 비활성화합니다. + Grid Manager에서 *구성* > *보안* > *보안 설정* > *어플라이언스*로 이동하여 *원격 IPMI 액세스 사용* 확인란의 선택을 취소합니다. + 그리드 관리 API에서 개인 엔드포인트를 사용하세요. `PUT /private/bmc` .

* SANtricity System Manager로 관리하는 SED, FDE 또는 FIPS NL-SAS 드라이브가 포함된 어플라이언스 모델의 경우 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/accessing-and-configuring-santricity-system-manager.html["SANtricity 드라이브 보안 활성화 및 구성"^] .
* StorageGRID Appliance Installer 및 Grid Manager를 사용하여 관리하는 SED 또는 FIPS NVMe SSD가 포함된 어플라이언스 모델의 경우 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html["StorageGRID 드라이브 암호화 활성화 및 구성"^] .
* SED, FDE 또는 FIPS 드라이브가 없는 어플라이언스의 경우 StorageGRID 소프트웨어 노드 암호화를 활성화하고 구성합니다. https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html#enable-node-encryption["키 관리 서버(KMS) 사용"^] .

