---
permalink: harden/index.html 
sidebar: sidebar 
keywords: Hardening guidelines, system, security 
summary: 시스템 강화는 StorageGRID 시스템에서 가능한 한 많은 보안 위험을 제거하는 프로세스입니다. 
---
= 시스템 강화를 위한 일반적인 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템 강화는 StorageGRID 시스템에서 가능한 한 많은 보안 위험을 제거하는 프로세스입니다.

StorageGRID 설치하고 구성할 때 이러한 지침을 사용하면 기밀성, 무결성 및 가용성에 대한 규정된 보안 목표를 충족하는 데 도움이 됩니다.

시스템 강화를 위해 업계 표준 모범 사례를 이미 사용하고 있어야 합니다. 예를 들어, StorageGRID 에 강력한 비밀번호를 사용하고, HTTP 대신 HTTPS를 사용하고, 가능한 경우 인증서 기반 인증을 활성화합니다.

StorageGRID 다음을 따릅니다. https://security.netapp.com/policy/["NetApp 취약점 처리 정책"^] .  보고된 취약점은 제품 보안 사고 대응 프로세스에 따라 검증되고 해결됩니다.

StorageGRID 시스템을 강화할 때 다음 사항을 고려하세요.

* *세 개의 StorageGRID 네트워크 중 어떤 것을 구현했습니까?*  모든 StorageGRID 시스템은 그리드 네트워크를 사용해야 하지만, 관리 네트워크, 클라이언트 네트워크 또는 둘 다를 사용할 수도 있습니다.  각 네트워크마다 보안 고려사항이 다릅니다.
* StorageGRID 시스템의 개별 노드에 사용하는 *플랫폼 유형*입니다.  StorageGRID 노드는 VMware 가상 머신, Linux 호스트의 컨테이너 엔진 또는 전용 하드웨어 어플라이언스로 배포할 수 있습니다.  각 플랫폼 유형에는 고유한 강화 모범 사례가 있습니다.
* *세입자 계정의 신뢰도*.  신뢰할 수 없는 테넌트 계정을 사용하는 서비스 제공자의 경우 신뢰할 수 있는 사내 테넌트만 사용하는 경우와는 다른 보안 문제가 발생합니다.
* 귀하의 조직이 따르는 보안 요구 사항 및 규칙은 무엇입니까?  특정 규제 또는 기업 요구 사항을 준수해야 할 수도 있습니다.

