---
permalink: network/general-networking-requirements.html 
sidebar: sidebar 
keywords: networking requirements, storagegrid networks 
summary: 모든 StorageGRID 배포는 다음 연결을 지원할 수 있어야 합니다. 
---
= 일반적인 네트워킹 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 StorageGRID 배포는 다음 연결을 지원할 수 있어야 합니다.

이러한 연결은 그리드, 관리자 또는 클라이언트 네트워크를 통해 발생할 수 있으며, 네트워크 토폴로지 예제에서 설명한 대로 이러한 네트워크의 조합을 통해 발생할 수도 있습니다.

* *관리 연결*: 일반적으로 SSH를 통해 관리자가 노드로 보내는 인바운드 연결입니다.  Grid Manager, Tenant Manager 및 StorageGRID Appliance 설치 프로그램에 웹 브라우저로 접속할 수 있습니다.
* *NTP 서버 연결*: 인바운드 UDP 응답을 수신하는 아웃바운드 UDP 연결입니다.
+
최소한 하나의 NTP 서버에 기본 관리 노드에서 접근할 수 있어야 합니다.

* *DNS 서버 연결*: 인바운드 UDP 응답을 수신하는 아웃바운드 UDP 연결입니다.
* *LDAP/Active Directory 서버 연결*: 스토리지 노드의 ID 서비스에서 발생하는 아웃바운드 TCP 연결입니다.
* * AutoSupport*: 관리 노드에서 다음 노드로의 아웃바운드 TCP 연결 `support.netapp.com` 또는 고객이 구성한 프록시.
* *외부 키 관리 서버*: 노드 암호화가 활성화된 각 어플라이언스 노드에서의 아웃바운드 TCP 연결.
* S3 클라이언트로부터의 인바운드 TCP 연결.
* CloudMirror 복제나 Cloud Storage Pools와 같은 StorageGRID 플랫폼 서비스에서의 아웃바운드 요청입니다.


StorageGRID 기본 라우팅 규칙을 사용하여 제공된 NTP 또는 DNS 서버에 접속할 수 없는 경우 DNS 및 NTP 서버의 IP 주소가 지정되어 있는 한 모든 네트워크(Grid, Admin 및 Client)에서 자동으로 접속을 시도합니다.  NTP 또는 DNS 서버에 어떤 네트워크에서든 접속이 가능한 경우, StorageGRID 자동으로 추가 라우팅 규칙을 생성하여 해당 네트워크가 향후 모든 연결 시도에 사용되도록 보장합니다.


TIP: 자동으로 검색된 호스트 경로를 사용할 수는 있지만 일반적으로 자동 검색에 실패할 경우 연결을 보장하기 위해 DNS 및 NTP 경로를 수동으로 구성해야 합니다.

배포 중에 선택 사항인 관리자 및 클라이언트 네트워크를 구성할 준비가 되지 않은 경우 구성 단계에서 그리드 노드를 승인할 때 이러한 네트워크를 구성할 수 있습니다.  또한 설치가 완료된 후 IP 변경 도구를 사용하여 이러한 네트워크를 구성할 수 있습니다(참조).link:../maintain/configuring-ip-addresses.html["IP 주소 구성"] ).



== 관리 노드 및 게이트웨이 노드에 대한 연결

관리 노드는 항상 공개 인터넷에 있는 클라이언트 등 신뢰할 수 없는 클라이언트로부터 보호되어야 합니다.  신뢰할 수 없는 클라이언트가 그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크의 관리 노드에 액세스할 수 없도록 해야 합니다.

고가용성 그룹에 추가하려는 관리 노드와 게이트웨이 노드는 고정 IP 주소로 구성되어야 합니다. 보다 link:../admin/managing-high-availability-groups.html["고가용성 그룹 관리"] .



== 네트워크 주소 변환(NAT) 사용

그리드 노드 간 또는 StorageGRID 사이트 간의 그리드 네트워크에서 NAT(네트워크 주소 변환)를 사용하지 마세요.  그리드 네트워크에 개인 IPv4 주소를 사용하는 경우 해당 주소는 모든 사이트의 모든 그리드 노드에서 직접 라우팅될 수 있어야 합니다.  그러나 필요에 따라 외부 클라이언트와 그리드 노드 간에 NAT를 사용하여 게이트웨이 노드에 대한 공용 IP 주소를 제공할 수 있습니다.  NAT를 사용하여 공용 네트워크 세그먼트를 연결하는 것은 그리드의 모든 노드에 투명한 터널링 애플리케이션을 사용하는 경우에만 지원됩니다. 즉, 그리드 노드는 공용 IP 주소를 알 필요가 없습니다.
