---
permalink: network/internal-grid-node-communications.html 
sidebar: sidebar 
keywords: storagegrid, network port, internal communications, ports, TCP, UDP, grid communications, port 
summary: 'StorageGRID 내부 방화벽은 포트 22, 80, 123, 443을 제외하고 그리드 네트워크의 특정 포트로 들어오는 연결만 허용합니다(외부 통신에 대한 정보 참조).  로드 밸런서 엔드포인트에서 정의한 포트에서도 연결이 허용됩니다.' 
---
= 내부 그리드 노드 통신
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 내부 방화벽은 그리드 네트워크의 특정 포트로 들어오는 연결을 허용합니다.  로드 밸런서 엔드포인트에서 정의한 포트에서도 연결이 허용됩니다.


NOTE: NetApp 그리드 노드 간에 ICMP(Internet Control Message Protocol) 트래픽을 활성화할 것을 권장합니다.  그리드 노드에 접근할 수 없을 때 ICMP 트래픽을 허용하면 장애 조치 성능이 향상될 수 있습니다.

StorageGRID ICMP와 표에 나열된 포트 외에도 VRRP(Virtual Router Redundancy Protocol)를 사용합니다.  VRRP는 IP 프로토콜 번호 112를 사용하는 인터넷 프로토콜입니다.  StorageGRID 유니캐스트 모드에서만 VRRP를 사용합니다.  VRRP는 다음의 경우에만 필요합니다.link:../admin/managing-high-availability-groups.html["고가용성 그룹"] 구성되어 있습니다.



== Linux 기반 노드에 대한 지침

기업 네트워킹 정책이 이러한 포트에 대한 액세스를 제한하는 경우 배포 구성 매개변수를 사용하여 배포 시점에 포트를 다시 매핑할 수 있습니다. 포트 리매핑 및 배포 구성 매개변수에 대한 자세한 내용은 다음을 참조하세요.

* link:../rhel/index.html["Red Hat Enterprise Linux에 StorageGRID 설치"]
* link:../ubuntu/index.html["Ubuntu 또는 Debian에 StorageGRID 설치"]




== VMware 기반 노드에 대한 지침

VMware 네트워킹 외부의 방화벽 제한을 정의해야 하는 경우에만 다음 포트를 구성하세요.

기업 네트워킹 정책이 이러한 포트에 대한 액세스를 제한하는 경우 VMware vSphere Web Client를 사용하여 노드를 배포할 때 포트를 다시 매핑하거나 그리드 노드 배포를 자동화할 때 구성 파일 설정을 사용하여 포트를 다시 매핑할 수 있습니다. 포트 리매핑 및 배포 구성 매개변수에 대한 자세한 내용은 다음을 참조하세요.link:../vmware/index.html["VMware에 StorageGRID 설치"] .



== 어플라이언스 노드에 대한 지침

기업 네트워킹 정책이 이러한 포트에 대한 액세스를 제한하는 경우 StorageGRID Appliance 설치 프로그램을 사용하여 포트를 다시 매핑할 수 있습니다. 보다 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-remapping-network-ports-for-appliance.html["선택 사항: 어플라이언스의 네트워크 포트를 다시 매핑합니다."^] .



== StorageGRID 내부 포트

[cols="1a,1a,1a,1a,4a"]
|===
| 포트 | TCP 또는 UDP | 에서 | 에게 | 세부 


 a| 
22
 a| 
TCP
 a| 
기본 관리 노드
 a| 
모든 노드
 a| 
유지 관리 절차를 위해 기본 관리 노드는 포트 22에서 SSH를 사용하여 다른 모든 노드와 통신할 수 있어야 합니다.  다른 노드에서 SSH 트래픽을 허용하는 것은 선택 사항입니다.



 a| 
80
 a| 
TCP
 a| 
가전제품
 a| 
기본 관리 노드
 a| 
StorageGRID 어플라이언스가 기본 관리 노드와 통신하여 설치를 시작하는 데 사용됩니다.



 a| 
123
 a| 
UDP
 a| 
모든 노드
 a| 
모든 노드
 a| 
네트워크 시간 프로토콜 서비스.  각 노드는 NTP를 사용하여 다른 모든 노드와 시간을 동기화합니다.



 a| 
443
 a| 
TCP
 a| 
모든 노드
 a| 
기본 관리 노드
 a| 
설치 및 기타 유지 관리 절차 중에 기본 관리 노드에 상태를 전달하는 데 사용됩니다.



 a| 
1055
 a| 
TCP
 a| 
모든 노드
 a| 
기본 관리 노드
 a| 
설치, 확장, 복구 및 기타 유지 관리 절차를 위한 내부 트래픽입니다.



 a| 
1139
 a| 
TCP
 a| 
저장 노드
 a| 
저장 노드
 a| 
저장 노드 간의 내부 트래픽.



 a| 
1501
 a| 
TCP
 a| 
모든 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
내부 트래픽 보고, 감사 및 구성.



 a| 
1502
 a| 
TCP
 a| 
모든 노드
 a| 
저장 노드
 a| 
S3 및 Swift 관련 내부 트래픽.



 a| 
1504
 a| 
TCP
 a| 
모든 노드
 a| 
관리 노드
 a| 
NMS 서비스 보고 및 구성 내부 트래픽.



 a| 
1505
 a| 
TCP
 a| 
모든 노드
 a| 
관리 노드
 a| 
AMS 서비스 내부 트래픽.



 a| 
1506
 a| 
TCP
 a| 
모든 노드
 a| 
모든 노드
 a| 
서버 상태 내부 트래픽.



 a| 
1507
 a| 
TCP
 a| 
모든 노드
 a| 
게이트웨이 노드
 a| 
로드 밸런서 내부 트래픽.



 a| 
1508
 a| 
TCP
 a| 
모든 노드
 a| 
기본 관리 노드
 a| 
구성 관리 내부 트래픽.



 a| 
1511
 a| 
TCP
 a| 
모든 노드
 a| 
저장 노드
 a| 
메타데이터 내부 트래픽.



 a| 
5353
 a| 
UDP
 a| 
모든 노드
 a| 
모든 노드
 a| 
설치, 확장, 복구 중에 전체 그리드 IP 변경과 기본 관리 노드 검색에 사용되는 멀티캐스트 DNS(mDNS) 서비스를 제공합니다.



 a| 
7001
 a| 
TCP
 a| 
저장 노드
 a| 
저장 노드
 a| 
Cassandra TLS 노드 간 클러스터 통신.



 a| 
7443
 a| 
TCP
 a| 
모든 노드
 a| 
기본 관리 노드
 a| 
설치, 확장, 복구, 기타 유지 관리 절차 및 오류 보고를 위한 내부 트래픽입니다.



 a| 
8011
 a| 
TCP
 a| 
모든 노드
 a| 
기본 관리 노드
 a| 
설치, 확장, 복구 및 기타 유지 관리 절차를 위한 내부 트래픽입니다.



 a| 
8443
 a| 
TCP
 a| 
기본 관리 노드
 a| 
어플라이언스 노드
 a| 
유지 관리 모드 절차와 관련된 내부 트래픽입니다.



 a| 
9042
 a| 
TCP
 a| 
저장 노드
 a| 
저장 노드
 a| 
카산드라 클라이언트 포트.



 a| 
9999
 a| 
TCP
 a| 
모든 노드
 a| 
모든 노드
 a| 
여러 서비스에 대한 내부 트래픽.  유지 관리 절차, 측정 항목, 네트워킹 업데이트가 포함됩니다.



 a| 
10226
 a| 
TCP
 a| 
저장 노드
 a| 
기본 관리 노드
 a| 
StorageGRID 어플라이언스에서 E-Series SANtricity System Manager에서 기본 관리 노드로 AutoSupport 패키지를 전달하는 데 사용됩니다.



 a| 
10342
 a| 
TCP
 a| 
모든 노드
 a| 
기본 관리 노드
 a| 
설치, 확장, 복구 및 기타 유지 관리 절차를 위한 내부 트래픽입니다.



 a| 
18000
 a| 
TCP
 a| 
관리/저장 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
계정 서비스 내부 트래픽.



 a| 
18001
 a| 
TCP
 a| 
관리/저장 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
ID 연합 내부 트래픽.



 a| 
18002
 a| 
TCP
 a| 
관리/저장 노드
 a| 
저장 노드
 a| 
객체 프로토콜과 관련된 내부 API 트래픽입니다.



 a| 
18003
 a| 
TCP
 a| 
관리/저장 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
플랫폼 서비스 내부 트래픽.



 a| 
18017
 a| 
TCP
 a| 
관리/저장 노드
 a| 
저장 노드
 a| 
클라우드 스토리지 풀을 위한 Data Mover 서비스 내부 트래픽입니다.



 a| 
18019
 a| 
TCP
 a| 
모든 노드
 a| 
모든 노드
 a| 
삭제 코딩 및 복제를 위한 청크 서비스 내부 트래픽



 a| 
18082
 a| 
TCP
 a| 
관리/저장 노드
 a| 
저장 노드
 a| 
S3 관련 내부 트래픽.



 a| 
18083
 a| 
TCP
 a| 
모든 노드
 a| 
저장 노드
 a| 
Swift 관련 내부 트래픽.



 a| 
18086
 a| 
TCP
 a| 
모든 노드
 a| 
저장 노드
 a| 
LDR 서비스와 관련된 내부 트래픽입니다.



 a| 
18200
 a| 
TCP
 a| 
관리/저장 노드
 a| 
저장 노드
 a| 
클라이언트 요청에 대한 추가 통계.



 a| 
19000
 a| 
TCP
 a| 
관리/저장 노드
 a| 
ADC가 있는 스토리지 노드
 a| 
Keystone 서비스 내부 교통.

|===
.관련 정보
link:external-communications.html["외부 커뮤니케이션"]
