---
permalink: network/linux-deployments.html 
sidebar: sidebar 
keywords: linux network, container engine, red hat enterprise linux rhel network, ubuntu network 
summary: 효율성, 안정성, 보안을 위해 StorageGRID 시스템은 컨테이너 엔진의 모음인 Linux에서 실행됩니다.  StorageGRID 시스템에서는 컨테이너 엔진 관련 네트워크 구성이 필요하지 않습니다. 
---
= Linux 배포
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
효율성, 안정성, 보안을 위해 StorageGRID 시스템은 컨테이너 엔진의 모음인 Linux에서 실행됩니다.  StorageGRID 시스템에서는 컨테이너 엔진 관련 네트워크 구성이 필요하지 않습니다.

컨테이너 네트워크 인터페이스에 VLAN이나 가상 이더넷(veth) 쌍과 같은 비결합 장치를 사용합니다.  노드 구성 파일에서 이 장치를 네트워크 인터페이스로 지정합니다.


CAUTION: 본드 또는 브리지 장치를 컨테이너 네트워크 인터페이스로 직접 사용하지 마세요.  그렇게 하면 컨테이너 네임스페이스에서 bond 및 bridge 장치를 사용하는 macvlan과 관련된 커널 문제로 인해 노드 시작이 방해받을 수 있습니다.

설치 지침을 참조하세요.link:../rhel/index.html["레드햇 엔터프라이즈 리눅스"] 또는link:../ubuntu/index.html["우분투 또는 데비안"] 배치.



== 컨테이너 엔진 배포를 위한 호스트 네트워크 구성

컨테이너 엔진 플랫폼에서 StorageGRID 배포를 시작하기 전에 각 노드가 사용할 네트워크(Grid, Admin, Client)를 결정합니다.  각 노드의 네트워크 인터페이스가 올바른 가상 또는 물리적 호스트 인터페이스에 구성되어 있는지, 그리고 각 네트워크에 충분한 대역폭이 있는지 확인해야 합니다.



=== 물리적 호스트

그리드 노드를 지원하기 위해 물리적 호스트를 사용하는 경우:

* 모든 호스트가 각 노드 인터페이스에 대해 동일한 호스트 인터페이스를 사용하는지 확인하세요.  이 전략은 호스트 구성을 단순화하고 향후 노드 마이그레이션을 가능하게 합니다.
* 물리적 호스트 자체의 IP 주소를 얻습니다.
+

NOTE: 호스트의 물리적 인터페이스는 호스트 자체와 호스트에서 실행되는 하나 이상의 노드에서 사용될 수 있습니다.  이 인터페이스를 사용하여 호스트나 노드에 할당된 모든 IP 주소는 고유해야 합니다.  호스트와 노드는 IP 주소를 공유할 수 없습니다.

* 호스트에 필요한 포트를 엽니다.
* StorageGRID 에서 VLAN 인터페이스를 사용하려면 호스트에 원하는 VLAN에 대한 액세스를 제공하는 하나 이상의 트렁크 인터페이스가 있어야 합니다.  이러한 인터페이스는 eth0, eth2 또는 추가 인터페이스로 노드 컨테이너에 전달될 수 있습니다.  트렁크 또는 액세스 인터페이스를 추가하려면 다음을 참조하세요.
+
** *RHEL(노드 설치 전)*:link:../rhel/creating-node-configuration-files.html["노드 구성 파일 생성"]
** *Ubuntu 또는 Debian(노드 설치 전)*:link:../ubuntu/creating-node-configuration-files.html["노드 구성 파일 생성"]
** *RHEL, Ubuntu 또는 Debian(노드 설치 후)*:link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux: 노드에 트렁크 또는 액세스 인터페이스 추가"]






=== 최소 대역폭 권장 사항

다음 표는 각 유형의 StorageGRID 노드와 각 유형의 네트워크에 대한 최소 LAN 대역폭 권장 사항을 제공합니다.  해당 호스트에서 실행하려는 StorageGRID 노드의 총 수와 유형에 대한 최소 집계 대역폭 요구 사항을 충족할 만큼 충분한 네트워크 대역폭을 각 물리적 또는 가상 호스트에 프로비저닝해야 합니다.

[cols="1a,1a,1a,1a"]
|===
| 노드 유형 3+| 네트워크 유형 


 a| 
 a| 
그리드
 a| 
관리자
 a| 
클라이언트



 a| 
 a| 
*최소 LAN 대역폭*



 a| 
관리자
 a| 
10Gbps
 a| 
1Gbps
 a| 
1Gbps



 a| 
게이트웨이
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps



 a| 
스토리지
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps



 a| 
보관소
 a| 
10Gbps
 a| 
1Gbps
 a| 
10Gbps

|===

NOTE: 이 표에는 공유 스토리지에 액세스하는 데 필요한 SAN 대역폭이 포함되어 있지 않습니다.  이더넷(iSCSI 또는 FCoE)을 통해 액세스하는 공유 스토리지를 사용하는 경우, 충분한 SAN 대역폭을 제공하기 위해 각 호스트에 별도의 물리적 인터페이스를 프로비저닝해야 합니다.  병목 현상이 발생하지 않도록 하려면 주어진 호스트의 SAN 대역폭이 해당 호스트에서 실행되는 모든 스토리지 노드의 총 스토리지 노드 네트워크 대역폭과 거의 일치해야 합니다.

해당 호스트에서 실행하려는 StorageGRID 노드의 수와 유형에 따라 각 호스트에 프로비저닝해야 하는 최소 네트워크 인터페이스 수를 결정하려면 표를 사용하세요.

예를 들어, 단일 호스트에서 하나의 관리 노드, 하나의 게이트웨이 노드, 하나의 스토리지 노드를 실행하려면 다음을 수행합니다.

* 관리 노드에서 그리드 및 관리 네트워크 연결(10 + 1 = 11Gbps 필요)
* 게이트웨이 노드에서 그리드 및 클라이언트 네트워크 연결(10 + 10 = 20Gbps 필요)
* 스토리지 노드에 그리드 네트워크 연결(10Gbps 필요)


이 시나리오에서는 최소 11 + 20 + 10 = 41Gbps의 네트워크 대역폭을 제공해야 하며, 이는 2개의 40Gbps 인터페이스 또는 5개의 10Gbps 인터페이스로 충족할 수 있으며, 잠재적으로 트렁크로 집계된 다음 호스트가 포함된 물리적 데이터 센터의 로컬 Grid, Admin 및 Client 서브넷을 전달하는 3개 이상의 VLAN에서 공유됩니다.

StorageGRID 배포를 준비하기 위해 StorageGRID 클러스터의 호스트에서 물리적 및 네트워크 리소스를 구성하는 데 권장되는 방법은 다음을 참조하세요.

* link:../rhel/configuring-host-network.html["호스트 네트워크 구성(Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html["호스트 네트워크 구성(Ubuntu 또는 Debian)"]

