---
permalink: network/network-installation-and-provisioning.html 
sidebar: sidebar 
keywords: network install, network provisioning 
summary: 노드 배포 및 그리드 구성 중에 그리드 네트워크와 선택 사항인 관리자 및 클라이언트 네트워크가 어떻게 사용되는지 이해해야 합니다. 
---
= 네트워크 설치 및 프로비저닝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 배포 및 그리드 구성 중에 그리드 네트워크와 선택 사항인 관리자 및 클라이언트 네트워크가 어떻게 사용되는지 이해해야 합니다.



== 노드의 초기 배포

노드를 처음 배포할 때는 노드를 그리드 네트워크에 연결하고 기본 관리 노드에 액세스할 수 있는지 확인해야 합니다.  그리드 네트워크가 격리된 경우 그리드 네트워크 외부에서 구성 및 설치에 액세스할 수 있도록 기본 관리 노드에서 관리 네트워크를 구성할 수 있습니다.

게이트웨이가 구성된 그리드 네트워크는 배포 중에 노드의 기본 게이트웨이가 됩니다.  기본 게이트웨이를 사용하면 그리드가 구성되기 전에 별도 서브넷에 있는 그리드 노드가 기본 관리 노드와 통신할 수 있습니다.

필요한 경우 NTP 서버를 포함하거나 Grid Manager 또는 API에 대한 액세스가 필요한 서브넷도 그리드 서브넷으로 구성할 수 있습니다.



== 기본 관리 노드를 사용한 자동 노드 등록

노드가 배포된 후 그리드 네트워크를 사용하여 기본 관리 노드에 등록됩니다.  그런 다음 Grid Manager를 사용할 수 있습니다. `configure-storagegrid.py` Python 스크립트 또는 설치 API를 사용하여 그리드를 구성하고 등록된 노드를 승인합니다.  그리드 구성 중에 여러 개의 그리드 서브넷을 구성할 수 있습니다.  그리드 구성을 완료하면 Grid Network 게이트웨이를 통해 이러한 서브넷으로 가는 정적 경로가 각 노드에 생성됩니다.



== 관리자 네트워크 또는 클라이언트 네트워크 비활성화

관리 네트워크 또는 클라이언트 네트워크를 비활성화하려면 노드 승인 프로세스 중에 해당 네트워크의 구성을 제거하거나 설치가 완료된 후 IP 변경 도구를 사용할 수 있습니다(참조).link:../maintain/configuring-ip-addresses.html["IP 주소 구성"] ).
