---
permalink: network/network-specific-requirements.html 
sidebar: sidebar 
keywords: network-specific requirements, network specific requirements, network requirements 
summary: 각 StorageGRID 네트워크 유형에 대한 요구 사항을 따르세요. 
---
= 네트워크별 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 StorageGRID 네트워크 유형에 대한 요구 사항을 따르세요.



== 네트워크 게이트웨이 및 라우터

* 설정된 경우, 주어진 네트워크의 게이트웨이는 특정 네트워크의 서브넷 내에 있어야 합니다.
* 정적 주소 지정을 사용하여 인터페이스를 구성하는 경우 0.0.0.0이 아닌 게이트웨이 주소를 지정해야 합니다.
* 게이트웨이가 없는 경우 가장 좋은 방법은 게이트웨이 주소를 네트워크 인터페이스의 IP 주소로 설정하는 것입니다.




== 서브넷


NOTE: 각 네트워크는 노드의 다른 네트워크와 겹치지 않는 자체 서브넷에 연결되어야 합니다.

다음 제한 사항은 배포 중에 Grid Manager에 의해 적용됩니다.  이러한 정보는 배포 전 네트워크 계획을 돕기 위해 제공됩니다.

* 모든 네트워크 IP 주소의 서브넷 마스크는 255.255.255.254 또는 255.255.255.255(CIDR 표기법으로 /31 또는 /32)가 될 수 없습니다.
* 네트워크 인터페이스 IP 주소와 서브넷 마스크(CIDR)로 정의된 서브넷은 동일한 노드에 구성된 다른 인터페이스의 서브넷과 겹칠 수 없습니다.
* 다음 IPv4 주소가 포함된 서브넷은 모든 노드의 그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크에 사용하지 마세요.
+
** 192,168,130,101
** 192,168,131,101
** 192,168,130,102
** 192,168,131,102
** 198.51.100.2
** 198.51.100.4


+
예를 들어, 어떤 노드의 그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크에도 다음 서브넷 범위를 사용하지 마세요.

+
** 192.168.130.0/24는 이 서브넷 범위에 IP 주소 192.168.130.101 및 192.168.130.102가 포함되어 있기 때문입니다.
** 192.168.131.0/24는 이 서브넷 범위에 IP 주소 192.168.131.101 및 192.168.131.102가 포함되어 있기 때문입니다.
** 198.51.100.0/24는 이 서브넷 범위에 IP 주소 198.51.100.2와 198.51.100.4가 포함되어 있기 때문입니다.


* 각 노드의 그리드 네트워크 서브넷은 GNSL에 포함되어야 합니다.
* 관리 네트워크 서브넷은 그리드 네트워크 서브넷, 클라이언트 네트워크 서브넷 또는 GNSL의 서브넷과 겹칠 수 없습니다.
* AESL의 서브넷은 GNSL의 서브넷과 겹칠 수 없습니다.
* 클라이언트 네트워크 서브넷은 그리드 네트워크 서브넷, 관리 네트워크 서브넷, GNSL의 서브넷 또는 AESL의 서브넷과 겹칠 수 없습니다.




== 그리드 네트워크

* 배포 시점에 각 그리드 노드는 그리드 네트워크에 연결되어야 하며 노드를 배포할 때 지정한 네트워킹 구성을 사용하여 기본 관리 노드와 통신할 수 있어야 합니다.
* 일반적인 그리드 운영 중에 각 그리드 노드는 그리드 네트워크를 통해 다른 모든 그리드 노드와 통신할 수 있어야 합니다.
+

NOTE: 그리드 네트워크는 각 노드 간에 직접 라우팅이 가능해야 합니다.  노드 간 네트워크 주소 변환(NAT)이 지원되지 않습니다.

* 그리드 네트워크가 여러 서브넷으로 구성된 경우 그리드 네트워크 서브넷 목록(GNSL)에 추가합니다.  GNSL의 각 서브넷에 대한 모든 노드에 정적 경로가 생성됩니다.
* Grid Network 인터페이스가 VLAN 인터페이스를 지원하기 위해 트렁크로 구성된 경우, 트렁크 네이티브 VLAN은 Grid Network 트래픽에 사용되는 VLAN이어야 합니다.  모든 그리드 노드는 트렁크 네이티브 VLAN을 통해 접근할 수 있어야 합니다.




== 관리자 네트워크

관리자 네트워크는 선택 사항입니다.  관리자 네트워크를 구성하려면 다음 요구 사항과 지침을 따르세요.

관리 네트워크의 일반적인 사용 사례로는 관리 연결, AutoSupport, KMS, 그리고 이러한 연결이 그리드 네트워크나 클라이언트 네트워크를 통해 제공되지 않는 경우 NTP, DNS, LDAP와 같은 중요 서버에 대한 연결이 있습니다.


NOTE: 원하는 네트워크 서비스와 클라이언트에 접근할 수 있는 한, 관리 네트워크와 AESL은 각 노드마다 고유할 수 있습니다.


NOTE: 외부 서브넷에서 인바운드 연결을 활성화하려면 관리 네트워크에서 하나 이상의 서브넷을 정의해야 합니다.  AESL의 각 서브넷에 대한 정적 경로는 각 노드에서 자동으로 생성됩니다.



== 클라이언트 네트워크

클라이언트 네트워크는 선택 사항입니다.  클라이언트 네트워크를 구성하려는 경우 다음 사항을 고려하세요.

* 클라이언트 네트워크는 S3 클라이언트의 트래픽을 지원하도록 설계되었습니다.  구성된 경우 클라이언트 네트워크 게이트웨이가 노드의 기본 게이트웨이가 됩니다.
* 클라이언트 네트워크를 사용하면 명시적으로 구성된 로드 밸런서 엔드포인트에서만 인바운드 클라이언트 트래픽을 허용하여 StorageGRID 적대적인 공격으로부터 보호할 수 있습니다. 보다 link:../admin/configuring-load-balancer-endpoints.html["로드 밸런서 엔드포인트 구성"] .
* 클라이언트 네트워크 인터페이스가 VLAN 인터페이스를 지원하기 위해 트렁크로 구성된 경우 클라이언트 네트워크 인터페이스(eth2)를 구성하는 것이 필요한지 고려하세요.  구성된 경우, 클라이언트 네트워크 트래픽은 스위치에 구성된 대로 트렁크 네이티브 VLAN을 통해 흐릅니다.


.관련 정보
link:../maintain/changing-nodes-network-configuration.html["노드 네트워크 구성 변경"]
