---
permalink: network/networking-and-ports-for-platform-services-and-cloud-storage-pools.html 
sidebar: sidebar 
keywords: networking for platform services, networking for cloud storage pools 
summary: StorageGRID 플랫폼 서비스나 Cloud Storage Pools를 사용하려면 대상 엔드포인트에 도달할 수 있도록 그리드 네트워킹과 방화벽을 구성해야 합니다. 
---
= 플랫폼 서비스 및 클라우드 스토리지 풀을 위한 네트워킹 및 포트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 플랫폼 서비스나 Cloud Storage Pools를 사용하려면 대상 엔드포인트에 도달할 수 있도록 그리드 네트워킹과 방화벽을 구성해야 합니다.



== 플랫폼 서비스를 위한 네트워킹

에서 설명한 대로link:../admin/manage-platform-services-for-tenants.html["테넌트를 위한 플랫폼 서비스 관리"] 그리고link:../tenant/considerations-for-platform-services.html["플랫폼 서비스 관리"] 플랫폼 서비스에는 검색 통합, 이벤트 알림, CloudMirror 복제를 제공하는 외부 서비스가 포함됩니다.

플랫폼 서비스는 StorageGRID ADC 서비스를 호스팅하는 스토리지 노드에서 외부 서비스 엔드포인트로의 액세스가 필요합니다.  접근성을 제공하기 위한 예는 다음과 같습니다.

* ADC 서비스가 있는 스토리지 노드에서 대상 엔드포인트로 라우팅되는 AESL 항목이 있는 고유한 관리 네트워크를 구성합니다.
* 클라이언트 네트워크에서 제공하는 기본 경로를 사용합니다.  기본 경로를 사용하면 다음을 사용할 수 있습니다.link:../admin/manage-firewall-controls.html["신뢰할 수 없는 클라이언트 네트워크 기능"] 인바운드 연결을 제한합니다.




== 클라우드 스토리지 풀을 위한 네트워킹

클라우드 스토리지 풀은 Amazon S3 Glacier나 Microsoft Azure Blob 스토리지와 같은 외부 서비스가 제공하는 엔드포인트에 대한 스토리지 노드의 액세스도 필요로 합니다. 자세한 내용은 다음을 참조하세요.link:../ilm/what-cloud-storage-pool-is.html["클라우드 스토리지 풀이란?"] .



== 플랫폼 서비스 및 클라우드 스토리지 풀을 위한 포트

기본적으로 플랫폼 서비스와 클라우드 스토리지 풀 통신은 다음 포트를 사용합니다.

* *80*: 다음으로 시작하는 엔드포인트 URI의 경우 `http`
* *443*: 다음으로 시작하는 엔드포인트 URI의 경우 `https`


엔드포인트를 생성하거나 편집할 때 다른 포트를 지정할 수 있습니다. 보다 link:internal-grid-node-communications.html["네트워크 포트 참조"] .

투명하지 않은 프록시 서버를 사용하는 경우에도 다음을 수행해야 합니다.link:../admin/configuring-storage-proxy-settings.html["저장소 프록시 설정 구성"] 메시지를 인터넷 상의 엔드포인트와 같은 외부 엔드포인트로 보낼 수 있도록 허용합니다.



== VLAN 및 플랫폼 서비스 및 클라우드 스토리지 풀

플랫폼 서비스나 클라우드 스토리지 풀에는 VLAN 네트워크를 사용할 수 없습니다.  대상 엔드포인트는 그리드, 관리자 또는 클라이언트 네트워크를 통해 도달할 수 있어야 합니다.
