---
permalink: network/storagegrid-network-types.html 
sidebar: sidebar 
keywords: network types, grid traffic, admin traffic, client traffic, grid network, admin network, client network 
summary: StorageGRID 시스템의 그리드 노드는 그리드 트래픽, 관리 트래픽, 클라이언트 트래픽을 처리합니다.  이 세 가지 유형의 트래픽을 관리하고 제어 및 보안을 제공하려면 네트워킹을 적절하게 구성해야 합니다. 
---
= StorageGRID 네트워크 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템의 그리드 노드는 _그리드 트래픽_, _관리자 트래픽_, _클라이언트 트래픽_을 처리합니다.  이 세 가지 유형의 트래픽을 관리하고 제어 및 보안을 제공하려면 네트워킹을 적절하게 구성해야 합니다.



== 교통 유형

[cols="1a,4a,2a"]
|===
| 교통 유형 | 설명 | 네트워크 유형 


 a| 
그리드 트래픽
 a| 
그리드의 모든 노드 사이를 이동하는 내부 StorageGRID 트래픽입니다.  모든 그리드 노드는 이 네트워크를 통해 다른 모든 그리드 노드와 통신할 수 있어야 합니다.
 a| 
그리드 네트워크(필수)



 a| 
관리자 트래픽
 a| 
시스템 관리 및 유지관리에 사용되는 트래픽입니다.
 a| 
관리자 네트워크(선택 사항),<<선택적 VLAN 네트워크,VLAN 네트워크(선택 사항)>>



 a| 
클라이언트 트래픽
 a| 
S3 클라이언트의 모든 개체 스토리지 요청을 포함하여 외부 클라이언트 애플리케이션과 그리드 간을 이동하는 트래픽입니다.
 a| 
클라이언트 네트워크(선택 사항),<<선택적 VLAN 네트워크,VLAN 네트워크(선택 사항)>>

|===
다음과 같은 방법으로 네트워킹을 구성할 수 있습니다.

* 그리드 네트워크만
* 그리드 및 관리 네트워크
* 그리드 및 클라이언트 네트워크
* 그리드, 관리 및 클라이언트 네트워크


그리드 네트워크는 필수이며 모든 그리드 트래픽을 관리할 수 있습니다.  관리자 및 클라이언트 네트워크는 설치 시에 포함하거나 나중에 요구 사항의 변경에 맞춰 추가할 수 있습니다.  관리 네트워크와 클라이언트 네트워크는 선택 사항이지만, 이러한 네트워크를 사용하여 관리 및 클라이언트 트래픽을 처리하는 경우 그리드 네트워크를 격리하고 안전하게 보호할 수 있습니다.

내부 포트는 그리드 네트워크를 통해서만 접근할 수 있습니다.  외부 포트는 모든 네트워크 유형에서 접근할 수 있습니다.  이러한 유연성은 StorageGRID 배포를 설계하고 스위치와 방화벽에서 외부 IP 및 포트 필터링을 설정하는 데 다양한 옵션을 제공합니다. 보다link:../network/internal-grid-node-communications.html["내부 그리드 노드 통신"] 그리고link:../network/external-communications.html["외부 커뮤니케이션"] .



== 네트워크 인터페이스

StorageGRID 노드는 다음과 같은 특정 인터페이스를 사용하여 각 네트워크에 연결됩니다.

[cols="1a,1a"]
|===
| 회로망 | 인터페이스 이름 


 a| 
그리드 네트워크(필수)
 a| 
eth0



 a| 
관리자 네트워크(선택 사항)
 a| 
eth1



 a| 
클라이언트 네트워크(선택 사항)
 a| 
eth2

|===
가상 또는 물리적 포트를 노드 네트워크 인터페이스에 매핑하는 방법에 대한 자세한 내용은 설치 지침을 참조하세요.

.소프트웨어 기반 노드
* link:../rhel/index.html["Red Hat Enterprise Linux에 StorageGRID 설치"]
* link:../ubuntu/index.html["Ubuntu 또는 Debian에 StorageGRID 설치"]
* link:../vmware/index.html["VMware에 StorageGRID 설치"]


.어플라이언스 노드
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg6100.html["SG6160 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg6100.html["SGF6112 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg6000.html["SG6000 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg5800.html["SG5800 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg5700.html["SG5700 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg110-and-1100.html["SG110 및 SG1100 서비스 기기"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/hardware-description-sg100-and-1000.html["SG100 및 SG1000 서비스 기기"^]




=== 각 노드에 대한 네트워크 정보

노드에서 활성화하는 각 네트워크에 대해 다음을 구성해야 합니다.

* IP 주소
* 서브넷 마스크
* 게이트웨이 IP 주소


각 그리드 노드의 세 네트워크 각각에 대해 하나의 IP 주소/마스크/게이트웨이 조합만 구성할 수 있습니다.  네트워크에 대한 게이트웨이를 구성하지 않으려면 IP 주소를 게이트웨이 주소로 사용해야 합니다.



=== 고가용성 그룹

고가용성(HA) 그룹은 그리드 또는 클라이언트 네트워크 인터페이스에 가상 IP(VIP) 주소를 추가하는 기능을 제공합니다. 자세한 내용은 다음을 참조하세요. link:../admin/managing-high-availability-groups.html["고가용성 그룹 관리"] .



== 그리드 네트워크

그리드 네트워크가 필요합니다.  이는 모든 내부 StorageGRID 트래픽에 사용됩니다.  그리드 네트워크는 모든 사이트와 서브넷에 걸쳐 그리드의 모든 노드 간에 연결을 제공합니다.  그리드 네트워크의 모든 노드는 다른 모든 노드와 통신할 수 있어야 합니다.  그리드 네트워크는 여러 개의 서브넷으로 구성될 수 있습니다.  NTP와 같은 중요한 그리드 서비스를 포함하는 네트워크도 그리드 서브넷으로 추가할 수 있습니다.


NOTE: StorageGRID 노드 간 NAT(네트워크 주소 변환)를 지원하지 않습니다.

관리 네트워크와 클라이언트 네트워크가 구성된 경우에도 모든 관리 트래픽과 모든 클라이언트 트래픽에 그리드 네트워크를 사용할 수 있습니다.  클라이언트 네트워크가 노드에 구성되어 있지 않으면 그리드 네트워크 게이트웨이가 노드 기본 게이트웨이입니다.


CAUTION: 그리드 네트워크를 구성할 때는 개방형 인터넷과 같은 신뢰할 수 없는 클라이언트로부터 네트워크가 보호되는지 확인해야 합니다.

Grid Network 게이트웨이에 대한 다음 요구 사항과 세부 정보를 참고하세요.

* 여러 개의 그리드 서브넷이 있는 경우 그리드 네트워크 게이트웨이를 구성해야 합니다.
* 그리드 네트워크 게이트웨이는 그리드 구성이 완료될 때까지 노드 기본 게이트웨이입니다.
* 글로벌 그리드 네트워크 서브넷 목록에 구성된 모든 서브넷의 모든 노드에 대해 정적 경로가 자동으로 생성됩니다.
* 클라이언트 네트워크가 추가되면 그리드 구성이 완료되면 기본 게이트웨이가 그리드 네트워크 게이트웨이에서 클라이언트 네트워크 게이트웨이로 전환됩니다.




== 관리자 네트워크

관리자 네트워크는 선택 사항입니다.  구성하면 시스템 관리 및 유지 관리 트래픽에 사용할 수 있습니다.  관리 네트워크는 일반적으로 개인 네트워크이므로 노드 간에 라우팅할 필요가 없습니다.

어떤 그리드 노드에 관리자 네트워크를 활성화할지 선택할 수 있습니다.

관리 네트워크를 사용하면 관리 및 유지 관리 트래픽이 그리드 네트워크를 통해 이동할 필요가 없습니다.  관리 네트워크의 일반적인 사용 사례는 다음과 같습니다.

* Grid Manager 및 Tenant Manager 사용자 인터페이스에 액세스합니다.
* NTP 서버, DNS 서버, 외부 키 관리 서버(KMS), Lightweight Directory Access Protocol(LDAP) 서버와 같은 중요 서비스에 액세스할 수 있습니다.
* 관리 노드의 감사 로그에 액세스합니다.
* 유지관리 및 지원을 위해 SSH(Secure Shell Protocol)에 액세스합니다.


관리 네트워크는 내부 그리드 트래픽에 사용되지 않습니다.  관리 네트워크 게이트웨이가 제공되며, 이를 통해 관리 네트워크가 여러 외부 서브넷과 통신할 수 있습니다.  그러나 관리 네트워크 게이트웨이는 노드 기본 게이트웨이로 사용되지 않습니다.

관리 네트워크 게이트웨이에 대한 다음 요구 사항과 세부 정보를 참고하세요.

* 관리 네트워크 서브넷 외부에서 연결이 이루어지거나 여러 관리 네트워크 서브넷이 구성된 경우 관리 네트워크 게이트웨이가 필요합니다.
* 노드의 관리 네트워크 서브넷 목록에 구성된 각 서브넷에 대해 정적 경로가 생성됩니다.




== 클라이언트 네트워크

클라이언트 네트워크는 선택 사항입니다.  구성하면 S3와 같은 클라이언트 애플리케이션에 대한 그리드 서비스에 대한 액세스를 제공하는 데 사용됩니다.  StorageGRID 데이터를 외부 리소스(예: 클라우드 스토리지 풀 또는 StorageGRID CloudMirror 복제 서비스)에서 액세스할 수 있도록 계획하는 경우 외부 리소스도 클라이언트 네트워크를 사용할 수 있습니다.  그리드 노드는 클라이언트 네트워크 게이트웨이를 통해 도달 가능한 모든 서브넷과 통신할 수 있습니다.

어떤 그리드 노드에서 클라이언트 네트워크를 활성화할지 선택할 수 있습니다.  모든 노드가 동일한 클라이언트 네트워크에 있을 필요는 없으며, 노드는 클라이언트 네트워크를 통해 서로 통신하지 않습니다.  그리드 설치가 완료될 때까지 클라이언트 네트워크는 작동하지 않습니다.

보안을 강화하기 위해 노드의 클라이언트 네트워크 인터페이스를 신뢰할 수 없도록 지정하여 클라이언트 네트워크에서 허용되는 연결을 더욱 제한할 수 있습니다.  노드의 클라이언트 네트워크 인터페이스를 신뢰할 수 없는 경우 해당 인터페이스는 CloudMirror 복제에 사용되는 것과 같은 아웃바운드 연결을 허용하지만, 로드 밸런서 엔드포인트로 명시적으로 구성된 포트에서만 인바운드 연결을 허용합니다. 보다link:../admin/manage-firewall-controls.html["방화벽 제어 관리"] 그리고link:../admin/configuring-load-balancer-endpoints.html["로드 밸런서 엔드포인트 구성"] .

클라이언트 네트워크를 사용하면 클라이언트 트래픽이 그리드 네트워크를 통과할 필요가 없습니다.  그리드 네트워크 트래픽은 안전하고 라우팅이 불가능한 네트워크로 분리될 수 있습니다.  다음 노드 유형은 종종 클라이언트 네트워크로 구성됩니다.

* 게이트웨이 노드는 StorageGRID 로드 밸런서 서비스에 대한 액세스와 S3 클라이언트가 그리드에 액세스할 수 있도록 하기 때문입니다.
* 스토리지 노드는 S3 프로토콜과 클라우드 스토리지 풀, CloudMirror 복제 서비스에 대한 액세스를 제공하기 때문입니다.
* 관리 노드는 테넌트 사용자가 관리 네트워크를 사용하지 않고도 테넌트 관리자에 연결할 수 있도록 보장합니다.


클라이언트 네트워크 게이트웨이에 대해 다음 사항을 참고하세요.

* 클라이언트 네트워크가 구성된 경우 클라이언트 네트워크 게이트웨이가 필요합니다.
* 그리드 구성이 완료되면 클라이언트 네트워크 게이트웨이가 그리드 노드의 기본 경로가 됩니다.




== 선택적 VLAN 네트워크

필요에 따라 클라이언트 트래픽과 일부 유형의 관리 트래픽에 대해 가상 LAN(VLAN) 네트워크를 선택적으로 사용할 수 있습니다.  하지만 그리드 트래픽은 VLAN 인터페이스를 사용할 수 없습니다.  노드 간의 내부 StorageGRID 트래픽은 항상 eth0의 Grid Network를 사용해야 합니다.

VLAN 사용을 지원하려면 스위치에서 노드의 하나 이상의 인터페이스를 트렁크 인터페이스로 구성해야 합니다.  그리드 네트워크 인터페이스(eth0) 또는 클라이언트 네트워크 인터페이스(eth2)를 트렁크로 구성하거나 노드에 트렁크 인터페이스를 추가할 수 있습니다.

eth0가 트렁크로 구성된 경우, Grid Network 트래픽은 스위치에 구성된 대로 트렁크 네이티브 인터페이스를 통해 흐릅니다.  마찬가지로 eth2가 트렁크로 구성되고 클라이언트 네트워크도 같은 노드에 구성된 경우, 클라이언트 네트워크는 스위치에 구성된 트렁크 포트의 기본 VLAN을 사용합니다.

SSH, Grid Manager 또는 Tenant Manager 트래픽에 사용되는 인바운드 관리 트래픽만 VLAN 네트워크에서 지원됩니다.  NTP, DNS, LDAP, KMS 및 클라우드 스토리지 풀에 사용되는 아웃바운드 트래픽은 VLAN 네트워크에서 지원되지 않습니다.


NOTE: VLAN 인터페이스는 관리 노드와 게이트웨이 노드에만 추가할 수 있습니다.  클라이언트 또는 관리자가 스토리지 노드에 액세스하는 데 VLAN 인터페이스를 사용할 수 없습니다.

보다link:../admin/configure-vlan-interfaces.html["VLAN 인터페이스 구성"] 지침과 가이드라인을 확인하세요.

VLAN 인터페이스는 HA 그룹에서만 사용되며 활성 노드에서 VIP 주소가 할당됩니다.  보다link:../admin/managing-high-availability-groups.html["고가용성 그룹 관리"] 지침과 가이드라인을 확인하세요.
