= 스토리지 노드의 호스트 이름 찾기
:allow-uri-read: 




== 스토리지 노드의 호스트 이름 찾기

. 기본 관리 노드에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh admin@_primary_Admin_Node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. 사용하다 `/etc/hosts` 복구된 스토리지 볼륨에 대한 스토리지 노드의 호스트 이름을 찾으려면 파일을 사용합니다.  그리드의 모든 노드 목록을 보려면 다음을 입력하세요. `cat /etc/hosts` .




== 모든 볼륨이 실패한 경우 데이터 복구

모든 스토리지 볼륨에 오류가 발생한 경우 전체 노드를 복구합니다.  복제된 데이터, 삭제 코딩된(EC) 데이터 또는 둘 다를 사용하는지 여부에 따라 *복제된 데이터*, *삭제 코딩된(EC) 데이터* 또는 둘 다에 대한 지침을 따르세요.

일부 볼륨만 실패한 경우 다음으로 이동하세요.<<일부 볼륨만 실패한 경우 데이터 복구>> .


NOTE: 당신은 달릴 수 없습니다 `repair-data` 동시에 여러 노드에 대한 작업을 수행합니다.  여러 노드를 복구하려면 기술 지원팀에 문의하세요.

[role="tabbed-block"]
====
.복제된 데이터
--
그리드에 복제된 데이터가 포함되어 있는 경우 다음을 사용하세요. `repair-data start-replicated-node-repair` 명령으로 `--nodes` 옵션, 여기서 `--nodes` 전체 스토리지 노드를 복구하기 위한 호스트 이름(시스템 이름)입니다.

이 명령은 SG-DC-SN3이라는 스토리지 노드에서 복제된 데이터를 복구합니다.

`repair-data start-replicated-node-repair --nodes SG-DC-SN3`


NOTE: 개체 데이터가 복원되면 StorageGRID 시스템이 복제된 개체 데이터를 찾을 수 없는 경우 *개체 손실* 경고가 트리거됩니다. 시스템 전체의 스토리지 노드에서 경고가 발생할 수 있습니다. 손실의 원인을 파악하고 회복이 가능한지 확인해야 합니다. 보다 link:../troubleshoot/investigating-lost-objects.html["분실물을 조사하세요"] .

--
.삭제 코드(EC) 데이터
--
그리드에 삭제 코드 데이터가 포함되어 있는 경우 다음을 사용하세요. `repair-data start-ec-node-repair` 명령으로 `--nodes` 옵션, 여기서 `--nodes` 전체 스토리지 노드를 복구하기 위한 호스트 이름(시스템 이름)입니다.

이 명령은 SG-DC-SN3이라는 스토리지 노드에서 삭제된 데이터를 복구합니다.

`repair-data start-ec-node-repair --nodes SG-DC-SN3`

이 작업은 고유한 값을 반환합니다. `repair ID` 이것을 식별하는 `repair_data` 작업.  이것을 사용하세요 `repair ID` 진행 상황과 결과를 추적하려면 `repair_data` 작업.  복구 프로세스가 완료되면 다른 피드백은 반환되지 않습니다.

삭제된 데이터의 복구는 일부 스토리지 노드가 오프라인 상태인 동안에도 시작될 수 있습니다.  모든 노드를 사용할 수 있게 되면 복구가 완료됩니다.

--
====


== 일부 볼륨만 실패한 경우 데이터 복구

일부 볼륨만 실패한 경우 영향을 받은 볼륨을 복구합니다.  복제된 데이터, 삭제 코딩된(EC) 데이터 또는 둘 다를 사용하는지 여부에 따라 *복제된 데이터*, *삭제 코딩된(EC) 데이터* 또는 둘 다에 대한 지침을 따르세요.

모든 볼륨이 실패한 경우 다음으로 이동하세요.<<모든 볼륨이 실패한 경우 데이터 복구>> .

볼륨 ID를 16진수로 입력하세요.  예를 들어, `0000` 첫 번째 볼륨이고 `000F` 16번째 권입니다.  하나의 볼륨, 볼륨 범위 또는 순서에 속하지 않는 여러 볼륨을 지정할 수 있습니다.

모든 볼륨은 동일한 스토리지 노드에 있어야 합니다.  두 개 이상의 스토리지 노드에 대한 볼륨을 복원해야 하는 경우 기술 지원팀에 문의하세요.

[role="tabbed-block"]
====
.복제된 데이터
--
그리드에 복제된 데이터가 포함되어 있는 경우 다음을 사용하세요. `start-replicated-volume-repair` 명령으로 `--nodes` 노드를 식별하는 옵션(여기서 `--nodes` (노드의 호스트 이름입니다).  그런 다음 다음 중 하나를 추가하세요. `--volumes` 또는 `--volume-range` 다음 예에서 볼 수 있듯이 옵션입니다.

*단일 볼륨*: 이 명령은 복제된 데이터를 볼륨으로 복원합니다. `0002` SG-DC-SN3이라는 스토리지 노드에서:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0002`

*볼륨 범위*: 이 명령은 범위 내의 모든 볼륨에 복제된 데이터를 복원합니다. `0003` 에게 `0009` SG-DC-SN3이라는 스토리지 노드에서:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volume-range 0003,0009`

*순서가 아닌 여러 볼륨*: 이 명령은 복제된 데이터를 볼륨으로 복원합니다. `0001` , `0005` , 그리고 `0008` SG-DC-SN3이라는 스토리지 노드에서:

`repair-data start-replicated-volume-repair --nodes SG-DC-SN3 --volumes 0001,0005,0008`


NOTE: 개체 데이터가 복원되면 StorageGRID 시스템이 복제된 개체 데이터를 찾을 수 없는 경우 *개체 손실* 경고가 트리거됩니다. 시스템 전체의 스토리지 노드에서 경고가 발생할 수 있습니다. 손실 원인을 파악하고 복구가 가능한지 확인하려면 알림 설명과 권장 조치를 확인하세요.

--
.삭제 코드(EC) 데이터
--
그리드에 삭제 코드 데이터가 포함되어 있는 경우 다음을 사용하세요. `start-ec-volume-repair` 명령으로 `--nodes` 노드를 식별하는 옵션(여기서 `--nodes` (노드의 호스트 이름입니다).  그런 다음 다음 중 하나를 추가하세요. `--volumes` 또는 `--volume-range` 다음 예에서 볼 수 있듯이 옵션입니다.

*단일 볼륨*: 이 명령은 삭제된 데이터를 볼륨으로 복원합니다. `0007` SG-DC-SN3이라는 스토리지 노드에서:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 0007`

*볼륨 범위*: 이 명령은 범위 내의 모든 볼륨에 삭제 코딩된 데이터를 복원합니다. `0004` 에게 `0006` SG-DC-SN3이라는 스토리지 노드에서:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volume-range 0004,0006`

*순서가 없는 여러 볼륨*: 이 명령은 삭제된 데이터를 볼륨으로 복원합니다. `000A` , `000C` , 그리고 `000E` SG-DC-SN3이라는 스토리지 노드에서:

`repair-data start-ec-volume-repair --nodes SG-DC-SN3 --volumes 000A,000C,000E`

그만큼 `repair-data` 작업은 고유한 값을 반환합니다. `repair ID` 이것을 식별하는 `repair_data` 작업.  이것을 사용하세요 `repair ID` 진행 상황과 결과를 추적하려면 `repair_data` 작업.  복구 프로세스가 완료되면 다른 피드백은 반환되지 않습니다.


NOTE: 삭제된 데이터의 복구는 일부 스토리지 노드가 오프라인 상태인 동안에도 시작될 수 있습니다.  모든 노드를 사용할 수 있게 되면 복구가 완료됩니다.

--
====