= S3 객체 잠금이란 무엇인가요?
:allow-uri-read: 




== S3 객체 잠금이란 무엇인가요?

StorageGRID S3 객체 잠금 기능은 Amazon Simple Storage Service(Amazon S3)의 S3 객체 잠금과 동일한 객체 보호 솔루션입니다.

StorageGRID 시스템에 대해 글로벌 S3 개체 잠금 설정이 활성화된 경우 S3 테넌트 계정은 S3 개체 잠금이 활성화되어 있거나 활성화되지 않은 버킷을 생성할 수 있습니다.  버킷에 S3 객체 잠금이 활성화된 경우 버킷 버전 관리가 필요하며 자동으로 활성화됩니다.

*S3 객체 잠금이 없는 버킷*에는 보존 설정이 지정되지 않은 객체만 있을 수 있습니다.  섭취된 객체에는 보존 설정이 없습니다.

*S3 객체 잠금이 있는 버킷*에는 S3 클라이언트 애플리케이션에서 지정한 보존 설정이 있는 객체와 없는 객체가 있을 수 있습니다.  수집된 일부 객체에는 보존 설정이 있습니다.

*S3 객체 잠금 및 기본 보존 기간이 구성된 버킷*에는 보존 기간이 지정된 객체를 업로드할 수 있으며 보존 기간이 설정되지 않은 새 객체를 업로드할 수 있습니다.  새 개체는 보존 설정이 개체 수준에서 구성되지 않았기 때문에 기본 설정을 사용합니다.

실제로 기본 보존이 구성된 경우 새로 수집된 모든 개체에는 보존 설정이 적용됩니다.  객체 보존 설정이 없는 기존 객체는 영향을 받지 않습니다.



=== 보존 모드

StorageGRID S3 객체 잠금 기능은 객체에 다양한 수준의 보호를 적용하기 위해 두 가지 보존 모드를 지원합니다.  이러한 모드는 Amazon S3 보존 모드와 동일합니다.

* 규정 준수 모드에서:
+
** 해당 객체는 보관 만료일에 도달할 때까지 삭제할 수 없습니다.
** 객체의 보관 기한은 늘릴 수 있지만 줄일 수는 없습니다.
** 해당 날짜에 도달하기 전까지는 객체의 보관 기간을 제거할 수 없습니다.


* 거버넌스 모드에서:
+
** 특별 권한이 있는 사용자는 요청에서 우회 헤더를 사용하여 특정 보존 설정을 수정할 수 있습니다.
** 이러한 사용자는 보관 기한에 도달하기 전에 개체 버전을 삭제할 수 있습니다.
** 이러한 사용자는 객체의 보관 기간을 늘리거나 줄이거나 제거할 수 있습니다.






=== 객체 버전에 대한 보존 설정

S3 객체 잠금이 활성화된 버킷을 생성한 경우 사용자는 S3 클라이언트 애플리케이션을 사용하여 버킷에 추가된 각 객체에 대해 다음과 같은 보존 설정을 선택적으로 지정할 수 있습니다.

* *보존 모드*: 규정 준수 또는 거버넌스.
* *보관 날짜*: 개체 버전의 보관 날짜가 미래인 경우, 개체를 검색할 수는 있지만 삭제할 수는 없습니다.
* *법적 보존*: 객체 버전에 법적 보존을 적용하면 해당 객체가 즉시 잠깁니다.  예를 들어, 조사나 법적 분쟁과 관련된 객체에 대해 법적 보류를 요청해야 할 수도 있습니다.  법적 보존에는 만료일이 없지만, 명시적으로 삭제하기 전까지는 유지됩니다.  법적 보존 기간은 보존 기한과 별개입니다.
+

NOTE: 객체가 법적 보존 상태에 있는 경우, 보존 모드에 관계없이 누구도 객체를 삭제할 수 없습니다.

+
객체 설정에 대한 자세한 내용은 다음을 참조하세요.link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 객체 잠금을 구성합니다."] .





=== 버킷에 대한 기본 보존 설정

S3 객체 잠금이 활성화된 버킷이 생성된 경우 사용자는 선택적으로 버킷에 대해 다음과 같은 기본 설정을 지정할 수 있습니다.

* *기본 보존 모드*: 규정 준수 또는 거버넌스.
* *기본 보존 기간*: 이 버킷에 추가된 새 개체 버전을 보존해야 하는 기간으로, 추가된 날로부터 시작됩니다.


기본 버킷 설정은 자체 보존 설정이 없는 새 개체에만 적용됩니다.  이러한 기본 설정을 추가하거나 변경해도 기존 버킷 개체는 영향을 받지 않습니다.

보다link:../tenant/creating-s3-bucket.html["S3 버킷 생성"] 그리고link:../tenant/update-default-retention-settings.html["S3 객체 잠금 기본 보존 기간 업데이트"] .
