= S3 객체 잠금이 활성화된 버킷에 대한 요구 사항
:allow-uri-read: 




== S3 객체 잠금이 활성화된 버킷에 대한 요구 사항

* StorageGRID 시스템에 대해 글로벌 S3 개체 잠금 설정이 활성화된 경우 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 S3 개체 잠금이 활성화된 버킷을 생성할 수 있습니다.
* S3 객체 잠금을 사용하려면 버킷을 생성할 때 S3 객체 잠금을 활성화해야 합니다.  기존 버킷에 대해 S3 개체 잠금을 활성화할 수 없습니다.
* 버킷에 대해 S3 객체 잠금이 활성화되면 StorageGRID 자동으로 해당 버킷에 대한 버전 관리를 활성화합니다.  버킷에 대한 S3 객체 잠금을 비활성화하거나 버전 관리를 일시 중단할 수 없습니다.
* 선택적으로 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 각 버킷에 대한 기본 보존 모드와 보존 기간을 지정할 수 있습니다.  버킷의 기본 보존 설정은 자체 보존 설정이 없는 버킷에 추가된 새 객체에만 적용됩니다.  업로드 시 각 객체 버전에 대한 보존 모드와 보존 기간을 지정하여 이러한 기본 설정을 재정의할 수 있습니다.
* 버킷 수명 주기 구성은 S3 객체 잠금이 활성화된 버킷에 대해 지원됩니다.
* S3 개체 잠금이 활성화된 버킷에서는 CloudMirror 복제가 지원되지 않습니다.




== S3 객체 잠금이 활성화된 버킷의 객체에 대한 요구 사항

* 개체 버전을 보호하려면 버킷에 대한 기본 보존 설정을 지정하거나 각 개체 버전에 대한 보존 설정을 지정할 수 있습니다.  객체 수준 보존 설정은 S3 클라이언트 애플리케이션이나 S3 REST API를 사용하여 지정할 수 있습니다.
* 보존 설정은 개별 개체 버전에 적용됩니다.  객체 버전에는 보관 마감일과 법적 보존 설정이 모두 있을 수 있으며, 둘 중 하나만 있을 수도 있고, 둘 다 없을 수도 있습니다.  객체에 대해 보관 기한 또는 법적 보존 설정을 지정하면 요청에 지정된 버전만 보호됩니다.  이전 버전의 개체는 잠긴 상태로 유지되는 동안 해당 개체의 새 버전을 만들 수 있습니다.




== S3 객체 잠금이 활성화된 버킷의 객체 수명 주기

S3 객체 잠금이 활성화된 버킷에 저장된 각 객체는 다음 단계를 거칩니다.

. *객체 수집*
+
S3 객체 잠금이 활성화된 버킷에 객체 버전이 추가되면 보존 설정이 다음과 같이 적용됩니다.

+
** 개체에 대한 보존 설정이 지정된 경우 개체 수준 설정이 적용됩니다.  모든 기본 버킷 설정은 무시됩니다.
** 개체에 대한 보존 설정이 지정되지 않은 경우 기본 버킷 설정이 적용됩니다(있는 경우).
** 객체 또는 버킷에 대한 보존 설정이 지정되지 않으면 해당 객체는 S3 객체 잠금으로 보호되지 않습니다.


+
보존 설정이 적용되면 개체와 S3 사용자 정의 메타데이터가 모두 보호됩니다.

. *객체 보존 및 삭제*
+
StorageGRID 는 각 보호된 개체의 여러 사본을 지정된 보존 기간 동안 저장합니다.  개체 복사본의 정확한 수와 유형, 저장 위치는 활성 ILM 정책의 규정에 따라 결정됩니다.  보호된 객체를 보관 기한에 도달하기 전에 삭제할 수 있는지 여부는 해당 보관 모드에 따라 달라집니다.

+
** 객체가 법적 보존 상태에 있는 경우, 보존 모드에 관계없이 누구도 객체를 삭제할 수 없습니다.



