---
permalink: tenant/changing-bucket-versioning.html 
sidebar: sidebar 
keywords: how to change bucket versioning, disabled versioning, enabled versioning, suspended versioning 
summary: S3 테넌트를 사용하는 경우 S3 버킷의 버전 상태를 변경할 수 있습니다. 
---
= 버킷의 객체 버전 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 테넌트를 사용하는 경우 S3 버킷의 버전 상태를 변경할 수 있습니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한 관리"] . 이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.
* 필요한 수의 스토리지 노드와 사이트를 사용할 수 있는지 확인했습니다.  어느 사이트 내에서도 두 개 이상의 스토리지 노드를 사용할 수 없거나 사이트를 사용할 수 없는 경우 이러한 설정을 변경하지 못할 수 있습니다.


.이 작업에 관하여
버킷에 대한 개체 버전 관리를 활성화하거나 일시 중지할 수 있습니다.  버킷에 대한 버전 관리를 활성화한 후에는 버전이 없는 상태로 돌아갈 수 없습니다.  하지만 버킷의 버전 관리를 일시 중단할 수 있습니다.

* 비활성화됨: 버전 관리가 활성화된 적이 없습니다.
* 활성화됨: 버전 관리가 활성화되었습니다.
* 일시 중단됨: 버전 관리가 이전에 활성화되었으며 일시 중단되었습니다.


자세한 내용은 다음을 참조하세요.

* link:../s3/object-versioning.html["객체 버전 관리"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 버전 객체에 대한 ILM 규칙 및 정책(예 4)"]
* link:../ilm/how-objects-are-deleted.html["객체가 삭제되는 방법"]


.단계
. 대시보드에서 *버킷 보기*를 선택하거나 *스토리지(S3)* > *버킷*을 선택하세요.
. 표에서 버킷 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. *버킷 옵션* 탭에서 *개체 버전 관리* 아코디언을 선택합니다.
. 이 버킷의 개체에 대한 버전 관리 상태를 선택합니다.
+
크로스 그리드 복제에 사용되는 버킷의 경우 개체 버전 관리가 활성화되어 있어야 합니다.  S3 개체 잠금 또는 레거시 규정 준수가 활성화된 경우 *개체 버전 관리* 옵션이 비활성화됩니다.

+
[cols="1a,3a"]
|===
| 옵션 | 설명 


 a| 
버전 관리 활성화
 a| 
이 버킷에 있는 각 개체의 모든 버전을 저장하려면 개체 버전 관리를 활성화하세요.  그러면 필요에 따라 객체의 이전 버전을 검색할 수 있습니다.

버킷에 이미 있던 객체는 사용자가 수정하면 버전이 지정됩니다.



 a| 
버전 관리 일시 중단
 a| 
더 이상 새로운 객체 버전을 생성하지 않으려면 객체 버전 관리를 일시 중단합니다.  기존 객체 버전을 검색할 수 있습니다.

|===
. *변경 사항 저장*을 선택하세요.

