---
permalink: tenant/configuring-event-notifications.html 
sidebar: sidebar 
keywords: how to configure event notifications, bucket notification 
summary: 버킷에 대한 알림을 활성화하려면 알림 구성 XML을 만들고 테넌트 관리자를 사용하여 XML을 버킷에 적용합니다. 
---
= 이벤트 알림 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버킷에 대한 알림을 활성화하려면 알림 구성 XML을 만들고 테넌트 관리자를 사용하여 XML을 버킷에 적용합니다.

.시작하기 전에
* StorageGRID 관리자가 귀하의 테넌트 계정에 대해 플랫폼 서비스를 활성화했습니다.
* 알림 소스 역할을 하는 버킷을 이미 생성했습니다.
* 이벤트 알림의 대상으로 사용하려는 엔드포인트가 이미 존재하며, 해당 엔드포인트의 URN도 있습니다.
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한 관리"] .  테넌트 관리자를 사용하여 버킷을 구성할 때 이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.


.이 작업에 관하여
이벤트 알림을 구성하려면 알림 구성 XML을 소스 버킷과 연결합니다. 알림 구성 XML은 버킷 알림을 구성하기 위한 S3 규칙을 따르며, 대상 Kafka 또는 Amazon SNS 주제는 엔드포인트의 URN으로 지정됩니다.

이벤트 알림 및 이를 구성하는 방법에 대한 일반 정보는 다음을 참조하세요. https://docs.aws.amazon.com/s3/["아마존 문서"^] .  StorageGRID S3 버킷 알림 구성 API를 구현하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:../s3/index.html["S3 클라이언트 애플리케이션 구현을 위한 지침"] .

버킷에 대한 이벤트 알림을 구성할 때 다음 요구 사항과 특성을 참고하세요.

* 유효한 알림 구성 XML을 만들고 적용하는 경우 각 대상에 대한 이벤트 알림 엔드포인트의 URN을 사용해야 합니다.
* S3 객체 잠금이 활성화된 버킷에서 이벤트 알림을 구성할 수는 있지만, 객체의 S3 객체 잠금 메타데이터(보관 기한 및 법적 보류 상태 포함)는 알림 메시지에 포함되지 않습니다.
* 이벤트 알림을 구성한 후에는 소스 버킷의 객체에 대해 지정된 이벤트가 발생할 때마다 알림이 생성되어 대상 엔드포인트로 사용되는 Amazon SNS 또는 Kafka 주제로 전송됩니다.
* 객체가 포함된 버킷에 대해 이벤트 알림을 활성화하면 알림 구성이 저장된 후 수행된 작업에 대해서만 알림이 전송됩니다.


.단계
. 소스 버킷에 대한 알림을 활성화하세요.
+
** S3 알림 API에 지정된 대로, 텍스트 편집기를 사용하여 이벤트 알림을 활성화하는 데 필요한 알림 구성 XML을 만듭니다.
** XML을 구성할 때 이벤트 알림 엔드포인트의 URN을 대상 주제로 사용합니다.
+
[listing]
----
<NotificationConfiguration>
  <TopicConfiguration>
     <Id>Image-created</Id>
     <Filter>
        <S3Key>
          <FilterRule>
            <Name>prefix</Name>
            <Value>images/</Value>
          </FilterRule>
        </S3Key>
    </Filter>
    <Topic>arn:aws:sns:us-east-1:050340950352:sgws-topic</Topic>
    <Event>s3:ObjectCreated:*</Event>
   </TopicConfiguration>
 </NotificationConfiguration>
----


. 테넌트 관리자에서 *저장소(S3)* > *버킷*을 선택합니다.
. 소스 버킷의 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. *플랫폼 서비스* > *이벤트 알림*을 선택하세요.
. *이벤트 알림 사용* 체크박스를 선택하세요.
. 알림 구성 XML을 텍스트 상자에 붙여넣고 *변경 사항 저장*을 선택합니다.
+

NOTE: StorageGRID 관리자는 Grid Manager 또는 Grid Management API를 사용하여 각 테넌트 계정에 대해 플랫폼 서비스를 활성화해야 합니다.  구성 XML을 저장할 때 오류가 발생하면 StorageGRID 관리자에게 문의하세요.

. 이벤트 알림이 올바르게 구성되었는지 확인하세요.
+
.. 구성 XML에 구성된 대로 알림을 트리거하기 위한 요구 사항을 충족하는 소스 버킷의 개체에 대한 작업을 수행합니다.
+
예에서, 객체가 생성될 때마다 이벤트 알림이 전송됩니다. `images/` 접두사.

.. 대상 Amazon SNS 또는 Kafka 주제에 알림이 전달되었는지 확인합니다.
+
예를 들어, 대상 주제가 Amazon SNS에 호스팅된 경우 알림이 전달되면 이메일을 보내도록 서비스를 구성할 수 있습니다.

+
[listing]
----
{
   "Records":[
      {
         "eventVersion":"2.0",
         "eventSource":"sgws:s3",
         "eventTime":"2017-08-08T23:52:38Z",
         "eventName":"ObjectCreated:Put",
         "userIdentity":{
            "principalId":"1111111111111111111"
         },
         "requestParameters":{
            "sourceIPAddress":"193.51.100.20"
         },
         "responseElements":{
            "x-amz-request-id":"122047343"
         },
         "s3":{
            "s3SchemaVersion":"1.0",
            "configurationId":"Image-created",
            "bucket":{
               "name":"test1",
               "ownerIdentity":{
                  "principalId":"1111111111111111111"
               },
               "arn":"arn:sgws:s3:::test1"
            },
            "object":{
               "key":"images/cat.jpg",
               "size":0,
               "eTag":"d41d8cd98f00b204e9800998ecf8427e",
               "sequencer":"14D90402421461C7"
            }
         }
      }
   ]
}
----
+
대상 주제에서 알림을 받으면 StorageGRID 알림에 대한 소스 버킷을 성공적으로 구성한 것입니다.





.관련 정보
link:understanding-notifications-for-buckets.html["버킷에 대한 알림 이해"]

link:../s3/index.html["S3 REST API 사용"]

link:creating-platform-services-endpoint.html["플랫폼 서비스 엔드포인트 생성"]
