---
permalink: tenant/configuring-cloudmirror-replication.html 
sidebar: sidebar 
keywords: how to configure CloudMirror replication, replication xml 
summary: 버킷 복제 구성 XML을 생성하고 테넌트 관리자를 사용하여 XML을 버킷에 적용하여 버킷에 대한 CloudMirror 복제를 활성화합니다. 
---
= CloudMirror 복제 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버킷에 대한 CloudMirror 복제를 활성화하려면 유효한 버킷 복제 구성 XML을 만들고 적용합니다.

.시작하기 전에
* StorageGRID 관리자가 귀하의 테넌트 계정에 대해 플랫폼 서비스를 활성화했습니다.
* 복제 소스 역할을 할 버킷을 이미 생성했습니다.
* CloudMirror 복제의 대상으로 사용하려는 엔드포인트가 이미 존재하며 해당 엔드포인트의 URN도 있습니다.
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한 관리"] .  테넌트 관리자를 사용하여 버킷을 구성할 때 이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.


.이 작업에 관하여
CloudMirror 복제는 엔드포인트에 지정된 대상 버킷으로 소스 버킷의 객체를 복사합니다.

버킷 복제에 대한 일반 정보와 이를 구성하는 방법은 다음을 참조하세요. https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html["Amazon Simple Storage Service(S3) 설명서: 객체 복제"^] .  StorageGRID GetBucketReplication, DeleteBucketReplication 및 PutBucketReplication을 구현하는 방법에 대한 정보는 다음을 참조하세요.link:../s3/operations-on-buckets.html["버킷 작업"] .


NOTE: CloudMirror 복제는 크로스 그리드 복제 기능과 중요한 유사점과 차이점이 있습니다.  자세한 내용은 다음을 참조하세요.link:../admin/grid-federation-compare-cgr-to-cloudmirror.html["크로스 그리드 복제와 CloudMirror 복제 비교"] .

CloudMirror 복제를 구성할 때 다음 요구 사항과 특성을 참고하세요.

* 유효한 버킷 복제 구성 XML을 생성하고 적용할 때 각 대상에 대한 S3 버킷 엔드포인트의 URN을 사용해야 합니다.
* S3 개체 잠금이 활성화된 소스 또는 대상 버킷에 대한 복제는 지원되지 않습니다.
* 객체가 포함된 버킷에서 CloudMirror 복제를 활성화하면 버킷에 추가된 새 객체는 복제되지만 버킷에 있는 기존 객체는 복제되지 않습니다.  복제를 트리거하려면 기존 객체를 업데이트해야 합니다.
* 복제 구성 XML에서 스토리지 클래스를 지정하면 StorageGRID 대상 S3 엔드포인트에 대한 작업을 수행할 때 해당 클래스를 사용합니다.  대상 엔드포인트도 지정된 저장 클래스를 지원해야 합니다.  목적지 시스템 공급업체가 제공하는 권장 사항을 반드시 따르세요.


.단계
. 소스 버킷에 대한 복제를 활성화하세요.
+
** S3 복제 API에 지정된 대로, 복제를 활성화하는 데 필요한 복제 구성 XML을 만들려면 텍스트 편집기를 사용합니다.
** XML을 구성할 때:
+
*** StorageGRID 복제 구성의 V1만 지원합니다.  이는 StorageGRID 다음을 지원하지 않음을 의미합니다. `Filter` 규칙에 대한 요소이며, 객체 버전 삭제에 대한 V1 규칙을 따릅니다.  자세한 내용은 복제 구성에 대한 Amazon 설명서를 참조하세요.
*** S3 버킷 엔드포인트의 URN을 대상으로 사용합니다.
*** 선택적으로 추가하세요 `<StorageClass>` 요소를 선택하고 다음 중 하나를 지정하세요.
+
****  `STANDARD`: 기본 저장 클래스입니다.  객체를 업로드할 때 저장 클래스를 지정하지 않으면 `STANDARD` 저장 클래스가 사용됩니다.
**** `STANDARD_IA`: (표준 - 접근 빈도가 낮음.)  이 저장 클래스는 자주 액세스하지 않지만 필요할 때 빠른 액세스가 필요한 데이터에 사용합니다.
**** `REDUCED_REDUNDANCY`: 이 저장 클래스는 중복성이 낮은 저장이 가능한 비중요한 재생산 가능 데이터에 사용됩니다. `STANDARD` 저장 클래스.


*** 당신이 지정하는 경우 `Role` 구성 XML에서는 무시됩니다.  이 값은 StorageGRID 에서 사용되지 않습니다.
+
[listing]
----
<ReplicationConfiguration>
    <Role></Role>
    <Rule>
        <Status>Enabled</Status>
        <Prefix>2020</Prefix>
        <Destination>
           <Bucket>urn:sgws:s3:::2017-records</Bucket>
           <StorageClass>STANDARD</StorageClass>
         </Destination>
     </Rule>
</ReplicationConfiguration>
----




. 대시보드에서 *버킷 보기*를 선택하거나 *스토리지(S3)* > *버킷*을 선택하세요.
. 소스 버킷의 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. *플랫폼 서비스* > *복제*를 선택합니다.
. *복제 활성화* 확인란을 선택합니다.
. 복제 구성 XML을 텍스트 상자에 붙여넣고 *변경 사항 저장*을 선택합니다.
+

NOTE: StorageGRID 관리자는 Grid Manager 또는 Grid Management API를 사용하여 각 테넌트 계정에 대해 플랫폼 서비스를 활성화해야 합니다.  구성 XML을 저장할 때 오류가 발생하면 StorageGRID 관리자에게 문의하세요.

. 복제가 올바르게 구성되었는지 확인하세요.
+
.. 복제 구성에 지정된 복제 요구 사항을 충족하는 객체를 소스 버킷에 추가합니다.
+
이전에 표시된 예에서 "2020" 접두사와 일치하는 객체가 복제됩니다.

.. 대상 버킷에 개체가 복제되었는지 확인합니다.
+
작은 객체의 경우 복제가 빠르게 이루어집니다.





.관련 정보
link:creating-platform-services-endpoint.html["플랫폼 서비스 엔드포인트 생성"]
