---
permalink: tenant/considerations-for-platform-services.html 
sidebar: sidebar 
keywords: considerations for using platform services 
summary: 플랫폼 서비스를 구현하기 전에 해당 서비스 사용에 대한 개요와 고려 사항을 검토하세요. 
---
= 플랫폼 서비스 개요 및 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
플랫폼 서비스를 구현하기 전에 해당 서비스 사용에 대한 개요와 고려 사항을 검토하세요.

S3에 대한 정보는 다음을 참조하세요.link:../s3/index.html["S3 REST API 사용"] .



== 플랫폼 서비스 개요

StorageGRID 플랫폼 서비스를 사용하면 이벤트 알림과 S3 객체 및 객체 메타데이터의 사본을 외부 대상으로 보낼 수 있어 하이브리드 클라우드 전략을 구현하는 데 도움이 됩니다.

플랫폼 서비스의 대상 위치는 일반적으로 StorageGRID 배포 외부에 있으므로 플랫폼 서비스는 외부 스토리지 리소스, 알림 서비스, 데이터 검색 또는 분석 서비스를 사용할 수 있는 기능과 유연성을 제공합니다.

단일 S3 버킷에 대해 플랫폼 서비스의 모든 조합을 구성할 수 있습니다.  예를 들어, 두 가지 모두 구성할 수 있습니다.link:../tenant/understanding-cloudmirror-replication-service.html["클라우드미러 서비스"] 그리고link:../tenant/understanding-notifications-for-buckets.html["알림"] StorageGRID S3 버킷에 저장하면 특정 객체를 Amazon Simple Storage Service(S3)로 미러링할 수 있으며, 각 객체에 대한 알림을 타사 모니터링 애플리케이션으로 전송하여 AWS 비용을 추적하는 데 도움이 됩니다.


TIP: StorageGRID 관리자는 Grid Manager 또는 Grid Management API를 사용하여 각 테넌트 계정에 대해 플랫폼 서비스 사용을 활성화해야 합니다.



== 플랫폼 서비스 구성 방법

플랫폼 서비스는 다음을 사용하여 구성하는 외부 엔드포인트와 통신합니다.link:configuring-platform-services-endpoints.html["세입자 관리자"] 또는link:understanding-tenant-management-api.html["테넌트 관리 API"] . 각 엔드포인트는 StorageGRID S3 버킷, Amazon Web Services 버킷, Amazon SNS 주제 또는 로컬, AWS 또는 다른 곳에서 호스팅되는 Elasticsearch 클러스터와 같은 외부 대상을 나타냅니다.

외부 엔드포인트를 만든 후에는 버킷에 XML 구성을 추가하여 버킷에 대한 플랫폼 서비스를 활성화할 수 있습니다.  XML 구성은 버킷이 작업해야 하는 개체, 버킷이 수행해야 하는 작업, 버킷이 서비스에 사용해야 하는 엔드포인트를 식별합니다.

구성하려는 각 플랫폼 서비스에 대해 별도의 XML 구성을 추가해야 합니다. 예를 들어:

* 키가 다음으로 시작하는 모든 객체를 원하는 경우 `/images` Amazon S3 버킷에 복제하려면 소스 버킷에 복제 구성을 추가해야 합니다.
* 이러한 객체가 버킷에 저장될 때 알림을 보내려면 알림 구성을 추가해야 합니다.
* 이러한 개체의 메타데이터를 인덱싱하려면 검색 통합을 구현하는 데 사용되는 메타데이터 알림 구성을 추가해야 합니다.


구성 XML의 형식은 StorageGRID 플랫폼 서비스를 구현하는 데 사용되는 S3 REST API에 의해 관리됩니다.

[cols="1a,2a,1a"]
|===
| 플랫폼 서비스 | S3 REST API | 참조하다 


 a| 
CloudMirror 복제
 a| 
* GetBucketReplication
* PutBucketReplication

 a| 
* link:configuring-cloudmirror-replication.html["CloudMirror 복제"]
* link:../s3/operations-on-buckets.html["버킷 작업"]




 a| 
알림
 a| 
* 버킷 알림 구성 가져오기
* PutBucketNotificationConfiguration

 a| 
* link:configuring-event-notifications.html["알림"]
* link:../s3/operations-on-buckets.html["버킷 작업"]




 a| 
검색 통합
 a| 
* GET 버킷 메타데이터 알림 구성
* PUT 버킷 메타데이터 알림 구성

 a| 
* link:configuring-search-integration-service.html["검색 통합"]
* link:../s3/custom-operations-on-buckets.html["StorageGRID 사용자 정의 작업"]


|===


== 플랫폼 서비스 이용 시 고려사항

[cols="1a,3a"]
|===
| 고려 사항 | 세부 


 a| 
목적지 엔드포인트 모니터링
 a| 
각 대상 엔드포인트의 가용성을 모니터링해야 합니다.  대상 엔드포인트와의 연결이 장시간 끊어지고 많은 양의 요청이 쌓이면 StorageGRID 에 대한 추가 클라이언트 요청(예: PUT 요청)이 실패합니다.  엔드포인트에 도달할 수 있게 되면 실패한 요청을 다시 시도해야 합니다.



 a| 
목적지 엔드포인트 제한
 a| 
StorageGRID 소프트웨어는 대상 엔드포인트가 요청을 수신할 수 있는 속도를 초과하는 요청 전송 속도를 초과하는 경우 버킷에 대한 수신 S3 요청을 제한할 수 있습니다.  제한은 대상 엔드포인트로 전송되기를 기다리는 요청이 잔뜩 쌓여 있는 경우에만 발생합니다.

유일하게 눈에 띄는 효과는 들어오는 S3 요청을 실행하는 데 시간이 더 걸린다는 것입니다.  성능이 현저히 저하되는 것을 감지하면 수집 속도를 낮추거나 용량이 더 큰 엔드포인트를 사용해야 합니다.  요청 백로그가 계속해서 늘어나면 클라이언트 S3 작업(예: PUT 요청)이 결국 실패하게 됩니다.

CloudMirror 요청은 일반적으로 검색 통합이나 이벤트 알림 요청보다 더 많은 데이터 전송이 포함되므로 대상 엔드포인트의 성능에 영향을 받을 가능성이 더 큽니다.



 a| 
주문 보증
 a| 
StorageGRID 사이트 내의 객체에 대한 작업 순서를 보장합니다.  모든 객체에 대한 작업이 동일한 사이트 내에서 이루어지는 한, 최종 객체 상태(복제용)는 항상 StorageGRID 의 상태와 동일합니다.

StorageGRID StorageGRID 사이트 전체에서 작업이 수행될 때 요청을 순서대로 정렬하기 위해 최선을 다합니다.  예를 들어, 처음에 사이트 A에 객체를 쓰고 나중에 사이트 B에 있는 동일한 객체를 덮어쓰는 경우, CloudMirror에서 대상 버킷에 복제한 최종 객체가 최신 객체일 보장은 없습니다.



 a| 
ILM 기반 객체 삭제
 a| 
AWS CRR과 Amazon Simple Notification Service의 삭제 동작과 일치시키기 위해 StorageGRID ILM 규칙으로 인해 소스 버킷의 객체가 삭제되면 CloudMirror 및 이벤트 알림 요청이 전송되지 않습니다.  예를 들어, ILM 규칙에 따라 14일 후에 개체가 삭제되면 CloudMirror 또는 이벤트 알림 요청이 전송되지 않습니다.

이와 대조적으로, ILM으로 인해 개체가 삭제되면 검색 통합 요청이 전송됩니다.



 a| 
Kafka 엔드포인트 사용
 a| 
Kafka 엔드포인트의 경우 Mutual TLS가 지원되지 않습니다. 결과적으로, 만약 당신이 가지고 있다면 `ssl.client.auth` 로 설정 `required` Kafka 브로커 구성에서 Kafka 엔드포인트 구성 문제가 발생할 수 있습니다.

Kafka 엔드포인트 인증에는 다음과 같은 인증 유형이 사용됩니다.  이러한 유형은 Amazon SNS 등 다른 엔드포인트의 인증에 사용되는 유형과 다르며 사용자 이름과 비밀번호 자격 증명이 필요합니다.

* SASL/평문
* SASL/스크램-SHA-256
* SASL/스크램-SHA-512


*참고:* 구성된 스토리지 프록시 설정은 Kafka 플랫폼 서비스 엔드포인트에 적용되지 않습니다.

|===


== CloudMirror 복제 서비스 사용 시 고려 사항

[cols="1a,3a"]
|===
| 고려 사항 | 세부 


 a| 
복제 상태
 a| 
StorageGRID 지원하지 않습니다 `x-amz-replication-status` 헤더.



 a| 
객체 크기
 a| 
CloudMirror 복제 서비스를 통해 대상 버킷에 복제할 수 있는 객체의 최대 크기는 5TiB이며, 이는 최대 _지원_ 객체 크기와 동일합니다.

*참고*: 단일 PutObject 작업에 권장되는 최대 크기는 5GiB(5,368,709,120바이트)입니다.  5GiB보다 큰 객체가 있는 경우 대신 멀티파트 업로드를 사용하세요.



 a| 
버킷 버전 관리 및 버전 ID
 a| 
StorageGRID 의 소스 S3 버킷에 버전 관리가 활성화된 경우 대상 버킷의 버전 관리도 활성화해야 합니다.

버전 관리를 사용할 때 대상 버킷의 객체 버전 순서는 최선의 노력이며 S3 프로토콜의 제한으로 인해 CloudMirror 서비스에서 보장되지 않는다는 점에 유의하세요.

*참고*: StorageGRID 의 소스 버킷 버전 ID는 대상 버킷 버전 ID와 관련이 없습니다.



 a| 
객체 버전에 대한 태그 지정
 a| 
S3 프로토콜의 제한으로 인해 CloudMirror 서비스는 버전 ID를 제공하는 PutObjectTagging 또는 DeleteObjectTagging 요청을 복제하지 않습니다.  소스와 대상의 버전 ID가 관련되어 있지 않으므로 특정 버전 ID에 대한 태그 업데이트가 복제될 것이라는 보장이 없습니다.

이와 대조적으로 CloudMirror 서비스는 버전 ID를 지정하지 않는 PutObjectTagging 요청이나 DeleteObjectTagging 요청을 복제합니다.  이러한 요청은 최신 키(또는 버킷에 버전이 지정된 경우 최신 버전)에 대한 태그를 업데이트합니다.  태그가 있는 일반적인 수집(태그 업데이트 아님)도 복제됩니다.



 a| 
멀티파트 업로드 및 `ETag` 가치
 a| 
멀티파트 업로드를 사용하여 업로드된 객체를 미러링하는 경우 CloudMirror 서비스는 해당 부분을 보존하지 않습니다.  그 결과, `ETag` 미러링된 객체의 값은 다음과 다릅니다. `ETag` 원래 객체의 가치.



 a| 
SSE-C(고객 제공 키를 사용한 서버 측 암호화)로 암호화된 객체
 a| 
CloudMirror 서비스는 SSE-C로 암호화된 객체를 지원하지 않습니다. CloudMirror 복제를 위해 원본 버킷으로 객체를 수집하려고 할 때 요청에 SSE-C 요청 헤더가 포함되어 있으면 작업이 실패합니다.



 a| 
S3 객체 잠금이 활성화된 버킷
 a| 
S3 개체 잠금이 활성화된 소스 또는 대상 버킷에 대한 복제는 지원되지 않습니다.

|===