---
permalink: tenant/creating-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create other user S3 access key 
summary: S3 테넌트를 사용하고 적절한 권한이 있는 경우 버킷 및 객체에 액세스해야 하는 애플리케이션 등 다른 사용자를 위해 S3 액세스 키를 생성할 수 있습니다. 
---
= 다른 사용자의 S3 액세스 키 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 테넌트를 사용하고 적절한 권한이 있는 경우 버킷 및 객체에 액세스해야 하는 애플리케이션 등 다른 사용자를 위해 S3 액세스 키를 생성할 수 있습니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["루트 액세스 권한"] .


.이 작업에 관하여
다른 사용자를 위해 하나 이상의 S3 액세스 키를 만들면 해당 사용자가 자신의 테넌트 계정에 대한 버킷을 만들고 관리할 수 있습니다.  새로운 액세스 키를 만든 후, 새로운 액세스 키 ID와 비밀 액세스 키로 애플리케이션을 업데이트합니다.  보안을 위해 사용자에게 필요한 것 이상의 키를 생성하지 말고, 사용되지 않는 키는 삭제하세요.  키가 하나뿐이고 만료가 임박한 경우, 기존 키가 만료되기 전에 새 키를 만든 다음 기존 키를 삭제하세요.

각 키에는 특정 만료 시간이 지정되거나 만료 시간이 지정되지 않을 수 있습니다.  만료 시간에 대한 다음 지침을 따르세요.

* 사용자의 키 접근을 특정 기간으로 제한하기 위해 키의 만료 시간을 설정합니다.  짧은 만료 시간을 설정하면 액세스 키 ID와 비밀 액세스 키가 실수로 노출될 경우 위험을 줄이는 데 도움이 될 수 있습니다.  만료된 키는 자동으로 제거됩니다.
* 사용자 환경의 보안 위험이 낮고 주기적으로 새로운 키를 생성할 필요가 없다면 키의 만료 시간을 설정할 필요가 없습니다.  나중에 새 키를 만들기로 결정한 경우 기존 키를 수동으로 삭제하세요.



CAUTION: 사용자에게 속한 S3 버킷과 객체는 테넌트 관리자에서 해당 사용자에게 표시된 액세스 키 ID와 비밀 액세스 키를 사용하여 액세스할 수 있습니다.  이러한 이유로 액세스 키를 비밀번호처럼 보호하세요.  정기적으로 액세스 키를 교체하고, 계정에서 사용하지 않는 키를 제거하고, 다른 사용자와 공유하지 마세요.

.단계
. *액세스 관리* > *사용자*를 선택합니다.
. S3 액세스 키를 관리할 사용자를 선택하세요.
+
사용자 세부 정보 페이지가 나타납니다.

. *액세스 키*를 선택한 다음 *키 생성*을 선택합니다.
. 다음 중 하나를 수행하세요.
+
** 만료되지 않는 키를 생성하려면 *만료 시간을 설정하지 마세요*를 선택하세요.  (기본)
** *만료 시간 설정*을 선택하고 만료 날짜와 시간을 설정합니다.
+

NOTE: 만료일은 현재 날짜로부터 최대 5년까지 가능합니다.  만료 시간은 현재 시간으로부터 최소 1분이 될 수 있습니다.



. *액세스 키 만들기*를 선택하세요.
+
액세스 키 다운로드 대화 상자가 나타나고 액세스 키 ID와 비밀 액세스 키가 나열됩니다.

. 액세스 키 ID와 비밀 액세스 키를 안전한 위치에 복사하거나 *.csv 다운로드*를 선택하여 액세스 키 ID와 비밀 액세스 키가 포함된 스프레드시트 파일을 저장합니다.
+

CAUTION: 이 정보를 복사하거나 다운로드하기 전까지는 이 대화 상자를 닫지 마세요.  대화 상자를 닫은 후에는 키를 복사하거나 다운로드할 수 없습니다.

. *마침*을 선택하세요.
+
새 키는 사용자 세부 정보 페이지의 액세스 키 탭에 나열됩니다.

. 테넌트 계정에 *그리드 페더레이션 연결 사용* 권한이 있는 경우, 선택적으로 테넌트 관리 API를 사용하여 소스 그리드의 테넌트에서 대상 그리드의 테넌트로 S3 액세스 키를 수동으로 복제합니다. 보다 link:grid-federation-clone-keys-with-api.html["API를 사용하여 S3 액세스 키 복제"] .

