---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: 테넌트 관리자를 사용하여 객체 데이터에 대한 S3 버킷을 생성할 수 있습니다. 
---
= S3 버킷 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 관리자를 사용하여 객체 데이터에 대한 S3 버킷을 생성할 수 있습니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 귀하는 루트 액세스 권한이 있거나 모든 버킷을 관리하는 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["허가"] . 이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.
+

NOTE: 버킷 또는 객체의 S3 객체 잠금 속성을 설정하거나 수정하는 권한은 다음을 통해 부여될 수 있습니다.link:../s3/bucket-and-group-access-policies.html["버킷 정책 또는 그룹 정책"] .

* 버킷에 대해 S3 개체 잠금을 활성화하려는 경우 그리드 관리자가 StorageGRID 시스템에 대한 글로벌 S3 개체 잠금 설정을 활성화했고 S3 개체 잠금 버킷 및 개체에 대한 요구 사항을 검토했습니다.
* 각 테넌트가 5,000개의 버킷을 갖는 경우 그리드의 각 스토리지 노드에는 최소 64GB의 RAM이 있습니다.
+

NOTE: 각 그리드에는 최대 100,000개의 버킷이 있을 수 있습니다.





== 마법사에 접속하세요

.단계
. 대시보드에서 *버킷 보기*를 선택하거나 *스토리지(S3)* > *버킷*을 선택하세요.
. *버킷 만들기*를 선택합니다.




== 세부 정보를 입력하세요

.단계
. 버킷에 대한 세부 정보를 입력하세요.
+
[cols="1a,3a"]
|===
| 필드 | 설명 


 a| 
버킷 이름
 a| 
다음 규칙을 준수하는 버킷의 이름:

** 각 StorageGRID 시스템에서 고유해야 합니다(테넌트 계정 내에서만 고유할 뿐만 아니라).
** DNS를 준수해야 합니다.
** 최소 3자, 최대 63자까지 입력 가능합니다.
** 각 라벨은 소문자 또는 숫자로 시작하고 끝나야 하며, 소문자, 숫자, 하이픈만 사용할 수 있습니다.
** 가상 호스팅 스타일 요청에는 마침표가 포함되어서는 안 됩니다.  마침표는 서버 와일드카드 인증서 검증에 문제를 일으킬 수 있습니다.


자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["버킷 명명 규칙에 대한 Amazon Web Services(AWS) 설명서"^] .

*참고*: 버킷을 만든 후에는 버킷 이름을 변경할 수 없습니다.



 a| 
지역
 a| 
버킷의 지역.

StorageGRID 관리자가 사용 가능한 지역을 관리합니다. 버킷의 지역은 객체에 적용되는 데이터 보호 정책에 영향을 미칠 수 있습니다. 기본적으로 모든 버킷은 다음에서 생성됩니다. `us-east-1` 지역.

*참고*: 버킷을 만든 후에는 지역을 변경할 수 없습니다.

|===
. *계속*을 선택하세요.




== 설정 관리

.단계
. 선택적으로 버킷에 대한 개체 버전 관리를 활성화합니다.
+
이 버킷에 있는 각 개체의 모든 버전을 저장하려면 개체 버전 관리를 활성화하세요.  그러면 필요에 따라 객체의 이전 버전을 검색할 수 있습니다.  버킷을 크로스 그리드 복제에 사용할 경우 개체 버전 관리를 활성화해야 합니다.

. 글로벌 S3 객체 잠금 설정이 활성화된 경우 WORM(Write-Once-Read-Many) 모델을 사용하여 버킷에 객체를 저장하기 위해 S3 객체 잠금을 선택적으로 활성화합니다.
+
예를 들어 특정 규정 요구 사항을 충족하기 위해 일정 기간 동안 객체를 보관해야 하는 경우에만 버킷에 대해 S3 객체 잠금을 활성화합니다. S3 객체 잠금은 특정 기간 또는 무기한으로 객체가 삭제되거나 덮어쓰이는 것을 방지하는 데 도움이 되는 영구 설정입니다.

+

CAUTION: 버킷에 대해 S3 개체 잠금 설정을 활성화한 후에는 비활성화할 수 없습니다. 올바른 권한이 있는 사람은 누구나 변경할 수 없는 객체를 이 버킷에 추가할 수 있습니다.  이러한 객체나 버킷 자체를 삭제할 수 없을 수도 있습니다.

+
버킷에 대해 S3 객체 잠금을 활성화하면 버킷 버전 관리가 자동으로 활성화됩니다.

. *S3 객체 잠금 활성화*를 선택한 경우, 선택적으로 이 버킷에 대해 *기본 보존*을 활성화합니다.
+

NOTE: 그리드 관리자는 귀하에게 권한을 부여해야 합니다.link:../tenant/using-s3-object-lock.html["S3 객체 잠금의 특정 기능 사용"] .

+
*기본 보존*을 활성화하면 버킷에 추가된 새 객체는 삭제되거나 덮어쓰이지 않도록 자동으로 보호됩니다. *기본 보존* 설정은 자체 보존 기간이 있는 개체에는 적용되지 않습니다.

+
.. *기본 보존*이 활성화된 경우 버킷에 대한 *기본 보존 모드*를 지정합니다.
+
[cols="1a,2a"]
|===
| 기본 보존 모드 | 설명 


 a| 
통치
 a| 
*** 사용자 `s3:BypassGovernanceRetention` 허가를 사용할 수 있습니다 `x-amz-bypass-governance-retention: true` 보존 설정을 우회하기 위한 요청 헤더입니다.
*** 이러한 사용자는 보관 기한에 도달하기 전에 개체 버전을 삭제할 수 있습니다.
*** 이러한 사용자는 객체의 보관 기간을 늘리거나 줄이거나 제거할 수 있습니다.




 a| 
규정 준수
 a| 
*** 해당 객체는 보관 만료일에 도달할 때까지 삭제할 수 없습니다.
*** 객체의 보관 기한은 늘릴 수 있지만 줄일 수는 없습니다.
*** 해당 날짜에 도달하기 전까지는 객체의 보관 기간을 제거할 수 없습니다.


*참고*: 그리드 관리자가 규정 준수 모드를 사용하도록 허용해야 합니다.

|===
.. *기본 보존*이 활성화된 경우 버킷의 *기본 보존 기간*을 지정합니다.
+
*기본 보존 기간*은 이 버킷에 추가된 새 객체를 수집한 시점부터 보존해야 하는 기간을 나타냅니다. 그리드 관리자가 설정한 테넌트의 최대 보존 기간보다 작거나 같은 값을 지정합니다.

+
그리드 관리자가 테넌트를 생성할 때 최대 보존 기간이 설정되며, 이 기간은 1일에서 100년까지의 값이 될 수 있습니다.  _기본_ 보존 기간을 설정하면 최대 보존 기간에 설정된 값을 초과할 수 없습니다.  필요한 경우 그리드 관리자에게 최대 보존 기간을 늘리거나 줄여달라고 요청하세요.



. [[capacity-limit]]선택적으로 *용량 제한 사용*을 선택하세요.
+
용량 제한은 이 버킷의 객체에 사용할 수 있는 최대 용량입니다. 이 값은 물리적인 양(디스크 크기)이 아닌 논리적인 양(객체 크기)을 나타냅니다.

+
제한을 설정하지 않으면 이 버킷의 용량은 무제한입니다. . link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["용량 제한 사용"] 자세한 내용은.

. *버킷 만들기*를 선택합니다.
+
버킷이 생성되어 버킷 페이지의 테이블에 추가됩니다.

. 선택적으로 *버킷 세부 정보 페이지로 이동*을 선택하세요.link:viewing-s3-bucket-details.html["버킷 세부 정보 보기"] 추가 구성을 수행합니다.

