---
permalink: tenant/creating-groups-for-swift-tenant.html 
sidebar: sidebar 
keywords: how to create Swift tenant groups 
summary: 페더레이션 그룹을 가져오거나 로컬 그룹을 만들어 Swift 테넌트 계정에 대한 액세스 권한을 관리할 수 있습니다.  최소한 하나의 그룹에는 Swift 테넌트 계정의 컨테이너와 객체를 관리하는 데 필요한 Swift 관리자 권한이 있어야 합니다. 
---
= Swift 테넌트에 대한 그룹 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
페더레이션 그룹을 가져오거나 로컬 그룹을 만들어 Swift 테넌트 계정에 대한 액세스 권한을 관리할 수 있습니다.  최소한 하나의 그룹에는 Swift 테넌트 계정의 컨테이너와 객체를 관리하는 데 필요한 Swift 관리자 권한이 있어야 합니다.


NOTE: Swift 클라이언트 애플리케이션에 대한 지원이 더 이상 제공되지 않으며 향후 릴리스에서 제거될 예정입니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["루트 액세스 권한"] .
* 페더레이션 그룹을 가져오려면 다음을 수행해야 합니다.link:using-identity-federation.html["구성된 ID 페더레이션"] , 그리고 페더레이션 그룹이 구성된 ID 소스에 이미 존재합니다.




== 그룹 만들기 마법사에 액세스하세요

.단계
첫 번째 단계로 그룹 만들기 마법사에 액세스하세요.

. *액세스 관리* > *그룹*을 선택하세요.
. *그룹 만들기*를 선택하세요.




== 그룹 유형을 선택하세요

로컬 그룹을 만들거나 페더레이션 그룹을 가져올 수 있습니다.

.단계
. 로컬 그룹을 만들려면 *로컬 그룹* 탭을 선택하고, 이전에 구성된 ID 소스에서 그룹을 가져오려면 *연합 그룹* 탭을 선택합니다.
+
StorageGRID 시스템에서 SSO(Single Sign-On)가 활성화된 경우 로컬 그룹에 속한 사용자는 테넌트 관리자에 로그인할 수 없지만, 그룹 권한에 따라 클라이언트 애플리케이션을 사용하여 테넌트의 리소스를 관리할 수 있습니다.

. 그룹 이름을 입력하세요.
+
** *로컬 그룹*: 표시 이름과 고유 이름을 모두 입력하세요.  나중에 표시 이름을 편집할 수 있습니다.
** *연합 그룹*: 고유한 이름을 입력하세요.  Active Directory의 경우 고유 이름은 다음과 관련된 이름입니다. `sAMAccountName` 기인하다.  OpenLDAP의 경우 고유 이름은 다음과 관련된 이름입니다. `uid` 기인하다.


. *계속*을 선택하세요.




== 그룹 권한 관리

그룹 권한은 사용자가 테넌트 관리자 및 테넌트 관리 API에서 수행할 수 있는 작업을 제어합니다.

.단계
. *액세스 모드*의 경우 다음 중 하나를 선택하세요.
+
** *읽기-쓰기* (기본값): 사용자는 테넌트 관리자에 로그인하여 테넌트 구성을 관리할 수 있습니다.
** *읽기 전용*: 사용자는 설정과 기능만 볼 수 있습니다.  테넌트 관리자 또는 테넌트 관리 API에서 어떠한 변경이나 작업도 수행할 수 없습니다.  로컬 읽기 전용 사용자는 자신의 비밀번호를 변경할 수 있습니다.
+

NOTE: 사용자가 여러 그룹에 속해 있고 그룹 중 하나가 읽기 전용으로 설정된 경우, 사용자는 선택한 모든 설정과 기능에 대한 읽기 전용 액세스 권한을 갖습니다.



. 그룹 사용자가 테넌트 관리자 또는 테넌트 관리 API에 로그인해야 하는 경우 *루트 액세스* 확인란을 선택합니다.
. *계속*을 선택하세요.




== Swift 그룹 정책 설정

Swift 사용자는 Swift REST API에 인증하여 컨테이너를 생성하고 객체를 수집하려면 관리자 권한이 필요합니다.

. 그룹 사용자가 Swift REST API를 사용하여 컨테이너와 객체를 관리해야 하는 경우 *Swift 관리자* 확인란을 선택합니다.
. 로컬 그룹을 만드는 경우 *계속*을 선택하세요.  연합 그룹을 만드는 경우 *그룹 만들기*와 *마침*을 선택하세요.




== 사용자 추가(로컬 그룹만 해당)

사용자를 추가하지 않고 그룹을 저장할 수도 있고, 이미 존재하는 로컬 사용자를 추가할 수도 있습니다.

.단계
. 선택적으로 이 그룹에 대해 하나 이상의 로컬 사용자를 선택합니다.
+
아직 로컬 사용자를 생성하지 않은 경우 사용자 페이지에서 이 그룹을 사용자에게 추가할 수 있습니다. 보다 link:../tenant/managing-local-users.html["로컬 사용자 관리"] .

. *그룹 만들기*와 *마침*을 선택합니다.
+
생성한 그룹이 그룹 목록에 나타납니다.


