---
permalink: tenant/creating-platform-services-endpoint.html 
sidebar: sidebar 
keywords: how to create platform services endpoint 
summary: 플랫폼 서비스를 활성화하려면 먼저 올바른 유형의 엔드포인트를 하나 이상 만들어야 합니다. 
---
= 플랫폼 서비스 엔드포인트 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
플랫폼 서비스를 활성화하려면 먼저 올바른 유형의 엔드포인트를 하나 이상 만들어야 합니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* StorageGRID 관리자가 귀하의 테넌트 계정에 대해 플랫폼 서비스를 활성화했습니다.
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["엔드포인트 또는 루트 액세스 권한 관리"] .
* 플랫폼 서비스 엔드포인트에서 참조하는 리소스가 생성되었습니다.
+
** CloudMirror 복제: S3 버킷
** 이벤트 알림: Amazon Simple Notification Service(Amazon SNS) 또는 Kafka 주제
** 검색 알림: 대상 클러스터가 인덱스를 자동으로 생성하도록 구성되지 않은 경우 Elasticsearch 인덱스입니다.


* 대상 리소스에 대한 정보가 있습니다.
+
** URI(Uniform Resource Identifier)에 대한 호스트 및 포트
+

NOTE: StorageGRID 시스템에 호스팅된 버킷을 CloudMirror 복제의 엔드포인트로 사용하려는 경우 그리드 관리자에게 문의하여 입력해야 할 값을 확인하세요.

** 고유 리소스 이름(URN)
+
link:specifying-urn-for-platform-services-endpoint.html["플랫폼 서비스 엔드포인트에 대한 URN을 지정합니다."]

** 인증 자격 증명(필요한 경우):
+
[role="tabbed-block"]
====
.검색 통합 엔드포인트
--
검색 통합 엔드포인트의 경우 다음 자격 증명을 사용할 수 있습니다.

*** 액세스 키: 액세스 키 ID 및 비밀 액세스 키
*** 기본 HTTP: 사용자 이름 및 비밀번호


--
.CloudMirror 복제 엔드포인트
--
CloudMirror 복제 엔드포인트의 경우 다음 자격 증명을 사용할 수 있습니다.

*** 액세스 키: 액세스 키 ID 및 비밀 액세스 키
*** CAP(C2S 액세스 포털): 임시 자격 증명 URL, 서버 및 클라이언트 인증서, 클라이언트 키, 선택적 클라이언트 개인 키 암호문구.


--
.Amazon SNS 엔드포인트
--
Amazon SNS 엔드포인트의 경우 다음 자격 증명을 사용할 수 있습니다.

*** 액세스 키: 액세스 키 ID 및 비밀 액세스 키


--
.카프카 엔드포인트
--
Kafka 엔드포인트의 경우 다음 자격 증명을 사용할 수 있습니다.

*** SASL/PLAIN: 사용자 이름 및 비밀번호
*** SASL/SCRAM-SHA-256: 사용자 이름 및 비밀번호
*** SASL/SCRAM-SHA-512: 사용자 이름 및 비밀번호


--
====
** 보안 인증서(사용자 정의 CA 인증서를 사용하는 경우)


* Elasticsearch 보안 기능이 활성화된 경우 연결 테스트를 위한 모니터 클러스터 권한과 문서 업데이트를 위한 인덱스 쓰기 권한 또는 인덱스 권한과 인덱스 삭제 권한이 모두 제공됩니다.


.단계
. *저장소(S3)* > *플랫폼 서비스 엔드포인트*를 선택합니다.  플랫폼 서비스 엔드포인트 페이지가 나타납니다.
. *엔드포인트 생성*을 선택합니다.
. 엔드포인트와 그 목적을 간략하게 설명하는 표시 이름을 입력하세요.
+
엔드포인트가 지원하는 플랫폼 서비스 유형은 엔드포인트 페이지에 나열될 때 엔드포인트 이름 옆에 표시되므로 이름에 해당 정보를 포함할 필요가 없습니다.

. *URI* 필드에 엔드포인트의 고유 리소스 식별자(URI)를 지정합니다.
+
--
다음 형식 중 하나를 사용하세요.

[listing]
----
https://host:port
http://host:port
----
포트를 지정하지 않으면 다음 기본 포트가 사용됩니다.

** HTTPS URI의 경우 포트 443, HTTP URI의 경우 포트 80(대부분의 엔드포인트)
** HTTPS 및 HTTP URI의 경우 포트 9092(Kafka 엔드포인트만 해당)


--
+
예를 들어, StorageGRID 에 호스팅된 버킷의 URI는 다음과 같습니다.

+
[listing]
----
https://s3.example.com:10443
----
+
이 예에서, `s3.example.com` StorageGRID 고가용성(HA) 그룹의 가상 IP(VIP)에 대한 DNS 항목을 나타냅니다. `10443` 로드 밸런서 엔드포인트에 정의된 포트를 나타냅니다.

+

NOTE: 가능하다면 단일 장애 지점을 방지하기 위해 부하 분산 노드의 HA 그룹에 연결해야 합니다.

+
마찬가지로 AWS에 호스팅된 버킷의 URI는 다음과 같습니다.

+
[listing]
----
https://s3-aws-region.amazonaws.com
----
+

NOTE: 엔드포인트가 CloudMirror 복제 서비스에 사용되는 경우 URI에 버킷 이름을 포함하지 마세요.  *URN* 필드에 버킷 이름을 포함합니다.

. 엔드포인트에 대한 고유 리소스 이름(URN)을 입력합니다.
+

NOTE: 엔드포인트가 생성된 후에는 엔드포인트의 URN을 변경할 수 없습니다.

. *계속*을 선택하세요.
. *인증 유형*에 대한 값을 선택하세요.
+
[role="tabbed-block"]
====
.검색 통합 엔드포인트
--
검색 통합 엔드포인트에 대한 자격 증명을 입력하거나 업로드합니다.

제공하는 자격 증명에는 대상 리소스에 대한 쓰기 권한이 있어야 합니다.

[cols="1a,2a,2a"]
|===
| 인증 유형 | 설명 | 신임장 


 a| 
익명의
 a| 
대상지에 익명으로 접근할 수 있도록 합니다.  보안이 비활성화된 엔드포인트에서만 작동합니다.
 a| 
인증이 없습니다.



 a| 
액세스 키
 a| 
AWS 스타일 자격 증명을 사용하여 대상과의 연결을 인증합니다.
 a| 
** 액세스 키 ID
** 비밀 액세스 키




 a| 
기본 HTTP
 a| 
사용자 이름과 비밀번호를 사용하여 대상에 대한 연결을 인증합니다.
 a| 
** 사용자 이름
** 비밀번호


|===
--
.CloudMirror 복제 엔드포인트
--
CloudMirror 복제 엔드포인트에 대한 자격 증명을 입력하거나 업로드합니다.

제공하는 자격 증명에는 대상 리소스에 대한 쓰기 권한이 있어야 합니다.

[cols="1a,2a,2a"]
|===
| 인증 유형 | 설명 | 신임장 


 a| 
익명의
 a| 
대상지에 익명으로 접근할 수 있도록 합니다.  보안이 비활성화된 엔드포인트에서만 작동합니다.
 a| 
인증이 없습니다.



 a| 
액세스 키
 a| 
AWS 스타일 자격 증명을 사용하여 대상과의 연결을 인증합니다.
 a| 
** 액세스 키 ID
** 비밀 액세스 키




 a| 
CAP(C2S 접속 포털)
 a| 
인증서와 키를 사용하여 대상에 대한 연결을 인증합니다.
 a| 
** 임시 자격 증명 URL
** 서버 CA 인증서(PEM 파일 업로드)
** 클라이언트 인증서(PEM 파일 업로드)
** 클라이언트 개인 키(PEM 파일 업로드, OpenSSL 암호화 형식 또는 암호화되지 않은 개인 키 형식)
** 클라이언트 개인 키 암호문구(선택 사항)


|===
--
.Amazon SNS 엔드포인트
--
Amazon SNS 엔드포인트에 대한 자격 증명을 입력하거나 업로드합니다.

제공하는 자격 증명에는 대상 리소스에 대한 쓰기 권한이 있어야 합니다.

[cols="1a,2a,2a"]
|===
| 인증 유형 | 설명 | 신임장 


 a| 
익명의
 a| 
대상지에 익명으로 접근할 수 있도록 합니다.  보안이 비활성화된 엔드포인트에서만 작동합니다.
 a| 
인증이 없습니다.



 a| 
액세스 키
 a| 
AWS 스타일 자격 증명을 사용하여 대상과의 연결을 인증합니다.
 a| 
** 액세스 키 ID
** 비밀 액세스 키


|===
--
.카프카 엔드포인트
--
Kafka 엔드포인트에 대한 자격 증명을 입력하거나 업로드합니다.

제공하는 자격 증명에는 대상 리소스에 대한 쓰기 권한이 있어야 합니다.

[cols="1a,2a,2a"]
|===
| 인증 유형 | 설명 | 신임장 


 a| 
익명의
 a| 
대상지에 익명으로 접근할 수 있도록 합니다.  보안이 비활성화된 엔드포인트에서만 작동합니다.
 a| 
인증이 없습니다.



 a| 
SASL/평문
 a| 
일반 텍스트로 된 사용자 이름과 비밀번호를 사용하여 대상에 대한 연결을 인증합니다.
 a| 
** 사용자 이름
** 비밀번호




 a| 
SASL/스크램-SHA-256
 a| 
챌린지-응답 프로토콜과 SHA-256 해싱을 사용하여 사용자 이름과 비밀번호를 사용하여 대상에 대한 연결을 인증합니다.
 a| 
** 사용자 이름
** 비밀번호




 a| 
SASL/스크램-SHA-512
 a| 
챌린지-응답 프로토콜과 SHA-512 해싱을 사용하여 사용자 이름과 비밀번호를 사용하여 대상에 대한 연결을 인증합니다.
 a| 
** 사용자 이름
** 비밀번호


|===
사용자 이름과 비밀번호가 Kafka 클러스터에서 얻은 위임 토큰에서 파생된 경우 *위임 받은 인증 사용*을 선택합니다.

--
====
. *계속*을 선택하세요.
. *서버 확인* 라디오 버튼을 선택하여 엔드포인트에 대한 TLS 연결을 확인하는 방법을 선택합니다.
+
[cols="1a,2a"]
|===
| 인증서 검증 유형 | 설명 


 a| 
사용자 정의 CA 인증서 사용
 a| 
사용자 정의 보안 인증서를 사용하세요.  이 설정을 선택하는 경우 사용자 지정 보안 인증서를 복사하여 *CA 인증서* 텍스트 상자에 붙여넣습니다.



 a| 
운영 체제 CA 인증서 사용
 a| 
운영 체제에 설치된 기본 Grid CA 인증서를 사용하여 연결을 보호합니다.



 a| 
인증서를 확인하지 마세요
 a| 
TLS 연결에 사용된 인증서가 검증되지 않았습니다.  이 옵션은 안전하지 않습니다.

|===
. *테스트 및 엔드포인트 생성*을 선택합니다.
+
** 지정된 자격 증명을 사용하여 엔드포인트에 도달할 수 있는 경우 성공 메시지가 나타납니다.  각 사이트의 한 노드에서 엔드포인트에 대한 연결이 검증됩니다.
** 엔드포인트 검증에 실패하면 오류 메시지가 나타납니다.  오류를 바로잡기 위해 엔드포인트를 수정해야 하는 경우 *엔드포인트 세부정보로 돌아가기*를 선택하고 정보를 업데이트하세요.  그런 다음 *엔드포인트 테스트 및 생성*을 선택합니다.
+

NOTE: 테넌트 계정에 플랫폼 서비스가 활성화되어 있지 않으면 엔드포인트 생성이 실패합니다.  StorageGRID 관리자에게 문의하세요.





엔드포인트를 구성한 후에는 해당 URN을 사용하여 플랫폼 서비스를 구성할 수 있습니다.

.관련 정보
* link:specifying-urn-for-platform-services-endpoint.html["플랫폼 서비스 엔드포인트에 대한 URN을 지정합니다."]
* link:configuring-cloudmirror-replication.html["CloudMirror 복제 구성"]
* link:configuring-event-notifications.html["이벤트 알림 구성"]
* link:configuring-search-integration-service.html["검색 통합 서비스 구성"]

