---
permalink: tenant/deleting-s3-bucket.html 
sidebar: sidebar 
keywords: how to delete S3 bucket 
summary: 테넌트 관리자를 사용하여 비어 있는 S3 버킷을 삭제할 수 있습니다. 
---
= S3 버킷 삭제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 관리자를 사용하여 비어 있는 S3 버킷을 하나 이상 삭제할 수 있습니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한 관리"] . 이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.
* 삭제하려는 버킷이 비어 있습니다.  삭제하려는 버킷이 비어 있지 않으면,link:../tenant/deleting-s3-bucket-objects.html["버킷에서 객체 삭제"] .


.이 작업에 관하여
이 지침에서는 테넌트 관리자를 사용하여 S3 버킷을 삭제하는 방법을 설명합니다.  다음을 사용하여 S3 버킷을 삭제할 수도 있습니다.link:understanding-tenant-management-api.html["테넌트 관리 API"] 또는link:../s3/operations-on-buckets.html["S3 REST API"] .

객체, 최신이 아닌 객체 버전 또는 삭제 마커가 포함된 S3 버킷은 삭제할 수 없습니다.  S3 버전 관리 객체가 삭제되는 방법에 대한 자세한 내용은 다음을 참조하세요.link:../ilm/how-objects-are-deleted.html["객체가 삭제되는 방법"] .

.단계
. 대시보드에서 *버킷 보기*를 선택하거나 *스토리지(S3)* > *버킷*을 선택하세요.
+
버킷 페이지가 나타나고 기존 S3 버킷이 모두 표시됩니다.

. 특정 버킷의 *작업* 메뉴나 세부 정보 페이지를 사용하세요.
+
[role="tabbed-block"]
====
.작업 메뉴
--
.. 삭제하려는 각 버킷의 확인란을 선택하세요.
.. *작업* > *버킷 삭제*를 선택합니다.


--
.세부 정보 페이지
--
.. 버킷 이름을 선택하면 세부 정보가 표시됩니다.
.. *버킷 삭제*를 선택하세요.


--
====
. 확인 대화 상자가 나타나면 *예*를 선택하세요.
+
StorageGRID 각 버킷이 비어 있는지 확인한 후 각 버킷을 삭제합니다.  이 작업에는 몇 분이 걸릴 수 있습니다.

+
버킷이 비어 있지 않으면 오류 메시지가 나타납니다.  당신은해야합니다link:../tenant/deleting-s3-bucket-objects.html["버킷의 모든 객체와 삭제 마커를 삭제합니다."] 버킷을 삭제하기 전에.


