---
permalink: tenant/duplicating-group.html 
sidebar: sidebar 
keywords: how to duplicate tenant group 
summary: 기존 그룹을 복제하면 더 빠르게 새로운 그룹을 만들 수 있습니다. 
---
= 중복 그룹
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 그룹을 복제하면 더 빠르게 새로운 그룹을 만들 수 있습니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 귀하는 루트 액세스 권한이 있는 사용자 그룹에 속해 있습니다. 보다 link:tenant-management-permissions.html["테넌트 관리 권한"] .


.단계
. *액세스 관리* > *그룹*을 선택하세요.
. 복제하려는 그룹의 확인란을 선택하세요.
. *그룹 복제*를 선택하세요. 그룹 생성에 대한 추가 세부 사항은 그룹 생성 지침을 참조하세요.link:creating-groups-for-s3-tenant.html["S3 테넌트"] 또는link:creating-groups-for-swift-tenant.html["스위프트 세입자"] .
. 로컬 그룹을 만들려면 *로컬 그룹* 탭을 선택하고, 이전에 구성된 ID 소스에서 그룹을 가져오려면 *연합 그룹* 탭을 선택합니다.
+
StorageGRID 시스템에 대해 SSO(Single Sign-On)가 활성화된 경우 로컬 그룹에 속한 사용자는 테넌트 관리자에 로그인할 수 없지만 클라이언트 애플리케이션을 사용하여 테넌트 리소스를 관리할 수 있습니다.link:tenant-management-permissions.html["그룹 권한"] .

. 그룹 이름을 입력하세요.
+
** *로컬 그룹*: 표시 이름과 고유 이름을 모두 입력하세요.  나중에 표시 이름을 편집할 수 있습니다.
** *연합 그룹*: 고유한 이름을 입력하세요.  Active Directory의 경우 고유 이름은 다음과 관련된 이름입니다. `sAMAccountName` 기인하다.  OpenLDAP의 경우 고유 이름은 다음과 관련된 이름입니다. `uid` 기인하다.


. *계속*을 선택하세요.
. 필요에 따라 이 그룹의 권한을 수정하세요.
. *계속*을 선택하세요.
. 필요에 따라 S3 테넌트에 대한 그룹을 복제하는 경우 선택적으로 *S3 정책 추가* 라디오 버튼에서 다른 정책을 선택합니다.  사용자 지정 정책을 선택한 경우 필요에 따라 JSON 문자열을 업데이트합니다.
. *그룹 만들기*를 선택하세요.

