---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: '그리드 관리자가 StorageGRID 시스템에 대한 정보 수명 주기 관리(ILM) 규칙을 만들 때, 선택적으로 객체의 마지막 액세스 시간을 사용하여 해당 객체를 다른 저장 위치로 이동할지 여부를 결정하도록 지정할 수 있습니다.  S3 테넌트를 사용하는 경우 S3 버킷의 객체에 대한 마지막 액세스 시간 업데이트를 활성화하여 이러한 규칙을 활용할 수 있습니다.' 
---
= 마지막 액세스 시간 업데이트 활성화 또는 비활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자가 StorageGRID 시스템에 대한 정보 수명 주기 관리(ILM) 규칙을 만들 때, 선택적으로 객체의 마지막 액세스 시간을 사용하여 해당 객체를 다른 저장 위치로 이동할지 여부를 결정하도록 지정할 수 있습니다.  S3 테넌트를 사용하는 경우 S3 버킷의 객체에 대한 마지막 액세스 시간 업데이트를 활성화하여 이러한 규칙을 활용할 수 있습니다.

이러한 지침은 *마지막 액세스 시간* 옵션을 고급 필터 또는 참조 시간으로 사용하는 하나 이상의 ILM 규칙이 포함된 StorageGRID 시스템에만 적용됩니다.  StorageGRID 시스템에 해당 규칙이 포함되어 있지 않으면 이 지침을 무시할 수 있습니다. 보다link:../ilm/using-last-access-time-in-ilm-rules.html["ILM 규칙에서 마지막 액세스 시간 사용"] 자세한 내용은.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한 관리"] . 이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.


.이 작업에 관하여
*마지막 접근 시간*은 ILM 규칙에 대한 *참조 시간* 배치 지침에 사용할 수 있는 옵션 중 하나입니다.  규칙의 참조 시간을 마지막 액세스 시간으로 설정하면 그리드 관리자가 해당 객체를 마지막으로 검색한(읽거나 본) 시점을 기준으로 객체가 특정 저장 위치에 배치되도록 지정할 수 있습니다.

예를 들어, 최근에 본 객체가 더 빠른 저장소에 남아 있도록 하려면 그리드 관리자가 다음을 지정하는 ILM 규칙을 만들 수 있습니다.

* 지난달에 검색된 객체는 로컬 스토리지 노드에 남아 있어야 합니다.
* 지난 한 달 동안 회수되지 않은 물건은 다른 장소로 옮겨야 합니다.


기본적으로 마지막 액세스 시간에 대한 업데이트는 비활성화되어 있습니다.  StorageGRID 시스템에 *마지막 액세스 시간* 옵션을 사용하는 ILM 규칙이 포함되어 있고 이 옵션을 이 버킷의 개체에 적용하려면 해당 규칙에 지정된 S3 버킷의 마지막 액세스 시간에 대한 업데이트를 활성화해야 합니다.


CAUTION: 객체를 검색할 때 마지막 액세스 시간을 업데이트하면 StorageGRID 성능이 저하될 수 있으며, 특히 객체가 작은 경우 더욱 그렇습니다.

StorageGRID 객체를 검색할 때마다 다음과 같은 추가 단계를 수행해야 하므로 마지막 액세스 시간 업데이트로 인해 성능에 영향이 발생합니다.

* 새로운 타임스탬프로 객체를 업데이트합니다.
* ILM 대기열에 객체를 추가하여 현재 ILM 규칙 및 정책에 대해 다시 평가할 수 있습니다.


이 표는 마지막 액세스 시간이 비활성화되거나 활성화되었을 때 버킷의 모든 객체에 적용되는 동작을 요약한 것입니다.

[cols="1a,1a,1a,1a,1a"]
|===


.2+| 요청 유형 2+| 마지막 액세스 시간이 비활성화된 경우의 동작(기본값) 2+| 마지막 액세스 시간이 활성화된 경우의 동작 


| 마지막 접속 시간이 업데이트되었나요? | ILM 평가 대기열에 개체가 추가되었습니까? | 마지막 접속 시간이 업데이트되었나요? | ILM 평가 대기열에 개체가 추가되었습니까? 


 a| 
객체, 해당 액세스 제어 목록 또는 해당 메타데이터를 검색하라는 요청
 a| 
아니요
 a| 
아니요
 a| 
예
 a| 
예



 a| 
객체의 메타데이터 업데이트 요청
 a| 
예
 a| 
예
 a| 
예
 a| 
예



 a| 
객체 또는 객체 버전을 나열해 달라는 요청
 a| 
아니요
 a| 
아니요
 a| 
아니요
 a| 
아니요



 a| 
한 버킷에서 다른 버킷으로 객체를 복사하라는 요청
 a| 
* 아니요, 원본 사본의 경우
* 네, 대상 사본의 경우

 a| 
* 아니요, 원본 사본의 경우
* 네, 대상 사본의 경우

 a| 
* 네, 원본 사본의 경우
* 네, 대상 사본의 경우

 a| 
* 네, 원본 사본의 경우
* 네, 대상 사본의 경우




 a| 
멀티파트 업로드 완료 요청
 a| 
네, 조립된 객체의 경우
 a| 
네, 조립된 객체의 경우
 a| 
네, 조립된 객체의 경우
 a| 
네, 조립된 객체의 경우

|===
.단계
. 대시보드에서 *버킷 보기*를 선택하거나 *스토리지(S3)* > *버킷*을 선택하세요.
. 표에서 버킷 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. *버킷 옵션* 탭에서 *마지막 액세스 시간 업데이트* 아코디언을 선택합니다.
. 마지막 액세스 시간 업데이트를 활성화하거나 비활성화합니다.
. *변경 사항 저장*을 선택하세요.

