---
permalink: tenant/ilm-policy-tags.html 
sidebar: sidebar 
keywords: how to assign ilm policy tag to bucket 
summary: 개체 스토리지 요구 사항에 따라 버킷에 할당할 ILM 정책 태그를 선택합니다. 
---
= 버킷에 ILM 정책 태그 적용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
개체 스토리지 요구 사항에 따라 버킷에 적용할 ILM 정책 태그를 선택합니다.

ILM 정책은 개체 데이터가 저장되는 위치와 특정 기간이 지난 후 삭제되는지 여부를 제어합니다.  그리드 관리자는 ILM 정책을 만들고 여러 개의 활성 정책을 사용하는 경우 이를 ILM 정책 태그에 할당합니다.


NOTE: 버킷의 정책 태그를 자주 다시 할당하지 마세요.  그렇지 않으면 성능 문제가 발생할 수 있습니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["루트 액세스, 모든 버킷 관리 또는 모든 버킷 보기 권한"] .  이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.


.단계
. 대시보드에서 *버킷 보기*를 선택하거나 *스토리지(S3)* > *버킷*을 선택하세요.
+
버킷 페이지가 나타납니다.  필요에 따라 정보를 열별로 정렬할 수도 있고, 목록을 앞뒤로 넘길 수도 있습니다.

. ILM 정책 태그를 할당할 버킷의 이름을 선택합니다.
+
이미 태그가 할당된 버킷에 대한 ILM 정책 태그 할당을 변경할 수도 있습니다.

+

NOTE: 표시된 개체 수와 사용된 공간 값은 추정치입니다. 이러한 추정치는 수집 타이밍, 네트워크 연결, 노드 상태의 영향을 받습니다.  버킷에 버전 관리가 활성화된 경우 삭제된 개체 버전이 개체 수에 포함됩니다.

. 버킷 옵션 탭에서 ILM 정책 태그 아코디언을 확장합니다.  이 아코디언은 그리드 관리자가 사용자 정의 정책 태그 사용을 활성화한 경우에만 나타납니다.
. 각 정책 태그에 대한 설명을 읽고 버킷에 어떤 태그를 적용해야 할지 확인하세요.
+

CAUTION: 버킷의 ILM 정책 태그를 변경하면 버킷에 있는 모든 개체에 대한 ILM 재평가가 트리거됩니다.  새로운 정책이 제한된 기간 동안만 객체를 보관하는 경우, 이전 객체는 삭제됩니다.

. 버킷에 할당하려는 태그에 대한 라디오 버튼을 선택합니다.
. *변경 사항 저장*을 선택하세요. 키가 있는 버킷에 새로운 S3 버킷 태그가 설정됩니다. `NTAP-SG-ILM-BUCKET-TAG` ILM 정책 태그 이름의 값입니다.
+

CAUTION: S3 애플리케이션이 실수로 새 버킷 태그를 재정의하거나 삭제하지 않도록 주의하세요.  버킷에 새 TagSet을 적용할 때 이 태그가 생략되면 버킷의 개체는 기본 ILM 정책에 따라 평가됩니다.

+

CAUTION: ILM 정책 태그가 검증된 경우 Tenant Manager 또는 Tenant Manager API만 사용하여 ILM 정책 태그를 설정하고 수정합니다.  수정하지 마십시오 `NTAP-SG-ILM-BUCKET-TAG` S3 PutBucketTagging API 또는 S3 DeleteBucketTagging API를 사용하여 ILM 정책 태그를 지정합니다.

+

NOTE: 버킷에 할당된 정책 태그를 변경하면 새 ILM 정책을 사용하여 객체를 다시 평가하는 동안 일시적으로 성능에 영향을 미칩니다.


