---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: '테넌트 계정을 사용하면 S3(Simple Storage Service) REST API 또는 Swift REST API를 사용하여 StorageGRID 시스템에서 객체를 저장하고 검색할 수 있습니다.' 
---
= 세입자 계정 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 계정을 사용하면 S3(Simple Storage Service) REST API 또는 Swift REST API를 사용하여 StorageGRID 시스템에서 객체를 저장하고 검색할 수 있습니다.



== 세입자 계정이란 무엇인가요?

각 테넌트 계정에는 자체 페더레이션 또는 로컬 그룹, 사용자, S3 버킷 또는 Swift 컨테이너 및 개체가 있습니다.

테넌트 계정은 저장된 객체를 여러 엔터티별로 분리하는 데 사용할 수 있습니다.  예를 들어, 다음 두 가지 사용 사례에 여러 테넌트 계정을 사용할 수 있습니다.

* *기업 사용 사례:* StorageGRID 시스템이 기업 내에서 사용되는 경우, 그리드의 개체 스토리지는 조직 내 여러 부서별로 분리될 수 있습니다.  예를 들어, 마케팅 부서, 고객 지원 부서, 인사부 등에 대한 테넌트 계정이 있을 수 있습니다.
+

NOTE: S3 클라이언트 프로토콜을 사용하면 S3 버킷과 버킷 정책을 사용하여 기업 내 부서 간에 객체를 분리할 수도 있습니다. 별도의 테넌트 계정을 만들 필요가 없습니다. 구현에 대한 지침을 참조하세요.link:../s3/bucket-and-group-access-policies.html["S3 버킷 및 버킷 정책"] 자세한 내용은.

* *서비스 제공자 사용 사례:* StorageGRID 시스템이 서비스 제공자에 의해 사용되는 경우, 그리드의 개체 스토리지는 스토리지를 임대하는 여러 엔터티에 의해 분리될 수 있습니다.  예를 들어, 회사 A, 회사 B, 회사 C 등의 세입자 계정이 있을 수 있습니다.




== 테넌트 계정을 만드는 방법

세입자 계정은 다음에 의해 생성됩니다.link:../admin/managing-tenants.html["Grid Manager를 사용하는 StorageGRID 그리드 관리자"] .  테넌트 계정을 생성할 때 그리드 관리자는 다음을 지정합니다.

* 테넌트 이름, 클라이언트 유형(S3), 선택적 스토리지 할당량을 포함한 기본 정보입니다.
* 테넌트 계정에 대한 권한(예: 테넌트 계정이 S3 플랫폼 서비스를 사용할 수 있는지, 자체 ID 소스를 구성할 수 있는지, S3 Select를 사용할 수 있는지, 그리드 페더레이션 연결을 사용할 수 있는지 여부)입니다.
* StorageGRID 시스템이 로컬 그룹 및 사용자, ID 페더레이션 또는 SSO(Single Sign-On)를 사용하는지 여부에 따라 테넌트의 초기 루트 액세스 권한이 결정됩니다.


또한, S3 테넌트 계정이 규정 요구 사항을 준수해야 하는 경우 그리드 관리자는 StorageGRID 시스템에 대해 S3 개체 잠금 설정을 활성화할 수 있습니다.  S3 개체 잠금이 활성화되면 모든 S3 테넌트 계정에서 규정을 준수하는 버킷을 만들고 관리할 수 있습니다.



=== S3 테넌트 구성

후에link:../admin/creating-tenant-account.html["S3 테넌트 계정이 생성되었습니다."] , 테넌트 관리자에 액세스하여 다음과 같은 작업을 수행할 수 있습니다.

* ID 페더레이션 설정(ID 소스가 그리드와 공유되지 않는 경우)
* 그룹 및 사용자 관리
* 계정 복제 및 크로스 그리드 복제에 그리드 페더레이션을 사용합니다.
* S3 액세스 키 관리
* S3 버킷 생성 및 관리
* S3 플랫폼 서비스 사용
* S3 Select 사용
* 저장 공간 사용량 모니터링



TIP: 테넌트 관리자를 사용하여 S3 버킷을 생성하고 관리할 수 있지만 다음을 사용해야 합니다.link:../s3/index.html["S3 클라이언트"] 또는link:use-s3-console.html["S3 콘솔"] 객체를 수집하고 관리합니다.
