---
permalink: tenant/specifying-urn-for-platform-services-endpoint.html 
sidebar: sidebar 
keywords: how to specify platform services urn 
summary: '플랫폼 서비스 엔드포인트를 생성할 때 고유 리소스 이름(URN)을 지정해야 합니다.  플랫폼 서비스에 대한 구성 XML을 생성할 때 URN을 사용하여 엔드포인트를 참조합니다.  각 엔드포인트의 URN은 고유해야 합니다.' 
---
= 플랫폼 서비스 엔드포인트에 대한 URN을 지정합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
플랫폼 서비스 엔드포인트를 생성할 때 고유 리소스 이름(URN)을 지정해야 합니다.  플랫폼 서비스에 대한 구성 XML을 생성할 때 URN을 사용하여 엔드포인트를 참조합니다.  각 엔드포인트의 URN은 고유해야 합니다.

StorageGRID 플랫폼 서비스 엔드포인트를 생성할 때 이를 검증합니다.  플랫폼 서비스 엔드포인트를 생성하기 전에 엔드포인트에 지정된 리소스가 존재하고 접근할 수 있는지 확인하세요.



== URN 요소

플랫폼 서비스 엔드포인트의 URN은 다음 중 하나로 시작해야 합니다. `arn:aws` 또는 `urn:mysite` 다음과 같습니다.

* 서비스가 Amazon Web Services(AWS)에서 호스팅되는 경우 다음을 사용하세요. `arn:aws`
* 서비스가 Google Cloud Platform(GCP)에서 호스팅되는 경우 다음을 사용하세요. `arn:aws`
* 서비스가 로컬로 호스팅되는 경우 다음을 사용하세요. `urn:mysite`


예를 들어 StorageGRID 에 호스팅된 CloudMirror 엔드포인트에 대한 URN을 지정하는 경우 URN은 다음으로 시작할 수 있습니다. `urn:sgws` .

URN의 다음 요소는 다음과 같이 플랫폼 서비스 유형을 지정합니다.

[cols="2a,1a"]
|===
| 서비스 | 유형 


 a| 
CloudMirror 복제
 a| 
`s3`



 a| 
알림
 a| 
`sns`또는 `kafka`



 a| 
검색 통합
 a| 
`es`

|===
예를 들어 StorageGRID 에 호스팅된 CloudMirror 엔드포인트에 대한 URN 지정을 계속하려면 다음을 추가합니다. `s3` 얻다 `urn:sgws:s3` .

URN의 마지막 요소는 대상 URI에서 특정 대상 리소스를 식별합니다.

[cols="1a,2a"]
|===
| 서비스 | 특정 리소스 


 a| 
CloudMirror 복제
 a| 
`bucket-name`



 a| 
알림
 a| 
`sns-topic-name`또는 `kafka-topic-name`



 a| 
검색 통합
 a| 
`domain-name/index-name/type-name`

*참고:* Elasticsearch 클러스터가 인덱스를 자동으로 생성하도록 구성되지 *않은* 경우 엔드포인트를 생성하기 전에 인덱스를 수동으로 생성해야 합니다.

|===


== AWS 및 GCP에서 호스팅되는 서비스에 대한 URN

AWS 및 GCP 엔터티의 경우 전체 URN이 유효한 AWS ARN입니다. 예를 들어:

* CloudMirror 복제:
+
[listing]
----
arn:aws:s3:::bucket-name
----
* 알림:
+
[listing]
----
arn:aws:sns:region:account-id:topic-name
----
* 검색 통합:
+
[listing]
----
arn:aws:es:region:account-id:domain/domain-name/index-name/type-name
----
+

NOTE: AWS 검색 통합 엔드포인트의 경우 `domain-name` 리터럴 문자열을 포함해야 합니다. `domain/` 여기에 표시된 대로.





== 로컬 호스팅 서비스를 위한 URN

클라우드 서비스 대신 로컬 호스팅 서비스를 사용하는 경우, URN의 세 번째이자 마지막 위치에 필요한 요소가 포함되어 있는 한, 유효하고 고유한 URN을 생성하는 어떤 방식으로든 URN을 지정할 수 있습니다.  선택 사항으로 표시된 요소는 비워둘 수도 있고, 리소스를 식별하고 URN을 고유하게 만드는 데 도움이 되는 방식으로 지정할 수도 있습니다. 예를 들어:

* CloudMirror 복제:
+
[listing]
----
urn:mysite:s3:optional:optional:bucket-name
----
+
StorageGRID 에 호스팅된 CloudMirror 엔드포인트의 경우 다음으로 시작하는 유효한 URN을 지정할 수 있습니다. `urn:sgws` :

+
[listing]
----
urn:sgws:s3:optional:optional:bucket-name
----
* 알림:
+
Amazon Simple Notification Service 엔드포인트를 지정합니다.

+
[listing]
----
urn:mysite:sns:optional:optional:sns-topic-name
----
+
Kafka 엔드포인트를 지정하세요.

+
[listing]
----
urn:mysite:kafka:optional:optional:kafka-topic-name
----
* 검색 통합:
+
[listing]
----
urn:mysite:es:optional:optional:domain-name/index-name/type-name
----
+

NOTE: 로컬 호스팅 검색 통합 엔드포인트의 경우 `domain-name` 요소는 엔드포인트의 URN이 고유한 한 어떤 문자열이든 될 수 있습니다.


