---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 테넌트 그룹을 만들기 전에 해당 그룹에 어떤 권한을 할당할지 고려하세요.  테넌트 관리 권한은 사용자가 테넌트 관리자 또는 테넌트 관리 API를 사용하여 수행할 수 있는 작업을 결정합니다.  사용자는 하나 이상의 그룹에 속할 수 있습니다.  사용자가 여러 그룹에 속해 있는 경우 권한이 누적됩니다. 
---
= 테넌트 관리 권한
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 그룹을 만들기 전에 해당 그룹에 어떤 권한을 할당할지 고려하세요.  테넌트 관리 권한은 사용자가 테넌트 관리자 또는 테넌트 관리 API를 사용하여 수행할 수 있는 작업을 결정합니다.  사용자는 하나 이상의 그룹에 속할 수 있습니다.  사용자가 여러 그룹에 속해 있는 경우 권한이 누적됩니다.

테넌트 관리자에 로그인하거나 테넌트 관리 API를 사용하려면 사용자는 최소한 하나 이상의 권한이 있는 그룹에 속해야 합니다.  로그인할 수 있는 모든 사용자는 다음 작업을 수행할 수 있습니다.

* 대시보드 보기
* 로컬 사용자의 경우 자신의 비밀번호 변경


모든 권한에 대해 그룹의 액세스 모드 설정은 사용자가 설정을 변경하고 작업을 수행할 수 있는지 또는 관련 설정과 기능을 볼 수만 있는지를 결정합니다.


NOTE: 사용자가 여러 그룹에 속해 있고 그룹 중 하나가 읽기 전용으로 설정된 경우, 사용자는 선택한 모든 설정과 기능에 대한 읽기 전용 액세스 권한을 갖습니다.

그룹에 다음과 같은 권한을 할당할 수 있습니다. S3 테넌트와 Swift 테넌트는 그룹 권한이 다르다는 점에 유의하세요.

[cols="1a,3a,3a"]
|===
| 허가 | 설명 | 세부 


 a| 
루트 접근
 a| 
테넌트 관리자와 테넌트 관리 API에 대한 전체 액세스 권한을 제공합니다.
 a| 
Swift 사용자는 테넌트 계정에 로그인하려면 루트 액세스 권한이 있어야 합니다.



 a| 
관리자
 a| 
Swift 세입자만 해당.  이 테넌트 계정에 대한 Swift 컨테이너 및 개체에 대한 전체 액세스 권한을 제공합니다.
 a| 
Swift 사용자는 Swift REST API를 사용하여 모든 작업을 수행하려면 Swift 관리자 권한이 있어야 합니다.



 a| 
자신의 S3 자격 증명을 관리하세요
 a| 
사용자가 자신의 S3 액세스 키를 만들고 제거할 수 있습니다.
 a| 
이 권한이 없는 사용자에게는 *저장소(S3)* > *내 S3 액세스 키* 메뉴 옵션이 표시되지 않습니다.



 a| 
모든 버킷 보기
 a| 
*S3 테넌트*: 사용자가 모든 버킷과 버킷 구성을 볼 수 있습니다.

*Swift 테넌트*: Swift 사용자가 테넌트 관리 API를 사용하여 모든 컨테이너와 컨테이너 구성을 볼 수 있도록 합니다.
 a| 
모든 버킷 보기 또는 모든 버킷 관리 권한이 없는 사용자에게는 *버킷* 메뉴 옵션이 표시되지 않습니다.

이 권한은 모든 버킷 관리 권한으로 대체됩니다. 이는 S3 클라이언트나 S3 콘솔에서 사용하는 S3 버킷이나 그룹 정책에는 영향을 미치지 않습니다.

이 권한은 Tenant Management API의 Swift 그룹에만 할당할 수 있습니다.  테넌트 관리자를 사용하여 Swift 그룹에 이 권한을 할당할 수 없습니다.



 a| 
모든 버킷 관리
 a| 
*S3 테넌트*: 사용자가 테넌트 관리자와 테넌트 관리 API를 사용하여 S3 버킷을 생성 및 삭제하고, S3 버킷이나 그룹 정책에 관계없이 테넌트 계정의 모든 S3 버킷에 대한 설정을 관리할 수 있습니다.

*Swift 테넌트*: Swift 사용자가 테넌트 관리 API를 사용하여 Swift 컨테이너의 일관성을 제어할 수 있습니다.
 a| 
모든 버킷 보기 또는 모든 버킷 관리 권한이 없는 사용자에게는 *버킷* 메뉴 옵션이 표시되지 않습니다.

이 권한은 모든 버킷 보기 권한보다 우선합니다. 이는 S3 클라이언트나 S3 콘솔에서 사용하는 S3 버킷이나 그룹 정책에는 영향을 미치지 않습니다.

이 권한은 Tenant Management API의 Swift 그룹에만 할당할 수 있습니다.  테넌트 관리자를 사용하여 Swift 그룹에 이 권한을 할당할 수 없습니다.



 a| 
엔드포인트 관리
 a| 
사용자가 테넌트 관리자 또는 테넌트 관리 API를 사용하여 StorageGRID 플랫폼 서비스의 대상으로 사용되는 플랫폼 서비스 엔드포인트를 생성하거나 편집할 수 있도록 합니다.
 a| 
이 권한이 없는 사용자에게는 *플랫폼 서비스 엔드포인트* 메뉴 옵션이 표시되지 않습니다.



 a| 
S3 콘솔 탭 사용
 a| 
모든 버킷 보기 또는 모든 버킷 관리 권한과 결합하면 사용자는 버킷의 세부 정보 페이지에 있는 S3 콘솔 탭에서 객체를 보고 관리할 수 있습니다.
 a| 

|===