---
permalink: tenant/tenant-management-api-versioning.html 
sidebar: sidebar 
keywords: tenant management api version 
summary: 테넌트 관리 API는 버전 관리를 사용하여 중단 없는 업그레이드를 지원합니다. 
---
= 테넌트 관리 API 버전 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 관리 API는 버전 관리를 사용하여 중단 없는 업그레이드를 지원합니다.

예를 들어, 이 요청 URL은 API 버전 4를 지정합니다.

`https://_hostname_or_ip_address_/api/v4/authorize`

이전 버전과 호환되지 않는 변경 사항이 있는 경우 API의 주요 버전이 올라갑니다.  API의 하위 버전은 이전 버전과 호환되는 변경 사항이 있을 경우 업데이트됩니다.  호환되는 변경 사항에는 새로운 엔드포인트나 새로운 속성의 추가가 포함됩니다.

다음 예는 변경 유형에 따라 API 버전이 어떻게 변경되는지 보여줍니다.

[cols="1a,1a,1a"]
|===
| API 변경 유형 | 이전 버전 | 새로운 버전 


 a| 
이전 버전과 호환 가능
 a| 
2.1
 a| 
2.2



 a| 
이전 버전과 호환되지 않습니다
 a| 
2.1
 a| 
3.0



 a| 
3.0
 a| 
4.0

|===
처음으로 StorageGRID 소프트웨어를 설치하면 최신 버전의 API만 활성화됩니다.  하지만 StorageGRID 의 새로운 기능 릴리스로 업그레이드하는 경우 최소한 하나의 StorageGRID 기능 릴리스에 대한 이전 API 버전에 계속 액세스할 수 있습니다.


NOTE: 지원되는 버전을 구성할 수 있습니다.  Swagger API 설명서의 *config* 섹션을 참조하세요.link:../admin/using-grid-management-api.html["그리드 관리 API"] 자세한 내용은.  모든 API 클라이언트를 최신 버전으로 업데이트한 후에는 이전 버전에 대한 지원을 비활성화해야 합니다.

오래된 요청은 다음과 같은 방법으로 더 이상 사용되지 않는 것으로 표시됩니다.

* 응답 헤더는 "Deprecated: true"입니다.
* JSON 응답 본문에 "deprecated": true가 포함되어 있습니다.
* 더 이상 사용되지 않는 경고가 nms.log에 추가되었습니다. 예를 들어:
+
[listing]
----
Received call to deprecated v2 API at POST "/api/v2/authorize"
----




== 현재 릴리스에서 지원되는 API 버전을 확인하세요.

사용하다 `GET /versions` 지원되는 API 주요 버전 목록을 반환하는 API 요청입니다.  이 요청은 Swagger API 문서의 *config* 섹션에 있습니다.

[listing]
----
GET https://{{IP-Address}}/api/versions
{
  "responseTime": "2023-06-27T22:13:50.750Z",
  "status": "success",
  "apiVersion": "4.0",
  "data": [
    2,
    3,
    4
  ]
}
----


== 요청에 대한 API 버전을 지정하세요

경로 매개변수를 사용하여 API 버전을 지정할 수 있습니다.(`/api/v4` ) 또는 헤더(`Api-Version: 4` ).  두 값을 모두 제공하는 경우 헤더 값이 경로 값보다 우선합니다.

[listing]
----
curl https://[IP-Address]/api/v4/grid/accounts

curl -H "Api-Version: 4" https://[IP-Address]/api/grid/accounts
----