---
permalink: tenant/understanding-cloudmirror-replication-service.html 
sidebar: sidebar 
keywords: cloudmirror replication 
summary: StorageGRID 버킷에 추가된 지정된 객체를 하나 이상의 대상 버킷에 복제하도록 하려면 S3 버킷에 대해 CloudMirror 복제를 활성화할 수 있습니다. 
---
= CloudMirror 복제 서비스 이해하기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 버킷에 추가된 지정된 객체를 하나 이상의 외부 대상 버킷에 복제하도록 하려면 S3 버킷에 대해 CloudMirror 복제를 활성화할 수 있습니다.

예를 들어, CloudMirror 복제를 사용하여 특정 고객 레코드를 Amazon S3로 미러링한 다음 AWS 서비스를 활용하여 데이터에 대한 분석을 수행할 수 있습니다.


NOTE: 소스 버킷에 S3 개체 잠금이 활성화된 경우 CloudMirror 복제가 지원되지 않습니다.



== CloudMirror와 ILM

CloudMirror 복제는 그리드의 활성 ILM 정책과 독립적으로 작동합니다.  CloudMirror 서비스는 객체가 소스 버킷에 저장된 대로 객체를 복제하고 가능한 한 빨리 대상 버킷에 전달합니다.  복제된 객체의 전달은 객체 수집이 성공하면 트리거됩니다.



== CloudMirror 및 크로스 그리드 복제

CloudMirror 복제는 크로스 그리드 복제 기능과 중요한 유사점과 차이점이 있습니다. link:../admin/grid-federation-compare-cgr-to-cloudmirror.html["크로스 그리드 복제와 CloudMirror 복제 비교"] .



== CloudMirror 및 S3 버킷

CloudMirror 복제는 일반적으로 외부 S3 버킷을 대상으로 사용하도록 구성됩니다.  하지만 다른 StorageGRID 배포나 S3 호환 서비스를 사용하도록 복제를 구성할 수도 있습니다.

기존 버킷:: 기존 버킷에 대해 CloudMirror 복제를 활성화하면 해당 버킷에 추가된 새 개체만 복제됩니다.  버킷에 있는 기존 객체는 복제되지 않습니다.  기존 개체의 복제를 강제로 수행하려면 개체 복사를 수행하여 기존 개체의 메타데이터를 업데이트할 수 있습니다.
+
--

NOTE: CloudMirror 복제를 사용하여 객체를 Amazon S3 대상으로 복사하는 경우 Amazon S3가 각 PUT 요청 헤더 내의 사용자 정의 메타데이터 크기를 2KB로 제한한다는 점에 유의하세요.  개체에 2KB보다 큰 사용자 정의 메타데이터가 있는 경우 해당 개체는 복제되지 않습니다.

--
여러 대상 버킷:: 단일 버킷의 객체를 여러 대상 버킷에 복제하려면 복제 구성 XML에서 각 규칙에 대한 대상을 지정합니다.  동시에 두 개 이상의 버킷에 객체를 복제할 수 없습니다.
버전이 지정된 버킷 또는 버전이 지정되지 않은 버킷:: 버전이 지정된 버킷이나 버전이 지정되지 않은 버킷에서 CloudMirror 복제를 구성할 수 있습니다.  대상 버킷은 버전이 지정되어 있을 수도 있고 지정되어 있지 않을 수도 있습니다.  버전이 지정된 버킷과 버전이 지정되지 않은 버킷을 원하는 대로 조합하여 사용할 수 있습니다.  예를 들어, 버전이 지정된 버킷을 버전이 지정되지 않은 소스 버킷의 대상으로 지정하거나 그 반대로 지정할 수 있습니다.  버전이 지정되지 않은 버킷 간에도 복제할 수 있습니다.




== 삭제, 복제 루프 및 이벤트

삭제 동작:: Amazon S3 서비스의 삭제 동작인 CRR(Cross-Region Replication)과 동일합니다.  소스 버킷에서 객체를 삭제해도 대상에 있는 복제된 객체는 삭제되지 않습니다.  소스 버킷과 대상 버킷 모두 버전이 관리된 경우 삭제 마커가 복제됩니다.  대상 버킷의 버전이 지정되지 않은 경우 소스 버킷에서 객체를 삭제해도 삭제 마커가 대상 버킷에 복제되지 않고 대상 객체도 삭제되지 않습니다.
복제 루프로부터 보호:: 객체가 대상 버킷에 복제되면 StorageGRID 이를 "복제본"으로 표시합니다.  대상 StorageGRID 버킷은 복제본으로 표시된 객체를 다시 복제하지 않으므로 실수로 복제 루프가 발생하는 것을 방지할 수 있습니다.  이 복제본 표시는 StorageGRID 내부에서 이루어지며 Amazon S3 버킷을 대상으로 사용할 때 AWS CRR을 활용하는 것을 방해하지 않습니다.
+
--

NOTE: 복제본을 표시하는 데 사용되는 사용자 정의 헤더는 다음과 같습니다. `x-ntap-sg-replica` .  이 표시는 거울이 쏟아지는 것을 방지합니다.  StorageGRID 두 그리드 간의 양방향 CloudMirror를 지원합니다.

--
대상 버킷의 이벤트:: 대상 버킷의 이벤트의 고유성과 순서는 보장되지 않습니다.  전달 성공을 보장하기 위해 수행된 작업의 결과로 소스 객체의 동일한 사본이 두 개 이상 목적지에 전달될 수 있습니다.  드물지만 동일한 개체가 두 개 이상의 서로 다른 StorageGRID 사이트에서 동시에 업데이트되는 경우 대상 버킷의 작업 순서가 소스 버킷의 이벤트 순서와 일치하지 않을 수 있습니다.

