---
permalink: tenant/understanding-search-integration-service.html 
sidebar: sidebar 
keywords: how to understand search integration service 
summary: 개체 메타데이터에 대해 외부 검색 및 데이터 분석 서비스를 사용하려면 S3 버킷에 대한 검색 통합을 활성화할 수 있습니다. 
---
= 검색 통합 서비스 이해하기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
개체 메타데이터에 대해 외부 검색 및 데이터 분석 서비스를 사용하려면 S3 버킷에 대한 검색 통합을 활성화할 수 있습니다.

검색 통합 서비스는 객체가 생성되거나 삭제되거나 해당 메타데이터나 태그가 업데이트될 때마다 S3 객체 메타데이터를 대상 엔드포인트에 자동적이고 비동기적으로 전송하는 맞춤형 StorageGRID 서비스입니다.  그런 다음 대상 서비스에서 제공하는 정교한 검색, 데이터 분석, 시각화 또는 머신 러닝 도구를 사용하여 개체 데이터를 검색, 분석하고 통찰력을 얻을 수 있습니다.

예를 들어, 버킷을 구성하여 S3 객체 메타데이터를 원격 Elasticsearch 서비스로 보낼 수 있습니다.  그런 다음 Elasticsearch를 사용하여 버킷 전체에서 검색을 수행하고 개체 메타데이터에 있는 패턴에 대한 정교한 분석을 수행할 수 있습니다.

S3 객체 잠금이 활성화된 버킷에서 Elasticsearch 통합을 구성할 수 있지만, 객체의 S3 객체 잠금 메타데이터(보관 기한 및 법적 보존 상태 포함)는 Elasticsearch로 전송되는 메타데이터에 포함되지 않습니다.


NOTE: 검색 통합 서비스는 개체 메타데이터를 대상으로 전송하므로 해당 구성 XML을 "_메타데이터_ 알림 구성 XML"이라고 합니다.  이 구성 XML은 _이벤트_ 알림을 활성화하는 데 사용되는 "알림 구성 XML"과 다릅니다.



== 검색 통합 및 S3 버킷

버전이 지정되었거나 지정되지 않은 모든 버킷에 대해 검색 통합 서비스를 활성화할 수 있습니다.  검색 통합은 메타데이터 알림 구성 XML을 어떤 객체에 대해 작업을 수행할지, 그리고 객체 메타데이터의 대상을 지정하는 버킷과 연결하여 구성됩니다.

메타데이터 알림은 버킷 이름, 개체 이름, 버전 ID(있는 경우)로 명명된 JSON 문서 형식으로 생성됩니다.  각 메타데이터 알림에는 모든 객체의 태그와 사용자 메타데이터 외에도 객체에 대한 표준 시스템 메타데이터 세트가 포함되어 있습니다.


NOTE: 태그와 사용자 메타데이터의 경우 StorageGRID 날짜와 숫자를 문자열이나 S3 이벤트 알림으로 Elasticsearch에 전달합니다.  이러한 문자열을 날짜나 숫자로 해석하도록 Elasticsearch를 구성하려면 Elasticsearch의 동적 필드 매핑 및 날짜 형식 매핑 지침을 따르세요.  검색 통합 서비스를 구성하기 전에 인덱스에서 동적 필드 매핑을 활성화해야 합니다.  문서가 색인된 후에는 색인에서 문서의 필드 유형을 편집할 수 없습니다.



== 검색 알림

메타데이터 알림은 다음과 같은 경우 생성되어 전달 대기열에 추가됩니다.

* 객체가 생성됩니다.
* 그리드의 ILM 정책 작동으로 인해 개체가 삭제되는 경우를 포함하여 개체가 삭제됩니다.
* 개체 메타데이터 또는 태그가 추가, 업데이트 또는 삭제됩니다.  업데이트 시에는 변경된 값만이 아니라 전체 메타데이터와 태그 세트가 항상 전송됩니다.


버킷에 메타데이터 알림 구성 XML을 추가하면 새로 만든 모든 개체와 데이터, 사용자 메타데이터 또는 태그를 업데이트하여 수정한 모든 개체에 대한 알림이 전송됩니다.  하지만 이미 버킷에 있는 객체에 대해서는 알림이 전송되지 않습니다.  버킷에 있는 모든 개체의 개체 메타데이터가 대상으로 전송되도록 하려면 다음 중 하나를 수행해야 합니다.

* 버킷을 생성한 후, 객체를 추가하기 전에 즉시 검색 통합 서비스를 구성하세요.
* 버킷에 이미 있는 모든 개체에 대해 대상에 메타데이터 알림 메시지를 전송하는 작업을 수행합니다.




== 검색 통합 서비스 및 Elasticsearch

StorageGRID 검색 통합 서비스는 Elasticsearch 클러스터를 대상으로 지원합니다.  다른 플랫폼 서비스와 마찬가지로 대상은 서비스의 구성 XML에서 URN이 사용되는 엔드포인트에 지정됩니다.  사용하다 https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 도구"^] 지원되는 Elasticsearch 버전을 확인합니다.
