---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: '버킷을 생성할 때 S3 개체 잠금을 활성화한 경우 버킷을 편집하여 기본 보존 설정을 변경할 수 있습니다.  기본 보존을 활성화(또는 비활성화)하고 기본 보존 모드와 보존 기간을 설정할 수 있습니다.' 
---
= S3 객체 잠금 기본 보존 기간 업데이트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버킷을 생성할 때 S3 개체 잠금을 활성화한 경우 버킷을 편집하여 기본 보존 설정을 변경할 수 있습니다.  기본 보존을 활성화(또는 비활성화)하고 기본 보존 모드와 보존 기간을 설정할 수 있습니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["모든 버킷 또는 루트 액세스 권한 관리"] . 이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.
* S3 객체 잠금은 StorageGRID 시스템에서 전역적으로 활성화되어 있으며, 버킷을 생성할 때 S3 객체 잠금을 활성화했습니다. 보다 link:using-s3-object-lock.html["S3 객체 잠금을 사용하여 객체를 유지합니다."] .


.단계
. 대시보드에서 *버킷 보기*를 선택하거나 *스토리지(S3)* > *버킷*을 선택하세요.
. 표에서 버킷 이름을 선택합니다.
+
버킷 세부 정보 페이지가 나타납니다.

. *버킷 옵션* 탭에서 *S3 개체 잠금* 아코디언을 선택합니다.
. 선택적으로 이 버킷에 대한 *기본 보존*을 활성화하거나 비활성화합니다.
+
이 설정에 대한 변경 사항은 버킷에 이미 있는 개체나 자체 보존 기간이 있는 개체에는 적용되지 않습니다.

. *기본 보존*이 활성화된 경우 버킷에 대한 *기본 보존 모드*를 지정합니다.
+
[cols="1a,2a"]
|===
| 기본 보존 모드 | 설명 


 a| 
통치
 a| 
** 사용자 `s3:BypassGovernanceRetention` 허가를 사용할 수 있습니다 `x-amz-bypass-governance-retention: true` 보존 설정을 우회하기 위한 요청 헤더입니다.
** 이러한 사용자는 보관 기한에 도달하기 전에 개체 버전을 삭제할 수 있습니다.
** 이러한 사용자는 객체의 보관 기간을 늘리거나 줄이거나 제거할 수 있습니다.




 a| 
규정 준수
 a| 
** 해당 객체는 보관 만료일에 도달할 때까지 삭제할 수 없습니다.
** 객체의 보관 기한은 늘릴 수 있지만 줄일 수는 없습니다.
** 해당 날짜에 도달하기 전까지는 객체의 보관 기간을 제거할 수 없습니다.


*참고*: 그리드 관리자가 규정 준수 모드를 사용하도록 허용해야 합니다.

|===
. *기본 보존*이 활성화된 경우 버킷의 *기본 보존 기간*을 지정합니다.
+
*기본 보존 기간*은 이 버킷에 추가된 새 객체를 수집한 시점부터 보존해야 하는 기간을 나타냅니다. 그리드 관리자가 설정한 테넌트의 최대 보존 기간보다 작거나 같은 값을 지정합니다.

+
그리드 관리자가 테넌트를 생성할 때 최대 보존 기간이 설정되며, 이 기간은 1일에서 100년까지의 값이 될 수 있습니다.  _기본_ 보존 기간을 설정하면 최대 보존 기간에 설정된 값을 초과할 수 없습니다.  필요한 경우 그리드 관리자에게 최대 보존 기간을 늘리거나 줄여달라고 요청하세요.

. *변경 사항 저장*을 선택하세요.

