---
permalink: tenant/using-s3-object-lock.html 
sidebar: sidebar 
keywords: how to use s3 object lock 
summary: 버킷과 객체가 보존에 대한 규정 요구 사항을 준수해야 하는 경우 S3 객체 잠금을 사용할 수 있습니다. 
---
= S3 객체 잠금을 사용하여 객체를 유지합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버킷과 객체가 보존에 대한 규정 요구 사항을 준수해야 하는 경우 S3 객체 잠금을 사용할 수 있습니다.


NOTE: 그리드 관리자는 S3 개체 잠금의 특정 기능을 사용할 수 있는 권한을 부여해야 합니다.



== S3 객체 잠금이란 무엇인가요?

StorageGRID S3 객체 잠금 기능은 Amazon Simple Storage Service(Amazon S3)의 S3 객체 잠금과 동일한 객체 보호 솔루션입니다.

StorageGRID 시스템에 대해 글로벌 S3 개체 잠금 설정이 활성화된 경우 S3 테넌트 계정은 S3 개체 잠금이 활성화되어 있거나 활성화되지 않은 버킷을 생성할 수 있습니다.  버킷에 S3 객체 잠금이 활성화된 경우 버킷 버전 관리가 필요하며 자동으로 활성화됩니다.

*S3 객체 잠금이 없는 버킷*에는 보존 설정이 지정되지 않은 객체만 있을 수 있습니다.  섭취된 객체에는 보존 설정이 없습니다.

*S3 객체 잠금이 있는 버킷*에는 S3 클라이언트 애플리케이션에서 지정한 보존 설정이 있는 객체와 없는 객체가 있을 수 있습니다.  수집된 일부 객체에는 보존 설정이 있습니다.

*S3 객체 잠금 및 기본 보존 기간이 구성된 버킷*에는 보존 기간이 지정된 객체를 업로드할 수 있으며 보존 기간이 설정되지 않은 새 객체를 업로드할 수 있습니다.  새 개체는 보존 설정이 개체 수준에서 구성되지 않았기 때문에 기본 설정을 사용합니다.

실제로 기본 보존이 구성된 경우 새로 수집된 모든 개체에는 보존 설정이 적용됩니다.  객체 보존 설정이 없는 기존 객체는 영향을 받지 않습니다.



=== 보존 모드

StorageGRID S3 객체 잠금 기능은 객체에 다양한 수준의 보호를 적용하기 위해 두 가지 보존 모드를 지원합니다.  이러한 모드는 Amazon S3 보존 모드와 동일합니다.

* 규정 준수 모드에서:
+
** 해당 객체는 보관 만료일에 도달할 때까지 삭제할 수 없습니다.
** 객체의 보관 기한은 늘릴 수 있지만 줄일 수는 없습니다.
** 해당 날짜에 도달하기 전까지는 객체의 보관 기간을 제거할 수 없습니다.


* 거버넌스 모드에서:
+
** 특별 권한이 있는 사용자는 요청에서 우회 헤더를 사용하여 특정 보존 설정을 수정할 수 있습니다.
** 이러한 사용자는 보관 기한에 도달하기 전에 개체 버전을 삭제할 수 있습니다.
** 이러한 사용자는 객체의 보관 기간을 늘리거나 줄이거나 제거할 수 있습니다.






=== 객체 버전에 대한 보존 설정

S3 객체 잠금이 활성화된 버킷을 생성한 경우 사용자는 S3 클라이언트 애플리케이션을 사용하여 버킷에 추가된 각 객체에 대해 다음과 같은 보존 설정을 선택적으로 지정할 수 있습니다.

* *보존 모드*: 규정 준수 또는 거버넌스.
* *보관 날짜*: 개체 버전의 보관 날짜가 미래인 경우, 개체를 검색할 수는 있지만 삭제할 수는 없습니다.
* *법적 보존*: 객체 버전에 법적 보존을 적용하면 해당 객체가 즉시 잠깁니다.  예를 들어, 조사나 법적 분쟁과 관련된 객체에 대해 법적 보류를 요청해야 할 수도 있습니다.  법적 보존에는 만료일이 없지만, 명시적으로 삭제하기 전까지는 유지됩니다.  법적 보존 기간은 보존 기한과 별개입니다.
+

NOTE: 객체가 법적 보존 상태에 있는 경우, 보존 모드에 관계없이 누구도 객체를 삭제할 수 없습니다.

+
객체 설정에 대한 자세한 내용은 다음을 참조하세요.link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 객체 잠금을 구성합니다."] .





=== 버킷에 대한 기본 보존 설정

S3 객체 잠금이 활성화된 버킷이 생성된 경우 사용자는 선택적으로 버킷에 대해 다음과 같은 기본 설정을 지정할 수 있습니다.

* *기본 보존 모드*: 규정 준수 또는 거버넌스.
* *기본 보존 기간*: 이 버킷에 추가된 새 개체 버전을 보존해야 하는 기간으로, 추가된 날로부터 시작됩니다.


기본 버킷 설정은 자체 보존 설정이 없는 새 개체에만 적용됩니다.  이러한 기본 설정을 추가하거나 변경해도 기존 버킷 개체는 영향을 받지 않습니다.

보다link:../tenant/creating-s3-bucket.html["S3 버킷 생성"] 그리고link:../tenant/update-default-retention-settings.html["S3 객체 잠금 기본 보존 기간 업데이트"] .



== S3 객체 잠금 작업

그리드 관리자와 테넌트 사용자를 위한 다음 목록에는 S3 객체 잠금 기능을 사용하기 위한 고급 작업이 포함되어 있습니다.

그리드 관리자::
+
--
* StorageGRID 시스템 전체에 대해 글로벌 S3 개체 잠금 설정을 활성화합니다.
* 정보 수명 주기 관리(ILM) 정책이 _규정을 준수_하는지 확인하십시오. 즉, 다음을 충족합니다.link:../ilm/managing-objects-with-s3-object-lock.html["S3 객체 잠금이 활성화된 버킷의 요구 사항"] .
* 필요에 따라 세입자가 보존 모드로 규정 준수를 사용하도록 허용합니다.  그렇지 않은 경우 거버넌스 모드만 허용됩니다.
* 필요에 따라 세입자의 최대 보존 기간을 설정합니다.


--
세입자 사용자::
+
--
* S3 객체 잠금을 사용하여 버킷 및 객체에 대한 고려 사항을 검토합니다.
* 필요에 따라 그리드 관리자에게 연락하여 글로벌 S3 개체 잠금 설정을 활성화하고 권한을 설정하세요.
* S3 객체 잠금이 활성화된 버킷을 생성합니다.
* 선택적으로 버킷에 대한 기본 보존 설정을 구성합니다.
+
** 기본 보존 모드: 그리드 관리자가 허용하는 경우 거버넌스 또는 규정 준수.
** 기본 보존 기간: 그리드 관리자가 설정한 최대 보존 기간보다 짧거나 같아야 합니다.


* S3 클라이언트 애플리케이션을 사용하여 객체를 추가하고 선택적으로 객체별 보존 기간을 설정합니다.
+
** 보존 모드.  그리드 관리자가 허용하는 경우 거버넌스 또는 규정 준수.
** 보관 기간: 그리드 관리자가 설정한 최대 보관 기간보다 짧거나 같아야 합니다.




--




== S3 객체 잠금이 활성화된 버킷에 대한 요구 사항

* StorageGRID 시스템에 대해 글로벌 S3 개체 잠금 설정이 활성화된 경우 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 S3 개체 잠금이 활성화된 버킷을 생성할 수 있습니다.
* S3 객체 잠금을 사용하려면 버킷을 생성할 때 S3 객체 잠금을 활성화해야 합니다.  기존 버킷에 대해 S3 개체 잠금을 활성화할 수 없습니다.
* 버킷에 대해 S3 객체 잠금이 활성화되면 StorageGRID 자동으로 해당 버킷에 대한 버전 관리를 활성화합니다.  버킷에 대한 S3 객체 잠금을 비활성화하거나 버전 관리를 일시 중단할 수 없습니다.
* 선택적으로 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 각 버킷에 대한 기본 보존 모드와 보존 기간을 지정할 수 있습니다.  버킷의 기본 보존 설정은 자체 보존 설정이 없는 버킷에 추가된 새 객체에만 적용됩니다.  업로드 시 각 객체 버전에 대한 보존 모드와 보존 기간을 지정하여 이러한 기본 설정을 재정의할 수 있습니다.
* 버킷 수명 주기 구성은 S3 객체 잠금이 활성화된 버킷에 대해 지원됩니다.
* S3 개체 잠금이 활성화된 버킷에서는 CloudMirror 복제가 지원되지 않습니다.




== S3 객체 잠금이 활성화된 버킷의 객체에 대한 요구 사항

* 개체 버전을 보호하려면 버킷에 대한 기본 보존 설정을 지정하거나 각 개체 버전에 대한 보존 설정을 지정할 수 있습니다.  객체 수준 보존 설정은 S3 클라이언트 애플리케이션이나 S3 REST API를 사용하여 지정할 수 있습니다.
* 보존 설정은 개별 개체 버전에 적용됩니다.  객체 버전에는 보관 마감일과 법적 보존 설정이 모두 있을 수 있으며, 둘 중 하나만 있을 수도 있고, 둘 다 없을 수도 있습니다.  객체에 대해 보관 기한 또는 법적 보존 설정을 지정하면 요청에 지정된 버전만 보호됩니다.  이전 버전의 개체는 잠긴 상태로 유지되는 동안 해당 개체의 새 버전을 만들 수 있습니다.




== S3 객체 잠금이 활성화된 버킷의 객체 수명 주기

S3 객체 잠금이 활성화된 버킷에 저장된 각 객체는 다음 단계를 거칩니다.

. *객체 수집*
+
S3 객체 잠금이 활성화된 버킷에 객체 버전이 추가되면 보존 설정이 다음과 같이 적용됩니다.

+
** 개체에 대한 보존 설정이 지정된 경우 개체 수준 설정이 적용됩니다.  모든 기본 버킷 설정은 무시됩니다.
** 개체에 대한 보존 설정이 지정되지 않은 경우 기본 버킷 설정이 적용됩니다(있는 경우).
** 객체 또는 버킷에 대한 보존 설정이 지정되지 않으면 해당 객체는 S3 객체 잠금으로 보호되지 않습니다.


+
보존 설정이 적용되면 개체와 S3 사용자 정의 메타데이터가 모두 보호됩니다.

. *객체 보존 및 삭제*
+
StorageGRID 는 각 보호된 개체의 여러 사본을 지정된 보존 기간 동안 저장합니다.  개체 복사본의 정확한 수와 유형, 저장 위치는 활성 ILM 정책의 규정에 따라 결정됩니다.  보호된 객체를 보관 기한에 도달하기 전에 삭제할 수 있는지 여부는 해당 보관 모드에 따라 달라집니다.

+
** 객체가 법적 보존 상태에 있는 경우, 보존 모드에 관계없이 누구도 객체를 삭제할 수 없습니다.






== 기존 규정 준수 버킷을 계속 관리할 수 있나요?

S3 객체 잠금 기능은 이전 StorageGRID 버전에서 사용 가능했던 규정 준수 기능을 대체합니다.  이전 버전의 StorageGRID 사용하여 규격에 맞는 버킷을 만든 경우 해당 버킷의 설정을 계속 관리할 수 있습니다. 그러나 더 이상 새로운 규격에 맞는 버킷을 만들 수 없습니다. 지침은 다음을 참조하세요.https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp 지식 기반: StorageGRID 11.5에서 레거시 호환 버킷을 관리하는 방법"^] .
