---
permalink: tenant/using-storagegrid-tenant-account.html 
sidebar: sidebar 
keywords: how to use tenant account 
summary: '테넌트 계정을 사용하면 Simple Storage Service (S3) REST API를 사용하여 StorageGRID 시스템에 객체를 저장하고 검색할 수 있습니다.' 
---
= StorageGRID 테넌트 계정 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 계정을 사용하면 S3(Simple Storage Service) REST API를 사용하여 StorageGRID 시스템에 객체를 저장하고 검색할 수 있습니다.

각 테넌트 계정에는 자체 페더레이션 또는 로컬 그룹, 사용자, S3 버킷 및 개체가 있습니다.


TIP: 이 버전의 문서 사이트에서는 Swift 세부 정보가 제거되었습니다. 보다 https://docs.netapp.com/us-en/storagegrid-118/tenant/using-storagegrid-tenant-account.html["StorageGRID 11.8: StorageGRID 테넌트 계정 사용"^] .

선택적으로 테넌트 계정을 사용하여 저장된 객체를 여러 엔터티별로 분리할 수 있습니다.  예를 들어, 다음 두 가지 사용 사례에 여러 테넌트 계정을 사용할 수 있습니다.

* *기업 사용 사례:* StorageGRID 시스템이 기업 내에서 사용되는 경우, 그리드의 개체 스토리지는 조직 내 여러 부서별로 분리될 수 있습니다.  예를 들어, 마케팅 부서, 고객 지원 부서, 인사부 등에 대한 테넌트 계정이 있을 수 있습니다.
+

NOTE: S3 클라이언트 프로토콜을 사용하면 S3 버킷과 버킷 정책을 사용하여 기업 내 부서 간에 객체를 분리할 수도 있습니다. 별도의 테넌트 계정을 만들 필요가 없습니다. 구현에 대한 지침을 참조하세요.link:../s3/bucket-and-group-access-policies.html["S3 버킷 및 버킷 정책"] 자세한 내용은.

* *서비스 제공자 사용 사례:* StorageGRID 시스템이 서비스 제공자에 의해 사용되는 경우, 그리드의 개체 스토리지는 스토리지를 임대하는 여러 엔터티에 의해 분리될 수 있습니다.  예를 들어, 회사 A, 회사 B, 회사 C 등의 세입자 계정이 있을 수 있습니다.




== 테넌트 계정 생성

테넌트 계정은 StorageGRID 그리드 관리자가 Grid Manager를 사용하여 생성합니다.  테넌트 계정을 생성할 때 그리드 관리자는 다음 정보를 지정합니다.

* 테넌트의 표시 이름(테넌트의 계정 ID는 자동으로 할당되며 변경할 수 없습니다).
* 테넌트 계정에서 S3 또는 Swift 프로토콜을 사용할지 여부.
* S3 테넌트 계정의 경우: 테넌트 계정에서 플랫폼 서비스를 사용할 수 있는지 여부입니다.  플랫폼 서비스 사용이 허용되는 경우, 그리드는 해당 사용을 지원하도록 구성되어야 합니다.
* 선택적으로 테넌트 계정에 대한 저장 할당량(테넌트 개체에 사용할 수 있는 최대 기가바이트, 테라바이트 또는 페타바이트 수)을 지정할 수 있습니다.  테넌트의 저장 할당량은 디스크 크기(물리적 양)가 아닌 논리적 양(개체 크기)을 나타냅니다.
* StorageGRID 시스템에 ID 페더레이션이 활성화된 경우, 어떤 페더레이션 그룹이 테넌트 계정을 구성할 수 있는 루트 액세스 권한을 가지고 있습니까?
* StorageGRID 시스템에서 SSO(Single Sign-On)를 사용하지 않는 경우 테넌트 계정이 자체 ID 소스를 사용할지 아니면 그리드의 ID 소스를 공유할지, 그리고 테넌트의 로컬 루트 사용자에 대한 초기 비밀번호입니다.


또한, S3 테넌트 계정이 규정 요구 사항을 준수해야 하는 경우 그리드 관리자는 StorageGRID 시스템에 대해 S3 개체 잠금 설정을 활성화할 수 있습니다.  S3 개체 잠금이 활성화되면 모든 S3 테넌트 계정에서 규정을 준수하는 버킷을 만들고 관리할 수 있습니다.



== S3 테넌트 구성

S3 테넌트 계정이 생성된 후 테넌트 관리자에 액세스하여 다음과 같은 작업을 수행할 수 있습니다.

* ID 페더레이션 설정(ID 소스가 그리드와 공유되지 않는 경우) 또는 로컬 그룹 및 사용자 생성
* S3 액세스 키 관리
* 규정 준수 버킷을 포함한 S3 버킷 생성 및 관리
* 플랫폼 서비스 사용(활성화된 경우)
* 저장 공간 사용량 모니터링



TIP: 테넌트 관리자를 사용하여 S3 버킷을 만들고 관리할 수 있지만, 객체를 수집하고 관리하려면 S3 액세스 키가 있어야 하며 S3 REST API를 사용해야 합니다.

.관련 정보
* link:../admin/index.html["StorageGRID 관리"]
* link:../s3/index.html["S3 REST API 사용"]

