---
permalink: tenant/viewing-s3-bucket-details.html 
sidebar: sidebar 
keywords: how to view bucket details 
summary: 테넌트 계정에서 버킷을 볼 수 있습니다. 
---
= 버킷 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 계정에서 버킷을 볼 수 있습니다.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 다음 사용자 그룹에 속해 있습니다.link:tenant-management-permissions.html["루트 액세스, 모든 버킷 관리 또는 모든 버킷 보기 권한"] .  이러한 권한은 그룹 또는 버킷 정책의 권한 설정을 재정의합니다.


.단계
. 대시보드에서 *버킷 보기*를 선택하거나 *스토리지(S3)* > *버킷*을 선택하세요.
+
버킷 페이지가 나타납니다.

. 각 버킷에 대한 요약 표를 검토하세요.
+
필요에 따라 정보를 열별로 정렬할 수도 있고, 목록을 앞뒤로 넘길 수도 있습니다.

+

NOTE: 표시된 개체 수, 사용된 공간, 사용량 값은 추정치입니다. 이러한 추정치는 수집 타이밍, 네트워크 연결, 노드 상태의 영향을 받습니다.  버킷에 버전 관리가 활성화된 경우 삭제된 개체 버전이 개체 수에 포함됩니다.

+
이름:: 변경할 수 없는 버킷의 고유한 이름입니다.
활성화된 기능:: 버킷에 대해 활성화된 기능 목록입니다.
S3 객체 잠금:: 버킷에 대해 S3 객체 잠금이 활성화되어 있는지 여부입니다.
+
--
이 열은 그리드에 대해 S3 개체 잠금이 활성화된 경우에만 나타납니다.  이 열에는 기존 규정 준수 버킷에 대한 정보도 표시됩니다.

--
지역:: 변경할 수 없는 버킷의 지역입니다.  이 열은 기본적으로 숨겨져 있습니다.
객체 개수:: 이 버킷에 있는 객체의 수입니다.  버킷에 버전 관리가 활성화된 경우 이 값에는 최신이 아닌 개체 버전이 포함됩니다.
+
--
객체가 추가되거나 삭제되면 이 값이 즉시 업데이트되지 않을 수 있습니다.

--
사용된 공간:: 버킷에 있는 모든 객체의 논리적 크기입니다.  논리적 크기에는 복제 또는 삭제 코딩된 사본이나 개체 메타데이터에 필요한 실제 공간이 포함되지 않습니다.
+
--
이 값을 업데이트하는 데 최대 10분이 걸릴 수 있습니다.

--
용법:: 버킷의 용량 한도가 설정된 경우, 해당 한도의 사용된 백분율입니다.
+
--
사용 가치는 내부 추정에 따른 것이며, 어떤 경우에는 초과될 수 있습니다.  예를 들어, StorageGRID 테넌트가 객체 업로드를 시작할 때 용량 제한(설정된 경우)을 확인하고 테넌트가 용량 제한을 초과한 경우 이 버킷에 대한 새로운 수집을 거부합니다.  그러나 StorageGRID 용량 제한을 초과했는지 판단할 때 현재 업로드 크기를 고려하지 않습니다.  객체가 삭제되면 테넌트가 용량 제한 사용량이 다시 계산될 때까지 이 버킷에 새 객체를 업로드하지 못할 수 있습니다.  계산에는 10분 이상 걸릴 수 있습니다.

이 값은 객체와 해당 메타데이터를 저장하는 데 필요한 물리적 크기가 아니라 논리적 크기를 나타냅니다.

--
용량:: 설정된 경우 버킷의 용량 제한입니다.
생성 날짜:: 버킷이 생성된 날짜와 시간입니다.  이 열은 기본적으로 숨겨져 있습니다.


. 특정 버킷에 대한 세부 정보를 보려면 표에서 버킷 이름을 선택하세요.
+
.. 웹 페이지 상단의 요약 정보를 보고 지역 및 개체 수 등 버킷의 세부 정보를 확인하세요.
.. 용량 제한 사용 막대를 확인하세요.  사용량이 100%이거나 100%에 가까운 경우 한도를 늘리거나 일부 객체를 삭제하는 것을 고려하세요.
.. 필요에 따라 *버킷에서 개체 삭제* 및 *버킷 삭제*를 선택합니다.
+
[CAUTION]
====
각 옵션을 선택할 때 나타나는 주의 사항에 주의하세요. 자세한 내용은 다음을 참조하세요.

*** link:deleting-s3-bucket-objects.html["버킷의 모든 객체 삭제"]
*** link:deleting-s3-bucket.html["버킷 삭제"](버킷은 비어 있어야 합니다)


====
.. 필요에 따라 각 탭에서 버킷의 설정을 보거나 변경합니다.
+
*** *S3 콘솔*: 버킷의 객체를 확인합니다. 자세한 내용은 다음을 참조하세요. link:use-s3-console.html["S3 콘솔 사용"] .
*** *버킷 옵션*: 옵션 설정을 보거나 변경합니다.  S3 객체 잠금과 같은 일부 설정은 버킷이 생성된 후에는 변경할 수 없습니다.
+
**** link:manage-bucket-consistency.html["버킷 일관성 관리"]
**** link:enabling-or-disabling-last-access-time-updates.html["마지막 액세스 시간 업데이트"]
**** link:../tenant/creating-s3-bucket.html#capacity-limit["용량 제한"]
**** link:changing-bucket-versioning.html["객체 버전 관리"]
**** link:using-s3-object-lock.html["S3 객체 잠금"]
**** link:update-default-retention-settings.html["기본 버킷 보존"]
**** link:grid-federation-manage-cross-grid-replication.html["그리드 간 복제 관리"](임차인에게 허용된 경우)


*** *플랫폼 서비스*:link:considerations-for-platform-services.html["플랫폼 서비스 관리"] (임차인에게 허용된 경우)
*** *버킷 접근*: 옵션 설정을 보거나 변경합니다.  특정 접근 권한이 있어야 합니다.
+
**** 구성link:configuring-cross-origin-resource-sharing-cors.html["교차 출처 리소스 공유(CORS)"] 따라서 버킷과 버킷 내의 객체는 다른 도메인의 웹 애플리케이션에서 접근할 수 있습니다.
**** link:../tenant/manage-bucket-policy.html["사용자 액세스 제어"]S3 버킷과 해당 버킷의 객체에 대한 정보입니다.







