---
permalink: tenant/viewing-your-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view your s3 access key 
summary: S3 테넌트를 사용 중이고 적절한 권한이 있는 경우 S3 액세스 키 목록을 볼 수 있습니다.  만료 시간별로 목록을 정렬하면 곧 만료되는 키를 파악할 수 있습니다.  필요에 따라 새로운 키를 만들거나 더 이상 사용하지 않는 키를 삭제할 수 있습니다. 
---
= S3 액세스 키 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 테넌트를 사용하고 있는 경우link:tenant-management-permissions.html["적절한 허가"] , S3 액세스 키 목록을 볼 수 있습니다.  만료 시간별로 목록을 정렬하면 곧 만료되는 키를 파악할 수 있습니다.  필요에 따라 다음을 수행할 수 있습니다.link:creating-your-own-s3-access-keys.html["새로운 키 생성"] 또는link:deleting-your-own-s3-access-keys.html["삭제 키"] 더 이상 사용하지 않는 것.


CAUTION: 귀하의 계정에 속한 S3 버킷과 객체는 테넌트 관리자에서 귀하의 계정에 표시된 액세스 키 ID와 비밀 액세스 키를 사용하여 액세스할 수 있습니다.  이러한 이유로 액세스 키를 비밀번호처럼 보호하세요.  정기적으로 액세스 키를 교체하고, 계정에서 사용하지 않는 키를 제거하고, 다른 사용자와 공유하지 마세요.

.시작하기 전에
* 귀하는 다음을 사용하여 테넌트 관리자에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 귀하는 Manage your own S3 자격 증명을 가진 사용자 그룹에 속합니다.link:tenant-management-permissions.html["허가"] .


.단계
. *저장소(S3)* > *내 액세스 키*를 선택하세요.
. 내 액세스 키 페이지에서 기존 액세스 키를 *만료 시간* 또는 *액세스 키 ID*별로 정렬합니다.
. 필요에 따라 새로운 키를 만들거나 더 이상 사용하지 않는 키를 삭제하세요.
+
기존 키가 만료되기 전에 새 키를 생성하면 계정의 개체에 대한 액세스 권한을 일시적으로 잃지 않고 새 키를 사용할 수 있습니다.

+
만료된 키는 자동으로 제거됩니다.


