---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords: how to automate installation 
summary: VMware OVF 도구를 사용하면 그리드 노드 배포를 자동화할 수 있습니다.  StorageGRID 의 구성을 자동화할 수도 있습니다. 
---
= 설치 자동화(VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware OVF 도구를 사용하면 그리드 노드 배포를 자동화할 수 있습니다.  StorageGRID 의 구성을 자동화할 수도 있습니다.



== 그리드 노드 배포 자동화

VMware OVF 도구를 사용하여 그리드 노드 배포를 자동화합니다.

.시작하기 전에
* Bash 3.2 이상이 설치된 Linux/Unix 시스템을 사용할 수 있습니다.
* vCenter를 사용하는 VMware vSphere가 있습니다.
* VMware OVF Tool 4.1이 설치되고 올바르게 구성되었습니다.
* OVF 도구를 사용하여 VMware vSphere에 액세스하기 위한 사용자 이름과 비밀번호를 알고 있습니다.
* OVF 파일에서 VM을 배포하고 전원을 켤 수 있는 충분한 권한이 있으며, VM에 연결할 추가 볼륨을 생성할 수 있는 권한이 있습니다.  를 참조하십시오 `ovftool` 자세한 내용은 문서를 참조하세요.
* StorageGRID 가상 머신을 배포하려는 vSphere의 위치에 대한 가상 인프라(VI) URL을 알고 있습니다.  이 URL은 일반적으로 vApp 또는 리소스 풀입니다. 예:  `vi://vcenter.example.com/vi/sgws`
+

NOTE: VMware를 사용할 수 있습니다 `ovftool` 이 값을 결정하는 유틸리티(참조 `ovftool` (자세한 내용은 문서를 참조하세요).

+

NOTE: vApp에 배포하는 경우 가상 머신은 처음에는 자동으로 시작되지 않으므로 수동으로 전원을 켜야 합니다.

* 배포 구성 파일에 필요한 모든 정보를 수집했습니다.  보다link:collecting-information-about-your-deployment-environment.html["배포 환경에 대한 정보 수집"] 정보를 위해.
* StorageGRID 의 VMware 설치 아카이브에서 다음 파일에 액세스할 수 있습니다.


[cols="1a,1a"]
|===
| 파일 이름 | 설명 


| NetApp-SG-버전-SHA.vmdk  a| 
그리드 노드 가상 머신을 생성하기 위한 템플릿으로 사용되는 가상 머신 디스크 파일입니다.

*참고:* 이 파일은 다음 폴더와 같은 폴더에 있어야 합니다. `.ovf` 그리고 `.mf` 파일.



| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
Open Virtualization Format 템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 기본 관리 노드를 배포하기 위한 것입니다.



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 기본이 아닌 관리 노드를 배포하기 위한 것입니다.



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 게이트웨이 노드를 배포하기 위한 것입니다.



| vsphere-storage.ovf vsphere-storage.mf  a| 
템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 가상 머신 기반 스토리지 노드를 배포하기 위한 것입니다.



| 배포-vsphere-ovftool.sh  a| 
가상 그리드 노드의 배포를 자동화하는 데 사용되는 Bash 셸 스크립트입니다.



| 배포-vsphere-ovftool-sample.ini  a| 
다음과 함께 사용할 수 있는 예제 구성 파일 `deploy-vsphere-ovftool.sh` 스크립트.

|===


=== 배포에 대한 구성 파일을 정의하세요

StorageGRID 에 대한 가상 그리드 노드를 배포하는 데 필요한 정보는 구성 파일에서 지정됩니다. `deploy-vsphere-ovftool.sh` 배시 스크립트.  예제 구성 파일을 수정하면 파일을 처음부터 만들 필요가 없습니다.

.단계
. 예제 구성 파일의 사본을 만듭니다.(`deploy-vsphere-ovftool.sample.ini` ).  새 파일을 다음과 같이 저장합니다. `deploy-vsphere-ovftool.ini` 같은 디렉토리에 `deploy-vsphere-ovftool.sh` .
. 열려 있는 `deploy-vsphere-ovftool.ini` .
. VMware 가상 그리드 노드를 배포하는 데 필요한 모든 정보를 입력하세요.
+
보다<<configuration-file-settings,구성 파일 설정>> 정보를 위해.

. 필요한 정보를 모두 입력하고 확인한 후 파일을 저장하고 닫습니다.




=== 구성 파일 설정

그만큼 `deploy-vsphere-ovftool.ini` 구성 파일에는 가상 그리드 노드를 배포하는 데 필요한 설정이 포함되어 있습니다.

구성 파일은 먼저 글로벌 매개변수를 나열한 다음, 노드 이름으로 정의된 섹션에 노드별 매개변수를 나열합니다.  파일이 사용되는 경우:

* _전역 매개변수_는 모든 그리드 노드에 적용됩니다.
* _노드별 매개변수_는 전역 매개변수를 재정의합니다.




==== 글로벌 매개변수

개별 섹션의 설정으로 재정의되지 않는 한, 글로벌 매개변수는 모든 그리드 노드에 적용됩니다.  여러 노드에 적용되는 매개변수를 글로벌 매개변수 섹션에 넣은 다음, 필요에 따라 개별 노드 섹션에서 이러한 설정을 재정의합니다.

* *OVFTOOL_ARGUMENTS*: OVFTOOL_ARGUMENTS를 글로벌 설정으로 지정하거나 특정 노드에 개별적으로 인수를 적용할 수 있습니다. 예를 들어:
+
[listing, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=eagerZeroedThick --datastore='_datastore_name_'
----
+
당신은 사용할 수 있습니다 `--powerOffTarget` 그리고 `--overwrite` 기존 가상 머신을 종료하고 교체하는 옵션입니다.

+

CAUTION: 전역적으로 지정하는 대신, 각 노드에 대해 OVFTOOL_ARGUMENTS를 지정하고 다른 데이터 저장소에 노드를 배포해야 합니다.

* *출처*: StorageGRID 가상 머신 템플릿 경로(`.vmdk` ) 파일 및 `.ovf` 그리고 `.mf` 개별 그리드 노드에 대한 파일입니다.  기본적으로 현재 디렉토리로 설정됩니다.
+
[listing, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* *대상*: StorageGRID 배포될 위치에 대한 VMware vSphere 가상 인프라(vi) URL입니다. 예를 들어:
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* *GRID_NETWORK_CONFIG*: IP 주소를 얻는 데 사용되는 방법으로 STATIC 또는 DHCP가 있습니다.  기본값은 STATIC입니다.  모든 노드 또는 대부분의 노드가 IP 주소를 얻기 위해 동일한 방법을 사용하는 경우, 여기에서 해당 방법을 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
GRID_NETWORK_CONFIG = STATIC
----
* *GRID_NETWORK_TARGET*: Grid Network에 사용할 기존 VMware 네트워크의 이름입니다.  모든 노드 또는 대부분의 노드가 동일한 네트워크 이름을 사용하는 경우 여기에 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
GRID_NETWORK_TARGET = SG Admin Network
----
* *GRID_NETWORK_MASK*: 그리드 네트워크의 네트워크 마스크입니다.  모든 노드 또는 대부분의 노드가 동일한 네트워크 마스크를 사용하는 경우 여기에서 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* *GRID_NETWORK_GATEWAY*: Grid Network의 네트워크 게이트웨이입니다.  모든 노드 또는 대부분의 노드가 동일한 네트워크 게이트웨이를 사용하는 경우 여기에서 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* *GRID_NETWORK_MTU*: 선택 사항.  그리드 네트워크의 최대 전송 단위(MTU)입니다.  지정된 경우 값은 1280~9216 사이여야 합니다. 예를 들어:
+
[listing]
----
GRID_NETWORK_MTU = 9000
----
+
생략하면 1400이 사용됩니다.

+
점보 프레임을 사용하려면 MTU를 점보 프레임에 적합한 값(예: 9000)으로 설정하세요.  그렇지 않으면 기본값을 유지합니다.

+

NOTE: 네트워크의 MTU 값은 노드가 연결된 vSphere의 가상 스위치 포트에 구성된 값과 일치해야 합니다.  그렇지 않으면 네트워크 성능 문제나 패킷 손실이 발생할 수 있습니다.

+

NOTE: 최상의 네트워크 성능을 위해서는 모든 노드가 해당 그리드 네트워크 인터페이스에서 유사한 MTU 값으로 구성되어야 합니다.  *그리드 네트워크 MTU 불일치* 경고는 개별 노드의 그리드 네트워크에 대한 MTU 설정에 상당한 차이가 있는 경우 발생합니다.  MTU 값은 모든 네트워크 유형에서 동일할 필요는 없습니다.

* *ADMIN_NETWORK_CONFIG*: IP 주소를 얻는 데 사용되는 방법으로 DISABLED, STATIC 또는 DHCP가 있습니다.  기본값은 DISABLED입니다.  모든 노드 또는 대부분의 노드가 IP 주소를 얻기 위해 동일한 방법을 사용하는 경우, 여기에서 해당 방법을 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* *ADMIN_NETWORK_TARGET*: 관리 네트워크에 사용할 기존 VMware 네트워크의 이름입니다.  관리 네트워크가 비활성화되어 있지 않은 경우 이 설정은 필수입니다.  모든 노드 또는 대부분의 노드가 동일한 네트워크 이름을 사용하는 경우 여기에 지정할 수 있습니다.  그리드 네트워크와 달리 모든 노드가 동일한 관리 네트워크에 연결될 필요는 없습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
ADMIN_NETWORK_TARGET = SG Admin Network
----
* *ADMIN_NETWORK_MASK*: 관리 네트워크의 네트워크 마스크입니다.  고정 IP 주소를 사용하는 경우 이 설정이 필요합니다.  모든 노드 또는 대부분의 노드가 동일한 네트워크 마스크를 사용하는 경우 여기에서 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* *ADMIN_NETWORK_GATEWAY*: 관리 네트워크의 네트워크 게이트웨이입니다.  정적 IP 주소를 사용하고 ADMIN_NETWORK_ESL 설정에서 외부 서브넷을 지정하는 경우 이 설정이 필요합니다.  (즉, ADMIN_NETWORK_ESL이 비어 있는 경우에는 필요하지 않습니다.)  모든 노드 또는 대부분의 노드가 동일한 네트워크 게이트웨이를 사용하는 경우 여기에서 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* *ADMIN_NETWORK_ESL*: CIDR 경로 대상의 쉼표로 구분된 목록으로 지정된 관리 네트워크의 외부 서브넷 목록(경로)입니다.  모든 노드 또는 대부분의 노드가 동일한 외부 서브넷 목록을 사용하는 경우 여기에서 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* *ADMIN_NETWORK_MTU*: 선택 사항.  관리 네트워크의 최대 전송 단위(MTU)입니다.  ADMIN_NETWORK_CONFIG = DHCP인 경우 지정하지 마세요.  지정된 경우 값은 1280~9216 사이여야 합니다.  생략하면 1400이 사용됩니다.  점보 프레임을 사용하려면 MTU를 점보 프레임에 적합한 값(예: 9000)으로 설정하세요.  그렇지 않으면 기본값을 유지합니다.  모든 노드 또는 대부분의 노드가 관리 네트워크에 동일한 MTU를 사용하는 경우 여기에서 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* *CLIENT_NETWORK_CONFIG*: IP 주소를 얻는 데 사용되는 방법으로 DISABLED, STATIC 또는 DHCP가 있습니다.  기본값은 DISABLED입니다.  모든 노드 또는 대부분의 노드가 IP 주소를 얻기 위해 동일한 방법을 사용하는 경우, 여기에서 해당 방법을 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* *CLIENT_NETWORK_TARGET*: 클라이언트 네트워크에 사용할 기존 VMware 네트워크의 이름입니다.  클라이언트 네트워크가 비활성화되어 있지 않은 경우 이 설정은 필수입니다.  모든 노드 또는 대부분의 노드가 동일한 네트워크 이름을 사용하는 경우 여기에 지정할 수 있습니다.  그리드 네트워크와 달리 모든 노드가 동일한 클라이언트 네트워크에 연결될 필요는 없습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
CLIENT_NETWORK_TARGET = SG Client Network
----
* *CLIENT_NETWORK_MASK*: 클라이언트 네트워크의 네트워크 마스크입니다.  고정 IP 주소를 사용하는 경우 이 설정이 필요합니다.  모든 노드 또는 대부분의 노드가 동일한 네트워크 마스크를 사용하는 경우 여기에서 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* *CLIENT_NETWORK_GATEWAY*: 클라이언트 네트워크의 네트워크 게이트웨이입니다.  고정 IP 주소를 사용하는 경우 이 설정이 필요합니다.  모든 노드 또는 대부분의 노드가 동일한 네트워크 게이트웨이를 사용하는 경우 여기에서 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* *CLIENT_NETWORK_MTU*: 선택 사항.  클라이언트 네트워크의 최대 전송 단위(MTU)입니다.  CLIENT_NETWORK_CONFIG = DHCP인 경우 지정하지 마세요.  지정된 경우 값은 1280~9216 사이여야 합니다.  생략하면 1400이 사용됩니다.  점보 프레임을 사용하려면 MTU를 점보 프레임에 적합한 값(예: 9000)으로 설정하세요.  그렇지 않으면 기본값을 유지합니다.  모든 노드 또는 대부분의 노드가 클라이언트 네트워크에 동일한 MTU를 사용하는 경우 여기에서 지정할 수 있습니다.  그런 다음 하나 이상의 개별 노드에 대해 다른 설정을 지정하여 글로벌 설정을 재정의할 수 있습니다. 예를 들어:
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* *PORT_REMAP*: 노드에서 내부 그리드 노드 통신이나 외부 통신에 사용하는 모든 포트를 다시 매핑합니다.  StorageGRID 에서 사용하는 하나 이상의 포트가 엔터프라이즈 네트워킹 정책에 의해 제한되는 경우 포트를 다시 매핑해야 합니다.  StorageGRID 에서 사용하는 포트 목록은 내부 그리드 노드 통신 및 외부 통신을 참조하세요.link:../network/index.html["네트워킹 가이드라인"] .
+

NOTE: 로드 밸런서 엔드포인트를 구성하는 데 사용할 포트를 다시 매핑하지 마세요.

+

NOTE: PORT_REMAP만 설정된 경우, 지정한 매핑은 인바운드 및 아웃바운드 통신 모두에 사용됩니다.  PORT_REMAP_INBOUND도 지정된 경우 PORT_REMAP은 아웃바운드 통신에만 적용됩니다.

+
사용된 형식은 다음과 같습니다. `_network type/protocol/default port used by grid node/new port_` 여기서 네트워크 유형은 Grid, Admin 또는 Client이고, 프로토콜은 TCP 또는 UDP입니다.

+
예를 들어:

+
[listing]
----
PORT_REMAP = client/tcp/18082/443
----
+
이 예제 설정을 단독으로 사용하면 그리드 노드의 인바운드 및 아웃바운드 통신이 포트 18082에서 포트 443으로 대칭적으로 매핑됩니다.  PORT_REMAP_INBOUND와 함께 사용하면 이 예제 설정은 포트 18082에서 포트 443으로 아웃바운드 통신을 매핑합니다.

+
쉼표로 구분된 목록을 사용하여 여러 포트를 다시 매핑할 수도 있습니다.

+
예를 들어:

+
[listing]
----
PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80
----
* *PORT_REMAP_INBOUND*: 지정된 포트에 대한 인바운드 통신을 다시 매핑합니다.  PORT_REMAP_INBOUND를 지정했지만 PORT_REMAP에 대한 값을 지정하지 않으면 해당 포트의 아웃바운드 통신은 변경되지 않습니다.
+

NOTE: 로드 밸런서 엔드포인트를 구성하는 데 사용할 포트를 다시 매핑하지 마세요.

+
사용된 형식은 다음과 같습니다. `_network type_/_protocol/_default port used by grid node_/_new port_` 여기서 네트워크 유형은 Grid, Admin 또는 Client이고, 프로토콜은 TCP 또는 UDP입니다.

+
예를 들어:

+
[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
+
이 예제에서는 포트 443으로 전송된 트래픽을 내부 방화벽을 통과하여 그리드 노드가 S3 요청을 수신하는 포트 18082로 전달합니다.

+
쉼표로 구분된 목록을 사용하여 여러 개의 인바운드 포트를 다시 매핑할 수도 있습니다.

+
예를 들어:

+
[listing]
----
PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22
----
* *TEMPORARY_PASSWORD_TYPE*: 노드가 그리드에 가입하기 전에 VM 콘솔이나 StorageGRID 설치 API에 액세스하거나 SSH를 사용할 때 사용할 임시 설치 암호 유형입니다.
+

TIP: 모든 노드 또는 대부분의 노드가 동일한 유형의 임시 설치 암호를 사용하는 경우 글로벌 매개변수 섹션에서 유형을 지정합니다.  그런 다음, 선택적으로 개별 노드에 대해 다른 설정을 사용합니다.  예를 들어, *사용자 지정 비밀번호 사용*을 전역적으로 선택하면 *CUSTOM_TEMPORARY_PASSWORD=<비밀번호>*를 사용하여 각 노드에 대한 비밀번호를 설정할 수 있습니다.

+
*TEMPORARY_PASSWORD_TYPE*은 다음 중 하나일 수 있습니다.

+
** *노드 이름 사용*: 노드 이름은 임시 설치 비밀번호로 사용되며 VM 콘솔, StorageGRID 설치 API 및 SSH에 대한 액세스를 제공합니다.
** *비밀번호 비활성화*: 임시 설치 비밀번호가 사용되지 않습니다.  설치 문제를 디버깅하기 위해 VM에 액세스해야 하는 경우 다음을 참조하세요.link:troubleshooting-installation-issues.html["설치 문제 해결"] .
** *사용자 지정 비밀번호 사용*: *CUSTOM_TEMPORARY_PASSWORD=<password>*로 제공된 값은 임시 설치 비밀번호로 사용되며 VM 콘솔, StorageGRID 설치 API 및 SSH에 대한 액세스를 제공합니다.
+

TIP: 선택적으로 *TEMPORARY_PASSWORD_TYPE* 매개변수를 생략하고 *CUSTOM_TEMPORARY_PASSWORD=<password>*만 지정할 수 있습니다.



* *CUSTOM_TEMPORARY_PASSWORD=<비밀번호>* 선택 사항.  VM 콘솔, StorageGRID 설치 API 및 SSH에 액세스할 때 설치하는 동안 사용할 임시 비밀번호입니다.  *TEMPORARY_PASSWORD_TYPE*이 *노드 이름 사용* 또는 *비밀번호 비활성화*로 설정된 경우 무시됩니다.




==== 노드별 매개변수

각 노드는 구성 파일의 자체 섹션에 있습니다.  각 노드에는 다음 설정이 필요합니다.

* 섹션 헤드는 그리드 관리자에 표시될 노드 이름을 정의합니다.  노드에 대한 선택적 NODE_NAME 매개변수를 지정하여 해당 값을 재정의할 수 있습니다.
* *NODE_TYPE*: VM_Admin_Node, VM_Storage_Node 또는 VM_API_Gateway_Node
* *STORAGE_TYPE*: 결합, 데이터 또는 메타데이터.  저장 노드에 대한 이 선택적 매개변수는 지정되지 않으면 기본적으로 결합(데이터 및 메타데이터)으로 설정됩니다. 자세한 내용은 다음을 참조하세요. link:../primer/what-storage-node-is.html#types-of-storage-nodes["저장 노드 유형"] .
* *GRID_NETWORK_IP*: 그리드 네트워크의 노드에 대한 IP 주소입니다.
* *ADMIN_NETWORK_IP*: 관리 네트워크의 노드에 대한 IP 주소입니다.  노드가 관리 네트워크에 연결되어 있고 ADMIN_NETWORK_CONFIG가 STATIC으로 설정된 경우에만 필요합니다.
* *CLIENT_NETWORK_IP*: 클라이언트 네트워크의 노드에 대한 IP 주소입니다.  노드가 클라이언트 네트워크에 연결되어 있고 이 노드의 CLIENT_NETWORK_CONFIG가 STATIC으로 설정된 경우에만 필요합니다.
* *ADMIN_IP*: 그리드 네트워크의 기본 관리 노드에 대한 IP 주소입니다.  기본 관리 노드의 GRID_NETWORK_IP로 지정한 값을 사용합니다.  이 매개변수를 생략하면 노드는 mDNS를 사용하여 기본 관리 노드 IP를 검색하려고 시도합니다. 자세한 내용은 다음을 참조하세요. link:how-grid-nodes-discover-primary-admin-node.html["그리드 노드가 기본 관리 노드를 검색하는 방법"] .
+

NOTE: 기본 관리 노드의 경우 ADMIN_IP 매개변수는 무시됩니다.

* 전역적으로 설정되지 않은 매개변수.  예를 들어, 노드가 관리 네트워크에 연결되어 있고 ADMIN_NETWORK 매개변수를 전역적으로 지정하지 않은 경우 노드에 대해 해당 매개변수를 지정해야 합니다.


.기본 관리 노드
기본 관리 노드에는 다음과 같은 추가 설정이 필요합니다.

* *노드 유형*: VM_관리자_노드
* *ADMIN_ROLE*: 기본


이 예제 항목은 세 개의 네트워크 모두에 있는 기본 관리 노드에 대한 것입니다.

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node
  TEMPORARY_PASSWORD_TYPE = Use custom password
  CUSTOM_TEMPORARY_PASSWORD = Passw0rd

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
다음 추가 설정은 기본 관리 노드에 대해 선택 사항입니다.

* *디스크*: 기본적으로 관리 노드에는 감사 및 데이터베이스 사용을 위해 200GB 하드 디스크 두 개가 추가로 할당됩니다.  DISK 매개변수를 사용하여 이러한 설정을 늘릴 수 있습니다. 예를 들어:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 관리자 노드의 경우 INSTANCES는 항상 2와 같아야 합니다.

.저장 노드
스토리지 노드에는 다음과 같은 추가 설정이 필요합니다.

* *NODE_TYPE*: VM_Storage_Node
+
이 예제 항목은 그리드 및 관리 네트워크에 있지만 클라이언트 네트워크에는 없는 스토리지 노드에 대한 것입니다.  이 노드는 ADMIN_IP 설정을 사용하여 그리드 네트워크에서 기본 관리 노드의 IP 주소를 지정합니다.

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
두 번째 예제 항목은 고객의 기업 네트워킹 정책에 따라 S3 클라이언트 애플리케이션이 포트 80 또는 443을 사용해서만 스토리지 노드에 액세스할 수 있도록 허용된 클라이언트 네트워크의 스토리지 노드에 대한 것입니다.  예제 구성 파일에서는 PORT_REMAP을 사용하여 스토리지 노드가 포트 443에서 S3 메시지를 보내고 받을 수 있도록 합니다.

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
마지막 예제에서는 포트 22에서 포트 3022로 향하는 ssh 트래픽에 대한 대칭적 리매핑을 생성하지만, 인바운드 및 아웃바운드 트래픽에 대한 값을 명시적으로 설정합니다.

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


스토리지 노드에 대한 추가 설정은 다음과 같습니다.

* *디스크*: 기본적으로 스토리지 노드에는 RangeDB 사용을 위해 4TB 디스크 3개가 할당됩니다.  DISK 매개변수를 사용하여 이러한 설정을 늘릴 수 있습니다. 예를 들어:
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----
* *STORAGE_TYPE*: 기본적으로 모든 새 스토리지 노드는 개체 데이터와 메타데이터를 모두 저장하도록 구성되며, 이를 _결합_ 스토리지 노드라고 합니다.  STORAGE_TYPE 매개변수를 사용하여 스토리지 노드 유형을 데이터나 메타데이터만 저장하도록 변경할 수 있습니다. 예를 들어:
+
[listing]
----
STORAGE_TYPE = data
----


.게이트웨이 노드
게이트웨이 노드에는 다음과 같은 추가 설정이 필요합니다.

* *노드_유형*: VM_API_게이트웨이


이 예제 항목은 세 네트워크 모두의 예제 게이트웨이 노드에 대한 것입니다.  이 예에서 구성 파일의 글로벌 섹션에는 클라이언트 네트워크 매개변수가 지정되지 않았으므로 노드에 대해 지정해야 합니다.

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG Client Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----
.기본이 아닌 관리 노드
기본이 아닌 관리 노드에는 다음과 같은 추가 설정이 필요합니다.

* *노드 유형*: VM_관리자_노드
* *ADMIN_ROLE*: 기본이 아님


이 예제 항목은 클라이언트 네트워크에 없는 기본이 아닌 관리 노드에 대한 것입니다.

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG Grid Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
다음 추가 설정은 기본이 아닌 관리 노드의 경우 선택 사항입니다.

* *디스크*: 기본적으로 관리 노드에는 감사 및 데이터베이스 사용을 위해 200GB 하드 디스크 두 개가 추가로 할당됩니다.  DISK 매개변수를 사용하여 이러한 설정을 늘릴 수 있습니다. 예를 들어:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: 관리자 노드의 경우 INSTANCES는 항상 2와 같아야 합니다.



== Bash 스크립트 실행

당신은 사용할 수 있습니다 `deploy-vsphere-ovftool.sh` VMware vSphere에서 StorageGRID 노드의 배포를 자동화하기 위해 수정한 Bash 스크립트와 deploy-vsphere-ovftool.ini 구성 파일입니다.

.시작하기 전에
사용자 환경에 맞게 deploy-vsphere-ovftool.ini 구성 파일을 생성했습니다.

Bash 스크립트에서 제공되는 도움말을 사용하려면 help 명령을 입력하세요.(`-h/--help` ). 예를 들어:

[listing]
----
./deploy-vsphere-ovftool.sh -h
----
또는

[listing]
----
./deploy-vsphere-ovftool.sh --help
----
.단계
. Bash 스크립트를 실행하기 위해 사용하는 Linux 머신에 로그인합니다.
. 설치 아카이브를 추출한 디렉토리로 변경합니다.
+
예를 들어:

+
[listing]
----
cd StorageGRID-Webscale-version/vsphere
----
. 모든 그리드 노드를 배포하려면 환경에 적합한 옵션을 사용하여 Bash 스크립트를 실행하세요.
+
예를 들어:

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd ./deploy-vsphere-ovftool.ini
----
. 오류로 인해 그리드 노드가 배포에 실패한 경우 오류를 해결하고 해당 노드에 대해서만 Bash 스크립트를 다시 실행합니다.
+
예를 들어:

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd --single-node="DC1-S3" ./deploy-vsphere-ovftool.ini
----


각 노드의 상태가 "통과"이면 배포가 완료됩니다.

[listing]
----
Deployment Summary
+-----------------------------+----------+----------------------+
| node                        | attempts | status               |
+-----------------------------+----------+----------------------+
| DC1-ADM1                    |        1 | Passed               |
| DC1-G1                      |        1 | Passed               |
| DC1-S1                      |        1 | Passed               |
| DC1-S2                      |        1 | Passed               |
| DC1-S3                      |        1 | Passed               |
+-----------------------------+----------+----------------------+
----


== StorageGRID 구성 자동화

그리드 노드를 배포한 후 StorageGRID 시스템 구성을 자동화할 수 있습니다.

.시작하기 전에
* 설치 아카이브에서 다음 파일의 위치를 알고 있습니다.
+
[cols="1a,1a"]
|===
| 파일 이름 | 설명 


| configure-storagegrid.py  a| 
구성을 자동화하는 데 사용되는 Python 스크립트



| configure-storagegrid.sample.json  a| 
스크립트와 함께 사용할 수 있는 예제 구성 파일



| configure-storagegrid.blank.json  a| 
스크립트와 함께 사용할 빈 구성 파일

|===
* 당신은 생성했습니다 `configure-storagegrid.json` 구성 파일.  이 파일을 생성하려면 예제 구성 파일을 수정할 수 있습니다.(`configure-storagegrid.sample.json` ) 또는 빈 구성 파일(`configure-storagegrid.blank.json` ).
+
당신은 사용할 수 있습니다 `configure-storagegrid.py` Python 스크립트 및 `configure-storagegrid.json` StorageGRID 시스템 구성을 자동화하는 그리드 구성 파일입니다.

+

NOTE: Grid Manager나 설치 API를 사용하여 시스템을 구성할 수도 있습니다.



.단계
. Python 스크립트를 실행하기 위해 사용하는 Linux 머신에 로그인합니다.
. 설치 아카이브를 추출한 디렉토리로 변경합니다.
+
예를 들어:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
어디 `platform` debs, rpms 또는 vsphere인가요?

. Python 스크립트를 실행하고 생성한 구성 파일을 사용합니다.
+
예를 들어:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.결과
복구 패키지 `.zip` 파일은 구성 과정 중에 생성되며, 설치 및 구성 과정을 실행하는 디렉토리에 다운로드됩니다.  하나 이상의 그리드 노드가 실패할 경우 StorageGRID 시스템을 복구할 수 있도록 복구 패키지 파일을 백업해야 합니다.  예를 들어, 안전하게 백업된 네트워크 위치와 안전한 클라우드 스토리지 위치에 복사하세요.


CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 얻는 데 사용할 수 있는 암호화 키와 비밀번호가 포함되어 있으므로 보호되어야 합니다.

임의의 비밀번호가 생성되도록 지정한 경우 다음을 엽니다. `Passwords.txt` 파일을 열고 StorageGRID 시스템에 액세스하는 데 필요한 비밀번호를 찾으세요.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
StorageGRID 시스템이 설치되고 구성되면 확인 메시지가 표시됩니다.

[listing]
----
StorageGRID has been configured and installed.
----
.관련 정보
* link:navigating-to-grid-manager.html["그리드 관리자로 이동"]
* link:overview-of-installation-rest-api.html["REST API 설치"]

