---
permalink: vmware/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords: how to collect information about your deployment environment 
summary: 그리드 노드를 배포하기 전에 네트워크 구성과 VMware 환경에 대한 정보를 수집해야 합니다. 
---
= 배포 환경에 대한 정보 수집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 노드를 배포하기 전에 네트워크 구성과 VMware 환경에 대한 정보를 수집해야 합니다.


NOTE: 일부 노드를 지금 설치하고 일부 노드를 나중에 설치하는 것보다, 모든 노드를 한 번에 설치하는 것이 더 효율적입니다.



== VMware 정보

배포 환경에 액세스하여 VMware 환경, 그리드, 관리자 및 클라이언트 네트워크용으로 생성된 네트워크, 스토리지 노드에 사용하려는 스토리지 볼륨 유형에 대한 정보를 수집해야 합니다.

다음을 포함하여 VMware 환경에 대한 정보를 수집해야 합니다.

* 배포를 완료하는 데 필요한 적절한 권한이 있는 VMware vSphere 계정의 사용자 이름과 비밀번호입니다.
* 각 StorageGRID 노드 가상 머신에 대한 호스트, 데이터 저장소 및 네트워크 구성 정보입니다.



NOTE: VMware 라이브 vMotion은 가상 머신 클럭 시간을 점프하게 하며 모든 유형의 그리드 노드에서 지원되지 않습니다.  드물지만 잘못된 시계 시간으로 인해 데이터 손실이나 구성 업데이트가 발생할 수 있습니다.



== 그리드 네트워크 정보

StorageGRID Grid Network(필수)를 위해 생성된 VMware 네트워크에 대한 정보를 수집해야 합니다. 여기에는 다음이 포함됩니다.

* 네트워크 이름.
* IP 주소를 할당하는 데 사용되는 방법으로 정적 또는 DHCP가 있습니다.
+
** 고정 IP 주소를 사용하는 경우 각 그리드 노드에 필요한 네트워킹 세부 정보(IP 주소, 게이트웨이, 네트워크 마스크)가 필요합니다.
** DHCP를 사용하는 경우 그리드 네트워크의 기본 관리 노드의 IP 주소입니다. 보다 link:how-grid-nodes-discover-primary-admin-node.html["그리드 노드가 기본 관리 노드를 검색하는 방법"] 자세한 내용은.






== 관리자 네트워크 정보

선택 사항인 StorageGRID 관리 네트워크에 연결될 노드의 경우, 다음을 포함하여 이 네트워크에 대해 생성된 VMware 네트워크에 대한 정보를 수집해야 합니다.

* 네트워크 이름.
* IP 주소를 할당하는 데 사용되는 방법으로 정적 또는 DHCP가 있습니다.
+
** 고정 IP 주소를 사용하는 경우 각 그리드 노드에 필요한 네트워킹 세부 정보(IP 주소, 게이트웨이, 네트워크 마스크)가 필요합니다.
** DHCP를 사용하는 경우 그리드 네트워크의 기본 관리 노드의 IP 주소입니다. 보다 link:how-grid-nodes-discover-primary-admin-node.html["그리드 노드가 기본 관리 노드를 검색하는 방법"] 자세한 내용은.


* 관리 네트워크의 외부 서브넷 목록(ESL)입니다.




== 클라이언트 네트워크 정보

선택 사항인 StorageGRID 클라이언트 네트워크에 연결될 노드의 경우, 다음을 포함하여 이 네트워크에 대해 생성된 VMware 네트워크에 대한 정보를 수집해야 합니다.

* 네트워크 이름.
* IP 주소를 할당하는 데 사용되는 방법으로 정적 또는 DHCP가 있습니다.
* 고정 IP 주소를 사용하는 경우 각 그리드 노드에 필요한 네트워킹 세부 정보(IP 주소, 게이트웨이, 네트워크 마스크)가 필요합니다.




== 추가 인터페이스에 대한 정보

노드를 설치한 후 vCenter에서 VM에 트렁크 또는 액세스 인터페이스를 추가할 수 있습니다.  예를 들어, 관리 노드나 게이트웨이 노드에 트렁크 인터페이스를 추가하여 VLAN 인터페이스를 사용하여 서로 다른 애플리케이션이나 테넌트에 속하는 트래픽을 분리할 수 있습니다.  또는 고가용성(HA) 그룹에서 사용할 액세스 인터페이스를 추가할 수도 있습니다.

추가한 인터페이스는 Grid Manager의 VLAN 인터페이스 페이지와 HA 그룹 페이지에 표시됩니다.

* 트렁크 인터페이스를 추가하는 경우 각 새 부모 인터페이스에 대해 하나 이상의 VLAN 인터페이스를 구성합니다. 보다 link:../admin/configure-vlan-interfaces.html["VLAN 인터페이스 구성"] .
* 액세스 인터페이스를 추가하는 경우 HA 그룹에 직접 추가해야 합니다. 보다 link:../admin/configure-high-availability-group.html["고가용성 그룹 구성"] .




== 가상 스토리지 노드의 스토리지 볼륨

가상 머신 기반 스토리지 노드에 대해 다음 정보를 수집해야 합니다.

* 추가할 스토리지 볼륨(스토리지 LUN)의 수와 크기. 다음을 참조하세요.link:storage-and-performance-requirements.html["저장 및 성능 요구 사항"] .




== 그리드 구성 정보

그리드를 구성하려면 정보를 수집해야 합니다.

* 그리드 라이센스
* 네트워크 시간 프로토콜(NTP) 서버 IP 주소
* DNS 서버 IP 주소

