---
permalink: vmware/deploying-storagegrid-node-as-virtual-machine.html 
sidebar: sidebar 
keywords: how to deploy grid nodes in vsphere or vsphere web client, port, remap, port remap 
summary: VMware vSphere Web Client를 사용하여 각 그리드 노드를 가상 머신으로 배포합니다.  배포 중에 각 그리드 노드가 생성되어 하나 이상의 StorageGRID 네트워크에 연결됩니다. 
---
= StorageGRID 노드를 가상 머신으로 배포
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere Web Client를 사용하여 각 그리드 노드를 가상 머신으로 배포합니다.  배포 중에 각 그리드 노드가 생성되어 하나 이상의 StorageGRID 네트워크에 연결됩니다.

StorageGRID 어플라이언스 스토리지 노드를 배포해야 하는 경우 다음을 참조하세요. https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/deploying-appliance-storage-node.html["어플라이언스 스토리지 노드 배포"^] .

선택적으로, 노드의 전원을 켜기 전에 노드 포트를 다시 매핑하거나 CPU 또는 메모리 설정을 늘릴 수 있습니다.

.시작하기 전에
* 당신은 방법을 검토했습니다link:index.html["설치를 계획하고 준비하다"] 그리고 소프트웨어, CPU 및 RAM, 스토리지 및 성능에 대한 요구 사항을 이해합니다.
* 귀하는 VMware vSphere Hypervisor에 익숙하며 이 환경에서 가상 머신을 배포한 경험이 있습니다.
+

NOTE: 그만큼 `open-vm-tools` VMware Tools와 유사한 오픈 소스 구현인 패키지가 StorageGRID 가상 머신에 포함되어 있습니다.  VMware Tools를 수동으로 설치할 필요는 없습니다.

* VMware용 StorageGRID 설치 아카이브의 올바른 버전을 다운로드하여 압축을 풀었습니다.
+

CAUTION: 확장 또는 복구 작업의 일부로 새 노드를 배포하는 경우 현재 그리드에서 실행 중인 StorageGRID 버전을 사용해야 합니다.

* StorageGRID 가상 머신 디스크가 있습니다.(`.vmdk` ) 파일:


[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
----
* 당신은 가지고있다 `.ovf` 그리고 `.mf` 배포하는 각 유형의 그리드 노드에 대한 파일:
+
[cols="1a,1a"]
|===
| 파일 이름 | 설명 


| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
기본 관리 노드에 대한 템플릿 파일과 매니페스트 파일입니다.



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
기본이 아닌 관리 노드에 대한 템플릿 파일과 매니페스트 파일입니다.



| vsphere-storage.ovf vsphere-storage.mf  a| 
스토리지 노드의 템플릿 파일과 매니페스트 파일입니다.



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
게이트웨이 노드의 템플릿 파일과 매니페스트 파일입니다.

|===
* 그만큼 `.vdmk` , `.ovf` , 그리고 `.mf` 모든 파일이 같은 디렉토리에 있습니다.
* 실패 도메인을 최소화하기 위한 계획이 있습니다.  예를 들어, 모든 게이트웨이 노드를 단일 vSphere ESXi 호스트에 배포해서는 안 됩니다.
+

CAUTION: 실제 운영 환경에서는 하나의 가상 머신에 두 개 이상의 스토리지 노드를 실행하지 마세요.  허용할 수 없는 장애 도메인 문제가 발생할 경우 동일한 ESXi 호스트에서 여러 가상 머신을 실행하지 마세요.

* 확장 또는 복구 작업의 일부로 노드를 배포하는 경우 다음이 있습니다.link:../expand/index.html["StorageGRID 시스템 확장을 위한 지침"] 또는link:../maintain/index.html["복구 및 유지 관리 지침"] .
* NetApp ONTAP 시스템에서 스토리지가 할당된 가상 머신으로 StorageGRID 노드를 배포하는 경우 볼륨에 FabricPool 계층화 정책이 활성화되어 있지 않음을 확인한 것입니다.  예를 들어, StorageGRID 노드가 VMware 호스트에서 가상 머신으로 실행되는 경우, 해당 노드의 데이터스토어를 지원하는 볼륨에 FabricPool 계층화 정책이 활성화되어 있지 않은지 확인하세요.  StorageGRID 노드와 함께 사용되는 볼륨에 대해 FabricPool 계층화를 비활성화하면 문제 해결 및 스토리지 작업이 간소화됩니다.
+

NOTE: StorageGRID 와 관련된 데이터를 StorageGRID 자체로 다시 계층화하는 데 FabricPool 사용하지 마세요.  StorageGRID 데이터를 StorageGRID 로 다시 계층화하면 문제 해결과 운영상의 복잡성이 증가합니다.



.이 작업에 관하여
VMware 노드를 처음 배포하거나, 확장 시 새 VMware 노드를 추가하거나, 복구 작업의 일부로 VMware 노드를 교체하려면 다음 지침을 따르세요.  단계에 명시된 경우를 제외하고 노드 배포 절차는 관리 노드, 스토리지 노드, 게이트웨이 노드를 포함한 모든 노드 유형에 대해 동일합니다.

새로운 StorageGRID 시스템을 설치하는 경우:

* 원하는 순서대로 노드를 배포할 수 있습니다.
* 각 가상 머신이 그리드 네트워크를 통해 기본 관리 노드에 연결할 수 있는지 확인해야 합니다.
* 그리드를 구성하기 전에 모든 그리드 노드를 배포해야 합니다.


확장 또는 복구 작업을 수행하는 경우:

* 새로운 가상 머신이 그리드 네트워크를 통해 다른 모든 노드에 연결할 수 있는지 확인해야 합니다.


노드의 포트를 다시 매핑해야 하는 경우 포트 다시 매핑 구성이 완료될 때까지 새 노드의 전원을 켜지 마세요.

.단계
. VCenter를 사용하여 OVF 템플릿을 배포합니다.
+
URL을 지정하는 경우 다음 파일이 들어 있는 폴더를 가리킵니다.  그렇지 않은 경우 로컬 디렉토리에서 각 파일을 선택합니다.

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-_node_.ovf
vsphere-_node_.mf
----
+
예를 들어, 이것이 배포하는 첫 번째 노드인 경우 다음 파일을 사용하여 StorageGRID 시스템의 기본 관리 노드를 배포합니다.

+
[listing, subs="specialcharacters,quotes"]
----
NetApp-_SG-version_-SHA.vmdk
vsphere-primary-admin.ovf
vsphere-primary-admin.mf
----
. 가상 머신의 이름을 입력하세요.
+
표준 관행은 가상 머신과 그리드 노드에 모두 동일한 이름을 사용하는 것입니다.

. 가상 머신을 적절한 vApp 또는 리소스 풀에 배치합니다.
. 기본 관리 노드를 배포하는 경우 최종 사용자 라이선스 계약을 읽고 동의하세요.
+
vCenter 버전에 따라 최종 사용자 라이선스 계약 수락, 가상 머신 이름 지정, 데이터 저장소 선택 단계 순서가 달라집니다.

. 가상 머신의 저장소를 선택하세요.
+
복구 작업의 일부로 노드를 배포하는 경우 다음 지침을 수행하십시오.<<step_recovery_storage,저장 복구 단계>> 새로운 가상 디스크를 추가하거나, 실패한 그리드 노드에서 가상 하드 디스크를 다시 연결하거나, 둘 다 수행합니다.

+
스토리지 노드를 배포할 때는 3개 이상의 스토리지 볼륨을 사용하고 각 스토리지 볼륨은 4TB 이상이어야 합니다.  볼륨 0에 최소 4TB를 할당해야 합니다.

+

NOTE: 스토리지 노드 .ovf 파일은 스토리지를 위한 여러 VMDK를 정의합니다.  이러한 VMDK가 저장 요구 사항을 충족하지 않는 경우 노드의 전원을 켜기 전에 VMDK를 제거하고 적절한 VMDK 또는 RDM을 저장에 할당해야 합니다.  VMDK는 VMware 환경에서 보다 일반적으로 사용되며 관리하기 쉬운 반면, RDM은 더 큰 개체 크기(예: 100MB 이상)를 사용하는 작업 부하에 대해 더 나은 성능을 제공할 수 있습니다.

+

NOTE: 일부 StorageGRID 설치는 일반적인 가상화된 워크로드보다 더 크고 더 활성화된 스토리지 볼륨을 사용할 수 있습니다.  다음과 같은 일부 하이퍼바이저 매개변수를 조정해야 할 수도 있습니다. `MaxAddressableSpaceTB` 최적의 성능을 달성하기 위해.  성능이 저하되는 경우 가상화 지원 리소스에 문의하여 작업 부하별 구성 조정이 환경에 도움이 될 수 있는지 확인하세요.

. 네트워크를 선택하세요.
+
각 소스 네트워크에 대한 대상 네트워크를 선택하여 노드가 사용할 StorageGRID 네트워크를 결정합니다.

+
** 그리드 네트워크가 필요합니다.  vSphere 환경에서 대상 네트워크를 선택해야 합니다.  + Grid Network는 모든 내부 StorageGRID 트래픽에 사용됩니다.  이는 모든 사이트와 서브넷에 걸쳐 그리드의 모든 노드 간에 연결을 제공합니다.  그리드 네트워크의 모든 노드는 다른 모든 노드와 통신할 수 있어야 합니다.
** 관리 네트워크를 사용하는 경우 vSphere 환경에서 다른 대상 네트워크를 선택하세요.  관리자 네트워크를 사용하지 않는 경우 그리드 네트워크에서 선택한 대상과 동일한 대상을 선택하세요.
** 클라이언트 네트워크를 사용하는 경우 vSphere 환경에서 다른 대상 네트워크를 선택하세요.  클라이언트 네트워크를 사용하지 않는 경우 그리드 네트워크에서 선택한 대상과 동일한 대상을 선택하세요.
** 관리자 또는 클라이언트 네트워크를 사용하는 경우 노드가 동일한 관리자 또는 클라이언트 네트워크에 있을 필요는 없습니다.


. *템플릿 사용자 지정*의 경우 필요한 StorageGRID 노드 속성을 구성합니다.
+
.. *노드 이름*을 입력하세요.
+

NOTE: 그리드 노드를 복구하는 경우 복구 중인 노드의 이름을 입력해야 합니다.

.. *임시 설치 비밀번호* 드롭다운을 사용하여 임시 설치 비밀번호를 지정하면 새 노드가 그리드에 가입하기 전에 VM 콘솔이나 StorageGRID 설치 API에 액세스하거나 SSH를 사용할 수 있습니다.
+

NOTE: 임시 설치 비밀번호는 노드 설치 중에만 사용됩니다.  그리드에 노드가 추가된 후에는 다음을 사용하여 액세스할 수 있습니다.link:../admin/change-node-console-password.html["노드 콘솔 비밀번호"] ,에 나열되어 있습니다 `Passwords.txt` 복구 패키지의 파일입니다.

+
*** *노드 이름 사용*: *노드 이름* 필드에 제공한 값이 임시 설치 비밀번호로 사용됩니다.
*** *사용자 지정 비밀번호 사용*: 사용자 지정 비밀번호는 임시 설치 비밀번호로 사용됩니다.
*** *비밀번호 비활성화*: 임시 설치 비밀번호가 사용되지 않습니다.  설치 문제를 디버깅하기 위해 VM에 액세스해야 하는 경우 다음을 참조하세요.link:troubleshooting-installation-issues.html["설치 문제 해결"] .


.. *사용자 지정 비밀번호 사용*을 선택한 경우, *사용자 지정 비밀번호* 필드에 사용하려는 임시 설치 비밀번호를 지정합니다.
.. *Grid Network (eth0)* 섹션에서 *Grid Network IP 구성*에 대해 STATIC 또는 DHCP를 선택합니다.
+
*** STATIC을 선택하는 경우 *그리드 네트워크 IP*, *그리드 네트워크 마스크*, *그리드 네트워크 게이트웨이*, *그리드 네트워크 MTU*를 입력합니다.
*** DHCP를 선택하면 *그리드 네트워크 IP*, *그리드 네트워크 마스크*, *그리드 네트워크 게이트웨이*가 자동으로 할당됩니다.


.. *기본 관리자 IP* 필드에 그리드 네트워크의 기본 관리 노드의 IP 주소를 입력합니다.
+

NOTE: 배포하는 노드가 기본 관리 노드인 경우 이 단계는 적용되지 않습니다.

+
기본 관리 노드 IP 주소를 생략하면 기본 관리 노드 또는 ADMIN_IP가 구성된 다른 그리드 노드가 하나 이상 동일한 서브넷에 있는 경우 IP 주소가 자동으로 검색됩니다.  하지만 여기에 기본 관리 노드 IP 주소를 설정하는 것이 좋습니다.

.. *관리자 네트워크(eth1)* 섹션에서 *관리자 네트워크 IP 구성*에 대해 STATIC, DHCP 또는 DISABLED를 선택합니다.
+
*** 관리자 네트워크를 사용하지 않으려면 '사용 안 함'을 선택하고 관리자 네트워크 IP에 *0.0.0.0*을 입력합니다.  다른 필드는 비워두어도 됩니다.
*** STATIC을 선택하는 경우 *관리자 네트워크 IP*, *관리자 네트워크 마스크*, *관리자 네트워크 게이트웨이*, *관리자 네트워크 MTU*를 입력합니다.
*** STATIC을 선택하는 경우 *관리자 네트워크 외부 서브넷 목록*을 입력합니다.  게이트웨이도 구성해야 합니다.
*** DHCP를 선택하면 *관리자 네트워크 IP*, *관리자 네트워크 마스크*, *관리자 네트워크 게이트웨이*가 자동으로 할당됩니다.


.. *클라이언트 네트워크(eth2)* 섹션에서 *클라이언트 네트워크 IP 구성*에 대해 STATIC, DHCP 또는 DISABLED를 선택합니다.
+
*** 클라이언트 네트워크를 사용하지 않으려면 비활성화를 선택하고 클라이언트 네트워크 IP에 *0.0.0.0*을 입력합니다.  다른 필드는 비워두어도 됩니다.
*** STATIC을 선택하는 경우 *클라이언트 네트워크 IP*, *클라이언트 네트워크 마스크*, *클라이언트 네트워크 게이트웨이*, *클라이언트 네트워크 MTU*를 입력합니다.
*** DHCP를 선택하면 *클라이언트 네트워크 IP*, *클라이언트 네트워크 마스크*, *클라이언트 네트워크 게이트웨이*가 자동으로 할당됩니다.




. 가상 머신 구성을 검토하고 필요한 변경 사항을 적용합니다.
. 완료할 준비가 되면 *마침*을 선택하여 가상 머신 업로드를 시작합니다.
. [[step_recovery_storage]]복구 작업의 일부로 이 노드를 배포했고 이것이 전체 노드 복구가 아닌 경우 배포가 완료된 후 다음 단계를 수행하십시오.
+
.. 가상 머신을 마우스 오른쪽 버튼으로 클릭하고 *설정 편집*을 선택합니다.
.. 저장을 위해 지정된 각 기본 가상 하드 디스크를 선택하고 *제거*를 선택합니다.
.. 데이터 복구 상황에 따라 스토리지 요구 사항에 맞춰 새 가상 디스크를 추가하거나, 이전에 제거된 실패한 그리드 노드에서 보존된 가상 하드 디스크를 다시 연결하거나, 두 가지를 모두 수행합니다.
+
다음의 중요한 지침을 참고하세요.

+
*** 새 디스크를 추가하는 경우 노드 복구 전에 사용하던 것과 동일한 유형의 저장 장치를 사용해야 합니다.
*** 스토리지 노드 .ovf 파일은 스토리지를 위한 여러 VMDK를 정의합니다.  이러한 VMDK가 저장 요구 사항을 충족하지 않는 경우 노드의 전원을 켜기 전에 VMDK를 제거하고 적절한 VMDK 또는 RDM을 저장에 할당해야 합니다.  VMDK는 VMware 환경에서 보다 일반적으로 사용되며 관리하기 쉬운 반면, RDM은 더 큰 개체 크기(예: 100MB 이상)를 사용하는 작업 부하에 대해 더 나은 성능을 제공할 수 있습니다.




. [[vmware-remap-ports]]이 노드에서 사용하는 포트를 다시 매핑해야 하는 경우 다음 단계를 따르세요.
+
기업 네트워킹 정책이 StorageGRID 에서 사용하는 하나 이상의 포트에 대한 액세스를 제한하는 경우 포트를 다시 매핑해야 할 수도 있습니다.  를 참조하십시오link:../network/index.html["네트워킹 가이드라인"] StorageGRID 에서 사용하는 포트에 대해.

+

NOTE: 로드 밸런서 엔드포인트에서 사용되는 포트를 다시 매핑하지 마세요.

+
.. 새로운 VM을 선택하세요.
.. 구성 탭에서 *설정* > *vApp 옵션*을 선택합니다.  *vApp 옵션*의 위치는 vCenter 버전에 따라 다릅니다.
.. *속성* 테이블에서 PORT_REMAP_INBOUND와 PORT_REMAP을 찾습니다.
.. 포트에 대한 인바운드 및 아웃바운드 통신을 대칭적으로 매핑하려면 *PORT_REMAP*을 선택합니다.
+

NOTE: PORT_REMAP만 설정된 경우 지정한 매핑은 인바운드 및 아웃바운드 통신 모두에 적용됩니다.  PORT_REMAP_INBOUND도 지정된 경우 PORT_REMAP은 아웃바운드 통신에만 적용됩니다.

+
... *값 설정*을 선택하세요.
... 포트 매핑을 입력하세요:
+
`<network type>/<protocol>/<default port used by grid node>/<new port>`

+
`<network type>`그리드, 관리자 또는 클라이언트이며 `<protocol>` tcp인가 udp인가.

+
예를 들어, 포트 22에서 포트 3022로 ssh 트래픽을 다시 매핑하려면 다음을 입력합니다.

+
`client/tcp/22/3022`

+
쉼표로 구분된 목록을 사용하여 여러 포트를 다시 매핑할 수 있습니다.

+
예를 들어:

+
`client/tcp/18082/443, client/tcp/18083/80`

... *확인*을 선택하세요.


.. 노드로의 인바운드 통신에 사용되는 포트를 지정하려면 *PORT_REMAP_INBOUND*를 선택하세요.
+

NOTE: PORT_REMAP_INBOUND를 지정하고 PORT_REMAP에 대한 값을 지정하지 않으면 해당 포트의 아웃바운드 통신은 변경되지 않습니다.

+
... *값 설정*을 선택하세요.
... 포트 매핑을 입력하세요:
+
`<network type>/<protocol>/<remapped inbound port>/<default inbound port used by grid node>`

+
`<network type>`그리드, 관리자 또는 클라이언트이며 `<protocol>` tcp인가 udp인가.

+
예를 들어, 포트 3022로 전송되는 인바운드 SSH 트래픽을 그리드 노드에서 포트 22에서 수신하도록 다시 매핑하려면 다음을 입력합니다.

+
`client/tcp/3022/22`

+
쉼표로 구분된 목록을 사용하여 여러 개의 인바운드 포트를 다시 매핑할 수 있습니다.

+
예를 들어:

+
`grid/tcp/3022/22, admin/tcp/3022/22`

... *확인*을 선택하세요




. 기본 설정에서 노드의 CPU나 메모리를 늘리려면:
+
.. 가상 머신을 마우스 오른쪽 버튼으로 클릭하고 *설정 편집*을 선택합니다.
.. 필요에 따라 CPU 수나 메모리 양을 변경하세요.
+
*메모리 예약*을 가상 머신에 할당된 *메모리*와 같은 크기로 설정합니다.

.. *확인*을 선택하세요.


. 가상 머신의 전원을 켭니다.


.당신이 완료한 후
확장 또는 복구 절차의 일부로 이 노드를 배포한 경우 해당 지침으로 돌아가서 절차를 완료하세요.
