---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download vmware installation files 
summary: StorageGRID 설치 아카이브를 다운로드하고 파일을 추출해야 합니다. 선택적으로 설치 패키지의 파일을 수동으로 확인할 수 있습니다. 
---
= StorageGRID 설치 파일을 다운로드하고 추출합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 설치 아카이브를 다운로드하고 파일을 추출해야 합니다. 선택적으로 설치 패키지의 파일을 수동으로 확인할 수 있습니다.

.단계
. 로 가다 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["StorageGRID 용 NetApp 다운로드 페이지"^] .
. 최신 릴리스를 다운로드하려면 버튼을 선택하거나 드롭다운 메뉴에서 다른 버전을 선택하고 *이동*을 선택하세요.
. NetApp 계정의 사용자 이름과 비밀번호로 Sign in .
. 주의/반드시 읽어야 할 내용이 나타나면 읽고 체크박스를 선택하세요.
+

CAUTION: StorageGRID 릴리스를 설치한 후에는 필요한 핫픽스를 적용해야 합니다. 자세한 내용은 다음을 참조하세요.link:../maintain/storagegrid-hotfix-procedure.html["복구 및 유지 관리 지침의 핫픽스 절차"]

. 최종 사용자 라이선스 계약을 읽고 확인란을 선택한 다음 *동의 및 계속*을 선택하세요.
. * StorageGRID 설치* 열에서 VMware용 .tgz 또는 .zip 설치 아카이브를 선택합니다.
+

NOTE: 사용하다 `.zip` 서비스 노트북에서 Windows를 실행하는 경우 파일입니다.

. 설치 아카이브를 저장합니다.
. [[vmware-download-verification-package]]설치 아카이브를 확인해야 하는 경우:
+
.. StorageGRID 코드 서명 검증 패키지를 다운로드하세요.  이 패키지의 파일 이름은 다음 형식을 사용합니다. `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz` , 어디 `<version-number>` StorageGRID 소프트웨어 버전입니다.
.. 다음 단계를 따르세요link:../vmware/download-files-verify.html["설치 파일을 수동으로 확인하세요"] .


. 설치 아카이브에서 파일을 추출합니다.
. 필요한 파일을 선택하세요.
+
필요한 파일은 계획된 그리드 토폴로지와 StorageGRID 시스템을 배포하는 방법에 따라 달라집니다.




NOTE: 표에 나열된 경로는 추출된 설치 아카이브에 의해 설치된 최상위 디렉토리를 기준으로 합니다.

[cols="1a,1a"]
|===
| 경로 및 파일 이름 | 설명 


| ./vsphere/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| ./vsphere/NLF000000.txt  a| 
제품에 대한 지원 권한을 제공하지 않는 무료 라이센스입니다.



| ./vsphere/ NetApp-SG-버전-SHA.vmdk  a| 
그리드 노드 가상 머신을 생성하기 위한 템플릿으로 사용되는 가상 머신 디스크 파일입니다.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
Open Virtualization Format 템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 기본 관리 노드를 배포하기 위한 것입니다.



| ./vsphere/vsphere-비-기본-관리자.ovf ./vsphere/vsphere-비-기본-관리자.mf  a| 
템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 기본이 아닌 관리 노드를 배포하기 위한 것입니다.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 게이트웨이 노드를 배포하기 위한 것입니다.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 가상 머신 기반 스토리지 노드를 배포하기 위한 것입니다.



| 배포 스크립팅 도구 | 설명 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
가상 그리드 노드의 배포를 자동화하는 데 사용되는 Bash 셸 스크립트입니다.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
다음과 함께 사용할 수 있는 구성 파일 예 `deploy-vsphere-ovftool.sh` 스크립트.



| ./vsphere/configure-storagegrid.py  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./vsphere/configure-sga.py  a| 
StorageGRID 어플라이언스의 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./vsphere/storagegrid-ssoauth.py  a| 
SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예시입니다.  이 스크립트는 Ping Federate 통합에도 사용할 수 있습니다.



| ./vsphere/configure-storagegrid.sample.json  a| 
다음과 함께 사용할 수 있는 구성 파일 예 `configure-storagegrid.py` 스크립트.



| ./vsphere/configure-storagegrid.blank.json  a| 
사용할 빈 구성 파일 `configure-storagegrid.py` 스크립트.



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Active Directory 또는 Ping Federate를 사용하여 SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예시입니다.



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
동반자가 호출하는 도우미 스크립트 `storagegrid-ssoauth-azure.py` Azure와 SSO 상호 작용을 수행하는 Python 스크립트입니다.



| ./vsphere/extras/api-schemas  a| 
StorageGRID 에 대한 API 스키마.

*참고*: 업그레이드를 수행하기 전에 이러한 스키마를 사용하여 업그레이드 호환성 테스트를 위한 비프로덕션 StorageGRID 환경이 없는 경우 StorageGRID 관리 API를 사용하기 위해 작성한 모든 코드가 새 StorageGRID 릴리스와 호환되는지 확인할 수 있습니다.

|===