---
permalink: vmware/required-materials.html 
sidebar: sidebar 
keywords: installation materials vmware 
summary: StorageGRID 설치하기 전에 필요한 정보와 자료를 수집하고 준비하세요. 
---
= 필수 정보 및 자료
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 설치하기 전에 필요한 정보와 자료를 수집하고 준비하세요.



== 필수 정보

네트워크 계획:: 각 StorageGRID 노드에 연결할 네트워크입니다.  StorageGRID 트래픽 분리, 보안 및 관리 편의성을 위해 여러 네트워크를 지원합니다.
+
--
StorageGRID 확인하세요link:../network/index.html["네트워킹 가이드라인"] .

--
네트워크 정보:: 각 그리드 노드에 할당할 IP 주소와 DNS 및 NTP 서버의 IP 주소입니다.
그리드 노드용 서버:: 배포하려는 StorageGRID 노드의 수와 유형을 지원하기에 충분한 리소스를 전체적으로 제공하는 서버 세트(물리적, 가상 또는 둘 다)를 식별합니다.
+
--

NOTE: StorageGRID 설치에서 StorageGRID 어플라이언스(하드웨어) 스토리지 노드를 사용하지 않는 경우 배터리 백업 쓰기 캐시(BBWC)가 있는 하드웨어 RAID 스토리지를 사용해야 합니다.  StorageGRID vSAN(가상 스토리지 영역 네트워크), 소프트웨어 RAID 또는 RAID 보호 없음을 지원하지 않습니다.

--
관련 정보:: https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 도구"^]




== 필요한 자료

NetApp StorageGRID 라이선스:: 유효하고 디지털로 서명된 NetApp 라이선스가 있어야 합니다.



NOTE: 테스트 및 개념 증명 그리드에 사용할 수 있는 비생산용 라이선스가 StorageGRID 설치 아카이브에 포함되어 있습니다.

StorageGRID 설치 아카이브:: link:downloading-and-extracting-storagegrid-installation-files.html["StorageGRID 설치 아카이브를 다운로드하고 파일을 추출합니다."] .
서비스 노트북:: StorageGRID 시스템은 서비스 노트북을 통해 설치됩니다.
+
--
서비스용 노트북에는 다음이 포함되어야 합니다.

* 네트워크 포트
* SSH 클라이언트(예: PuTTY)
* link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]


--
StorageGRID 문서::
+
--
* link:../release-notes/index.html["릴리스 노트"]
* link:../admin/index.html["StorageGRID 관리 지침"]


--

