---
permalink: vmware/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: 가상 머신을 사용하면 모든 유형의 StorageGRID 노드를 호스팅할 수 있습니다.  각 그리드 노드마다 하나의 가상 머신이 필요합니다. 
---
= VMware 소프트웨어 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 머신을 사용하면 모든 유형의 StorageGRID 노드를 호스팅할 수 있습니다.  각 그리드 노드마다 하나의 가상 머신이 필요합니다.



== VMware vSphere 하이퍼바이저

준비된 물리적 서버에 VMware vSphere Hypervisor를 설치해야 합니다.  VMware 소프트웨어를 설치하기 전에 하드웨어를 올바르게 구성해야 합니다(펌웨어 버전 및 BIOS 설정 포함).

* 설치하려는 StorageGRID 시스템의 네트워킹을 지원하기 위해 필요에 따라 하이퍼바이저에서 네트워킹을 구성합니다.
+
link:../network/index.html["네트워킹 가이드라인"]

* 그리드 노드를 호스팅하는 데 필요한 가상 머신과 가상 디스크를 수용할 만큼 데이터 저장소가 충분히 큰지 확인하세요.
* 두 개 이상의 데이터 저장소를 만드는 경우 각 데이터 저장소의 이름을 지정하면 가상 머신을 만들 때 각 그리드 노드에 사용할 데이터 저장소를 쉽게 식별할 수 있습니다.




== ESX 호스트 구성 요구 사항


CAUTION: 각 ESX 호스트에서 네트워크 시간 프로토콜(NTP)을 올바르게 구성해야 합니다.  호스트 시간이 올바르지 않으면 데이터 손실을 포함한 부정적인 영향이 발생할 수 있습니다.



== VMware 구성 요구 사항

StorageGRID 노드를 배포하기 전에 VMware vSphere 및 vCenter를 설치하고 구성해야 합니다.

지원되는 VMware vSphere Hypervisor 및 VMware vCenter Server 소프트웨어 버전은 다음을 참조하세요. https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 도구"^] .

이러한 VMware 제품을 설치하는 데 필요한 단계는 VMware 설명서를 참조하세요.
