---
permalink: vmware/troubleshooting-installation-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot installation issues 
summary: StorageGRID 시스템을 설치하는 동안 문제가 발생하면 설치 로그 파일에 액세스할 수 있습니다. 
---
= 설치 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템을 설치하는 동안 문제가 발생하면 설치 로그 파일에 액세스할 수 있습니다.

기술 지원팀에서 문제를 해결하는 데 필요할 수 있는 주요 설치 로그 파일은 다음과 같습니다.

* `/var/local/log/install.log`(모든 그리드 노드에서 발견됨)
* `/var/local/log/gdu-server.log`(기본 관리 노드에서 발견됨)


.관련 정보
로그 파일에 액세스하는 방법을 알아보려면 다음을 참조하세요.link:../monitor/logs-files-reference.html["로그 파일 참조"] .

추가 도움이 필요하면 문의하세요. https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^] .



== 가상 머신 리소스 예약에 조정이 필요합니다.

OVF 파일에는 각 그리드 노드가 효율적으로 작동하는 데 충분한 RAM과 CPU를 확보하도록 설계된 리소스 예약이 포함되어 있습니다.  VMware에 이러한 OVF 파일을 배포하여 가상 머신을 생성하고 미리 정의된 수의 리소스를 사용할 수 없는 경우 가상 머신이 시작되지 않습니다.

.이 작업에 관하여
VM 호스트에 각 그리드 노드에 대한 충분한 리소스가 있는지 확인한 후, 각 가상 머신에 할당된 리소스를 수동으로 조정한 다음 가상 머신을 시작해 보세요.

.단계
. VMware vSphere Hypervisor 클라이언트 트리에서 시작되지 않은 가상 머신을 선택합니다.
. 가상 머신을 마우스 오른쪽 버튼으로 클릭하고 *설정 편집*을 선택합니다.
. 가상 머신 속성 창에서 *리소스* 탭을 선택합니다.
. 가상 머신에 할당된 리소스를 조정합니다.
+
.. *CPU*를 선택한 다음 예약 슬라이더를 사용하여 이 가상 머신에 예약된 MHz를 조정합니다.
.. *메모리*를 선택한 다음 예약 슬라이더를 사용하여 이 가상 머신에 예약된 MB를 조정합니다.


. *확인*을 클릭합니다.
. 동일한 VM 호스트에 호스팅된 다른 가상 머신에 대해서도 필요에 따라 반복합니다.




== 임시 설치 비밀번호가 비활성화되었습니다.

VMware 노드를 배포할 때 선택적으로 임시 설치 비밀번호를 지정할 수 있습니다.  새 노드가 그리드에 가입하기 전에 VM 콘솔에 액세스하거나 SSH를 사용하려면 이 비밀번호가 필요합니다.

임시 설치 비밀번호를 비활성화하도록 선택한 경우 설치 문제를 디버깅하기 위해 추가 단계를 수행해야 합니다.

다음 중 하나를 수행할 수 있습니다.

* VM을 다시 배포하지만 콘솔에 액세스하거나 SSH를 사용하여 설치 문제를 디버깅할 수 있도록 임시 설치 암호를 지정합니다.
* vCenter를 사용하여 비밀번호를 설정하세요.
+
.. VM의 전원을 끕니다.
.. *VM*으로 이동하여 *구성* 탭을 선택하고 *vApp 옵션*을 선택합니다.
.. 설정할 임시 설치 암호 유형을 지정하세요:
+
*** 사용자 지정 임시 비밀번호를 설정하려면 *CUSTOM_TEMPORARY_PASSWORD*를 선택하세요.
*** 노드 이름을 임시 비밀번호로 사용하려면 *TEMPORARY_PASSWORD_TYPE*을 선택하세요.


.. *값 설정*을 선택하세요.
.. 임시 비밀번호를 설정하세요:
+
*** *CUSTOM_TEMPORARY_PASSWORD*를 사용자 지정 비밀번호 값으로 변경합니다.
*** *TEMPORARY_PASSWORD_TYPE*을 *노드 이름 사용* 값으로 업데이트합니다.


.. 새 비밀번호를 적용하려면 VM을 다시 시작하세요.



