---
permalink: rhel/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: 각 호스트에 블록 스토리지 볼륨을 할당해야 합니다. 
---
= 호스트 스토리지 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 호스트에 블록 스토리지 볼륨을 할당해야 합니다.

.시작하기 전에
다음 항목을 검토했으며, 이 항목에서는 이 작업을 수행하는 데 필요한 정보를 제공합니다.

* link:storage-and-performance-requirements.html["저장 및 성능 요구 사항"]
* link:node-container-migration-requirements.html["노드 컨테이너 마이그레이션 요구 사항"]


.이 작업에 관하여
호스트에 블록 스토리지 볼륨(LUN)을 할당할 때 "스토리지 요구 사항"의 표를 사용하여 다음 사항을 확인하세요.

* 각 호스트에 필요한 볼륨 수(해당 호스트에 배포될 노드의 수와 유형에 따라 다름)
* 각 볼륨에 대한 저장 범주(즉, 시스템 데이터 또는 개체 데이터)
* 각 권의 크기


호스트에 StorageGRID 노드를 배포할 때 이 정보와 Linux가 각 물리적 볼륨에 할당한 영구 이름을 사용합니다.


NOTE: 이러한 볼륨을 분할, 포맷 또는 마운트할 필요는 없습니다. 호스트에서 볼 수 있도록 하기만 하면 됩니다.


NOTE: 메타데이터 전용 스토리지 노드에는 개체 데이터 LUN이 하나만 필요합니다.

"원시" 특수 장치 파일 사용을 피하세요(`/dev/sdb` 예를 들어 볼륨 이름 목록을 작성할 때.  이러한 파일은 호스트를 재부팅할 때마다 변경될 수 있으며, 이는 시스템의 적절한 작동에 영향을 미칩니다.  iSCSI LUN 및 Device Mapper Multipathing을 사용하는 경우 다중 경로 별칭을 사용하는 것이 좋습니다. `/dev/mapper` 특히 SAN 토폴로지에 공유 스토리지에 대한 중복 네트워크 경로가 포함된 경우 디렉토리가 필요합니다.  또는 시스템에서 생성한 소프트링크를 사용할 수 있습니다. `/dev/disk/by-path/` 영구적인 장치 이름을 위해.

예를 들어:

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
각 설치마다 결과가 다릅니다.

이러한 각 블록 스토리지 볼륨에 친숙한 이름을 지정하면 초기 StorageGRID 설치와 향후 유지 관리 절차가 간소화됩니다.  공유 스토리지 볼륨에 대한 중복 액세스를 위해 장치 매퍼 멀티패스 드라이버를 사용하는 경우 다음을 사용할 수 있습니다. `alias` 당신의 필드 `/etc/multipath.conf` 파일.

예를 들어:

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
이런 방식으로 별칭 필드를 사용하면 별칭이 블록 장치로 나타납니다. `/dev/mapper` 호스트의 디렉토리를 사용하면 구성이나 유지 관리 작업에서 블록 스토리지 볼륨을 지정해야 할 때마다 친숙하고 쉽게 검증할 수 있는 이름을 지정할 수 있습니다.


NOTE: StorageGRID 노드 마이그레이션을 지원하기 위해 공유 스토리지를 설정하고 Device Mapper Multipathing을 사용하는 경우 공통을 생성하고 설치할 수 있습니다. `/etc/multipath.conf` 모든 공동 배치 호스트에서.  각 호스트에서 다른 컨테이너 엔진 스토리지 볼륨을 사용해야 합니다.  별칭을 사용하고 각 컨테이너 엔진 스토리지 볼륨 LUN에 대한 별칭에 대상 호스트 이름을 포함하면 기억하기 쉬워지므로 권장됩니다.


NOTE: 소프트웨어 전용 배포를 위한 컨테이너 엔진으로 Docker에 대한 지원이 더 이상 제공되지 않습니다. Docker는 향후 릴리스에서 다른 컨테이너 엔진으로 대체될 예정입니다.

.관련 정보
link:configuring-docker-storage-volume.html["컨테이너 엔진 스토리지 볼륨 구성"]
