---
permalink: rhel/creating-node-configuration-files.html 
sidebar: sidebar 
keywords: how to create red hat linux node configuration files, port, remap, port remap 
summary: 노드 구성 파일은 StorageGRID 호스트 서비스가 노드를 시작하고 적절한 네트워크 및 블록 스토리지 리소스에 연결하는 데 필요한 정보를 제공하는 작은 텍스트 파일입니다.  노드 구성 파일은 가상 노드에 사용되며 어플라이언스 노드에는 사용되지 않습니다. 
---
= Red Hat Enterprise Linux 배포를 위한 노드 구성 파일 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 구성 파일은 StorageGRID 호스트 서비스가 노드를 시작하고 적절한 네트워크 및 블록 스토리지 리소스에 연결하는 데 필요한 정보를 제공하는 작은 텍스트 파일입니다.  노드 구성 파일은 가상 노드에 사용되며 어플라이언스 노드에는 사용되지 않습니다.



== 노드 구성 파일의 위치

각 StorageGRID 노드에 대한 구성 파일을 다음 위치에 두십시오. `/etc/storagegrid/nodes` 노드가 실행될 호스트의 디렉토리입니다.  예를 들어 HostA에서 하나의 관리 노드, 하나의 게이트웨이 노드 및 하나의 스토리지 노드를 실행하려는 경우 세 개의 노드 구성 파일을 배치해야 합니다. `/etc/storagegrid/nodes` HostA에서.

vim이나 nano와 같은 텍스트 편집기를 사용하여 각 호스트에 직접 구성 파일을 만들 수도 있고, 다른 곳에서 구성 파일을 만들어 각 호스트로 옮길 수도 있습니다.



== 노드 구성 파일 이름 지정

구성 파일의 이름은 중요합니다.  형식은 다음과 같습니다 `node-name.conf` , 어디 `node-name` 는 노드에 지정하는 이름입니다.  이 이름은 StorageGRID 설치 프로그램에 나타나며 노드 마이그레이션과 같은 노드 유지 관리 작업에 사용됩니다.

노드 이름은 다음 규칙을 따라야 합니다.

* 고유해야 합니다
* 문자로 시작해야 합니다
* A부터 Z까지, a부터 z까지의 문자를 포함할 수 있습니다.
* 0부터 9까지의 숫자를 포함할 수 있습니다.
* 하나 이상의 하이픈(-)을 포함할 수 있습니다.
* 32자를 넘지 않아야 합니다. `.conf` 확대


모든 파일 `/etc/storagegrid/nodes` 이러한 명명 규칙을 따르지 않는 항목은 호스트 서비스에서 구문 분석되지 않습니다.

그리드에 다중 사이트 토폴로지를 계획한 경우 일반적인 노드 명명 체계는 다음과 같습니다.

`site-nodetype-nodenumber.conf`

예를 들어 다음을 사용할 수 있습니다. `dc1-adm1.conf` 데이터 센터 1의 첫 번째 관리 노드의 경우 `dc2-sn3.conf` 데이터 센터 2의 세 번째 스토리지 노드용입니다.  하지만 모든 노드 이름이 명명 규칙을 따르는 한 원하는 방식을 사용할 수 있습니다.



== 노드 구성 파일의 내용

구성 파일에는 키/값 쌍이 들어 있으며, 한 줄에 키 하나와 값 하나가 들어 있습니다.  각 키/값 쌍에 대해 다음 규칙을 따르세요.

* 키와 값은 등호로 구분해야 합니다.(`=` ) 및 선택적 공백.
* 키에는 공백이 포함될 수 없습니다.
* 값에는 공백이 포함될 수 있습니다.
* 앞뒤의 공백은 무시됩니다.


다음 표는 지원되는 모든 키의 값을 정의합니다.  각 키에는 다음 지정 중 하나가 있습니다.

* *필수*: 모든 노드 또는 지정된 노드 유형에 필요합니다.
* *모범 사례*: 선택 사항이지만 권장됨
* *선택 사항*: 모든 노드에 대한 선택 사항




=== 관리자 네트워크 키



==== 관리자_IP

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
그리드 네트워크 이 노드가 속한 그리드의 기본 관리 노드의 IPv4 주소입니다.  NODE_TYPE = VM_Admin_Node, ADMIN_ROLE = Primary인 그리드 노드의 GRID_NETWORK_IP에 지정한 것과 동일한 값을 사용합니다. 이 매개변수를 생략하면 노드는 mDNS를 사용하여 기본 관리 노드를 검색하려고 시도합니다.

link:how-grid-nodes-discover-primary-admin-node.html["그리드 노드가 기본 관리 노드를 검색하는 방법"]

*참고*: 이 값은 무시되며, 기본 관리 노드에서는 금지될 수 있습니다.
 a| 
모범 사례

|===


==== 관리자_네트워크_구성

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
DHCP, STATIC 또는 DISABLED
 a| 
선택 과목

|===


==== 관리자_네트워크_ESL

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
이 노드가 관리 네트워크 게이트웨이를 사용하여 통신해야 하는 CIDR 표기법의 서브넷을 쉼표로 구분한 목록입니다.

예: `172.16.0.0/21,172.17.0.0/21`
 a| 
선택 과목

|===


==== 관리자 네트워크 게이트웨이

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
이 노드의 로컬 관리 네트워크 게이트웨이의 IPv4 주소입니다.  ADMIN_NETWORK_IP 및 ADMIN_NETWORK_MASK로 정의된 서브넷에 있어야 합니다.  DHCP로 구성된 네트워크에서는 이 값이 무시됩니다.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
필요한 경우 `ADMIN_NETWORK_ESL` 지정되어 있습니다.  그 외에는 선택 사항입니다.

|===


==== 관리자_네트워크_IP

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
관리 네트워크에서 이 노드의 IPv4 주소입니다.  이 키는 ADMIN_NETWORK_CONFIG = STATIC인 경우에만 필요합니다. 다른 값에는 지정하지 마세요.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
ADMIN_NETWORK_CONFIG = STATIC인 경우 필요합니다.

그 외에는 선택 사항입니다.

|===


==== 관리자_네트워크_MAC

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
컨테이너의 관리 네트워크 인터페이스에 대한 MAC 주소입니다.

이 필드는 선택 사항입니다.  생략하면 MAC 주소가 자동으로 생성됩니다.

콜론으로 구분된 6쌍의 16진수 숫자여야 합니다.

예: `b2:9c:02:c2:27:10`
 a| 
선택 과목

|===


==== 관리자 네트워크 마스크

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
관리 네트워크의 이 노드에 대한 IPv4 넷마스크입니다.  ADMIN_NETWORK_CONFIG = STATIC인 경우 이 키를 지정하세요. 다른 값에는 지정하지 마세요.

예:

`255.255.255.0`

`255.255.248.0`
 a| 
ADMIN_NETWORK_IP가 지정되고 ADMIN_NETWORK_CONFIG = STATIC인 경우 필요합니다.

그 외에는 선택 사항입니다.

|===


==== 관리자_네트워크_MTU

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
관리 네트워크에서 이 노드의 최대 전송 단위(MTU)입니다.  ADMIN_NETWORK_CONFIG = DHCP인 경우 지정하지 마세요.  지정된 경우 값은 1280~9216 사이여야 합니다.  생략하면 1500이 사용됩니다.

점보 프레임을 사용하려면 MTU를 점보 프레임에 적합한 값(예: 9000)으로 설정하세요.  그렇지 않으면 기본값을 유지합니다.

*중요*: 네트워크의 MTU 값은 노드가 연결된 스위치 포트에 구성된 값과 일치해야 합니다.  그렇지 않으면 네트워크 성능 문제나 패킷 손실이 발생할 수 있습니다.

예:

`1500`

`8192`
 a| 
선택 과목

|===


==== 관리자_네트워크_대상

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
StorageGRID 노드에서 관리자 네트워크에 액세스하는 데 사용할 호스트 장치의 이름입니다.  네트워크 인터페이스 이름만 지원됩니다.  일반적으로 GRID_NETWORK_TARGET 또는 CLIENT_NETWORK_TARGET에 지정된 것과 다른 인터페이스 이름을 사용합니다.

*참고*: 본드나 브리지 장치를 네트워크 대상으로 사용하지 마세요.  본드 장치 위에 VLAN(또는 다른 가상 인터페이스)을 구성하거나 브리지와 가상 이더넷(veth) 쌍을 사용합니다.

*모범 사례*: 이 노드에 처음에 관리자 네트워크 IP 주소가 없더라도 값을 지정합니다.  그러면 나중에 호스트에서 노드를 다시 구성하지 않고도 관리자 네트워크 IP 주소를 추가할 수 있습니다.

예:

`bond0.1002`

`ens256`
 a| 
모범 사례

|===


==== 관리자_네트워크_대상_유형

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
인터페이스(이것은 유일하게 지원되는 값입니다.)
 a| 
선택 과목

|===


==== 관리자_네트워크_대상_유형_인터페이스_클론_맥

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
참 또는 거짓

StorageGRID 컨테이너가 관리 네트워크의 호스트 대상 인터페이스의 MAC 주소를 사용하도록 하려면 키를 "true"로 설정합니다.

*모범 사례:* 무차별 모드가 필요한 네트워크에서는 대신 ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC 키를 사용하세요.

MAC 클로닝에 대한 자세한 내용은 다음을 참조하세요.

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 주소 복제를 위한 고려 사항 및 권장 사항(Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 주소 복제에 대한 고려 사항 및 권장 사항(Ubuntu 또는 Debian)"]

 a| 
모범 사례

|===


==== 관리자 역할

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
1차 또는 비1차

이 키는 NODE_TYPE = VM_Admin_Node인 경우에만 필요합니다. 다른 노드 유형에는 지정하지 마세요.
 a| 
NODE_TYPE = VM_Admin_Node인 경우 필요합니다.

그 외에는 선택 사항입니다.

|===


=== 블록 장치 키



==== 블록 장치 감사 로그

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
이 노드가 감사 로그를 영구적으로 저장하는 데 사용할 블록 장치 특수 파일의 경로와 이름입니다.

예:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
NODE_TYPE = VM_Admin_Node인 노드에 필요합니다.  다른 노드 유형에는 지정하지 마세요.

|===


==== 블록_장치_범위_db_nnn

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
이 노드가 영구 개체 저장소에 사용할 블록 장치 특수 파일의 경로와 이름입니다.  이 키는 NODE_TYPE = VM_Storage_Node인 노드에만 필요합니다. 다른 노드 유형에는 지정하지 마세요.

BLOCK_DEVICE_RANGEDB_000만 필수이고 나머지는 선택 사항입니다.  BLOCK_DEVICE_RANGEDB_000에 지정된 블록 장치는 최소 4TB여야 합니다. 다른 장치는 더 작을 수 있습니다.

틈을 두지 마세요.  BLOCK_DEVICE_RANGEDB_005를 지정하는 경우 BLOCK_DEVICE_RANGEDB_004도 지정해야 합니다.

*참고*: 기존 배포와의 호환성을 위해 업그레이드된 노드에는 2자리 키가 지원됩니다.

예:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
필수의:

BLOCK_DEVICE_RANGEDB_000

선택 과목:

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== 블록 장치 테이블

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
이 노드가 데이터베이스 테이블의 영구 저장에 사용할 블록 장치 특수 파일의 경로와 이름입니다.  이 키는 NODE_TYPE = VM_Admin_Node인 노드에만 필요합니다. 다른 노드 유형에는 지정하지 마세요.

예:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
필수의

|===


==== 블록 장치 변수 로컬

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
이 노드가 사용할 블록 장치 특수 파일의 경로 및 이름 `/var/local` 영구 저장소.

예:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
필수의

|===


=== 클라이언트 네트워크 키



==== 클라이언트_네트워크_구성

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
DHCP, STATIC 또는 DISABLED
 a| 
선택 과목

|===


==== 클라이언트 네트워크 게이트웨이

[cols="4a,2a"]
|===


 a| 
가치
 a| 
지정



 a| 
이 노드에 대한 로컬 클라이언트 네트워크 게이트웨이의 IPv4 주소입니다. 이 주소는 CLIENT_NETWORK_IP 및 CLIENT_NETWORK_MASK로 정의된 서브넷에 있어야 합니다.  DHCP로 구성된 네트워크에서는 이 값이 무시됩니다.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
선택 과목

|===


==== 클라이언트_네트워크_IP

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
클라이언트 네트워크에서 이 노드의 IPv4 주소입니다.

이 키는 CLIENT_NETWORK_CONFIG = STATIC인 경우에만 필요합니다. 다른 값에는 지정하지 마세요.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
CLIENT_NETWORK_CONFIG = STATIC인 경우 필요합니다.

그 외에는 선택 사항입니다.

|===


==== 클라이언트_네트워크_MAC

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
컨테이너의 클라이언트 네트워크 인터페이스에 대한 MAC 주소입니다.

이 필드는 선택 사항입니다.  생략하면 MAC 주소가 자동으로 생성됩니다.

콜론으로 구분된 6쌍의 16진수 숫자여야 합니다.

예: `b2:9c:02:c2:27:20`
 a| 
선택 과목

|===


==== 클라이언트 네트워크 마스크

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
클라이언트 네트워크의 이 노드에 대한 IPv4 넷마스크입니다.

CLIENT_NETWORK_CONFIG = STATIC인 경우 이 키를 지정하세요. 다른 값에는 지정하지 마세요.

예:

`255.255.255.0`

`255.255.248.0`
 a| 
CLIENT_NETWORK_IP가 지정되고 CLIENT_NETWORK_CONFIG = STATIC인 경우 필요합니다.

그 외에는 선택 사항입니다.

|===


==== 클라이언트_네트워크_MTU

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
클라이언트 네트워크에서 이 노드의 최대 전송 단위(MTU)입니다.  CLIENT_NETWORK_CONFIG = DHCP인 경우 지정하지 마세요.  지정된 경우 값은 1280~9216 사이여야 합니다.  생략하면 1500이 사용됩니다.

점보 프레임을 사용하려면 MTU를 점보 프레임에 적합한 값(예: 9000)으로 설정하세요.  그렇지 않으면 기본값을 유지합니다.

*중요*: 네트워크의 MTU 값은 노드가 연결된 스위치 포트에 구성된 값과 일치해야 합니다.  그렇지 않으면 네트워크 성능 문제나 패킷 손실이 발생할 수 있습니다.

예:

`1500`

`8192`
 a| 
선택 과목

|===


==== 클라이언트_네트워크_대상

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
StorageGRID 노드에서 클라이언트 네트워크에 액세스하는 데 사용할 호스트 장치의 이름입니다.  네트워크 인터페이스 이름만 지원됩니다.  일반적으로 GRID_NETWORK_TARGET 또는 ADMIN_NETWORK_TARGET에 지정된 것과 다른 인터페이스 이름을 사용합니다.

*참고*: 본드나 브리지 장치를 네트워크 대상으로 사용하지 마세요.  본드 장치 위에 VLAN(또는 다른 가상 인터페이스)을 구성하거나 브리지와 가상 이더넷(veth) 쌍을 사용합니다.

*모범 사례:* 이 노드에 처음에는 클라이언트 네트워크 IP 주소가 없더라도 값을 지정합니다.  그러면 나중에 호스트의 노드를 다시 구성하지 않고도 클라이언트 네트워크 IP 주소를 추가할 수 있습니다.

예:

`bond0.1003`

`ens423`
 a| 
모범 사례

|===


==== 클라이언트_네트워크_대상_유형

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
인터페이스(이것은 지원되는 값입니다.)
 a| 
선택 과목

|===


==== 클라이언트_네트워크_대상_유형_인터페이스_클론_맥

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
참 또는 거짓

StorageGRID 컨테이너가 클라이언트 네트워크의 호스트 대상 인터페이스의 MAC 주소를 사용하도록 하려면 키를 "true"로 설정합니다.

*모범 사례:* 무차별 모드가 필요한 네트워크에서는 대신 CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC 키를 사용하세요.

MAC 클로닝에 대한 자세한 내용은 다음을 참조하세요.

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 주소 복제를 위한 고려 사항 및 권장 사항(Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 주소 복제에 대한 고려 사항 및 권장 사항(Ubuntu 또는 Debian)"]

 a| 
모범 사례

|===


=== 그리드 네트워크 키



==== 그리드 네트워크 구성

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
정적 또는 DHCP

지정하지 않으면 기본값은 STATIC입니다.
 a| 
모범 사례

|===


==== 그리드 네트워크 게이트웨이

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
이 노드에 대한 로컬 Grid Network 게이트웨이의 IPv4 주소입니다. 이 주소는 GRID_NETWORK_IP 및 GRID_NETWORK_MASK로 정의된 서브넷에 있어야 합니다.  DHCP로 구성된 네트워크에서는 이 값이 무시됩니다.

Grid Network가 게이트웨이가 없는 단일 서브넷인 경우 서브넷(XYZ1)의 표준 게이트웨이 주소나 이 노드의 GRID_NETWORK_IP 값을 사용하세요. 두 값 모두 향후 Grid Network 확장을 간소화하는 데 도움이 됩니다.
 a| 
필수의

|===


==== 그리드 네트워크 IP

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
그리드 네트워크에서 이 노드의 IPv4 주소입니다.  이 키는 GRID_NETWORK_CONFIG = STATIC인 경우에만 필요합니다. 다른 값에는 지정하지 마세요.

예:

`1.1.1.1`

`10.224.4.81`
 a| 
GRID_NETWORK_CONFIG = STATIC인 경우 필요합니다.

그 외에는 선택 사항입니다.

|===


==== 그리드_네트워크_맥

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
컨테이너의 Grid Network 인터페이스에 대한 MAC 주소입니다.

콜론으로 구분된 6쌍의 16진수 숫자여야 합니다.

예: `b2:9c:02:c2:27:30`
 a| 
선택 과목

생략하면 MAC 주소가 자동으로 생성됩니다.

|===


==== 그리드 네트워크 마스크

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
그리드 네트워크의 이 노드에 대한 IPv4 넷마스크입니다.  GRID_NETWORK_CONFIG = STATIC인 경우 이 키를 지정하세요. 다른 값에는 지정하지 마세요.

예:

`255.255.255.0`

`255.255.248.0`
 a| 
GRID_NETWORK_IP가 지정되고 GRID_NETWORK_CONFIG = STATIC인 경우 필요합니다.

그 외에는 선택 사항입니다.

|===


==== 그리드 네트워크 MTU

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
그리드 네트워크에서 이 노드의 최대 전송 단위(MTU)입니다.  GRID_NETWORK_CONFIG = DHCP인 경우 지정하지 마세요.  지정된 경우 값은 1280~9216 사이여야 합니다.  생략하면 1500이 사용됩니다.

점보 프레임을 사용하려면 MTU를 점보 프레임에 적합한 값(예: 9000)으로 설정하세요.  그렇지 않으면 기본값을 유지합니다.

*중요*: 네트워크의 MTU 값은 노드가 연결된 스위치 포트에 구성된 값과 일치해야 합니다.  그렇지 않으면 네트워크 성능 문제나 패킷 손실이 발생할 수 있습니다.

*중요*: 최상의 네트워크 성능을 위해서는 모든 노드가 Grid Network 인터페이스에서 유사한 MTU 값으로 구성되어야 합니다.  *그리드 네트워크 MTU 불일치* 경고는 개별 노드의 그리드 네트워크에 대한 MTU 설정에 상당한 차이가 있는 경우 발생합니다.  MTU 값은 모든 네트워크 유형에서 동일할 필요는 없습니다.

예:

`1500`

`8192`
 a| 
선택 과목

|===


==== 그리드 네트워크 대상

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
StorageGRID 노드에서 Grid Network에 액세스하는 데 사용할 호스트 장치의 이름입니다.  네트워크 인터페이스 이름만 지원됩니다.  일반적으로 ADMIN_NETWORK_TARGET 또는 CLIENT_NETWORK_TARGET에 지정된 것과 다른 인터페이스 이름을 사용합니다.

*참고*: 본드나 브리지 장치를 네트워크 대상으로 사용하지 마세요.  본드 장치 위에 VLAN(또는 다른 가상 인터페이스)을 구성하거나 브리지와 가상 이더넷(veth) 쌍을 사용합니다.

예:

`bond0.1001`

`ens192`
 a| 
필수의

|===


==== 그리드 네트워크 대상 유형

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
인터페이스(이것은 유일하게 지원되는 값입니다.)
 a| 
선택 과목

|===


==== 그리드 네트워크 대상 유형 인터페이스 클론 MAC

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
참 또는 거짓

StorageGRID 컨테이너가 Grid Network의 호스트 대상 인터페이스의 MAC 주소를 사용하도록 하려면 키 값을 "true"로 설정합니다.

*모범 사례:* 무차별 모드가 필요한 네트워크에서는 대신 GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC 키를 사용하세요.

MAC 클로닝에 대한 자세한 내용은 다음을 참조하세요.

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 주소 복제를 위한 고려 사항 및 권장 사항(Red Hat Enterprise Linux)"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 주소 복제에 대한 고려 사항 및 권장 사항(Ubuntu 또는 Debian)"]

 a| 
모범 사례

|===


=== 설치 비밀번호 키(임시)



==== 사용자 지정 임시 비밀번호 해시

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
기본 관리 노드의 경우 설치 중에 StorageGRID 설치 API에 대한 기본 임시 비밀번호를 설정합니다.

*참고*: 기본 관리 노드에만 설치 비밀번호를 설정하세요.  다른 노드 유형에 비밀번호를 설정하려고 하면 노드 구성 파일의 유효성 검사가 실패합니다.

설치가 완료되면 이 값을 설정해도 효과가 없습니다.

이 키가 생략되면 기본적으로 임시 비밀번호가 설정되지 않습니다.  또는 StorageGRID 설치 API를 사용하여 임시 비밀번호를 설정할 수 있습니다.

반드시 있어야 합니다 `crypt()` SHA-512 비밀번호 해시 형식 `$6$<salt>$<password hash>` 비밀번호는 최소 8자, 최대 32자입니다.

이 해시는 다음과 같은 CLI 도구를 사용하여 생성할 수 있습니다. `openssl passwd` SHA-512 모드의 명령.
 a| 
모범 사례

|===


=== 인터페이스 키



==== 인터페이스_대상_nnnn

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
이 노드에 추가하려는 추가 인터페이스의 이름과 설명(선택 사항)입니다.  각 노드에 여러 개의 추가 인터페이스를 추가할 수 있습니다.

_nnnn_의 경우, 추가하는 각 INTERFACE_TARGET 항목에 대해 고유한 번호를 지정합니다.

값의 경우 베어 메탈 호스트의 물리적 인터페이스 이름을 지정합니다.  그런 다음 선택적으로 쉼표를 추가하고 VLAN 인터페이스 페이지와 HA 그룹 페이지에 표시되는 인터페이스에 대한 설명을 제공합니다.

예: `INTERFACE_TARGET_0001=ens256, Trunk`

트렁크 인터페이스를 추가하는 경우 StorageGRID 에서 VLAN 인터페이스를 구성해야 합니다.  액세스 인터페이스를 추가하면 HA 그룹에 인터페이스를 직접 추가할 수 있으며 VLAN 인터페이스를 구성할 필요가 없습니다.
 a| 
선택 과목

|===


=== 최대 RAM 키



==== 최대 RAM

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
이 노드가 사용할 수 있는 최대 RAM 양입니다.  이 키가 생략되면 노드에 메모리 제한이 없습니다.  프로덕션 수준 노드에 대해 이 필드를 설정할 때 최소 24GB, 전체 시스템 RAM보다 16~32GB 적은 값을 지정하세요.

*참고*: RAM 값은 노드의 실제 메타데이터 예약 공간에 영향을 미칩니다. 를 참조하십시오link:../admin/managing-object-metadata-storage.html["메타데이터 예약 공간이 무엇인지에 대한 설명"] .

이 필드의 형식은 다음과 같습니다. `_numberunit_` , 어디 `_unit_` 될 수 있다 `b` , `k` , `m` , 또는 `g` .

예:

`24g`

`38654705664b`

*참고*: 이 옵션을 사용하려면 메모리 cgroup에 대한 커널 지원을 활성화해야 합니다.
 a| 
선택 과목

|===


=== 노드 유형 키



==== 노드 유형

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
노드 유형:

* VM_관리_노드
* VM_스토리지_노드
* VM_아카이브_노드
* VM_API_게이트웨이

 a| 
필수의

|===


==== 저장 유형

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
저장 노드에 포함된 객체의 유형을 정의합니다. 자세한 내용은 다음을 참조하세요. link:../primer/what-storage-node-is.html#types-of-storage-nodes["저장 노드 유형"] .  이 키는 NODE_TYPE = VM_Storage_Node인 노드에만 필요합니다. 다른 노드 유형에는 지정하지 마세요.  저장 유형:

* 결합된
* 데이터
* 메타데이터


*참고*: STORAGE_TYPE이 지정되지 않으면 기본적으로 스토리지 노드 유형이 결합(데이터 및 메타데이터)으로 설정됩니다.
 a| 
선택 과목

|===


=== 포트 리맵 키



==== 포트 리맵

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
내부 그리드 노드 통신이나 외부 통신에 사용되는 모든 포트를 다시 매핑합니다.  StorageGRID 에서 사용하는 하나 이상의 포트를 제한하는 엔터프라이즈 네트워킹 정책이 있는 경우 포트를 다시 매핑해야 합니다.link:../network/internal-grid-node-communications.html["내부 그리드 노드 통신"] 또는link:../network/external-communications.html["외부 커뮤니케이션"] .

*중요*: 로드 밸런서 엔드포인트를 구성하는 데 사용할 포트를 다시 매핑하지 마세요.

*참고*: PORT_REMAP만 설정된 경우, 지정한 매핑이 인바운드 및 아웃바운드 통신 모두에 사용됩니다.  PORT_REMAP_INBOUND도 지정된 경우 PORT_REMAP은 아웃바운드 통신에만 적용됩니다.

사용된 형식은 다음과 같습니다. `_network type_/_protocol_/_default port used by grid node_/_new port_` , 어디 `_network type_` 그리드, 관리자 또는 클라이언트이며 `_protocol_` tcp인가 udp인가.

예: `PORT_REMAP = client/tcp/18082/443`

쉼표로 구분된 목록을 사용하여 여러 포트를 다시 매핑할 수도 있습니다.

예: `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
선택 과목

|===


==== 포트_재맵_인바운드

[cols="4a,2a"]
|===
| 가치 | 지정 


 a| 
지정된 포트로 들어오는 통신을 다시 매핑합니다.  PORT_REMAP_INBOUND를 지정했지만 PORT_REMAP에 대한 값을 지정하지 않으면 해당 포트의 아웃바운드 통신은 변경되지 않습니다.

*중요*: 로드 밸런서 엔드포인트를 구성하는 데 사용할 포트를 다시 매핑하지 마세요.

사용된 형식은 다음과 같습니다. `_network type_/_protocol_/_remapped port_/_default port used by grid node_` , 어디 `_network type_` 그리드, 관리자 또는 클라이언트이며 `_protocol_` tcp인가 udp인가.

예: `PORT_REMAP_INBOUND = grid/tcp/3022/22`

쉼표로 구분된 목록을 사용하여 여러 개의 인바운드 포트를 다시 매핑할 수도 있습니다.

예: `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
선택 과목

|===