---
permalink: rhel/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: 가상 머신을 사용하면 모든 유형의 StorageGRID 노드를 호스팅할 수 있습니다.  각 그리드 노드마다 하나의 가상 머신이 필요합니다. 
---
= Red Hat Enterprise Linux 소프트웨어 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 머신을 사용하면 모든 유형의 StorageGRID 노드를 호스팅할 수 있습니다.  각 그리드 노드마다 하나의 가상 머신이 필요합니다.

Red Hat Enterprise Linux(RHEL)에 StorageGRID 설치하려면 일부 타사 소프트웨어 패키지를 설치해야 합니다. 일부 지원되는 Linux 배포판에는 기본적으로 이러한 패키지가 포함되어 있지 않습니다. StorageGRID 설치가 테스트된 소프트웨어 패키지 버전은 이 페이지에 나열된 버전을 포함합니다.

이러한 패키지 중 하나가 필요한 Linux 배포판 및 컨테이너 런타임 설치 옵션을 선택하고 Linux 배포판에서 자동으로 설치되지 않은 경우, 공급업체나 Linux 배포판 지원 공급업체에서 제공하는 경우 여기에 나열된 버전 중 하나를 설치하세요.  그렇지 않은 경우 공급업체에서 제공하는 기본 패키지 버전을 사용하세요.

모든 설치 옵션에는 Podman 또는 Docker가 필요합니다.  두 패키지를 모두 설치하지 마세요.  설치 옵션에 필요한 패키지만 설치하세요.


NOTE: 소프트웨어 전용 배포를 위한 컨테이너 엔진으로 Docker에 대한 지원이 더 이상 제공되지 않습니다. Docker는 향후 릴리스에서 다른 컨테이너 엔진으로 대체될 예정입니다.



== 테스트된 Python 버전

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3.8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




== 테스트된 Podman 버전

* 3.2.3-0
* 3.4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4.3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12




== 테스트된 Docker 버전


IMPORTANT: Docker 지원은 더 이상 제공되지 않으며 향후 릴리스에서 제거될 예정입니다.

* 도커-CE 20.10.7
* 도커-CE 20.10.20-3
* 도커-CE 23.0.6-1
* 도커-CE 24.0.2-1
* 도커-CE 24.0.4-1
* 도커-CE 24.0.5-1
* 도커-CE 24.0.7-1
* 1.5-2

