---
permalink: admin/changing-network-options-object-encryption.html 
sidebar: sidebar 
keywords: enable http, storage node connections 
summary: 네트워크 및 개체 보안을 구성하여 저장된 개체를 암호화하고, 특정 S3 요청을 차단하거나, 클라이언트가 스토리지 노드에 연결할 때 HTTPS 대신 HTTP를 사용하도록 허용할 수 있습니다. 
---
= 네트워크 및 개체 보안 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크 및 개체 보안을 구성하여 저장된 개체를 암호화하고, 특정 S3 요청을 차단하거나, 클라이언트가 스토리지 노드에 연결할 때 HTTPS 대신 HTTP를 사용하도록 허용할 수 있습니다.



== 저장된 객체 암호화

저장된 객체 암호화를 사용하면 S3를 통해 수집되는 모든 객체 데이터를 암호화할 수 있습니다.  기본적으로 저장된 객체는 암호화되지 않지만 AES-128 또는 AES-256 암호화 알고리즘을 사용하여 객체를 암호화하도록 선택할 수 있습니다.  해당 설정을 활성화하면 새로 수집된 모든 개체가 암호화되지만 기존에 저장된 개체에는 변경 사항이 적용되지 않습니다.  암호화를 비활성화하면 현재 암호화된 개체는 암호화된 상태로 유지되지만 새로 수집된 개체는 암호화되지 않습니다.

저장된 개체 암호화 설정은 버킷 수준 또는 개체 수준 암호화로 암호화되지 않은 S3 개체에만 적용됩니다.

StorageGRID 암호화 방법에 대한 자세한 내용은 다음을 참조하세요.link:../admin/reviewing-storagegrid-encryption-methods.html["StorageGRID 암호화 방법 검토"] .



== 클라이언트 수정 방지

클라이언트 수정 방지는 시스템 전체 설정입니다.  *클라이언트 수정 방지* 옵션을 선택하면 다음 요청이 거부됩니다.



=== S3 REST API

* DeleteBucket 요청
* 기존 객체의 데이터, 사용자 정의 메타데이터 또는 S3 객체 태깅을 수정하려는 모든 요청




== 스토리지 노드 연결에 HTTP 활성화

기본적으로 클라이언트 애플리케이션은 스토리지 노드에 직접 연결하기 위해 HTTPS 네트워크 프로토콜을 사용합니다.  예를 들어, 비생산 그리드를 테스트할 때 이러한 연결에 대해 HTTP를 선택적으로 활성화할 수 있습니다.

S3 클라이언트가 스토리지 노드에 직접 HTTP 연결을 해야 하는 경우에만 스토리지 노드 연결에 HTTP를 사용하세요.  HTTPS 연결만 사용하는 클라이언트나 로드 밸런서 서비스에 연결하는 클라이언트의 경우 이 옵션을 사용할 필요가 없습니다.link:../admin/configuring-load-balancer-endpoints.html["각 로드 밸런서 엔드포인트 구성"] HTTP 또는 HTTPS를 사용하세요).

보다link:summary-ip-addresses-and-ports-for-client-connections.html["요약: 클라이언트 연결을 위한 IP 주소 및 포트"] HTTP 또는 HTTPS를 사용하여 스토리지 노드에 연결할 때 S3 클라이언트가 사용하는 포트를 알아보세요.



== 옵션 선택

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 루트 접근 권한이 있습니다.


.단계
. *구성* > *보안* > *보안 설정*을 선택합니다.
. *네트워크 및 개체* 탭을 선택합니다.
. 저장된 개체 암호화의 경우, 저장된 개체를 암호화하지 않으려면 *없음*(기본값) 설정을 사용하고, 저장된 개체를 암호화하려면 *AES-128* 또는 *AES-256*을 선택합니다.
. 선택적으로 S3 클라이언트가 특정 요청을 하는 것을 방지하려면 *클라이언트 수정 방지*를 선택합니다.
+

NOTE: 이 설정을 변경하면 새로운 설정이 적용되는 데 약 1분이 소요됩니다.  구성된 값은 성능과 확장성을 위해 캐시됩니다.

. 클라이언트가 스토리지 노드에 직접 연결하고 HTTP 연결을 사용하려는 경우 선택적으로 *스토리지 노드 연결에 HTTP 사용*을 선택합니다.
+

NOTE: 프로덕션 그리드에서 HTTP를 활성화할 때는 요청이 암호화되지 않은 상태로 전송되므로 주의하세요.

. *저장*을 선택하세요.

