---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: security, browser inactivity timeout, management API stack track 
summary: 인터페이스 보안 설정을 사용하면 사용자가 지정된 시간 이상 활동이 없을 경우 로그아웃할지 여부와 API 오류 응답에 스택 추적을 포함할지 여부를 제어할 수 있습니다. 
---
= 인터페이스 보안 설정 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
인터페이스 보안 설정을 사용하면 사용자가 지정된 시간 이상 활동이 없을 경우 로그아웃할지 여부와 API 오류 응답에 스택 추적을 포함할지 여부를 제어할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:admin-group-permissions.html["루트 액세스 권한"] .


.이 작업에 관하여
*보안 설정* 페이지에는 *브라우저 비활성 시간 제한* 및 *관리 API 스택 추적* 설정이 포함되어 있습니다.

브라우저 비활성 시간 초과:: 사용자가 로그아웃되기 전까지 사용자 브라우저가 비활성화될 수 있는 시간을 나타냅니다.  기본값은 15분입니다.
+
--
브라우저 비활성 시간 초과는 다음 항목에 의해서도 제어됩니다.

* 시스템 보안을 위해 포함된 별도의 구성 불가능한 StorageGRID 타이머입니다.  각 사용자의 인증 토큰은 사용자가 로그인한 후 16시간 후에 만료됩니다. 사용자 인증이 만료되면 브라우저 비활성 시간 초과가 비활성화되었거나 브라우저 시간 초과 값에 도달하지 않았더라도 해당 사용자는 자동으로 로그아웃됩니다.  토큰을 갱신하려면 사용자가 다시 로그인해야 합니다.
* StorageGRID 에 대해 SSO(Single Sign-On)가 활성화되어 있다고 가정할 때 ID 공급자에 대한 시간 초과 설정입니다.
+
SSO가 활성화되어 있고 사용자 브라우저의 시간이 초과되면 사용자는 StorageGRID 다시 액세스하려면 SSO 자격 증명을 다시 입력해야 합니다. 보다 link:configuring-sso.html["단일 로그인 구성"] .



--
관리 API 스택 추적:: Grid Manager 및 Tenant Manager API 오류 응답에서 스택 추적이 반환되는지 여부를 제어합니다.
+
--
이 옵션은 기본적으로 비활성화되어 있지만 테스트 환경에서는 이 기능을 활성화하는 것이 좋습니다.  일반적으로 API 오류 발생 시 내부 소프트웨어 세부 정보가 노출되는 것을 방지하려면 프로덕션 환경에서 스택 추적을 비활성화해야 합니다.

--


.단계
. *구성* > *보안* > *보안 설정*을 선택합니다.
. *인터페이스* 탭을 선택합니다.
. 브라우저 비활성 시간 초과 설정을 변경하려면:
+
.. 아코디언을 확장합니다.
.. 제한 시간을 변경하려면 60초에서 7일 사이의 값을 지정하세요.  기본 제한 시간은 15분입니다.
.. 이 기능을 비활성화하려면 체크박스의 선택을 취소하세요.
.. *저장*을 선택하세요.
+
새로운 설정은 현재 로그인한 사용자에게는 영향을 미치지 않습니다. 새로운 시간 초과 설정을 적용하려면 사용자는 다시 로그인하거나 브라우저를 새로 고쳐야 합니다.



. 관리 API 스택 추적에 대한 설정을 변경하려면:
+
.. 아코디언을 확장합니다.
.. Grid Manager 및 Tenant Manager API 오류 응답에서 스택 추적을 반환하려면 확인란을 선택하세요.
+

CAUTION: API 오류가 발생할 때 내부 소프트웨어 세부 정보가 노출되는 것을 방지하려면 프로덕션 환경에서 스택 추적을 비활성화된 상태로 두세요.

.. *저장*을 선택하세요.



