---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 그리드의 각 노드에는 고유한 노드 콘솔 비밀번호가 있으며, 이 비밀번호는 노드에 로그인하는 데 필요합니다.  그리드의 각 노드에 대한 노드 콘솔 비밀번호를 변경하려면 다음 단계를 따르세요.  비밀번호는 복구 패키지에 저장됩니다. 
---
= 노드 콘솔 비밀번호 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드의 각 노드에는 고유한 노드 콘솔 비밀번호가 있으며, 이 비밀번호는 노드에 로그인하는 데 필요합니다.  그리드의 각 노드에 대한 고유한 노드 콘솔 비밀번호를 변경하려면 다음 단계를 따르세요.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"] .
* 현재 프로비저닝 암호가 있습니다.


.이 작업에 관하여
SSH를 사용하여 "admin"으로 노드에 로그인하거나 VM/물리적 콘솔 연결에서 루트 사용자로 로그인하려면 노드 콘솔 비밀번호를 사용합니다.  노드 콘솔 비밀번호 변경 프로세스는 그리드의 각 노드에 대해 새 비밀번호를 생성하고 비밀번호를 업데이트된 위치에 저장합니다. `Passwords.txt` 복구 패키지의 파일입니다.  비밀번호는 Passwords.txt 파일의 비밀번호 열에 나열되어 있습니다.


NOTE: 노드 간 통신에 사용되는 SSH 키에는 별도의 SSH 액세스 비밀번호가 있습니다.  이 절차를 통해 SSH 액세스 비밀번호는 변경되지 않습니다.



== 마법사에 접속하세요

.단계
. *구성* > *접근 제어* > *그리드 비밀번호*를 선택합니다.
. *노드 콘솔 비밀번호 변경*에서 *변경*을 선택합니다.




== 프로비저닝 암호를 입력하세요

.단계
. 그리드의 프로비저닝 암호를 입력하세요.
. *계속*을 선택하세요.




== [[download-current]]현재 복구 패키지를 다운로드하세요

노드 콘솔 비밀번호를 변경하기 전에 최신 복구 패키지를 다운로드하세요. 어떤 노드에서든 비밀번호 변경 프로세스가 실패하면 이 파일에 있는 비밀번호를 사용할 수 있습니다.

.단계
. *복구 패키지 다운로드*를 선택하세요.
. 복구 패키지 파일을 복사합니다(`.zip` ) 두 개의 안전하고 보안이 유지되는 별도 장소로 이동합니다.
+

CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 얻는 데 사용할 수 있는 암호화 키와 비밀번호가 포함되어 있으므로 보호되어야 합니다.

. *계속*을 선택하세요.
. 확인 대화 상자가 나타나면 노드 콘솔 비밀번호 변경을 시작할 준비가 되었으면 *예*를 선택하세요.
+
이 프로세스는 시작된 후에는 취소할 수 없습니다.





== 노드 콘솔 비밀번호 변경

노드 콘솔 비밀번호 프로세스가 시작되면 새 비밀번호가 포함된 새 복구 패키지가 생성됩니다.  그런 다음 각 노드에서 비밀번호가 업데이트됩니다.

.단계
. 새로운 복구 패키지가 생성될 때까지 기다리세요. 몇 분 정도 걸릴 수 있습니다.
. *새로운 복구 패키지 다운로드*를 선택하세요.
. 다운로드가 완료되면:
+
.. 열기 `.zip` 파일.
.. 다음을 포함한 콘텐츠에 액세스할 수 있는지 확인하세요. `Passwords.txt` 새로운 노드 콘솔 비밀번호가 포함된 파일입니다.
.. 새로운 복구 패키지 파일을 복사합니다.(`.zip` ) 두 개의 안전하고 보안이 유지되는 별도 장소로 이동합니다.
+

CAUTION: 이전 복구 패키지를 덮어쓰지 마세요.

+
복구 패키지 파일은 StorageGRID 시스템에서 데이터를 얻는 데 사용할 수 있는 암호화 키와 비밀번호가 포함되어 있으므로 보호되어야 합니다.



. 새로운 복구 패키지를 다운로드하고 내용을 확인했음을 나타내려면 확인란을 선택하세요.
. *노드 콘솔 비밀번호 변경*을 선택하고 모든 노드가 새 비밀번호로 업데이트될 때까지 기다립니다.  몇 분 정도 걸릴 수 있습니다.
+
모든 노드의 비밀번호가 변경되면 녹색 성공 배너가 나타납니다.  다음 단계로 넘어가세요.

+
업데이트 과정에서 오류가 발생하면 배너 메시지에 비밀번호 변경에 실패한 노드 수가 나열됩니다. 시스템은 비밀번호 변경에 실패한 모든 노드에서 자동으로 프로세스를 다시 시도합니다. 프로세스가 종료되어 일부 노드의 비밀번호가 변경되지 않은 경우, *다시 시도* 버튼이 나타납니다.

+
하나 이상의 노드에서 비밀번호 업데이트가 실패한 경우:

+
.. 표에 나열된 오류 메시지를 검토하세요.
.. 문제를 해결하세요.
.. *다시 시도*를 선택하세요.
+

NOTE: 다시 시도하면 이전 비밀번호 변경 시도에서 실패한 노드의 노드 콘솔 비밀번호만 변경됩니다.



. 모든 노드의 노드 콘솔 암호가 변경된 후 삭제합니다.<<download-current,처음으로 다운로드한 복구 패키지>> .
. 선택적으로 *복구 패키지* 링크를 사용하여 새로운 복구 패키지의 추가 사본을 다운로드할 수 있습니다.

