---
permalink: admin/configuring-custom-server-certificate-for-grid-manager-tenant-manager.html 
sidebar: sidebar 
keywords: custom certificates, grid manager, tenant manager, management interface certificate 
summary: 기본 StorageGRID 서버 인증서를 단일 사용자 정의 서버 인증서로 교체하면 사용자가 보안 경고를 받지 않고 Grid Manager와 Tenant Manager에 액세스할 수 있습니다.  기본 관리 인터페이스 인증서로 되돌리거나 새 인증서를 생성할 수도 있습니다. 
---
= 관리 인터페이스 인증서 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 관리 인터페이스 인증서를 단일 사용자 정의 인증서로 교체하면 사용자가 보안 경고를 받지 않고 Grid Manager와 Tenant Manager에 액세스할 수 있습니다.  기본 관리 인터페이스 인증서로 되돌리거나 새 인증서를 생성할 수도 있습니다.

.이 작업에 관하여
기본적으로 모든 관리 노드에는 그리드 CA가 서명한 인증서가 발급됩니다.  이러한 CA 서명 인증서는 단일 공통 사용자 정의 관리 인터페이스 인증서와 해당 개인 키로 대체될 수 있습니다.

모든 관리 노드에 단일 사용자 정의 관리 인터페이스 인증서가 사용되므로 클라이언트가 Grid Manager 및 Tenant Manager에 연결할 때 호스트 이름을 확인해야 하는 경우 인증서를 와일드카드 또는 다중 도메인 인증서로 지정해야 합니다.  그리드의 모든 관리 노드와 일치하도록 사용자 정의 인증서를 정의합니다.

서버에서 구성을 완료해야 하며, 사용하는 루트 인증 기관(CA)에 따라 사용자는 Grid Manager와 Tenant Manager에 액세스하는 데 사용할 웹 브라우저에 Grid CA 인증서를 설치해야 할 수도 있습니다.


NOTE: 실패한 서버 인증서로 인해 작업이 중단되지 않도록 하기 위해 이 서버 인증서가 만료되려고 할 때 *관리 인터페이스에 대한 서버 인증서 만료* 알림이 트리거됩니다. 필요에 따라 *구성* > *보안* > *인증서*를 선택하고 글로벌 탭에서 관리 인터페이스 인증서의 만료 날짜를 확인하여 현재 인증서가 만료되는 시기를 확인할 수 있습니다.

[NOTE]
====
IP 주소 대신 도메인 이름을 사용하여 Grid Manager 또는 Tenant Manager에 액세스하는 경우 다음 중 하나가 발생하면 우회 옵션 없이 브라우저에 인증서 오류가 표시됩니다.

* 사용자 정의 관리 인터페이스 인증서가 만료되었습니다.
* 너<<기본 관리 인터페이스 인증서 복원,사용자 정의 관리 인터페이스 인증서에서 기본 서버 인증서로 되돌리기>> .


====


== 사용자 정의 관리 인터페이스 인증서 추가

사용자 정의 관리 인터페이스 인증서를 추가하려면 자체 인증서를 제공하거나 Grid Manager를 사용하여 인증서를 생성할 수 있습니다.

.단계
. *구성* > *보안* > *인증서*를 선택합니다.
. *전역* 탭에서 *관리 인터페이스 인증서*를 선택합니다.
. *사용자 정의 인증서 사용*을 선택하세요.
. 인증서를 업로드하거나 생성합니다.
+
[role="tabbed-block"]
====
.인증서 업로드
--
필요한 서버 인증서 파일을 업로드합니다.

.. *증명서 업로드*를 선택하세요.
.. 필요한 서버 인증서 파일을 업로드하세요.
+
*** *서버 인증서*: 사용자 정의 서버 인증서 파일(PEM 인코딩).
*** *인증서 개인 키*: 사용자 지정 서버 인증서 개인 키 파일(`.key` ).
+

NOTE: EC 개인 키는 224비트 이상이어야 합니다.  RSA 개인 키는 2048비트 이상이어야 합니다.

*** *CA 번들*: 각 중간 발급 인증 기관(CA)의 인증서를 포함하는 단일 선택 파일입니다.  해당 파일에는 PEM으로 인코딩된 CA 인증서 파일이 각각 포함되어 있어야 하며, 인증서 체인 순서대로 연결되어 있어야 합니다.


.. *인증서 세부 정보*를 확장하여 업로드한 각 인증서의 메타데이터를 확인하세요.  선택적 CA 번들을 업로드한 경우 각 인증서가 자체 탭에 표시됩니다.
+
*** 인증서 파일을 저장하려면 *인증서 다운로드*를 선택하고, 인증서 번들을 저장하려면 *CA 번들 다운로드*를 선택합니다.
+
인증서 파일 이름과 다운로드 위치를 지정하세요.  파일을 확장자로 저장하세요 `.pem` .

+
예:  `storagegrid_certificate.pem`

*** 다른 곳에 붙여넣기 위해 인증서 내용을 복사하려면 *인증서 PEM 복사* 또는 *CA 번들 PEM 복사*를 선택하세요.


.. *저장*을 선택하세요. + 사용자 정의 관리 인터페이스 인증서는 Grid Manager, Tenant Manager, Grid Manager API 또는 Tenant Manager API에 대한 모든 후속 새 연결에 사용됩니다.


--
.인증서 생성
--
서버 인증서 파일을 생성합니다.


NOTE: 프로덕션 환경에서 가장 좋은 방법은 외부 인증 기관에서 서명한 사용자 지정 관리 인터페이스 인증서를 사용하는 것입니다.

.. *인증서 생성*을 선택하세요.
.. 인증서 정보를 지정하세요:
+
[cols="1a,3a"]
|===
| 필드 | 설명 


 a| 
도메인 이름
 a| 
인증서에 포함할 하나 이상의 정규화된 도메인 이름입니다.  여러 도메인 이름을 나타내려면 *를 와일드카드로 사용합니다.



 a| 
아이피
 a| 
인증서에 포함할 하나 이상의 IP 주소입니다.



 a| 
제목 (선택사항)
 a| 
X.509 인증서 소유자의 주체 또는 고유 이름(DN).

이 필드에 값을 입력하지 않으면 생성된 인증서는 첫 번째 도메인 이름이나 IP 주소를 주체 일반 이름(CN)으로 사용합니다.



 a| 
유효일
 a| 
인증서가 생성된 후 만료되는 일수입니다.



 a| 
키 사용 확장 추가
 a| 
선택한 경우(기본값이며 권장), 키 사용 및 확장 키 사용 확장 기능이 생성된 인증서에 추가됩니다.

이러한 확장은 인증서에 포함된 키의 목적을 정의합니다.

*참고*: 인증서에 이러한 확장자가 포함되어 있는 경우 이전 클라이언트에서 연결 문제가 발생하지 않는 한 이 확인란을 선택된 상태로 두세요.

|===
.. *생성*을 선택하세요.
.. 생성된 인증서의 메타데이터를 보려면 *인증서 세부 정보*를 선택하세요.
+
*** 인증서 파일을 저장하려면 *인증서 다운로드*를 선택하세요.
+
인증서 파일 이름과 다운로드 위치를 지정하세요.  파일을 확장자로 저장하세요 `.pem` .

+
예:  `storagegrid_certificate.pem`

*** 다른 곳에 붙여넣기 위해 인증서 내용을 복사하려면 *인증서 PEM 복사*를 선택하세요.


.. *저장*을 선택하세요. + 사용자 정의 관리 인터페이스 인증서는 Grid Manager, Tenant Manager, Grid Manager API 또는 Tenant Manager API에 대한 모든 후속 새 연결에 사용됩니다.


--
====
. 웹 브라우저가 최신 상태인지 확인하려면 페이지를 새로 고칩니다.
+

NOTE: 새로운 인증서를 업로드하거나 생성한 후 관련 인증서 만료 알림이 지워지는 데 최대 하루가 걸릴 수 있습니다.

. 사용자 지정 관리 인터페이스 인증서를 추가하면 관리 인터페이스 인증서 페이지에 사용 중인 인증서에 대한 자세한 인증서 정보가 표시됩니다.  + 필요에 따라 인증서 PEM을 다운로드하거나 복사할 수 있습니다.




== 기본 관리 인터페이스 인증서 복원

Grid Manager 및 Tenant Manager 연결에 기본 관리 인터페이스 인증서를 사용하도록 되돌릴 수 있습니다.

.단계
. *구성* > *보안* > *인증서*를 선택합니다.
. *전역* 탭에서 *관리 인터페이스 인증서*를 선택합니다.
. *기본 인증서 사용*을 선택하세요.
+
기본 관리 인터페이스 인증서를 복원하면 구성한 사용자 지정 서버 인증서 파일이 삭제되어 시스템에서 복구할 수 없습니다.  기본 관리 인터페이스 인증서는 이후의 모든 새 클라이언트 연결에 사용됩니다.

. 웹 브라우저가 최신 상태인지 확인하려면 페이지를 새로 고칩니다.




== 스크립트를 사용하여 새로운 자체 서명 관리 인터페이스 인증서를 생성합니다.

엄격한 호스트 이름 검증이 필요한 경우 스크립트를 사용하여 관리 인터페이스 인증서를 생성할 수 있습니다.

.시작하기 전에
* 당신은 가지고있다link:admin-group-permissions.html["특정 액세스 권한"] .
* 당신은 가지고있다 `Passwords.txt` 파일.


.이 작업에 관하여
프로덕션 환경에서는 외부 인증 기관에서 서명한 인증서를 사용하는 것이 가장 좋습니다.

.단계
. 각 관리 노드의 정규화된 도메인 이름(FQDN)을 얻습니다.
. 기본 관리 노드에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh admin@primary_Admin_Node_IP`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. 새로운 자체 서명 인증서로 StorageGRID 구성합니다.
+
`$ sudo make-certificate --domains _wildcard-admin-node-fqdn_ --type management`

+
** 을 위한 `--domains` 와일드카드를 사용하여 모든 관리 노드의 정규화된 도메인 이름을 나타냅니다.  예를 들어, `*.ui.storagegrid.example.com` * 와일드카드를 사용하여 표현합니다. `admin1.ui.storagegrid.example.com` 그리고 `admin2.ui.storagegrid.example.com` .
** 세트 `--type` 에게 `management` Grid Manager와 Tenant Manager에서 사용되는 관리 인터페이스 인증서를 구성합니다.
** 기본적으로 생성된 인증서는 1년(365일) 동안 유효하며 만료되기 전에 다시 만들어야 합니다.  당신은 사용할 수 있습니다 `--days` 기본 유효 기간을 재정의하는 인수입니다.
+

NOTE: 인증서의 유효 기간은 다음 날짜부터 시작됩니다. `make-certificate` 실행됩니다.  관리 클라이언트가 StorageGRID 와 동일한 시간 소스에 동기화되었는지 확인해야 합니다. 그렇지 않으면 클라이언트가 인증서를 거부할 수 있습니다.

+
 $ sudo make-certificate --domains *.ui.storagegrid.example.com --type management --days 720
+
결과 출력에는 관리 API 클라이언트에 필요한 공개 인증서가 포함되어 있습니다.



. 인증서를 선택하여 복사합니다.
+
선택 항목에 BEGIN 태그와 END 태그를 포함하세요.

. 명령 셸에서 로그아웃합니다. `$ exit`
. 인증서가 구성되었는지 확인하세요.
+
.. 그리드 관리자에 접속합니다.
.. *구성* > *보안* > *인증서*를 선택하세요.
.. *전역* 탭에서 *관리 인터페이스 인증서*를 선택합니다.


. 복사한 공개 인증서를 사용하도록 관리 클라이언트를 구성합니다.  BEGIN 및 END 태그를 포함합니다.




== 관리 인터페이스 인증서를 다운로드하거나 복사하세요

관리 인터페이스 인증서 내용을 저장하거나 복사하여 다른 곳에서 사용할 수 있습니다.

.단계
. *구성* > *보안* > *인증서*를 선택합니다.
. *전역* 탭에서 *관리 인터페이스 인증서*를 선택합니다.
. *서버* 또는 *CA 번들* 탭을 선택한 다음 인증서를 다운로드하거나 복사합니다.
+
[role="tabbed-block"]
====
.인증서 파일 또는 CA 번들 다운로드
--
인증서 또는 CA 번들을 다운로드하세요 `.pem` 파일.  선택적 CA 번들을 사용하는 경우 번들의 각 인증서는 해당 하위 탭에 표시됩니다.

.. *인증서 다운로드* 또는 *CA 번들 다운로드*를 선택하세요.
+
CA 번들을 다운로드하는 경우 CA 번들 보조 탭의 모든 인증서가 단일 파일로 다운로드됩니다.

.. 인증서 파일 이름과 다운로드 위치를 지정하세요.  파일을 확장자로 저장하세요 `.pem` .
+
예:  `storagegrid_certificate.pem`



--
.인증서 또는 CA 번들 PEM 복사
--
인증서 텍스트를 복사하여 다른 곳에 붙여넣으세요.  선택적 CA 번들을 사용하는 경우 번들의 각 인증서는 해당 하위 탭에 표시됩니다.

.. *인증서 PEM 복사* 또는 *CA 번들 PEM 복사*를 선택하세요.
+
CA 번들을 복사하는 경우 CA 번들 보조 탭의 모든 인증서가 함께 복사됩니다.

.. 복사한 인증서를 텍스트 편집기에 붙여넣습니다.
.. 텍스트 파일을 확장자로 저장하세요 `.pem` .
+
예:  `storagegrid_certificate.pem`



--
====

