---
permalink: admin/configuring-stored-object-compression.html 
sidebar: sidebar 
keywords: object compression, compress stored objects 
summary: StorageGRID 에 저장된 객체의 크기를 줄이기 위해 객체 압축을 활성화하여 객체가 차지하는 저장 공간을 줄일 수 있습니다. 
---
= 저장된 객체 압축
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 에 저장된 객체의 크기를 줄이기 위해 객체 압축을 활성화하여 객체가 차지하는 저장 공간을 줄일 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:admin-group-permissions.html["특정 액세스 권한"] .


.이 작업에 관하여
기본적으로 객체 압축은 비활성화되어 있습니다.  압축을 활성화하면 StorageGRID 각 객체를 저장할 때 손실 없는 압축을 사용하여 압축을 시도합니다.


NOTE: 이 설정을 변경하면 새로운 설정이 적용되는 데 약 1분이 소요됩니다.  구성된 값은 성능과 확장성을 위해 캐시됩니다.

객체 압축을 활성화하기 전에 다음 사항을 확인하세요.

* 저장되는 데이터가 압축 가능하다는 것을 알지 못하는 한 *저장된 객체 압축*을 선택하지 마세요.
* StorageGRID 에 객체를 저장하는 애플리케이션은 객체를 저장하기 전에 압축할 수 있습니다.  클라이언트 애플리케이션이 StorageGRID 에 저장하기 전에 이미 객체를 압축한 경우 이 옵션을 선택해도 객체의 크기는 더 이상 줄어들지 않습니다.
* StorageGRID 와 함께 NetApp FabricPool 사용하는 경우 *저장된 개체 압축*을 선택하지 마세요.
* *저장된 객체 압축*을 선택하면 S3 클라이언트 애플리케이션은 반환할 바이트 범위를 지정하는 GetObject 작업을 수행하지 않아야 합니다.  이러한 "범위 읽기" 작업은 StorageGRID 요청된 바이트에 액세스하기 위해 객체를 효과적으로 압축 해제해야 하기 때문에 비효율적입니다.  매우 큰 객체에서 작은 범위의 바이트를 요청하는 GetObject 작업은 특히 비효율적입니다. 예를 들어, 50GB 압축 객체에서 10MB 범위를 읽는 것은 비효율적입니다.
+
압축된 객체에서 범위를 읽는 경우 클라이언트 요청이 시간 초과될 수 있습니다.

+

NOTE: 객체를 압축해야 하고 클라이언트 애플리케이션에서 범위 읽기를 사용해야 하는 경우 애플리케이션의 읽기 시간 제한을 늘리세요.



.단계
. *구성* > *시스템* > *저장소 설정* > *개체 압축*을 선택합니다.
. *저장된 개체 압축* 확인란을 선택합니다.
. *저장*을 선택하세요.

