---
permalink: admin/configure-autosupport-grid-manager.html 
sidebar: sidebar 
keywords: how to configure autosupport, what is autosupport-on-demand 
summary: 기본적으로 StorageGRID AutoSupport 기능은 StorageGRID 처음 설치할 때 활성화됩니다.  하지만 각 어플라이언스에서 하드웨어 AutoSupport 구성해야 합니다.  필요에 따라 AutoSupport 구성을 변경할 수 있습니다. 
---
= AutoSupport 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본적으로 StorageGRID AutoSupport 기능은 StorageGRID 처음 설치할 때 활성화됩니다.  하지만 각 어플라이언스에서 하드웨어 AutoSupport 구성해야 합니다.  필요에 따라 AutoSupport 구성을 변경할 수 있습니다.

StorageGRID AutoSupport 의 구성을 변경하려면 기본 관리 노드에서만 변경하세요.  당신은해야합니다<<autosupport-for-appliances,하드웨어 AutoSupport 구성>> 각 기기마다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:admin-group-permissions.html["루트 액세스 권한"] .
* AutoSupport 패키지를 보내기 위해 HTTPS를 사용하는 경우 직접 또는 간접적으로 기본 관리 노드에 아웃바운드 인터넷 액세스를 제공한 것입니다.link:configuring-admin-proxy-settings.html["프록시 서버 사용"] (인바운드 연결은 필요하지 않습니다).
* StorageGRID AutoSupport 페이지에서 HTTP가 선택된 경우link:configuring-admin-proxy-settings.html["프록시 서버를 구성했습니다"] AutoSupport 패키지를 HTTPS로 전달합니다.  NetApp의 AutoSupport 서버는 HTTP를 사용하여 보낸 패키지를 거부합니다.
* AutoSupport 패키지의 프로토콜로 SMTP를 사용하는 경우 SMTP 메일 서버가 구성되어 있습니다.


.이 작업에 관하여
다음 옵션을 조합하여 AutoSupport 패키지를 기술 지원팀에 보낼 수 있습니다.

* *주간*: 일주일에 한 번씩 AutoSupport 패키지를 자동으로 보냅니다.  기본 설정: 활성화됨.
* *이벤트 트리거*: 매시간 또는 중요한 시스템 이벤트가 발생할 때마다 AutoSupport 패키지를 자동으로 보냅니다.  기본 설정: 활성화됨.
* *주문형*: 기술 지원팀이 StorageGRID 시스템에서 AutoSupport 패키지를 자동으로 보내도록 요청할 수 있도록 허용합니다. 이 기능은 기술 지원팀이 적극적으로 문제를 해결하고 있을 때 유용합니다(HTTPS AutoSupport 전송 프로토콜 필요).  기본 설정: 비활성화.
* *사용자가 트리거*: 언제든지 AutoSupport 패키지를 수동으로 보냅니다.




== [[specify-protocol-for-autosupport-packages]] AutoSupport 패키지에 대한 프로토콜을 지정합니다.

AutoSupport 패키지를 보내려면 다음 프로토콜을 사용할 수 있습니다.

* *HTTPS*: 이는 새로 설치하는 경우 기본 설정이며 권장되는 설정입니다.  이 프로토콜은 포트 443을 사용합니다.  당신이 원한다면<<주문형 AutoSupport 활성화,AutoSupport on Demand 기능을 활성화하세요>> HTTPS를 사용해야 합니다.
* *HTTP*: HTTP를 선택하는 경우 AutoSupport 패키지를 HTTPS로 전달하기 위해 프록시 서버를 구성해야 합니다.  NetApp의 AutoSupport 서버는 HTTP를 사용하여 전송된 패키지를 거부합니다.  이 프로토콜은 포트 80을 사용합니다.
* *SMTP*: AutoSupport 패키지를 이메일로 받으려면 이 옵션을 사용하세요.


귀하가 설정한 프로토콜은 모든 유형의 AutoSupport 패키지를 보내는 데 사용됩니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. AutoSupport 패키지를 보내는 데 사용할 프로토콜을 선택하세요.
. *HTTPS*를 선택한 경우, 기술 지원 서버에 대한 연결을 보호하기 위해 NetApp 지원 인증서(TLS 인증서)를 사용할지 여부를 선택합니다.
+
** *인증서 확인* (기본값): AutoSupport 패키지 전송이 안전한지 확인합니다.  NetApp 지원 인증서는 이미 StorageGRID 소프트웨어와 함께 설치되었습니다.
** *인증서 확인 안 함*: 인증서에 일시적인 문제가 있는 경우 등 인증서 유효성 검사를 사용하지 않아야 할 정당한 이유가 있는 경우에만 이 옵션을 선택하세요.


. *저장*을 선택하세요. 모든 주간, 사용자 트리거, 이벤트 트리거 패키지는 선택된 프로토콜을 사용하여 전송됩니다.




== 주간 AutoSupport 비활성화

기본적으로 StorageGRID 시스템은 일주일에 한 번 기술 지원팀에 AutoSupport 패키지를 보내도록 구성되어 있습니다.

주간 AutoSupport 패키지가 언제 발송되는지 확인하려면 * AutoSupport* > *결과* 탭으로 이동하세요.  *주간 AutoSupport* 섹션에서 *다음 예약 시간*의 값을 확인하세요.

언제든지 주간 AutoSupport 패키지의 자동 전송을 비활성화할 수 있습니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. *주간 AutoSupport 활성화* 확인란을 선택 취소합니다.
. *저장*을 선택하세요.




== 이벤트 트리거 AutoSupport 비활성화

기본적으로 StorageGRID 시스템은 매시간 기술 지원팀에 AutoSupport 패키지를 보내도록 구성되어 있습니다.

언제든지 이벤트에 따른 AutoSupport 비활성화할 수 있습니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. *이벤트 트리거 AutoSupport 사용* 확인란을 선택 취소합니다.
. *저장*을 선택하세요.




== 주문형 AutoSupport 활성화

AutoSupport on Demand는 기술 지원팀이 적극적으로 해결하고 있는 문제를 해결하는 데 도움을 줄 수 있습니다.

기본적으로 AutoSupport on Demand는 비활성화되어 있습니다.  이 기능을 활성화하면 기술 지원팀에서 StorageGRID 시스템에 AutoSupport 패키지를 자동으로 보내달라고 요청할 수 있습니다.  기술 지원팀은 AutoSupport on Demand 쿼리에 대한 폴링 시간 간격을 설정할 수도 있습니다.

기술 지원팀은 AutoSupport on Demand를 활성화하거나 비활성화할 수 없습니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. 프로토콜로 *HTTPS*를 선택하세요.
. *주간 AutoSupport 활성화* 확인란을 선택하세요.
. *주문형 AutoSupport 활성화* 확인란을 선택하세요.
. *저장*을 선택하세요.
+
AutoSupport on Demand가 활성화되어 있으며, 기술 지원팀은 AutoSupport on Demand 요청을 StorageGRID 로 보낼 수 있습니다.





== 소프트웨어 업데이트에 대한 확인 비활성화

기본적으로 StorageGRID NetApp 에 ​​연락하여 시스템에 대한 소프트웨어 업데이트가 있는지 확인합니다.  StorageGRID 핫픽스나 새 버전이 제공되는 경우 새 버전은 StorageGRID 업그레이드 페이지에 표시됩니다.

필요에 따라 소프트웨어 업데이트 확인을 비활성화할 수 있습니다.  예를 들어, 시스템에 WAN 접속이 불가능한 경우 다운로드 오류를 방지하기 위해 해당 검사를 비활성화해야 합니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. *소프트웨어 업데이트 확인* 체크박스를 선택 취소합니다.
. *저장*을 선택하세요.




== 추가 AutoSupport 대상 추가

AutoSupport 활성화하면 건강 및 상태 패키지가 기술 지원팀으로 전송됩니다.  모든 AutoSupport 패키지에 대해 추가 대상을 하나 지정할 수 있습니다.

AutoSupport 패키지를 보내는 데 사용되는 프로토콜을 확인하거나 변경하려면 다음 지침을 참조하세요.<<specify-protocol-for-autosupport-packages,AutoSupport 패키지에 대한 프로토콜을 지정합니다.>> .


NOTE: SMTP 프로토콜을 사용하여 AutoSupport 패키지를 추가 대상지로 보낼 수 없습니다.

.단계
. *지원* > *도구* > * AutoSupport* > *설정*을 선택하세요.
. *추가 AutoSupport 대상 활성화*를 선택합니다.
. 다음을 지정하세요.
+
호스트 이름:: 추가 AutoSupport 대상 서버의 서버 호스트 이름 또는 IP 주소입니다.
+
--

NOTE: 추가 목적지는 하나만 입력할 수 있습니다.

--
포트:: 추가 AutoSupport 대상 서버에 연결하는 데 사용되는 포트입니다.  HTTP의 경우 기본값은 포트 80이고 HTTPS의 경우 기본값은 포트 443입니다.
인증서 검증:: 추가 대상에 대한 연결을 보호하기 위해 TLS 인증서를 사용하는지 여부입니다.
+
--
** 인증서 검증을 사용하려면 *인증서 확인*을 선택하세요.
** 인증서 검증 없이 AutoSupport 패키지를 보내려면 *인증서 확인 안 함*을 선택하세요.
+
인증서에 일시적인 문제가 있는 경우 등 인증서 유효성 검사를 사용하지 않아야 할 정당한 이유가 있는 경우에만 이 옵션을 선택하세요.



--


. *인증서 확인*을 선택한 경우 다음을 수행하세요.
+
.. CA 인증서의 위치를 찾아보세요.
.. CA 인증서 파일을 업로드합니다.
+
CA 인증서 메타데이터가 나타납니다.



. *저장*을 선택하세요.
+
향후 모든 주간, 이벤트 트리거, 사용자 트리거 AutoSupport 패키지는 추가 목적지로 전송됩니다.





== [[autosupport-for-appliances]]어플라이언스에 대한 AutoSupport 구성

AutoSupport for Appliances는 StorageGRID 하드웨어 문제를 보고하고, StorageGRID AutoSupport StorageGRID 소프트웨어 문제를 보고합니다. 단, SGF6112의 경우 StorageGRID AutoSupport 하드웨어 및 소프트웨어 문제를 모두 보고합니다.  SGF6112를 제외한 모든 어플라이언스에서 AutoSupport 구성해야 하며, SGF6112의 경우 추가 구성이 필요하지 않습니다.  AutoSupport 서비스 어플라이언스와 스토리지 어플라이언스에 대해 다르게 구현됩니다.

SANtricity 사용하여 각 스토리지 어플라이언스에 대한 AutoSupport 활성화합니다.  초기 어플라이언스 설정 중 또는 어플라이언스가 설치된 후에 SANtricity AutoSupport 구성할 수 있습니다.

* SG6000 및 SG5700 가전제품의 경우 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/accessing-and-configuring-santricity-system-manager.html["SANtricity System Manager에서 AutoSupport 구성"^]


E-Series 어플라이언스의 AutoSupport 패키지는 프록시를 통한 AutoSupport 전달을 구성하는 경우 StorageGRID AutoSupport 에 포함될 수 있습니다.link:../admin/sending-eseries-autosupport-messages-through-storagegrid.html["SANtricity 시스템 관리자"] .

StorageGRID AutoSupport DIMM이나 호스트 인터페이스 카드(HIC) 오류와 같은 하드웨어 문제를 보고하지 않습니다.  그러나 일부 구성 요소 오류가 발생할 수 있습니다.link:../monitor/alerts-reference.html["하드웨어 알림"] .  BMC (베이스보드 관리 컨트롤러)가 있는 StorageGRID 어플라이언스의 경우 하드웨어 오류를 보고하기 위해 이메일 및 SNMP 트랩을 구성할 수 있습니다.

* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/setting-up-email-notifications-for-alerts.html["BMC 알림에 대한 이메일 알림 설정"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/configuring-snmp-settings-for-bmc.html["BMC 에 대한 SNMP 설정 구성"^]


.관련 정보
https://mysupport.netapp.com/site/global/dashboard["NetApp 지원"^]
