---
permalink: admin/configuring-storagegrid-certificates-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricpool, ONTAP certificates 
summary: FabricPool 사용하는 ONTAP 클라이언트와 같이 엄격한 호스트 이름 유효성 검사를 수행하고 엄격한 호스트 이름 유효성 검사를 비활성화하는 것을 지원하지 않는 S3 클라이언트의 경우, 로드 밸런서 엔드포인트를 구성할 때 서버 인증서를 생성하거나 업로드할 수 있습니다. 
---
= FabricPool 에 대한 StorageGRID 인증서 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool 사용하는 ONTAP 클라이언트와 같이 엄격한 호스트 이름 유효성 검사를 수행하고 엄격한 호스트 이름 유효성 검사를 비활성화하는 것을 지원하지 않는 S3 클라이언트의 경우, 로드 밸런서 엔드포인트를 구성할 때 서버 인증서를 생성하거나 업로드할 수 있습니다.

.시작하기 전에
* 당신은 가지고있다link:admin-group-permissions.html["특정 액세스 권한"] .
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .


.이 작업에 관하여
로드 밸런서 엔드포인트를 생성할 때 자체 서명된 서버 인증서를 생성하거나 알려진 인증 기관(CA)에서 서명한 인증서를 업로드할 수 있습니다.  운영 환경에서는 알려진 CA에서 서명한 인증서를 사용해야 합니다.  CA가 서명한 인증서는 중단 없이 교체할 수 있습니다.  또한 중간자 공격에 대한 보호 기능이 더 뛰어나므로 보안도 더 뛰어납니다.

다음 단계에서는 FabricPool 사용하는 S3 클라이언트에 대한 일반적인 지침을 제공합니다.  더 자세한 정보와 절차는 다음을 참조하세요.link:../fabricpool/index.html["FabricPool 에 대한 StorageGRID 구성"] .

.단계
. 선택적으로 FabricPool 에서 사용할 고가용성(HA) 그룹을 구성합니다.
. FabricPool 에서 사용할 S3 로드 밸런서 엔드포인트를 생성합니다.
+
HTTPS 로드 밸런서 엔드포인트를 생성하면 서버 인증서, 인증서 개인 키, 선택적 CA 번들을 업로드하라는 메시지가 표시됩니다.

. ONTAP 에서 StorageGRID 클라우드 계층으로 연결합니다.
+
업로드한 CA 인증서에 사용된 로드 밸런서 엔드포인트 포트와 정규화된 도메인 이름을 지정합니다.  그런 다음 CA 인증서를 제공합니다.

+

NOTE: 중간 CA가 StorageGRID 인증서를 발급한 경우 중간 CA 인증서를 제공해야 합니다.  StorageGRID 인증서가 루트 CA에서 직접 발급된 경우 루트 CA 인증서를 제공해야 합니다.


