---
permalink: admin/configuring-custom-server-certificate-for-storage-node.html 
sidebar: sidebar 
keywords: global S3 API certificate 
summary: S3 클라이언트가 스토리지 노드나 로드 밸런서 엔드포인트에 연결하는 데 사용되는 서버 인증서를 교체하거나 복원할 수 있습니다.  교체용 사용자 정의 서버 인증서는 귀하의 조직에 맞게 지정됩니다. 
---
= S3 API 인증서 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 클라이언트가 스토리지 노드나 로드 밸런서 엔드포인트에 연결하는 데 사용되는 서버 인증서를 교체하거나 복원할 수 있습니다.  교체용 사용자 정의 서버 인증서는 귀하의 조직에 맞게 지정됩니다.


TIP: 이 버전의 문서 사이트에서는 Swift 세부 정보가 제거되었습니다. 보다 https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-custom-server-certificate-for-storage-node.html["StorageGRID 11.8: S3 및 Swift API 인증서 구성"^] .

.이 작업에 관하여
기본적으로 모든 스토리지 노드에는 그리드 CA가 서명한 X.509 서버 인증서가 발급됩니다.  이러한 CA 서명 인증서는 단일 공통 사용자 정의 서버 인증서와 해당 개인 키로 대체될 수 있습니다.

모든 스토리지 노드에는 단일 사용자 지정 서버 인증서가 사용되므로 클라이언트가 스토리지 엔드포인트에 연결할 때 호스트 이름을 확인해야 하는 경우 인증서를 와일드카드 또는 다중 도메인 인증서로 지정해야 합니다.  그리드의 모든 스토리지 노드와 일치하도록 사용자 정의 인증서를 정의합니다.

서버에서 구성을 완료한 후에는 시스템에 액세스하는 데 사용할 S3 API 클라이언트에 Grid CA 인증서를 설치해야 할 수도 있습니다. 이는 사용하는 루트 인증 기관(CA)에 따라 다릅니다.


NOTE: 실패한 서버 인증서로 인해 작업이 중단되지 않도록 하기 위해 루트 서버 인증서가 만료되려고 할 때 *S3 API에 대한 글로벌 서버 인증서 만료* 알림이 트리거됩니다. 필요에 따라 *구성* > *보안* > *인증서*를 선택하고 글로벌 탭에서 S3 API 인증서의 만료 날짜를 확인하여 현재 인증서가 만료되는 시점을 확인할 수 있습니다.

사용자 정의 S3 API 인증서를 업로드하거나 생성할 수 있습니다.



== 사용자 정의 S3 API 인증서 추가

.단계
. *구성* > *보안* > *인증서*를 선택합니다.
. *글로벌* 탭에서 *S3 API 인증서*를 선택합니다.
. *사용자 정의 인증서 사용*을 선택하세요.
. 인증서를 업로드하거나 생성합니다.
+
[role="tabbed-block"]
====
.인증서 업로드
--
필요한 서버 인증서 파일을 업로드합니다.

.. *증명서 업로드*를 선택하세요.
.. 필요한 서버 인증서 파일을 업로드하세요.
+
*** *서버 인증서*: 사용자 정의 서버 인증서 파일(PEM 인코딩).
*** *인증서 개인 키*: 사용자 지정 서버 인증서 개인 키 파일(`.key` ).
+

NOTE: EC 개인 키는 224비트 이상이어야 합니다.  RSA 개인 키는 2048비트 이상이어야 합니다.

*** *CA 번들*: 각 중간 발급 인증 기관의 인증서를 포함하는 단일 선택 파일입니다.  해당 파일에는 PEM으로 인코딩된 CA 인증서 파일이 각각 포함되어 있어야 하며, 인증서 체인 순서대로 연결되어 있어야 합니다.


.. 업로드된 각 사용자 정의 S3 API 인증서에 대한 메타데이터와 PEM을 표시하려면 인증서 세부 정보를 선택합니다.  선택적 CA 번들을 업로드한 경우 각 인증서가 자체 탭에 표시됩니다.
+
*** 인증서 파일을 저장하려면 *인증서 다운로드*를 선택하고, 인증서 번들을 저장하려면 *CA 번들 다운로드*를 선택합니다.
+
인증서 파일 이름과 다운로드 위치를 지정하세요.  파일을 확장자로 저장하세요 `.pem` .

+
예:  `storagegrid_certificate.pem`

*** 다른 곳에 붙여넣기 위해 인증서 내용을 복사하려면 *인증서 PEM 복사* 또는 *CA 번들 PEM 복사*를 선택하세요.


.. *저장*을 선택하세요.
+
사용자 지정 서버 인증서는 이후의 새로운 S3 클라이언트 연결에 사용됩니다.



--
.인증서 생성
--
서버 인증서 파일을 생성합니다.

.. *인증서 생성*을 선택하세요.
.. 인증서 정보를 지정하세요:
+
[cols="1a,3a"]
|===
| 필드 | 설명 


 a| 
도메인 이름
 a| 
인증서에 포함할 하나 이상의 정규화된 도메인 이름입니다.  여러 도메인 이름을 나타내려면 *를 와일드카드로 사용합니다.



 a| 
아이피
 a| 
인증서에 포함할 하나 이상의 IP 주소입니다.



 a| 
제목 (선택사항)
 a| 
X.509 인증서 소유자의 주체 또는 고유 이름(DN).

이 필드에 값을 입력하지 않으면 생성된 인증서는 첫 번째 도메인 이름이나 IP 주소를 주체 일반 이름(CN)으로 사용합니다.



 a| 
유효일
 a| 
인증서가 생성된 후 만료되는 일수입니다.



 a| 
키 사용 확장 추가
 a| 
선택한 경우(기본값이며 권장), 키 사용 및 확장 키 사용 확장 기능이 생성된 인증서에 추가됩니다.

이러한 확장은 인증서에 포함된 키의 목적을 정의합니다.

*참고*: 인증서에 이러한 확장자가 포함되어 있는 경우 이전 클라이언트에서 연결 문제가 발생하지 않는 한 이 확인란을 선택된 상태로 두세요.

|===
.. *생성*을 선택하세요.
.. 사용자 정의 S3 API 인증서에 대한 메타데이터와 PEM을 표시하려면 *인증서 세부 정보*를 선택합니다.
+
*** 인증서 파일을 저장하려면 *인증서 다운로드*를 선택하세요.
+
인증서 파일 이름과 다운로드 위치를 지정하세요.  파일을 확장자로 저장하세요 `.pem` .

+
예:  `storagegrid_certificate.pem`

*** 다른 곳에 붙여넣기 위해 인증서 내용을 복사하려면 *인증서 PEM 복사*를 선택하세요.


.. *저장*을 선택하세요.
+
사용자 지정 서버 인증서는 이후의 새로운 S3 클라이언트 연결에 사용됩니다.



--
====
. 기본 StorageGRID 서버 인증서, 업로드된 CA 서명 인증서 또는 생성된 사용자 지정 인증서에 대한 메타데이터를 표시할 탭을 선택합니다.
+

NOTE: 새로운 인증서를 업로드하거나 생성한 후 관련 인증서 만료 알림이 지워지는 데 최대 하루가 걸릴 수 있습니다.

. 웹 브라우저가 최신 상태인지 확인하려면 페이지를 새로 고칩니다.
. 사용자 정의 S3 API 인증서를 추가하면 S3 API 인증서 페이지에 사용 중인 사용자 정의 S3 API 인증서에 대한 자세한 인증서 정보가 표시됩니다.  + 필요에 따라 인증서 PEM을 다운로드하거나 복사할 수 있습니다.




== 기본 S3 API 인증서 복원

S3 클라이언트가 스토리지 노드에 연결할 때 기본 S3 API 인증서를 사용하도록 되돌릴 수 있습니다.  하지만 로드 밸런서 엔드포인트에는 기본 S3 API 인증서를 사용할 수 없습니다.

.단계
. *구성* > *보안* > *인증서*를 선택합니다.
. *글로벌* 탭에서 *S3 API 인증서*를 선택합니다.
. *기본 인증서 사용*을 선택하세요.
+
글로벌 S3 API 인증서의 기본 버전을 복원하면 구성한 사용자 지정 서버 인증서 파일이 삭제되며 시스템에서 복구할 수 없습니다.  기본 S3 API 인증서는 이후의 새로운 S3 클라이언트가 스토리지 노드에 연결할 때 사용됩니다.

. 경고를 확인하고 기본 S3 API 인증서를 복원하려면 *확인*을 선택하세요.
+
루트 액세스 권한이 있고 사용자 지정 S3 API 인증서가 로드 밸런서 엔드포인트 연결에 사용된 경우, 기본 S3 API 인증서를 사용하여 더 이상 액세스할 수 없는 로드 밸런서 엔드포인트 목록이 표시됩니다.  로 가다link:../admin/configuring-load-balancer-endpoints.html["로드 밸런서 엔드포인트 구성"] 영향을 받은 엔드포인트를 편집하거나 제거합니다.

. 웹 브라우저가 최신 상태인지 확인하려면 페이지를 새로 고칩니다.




== S3 API 인증서를 다운로드하거나 복사하세요

S3 API 인증서 내용을 저장하거나 복사하여 다른 곳에서 사용할 수 있습니다.

.단계
. *구성* > *보안* > *인증서*를 선택합니다.
. *글로벌* 탭에서 *S3 API 인증서*를 선택합니다.
. *서버* 또는 *CA 번들* 탭을 선택한 다음 인증서를 다운로드하거나 복사합니다.
+
[role="tabbed-block"]
====
.인증서 파일 또는 CA 번들 다운로드
--
인증서 또는 CA 번들을 다운로드하세요 `.pem` 파일.  선택적 CA 번들을 사용하는 경우 번들의 각 인증서는 해당 하위 탭에 표시됩니다.

.. *인증서 다운로드* 또는 *CA 번들 다운로드*를 선택하세요.
+
CA 번들을 다운로드하는 경우 CA 번들 보조 탭의 모든 인증서가 단일 파일로 다운로드됩니다.

.. 인증서 파일 이름과 다운로드 위치를 지정하세요.  파일을 확장자로 저장하세요 `.pem` .
+
예:  `storagegrid_certificate.pem`



--
.인증서 또는 CA 번들 PEM 복사
--
인증서 텍스트를 복사하여 다른 곳에 붙여넣으세요.  선택적 CA 번들을 사용하는 경우 번들의 각 인증서는 해당 하위 탭에 표시됩니다.

.. *인증서 PEM 복사* 또는 *CA 번들 PEM 복사*를 선택하세요.
+
CA 번들을 복사하는 경우 CA 번들 보조 탭의 모든 인증서가 함께 복사됩니다.

.. 복사한 인증서를 텍스트 편집기에 붙여넣습니다.
.. 텍스트 파일을 확장자로 저장하세요 `.pem` .
+
예:  `storagegrid_certificate.pem`



--
====


.관련 정보
* link:../s3/index.html["S3 REST API 사용"]
* link:configuring-s3-api-endpoint-domain-names.html["S3 엔드포인트 도메인 이름 구성"]

