---
permalink: admin/controlling-storagegrid-access.html 
sidebar: sidebar 
keywords: administrator access, single sign on, sso, users, groups, client certificates, passwords, passphrase 
summary: '그룹과 사용자를 만들거나 가져오고 각 그룹에 권한을 할당하여 누가 StorageGRID 에 액세스할 수 있는지, 그리고 사용자가 수행할 수 있는 작업을 제어할 수 있습니다.  선택적으로, 단일 로그인(SSO)을 활성화하고, 클라이언트 인증서를 생성하고, 그리드 비밀번호를 변경할 수 있습니다.' 
---
= StorageGRID 액세스 제어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그룹과 사용자를 만들거나 가져오고 각 그룹에 권한을 할당하여 누가 StorageGRID 에 액세스할 수 있는지, 그리고 사용자가 수행할 수 있는 작업을 제어할 수 있습니다.  선택적으로 SSO(Single Sign-On)를 활성화하고, 클라이언트 인증서를 만들고, 그리드 비밀번호를 변경할 수 있습니다.



== Grid Manager에 대한 액세스 제어

ID 페더레이션 서비스에서 그룹과 사용자를 가져오거나 로컬 그룹과 로컬 사용자를 설정하여 Grid Manager와 Grid Management API에 액세스할 수 있는 사람을 결정합니다.

사용 중link:using-identity-federation.html["ID 연합"] 설정을 만듭니다link:managing-admin-groups.html["여러 떼"] 그리고link:managing-users.html["사용자"] 더 빠르고, 사용자는 익숙한 자격 증명을 사용하여 StorageGRID 에 로그인할 수 있습니다.  Active Directory, OpenLDAP 또는 Oracle Directory Server를 사용하는 경우 ID 페더레이션을 구성할 수 있습니다.


NOTE: 다른 LDAP v3 서비스를 사용하려면 기술 지원팀에 문의하세요.

각 사용자가 수행할 수 있는 작업은 다른 작업을 할당하여 결정합니다.link:admin-group-permissions.html["권한"] 각 그룹에.  예를 들어, 한 그룹의 사용자가 ILM 규칙을 관리하고 다른 그룹의 사용자가 유지 관리 작업을 수행할 수 있도록 할 수 있습니다.  사용자는 시스템에 액세스하려면 최소한 하나의 그룹에 속해야 합니다.

선택적으로 그룹을 읽기 전용으로 구성할 수 있습니다.  읽기 전용 그룹의 사용자는 설정과 기능만 볼 수 있습니다.  그들은 Grid Manager나 Grid Management API에서 어떠한 변경이나 작업도 수행할 수 없습니다.



== 단일 로그인 활성화

StorageGRID 시스템은 SAML 2.0(Security Assertion Markup Language 2.0) 표준을 사용하여 SSO(Single Sign-On)를 지원합니다. 당신이 후에link:configuring-sso.html["SSO 구성 및 활성화"] 모든 사용자는 Grid Manager, Tenant Manager, Grid Management API 또는 Tenant Management API에 액세스하기 전에 외부 ID 공급자로부터 인증을 받아야 합니다. 로컬 사용자는 StorageGRID 에 로그인할 수 없습니다.



== 프로비저닝 암호 변경

프로비저닝 암호는 많은 설치 및 유지 관리 절차와 StorageGRID 복구 패키지를 다운로드하는 데 필요합니다. StorageGRID 시스템의 그리드 토폴로지 정보와 암호화 키의 백업을 다운로드하려면 암호도 필요합니다. 당신은 할 수 있습니다link:changing-provisioning-passphrase.html["암호를 변경하다"] 필요에 따라.



== 노드 콘솔 비밀번호 변경

그리드의 각 노드에는 고유한 노드 콘솔 비밀번호가 있습니다. SSH를 사용하여 "admin"으로 노드에 로그인하거나 VM/물리적 콘솔 연결에서는 루트 사용자로 로그인해야 합니다. 필요에 따라 다음을 수행할 수 있습니다.link:change-node-console-password.html["노드 콘솔 비밀번호 변경"] 각 노드에 대해.
