---
permalink: admin/creating-traffic-classification-policies.html 
sidebar: sidebar 
keywords: traffic classification, network traffic, traffic limits, policy 
summary: 버킷, 테넌트, IP 서브넷 또는 로드 밸런서 엔드포인트별로 네트워크 트래픽을 모니터링하고 선택적으로 제한하려면 트래픽 분류 정책을 만듭니다.  선택적으로 대역폭, 동시 요청 수 또는 요청 속도를 기준으로 정책에 대한 제한을 설정할 수 있습니다. 
---
= 트래픽 분류 정책 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
버킷, 버킷 정규식, CIDR, 로드 밸런서 엔드포인트 또는 테넌트별로 네트워크 트래픽을 모니터링하고 선택적으로 제한하려는 경우 트래픽 분류 정책을 만들 수 있습니다.  선택적으로 대역폭, 동시 요청 수 또는 요청 속도를 기준으로 정책에 대한 제한을 설정할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:admin-group-permissions.html["루트 액세스 권한"] .
* 일치시키고자 하는 모든 로드 밸런서 엔드포인트를 생성했습니다.
* 일치시키고 싶은 테넌트를 생성했습니다.


.단계
. *구성* > *네트워크* > *트래픽 분류*를 선택합니다.
. *만들기*를 선택하세요.
. 정책의 이름과 설명(선택 사항)을 입력하고 *계속*을 선택합니다.
+
예를 들어, 이 트래픽 분류 정책이 적용되는 사항과 제한되는 사항을 설명하세요.

. *규칙 추가*를 선택하고 다음 세부 정보를 지정하여 정책에 대한 하나 이상의 일치 규칙을 만듭니다.  생성하는 모든 정책에는 적어도 하나의 일치하는 규칙이 있어야 합니다. *계속*을 선택하세요.
+
[cols="1a,3a"]
|===
| 필드 | 설명 


 a| 
유형
 a| 
매칭 규칙이 적용되는 트래픽 유형을 선택합니다.  트래픽 유형으로는 버킷, 버킷 정규식, CIDR, 로드 밸런서 엔드포인트, 테넌트가 있습니다.



 a| 
일치 값
 a| 
선택한 유형과 일치하는 값을 입력하세요.

** 버킷: 하나 이상의 버킷 이름을 입력하세요.
** 버킷 정규 표현식: 버킷 이름 집합과 일치하는 데 사용되는 하나 이상의 정규 표현식을 입력하세요.
+
정규 표현식은 고정되지 않았습니다.  버킷 이름의 시작 부분에서 일치시키려면 ^ 앵커를 사용하고, 이름의 끝 부분에서 일치시키려면 $ 앵커를 사용합니다.  정규 표현식 매칭은 PCRE(Perl 호환 정규 표현식) 구문의 하위 집합을 지원합니다.

** CIDR: 원하는 서브넷과 일치하는 하나 이상의 IPv4 서브넷을 CIDR 표기법으로 입력합니다.
** 로드 밸런서 엔드포인트: 엔드포인트 이름을 선택하세요.  이는 귀하가 정의한 로드 밸런서 엔드포인트입니다.link:../admin/configuring-load-balancer-endpoints.html["로드 밸런서 엔드포인트 구성"] .
** 테넌트: 테넌트 매칭은 액세스 키 ID를 사용합니다.  요청에 액세스 키 ID가 포함되어 있지 않으면(예: 익명 액세스) 액세스된 버킷의 소유권을 사용하여 테넌트를 결정합니다.




 a| 
역매칭
 a| 
방금 정의한 유형 및 일치 값과 일치하는 트래픽을 제외한 모든 네트워크 트래픽을 일치시키려면 *역 일치* 확인란을 선택합니다.  그렇지 않으면 확인란을 선택하지 마세요.

예를 들어, 이 정책을 모든 로드 밸런서 엔드포인트에 적용하려면 제외할 로드 밸런서 엔드포인트를 지정하고 *역 일치*를 선택합니다.

최소한 하나가 역 매처인 여러 매처가 포함된 정책의 경우 모든 요청과 일치하는 정책을 만들지 않도록 주의하세요.

|===
. 선택적으로 *제한 추가*를 선택하고 다음 세부 정보를 선택하여 규칙에 따라 일치하는 네트워크 트래픽을 제어하기 위한 하나 이상의 제한을 추가합니다.
+

NOTE: StorageGRID 제한을 두지 않아도 측정 항목을 수집하므로 트래픽 추세를 파악할 수 있습니다.

+
[cols="1a,3a"]
|===
| 필드 | 설명 


 a| 
유형
 a| 
규칙에 따라 일치하는 네트워크 트래픽에 적용하려는 제한 유형입니다.  예를 들어, 대역폭이나 요청 속도를 제한할 수 있습니다.

*참고*: 전체 대역폭을 제한하거나 요청당 대역폭을 제한하는 정책을 만들 수 있습니다.  하지만 StorageGRID 두 가지 유형의 대역폭을 동시에 제한할 수 없습니다.  집계 대역폭이 사용 중이면 요청당 대역폭을 사용할 수 없습니다.  반대로, 요청당 대역폭이 사용 중이면 전체 대역폭을 사용할 수 없습니다.  총 대역폭 제한은 제한되지 않은 트래픽에 추가적인 사소한 성능 영향을 미칠 수 있습니다.

대역폭 제한의 경우 StorageGRID 설정된 제한 유형에 가장 적합한 정책을 적용합니다.  예를 들어, 단방향으로만 트래픽을 제한하는 정책이 있는 경우, 대역폭 제한이 있는 추가 정책과 일치하는 트래픽이 있더라도 반대 방향의 트래픽은 무제한이 됩니다.  StorageGRID 다음 순서에 따라 대역폭 제한에 대한 "최상의" 일치 항목을 구현합니다.

** 정확한 IP 주소(/32 마스크)
** 정확한 버킷 이름
** 버킷 정규식
** 거주자
** 엔드포인트
** 정확하지 않은 CIDR 일치(/32 아님)
** 역매칭




 a| 
적용 대상
 a| 
이 제한이 클라이언트 읽기 요청(GET 또는 HEAD)에 적용되는지, 쓰기 요청(PUT, POST 또는 DELETE)에 적용되는지 여부입니다.



 a| 
가치
 a| 
선택한 단위에 따라 네트워크 트래픽이 제한되는 값입니다.  예를 들어, 10을 입력하고 MiB/s를 선택하면 이 규칙에 따라 일치하는 네트워크 트래픽이 10MiB/s를 초과하지 않습니다.

*참고*: 단위 설정에 따라 사용 가능한 단위는 이진수(예: GiB) 또는 십진수(예: GB)입니다.  단위 설정을 변경하려면 그리드 관리자의 오른쪽 상단에 있는 사용자 드롭다운을 선택한 다음, *사용자 기본 설정*을 선택하세요.



 a| 
단위
 a| 
입력한 값을 설명하는 단위입니다.

|===
+
예를 들어, SLA 계층에 대해 40GB/s 대역폭 제한을 생성하려면 GET/HEAD(40GB/s) 및 PUT/POST/DELETE(40GB/s)의 두 가지 집계 대역폭 제한을 생성합니다.

. *계속*을 선택하세요.
. 트래픽 분류 정책을 읽고 검토하세요.  *이전* 버튼을 사용하여 뒤로 돌아가서 필요한 대로 변경하세요.  정책에 만족하면 *저장하고 계속*을 선택하세요.
+
S3 클라이언트 트래픽은 이제 트래픽 분류 정책에 따라 처리됩니다.



.당신이 완료한 후
link:viewing-network-traffic-metrics.html["네트워크 트래픽 메트릭 보기"]교통 제한이 예상대로 시행되고 있는지 확인하세요.
