---
permalink: admin/creating-tenant-account.html 
sidebar: sidebar 
keywords: create tenant, tenant account 
summary: StorageGRID 시스템의 스토리지에 대한 액세스를 제어하려면 최소한 하나의 테넌트 계정을 만들어야 합니다. 
---
= 테넌트 계정 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템의 스토리지에 대한 액세스를 제어하려면 최소한 하나의 테넌트 계정을 만들어야 합니다.

테넌트 계정을 만드는 단계는 다음에 따라 다릅니다.link:using-identity-federation.html["ID 연합"] 그리고link:configuring-sso.html["단일 로그인"] 구성되었는지 여부와 테넌트 계정을 만드는 데 사용하는 Grid Manager 계정이 루트 액세스 권한이 있는 관리자 그룹에 속하는지 여부입니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:admin-group-permissions.html["루트 액세스 또는 테넌트 계정 권한"] .
* 테넌트 계정이 Grid Manager에 대해 구성된 ID 소스를 사용하고, 페더레이션 그룹에 테넌트 계정에 대한 루트 액세스 권한을 부여하려는 경우, 해당 페더레이션 그룹을 Grid Manager로 가져온 것입니다.  이 관리자 그룹에는 Grid Manager 권한을 할당할 필요가 없습니다. 보다 link:managing-admin-groups.html["관리자 그룹 관리"] .
* 그리드 페더레이션 연결을 사용하여 S3 테넌트가 계정 데이터를 복제하고 버킷 객체를 다른 그리드에 복제하도록 허용하려면 다음을 수행합니다.
+
** 당신은 가지고있다link:grid-federation-create-connection.html["그리드 페더레이션 연결을 구성했습니다."] .
** 연결 상태는 *연결됨*입니다.
** 루트 접근 권한이 있습니다.
** 고려 사항을 검토했습니다.link:grid-federation-manage-tenants.html["그리드 연합을 위한 허용된 세입자 관리"] .
** 테넌트 계정이 Grid Manager에 대해 구성된 ID 소스를 사용하는 경우 두 그리드 모두에서 동일한 페더레이션 그룹을 Grid Manager로 가져온 것입니다.
+
테넌트를 생성할 때 소스 및 대상 테넌트 계정 모두에 대한 초기 루트 액세스 권한을 갖도록 이 그룹을 선택합니다.

+

TIP: 테넌트를 생성하기 전에 두 그리드 모두에 이 관리자 그룹이 존재하지 않으면 테넌트가 대상에 복제되지 않습니다.







== 마법사에 접속하세요

.단계
. *임차인*을 선택하세요.
. *만들기*를 선택하세요.




== 세부 정보를 입력하세요

.단계
. 세입자에 대한 세부 정보를 입력하세요.
+
[cols="1a,3a"]
|===
| 필드 | 설명 


 a| 
이름
 a| 
테넌트 계정의 이름입니다.  세입자 이름은 고유할 필요가 없습니다.  테넌트 계정이 생성되면 고유한 20자리 계정 ID를 받습니다.



 a| 
설명(선택 사항)
 a| 
세입자를 식별하는 데 도움이 되는 설명입니다.

그리드 페더레이션 연결을 사용할 테넌트를 생성하는 경우, 선택적으로 이 필드를 사용하여 어떤 테넌트가 소스 테넌트이고 어떤 테넌트가 대상 테넌트인지 식별할 수 있습니다.  예를 들어, 그리드 1에서 생성된 테넌트에 대한 이 설명은 그리드 2에 복제된 테넌트에도 나타납니다. "이 테넌트는 그리드 1에서 생성되었습니다."



 a| 
클라이언트 유형
 a| 
이 테넌트가 사용할 클라이언트 프로토콜 유형은 *S3* 또는 *Swift*입니다.

*참고*: Swift 클라이언트 애플리케이션에 대한 지원이 더 이상 제공되지 않으며 향후 릴리스에서 제거될 예정입니다.



 a| 
저장 용량 할당량(선택 사항)
 a| 
이 세입자에게 저장 공간 할당량을 지정하려면 할당량과 단위에 대한 숫자 값을 입력하세요.

|===
. *계속*을 선택하세요.




== [[admin-tenant-select-permissions]]권한 선택

.단계
. 선택적으로 이 테넌트에게 부여할 기본 권한을 선택합니다.
+

NOTE: 이러한 권한 중 일부에는 추가 요구 사항이 있습니다.  자세한 내용을 보려면 각 권한에 대한 도움말 아이콘을 선택하세요.

+
[cols="1a,3a"]
|===
| 허가 | 선택하면... 


 a| 
플랫폼 서비스 허용
 a| 
세입자는 CloudMirror와 같은 S3 플랫폼 서비스를 사용할 수 있습니다. 보다 link:../admin/manage-platform-services-for-tenants.html["S3 테넌트 계정에 대한 플랫폼 서비스 관리"] .



 a| 
자체 ID 소스 사용
 a| 
테넌트는 연합된 그룹과 사용자에 대한 자체 ID 소스를 구성하고 관리할 수 있습니다. 이 옵션은 다음 경우 비활성화됩니다.link:../admin/configuring-sso.html["구성된 SSO"] StorageGRID 시스템용.



 a| 
S3 선택 허용
 a| 
테넌트는 S3 SelectObjectContent API 요청을 발행하여 객체 데이터를 필터링하고 검색할 수 있습니다. 보다 link:../admin/manage-s3-select-for-tenant-accounts.html["테넌트 계정에 대한 S3 Select 관리"] .

*중요*: SelectObjectContent 요청은 모든 S3 클라이언트와 모든 테넌트의 로드 밸런서 성능을 저하시킬 수 있습니다.  이 기능은 필요할 때에만, 신뢰할 수 있는 세입자에게만 활성화하세요.

|===
. 선택적으로 이 테넌트에게 부여할 고급 권한을 선택합니다.
+
[cols="1a,3a"]
|===
| 허가 | 선택하면... 


 a| 
그리드 연합 연결
 a| 
세입자는 다음과 같은 그리드 연합 연결을 사용할 수 있습니다.

** 이 테넌트와 해당 계정에 추가된 모든 테넌트 그룹 및 사용자가 이 그리드(_소스 그리드_)에서 선택한 연결의 다른 그리드(_대상 그리드_)로 복제됩니다.
** 이 테넌트가 각 그리드의 해당 버킷 간에 크로스 그리드 복제를 구성할 수 있도록 합니다.


보다 link:../admin/grid-federation-manage-tenants.html["그리드 연합을 위한 허용된 세입자 관리"] .



 a| 
S3 객체 잠금
 a| 
세입자가 S3 개체 잠금의 특정 기능을 사용하도록 허용:

** *최대 보존 기간 설정*은 이 버킷에 추가된 새 객체를 수집한 시점부터 최대 보존 기간을 정의합니다.
** *규정 준수 모드 허용*은 사용자가 보존 기간 동안 보호된 개체 버전을 덮어쓰거나 삭제하는 것을 방지합니다.


|===
. *계속*을 선택하세요.




== 루트 액세스를 정의하고 테넌트를 생성합니다.

.단계
. StorageGRID 시스템에서 ID 페더레이션, SSO(Single Sign-On) 또는 둘 다를 사용하는지 여부에 따라 테넌트 계정에 대한 루트 액세스를 정의합니다.
+
[cols="1a,2a"]
|===
| 옵션 | 이것을 하세요 


 a| 
ID 페더레이션이 활성화되지 않은 경우
 a| 
로컬 루트 사용자로 테넌트에 로그인할 때 사용할 비밀번호를 지정합니다.



 a| 
ID 페더레이션이 활성화된 경우
 a| 
.. 테넌트에 대한 루트 액세스 권한을 부여할 기존 페더레이션 그룹을 선택합니다.
.. 선택적으로 로컬 루트 사용자로 테넌트에 로그인할 때 사용할 비밀번호를 지정합니다.




 a| 
ID 페더레이션과 SSO(Single Sign-On)가 모두 활성화된 경우
 a| 
테넌트에 대한 루트 액세스 권한을 부여할 기존 페더레이션 그룹을 선택합니다.  로컬 사용자는 로그인할 수 없습니다.

|===
. *테넌트 생성*을 선택하세요.
+
성공 메시지가 나타나고 새 테넌트가 테넌트 페이지에 나열됩니다.  세입자 세부 정보를 보고 세입자 활동을 모니터링하는 방법을 알아보려면 다음을 참조하세요.link:../monitor/monitoring-tenant-activity.html["세입자 활동 모니터링"] .

+

NOTE: 네트워크 연결, 노드 상태 및 Cassandra 작업에 따라 그리드 전체에 테넌트 설정을 적용하는 데 15분 이상 걸릴 수 있습니다.

. 테넌트에 대해 *그리드 페더레이션 연결 사용* 권한을 선택한 경우:
+
.. 연결의 다른 그리드에 동일한 테넌트가 복제되었는지 확인합니다.  두 그리드의 테넌트는 모두 동일한 20자리 계정 ID, 이름, 설명, 할당량 및 권한을 갖습니다.
+

NOTE: "복제본 없이 테넌트가 생성되었습니다"라는 오류 메시지가 표시되면 다음 지침을 참조하세요.link:grid-federation-troubleshoot.html["그리드 페더레이션 오류 문제 해결"] .

.. 루트 액세스를 정의할 때 로컬 루트 사용자 비밀번호를 제공한 경우link:changing-password-for-tenant-local-root-user.html["로컬 루트 사용자의 비밀번호를 변경합니다"] 복제된 테넌트에 대해.
+

TIP: 로컬 루트 사용자는 비밀번호가 변경될 때까지 대상 그리드의 테넌트 관리자에 로그인할 수 없습니다.







== 테넌트에 Sign in (선택 사항)

필요에 따라 지금 새 테넌트에 로그인하여 구성을 완료할 수도 있고, 나중에 테넌트에 로그인할 수도 있습니다.  로그인 단계는 기본 포트(443)를 사용하여 Grid Manager에 로그인했는지 아니면 제한된 포트를 사용하여 로그인했는지에 따라 달라집니다. 보다 link:controlling-access-through-firewalls.html["외부 방화벽에서 접근 제어"] .



=== 지금 Sign in

[cols="1a,3a"]
|===
| 만약 당신이 사용하고 있다면... | 이렇게 하세요... 


 a| 
포트 443을 사용하고 로컬 루트 사용자에 대한 비밀번호를 설정합니다.
 a| 
. *루트로 Sign in *을 선택하세요.
+
로그인하면 버킷, ID 페더레이션, 그룹 및 사용자를 구성하기 위한 링크가 나타납니다.

. 테넌트 계정을 구성하려면 링크를 선택하세요.
+
각 링크를 클릭하면 테넌트 관리자의 해당 페이지가 열립니다.  페이지를 완성하려면 다음을 참조하세요.link:../tenant/index.html["테넌트 계정 사용 지침"] .





 a| 
포트 443이고 로컬 루트 사용자에 대한 비밀번호를 설정하지 않았습니다.
 a| 
* Sign in*을 선택하고 루트 액세스 페더레이션 그룹의 사용자 자격 증명을 입력합니다.



 a| 
제한된 항구
 a| 
. *마침*을 선택하세요
. 테넌트 계정에 액세스하는 방법에 대한 자세한 내용을 알아보려면 테넌트 표에서 *제한됨*을 선택하세요.
+
테넌트 관리자의 URL 형식은 다음과 같습니다.

+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_`정규화된 도메인 이름 또는 관리 노드의 IP 주소입니다.
** `_port_`테넌트 전용 포트입니다
** `_20-digit-account-id_`세입자의 고유 계정 ID입니다.




|===


=== 나중에 Sign in

[cols="1a,3a"]
|===
| 만약 당신이 사용하고 있다면... | 다음 중 하나를 하세요... 


 a| 
포트 443
 a| 
* 그리드 관리자에서 *테넌트*를 선택하고 테넌트 이름 오른쪽에 있는 * Sign in*을 선택합니다.
* 웹 브라우저에 세입자의 URL을 입력하세요:
+
`https://_FQDN_or_Admin_Node_IP_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_`정규화된 도메인 이름 또는 관리 노드의 IP 주소입니다.
** `_20-digit-account-id_`세입자의 고유 계정 ID입니다.






 a| 
제한된 항구
 a| 
* 그리드 관리자에서 *테넌트*를 선택하고 *제한됨*을 선택합니다.
* 웹 브라우저에 세입자의 URL을 입력하세요:
+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_`

+
** `_FQDN_or_Admin_Node_IP_`정규화된 도메인 이름 또는 관리 노드의 IP 주소입니다.
** `_port_`세입자만 출입이 가능한 제한 포트입니다.
** `_20-digit-account-id_`세입자의 고유 계정 ID입니다.




|===


== 테넌트 구성

지침을 따르세요link:../tenant/index.html["세입자 계정 사용"] 테넌트 그룹 및 사용자, S3 액세스 키, 버킷, 플랫폼 서비스, 계정 복제 및 크로스 그리드 복제를 관리합니다.
