---
permalink: admin/deactivate-features-from-api.html 
sidebar: sidebar 
keywords: deactivate features from api 
summary: Grid Management API를 사용하면 StorageGRID 시스템의 특정 기능을 완전히 비활성화할 수 있습니다.  기능이 비활성화되면 아무에게도 해당 기능과 관련된 작업을 수행할 수 있는 권한을 할당할 수 없습니다. 
---
= API를 사용하여 기능 비활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid Management API를 사용하면 StorageGRID 시스템의 특정 기능을 완전히 비활성화할 수 있습니다.  기능이 비활성화되면 아무에게도 해당 기능과 관련된 작업을 수행할 수 있는 권한을 할당할 수 없습니다.

.이 작업에 관하여
비활성화된 기능 시스템을 사용하면 StorageGRID 시스템의 특정 기능에 대한 액세스를 방지할 수 있습니다.  기능을 비활성화하는 것은 루트 사용자나 *루트 접근* 권한이 있는 관리자 그룹에 속한 사용자가 해당 기능을 사용하지 못하도록 하는 유일한 방법입니다.

이 기능이 어떻게 유용한지 알아보려면 다음 시나리오를 고려해 보세요.

_회사 A는 테넌트 계정을 생성하여 StorageGRID 시스템의 저장 용량을 임대하는 서비스 제공업체입니다.  임차인의 물건에 대한 보안을 보호하기 위해 회사 A는 계정이 배포된 후에는 자사 직원이 임차인 계정에 절대 액세스할 수 없도록 하려고 합니다.

회사 A는 그리드 관리 API의 기능 비활성화 시스템을 사용하여 이 목표를 달성할 수 있습니다.  회사 A는 그리드 관리자(UI와 API 모두)에서 *테넌트 루트 비밀번호 변경* 기능을 완전히 비활성화하여 루트 사용자와 *루트 액세스* 권한이 있는 그룹에 속한 사용자를 포함한 관리자 사용자가 모든 테넌트 계정의 루트 사용자 비밀번호를 변경할 수 없도록 합니다.

.단계
. Grid Management API에 대한 Swagger 설명서를 확인하세요. 보다 link:using-grid-management-api.html["그리드 관리 API 사용"] .
. 비활성화 기능 엔드포인트를 찾습니다.
. 테넌트 루트 비밀번호 변경과 같은 기능을 비활성화하려면 다음과 같이 API에 본문을 보내세요.
+
`{ "grid": {"changeTenantRootPassword": true} }`

+
요청이 완료되면 테넌트 루트 비밀번호 변경 기능이 비활성화됩니다.  *테넌트 루트 비밀번호 변경* 관리 권한이 더 이상 사용자 인터페이스에 나타나지 않으며, 테넌트의 루트 비밀번호를 변경하려는 모든 API 요청은 "403 Forbidden"이라는 오류 메시지와 함께 실패합니다.





== 비활성화된 기능 다시 활성화

기본적으로 Grid Management API를 사용하면 비활성화된 기능을 다시 활성화할 수 있습니다.  하지만 비활성화된 기능이 다시 활성화되는 것을 방지하려면 *activateFeatures* 기능 자체를 비활성화하면 됩니다.


CAUTION: *activateFeatures* 기능은 다시 활성화할 수 없습니다.  이 기능을 비활성화하기로 결정하면 다른 비활성화된 기능을 다시 활성화할 수 있는 능력을 영구적으로 잃게 된다는 점을 알아두세요.  손실된 기능을 복구하려면 기술 지원팀에 문의해야 합니다.

.단계
. Grid Management API에 대한 Swagger 설명서를 확인하세요.
. 비활성화 기능 엔드포인트를 찾습니다.
. 모든 기능을 다시 활성화하려면 다음과 같이 API에 본문을 보내세요.
+
`{ "grid": null }`

+
이 요청이 완료되면 테넌트 루트 비밀번호 변경 기능을 포함한 모든 기능이 다시 활성화됩니다.  *테넌트 루트 비밀번호 변경* 관리 권한이 이제 사용자 인터페이스에 표시되며, 테넌트의 루트 비밀번호를 변경하려는 모든 API 요청은 사용자에게 *루트 액세스* 또는 *테넌트 루트 비밀번호 변경* 관리 권한이 있는 경우 성공합니다.




TIP: 이전 예제에서는 비활성화된 모든 기능이 다시 활성화됩니다.  비활성화된 상태로 유지되어야 하는 다른 기능이 비활성화된 경우 PUT 요청에서 해당 기능을 명시적으로 지정해야 합니다.  예를 들어, 테넌트 루트 비밀번호 변경 기능을 다시 활성화하고 storageAdmin 관리 권한을 계속 비활성화하려면 다음 PUT 요청을 보내세요.
`{ "grid": {"storageAdmin": true} }`
