---
permalink: admin/grid-federation-retry-failed-replication.html 
sidebar: sidebar 
keywords: grid federation, troubleshoot 
summary: 크로스 그리드 복제 영구 실패 경고를 해결한 후에는 다른 그리드에 개체나 삭제 마커를 복제하는 데 실패했는지 확인해야 합니다.  그런 다음 이러한 객체를 다시 수집하거나 Grid Management API를 사용하여 복제를 다시 시도할 수 있습니다. 
---
= 실패한 복제 작업을 식별하고 다시 시도합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*크로스 그리드 복제 영구 실패* 경고를 해결한 후에는 다른 그리드에 개체나 삭제 마커를 복제하는 데 실패했는지 확인해야 합니다.  그런 다음 이러한 객체를 다시 수집하거나 Grid Management API를 사용하여 복제를 다시 시도할 수 있습니다.

*크로스 그리드 복제 영구 실패* 경고는 사용자 개입이 필요한 이유로 두 그리드의 버킷 간에 테넌트 개체를 복제할 수 없음을 나타냅니다.  이 알림은 일반적으로 소스 또는 대상 버킷이 변경되면 발생합니다. 자세한 내용은 다음을 참조하십시오. link:grid-federation-troubleshoot.html["그리드 페더레이션 오류 문제 해결"] .



== 복제에 실패한 개체가 있는지 확인합니다.

다른 그리드에 개체나 삭제 마커가 복제되지 않았는지 확인하려면 감사 로그를 검색할 수 있습니다.link:../audit/cgrr-cross-grid-replication-request.html["CGRR(크로스 그리드 복제 요청)"] 메시지.  이 메시지는 StorageGRID 대상 버킷에 개체, 다중 파트 개체 또는 삭제 마커를 복제하지 못할 때 로그에 추가됩니다.

당신은 사용할 수 있습니다link:../audit/using-audit-explain-tool.html["감사 설명 도구"] 결과를 읽기 쉬운 형식으로 번역합니다.

.시작하기 전에
* 루트 접근 권한이 있습니다.
* 당신은 가지고있다 `Passwords.txt` 파일.
* 기본 관리 노드의 IP 주소를 알고 있습니다.


.단계
. 기본 관리 노드에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh admin@_primary_Admin_Node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. audit.log에서 CGRR 메시지를 검색하고 audit-explain 도구를 사용하여 결과를 형식화합니다.
+
예를 들어, 이 명령은 지난 30분 동안의 모든 CGRR 메시지를 grep하여 검색하고 audit-explain 도구를 사용합니다.

+
`# awk -vdate=$(date -d "30 minutes ago" '+%Y-%m-%dT%H:%M:%S') '$1$2 >= date { print }' audit.log | grep CGRR | audit-explain`

+
명령의 결과는 6개의 CGRR 메시지에 대한 항목이 있는 이 예제와 같습니다.  이 예에서 모든 크로스 그리드 복제 요청은 객체를 복제할 수 없기 때문에 일반 오류를 반환했습니다.  처음 세 가지 오류는 "개체 복제" 작업에 대한 것이고, 마지막 세 가지 오류는 "마커 삭제 복제" 작업에 대한 것입니다.

+
[listing]
----
CGRR Cross-Grid Replication Request tenant:50736445269627437748 connection:447896B6-6F9C-4FB2-95EA-AEBF93A774E9 operation:"replicate object" bucket:bucket123 object:"audit-0" version:QjRBNDIzODAtNjQ3My0xMUVELTg2QjEtODJBMjAwQkI3NEM4 error:general error
CGRR Cross-Grid Replication Request tenant:50736445269627437748 connection:447896B6-6F9C-4FB2-95EA-AEBF93A774E9 operation:"replicate object" bucket:bucket123 object:"audit-3" version:QjRDOTRCOUMtNjQ3My0xMUVELTkzM0YtOTg1MTAwQkI3NEM4 error:general error
CGRR Cross-Grid Replication Request tenant:50736445269627437748 connection:447896B6-6F9C-4FB2-95EA-AEBF93A774E9 operation:"replicate delete marker" bucket:bucket123 object:"audit-1" version:NUQ0OEYxMDAtNjQ3NC0xMUVELTg2NjMtOTY5NzAwQkI3NEM4 error:general error
CGRR Cross-Grid Replication Request tenant:50736445269627437748 connection:447896B6-6F9C-4FB2-95EA-AEBF93A774E9 operation:"replicate delete marker" bucket:bucket123 object:"audit-5" version:NUQ1ODUwQkUtNjQ3NC0xMUVELTg1NTItRDkwNzAwQkI3NEM4 error:general error
----
+
각 항목에는 다음 정보가 포함되어 있습니다.

+
[cols="1a,2a"]
|===
| 필드 | 설명 


| CGRR 크로스 그리드 복제 요청  a| 
요청의 이름



| 거주자  a| 
세입자 계정 ID



| 연결  a| 
그리드 페더레이션 연결의 ID



| 작업  a| 
시도된 복제 작업의 유형:

** 객체 복제
** 복제 삭제 마커
** 멀티파트 객체 복제




| 버킷  a| 
버킷 이름



| 물체  a| 
객체 이름



| 버전  a| 
객체의 버전 ID



| 오류  a| 
오류의 유형.  크로스 그리드 복제가 실패하면 오류는 "일반 오류"입니다.

|===




== 실패한 복제를 다시 시도하세요

대상 버킷에 복제되지 않은 개체 및 삭제 마커 목록을 생성하고 기본 문제를 해결한 후 다음 두 가지 방법 중 하나로 복제를 다시 시도할 수 있습니다.

* 각 객체를 소스 버킷으로 다시 수집합니다.
* 설명된 대로 Grid Management 개인 API를 사용하세요.


.단계
. 그리드 관리자 상단에서 도움말 아이콘을 선택하고 *API 설명서*를 선택하세요.
. *비공개 API 문서로 이동*을 선택하세요.
+

NOTE: "비공개"로 표시된 StorageGRID API 엔드포인트는 사전 고지 없이 변경될 수 있습니다.  StorageGRID 개인 엔드포인트는 요청의 API 버전도 무시합니다.

. *cross-grid-replication-advanced* 섹션에서 다음 엔드포인트를 선택하세요.
+
`POST /private/cross-grid-replication-retry-failed`

. *시도해보기*를 선택하세요.
. *본문* 텍스트 상자에서 *versionID*에 대한 예제 항목을 실패한 크로스 그리드 복제 요청에 해당하는 audit.log의 버전 ID로 바꿉니다.
+
문자열 주위에 큰따옴표를 꼭 넣어주세요.

. *실행*을 선택하세요.
. 서버 응답 코드가 *204*인지 확인하세요. 이는 개체 또는 삭제 마커가 다른 그리드로의 교차 그리드 복제를 위해 보류 중으로 표시되었음을 나타냅니다.
+

NOTE: 보류 중은 크로스 그리드 복제 요청이 처리를 위해 내부 대기열에 추가되었음을 의미합니다.





== 복제 재시도 모니터링

복제 재시도 작업이 완료되는지 모니터링해야 합니다.


TIP: 개체나 삭제 마커를 다른 그리드에 복제하는 데는 몇 시간 이상 걸릴 수 있습니다.

다음 두 가지 방법 중 하나로 재시도 작업을 모니터링할 수 있습니다.

* S3를 사용하세요link:../s3/head-object.html["헤드오브젝트"] 또는link:../s3/get-object.html["객체 가져오기"] 요구.  응답에는 StorageGRID 관련 내용이 포함됩니다. `x-ntap-sg-cgr-replication-status` 응답 헤더는 다음 값 중 하나를 갖습니다.
+
[cols="1a,2a"]
|===
| 그리드 | 복제 상태 


 a| 
원천
 a| 
** *완료*: 복제가 성공했습니다.
** *보류*: 객체가 아직 복제되지 않았습니다.
** *실패*: 복제가 영구적인 오류로 실패했습니다. 사용자는 오류를 해결해야 합니다.




 a| 
목적지
 a| 
*REPLICA*: 개체가 소스 그리드에서 복제되었습니다.

|===
* 설명된 대로 Grid Management 개인 API를 사용하세요.


.단계
. 개인 API 설명서의 *cross-grid-replication-advanced* 섹션에서 다음 엔드포인트를 선택하세요.
+
`GET /private/cross-grid-replication-object-status/{id}`

. *시도해보기*를 선택하세요.
. 매개변수 섹션에서 사용한 버전 ID를 입력하세요. `cross-grid-replication-retry-failed` 요구.
. *실행*을 선택하세요.
. 서버 응답 코드가 *200*인지 확인하세요.
. 복제 상태를 검토하세요. 다음 중 하나입니다.
+
** *보류*: 객체가 아직 복제되지 않았습니다.
** *완료*: 복제가 성공했습니다.
** *실패*: 복제가 영구적인 오류로 실패했습니다. 사용자는 오류를 해결해야 합니다.



