---
permalink: admin/grid-management-api-operations.html 
sidebar: sidebar 
keywords: Grid Management API,  API operations 
summary: 그리드 관리 API는 사용 가능한 API 작업을 다음 섹션으로 구성합니다. 
---
= 그리드 관리 API 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리 API는 사용 가능한 작업을 다음 섹션으로 구성합니다.


NOTE: 이 목록에는 공개 API에서 사용할 수 있는 작업만 포함되어 있습니다.

* *계정*: 새 계정을 만들고 해당 계정의 스토리지 사용량을 검색하는 등 스토리지 테넌트 계정을 관리하는 작업입니다.
* *alert-history*: 해결된 경고에 대한 작업입니다.
* *alert-receivers*: 경고 알림 수신기(이메일)에 대한 작업입니다.
* *alert-rules*: 경고 규칙에 대한 작업입니다.
* *경고-침묵*: 경보 침묵에 대한 작업입니다.
* *알림*: 알림에 따른 작업입니다.
* *감사*: 감사 구성을 나열하고 업데이트하는 작업입니다.
* *auth*: 사용자 세션 인증을 수행하는 작업입니다.
+
그리드 관리 API는 베어러 토큰 인증 체계를 지원합니다.  로그인하려면 인증 요청의 JSON 본문에 사용자 이름과 비밀번호를 제공합니다(즉, `POST /api/v3/authorize` ).  사용자가 성공적으로 인증되면 보안 토큰이 반환됩니다.  이 토큰은 후속 API 요청의 헤더에 제공되어야 합니다("Authorization: Bearer _token_").  토큰은 16시간 후에 만료됩니다.

+

NOTE: StorageGRID 시스템에 대해 Single Sign-On이 활성화된 경우 인증을 위해 여러 단계를 수행해야 합니다.  "단일 로그인이 활성화된 경우 API에 인증하기"를 참조하세요.

+
인증 보안을 개선하는 방법에 대한 자세한 내용은 "교차 사이트 요청 위조 방지"를 참조하세요.

* *클라이언트 인증서*: 외부 모니터링 도구를 사용하여 StorageGRID 안전하게 액세스할 수 있도록 클라이언트 인증서를 구성하는 작업입니다.
* *config*: Grid Management API의 제품 릴리스 및 버전과 관련된 작업입니다.  해당 릴리스에서 지원하는 Grid Management API의 제품 릴리스 버전과 주요 버전을 나열할 수 있으며, 더 이상 사용되지 않는 API 버전을 비활성화할 수 있습니다.
* *deactivated-features*: 비활성화되었을 수 있는 기능을 확인하는 작업입니다.
* *dns-servers*: 구성된 외부 DNS 서버를 나열하고 변경하는 작업입니다.
* *드라이브-세부정보*: 특정 스토리지 어플라이언스 모델의 드라이브에 대한 작업입니다.
* *endpoint-domain-names*: S3 엔드포인트 도메인 이름을 나열하고 변경하는 작업입니다.
* *erasure-coding*: 삭제 코딩 프로필에 대한 작업.
* *확장*: 확장 작업(절차 수준).
* *확장 노드*: 확장 작업(노드 수준)
* *확장 사이트*: 확장 작업(사이트 수준).
* *grid-networks*: 그리드 네트워크 목록을 나열하고 변경하는 작업입니다.
* *grid-passwords*: 그리드 비밀번호 관리를 위한 작업입니다.
* *그룹*: 로컬 그리드 관리자 그룹을 관리하고 외부 LDAP 서버에서 연합된 그리드 관리자 그룹을 검색하는 작업입니다.
* *identity-source*: 외부 ID 소스를 구성하고 페더레이션 그룹 및 사용자 정보를 수동으로 동기화하는 작업입니다.
* *ilm*: 정보 수명 주기 관리(ILM)에 대한 운영.
* *in-progress-procedures*: 현재 진행 중인 유지 관리 절차를 검색합니다.
* *라이선스*: StorageGRID 라이선스를 검색하고 업데이트하는 작업입니다.
* *로그*: 로그 파일을 수집하고 다운로드하는 작업.v
* *메트릭*: 단일 시점에서의 즉각적인 메트릭 쿼리와 일정 시간 범위에 걸친 범위 메트릭 쿼리를 포함한 StorageGRID 메트릭에 대한 작업입니다.  Grid Management API는 Prometheus 시스템 모니터링 도구를 백엔드 데이터 소스로 사용합니다.  Prometheus 쿼리를 구성하는 방법에 대한 자세한 내용은 Prometheus 웹 사이트를 참조하세요.
+

NOTE: 다음을 포함하는 측정항목``_private_`` 이름에 있는 모든 단어는 내부적으로만 사용하도록 의도되었습니다.  이러한 측정항목은 StorageGRID 릴리스 간에 사전 고지 없이 변경될 수 있습니다.

* *노드-세부정보*: 노드 세부정보에 대한 작업입니다.
* *node-health*: 노드 상태 관련 작업입니다.
* *node-storage-state*: 노드 저장소 상태에 대한 작업입니다.
* *ntp-servers*: 외부 네트워크 시간 프로토콜(NTP) 서버를 나열하거나 업데이트하는 작업입니다.
* *객체*: 객체 및 객체 메타데이터에 대한 작업입니다.
* *복구*: 복구 절차를 위한 작업.
* *복구 패키지*: 복구 패키지를 다운로드하는 작업입니다.
* *지역*: 지역을 보고 생성하는 작업입니다.
* *s3-object-lock*: 글로벌 S3 객체 잠금 설정에 대한 작업입니다.
* *server-certificate*: Grid Manager 서버 인증서를 보고 업데이트하는 작업입니다.
* *snmp*: 현재 SNMP 구성에 대한 작업입니다.
* *storage-watermarks*: 스토리지 노드 워터마크.
* *트래픽 클래스*: 트래픽 분류 정책에 대한 작업입니다.
* *untrusted-client-network*: 신뢰할 수 없는 클라이언트 네트워크 구성에 대한 작업입니다.
* *사용자*: Grid Manager 사용자를 보고 관리하는 작업입니다.

