---
permalink: admin/grid-federation-compare-cgr-to-cloudmirror.html 
sidebar: sidebar 
keywords: cross-grid replication, cloudmirror replication 
summary: 그리드 페더레이션을 사용하기 시작하면 크로스 그리드 복제와 StorageGRID CloudMirror 복제 서비스 간의 유사점과 차이점을 검토하세요. 
---
= 크로스 그리드 복제와 CloudMirror 복제 비교
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 연합을 사용하기 시작하면 다음 간의 유사점과 차이점을 검토하십시오.link:grid-federation-what-is-cross-grid-replication.html["크로스 그리드 복제"] 그리고link:../tenant/understanding-cloudmirror-replication-service.html["StorageGRID CloudMirror 복제 서비스"] .

[cols="1a,3a,3a"]
|===
|  | 크로스 그리드 복제 | CloudMirror 복제 서비스 


 a| 
주된 목적은 무엇입니까?
 a| 
하나의 StorageGRID 시스템은 재해 복구 시스템 역할을 합니다.  버킷에 있는 객체는 한 방향 또는 두 방향 모두로 그리드 간에 복제될 수 있습니다.
 a| 
테넌트가 StorageGRID (소스)의 버킷에서 외부 S3 버킷(대상)으로 객체를 자동으로 복제할 수 있도록 합니다.

CloudMirror 복제는 독립적인 S3 인프라에서 객체의 독립적인 사본을 생성합니다. 이러한 독립적인 사본은 백업으로 사용되지 않지만, 종종 클라우드에서 추가 처리됩니다.



 a| 
어떻게 설정되나요?
 a| 
. 두 개의 그리드 간에 그리드 연합 연결을 구성합니다.
. 다른 그리드에 자동으로 복제되는 새로운 테넌트 계정을 추가합니다.
. 새로운 테넌트 그룹과 사용자를 추가하고, 이들도 복제합니다.
. 각 그리드에 해당 버킷을 만들고 그리드 간 복제가 한 방향 또는 양방향으로 발생하도록 합니다.

 a| 
. 테넌트 사용자는 테넌트 관리자 또는 S3 API를 사용하여 CloudMirror 엔드포인트(IP 주소, 자격 증명 등)를 정의하여 CloudMirror 복제를 구성합니다.
. 해당 테넌트 계정이 소유한 모든 버킷은 CloudMirror 엔드포인트를 가리키도록 구성할 수 있습니다.




 a| 
이를 설정하는 책임은 누구에게 있나요?
 a| 
* 그리드 관리자는 연결과 테넌트를 구성합니다.
* 테넌트 사용자는 그룹, 사용자, 키, 버킷을 구성합니다.

 a| 
일반적으로 세입자 사용자입니다.



 a| 
목적지는 어디인가요?
 a| 
그리드 페더레이션 연결의 다른 StorageGRID 시스템에 있는 해당하고 동일한 S3 버킷.
 a| 
* 호환 가능한 모든 S3 인프라(Amazon S3 포함).
* 구글 클라우드 플랫폼(GCP)




 a| 
객체 버전 관리가 필요합니까?
 a| 
네, 소스 버킷과 대상 버킷 모두에서 개체 버전 관리가 활성화되어 있어야 합니다.
 a| 
아니요, CloudMirror 복제는 소스와 대상 모두에서 버전이 지정되지 않은 버킷과 버전이 지정된 버킷의 모든 조합을 지원합니다.



 a| 
물체가 목적지로 이동하게 하는 원인은 무엇인가?
 a| 
버킷에 크로스 그리드 복제가 활성화되면 해당 객체가 자동으로 복제됩니다.
 a| 
CloudMirror 엔드포인트로 구성된 버킷에 개체가 추가되면 해당 개체가 자동으로 복제됩니다.  버킷이 CloudMirror 엔드포인트로 구성되기 전에 소스 버킷에 존재했던 개체는 수정되지 않는 한 복제되지 않습니다.



 a| 
객체는 어떻게 복제되나요?
 a| 
크로스 그리드 복제는 버전이 지정된 객체를 생성하고, 소스 버킷에서 대상 버킷으로 버전 ID를 복제합니다.  이를 통해 두 그리드에서 버전 순서를 유지할 수 있습니다.
 a| 
CloudMirror 복제에는 버전 관리가 활성화된 버킷이 필요하지 않으므로 CloudMirror는 사이트 내의 키에 대한 순서만 유지할 수 있습니다.  다른 사이트의 객체에 대한 요청에 대해 순서가 유지된다는 보장은 없습니다.



 a| 
객체를 복제할 수 없다면 어떻게 되나요?
 a| 
해당 개체는 메타데이터 저장 한도에 따라 복제 대기 중입니다.
 a| 
개체는 플랫폼 서비스 제한에 따라 복제 대기 중입니다(참조).link:manage-platform-services-for-tenants.html["플랫폼 서비스 이용에 대한 권장 사항"] ).



 a| 
객체의 시스템 메타데이터가 복제되었나요?
 a| 
네, 객체가 다른 그리드에 복제되면 해당 시스템 메타데이터도 복제됩니다.  두 그리드의 메타데이터는 동일합니다.
 a| 
아니요. 개체가 외부 버킷에 복제되면 해당 시스템 메타데이터가 업데이트됩니다.  메타데이터는 수집 시간과 독립적인 S3 인프라의 동작에 따라 위치마다 다릅니다.



 a| 
객체는 어떻게 검색되나요?
 a| 
애플리케이션은 두 그리드 중 하나의 버킷에 요청을 보내 객체를 검색하거나 읽을 수 있습니다.
 a| 
애플리케이션은 StorageGRID 또는 S3 대상에 요청을 보내 객체를 검색하거나 읽을 수 있습니다.  예를 들어, CloudMirror 복제를 사용하여 파트너 조직에 객체를 미러링한다고 가정해 보겠습니다.  파트너는 자체 애플리케이션을 사용하여 S3 대상에서 직접 객체를 읽거나 업데이트할 수 있습니다.  StorageGRID 사용할 필요는 없습니다.



 a| 
객체가 삭제되면 어떻게 되나요?
 a| 
* 버전 ID가 포함된 삭제 요청은 대상 그리드에 복제되지 않습니다.
* 버전 ID가 포함되지 않은 삭제 요청은 소스 버킷에 삭제 마커를 추가하며, 이는 선택적으로 대상 그리드에 복제될 수 있습니다.
* 크로스 그리드 복제가 단방향으로만 구성된 경우 대상 버킷의 객체를 소스에 영향을 주지 않고 삭제할 수 있습니다.

 a| 
결과는 소스 버킷과 대상 버킷의 버전 상태에 따라 달라집니다(두 버킷이 동일할 필요는 없음).

* 두 버킷 모두 버전이 관리된 경우 삭제 요청은 두 위치 모두에 삭제 마커를 추가합니다.
* 소스 버킷만 버전이 관리되는 경우 삭제 요청을 하면 소스에는 삭제 마커가 추가되지만 대상에는 추가되지 않습니다.
* 두 버킷 모두 버전이 지정되지 않은 경우 삭제 요청을 하면 소스에서는 개체가 삭제되지만 대상에서는 삭제되지 않습니다.


마찬가지로, 대상 버킷의 객체는 소스에 영향을 주지 않고 삭제될 수 있습니다.

|===