---
permalink: admin/manage-security.html 
sidebar: sidebar 
keywords: how to manage security 
summary: Grid Manager에서 다양한 보안 설정을 구성하여 StorageGRID 시스템을 보호할 수 있습니다. 
---
= 보안 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid Manager에서 다양한 보안 설정을 구성하여 StorageGRID 시스템을 보호할 수 있습니다.



== 암호화 관리

StorageGRID 데이터 암호화를 위한 여러 가지 옵션을 제공합니다.  당신은해야합니다link:reviewing-storagegrid-encryption-methods.html["사용 가능한 암호화 방법을 검토하세요"] 귀하의 데이터 보호 요구 사항을 충족하는 것이 무엇인지 확인하세요.



== 인증서 관리

당신은 할 수 있습니다link:using-storagegrid-security-certificates.html["서버 인증서 구성 및 관리"] HTTP 연결이나 서버에 클라이언트나 사용자 신원을 인증하는 데 사용되는 클라이언트 인증서에 사용됩니다.



== 키 관리 서버 구성

를 사용하여link:kms-configuring.html["키 관리 서버"] 데이터 센터에서 어플라이언스를 제거하더라도 StorageGRID 데이터를 보호할 수 있습니다.  어플라이언스 볼륨이 암호화된 후에는 노드가 KMS와 통신할 수 없는 한 어플라이언스의 어떠한 데이터에도 액세스할 수 없습니다.


NOTE: 암호화 키 관리를 사용하려면 어플라이언스를 그리드에 추가하기 전에 설치 중에 각 어플라이언스에 대해 *노드 암호화* 설정을 활성화해야 합니다.



== 프록시 설정 관리

S3 플랫폼 서비스 또는 클라우드 스토리지 풀을 사용하는 경우 다음을 구성할 수 있습니다.link:configuring-storage-proxy-settings.html["스토리지 프록시 서버"] 스토리지 노드와 외부 S3 엔드포인트 간.  HTTPS 또는 HTTP를 사용하여 AutoSupport 패키지를 보내는 경우 다음을 구성할 수 있습니다.link:configuring-admin-proxy-settings.html["관리자 프록시 서버"] 관리 노드와 기술 지원 사이.



== 방화벽 제어

시스템 보안을 강화하려면 특정 포트를 열거나 닫아 StorageGRID 관리 노드에 대한 액세스를 제어할 수 있습니다.link:controlling-access-through-firewalls.html["외부 방화벽"] .  각 노드에 대한 네트워크 액세스를 구성하여 제어할 수도 있습니다.link:manage-firewall-controls.html["내부 방화벽"] .  배포에 필요한 포트를 제외한 모든 포트에 대한 액세스를 차단할 수 있습니다.
