---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: '테넌트 계정을 사용하면 Simple Storage Service (S3) REST API를 사용하여 StorageGRID 시스템에 객체를 저장하고 검색할 수 있습니다.' 
---
= 세입자 계정이란 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
테넌트 계정을 사용하면 S3(Simple Storage Service) REST API를 사용하여 StorageGRID 시스템에 객체를 저장하고 검색할 수 있습니다.


TIP: 이 버전의 문서 사이트에서는 Swift 세부 정보가 제거되었습니다. 보다 https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8: 테넌트 관리"^] .

그리드 관리자는 S3 클라이언트가 객체를 저장하고 검색하는 데 사용하는 테넌트 계정을 만들고 관리합니다.

각 테넌트 계정에는 연합 또는 로컬 그룹, 사용자, S3 버킷 및 개체가 있습니다.

테넌트 계정은 저장된 객체를 여러 엔터티별로 분리하는 데 사용할 수 있습니다.  예를 들어, 다음 두 가지 사용 사례에 여러 테넌트 계정을 사용할 수 있습니다.

* *기업 사용 사례:* 기업 애플리케이션에서 StorageGRID 시스템을 관리하는 경우 조직의 여러 부서별로 그리드의 개체 스토리지를 분리하고 싶을 수 있습니다.  이 경우 마케팅 부서, 고객 지원 부서, 인사부 등을 위한 테넌트 계정을 만들 수 있습니다.
+

NOTE: S3 클라이언트 프로토콜을 사용하면 S3 버킷과 버킷 정책을 사용하여 기업 내 부서 간에 객체를 분리할 수 있습니다. 세입자 계정을 사용할 필요가 없습니다. 구현에 대한 지침을 참조하세요.link:../s3/bucket-and-group-access-policies.html["S3 버킷 및 버킷 정책"] 자세한 내용은.

* *서비스 공급자 사용 사례:* 서비스 공급자로서 StorageGRID 시스템을 관리하는 경우 그리드의 개체 스토리지를 그리드의 스토리지를 임대할 여러 엔터티로 분리할 수 있습니다.  이 경우 회사 A, 회사 B, 회사 C 등의 순으로 테넌트 계정을 만들면 됩니다.


자세한 내용은 다음을 참조하세요. link:../tenant/index.html["세입자 계정 사용"] .



== 테넌트 계정은 어떻게 만드나요?

그리드 관리자를 사용하여 테넌트 계정을 만듭니다.  테넌트 계정을 생성할 때 다음 정보를 지정합니다.

* 테넌트 이름, 클라이언트 유형(S3), 선택적 스토리지 할당량을 포함한 기본 정보입니다.
* 테넌트 계정에 대한 권한(예: 테넌트 계정이 S3 플랫폼 서비스를 사용할 수 있는지, 자체 ID 소스를 구성할 수 있는지, S3 Select를 사용할 수 있는지, 그리드 페더레이션 연결을 사용할 수 있는지 여부)입니다.
* StorageGRID 시스템이 로컬 그룹 및 사용자, ID 페더레이션 또는 SSO(Single Sign-On)를 사용하는지 여부에 따라 테넌트의 초기 루트 액세스 권한이 결정됩니다.


또한 S3 테넌트 계정이 규정 요구 사항을 준수해야 하는 경우 StorageGRID 시스템에 대해 S3 개체 잠금 설정을 활성화할 수 있습니다.  S3 개체 잠금이 활성화되면 모든 S3 테넌트 계정에서 규정을 준수하는 버킷을 만들고 관리할 수 있습니다.



== 테넌트 관리자는 무엇에 사용되나요?

테넌트 계정을 생성한 후 테넌트 사용자는 테넌트 관리자에 로그인하여 다음과 같은 작업을 수행할 수 있습니다.

* ID 페더레이션 설정(ID 소스가 그리드와 공유되지 않는 경우)
* 그룹 및 사용자 관리
* 계정 복제 및 크로스 그리드 복제에 그리드 페더레이션을 사용합니다.
* S3 액세스 키 관리
* S3 버킷 생성 및 관리
* S3 플랫폼 서비스 사용
* S3 Select 사용
* 저장 공간 사용량 모니터링



TIP: S3 테넌트 사용자는 테넌트 관리자를 사용하여 S3 액세스 키와 버킷을 만들고 관리할 수 있지만, 객체를 수집하고 관리하려면 S3 클라이언트 애플리케이션을 사용해야 합니다. 보다link:../s3/index.html["S3 REST API 사용"] 자세한 내용은.
