---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: QoS, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: '트래픽 분류 정책을 사용하면 다양한 유형의 네트워크 트래픽을 식별하고 모니터링할 수 있습니다.  이러한 정책은 트래픽 제한 및 모니터링을 지원하여 서비스 품질(QoS)을 향상하는 데 도움이 될 수 있습니다.' 
---
= 트래픽 분류 정책이란 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
트래픽 분류 정책을 사용하면 다양한 유형의 네트워크 트래픽을 식별하고 모니터링할 수 있습니다.  이러한 정책은 트래픽 제한 및 모니터링을 지원하여 서비스 품질(QoS)을 향상하는 데 도움이 될 수 있습니다.

트래픽 분류 정책은 게이트웨이 노드와 관리 노드에 대한 StorageGRID 부하 분산 서비스의 엔드포인트에 적용됩니다.  트래픽 분류 정책을 만들려면 로드 밸런서 엔드포인트를 이미 생성했어야 합니다.



== 매칭 규칙

각 트래픽 분류 정책에는 다음 엔터티 중 하나 이상과 관련된 네트워크 트래픽을 식별하기 위한 하나 이상의 일치 규칙이 포함되어 있습니다.

* 버킷
* 서브넷
* 거주자
* 로드 밸런서 엔드포인트


StorageGRID 규칙의 목적에 따라 정책 내의 모든 규칙과 일치하는 트래픽을 모니터링합니다.  정책에 대한 모든 규칙과 일치하는 모든 트래픽은 해당 정책에 의해 처리됩니다.  반대로, 지정된 엔터티를 제외한 모든 트래픽을 일치시키는 규칙을 설정할 수 있습니다.



== 교통 제한

선택적으로 정책에 다음 제한 유형을 추가할 수 있습니다.

* 총 대역폭
* 요청당 대역폭
* 동시 요청
* 요청률


제한 값은 로드 밸런서별로 적용됩니다.  트래픽이 여러 로드 밸런서에 동시에 분산되는 경우 총 최대 속도는 지정한 속도 제한의 배수가 됩니다.


NOTE: 전체 대역폭을 제한하거나 요청당 대역폭을 제한하는 정책을 만들 수 있습니다.  하지만 StorageGRID 두 가지 유형의 대역폭을 동시에 제한할 수 없습니다.  총 대역폭 제한은 제한되지 않은 트래픽에 추가적인 사소한 성능 영향을 미칠 수 있습니다.

집계 또는 요청당 대역폭 제한의 경우, 요청은 설정한 속도로 스트리밍되거나 스트리밍됩니다.  StorageGRID 하나의 속도만 적용할 수 있으므로 매처 유형별로 가장 구체적으로 일치하는 정책이 적용됩니다.  요청에 의해 소비된 대역폭은 집계 대역폭 제한 정책을 포함하는 덜 구체적인 다른 일치 정책에 포함되지 않습니다.  다른 모든 제한 유형의 경우 클라이언트 요청은 250밀리초 지연되고 일치하는 정책 제한을 초과하는 요청에 대해 503 Slow Down 응답을 받습니다.

그리드 관리자에서 트래픽 차트를 보고 정책이 예상한 트래픽 제한을 시행하고 있는지 확인할 수 있습니다.



== SLA와 함께 트래픽 분류 정책 사용

트래픽 분류 정책을 용량 제한 및 데이터 보호와 함께 사용하면 용량, 데이터 보호 및 성능에 대한 세부 사항을 제공하는 서비스 수준 계약(SLA)을 시행할 수 있습니다.

다음 예에서는 SLA의 세 가지 계층을 보여줍니다.  각 SLA 계층의 성능 목표를 달성하기 위해 트래픽 분류 정책을 만들 수 있습니다.

[cols="1a,1a,1a,1a,1a"]
|===
| 서비스 수준 계층 | 용량 | 데이터 보호 | 최대 허용 성능 | 비용 


 a| 
금
 a| 
1 PB 저장 용량 허용
 a| 
3개 사본 ILM 규칙
 a| 
25K 요청/초

5GB/초(40Gbps) 대역폭
 a| 
한 달에 $$$



 a| 
은
 a| 
250TB 저장 용량 허용
 a| 
2개의 ILM 규칙 사본
 a| 
10K 요청/초

1.25GB/초(10Gbps) 대역폭
 a| 
$$ 한 달에



 a| 
청동
 a| 
100TB 저장 용량 허용
 a| 
2개의 ILM 규칙 사본
 a| 
5K 요청/초

1GB/초(8Gbps) 대역폭
 a| 
월 $

|===