---
permalink: admin/manage-s3-select-for-tenant-accounts.html 
sidebar: sidebar 
keywords: s3 select, selectobjectcontent, best practices, object format, s3 select requirements 
summary: 특정 S3 테넌트가 S3 Select를 사용하여 개별 개체에 대해 SelectObjectContent 요청을 실행하도록 허용할 수 있습니다. 
---
= 테넌트 계정에 대한 S3 Select 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 S3 테넌트가 S3 Select를 사용하여 개별 개체에 대해 SelectObjectContent 요청을 실행하도록 허용할 수 있습니다.

S3 Select는 검색을 위해 데이터베이스와 관련 리소스를 배포하지 않고도 대량의 데이터를 검색할 수 있는 효율적인 방법을 제공합니다.  또한 데이터를 검색하는 데 드는 비용과 대기 시간도 줄어듭니다.



== S3 Select란 무엇인가요?

S3 Select를 사용하면 S3 클라이언트가 SelectObjectContent 요청을 사용하여 객체에서 필요한 데이터만 필터링하고 검색할 수 있습니다.  S3 Select의 StorageGRID 구현에는 S3 Select 명령과 기능의 하위 집합이 포함되어 있습니다.



== S3 Select 사용 시 고려 사항 및 요구 사항



=== 그리드 관리 요구 사항

그리드 관리자는 테넌트에게 S3 Select 권한을 부여해야 합니다.  *S3 선택 허용*을 선택하세요.link:creating-tenant-account.html["테넌트 생성"] 또는link:editing-tenant-account.html["테넌트 편집"] .



=== 객체 형식 요구 사항

쿼리하려는 개체는 다음 형식 중 하나여야 합니다.

* *CSV*.  그대로 사용하거나 GZIP 또는 BZIP2 아카이브로 압축하여 사용할 수 있습니다.
* *쪽매 세공*.  Parquet 객체에 대한 추가 요구 사항:
+
** S3 Select는 GZIP 또는 Snappy를 사용한 열 압축만 지원합니다.  S3 Select는 Parquet 객체에 대한 전체 객체 압축을 지원하지 않습니다.
** S3 Select는 Parquet 출력을 지원하지 않습니다.  출력 형식을 CSV 또는 JSON으로 지정해야 합니다.
** 압축되지 않은 행 그룹의 최대 크기는 512MB입니다.
** 개체의 스키마에 지정된 데이터 유형을 사용해야 합니다.
** INTERVAL, JSON, LIST, TIME 또는 UUID 논리 유형을 사용할 수 없습니다.






=== 엔드포인트 요구 사항

SelectObjectContent 요청은 다음으로 전송되어야 합니다.link:configuring-load-balancer-endpoints.html["StorageGRID 로드 밸런서 엔드포인트"] .

엔드포인트에서 사용되는 관리 노드와 게이트웨이 노드는 다음 중 하나여야 합니다.

* 서비스 어플라이언스 노드
* VMware 기반 소프트웨어 노드
* cgroup v2가 활성화된 커널을 실행하는 베어 메탈 노드




=== 일반적인 고려 사항

쿼리를 스토리지 노드로 직접 전송할 수 없습니다.


CAUTION: SelectObjectContent 요청은 모든 S3 클라이언트와 모든 테넌트의 로드 밸런서 성능을 저하시킬 수 있습니다.  이 기능은 필요할 때에만, 신뢰할 수 있는 세입자에게만 활성화하세요.

를 참조하십시오link:../s3/use-s3-select.html["S3 Select 사용 지침"] .

보려면link:../monitor/reviewing-support-metrics.html["그라파나 차트"] S3 Select 작업의 경우 시간 경과에 따라 그리드 관리자에서 *지원* > *도구* > *메트릭*을 선택합니다.
