---
permalink: admin/networking-and-ports-for-platform-services.html 
sidebar: sidebar 
keywords: platform services, ports for platform services, 443, 80 
summary: S3 테넌트가 플랫폼 서비스를 사용하도록 허용하는 경우 플랫폼 서비스 메시지가 대상지에 전달될 수 있도록 그리드에 대한 네트워킹을 구성해야 합니다. 
---
= 플랫폼 서비스를 위한 네트워크 및 포트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 테넌트가 플랫폼 서비스를 사용하도록 허용하는 경우 플랫폼 서비스 메시지가 대상지에 전달될 수 있도록 그리드에 대한 네트워킹을 구성해야 합니다.

테넌트 계정을 생성하거나 업데이트할 때 S3 테넌트 계정에 대한 플랫폼 서비스를 활성화할 수 있습니다.  플랫폼 서비스가 활성화된 경우 테넌트는 S3 버킷에서 CloudMirror 복제, 이벤트 알림 또는 검색 통합 메시지의 대상 역할을 하는 엔드포인트를 만들 수 있습니다.  이러한 플랫폼 서비스 메시지는 ADC 서비스를 실행하는 스토리지 노드에서 대상 엔드포인트로 전송됩니다.

예를 들어, 테넌트는 다음 유형의 대상 엔드포인트를 구성할 수 있습니다.

* 로컬로 호스팅되는 Elasticsearch 클러스터
* Amazon Simple Notification Service 메시지 수신을 지원하는 로컬 애플리케이션
* 로컬 호스팅 Kafka 클러스터
* 동일하거나 다른 StorageGRID 인스턴스에 로컬로 호스팅된 S3 버킷
* Amazon Web Services의 엔드포인트와 같은 외부 엔드포인트.


플랫폼 서비스 메시지가 전달될 수 있도록 하려면 ADC 스토리지 노드가 포함된 네트워크를 구성해야 합니다.  다음 포트를 사용하여 플랫폼 서비스 메시지를 대상 엔드포인트로 보낼 수 있는지 확인해야 합니다.

기본적으로 플랫폼 서비스 메시지는 다음 포트를 통해 전송됩니다.

* *80*: http로 시작하는 엔드포인트 URI의 경우(대부분의 엔드포인트)
* *443*: https로 시작하는 엔드포인트 URI의 경우(대부분의 엔드포인트)
* *9092*: http 또는 https로 시작하는 엔드포인트 URI의 경우(Kafka 엔드포인트만 해당)


테넌트는 엔드포인트를 생성하거나 편집할 때 다른 포트를 지정할 수 있습니다.


NOTE: StorageGRID 배포가 CloudMirror 복제의 대상으로 사용되는 경우 복제 메시지가 80 또는 443이 아닌 다른 포트에서 수신될 수 있습니다.  대상 StorageGRID 배포에서 S3에 사용되는 포트가 엔드포인트에 지정되어 있는지 확인하세요.

투명하지 않은 프록시 서버를 사용하는 경우에도 다음을 수행해야 합니다.link:configuring-storage-proxy-settings.html["저장소 프록시 설정 구성"] 메시지를 인터넷 상의 엔드포인트와 같은 외부 엔드포인트로 보낼 수 있도록 허용합니다.

.관련 정보
link:../tenant/index.html["세입자 계정 사용"]
