---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: '객체를 저장하거나 검색하기 위해 S3 클라이언트 애플리케이션은 모든 관리 노드와 게이트웨이 노드에 포함된 로드 밸런서 서비스나 모든 스토리지 노드에 포함된 로컬 배포 라우터(LDR) 서비스에 연결합니다.' 
---
= 요약: 클라이언트 연결을 위한 IP 주소 및 포트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
객체를 저장하거나 검색하기 위해 S3 클라이언트 애플리케이션은 모든 관리 노드와 게이트웨이 노드에 포함된 로드 밸런서 서비스나 모든 스토리지 노드에 포함된 로컬 배포 라우터(LDR) 서비스에 연결합니다.

클라이언트 애플리케이션은 그리드 노드의 IP 주소와 해당 노드의 서비스 포트 번호를 사용하여 StorageGRID 에 연결할 수 있습니다.  선택적으로, 고가용성(HA) 부하 분산 노드 그룹을 만들어 가상 IP(VIP) 주소를 사용하는 고가용성 연결을 제공할 수 있습니다.  IP 또는 VIP 주소 대신 FQDN(정규화된 도메인 이름)을 사용하여 StorageGRID 에 연결하려면 DNS 항목을 구성할 수 있습니다.

이 표는 클라이언트가 StorageGRID 에 연결할 수 있는 다양한 방법과 각 연결 유형에 사용되는 IP 주소와 포트를 요약한 것입니다.  이미 로드 밸런서 엔드포인트와 고가용성(HA) 그룹을 생성한 경우 다음을 참조하세요.<<IP 주소를 찾을 수 있는 곳>> 그리드 관리자에서 이러한 값을 찾습니다.

[cols="1a,1a,1a,1a"]
|===
| 연결이 이루어지는 곳 | 클라이언트가 접속하는 서비스 | IP 주소 | 포트 


 a| 
HA 그룹
 a| 
로드 밸런서
 a| 
HA 그룹의 가상 IP 주소
 a| 
로드 밸런서 엔드포인트에 할당된 포트



 a| 
관리 노드
 a| 
로드 밸런서
 a| 
관리 노드의 IP 주소
 a| 
로드 밸런서 엔드포인트에 할당된 포트



 a| 
게이트웨이 노드
 a| 
로드 밸런서
 a| 
게이트웨이 노드의 IP 주소
 a| 
로드 밸런서 엔드포인트에 할당된 포트



 a| 
저장 노드
 a| 
LDR
 a| 
저장 노드의 IP 주소
 a| 
기본 S3 포트:

* HTTPS: 18082
* HTTP: 18084


|===


== URL 예시

게이트웨이 노드의 HA 그룹의 로드 밸런서 엔드포인트에 클라이언트 애플리케이션을 연결하려면 아래와 같이 구성된 URL을 사용합니다.

`https://_VIP-of-HA-group:LB-endpoint-port_`

예를 들어, HA 그룹의 가상 IP 주소가 192.0.2.5이고 로드 밸런서 엔드포인트의 포트 번호가 10443인 경우 애플리케이션은 다음 URL을 사용하여 StorageGRID 에 연결할 수 있습니다.

`\https://192.0.2.5:10443`



== IP 주소를 찾을 수 있는 곳

. 다음을 사용하여 Grid Manager에 Sign in.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
. 그리드 노드의 IP 주소를 찾으려면:
+
.. *노드*를 선택하세요.
.. 연결하려는 관리 노드, 게이트웨이 노드 또는 스토리지 노드를 선택하세요.
.. *개요* 탭을 선택하세요.
.. 노드 정보 섹션에서 노드의 IP 주소를 기록해 둡니다.
.. IPv6 주소와 인터페이스 매핑을 보려면 *더 보기*를 선택하세요.
+
클라이언트 애플리케이션에서 목록에 있는 모든 IP 주소로 연결을 설정할 수 있습니다.

+
*** *eth0:* 그리드 네트워크
*** *eth1:* 관리 네트워크(선택 사항)
*** *eth2:* 클라이언트 네트워크(선택 사항)
+

NOTE: 관리 노드 또는 게이트웨이 노드를 보고 있고 해당 노드가 고가용성 그룹의 활성 노드인 경우 HA 그룹의 가상 IP 주소가 eth2에 표시됩니다.





. 고가용성 그룹의 가상 IP 주소를 찾으려면:
+
.. *구성* > *네트워크* > *고가용성 그룹*을 선택합니다.
.. 표에서 HA 그룹의 가상 IP 주소를 확인하세요.


. 로드 밸런서 엔드포인트의 포트 번호를 찾으려면:
+
.. *구성* > *네트워크* > *로드 밸런서 엔드포인트*를 선택합니다.
.. 사용하려는 엔드포인트의 포트 번호를 기록해 두세요.
+

NOTE: 포트 번호가 80 또는 443인 경우 엔드포인트는 게이트웨이 노드에서만 구성됩니다. 해당 포트는 관리 노드에서 예약되어 있기 때문입니다.  다른 모든 포트는 게이트웨이 노드와 관리 노드 모두에 구성됩니다.

.. 표에서 엔드포인트 이름을 선택합니다.
.. *클라이언트 유형*(S3)이 엔드포인트를 사용할 클라이언트 애플리케이션과 일치하는지 확인합니다.



