---
permalink: admin/temporarily-disabling-and-reenabling-sso-for-admin-node.html 
sidebar: sidebar 
keywords: signing in when sso is down, single sign on failure 
summary: 'Single Sign-On (SSO) 시스템이 다운되면 Grid Manager에 로그인하지 못할 수 있습니다.  이 경우, 하나의 관리 노드에 대해 SSO를 일시적으로 비활성화했다가 다시 활성화할 수 있습니다.  SSO를 비활성화한 다음 다시 활성화하려면 노드의 명령 셸에 액세스해야 합니다.' 
---
= 한 관리 노드에 대해 단일 로그인을 일시적으로 비활성화하고 다시 활성화합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSO(Single Sign-On) 시스템이 다운되면 Grid Manager에 로그인하지 못할 수 있습니다.  이 경우, 하나의 관리 노드에 대해 SSO를 일시적으로 비활성화했다가 다시 활성화할 수 있습니다.  SSO를 비활성화한 다음 다시 활성화하려면 노드의 명령 셸에 액세스해야 합니다.

.시작하기 전에
* 당신은 가지고있다link:admin-group-permissions.html["특정 액세스 권한"] .
* 당신은 가지고있다 `Passwords.txt` 파일.
* 로컬 루트 사용자의 비밀번호를 알고 있습니다.


.이 작업에 관하여
한 관리 노드에 대해 SSO를 비활성화한 후에는 로컬 루트 사용자로 Grid Manager에 로그인할 수 있습니다.  StorageGRID 시스템을 보호하려면 로그아웃하자마자 노드의 명령 셸을 사용하여 관리 노드에서 SSO를 다시 활성화해야 합니다.


TIP: 한 관리 노드의 SSO를 비활성화해도 그리드 내 다른 관리 노드의 SSO 설정에는 영향을 미치지 않습니다.  그리드 관리자의 Single Sign-on 페이지에서 *SSO 사용* 체크박스는 선택된 상태로 유지되며, 기존 SSO 설정은 업데이트하지 않는 한 모두 그대로 유지됩니다.

.단계
. 관리자 노드에 로그인하세요:
+
.. 다음 명령을 입력하세요: `ssh admin@Admin_Node_IP`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. 다음 명령을 실행하세요.``disable-saml``
+
메시지는 해당 명령이 이 관리 노드에만 적용된다는 것을 나타냅니다.

. SSO를 비활성화할지 확인하세요.
+
메시지는 노드에서 Single Sign-On이 비활성화되었음을 나타냅니다.

. 웹 브라우저에서 동일한 관리 노드의 Grid Manager에 액세스합니다.
+
SSO가 비활성화되었기 때문에 이제 Grid Manager 로그인 페이지가 표시됩니다.

. 사용자 이름 root와 로컬 root 사용자의 비밀번호로 Sign in .
. SSO 구성을 수정해야 하기 때문에 SSO를 일시적으로 비활성화한 경우:
+
.. *구성* > *액세스 제어* > *단일 로그인*을 선택합니다.
.. 잘못되었거나 오래된 SSO 설정을 변경합니다.
.. *저장*을 선택하세요.
+
Single Sign-on 페이지에서 *저장*을 선택하면 전체 그리드에 대한 SSO가 자동으로 다시 활성화됩니다.



. 다른 이유로 Grid Manager에 액세스해야 하기 때문에 SSO를 일시적으로 비활성화한 경우:
+
.. 수행해야 할 작업을 수행하세요.
.. *로그아웃*을 선택하고 그리드 관리자를 닫습니다.
.. 관리 노드에서 SSO를 다시 활성화합니다.  다음 단계 중 하나를 수행할 수 있습니다.
+
*** 다음 명령을 실행하세요. `enable-saml`
+
메시지는 해당 명령이 이 관리 노드에만 적용된다는 것을 나타냅니다.

+
SSO를 활성화할지 확인하세요.

+
메시지는 노드에서 Single Sign-On이 활성화되었음을 나타냅니다.

*** 그리드 노드를 재부팅합니다. `reboot`




. 웹 브라우저에서 동일한 관리 노드의 Grid Manager에 액세스합니다.
. StorageGRID Sign in 페이지가 나타나는지 확인하고 Grid Manager에 액세스하려면 SSO 자격 증명을 입력해야 합니다.

