---
permalink: admin/use-s3-setup-wizard.html 
sidebar: sidebar 
keywords: S3, S3 setup wizard 
summary: S3 설정 마법사를 사용하여 StorageGRID S3 애플리케이션의 개체 스토리지 시스템으로 구성할 수 있습니다. 
---
= S3 설정 마법사 사용: 고려 사항 및 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 설정 마법사를 사용하여 StorageGRID S3 애플리케이션의 개체 스토리지 시스템으로 구성할 수 있습니다.



== S3 설정 마법사를 사용하는 경우

S3 설정 마법사는 S3 애플리케이션과 함께 사용할 StorageGRID 구성하는 각 단계를 안내합니다.  마법사를 완료하는 과정의 일부로 S3 애플리케이션에 값을 입력하는 데 사용할 수 있는 파일을 다운로드합니다.  마법사를 사용하면 시스템을 더 빠르게 구성하고 설정이 StorageGRID 모범 사례에 부합하는지 확인할 수 있습니다.

만약 당신이 가지고 있다면link:admin-group-permissions.html["루트 액세스 권한"] StorageGRID Grid Manager를 사용하기 시작할 때 S3 설정 마법사를 완료할 수 있으며, 나중에 언제든지 마법사에 액세스하여 완료할 수 있습니다.  요구 사항에 따라 필수 항목 중 일부 또는 전부를 수동으로 구성한 다음 마법사를 사용하여 S3 애플리케이션에 필요한 값을 조합할 수도 있습니다.



== 마법사를 사용하기 전에

마법사를 사용하기 전에 다음 전제 조건을 모두 충족했는지 확인하세요.

IP 주소를 얻고 VLAN 인터페이스를 설정합니다.:: 고가용성(HA) 그룹을 구성하는 경우 S3 애플리케이션이 연결할 노드와 사용할 StorageGRID 네트워크를 알 수 있습니다.  또한 서브넷 CIDR, 게이트웨이 IP 주소, 가상 IP(VIP) 주소에 어떤 값을 입력해야 하는지도 알고 있습니다.
+
--
S3 애플리케이션의 트래픽을 분리하기 위해 가상 LAN을 사용하려는 경우 VLAN 인터페이스가 이미 구성되어 있습니다. 보다 link:../admin/configure-vlan-interfaces.html["VLAN 인터페이스 구성"] .

--
ID 페더레이션 및 SSO 구성:: StorageGRID 시스템에 ID 페더레이션이나 SSO(Single Sign-On)를 사용하려는 경우 이러한 기능을 활성화해야 합니다. 또한 S3 애플리케이션이 사용할 테넌트 계정에 대해 루트 액세스 권한이 있는 페더레이션 그룹이 어느 것인지도 알고 있습니다. 보다link:../admin/using-identity-federation.html["ID 페더레이션 사용"] 그리고link:../admin/configuring-sso.html["단일 로그인 구성"] .
도메인 이름 획득 및 구성:: StorageGRID 에 사용할 정규화된 도메인 이름(FQDN)을 알고 있습니다.  도메인 이름 서버(DNS) 항목은 마법사를 사용하여 만든 HA 그룹의 가상 IP(VIP) 주소에 이 FQDN을 매핑합니다.
+
--
S3 가상 호스팅 스타일 요청을 사용하려면 다음이 필요합니다.link:../admin/configuring-s3-api-endpoint-domain-names.html["구성된 S3 엔드포인트 도메인 이름"] .  가상 호스팅 스타일 요청을 사용하는 것이 좋습니다.

--
로드 밸런서 및 보안 인증서 요구 사항 검토:: StorageGRID 로드 밸런서를 사용할 계획이라면 로드 밸런싱에 대한 일반적인 고려 사항을 검토했을 것입니다.  업로드할 인증서가 있거나 인증서를 생성하는 데 필요한 값이 있습니다.
+
--
외부(타사) 로드 밸런서 엔드포인트를 사용하려는 경우 해당 로드 밸런서에 대한 정규화된 도메인 이름(FQDN), 포트 및 인증서가 있어야 합니다.

--
모든 그리드 페더레이션 연결 구성:: 그리드 페더레이션 연결을 사용하여 S3 테넌트가 계정 데이터를 복제하고 버킷 객체를 다른 그리드에 복제하도록 허용하려면 마법사를 시작하기 전에 다음 사항을 확인하세요.
+
--
* 당신은 가지고있다link:grid-federation-manage-connection.html["그리드 페더레이션 연결을 구성했습니다."] .
* 연결 상태는 *연결됨*입니다.
* 루트 접근 권한이 있습니다.


--

