---
permalink: admin/viewing-network-traffic-metrics.html 
sidebar: sidebar 
keywords: network traffic, traffic classification policy, monitor traffic 
summary: 트래픽 분류 정책 페이지에서 제공되는 그래프를 통해 네트워크 트래픽을 모니터링할 수 있습니다. 
---
= 네트워크 트래픽 메트릭 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
트래픽 분류 정책 페이지에서 제공되는 그래프를 통해 네트워크 트래픽을 모니터링할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:admin-group-permissions.html["루트 액세스 또는 테넌트 계정 권한"] .


.이 작업에 관하여
기존 트래픽 분류 정책의 경우 로드 밸런서 서비스에 대한 메트릭을 보고 정책이 네트워크 전반의 트래픽을 성공적으로 제한하는지 확인할 수 있습니다.  그래프의 데이터는 정책을 조정해야 하는지 여부를 판단하는 데 도움이 될 수 있습니다.

트래픽 분류 정책에 대한 제한이 설정되지 않은 경우에도 측정항목이 수집되고 그래프는 트래픽 추세를 이해하는 데 유용한 정보를 제공합니다.

.단계
. *구성* > *네트워크* > *트래픽 분류*를 선택합니다.
+
트래픽 분류 정책 페이지가 나타나고 기존 정책이 표에 나열됩니다.

. 측정 항목을 보려는 트래픽 분류 정책 이름을 선택합니다.
. *측정항목* 탭을 선택합니다.
+
트래픽 분류 정책 그래프가 나타납니다.  그래프는 선택한 정책과 일치하는 트래픽에 대한 메트릭만 표시합니다.

+
다음 그래프는 해당 페이지에 포함되어 있습니다.

+
** 요청 속도: 이 그래프는 모든 로드 밸런서가 처리하는 이 정책과 일치하는 대역폭의 양을 보여줍니다.  수신된 데이터에는 모든 요청에 대한 요청 헤더와 본문 데이터가 있는 응답에 대한 본문 데이터 크기가 포함됩니다.  전송에는 모든 요청에 대한 응답 헤더와 응답에 본문 데이터가 포함된 요청에 대한 응답 본문 데이터 크기가 포함됩니다.
+

NOTE: 요청이 완료되면 이 차트는 대역폭 사용량만 표시합니다.  느리거나 큰 객체 요청의 경우 실제 순간 대역폭은 이 그래프에 보고된 값과 다를 수 있습니다.

** 오류 응답률: 이 그래프는 이 정책과 일치하는 요청이 클라이언트에 오류(HTTP 상태 코드 >= 400)를 반환하는 대략적인 비율을 보여줍니다.
** 평균 요청 기간(오류 없음): 이 그래프는 이 정책과 일치하는 성공적인 요청의 평균 기간을 제공합니다.
** 정책 대역폭 사용량: 이 그래프는 모든 로드 밸런서가 처리하는 이 정책과 일치하는 대역폭의 양을 보여줍니다.  수신된 데이터에는 모든 요청에 대한 요청 헤더와 본문 데이터가 있는 응답에 대한 본문 데이터 크기가 포함됩니다.  전송에는 모든 요청에 대한 응답 헤더와 응답에 본문 데이터가 포함된 요청에 대한 응답 본문 데이터 크기가 포함됩니다.


. 그래프의 특정 부분에 대한 값이 팝업으로 표시되면 선 그래프 위에 커서를 올려놓으세요.
. 정책에 대한 모든 그래프를 보려면 메트릭 제목 바로 아래에 있는 *Grafana 대시보드*를 선택하세요.  *메트릭* 탭의 4개 그래프 외에도 두 개의 그래프를 더 볼 수 있습니다.
+
** 객체 크기에 따른 쓰기 요청 속도: 이 정책과 일치하는 PUT/POST/DELETE 요청의 속도입니다.  개별 셀의 위치는 초당 속도를 보여줍니다.  호버 뷰에 표시된 속도는 정수 단위로 잘려나가며 버킷에 0이 아닌 요청이 있는 경우 0으로 보고될 수 있습니다.
** 객체 크기에 따른 읽기 요청 속도: 이 정책과 일치하는 GET/HEAD 요청의 속도입니다.  개별 셀의 위치는 초당 속도를 보여줍니다.  호버 뷰에 표시된 속도는 정수 단위로 잘려나가며 버킷에 0이 아닌 요청이 있는 경우 0으로 보고될 수 있습니다.


. 또는 *지원* 메뉴에서 그래프에 액세스하세요.
+
.. *지원* > *도구* > *측정항목*을 선택하세요.
.. *Grafana* 섹션에서 *트래픽 분류 정책*을 선택합니다.
.. 페이지 왼쪽 상단의 메뉴에서 정책을 선택하세요.
.. 그래프 위에 커서를 놓으면 샘플의 날짜와 시간, 카운트에 집계된 객체 크기, 해당 기간 동안의 초당 요청 수를 보여 주는 팝업이 나타납니다.
+
트래픽 분류 정책은 ID로 식별됩니다.  정책 ID는 트래픽 분류 정책 페이지에 나열되어 있습니다.



. 그래프를 분석하여 정책이 트래픽을 얼마나 자주 제한하는지, 그리고 정책을 조정해야 하는지 확인하세요.

