---
permalink: admin/what-is-autosupport.html 
sidebar: sidebar 
keywords: autosupport, technical support, storagegrid health, system status, Active IQ 
summary: AutoSupport 기능을 사용하면 StorageGRID NetApp 기술 지원팀에 상태 패키지를 보낼 수 있습니다. 
---
= AutoSupport 란 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 기능을 사용하면 StorageGRID NetApp 기술 지원팀에 상태 패키지를 보낼 수 있습니다.

AutoSupport 사용하면 문제 파악 및 해결 속도를 크게 높일 수 있습니다.  기술 지원팀은 시스템의 저장 요구 사항을 모니터링하고 새로운 노드나 사이트를 추가해야 하는지 여부를 결정하는 데 도움을 줄 수도 있습니다.  선택적으로 AutoSupport 패키지를 추가 대상지 하나로 보내도록 구성할 수 있습니다.

StorageGRID 에는 두 가지 유형의 AutoSupport 가 있습니다.

* * StorageGRID AutoSupport*는 StorageGRID 소프트웨어 문제를 보고합니다.  StorageGRID 처음 설치하면 기본적으로 활성화됩니다.  당신은 할 수 있습니다link:configure-autosupport-grid-manager.html["기본 AutoSupport 구성 변경"] 필요한 경우.
+

NOTE: StorageGRID AutoSupport 활성화되어 있지 않으면 Grid Manager 대시보드에 메시지가 나타납니다. 해당 메시지에는 AutoSupport 구성 페이지에 대한 링크가 포함되어 있습니다.  메시지를 닫으면 AutoSupport 비활성화된 경우에도 브라우저 캐시가 지워질 때까지 메시지가 다시 나타나지 않습니다.

* *가전제품 하드웨어 AutoSupport*는 StorageGRID 가전제품 문제를 보고합니다.  당신은해야합니다link:configure-autosupport-grid-manager.html#autosupport-for-appliances["각 어플라이언스에서 하드웨어 AutoSupport 구성"] .




== Active IQ 란 무엇인가요?

Active IQ 는 NetApp의 설치 기반에서 얻은 예측 분석과 커뮤니티 지식을 활용하는 클라우드 기반 디지털 자문 서비스입니다.  지속적인 위험 평가, 예측적 알림, 처방적 지침, 자동화된 조치를 통해 문제가 발생하기 전에 예방하고 시스템 상태를 개선하며 시스템 가용성을 높일 수 있습니다.

NetApp 지원 사이트에서 Active IQ 대시보드와 기능을 사용하려면 AutoSupport 활성화해야 합니다.

https://docs.netapp.com/us-en/active-iq/index.html["Active IQ Digital Advisor 문서"^]



== AutoSupport 패키지에 포함된 정보

AutoSupport 패키지에는 다음 파일과 세부 정보가 포함되어 있습니다.

[cols="2a,2a,3a"]
|===
| 파일 이름 | 전지 | 설명 


 a| 
자동 지원-히스토리.XML
 a| 
AutoSupport 시퀀스 번호 + 이 AutoSupport 에 대한 대상 + 배달 상태 + 배달 시도 + AutoSupport 제목 + 배달 URI + 마지막 오류 + AutoSupport PUT 파일 이름 + 생성 시간 + Autosupport 압축 크기 + Autosupport 압축 해제 크기 + 총 수집 시간(ms)
 a| 
AutoSupport 기록 파일.



 a| 
자동 지원.XML
 a| 
노드 + 지원에 문의하기 위한 프로토콜 + HTTP/HTTPS 지원 URL + 지원 주소 + AutoSupport OnDemand 상태 + AutoSupport OnDemand 서버 URL + AutoSupport OnDemand 폴링 간격
 a| 
AutoSupport 상태 파일.  사용된 프로토콜, 기술 지원 URL 및 주소, 폴링 간격, OnDemand AutoSupport (활성화 또는 비활성화된 경우)에 대한 세부 정보를 제공합니다.



 a| 
버킷.XML
 a| 
버킷 ID + 계정 ID + 빌드 버전 + 위치 제약 조건 구성 + 규정 준수 활성화 + 규정 준수 구성 + S3 객체 잠금 활성화 + S3 객체 잠금 구성 + 일관성 구성 + CORS 활성화 + CORS 구성 + 마지막 액세스 시간 활성화 + 정책 활성화 + 정책 구성 + 알림 활성화 + 알림 구성 + Cloud Mirror 활성화 + Cloud Mirror 구성 + 검색 활성화 + 검색 구성 + 버킷 태그 지정 활성화 + 버킷 태그 지정 구성 + 버전 관리 구성
 a| 
버킷 수준에서 구성 세부 정보와 통계를 제공합니다.  버킷 구성의 예로는 플랫폼 서비스, 규정 준수, 버킷 일관성 등이 있습니다.



 a| 
그리드 구성.XML
 a| 
속성 ID + 속성 이름 + 값 + 인덱스 + 테이블 ID + 테이블 이름
 a| 
그리드 전체 구성 정보 파일입니다.  그리드 인증서, 메타데이터 예약 공간, 그리드 전체 구성 설정(규정 준수, S3 개체 잠금, 개체 압축, 경고, syslog 및 ILM 구성), 삭제 코딩 프로필 세부 정보, DNS 이름 등에 대한 정보가 포함되어 있습니다.link:../primer/nodes-and-services.html#storagegrid-services["NMS 이름"] .



 a| 
GRID-SPEC.XML
 a| 
그리드 사양, 원시 XML
 a| 
StorageGRID 구성 및 배포에 사용됩니다.  노드의 그리드 사양, NTP 서버 IP, DNS 서버 IP, 네트워크 토폴로지 및 하드웨어 프로필이 포함되어 있습니다.



 a| 
그리드-태스크.XML
 a| 
노드 + 서비스 경로 + 속성 ID + 속성 이름 + 값 + 인덱스 + 테이블 ID + 테이블 이름
 a| 
그리드 작업(유지관리 절차) 상태 파일.  그리드의 활성, 종료, 완료, 실패 및 보류 중인 작업에 대한 세부 정보를 제공합니다.



 a| 
그리드.JSON
 a| 
그리드 + 개정 + 소프트웨어 버전 + 설명 + 라이센스 + 비밀번호 + DNS + NTP + 사이트 + 노드
 a| 
그리드 정보.



 a| 
ILM 구성.XML
 a| 
속성 ID + 속성 이름 + 값 + 인덱스 + 테이블 ID + 테이블 이름
 a| 
ILM 구성에 대한 속성 목록입니다.



 a| 
ILM-STATUS.XML
 a| 
노드 + 서비스 경로 + 속성 ID + 속성 이름 + 값 + 인덱스 + 테이블 ID + 테이블 이름
 a| 
ILM 지표 정보 파일.  각 노드에 대한 ILM 평가율과 그리드 전체 지표가 포함되어 있습니다.



 a| 
ILM.XML
 a| 
ILM 원시 XML
 a| 
ILM 활성 정책 파일.  스토리지 풀 ID, 수집 동작, 필터, 규칙 및 설명과 같은 활성 ILM 정책에 대한 세부 정보가 포함되어 있습니다.



 a| 
LOG.TGZ
 a| 
_해당 없음_
 a| 
다운로드 가능한 로그 파일.  포함 `bycast-err.log` 그리고 `servermanager.log` 각 노드에서.



 a| 
매니페스트.XML
 a| 
수집 순서 + 이 데이터에 대한 AutoSupport 콘텐츠 파일 이름 + 이 데이터 항목에 대한 설명 + 수집된 바이트 수 + 수집에 소요된 시간 + 이 데이터 항목의 상태 + 오류에 대한 설명 + 이 데이터에 대한 AutoSupport 콘텐츠 유형 +
 a| 
AutoSupport 메타데이터와 모든 AutoSupport 파일에 대한 간략한 설명이 포함되어 있습니다.



 a| 
NMS-ENTITIES.XML
 a| 
속성 인덱스 + 엔티티 OID + 노드 ID + 장치 모델 ID + 장치 모델 버전 + 엔티티 이름
 a| 
그룹 및 서비스 엔터티link:../primer/nodes-and-services.html#storagegrid-services["NMS 트리"] .  그리드 토폴로지 세부 정보를 제공합니다.  노드는 노드에서 실행되는 서비스를 기준으로 결정될 수 있습니다.



 a| 
객체-상태.XML
 a| 
노드 + 서비스 경로 + 속성 ID + 속성 이름 + 값 + 인덱스 + 테이블 ID + 테이블 이름
 a| 
백그라운드 스캔 상태, 활성 전송, 전송 속도, 총 전송, 삭제 속도, 손상된 조각, 손실된 개체, 누락된 개체, 시도된 복구, 스캔 속도, 예상 스캔 기간 및 복구 완료 상태를 포함한 개체 상태입니다.



 a| 
서버 상태.XML
 a| 
노드 + 서비스 경로 + 속성 ID + 속성 이름 + 값 + 인덱스 + 테이블 ID + 테이블 이름
 a| 
서버 구성.  각 노드에 대한 다음 세부 정보가 포함되어 있습니다: 플랫폼 유형, 운영 체제, 설치된 메모리, 사용 가능한 메모리, 스토리지 연결, 스토리지 어플라이언스 섀시 일련 번호, 스토리지 컨트롤러 실패 드라이브 수, 컴퓨팅 컨트롤러 섀시 온도, 컴퓨팅 하드웨어, 컴퓨팅 컨트롤러 일련 번호, 전원 공급 장치, 드라이브 크기 및 드라이브 유형.



 a| 
서비스 상태.XML
 a| 
노드 + 서비스 경로 + 속성 ID + 속성 이름 + 값 + 인덱스 + 테이블 ID + 테이블 이름
 a| 
서비스 노드 정보 파일.  할당된 테이블 공간, 여유 테이블 공간, 데이터베이스의 Reaper 메트릭, 세그먼트 복구 기간, 복구 작업 기간, 자동 작업 재시작, 자동 작업 종료와 같은 세부 정보가 포함되어 있습니다.



 a| 
저장 등급.XML
 a| 
스토리지 등급 ID + 스토리지 등급 이름 + 스토리지 노드 ID + 스토리지 노드 경로
 a| 
각 스토리지 노드에 대한 스토리지 등급 정의 파일입니다.



 a| 
요약-속성.XML
 a| 
그룹 OID + 그룹 경로 + 요약 속성 ID + 요약 속성 이름 + 값 + 인덱스 + 테이블 ID + 테이블 이름
 a| 
StorageGRID 사용 정보를 요약한 고급 시스템 상태 데이터입니다.  그리드 이름, 사이트 이름, 그리드 및 사이트당 스토리지 노드 수, 라이선스 유형, 라이선스 용량 및 사용량, 소프트웨어 지원 조건, S3 작업 세부 정보 등의 세부 정보를 제공합니다.



 a| 
시스템-알림.XML
 a| 
이름 + 심각도 + 노드 이름 + 경고 상태 + 사이트 이름 + 경고 발생 시간 + 경고 해결 시간 + 규칙 ID + 노드 ID + 사이트 ID + 음소거됨 + 기타 주석 + 기타 레이블
 a| 
StorageGRID 시스템의 잠재적 문제를 나타내는 현재 시스템 알림입니다.



 a| 
사용자 에이전트.XML
 a| 
사용자 에이전트 + 일수 + 총 HTTP 요청 + 수집된 총 바이트 + 검색된 총 바이트 + PUT 요청 + GET 요청 + DELETE 요청 + HEAD 요청 + POST 요청 + OPTIONS 요청 + 평균 요청 시간(ms) + 평균 PUT 요청 시간(ms) + 평균 GET 요청 시간(ms) + 평균 DELETE 요청 시간(ms) + 평균 HEAD 요청 시간(ms) + 평균 POST 요청 시간(ms) + 평균 OPTIONS 요청 시간(ms)
 a| 
애플리케이션 사용자 에이전트를 기반으로 한 통계입니다.  예를 들어, 사용자 에이전트당 PUT/GET/DELETE/HEAD 작업의 수와 각 작업의 총 바이트 크기입니다.



 a| 
X-헤더-데이터
 a| 
X-Netapp-asup-생성-온 + X-Netapp-asup-호스트 이름 + X-Netapp-asup-os-버전 + X-Netapp-asup-직렬-번호 + X-Netapp-asup-주제 + X-Netapp-asup-시스템-id + X-Netapp-asup-모델-이름 +
 a| 
AutoSupport 헤더 데이터.

|===