---
permalink: s3/changes-to-s3-rest-api-support.html 
sidebar: sidebar 
keywords: s3 rest api support changes 
summary: S3 REST API에 대한 StorageGRID 시스템 지원의 변경 사항을 알아야 합니다. 
---
= S3 REST API 지원 변경 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 REST API에 대한 StorageGRID 시스템 지원의 변경 사항을 알아야 합니다.

[cols="1a,4a"]
|===
| 풀어 주다 | 댓글 


 a| 
11.8
 a| 
* 추가 지원 `ExpiredObjectDeleteMarker` 만료된 객체 삭제 마커를 삭제하는 PutBucketLifecycleConfiguration 작업에서.
* 추가 지원 `s3:ExistingObjectTag/<tag-key>` 정책 조건 키는 기존 객체에 특정 태그 키와 값이 있어야 한다는 것을 요구합니다.
* 추가 지원 `s3:RequestObjectTag/<tag-key>` 태그 지정이 객체 요청에 포함된 경우 특정 태그와 키 값이 필요한 정책 조건 키입니다.




 a| 
11.7
 a| 
* S3 개체 잠금과 함께 GOVERNANCE 모드를 사용하기 위한 지원이 추가되었습니다.
* StorageGRID 관련 지원이 추가되었습니다. `x-ntap-sg-cgr-replication-status` GetObject 및 HeadObject 요청에 대한 응답 헤더.  이 헤더는 그리드 간 복제에 대한 객체의 복제 상태를 제공합니다.
* SelectObjectContent 요청은 이제 Parquet 객체를 지원합니다.




 a| 
11.6
 a| 
* 사용에 대한 지원이 추가되었습니다. `partNumber` GetObject 및 HeadObject 요청의 요청 매개변수.
* S3 객체 잠금에 대한 기본 보존 모드와 버킷 수준의 기본 보존 기간에 대한 지원이 추가되었습니다.
* 추가 지원 `s3:object-lock-remaining-retention-days` 정책 조건 키를 사용하여 개체에 허용되는 보존 기간 범위를 설정합니다.
* 단일 PutObject 작업에 대한 최대 권장 크기를 5GiB(5,368,709,120바이트)로 변경했습니다.  5GiB보다 큰 객체가 있는 경우 대신 멀티파트 업로드를 사용하세요.




 a| 
11.5
 a| 
* 버킷 암호화 관리에 대한 지원이 추가되었습니다.
* S3 개체 잠금에 대한 지원이 추가되었고 더 이상 사용되지 않는 레거시 규정 준수 요청이 추가되었습니다.
* 버전이 지정된 버킷에서 DeleteObjects를 사용할 수 있도록 지원이 추가되었습니다.
* 그만큼 `Content-MD5` 요청 헤더가 이제 올바르게 지원됩니다.




 a| 
11.4
 a| 
* DeleteBucketTagging, GetBucketTagging, PutBucketTagging에 대한 지원이 추가되었습니다.  비용 할당 태그는 지원되지 않습니다.
* StorageGRID 11.4에서 생성된 버킷의 경우 성능 모범 사례를 충족하기 위해 개체 키 이름을 제한할 필요가 더 이상 없습니다.
* 버킷 알림에 대한 지원이 추가되었습니다. `s3:ObjectRestore:Post` 이벤트 유형.
* 이제 다중 파트 파트에 대한 AWS 크기 제한이 적용됩니다.  멀티파트 업로드의 각 부분은 5MiB~5GiB 사이여야 합니다.  마지막 부분은 5MiB보다 작을 수 있습니다.
* TLS 1.3에 대한 지원이 추가되었습니다.




 a| 
11.3
 a| 
* 고객이 제공한 키(SSE-C)를 사용하여 개체 데이터의 서버 측 암호화에 대한 지원이 추가되었습니다.
* DeleteBucketLifecycle, GetBucketLifecycleConfiguration 및 PutBucketLifecycleConfiguration 작업(만료 작업만 해당) 및 다음에 대한 지원이 추가되었습니다. `x-amz-expiration` 응답 헤더.
* 수집 시 동기 배치를 사용하는 ILM 규칙의 영향을 설명하기 위해 PutObject, CopyObject 및 MultipartUpload를 업데이트했습니다.
* TLS 1.1 암호는 더 이상 지원되지 않습니다.




 a| 
11.2
 a| 
Cloud Storage 풀과 함께 사용할 RestoreObject에 대한 지원이 추가되었습니다.  그룹 및 버킷 정책에서 ARN, 정책 조건 키, 정책 변수에 대한 AWS 구문 사용에 대한 지원이 추가되었습니다.  StorageGRID 구문을 사용하는 기존 그룹 및 버킷 정책은 계속 지원됩니다.

*참고:* 사용자 정의 StorageGRID 기능에서 사용되는 것을 포함하여 다른 구성 JSON/XML에서 ARN/URN을 사용하는 방식은 변경되지 않았습니다.



 a| 
11.1
 a| 
CORS(교차 출처 리소스 공유), 그리드 노드에 대한 S3 클라이언트 연결을 위한 HTTP, 버킷의 규정 준수 설정에 대한 지원이 추가되었습니다.



 a| 
11.0
 a| 
버킷에 대한 플랫폼 서비스(CloudMirror 복제, 알림, Elasticsearch 검색 통합) 구성에 대한 지원이 추가되었습니다.  또한 버킷에 대한 객체 태그 위치 제약 조건과 사용 가능한 일관성에 대한 지원이 추가되었습니다.



 a| 
10.4
 a| 
버전 관리, Endpoint Domain Names 페이지 업데이트, 정책의 조건 및 변수, 정책 예제, PutOverwriteObject 권한에 대한 ILM 스캐닝 변경 사항에 대한 지원이 추가되었습니다.



 a| 
10.3
 a| 
버전 관리에 대한 지원이 추가되었습니다.



 a| 
10.2
 a| 
그룹 및 버킷 액세스 정책과 다중 파트 복사(UploadPartCopy)에 대한 지원이 추가되었습니다.



 a| 
10.1
 a| 
멀티파트 업로드, 가상 호스팅 스타일 요청 및 v4 인증에 대한 지원이 추가되었습니다.



 a| 
10.0
 a| 
StorageGRID 시스템에서 S3 REST API를 처음 지원합니다. 현재 지원되는 _Simple Storage Service API Reference_ 버전은 2006-03-01입니다.

|===