---
permalink: s3/deprecated-put-bucket-compliance-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, PUT deprecated compliance requests 
summary: PUT 버킷 규정 준수 요청은 더 이상 사용되지 않습니다.  하지만 이 요청을 계속 사용하여 기존 레거시 규정 준수 버킷의 규정 준수 설정을 수정할 수 있습니다. 
---
= 더 이상 사용되지 않음: PUT 버킷 규정 준수 요청
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PUT 버킷 규정 준수 요청은 더 이상 사용되지 않습니다.  하지만 이 요청을 계속 사용하여 기존 레거시 규정 준수 버킷의 규정 준수 설정을 수정할 수 있습니다.  예를 들어, 기존 버킷을 법적 보류 상태로 두거나 보관 기간을 늘릴 수 있습니다.

[NOTE]
====
이전 StorageGRID 버전에서 사용 가능했던 StorageGRID 규정 준수 기능은 더 이상 사용되지 않으며 S3 개체 잠금으로 대체되었습니다.  자세한 내용은 다음을 참조하세요.

* link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 객체 잠금을 구성합니다."]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp 지식 기반: StorageGRID 11.5에서 레거시 호환 버킷을 관리하는 방법"^]


====
이 작업을 완료하려면 s3:PutBucketCompliance 권한이 있거나 계정 루트여야 합니다.

PUT 버킷 규정 준수 요청을 발행할 때 규정 준수 설정의 모든 필드에 값을 지정해야 합니다.



== 요청 예시

이 예제 요청은 이름이 지정된 버킷의 규정 준수 설정을 수정합니다. `mybucket` .  이 예에서 객체는 `mybucket` 이제 객체가 그리드에 수집된 시점부터 1년이 아닌 2년(1,051,200분) 동안 보관됩니다.  이 버킷에는 법적 구속력이 없습니다.  각 객체는 2년 후 자동으로 삭제됩니다.

[listing, subs="specialcharacters,quotes"]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization name_
Host: _host_
Content-Length: 152

<SGCompliance>
  <RetentionPeriodMinutes>1051200</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
[cols="1a,2a"]
|===
| 이름 | 설명 


 a| 
보존 기간(분)
 a| 
이 버킷에 추가된 객체의 보존 기간(분)입니다.  보존 기간은 객체가 그리드에 수집되는 시점부터 시작됩니다.

*중요* RetentionPeriodMinutes에 대한 새 값을 지정할 때 버킷의 현재 보존 기간보다 크거나 같은 값을 지정해야 합니다.  버킷의 보존 기간이 설정된 후에는 해당 값을 줄일 수 없고, 늘릴 수만 있습니다.



 a| 
리걸홀드
 a| 
* 참: 이 버킷은 현재 법적 보류 중입니다.  이 버킷의 객체는 보존 기간이 만료된 경우에도 법적 보류가 해제될 때까지 삭제할 수 없습니다.
* 거짓: 이 버킷은 현재 법적 보류 상태에 있지 않습니다.  이 버킷의 객체는 보존 기간이 만료되면 삭제될 수 있습니다.




 a| 
자동 삭제
 a| 
* 참: 버킷에 법적 보류가 적용되지 않는 한, 보존 기간이 만료되면 이 버킷의 객체는 자동으로 삭제됩니다.
* 거짓: 보존 기간이 만료되어도 이 버킷의 개체는 자동으로 삭제되지 않습니다.  해당 객체를 삭제해야 하는 경우 수동으로 삭제해야 합니다.


|===


== 규정 준수 설정에 대한 일관성

PUT 버킷 규정 준수 요청으로 S3 버킷의 규정 준수 설정을 업데이트하면 StorageGRID 그리드 전체에서 버킷의 메타데이터를 업데이트하려고 시도합니다.  기본적으로 StorageGRID *강력한 글로벌* 일관성을 사용하여 모든 데이터 센터 사이트와 버킷 메타데이터가 포함된 모든 스토리지 노드가 변경된 규정 준수 설정에 대해 읽기 후 쓰기 일관성을 갖도록 보장합니다.

데이터 센터 사이트 또는 사이트의 여러 스토리지 노드를 사용할 수 없어 StorageGRID *강력한 글로벌* 일관성을 달성할 수 없는 경우 응답에 대한 HTTP 상태 코드는 다음과 같습니다. `503 Service Unavailable.`

이러한 응답을 받으면 그리드 관리자에게 연락하여 필요한 저장 서비스를 최대한 빨리 사용할 수 있도록 해야 합니다.  그리드 관리자가 각 사이트에서 충분한 스토리지 노드를 확보할 수 없는 경우, 기술 지원팀은 *강력한 사이트* 일관성을 강제로 적용하여 실패한 요청을 다시 시도하도록 지시할 수 있습니다.


CAUTION: 기술 지원팀의 지시가 있거나 이 수준을 사용할 경우 발생할 수 있는 잠재적 결과를 이해하지 못하는 한, PUT 버킷 규정 준수를 위해 *강력한 사이트* 일관성을 강제로 적용하지 마세요.

일관성이 *강력한 사이트*로 낮아지면 StorageGRID 업데이트된 규정 준수 설정이 사이트 내의 클라이언트 요청에 대해서만 읽기 후 쓰기 일관성을 갖도록 보장합니다.  즉, 모든 사이트와 스토리지 노드를 사용할 수 있을 때까지 StorageGRID 시스템은 이 버킷에 대해 일시적으로 여러 개의 일관되지 않은 설정을 가질 수 있습니다.  일관되지 않은 설정으로 인해 예상치 못한 바람직하지 않은 동작이 발생할 수 있습니다.  예를 들어, 버킷에 법적 보류를 적용하고 더 낮은 일관성을 강제로 적용하는 경우 버킷의 이전 규정 준수 설정(즉, 법적 보류)이 일부 데이터 센터 사이트에서 계속 적용될 수 있습니다.  결과적으로, 법적 보류 상태라고 생각되는 객체는 보존 기간이 만료되면 사용자에 의해 삭제되거나 자동 삭제(활성화된 경우)에 의해 삭제될 수 있습니다.

*강력한 사이트* 일관성 사용을 강제하려면 PUT 버킷 규정 준수 요청을 다시 발행하고 다음을 포함합니다. `Consistency-Control` HTTP 요청 헤더는 다음과 같습니다.

[listing]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Consistency-Control: strong-site
----


== 오류 응답

* 버킷이 규정을 준수하도록 생성되지 않은 경우 응답에 대한 HTTP 상태 코드는 다음과 같습니다. `404 Not Found` .
* 만약에 `RetentionPeriodMinutes` 요청이 버킷의 현재 보존 기간보다 짧은 경우 HTTP 상태 코드는 다음과 같습니다. `400 Bad Request` .


.관련 정보
link:deprecated-put-bucket-request-modifications-for-compliance.html["더 이상 사용되지 않음: 규정 준수를 위한 PUT 버킷 요청 수정"]
