---
permalink: s3/deprecated-bucket-requests-for-legacy-compliance.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated bucket requests 
summary: 기존 규정 준수 기능을 사용하여 생성된 버킷을 관리하려면 StorageGRID S3 REST API를 사용해야 할 수도 있습니다. 
---
= 레거시 규정 준수를 위한 더 이상 사용되지 않는 버킷 요청
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 규정 준수 기능을 사용하여 생성된 버킷을 관리하려면 StorageGRID S3 REST API를 사용해야 할 수도 있습니다.



== 규정 준수 기능이 더 이상 사용되지 않습니다.

이전 StorageGRID 버전에서 사용 가능했던 StorageGRID 규정 준수 기능은 더 이상 사용되지 않으며 S3 개체 잠금으로 대체되었습니다.

이전에 글로벌 규정 준수 설정을 활성화한 경우 StorageGRID 11.6에서는 글로벌 S3 개체 잠금 설정이 활성화됩니다.  더 이상 규정 준수가 활성화된 상태에서는 새 버킷을 생성할 수 없습니다. 그러나 필요에 따라 StorageGRID S3 REST API를 사용하여 기존의 모든 규정 준수 버킷을 관리할 수 있습니다.

* link:use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 객체 잠금을 구성합니다."]
* link:../ilm/index.html["ILM을 사용하여 객체 관리"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp 지식 기반: StorageGRID 11.5에서 레거시 호환 버킷을 관리하는 방법"^]


더 이상 사용되지 않는 규정 준수 요청:

* link:../s3/deprecated-put-bucket-request-modifications-for-compliance.html["더 이상 사용되지 않음 - 규정 준수를 위한 PUT 버킷 요청 수정"]
+
SGCompliance XML 요소는 더 이상 사용되지 않습니다.  이전에는 PUT 버킷 요청의 선택적 XML 요청 본문에 이 StorageGRID 사용자 지정 요소를 포함하여 규정 준수 버킷을 생성할 수 있었습니다.

* link:../s3/deprecated-get-bucket-compliance-request.html["더 이상 사용되지 않음 - GET 버킷 규정 준수"]
+
GET 버킷 규정 준수 요청은 더 이상 사용되지 않습니다.  하지만 이 요청을 계속 사용하여 기존 레거시 규정 준수 버킷에 현재 적용된 규정 준수 설정을 확인할 수 있습니다.

* link:../s3/deprecated-put-bucket-compliance-request.html["더 이상 사용되지 않음 - PUT 버킷 규정 준수"]
+
PUT 버킷 규정 준수 요청은 더 이상 사용되지 않습니다.  하지만 이 요청을 계속 사용하여 기존 레거시 규정 준수 버킷의 규정 준수 설정을 수정할 수 있습니다.  예를 들어, 기존 버킷을 법적 보류 상태로 두거나 보관 기간을 늘릴 수 있습니다.


