---
permalink: s3/deprecated-get-bucket-compliance-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, deprecated GET compliance requests 
summary: GET 버킷 규정 준수 요청은 더 이상 사용되지 않습니다.  하지만 이 요청을 계속 사용하여 기존 레거시 규정 준수 버킷에 현재 적용된 규정 준수 설정을 확인할 수 있습니다. 
---
= 더 이상 사용되지 않음: GET 버킷 규정 준수 요청
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
GET 버킷 규정 준수 요청은 더 이상 사용되지 않습니다.  하지만 이 요청을 계속 사용하여 기존 레거시 규정 준수 버킷에 현재 적용된 규정 준수 설정을 확인할 수 있습니다.

[NOTE]
====
이전 StorageGRID 버전에서 사용 가능했던 StorageGRID 규정 준수 기능은 더 이상 사용되지 않으며 S3 개체 잠금으로 대체되었습니다.  자세한 내용은 다음을 참조하세요.

* link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 객체 잠금을 구성합니다."]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp 지식 기반: StorageGRID 11.5에서 레거시 호환 버킷을 관리하는 방법"^]


====
이 작업을 완료하려면 s3:GetBucketCompliance 권한이 있거나 계정 루트여야 합니다.



== 요청 예시

이 예제 요청을 통해 버킷에 대한 규정 준수 설정을 결정할 수 있습니다. `mybucket` .

[listing, subs="specialcharacters,quotes"]
----
GET /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== 응답 예시

응답 XML에서, `<SGCompliance>` 버킷에 적용되는 규정 준수 설정을 나열합니다.  이 예시 응답은 각 객체가 그리드에 수집된 날로부터 1년(525,600분) 동안 보관되는 버킷에 대한 규정 준수 설정을 보여줍니다.  현재 이 버킷에 대한 법적 보류는 없습니다.  각 객체는 1년 후 자동으로 삭제됩니다.

[listing, subs="specialcharacters,quotes"]
----
HTTP/1.1 200 OK
Date: _date_
Connection: _connection_
Server: StorageGRID/11.1.0
x-amz-request-id: _request ID_
Content-Length: _length_
Content-Type: application/xml

<SGCompliance>
  <RetentionPeriodMinutes>525600</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
[cols="1a,2a"]
|===
| 이름 | 설명 


 a| 
보존 기간(분)
 a| 
이 버킷에 추가된 객체의 보존 기간(분)입니다.  보존 기간은 객체가 그리드에 수집되는 시점부터 시작됩니다.



 a| 
리걸홀드
 a| 
* 참: 이 버킷은 현재 법적 보류 중입니다.  이 버킷의 객체는 보존 기간이 만료된 경우에도 법적 보류가 해제될 때까지 삭제할 수 없습니다.
* 거짓: 이 버킷은 현재 법적 보류 상태에 있지 않습니다.  이 버킷의 객체는 보존 기간이 만료되면 삭제될 수 있습니다.




 a| 
자동 삭제
 a| 
* 참: 버킷에 법적 보류가 적용되지 않는 한, 보존 기간이 만료되면 이 버킷의 객체는 자동으로 삭제됩니다.
* 거짓: 보존 기간이 만료되어도 이 버킷의 개체는 자동으로 삭제되지 않습니다.  해당 객체를 삭제해야 하는 경우 수동으로 삭제해야 합니다.


|===


== 오류 응답

버킷이 규정을 준수하도록 생성되지 않은 경우 응답에 대한 HTTP 상태 코드는 다음과 같습니다. `404 Not Found` , S3 오류 코드와 함께 `XNoSuchBucketCompliance` .
