---
permalink: s3/example-group-policies.html 
sidebar: sidebar 
keywords: group policy examples 
summary: 이 섹션의 예를 사용하여 그룹에 대한 StorageGRID 액세스 정책을 구축하세요. 
---
= 그룹 정책 예시
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 섹션의 예를 사용하여 그룹에 대한 StorageGRID 액세스 정책을 구축하세요.

그룹 정책은 정책이 연결된 그룹에 대한 액세스 권한을 지정합니다.  없습니다 `Principal` 정책의 요소이기 때문에 암묵적입니다.  그룹 정책은 테넌트 관리자 또는 API를 사용하여 구성됩니다.



== 예: 테넌트 관리자를 사용하여 그룹 정책 설정

테넌트 관리자에서 그룹을 추가하거나 편집할 때 그룹 정책을 선택하여 이 그룹의 구성원이 가질 S3 액세스 권한을 결정할 수 있습니다. 보다 link:../tenant/creating-groups-for-s3-tenant.html["S3 테넌트에 대한 그룹 생성"] .

* *S3 접근 불가*: 기본 옵션입니다.  이 그룹의 사용자는 버킷 정책으로 액세스 권한이 부여되지 않는 한 S3 리소스에 액세스할 수 없습니다.  이 옵션을 선택하면 기본적으로 루트 사용자만 S3 리소스에 액세스할 수 있습니다.
* *읽기 전용 액세스*: 이 그룹의 사용자는 S3 리소스에 대한 읽기 전용 액세스 권한을 갖습니다.  예를 들어, 이 그룹의 사용자는 객체를 나열하고 객체 데이터, 메타데이터, 태그를 읽을 수 있습니다.  이 옵션을 선택하면 읽기 전용 그룹 정책에 대한 JSON 문자열이 텍스트 상자에 나타납니다.  이 문자열을 편집할 수 없습니다.
* *전체 액세스*: 이 그룹의 사용자는 버킷을 포함한 S3 리소스에 대한 전체 액세스 권한을 갖습니다.  이 옵션을 선택하면 전체 액세스 그룹 정책에 대한 JSON 문자열이 텍스트 상자에 나타납니다.  이 문자열을 편집할 수 없습니다.
* *랜섬웨어 완화*: 이 샘플 정책은 이 테넌트의 모든 버킷에 적용됩니다.  이 그룹의 사용자는 일반적인 작업을 수행할 수 있지만, 개체 버전 관리가 활성화된 버킷에서 개체를 영구적으로 삭제할 수는 없습니다.
+
모든 버킷 관리 권한이 있는 테넌트 관리자 사용자는 이 그룹 정책을 재정의할 수 있습니다.  모든 버킷 관리 권한을 신뢰할 수 있는 사용자로 제한하고, 가능한 경우 다중 인증(MFA)을 사용하세요.

* *사용자 지정*: 그룹의 사용자에게 텍스트 상자에 지정한 권한이 부여됩니다.




== 예: 모든 버킷에 대한 전체 액세스 허용

이 예에서 그룹의 모든 구성원은 버킷 정책에서 명시적으로 거부하지 않는 한 테넌트 계정이 소유한 모든 버킷에 대한 전체 액세스가 허용됩니다.

[listing]
----
{
  "Statement": [
    {
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::*"
    }
  ]
}
----


== 예: 모든 버킷에 대한 그룹 읽기 전용 액세스 허용

이 예에서 그룹의 모든 구성원은 버킷 정책에서 명시적으로 거부하지 않는 한 S3 리소스에 대한 읽기 전용 액세스 권한을 갖습니다.  예를 들어, 이 그룹의 사용자는 객체를 나열하고 객체 데이터, 메타데이터, 태그를 읽을 수 있습니다.

[listing]
----
{
  "Statement": [
    {
      "Sid": "AllowGroupReadOnlyAccess",
      "Effect": "Allow",
      "Action": [
        "s3:ListAllMyBuckets",
        "s3:ListBucket",
        "s3:ListBucketVersions",
        "s3:GetObject",
        "s3:GetObjectTagging",
        "s3:GetObjectVersion",
        "s3:GetObjectVersionTagging"
      ],
      "Resource": "arn:aws:s3:::*"
    }
  ]
}
----


== 예: 그룹 구성원에게 버킷의 "폴더"에만 전체 액세스 허용

이 예에서, 그룹 구성원은 지정된 버킷의 특정 폴더(키 접두사)만 나열하고 액세스할 수 있습니다.  이러한 폴더의 개인 정보 보호를 결정할 때는 다른 그룹 정책과 버킷 정책의 액세스 권한을 고려해야 합니다.

[listing]
----
{
  "Statement": [
    {
      "Sid": "AllowListBucketOfASpecificUserPrefix",
      "Effect": "Allow",
      "Action": "s3:ListBucket",
      "Resource": "arn:aws:s3:::department-bucket",
      "Condition": {
        "StringLike": {
          "s3:prefix": "${aws:username}/*"
        }
      }
    },
    {
      "Sid": "AllowUserSpecificActionsOnlyInTheSpecificUserPrefix",
      "Effect": "Allow",
      "Action": "s3:*Object",
      "Resource": "arn:aws:s3:::department-bucket/${aws:username}/*"
    }
  ]
}
----