---
permalink: s3/head-object.html 
sidebar: sidebar 
keywords: HeadObject 
summary: S3 HeadObject 요청을 사용하면 객체 자체를 반환하지 않고도 객체에서 메타데이터를 검색할 수 있습니다. 
---
= 헤드오브젝트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 HeadObject 요청을 사용하면 객체 자체를 반환하지 않고도 객체에서 메타데이터를 검색할 수 있습니다.  객체가 Cloud Storage Pool에 저장된 경우 HeadObject를 사용하여 객체의 전환 상태를 확인할 수 있습니다.



== HeadObject 및 multipart 객체

당신은 사용할 수 있습니다 `partNumber` 다중 파트 또는 세그먼트화된 객체의 특정 부분에 대한 메타데이터를 검색하기 위한 요청 매개변수입니다.  그만큼 `x-amz-mp-parts-count` 응답 요소는 객체가 몇 개의 부분으로 구성되어 있는지를 나타냅니다.

설정할 수 있습니다 `partNumber` 분할/다중 파트 개체와 분할되지 않은/다중 파트가 아닌 개체 모두에 대해 1로 설정됩니다. 그러나 `x-amz-mp-parts-count` 응답 요소는 분할된 객체나 다중 부분 객체에 대해서만 반환됩니다.



== 사용자 메타데이터의 UTF-8 문자

StorageGRID 사용자 정의 메타데이터에서 이스케이프된 UTF-8 문자를 구문 분석하거나 해석하지 않습니다.  사용자 정의 메타데이터에 이스케이프된 UTF-8 문자가 포함된 개체에 대한 HEAD 요청은 다음을 반환하지 않습니다. `x-amz-missing-meta` 키 이름이나 값에 인쇄할 수 없는 문자가 포함된 경우 헤더를 지정합니다.



== 지원되는 요청 헤더

다음 요청 헤더가 지원됩니다.

* `x-amz-checksum-mode`
+
그만큼 `partNumber` 매개변수 및 `Range` 헤더는 지원되지 않습니다 `x-amz-checksum-mode` HeadObject에 대한.  요청에 포함시킬 때 `x-amz-checksum-mode` 활성화된 경우 StorageGRID 응답에서 체크섬 값을 반환하지 않습니다.





== 지원되지 않는 요청 헤더

다음 요청 헤더는 지원되지 않으며 다음을 반환합니다. `XNotImplemented` :

* `x-amz-website-redirect-location`




== 버전 관리

만약 `versionId` 하위 리소스가 지정되지 않으면 작업은 버전이 지정된 버킷에서 해당 객체의 최신 버전을 가져옵니다.  개체의 현재 버전이 삭제 마커인 경우 "찾을 수 없음" 상태가 반환됩니다. `x-amz-delete-marker` 응답 헤더가 다음으로 설정됨 `true` .



== 고객이 제공한 암호화 키(SSE-C)를 사용한 서버 측 암호화를 위한 요청 헤더

사용자가 제공한 고유 키로 개체가 암호화된 경우 이 세 개의 헤더를 모두 사용하세요.

* `x-amz-server-side-encryption-customer-algorithm`: 지정 `AES256` .
* `x-amz-server-side-encryption-customer-key`: 개체에 대한 암호화 키를 지정합니다.
* `x-amz-server-side-encryption-customer-key-MD5`: 객체의 암호화 키의 MD5 다이제스트를 지정합니다.



CAUTION: 귀하가 제공한 암호화 키는 결코 저장되지 않습니다.  암호화 키를 잃어버리면 해당 객체도 잃어버리게 됩니다.  고객이 제공한 키를 사용하여 개체 데이터를 보호하기 전에 다음 고려 사항을 검토하십시오.link:using-server-side-encryption.html["서버 측 암호화를 사용하세요"] .



== Cloud Storage Pool 객체에 대한 HeadObject 응답

객체가 다음에 저장되어 있는 경우link:../ilm/what-cloud-storage-pool-is.html["클라우드 스토리지 풀"] , 다음 응답 헤더가 반환됩니다.

* `x-amz-storage-class: GLACIER`
* `x-amz-restore`


응답 헤더는 객체가 Cloud Storage 풀로 이동되고, 선택적으로 검색 불가능한 상태로 전환되고, 복원되는 과정에 대한 정보를 제공합니다.

[cols="1a,1a"]
|===
| 객체의 상태 | HeadObject에 대한 응답 


 a| 
StorageGRID 에 수집되었지만 아직 ILM에서 평가되지 않은 객체 또는 기존 스토리지 풀에 저장된 객체 또는 삭제 코딩을 사용하는 객체
 a| 
`200 OK`(특별한 응답 헤더는 반환되지 않습니다.)



 a| 
Cloud Storage Pool에 있는 객체이지만 아직 검색 불가능한 상태로 전환되지 않았습니다.
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2030 00:00:00 GMT"`

객체가 검색 불가능한 상태로 전환될 때까지 값은 `expiry-date` 미래의 어느 먼 시간으로 설정되어 있습니다.  전환의 정확한 시간은 StorageGRID 시스템에서 제어되지 않습니다.



 a| 
개체가 검색 불가 상태로 전환되었지만 그리드에 최소한 하나의 사본도 존재합니다.
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2030 00:00:00 GMT"`

에 대한 가치 `expiry-date` 미래의 어느 먼 시간으로 설정되어 있습니다.

*참고*: 그리드의 복사본을 사용할 수 없는 경우(예: 스토리지 노드가 다운된 경우) 다음을 실행해야 합니다.link:post-object-restore.html["복원 개체"] 객체를 성공적으로 검색하려면 먼저 Cloud Storage Pool에서 복사본을 복원하라는 요청을 해야 합니다.



 a| 
개체가 검색 불가능한 상태로 전환되었으며 그리드에 복사본이 없습니다.
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`



 a| 
복구 불가능한 상태에서 복구 중인 객체
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="true"`



 a| 
객체가 Cloud Storage Pool에 완전히 복원되었습니다.
 a| 
`200 OK`

`x-amz-storage-class: GLACIER`

`x-amz-restore: ongoing-request="false", expiry-date="Sat, 23 July 20 2018 00:00:00 GMT"`

그만큼 `expiry-date` Cloud Storage 풀의 객체가 검색 불가능한 상태로 반환되는 시점을 나타냅니다.

|===


=== Cloud Storage Pool의 다중 부분 또는 분할된 객체

여러 부분으로 구성된 객체를 업로드하거나 StorageGRID 큰 객체를 여러 세그먼트로 분할한 경우 StorageGRID 객체의 부분 또는 세그먼트 하위 집합을 샘플링하여 해당 객체를 Cloud Storage 풀에서 사용할 수 있는지 여부를 확인합니다.  어떤 경우에는 HeadObject 요청이 잘못 반환될 수 있습니다. `x-amz-restore: ongoing-request="false"` 객체의 일부가 이미 복구 불가능한 상태로 전환되었거나 객체의 일부가 아직 복원되지 않은 경우입니다.



== HeadObject 및 크로스 그리드 복제

당신이 사용하는 경우link:../admin/grid-federation-overview.html["그리드 연합"] 그리고link:../tenant/grid-federation-manage-cross-grid-replication.html["크로스 그리드 복제"] 버킷에 대해 복제가 활성화되면 S3 클라이언트는 HeadObject 요청을 발행하여 객체의 복제 상태를 확인할 수 있습니다.  응답에는 StorageGRID 관련 내용이 포함됩니다. `x-ntap-sg-cgr-replication-status` 응답 헤더는 다음 값 중 하나를 갖습니다.

[cols="1a,2a"]
|===
| 그리드 | 복제 상태 


 a| 
원천
 a| 
* *완료*: 복제가 성공했습니다.
* *보류*: 객체가 아직 복제되지 않았습니다.
* *실패*: 복제가 영구적인 오류로 실패했습니다. 사용자는 오류를 해결해야 합니다.




 a| 
목적지
 a| 
*REPLICA*: 개체가 소스 그리드에서 복제되었습니다.

|===

NOTE: StorageGRID 지원하지 않습니다 `x-amz-replication-status` 헤더.
