---
permalink: s3/index.html 
sidebar: sidebar 
keywords: about s3, s3 rest api, s3 overview 
summary: 'StorageGRID REST(Representational State Transfer) 웹 서비스 세트로 구현된 Simple Storage Service(S3) API를 지원합니다.' 
---
= S3 REST API 지원 버전 및 업데이트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID REST(Representational State Transfer) 웹 서비스 세트로 구현된 S3(Simple Storage Service) API를 지원합니다.

S3 REST API에 대한 지원을 통해 S3 웹 서비스용으로 개발된 서비스 지향 애플리케이션을 StorageGRID 시스템을 사용하는 온프레미스 개체 스토리지와 연결할 수 있습니다.  클라이언트 애플리케이션의 현재 S3 REST API 호출 사용에 최소한의 변경만 필요합니다.



== 지원되는 버전

StorageGRID 다음과 같은 특정 버전의 S3 및 HTTP를 지원합니다.

[cols="1a,1a"]
|===
| 목 | 버전 


 a| 
S3 API 사양
 a| 
http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["Amazon Web Services(AWS) 설명서: Amazon Simple Storage Service API 참조"^]



 a| 
HTTP
 a| 
1.1

HTTP에 대한 자세한 내용은 HTTP/1.1(RFC 7230-35)을 참조하세요.

https://datatracker.ietf.org/doc/html/rfc2616["IETF RFC 2616: 하이퍼텍스트 전송 프로토콜(HTTP/1.1)"^]

*참고*: StorageGRID HTTP/1.1 파이프라인을 지원하지 않습니다.

|===


== S3 REST API 지원 업데이트

[cols="1a,4a"]
|===
| 풀어 주다 | 댓글 


 a| 
11.9
 a| 
* 다음 요청과 지원되는 헤더에 대해 미리 계산된 SHA-256 체크섬 값에 대한 지원이 추가되었습니다.  이 기능을 사용하면 업로드된 개체의 무결성을 확인할 수 있습니다.
+
** CompleteMultipartUpload: `x-amz-checksum-sha256`
** CreateMultipartUpload: `x-amz-checksum-algorithm`
** 객체 가져오기: `x-amz-checksum-mode`
** HeadObject: `x-amz-checksum-mode`
** 리스트파트
** PutObject: `x-amz-checksum-sha256`
** 업로드 부분: `x-amz-checksum-sha256`


* 그리드 관리자가 테넌트 수준 보존 및 규정 준수 설정을 제어할 수 있는 기능이 추가되었습니다.  이러한 설정은 S3 개체 잠금 설정에 영향을 미칩니다.
+
** 버킷 기본 보존 모드 및 객체 보존 모드: 그리드 관리자가 허용하는 경우 거버넌스 또는 규정 준수.
** 버킷 기본 보존 기간 및 개체 보존 기간: 그리드 관리자가 설정한 최대 보존 기간에서 허용하는 기간보다 짧거나 같아야 합니다.


* 향상된 지원 `aws-chunked` 콘텐츠 인코딩 및 스트리밍 `x-amz-content-sha256` 가치. 제한 사항:
+
** 존재하는 경우, `chunk-signature` 선택 사항이며 검증되지 않습니다.
** 존재하는 경우, `x-amz-trailer` 내용이 무시됩니다






 a| 
11.8
 a| 
S3 작업의 이름을 사용된 이름과 일치하도록 업데이트했습니다. http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html["Amazon Web Services(AWS) 설명서: Amazon Simple Storage Service API 참조"^] .



 a| 
11.7
 a| 
* 추가됨link:quick-reference-support-for-aws-apis.html["빠른 참조: 지원되는 S3 API 요청"] .
* S3 개체 잠금과 함께 GOVERNANCE 모드를 사용하기 위한 지원이 추가되었습니다.
* StorageGRID 관련 지원이 추가되었습니다. `x-ntap-sg-cgr-replication-status` GET Object 및 HEAD Object 요청에 대한 응답 헤더입니다.  이 헤더는 그리드 간 복제에 대한 객체의 복제 상태를 제공합니다.
* SelectObjectContent 요청은 이제 Parquet 객체를 지원합니다.




 a| 
11.6
 a| 
* 사용에 대한 지원이 추가되었습니다. `partNumber` GET 객체 및 HEAD 객체 요청의 요청 매개변수.
* S3 객체 잠금에 대한 기본 보존 모드와 버킷 수준의 기본 보존 기간에 대한 지원이 추가되었습니다.
* 추가 지원 `s3:object-lock-remaining-retention-days` 정책 조건 키를 사용하여 개체에 허용되는 보존 기간 범위를 설정합니다.
* 단일 PUT 개체 작업에 대한 최대 권장 크기를 5GiB(5,368,709,120바이트)로 변경했습니다.  5GiB보다 큰 객체가 있는 경우 대신 멀티파트 업로드를 사용하세요.




 a| 
11.5
 a| 
* 버킷 암호화 관리에 대한 지원이 추가되었습니다.
* S3 개체 잠금에 대한 지원이 추가되었고 더 이상 사용되지 않는 레거시 규정 준수 요청이 추가되었습니다.
* 버전이 지정된 버킷에서 여러 개체를 삭제하기 위한 지원이 추가되었습니다.
* 그만큼 `Content-MD5` 요청 헤더가 이제 올바르게 지원됩니다.




 a| 
11.4
 a| 
* DELETE 버킷 태그, GET 버킷 태그, PUT 버킷 태그에 대한 지원이 추가되었습니다.  비용 할당 태그는 지원되지 않습니다.
* StorageGRID 11.4에서 생성된 버킷의 경우 성능 모범 사례를 충족하기 위해 개체 키 이름을 제한할 필요가 더 이상 없습니다.
* 버킷 알림에 대한 지원이 추가되었습니다. `s3:ObjectRestore:Post` 이벤트 유형.
* 이제 다중 파트 파트에 대한 AWS 크기 제한이 적용됩니다.  멀티파트 업로드의 각 부분은 5MiB~5GiB 사이여야 합니다.  마지막 부분은 5MiB보다 작을 수 있습니다.
* TLS 1.3에 대한 지원이 추가되었습니다.




 a| 
11.3
 a| 
* 고객이 제공한 키(SSE-C)를 사용하여 개체 데이터의 서버 측 암호화에 대한 지원이 추가되었습니다.
* DELETE, GET 및 PUT 버킷 수명 주기 작업(만료 작업만 해당) 및 다음 작업에 대한 지원이 추가되었습니다. `x-amz-expiration` 응답 헤더.
* 수집 시 동기 배치를 사용하는 ILM 규칙의 영향을 설명하기 위해 PUT 개체, PUT 개체 - 복사 및 다중 파트 업로드를 업데이트했습니다.
* TLS 1.1 암호는 더 이상 지원되지 않습니다.




 a| 
11.2
 a| 
Cloud Storage 풀과 함께 사용할 POST 개체 복원에 대한 지원이 추가되었습니다.  그룹 및 버킷 정책에서 ARN, 정책 조건 키, 정책 변수에 대한 AWS 구문 사용에 대한 지원이 추가되었습니다.  StorageGRID 구문을 사용하는 기존 그룹 및 버킷 정책은 계속 지원됩니다.

*참고:* 사용자 정의 StorageGRID 기능에서 사용되는 것을 포함하여 다른 구성 JSON/XML에서 ARN/URN을 사용하는 방식은 변경되지 않았습니다.



 a| 
11.1
 a| 
CORS(교차 출처 리소스 공유), 그리드 노드에 대한 S3 클라이언트 연결을 위한 HTTP, 버킷의 규정 준수 설정에 대한 지원이 추가되었습니다.



 a| 
11.0
 a| 
버킷에 대한 플랫폼 서비스(CloudMirror 복제, 알림, Elasticsearch 검색 통합) 구성에 대한 지원이 추가되었습니다.  또한 버킷에 대한 객체 태그 위치 제약 조건과 사용 가능한 일관성에 대한 지원이 추가되었습니다.



 a| 
10.4
 a| 
버전 관리, Endpoint Domain Names 페이지 업데이트, 정책의 조건 및 변수, 정책 예제, PutOverwriteObject 권한에 대한 ILM 스캐닝 변경 사항에 대한 지원이 추가되었습니다.



 a| 
10.3
 a| 
버전 관리에 대한 지원이 추가되었습니다.



 a| 
10.2
 a| 
그룹 및 버킷 액세스 정책과 다중 파트 복사(파트 업로드 - 복사)에 대한 지원이 추가되었습니다.



 a| 
10.1
 a| 
멀티파트 업로드, 가상 호스팅 스타일 요청 및 v4 인증에 대한 지원이 추가되었습니다.



 a| 
10.0
 a| 
StorageGRID 시스템에서 S3 REST API를 처음 지원합니다. 현재 지원되는 _Simple Storage Service API Reference_ 버전은 2006-03-01입니다.

|===