---
permalink: s3/initiate-multipart-upload.html 
sidebar: sidebar 
keywords: initiate multipart upload, CreateMultipartUpload, upload ID 
summary: CreateMultipartUpload 작업은 객체에 대한 멀티파트 업로드를 시작하고 업로드 ID를 반환합니다. 
---
= CreateMultipartUpload
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CreateMultipartUpload(이전 명칭: Initiate Multipart Upload) 작업은 객체에 대한 멀티파트 업로드를 시작하고 업로드 ID를 반환합니다.

그만큼 `x-amz-storage-class` 요청 헤더가 지원됩니다.  제출된 값 `x-amz-storage-class` StorageGRID 수집 중에 개체 데이터를 보호하는 방법에 영향을 주며, StorageGRID 시스템에 저장된 개체의 영구 복사본 수(ILM에서 결정)에는 영향을 주지 않습니다.

섭취된 개체와 일치하는 ILM 규칙이 Strict를 사용하는 경우link:../ilm/data-protection-options-for-ingest.html["수집 옵션"] , 그 `x-amz-storage-class` 헤더는 효과가 없습니다.

다음 값을 사용할 수 있습니다. `x-amz-storage-class` :

* `STANDARD`(기본)
+
** *이중 커밋*: ILM 규칙에서 이중 커밋 수집 옵션을 지정하는 경우, 객체가 수집되자마자 해당 객체의 두 번째 사본이 생성되어 다른 스토리지 노드에 배포됩니다(이중 커밋).  ILM을 평가할 때 StorageGRID 이러한 초기 임시 사본이 규칙의 배치 지침을 충족하는지 확인합니다.  그렇지 않은 경우 새로운 객체 복사본을 다른 위치에 만들어야 할 수도 있고, 초기 임시 복사본을 삭제해야 할 수도 있습니다.
** *균형*: ILM 규칙이 균형 옵션을 지정하고 StorageGRID 규칙에 지정된 모든 복사본을 즉시 만들 수 없는 경우 StorageGRID 서로 다른 스토리지 노드에 두 개의 임시 복사본을 만듭니다.
+
StorageGRID ILM 규칙(동기 배치)에 지정된 모든 개체 복사본을 즉시 생성할 수 있는 경우 `x-amz-storage-class` 헤더는 효과가 없습니다.



* `REDUCED_REDUNDANCY`
+
** *이중 커밋*: ILM 규칙에서 이중 커밋 옵션을 지정하는 경우 StorageGRID 객체가 수집될 때 단일 임시 사본을 만듭니다(단일 커밋).
** *균형*: ILM 규칙에서 균형 옵션을 지정하는 경우 StorageGRID 시스템이 규칙에 지정된 모든 복사본을 즉시 만들 수 없는 경우에만 단일 임시 복사본을 만듭니다.  StorageGRID 동기 배치를 수행할 수 있는 경우 이 헤더는 아무런 효과가 없습니다.  그만큼 `REDUCED_REDUNDANCY` 이 옵션은 개체와 일치하는 ILM 규칙이 단일 복제 복사본을 생성할 때 가장 잘 사용됩니다.  이 경우 사용 `REDUCED_REDUNDANCY` 모든 수집 작업에 대해 불필요한 추가 객체 복사본 생성 및 삭제를 제거합니다.


+
를 사용하여 `REDUCED_REDUNDANCY` 다른 상황에서는 이 옵션을 권장하지 않습니다. `REDUCED_REDUNDANCY` 수집 중에 객체 데이터가 손실될 위험이 높아집니다.  예를 들어, ILM 평가가 발생하기 전에 실패한 스토리지 노드에 단일 사본이 처음 저장된 경우 데이터가 손실될 수 있습니다.




CAUTION: 특정 기간 동안 복제된 사본이 하나만 있으면 데이터가 영구적으로 손실될 위험이 있습니다.  개체의 복제된 사본이 하나만 있는 경우 스토리지 노드에 장애가 발생하거나 심각한 오류가 발생하면 해당 개체는 손실됩니다.  업그레이드 등의 유지 관리 절차가 진행되는 동안에는 해당 객체에 대한 액세스 권한을 일시적으로 잃게 됩니다.

지정 `REDUCED_REDUNDANCY` 객체가 처음 수집될 때 생성되는 복사본의 수에만 영향을 미칩니다.  이는 활성 ILM 정책에 따라 객체를 평가할 때 객체의 복사본이 얼마나 많이 만들어지는지에 영향을 미치지 않으며, StorageGRID 시스템에서 데이터가 더 낮은 수준의 중복으로 저장되는 결과를 초래하지 않습니다.


NOTE: S3 객체 잠금이 활성화된 버킷에 객체를 수집하는 경우 `REDUCED_REDUNDANCY` 옵션은 무시됩니다.  레거시 호환 버킷에 객체를 수집하는 경우 `REDUCED_REDUNDANCY` 옵션이 오류를 반환합니다.  StorageGRID 규정 준수 요구 사항이 충족되는지 확인하기 위해 항상 이중 커밋 수집을 수행합니다.



== 지원되는 요청 헤더

다음 요청 헤더가 지원됩니다.

* `Content-Type`
* `x-amz-checksum-algorithm`
+
현재는 SHA256 값만 가능합니다. `x-amz-checksum-algorithm` 지원됩니다.

* `x-amz-meta-`사용자 정의 메타데이터를 포함하는 이름-값 쌍이 뒤따릅니다.
+
사용자 정의 메타데이터에 대한 이름-값 쌍을 지정할 때 다음과 같은 일반 형식을 사용하세요.

+
[listing]
----
x-amz-meta-_name_: `value`
----
+
ILM 규칙의 참조 시간으로 *사용자 정의 생성 시간* 옵션을 사용하려면 다음을 사용해야 합니다. `creation-time` 객체가 생성된 시점을 기록하는 메타데이터의 이름으로. 예를 들어:

+
[listing]
----
x-amz-meta-creation-time: 1443399726
----
+
에 대한 가치 `creation-time` 1970년 1월 1일 이후의 초로 계산됩니다.

+

NOTE: 첨가 `creation-time` 레거시 규정 준수가 활성화된 버킷에 객체를 추가하는 경우 사용자 정의 메타데이터가 허용되지 않습니다.  오류가 반환됩니다.

* S3 객체 잠금 요청 헤더:
+
** `x-amz-object-lock-mode`
** `x-amz-object-lock-retain-until-date`
** `x-amz-object-lock-legal-hold`
+
이러한 헤더 없이 요청이 이루어지면 버킷 기본 보존 설정을 사용하여 개체 버전 보존 기간을 계산합니다.

+
link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 객체 잠금을 구성합니다."]



* SSE 요청 헤더:
+
** `x-amz-server-side-encryption`
** `x-amz-server-side-encryption-customer-key-MD5`
** `x-amz-server-side-encryption-customer-key`
** `x-amz-server-side-encryption-customer-algorithm`
+
<<서버 측 암호화를 위한 요청 헤더>>



+

NOTE: StorageGRID UTF-8 문자를 처리하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:put-object.html["PutObject"] .





== 서버 측 암호화를 위한 요청 헤더

다음 요청 헤더를 사용하면 서버 측 암호화를 통해 다중 파트 객체를 암호화할 수 있습니다.  SSE와 SSE-C 옵션은 상호 배타적입니다.

* *SSE*: StorageGRID 에서 관리하는 고유 키로 객체를 암호화하려면 CreateMultipartUpload 요청에서 다음 헤더를 사용합니다.  UploadPart 요청에서 이 헤더를 지정하지 마세요.
+
** `x-amz-server-side-encryption`


* *SSE-C*: 사용자가 제공하고 관리하는 고유 키로 객체를 암호화하려면 CreateMultipartUpload 요청(및 이후의 각 UploadPart 요청)에서 이 세 개의 헤더를 모두 사용합니다.
+
** `x-amz-server-side-encryption-customer-algorithm`: 지정 `AES256` .
** `x-amz-server-side-encryption-customer-key`: 새 개체에 대한 암호화 키를 지정합니다.
** `x-amz-server-side-encryption-customer-key-MD5`: 새 객체의 암호화 키의 MD5 다이제스트를 지정합니다.





CAUTION: 귀하가 제공한 암호화 키는 결코 저장되지 않습니다.  암호화 키를 잃어버리면 해당 객체도 잃어버리게 됩니다.  고객이 제공한 키를 사용하여 개체 데이터를 보호하기 전에 다음 사항을 검토하십시오.link:using-server-side-encryption.html["서버 측 암호화 사용"] .



== 지원되지 않는 요청 헤더

다음 요청 헤더는 지원되지 않습니다.

* `x-amz-website-redirect-location`
+
그만큼 `x-amz-website-redirect-location` 헤더 반환 `XNotImplemented` .





== 버전 관리

다중 파트 업로드는 업로드 시작, 업로드 목록 작성, 파트 업로드, 업로드된 파트 조립, 업로드 완료를 위한 별도의 작업으로 구성됩니다.  CompleteMultipartUpload 작업이 수행되면 개체가 생성되고(해당되는 경우 버전 관리도 수행됨)
