---
permalink: s3/object-versioning.html 
sidebar: sidebar 
keywords: object version, object versioning 
summary: 객체의 여러 버전을 보관하려면 버킷의 버전 상태를 설정할 수 있습니다.  버킷에 대한 버전 관리를 활성화하면 실수로 객체를 삭제하는 것을 방지하는 데 도움이 되며 객체의 이전 버전을 검색하여 복원할 수 있습니다. 
---
= 객체 버전 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 개체의 여러 버전을 보관하려면 버킷의 버전 상태를 설정할 수 있습니다.  버킷에 대한 버전 관리를 활성화하면 실수로 객체를 삭제하는 것을 방지하는 데 도움이 되며 객체의 이전 버전을 검색하여 복원할 수 있습니다.

StorageGRID 시스템은 대부분의 기능을 지원하고 몇 가지 제한 사항이 있는 버전 관리를 구현합니다.  StorageGRID 각 객체의 최대 10,000개 버전을 지원합니다.

객체 버전 관리 기능은 StorageGRID 정보 수명 주기 관리(ILM) 또는 S3 버킷 수명 주기 구성과 결합될 수 있습니다.  각 버킷에 대해 버전 관리를 명시적으로 활성화해야 합니다.  버킷에 버전 관리가 활성화된 경우 버킷에 추가된 각 개체에는 StorageGRID 시스템에서 생성된 버전 ID가 지정됩니다.

MFA(다중 인증) 사용 시 삭제가 지원되지 않습니다.


NOTE: 버전 관리 기능은 StorageGRID 버전 10.3 이상으로 생성된 버킷에서만 활성화할 수 있습니다.



== ILM 및 버전 관리

ILM 정책은 개체의 각 버전에 적용됩니다.  ILM 스캐닝 프로세스는 모든 객체를 지속적으로 스캔하고 현재 ILM 정책에 따라 다시 평가합니다.  ILM 정책을 변경하면 이전에 수집된 모든 개체에 적용됩니다.  버전 관리가 활성화된 경우 이전에 수집된 버전도 포함됩니다.  ILM 스캐닝은 이전에 수집된 객체에 새로운 ILM 변경 사항을 적용합니다.

버전 관리가 활성화된 버킷의 S3 개체의 경우 버전 관리 지원을 통해 참조 시간으로 "비현재 시간"을 사용하는 ILM 규칙을 만들 수 있습니다("이 규칙을 이전 개체 버전에만 적용합니까?"라는 질문에 대해 *예*를 선택합니다).link:../ilm/create-ilm-rule-enter-details.html["ILM 규칙 만들기 마법사의 1단계"] ).  객체가 업데이트되면 이전 버전은 더 이상 업데이트되지 않습니다.  "비현재 시간" 필터를 사용하면 이전 버전의 개체가 저장소에 미치는 영향을 줄이는 정책을 만들 수 있습니다.


NOTE: 멀티파트 업로드 작업을 사용하여 객체의 새 버전을 업로드하는 경우, 객체의 원래 버전에 대한 비현재 시간은 멀티파트 업로드가 완료된 시간이 아닌, 새 버전에 대한 멀티파트 업로드가 생성된 시간을 반영합니다.  제한된 경우지만 원래 버전의 비현재 시간은 현재 버전의 시간보다 몇 시간 또는 며칠 앞설 수 있습니다.

.관련 정보
* link:../ilm/how-objects-are-deleted.html#delete-s3-versioned-objects["S3 버전이 지정된 객체가 삭제되는 방식"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 버전 객체에 대한 ILM 규칙 및 정책(예 4)"] .

