---
permalink: s3/operations-for-multipart-uploads.html 
sidebar: sidebar 
keywords: operations, multipart uploads, uploads, rest API 
summary: 이 섹션에서는 StorageGRID 다중 파트 업로드 작업을 지원하는 방식을 설명합니다. 
---
= 멀티파트 업로드 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 StorageGRID 다중 파트 업로드 작업을 지원하는 방식을 설명합니다.

다음 조건 및 참고 사항은 모든 다중 파트 업로드 작업에 적용됩니다.

* 단일 버킷에 대한 동시 멀티파트 업로드는 1,000개를 초과해서는 안 됩니다. 해당 버킷에 대한 ListMultipartUploads 쿼리의 결과가 불완전한 결과를 반환할 수 있습니다.
* StorageGRID 다중 파트 파트에 대한 AWS 크기 제한을 적용합니다.  S3 클라이언트는 다음 지침을 따라야 합니다.
+
** 멀티파트 업로드의 각 부분은 5MiB(5,242,880바이트)에서 5GiB(5,368,709,120바이트) 사이여야 합니다.
** 마지막 부분은 5MiB(5,242,880바이트)보다 작을 수 있습니다.
** 일반적으로 부품 크기는 가능한 한 커야 합니다.  예를 들어, 100GiB 객체에 대해 5GiB의 부분 크기를 사용합니다.  각 부분이 고유한 개체로 간주되므로 큰 부분 크기를 사용하면 StorageGRID 메타데이터 오버헤드가 줄어듭니다.
** 5GiB보다 작은 객체의 경우 대신 비멀티파트 업로드를 사용하는 것이 좋습니다.


* ILM은 다중 파트 객체의 각 부분에 대해 수집될 때 평가되고 다중 파트 업로드가 완료될 때 객체 전체에 대해 평가됩니다. ILM 규칙이 Balanced 또는 Strict를 사용하는 경우link:../ilm/data-protection-options-for-ingest.html["수집 옵션"] .  이것이 객체와 부품 배치에 어떤 영향을 미치는지 알고 있어야 합니다.
+
** S3 멀티파트 업로드가 진행되는 동안 ILM이 변경되면 멀티파트 업로드가 완료될 때 객체의 일부가 현재 ILM 요구 사항을 충족하지 못할 수 있습니다.  올바르게 배치되지 않은 모든 부품은 ILM 재평가를 위해 대기열에 추가되고 나중에 올바른 위치로 옮겨집니다.
** 부품의 ILM을 평가할 때 StorageGRID 객체의 크기가 아닌 부품의 크기를 필터링합니다.  즉, 객체의 일부가 객체 전체에 대한 ILM 요구 사항을 충족하지 못하는 위치에 저장될 수 있다는 의미입니다.  예를 들어, 규칙에서 10GB 이상의 모든 객체는 DC1에 저장하고 그보다 작은 모든 객체는 DC2에 저장하도록 지정한 경우, 10개 부분으로 구성된 멀티파트 업로드의 각 1GB 부분은 수집 시 DC2에 저장됩니다.  하지만 ILM이 객체 전체에 대해 평가되는 경우 객체의 모든 부분이 DC1로 이동됩니다.


* 모든 다중 파트 업로드 작업은 StorageGRID 지원합니다.link:consistency-controls.html["일관성 값"] .
* 다중 파트 업로드를 사용하여 객체를 수집하는 경우link:../admin/what-object-segmentation-is.html["객체 분할 임계값(1GiB)"] 적용되지 않습니다.
* 필요에 따라 사용할 수 있습니다link:using-server-side-encryption.html["서버 측 암호화"] 여러 부분으로 업로드 가능.  SSE( StorageGRID 관리 키를 사용한 서버 측 암호화)를 사용하려면 다음을 포함합니다. `x-amz-server-side-encryption` CreateMultipartUpload 요청의 요청 헤더만.  SSE-C(고객 제공 키를 사용한 서버 측 암호화)를 사용하려면 CreateMultipartUpload 요청과 이후의 각 UploadPart 요청에서 동일한 세 개의 암호화 키 요청 헤더를 지정합니다.


[cols="2a,3a"]
|===
| 작업 | 구현 


 a| 
AbortMultipartUpload
 a| 
모든 Amazon S3 REST API 동작으로 구현되었습니다.  사전 고지 없이 변경될 수 있습니다.



 a| 
CompleteMultipartUpload
 a| 
보다link:complete-multipart-upload.html["CompleteMultipartUpload"]



 a| 
CreateMultipartUpload

(이전 명칭: 다중 파트 업로드 시작)
 a| 
보다link:initiate-multipart-upload.html["CreateMultipartUpload"]



 a| 
ListMultipartUploads
 a| 
보다link:list-multipart-uploads.html["ListMultipartUploads"]



 a| 
리스트파트
 a| 
모든 Amazon S3 REST API 동작으로 구현되었습니다.  사전 고지 없이 변경될 수 있습니다.



 a| 
업로드파트
 a| 
보다link:upload-part.html["업로드파트"]



 a| 
업로드파트복사
 a| 
보다link:upload-part-copy.html["업로드파트복사"]

|===