---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, RestoreObject, object 
summary: S3 RestoreObject 요청을 사용하면 Cloud Storage 풀에 저장된 객체를 복원할 수 있습니다. 
---
= 복원 개체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 RestoreObject 요청을 사용하면 Cloud Storage 풀에 저장된 객체를 복원할 수 있습니다.



== 지원되는 요청 유형

StorageGRID 객체를 복원하기 위한 RestoreObject 요청만 지원합니다.  지원하지 않습니다 `SELECT` 복원 유형.  선택 요청 반환 `XNotImplemented` .



== 버전 관리

선택적으로 지정하세요 `versionId` 버전이 지정된 버킷에서 특정 버전의 객체를 복원합니다.  지정하지 않으면 `versionId` , 객체의 가장 최신 버전이 복원됩니다.



== Cloud Storage Pool 객체의 RestoreObject 동작

객체가 다음에 저장되어 있는 경우link:../ilm/what-cloud-storage-pool-is.html["클라우드 스토리지 풀"] RestoreObject 요청은 개체 상태에 따라 다음과 같은 동작을 합니다. 보다link:head-object.html["헤드오브젝트"] 자세한 내용은.


NOTE: 객체가 Cloud Storage 풀에 저장되어 있고 해당 객체의 사본이 하나 이상 그리드에 있는 경우 RestoreObject 요청을 실행하여 객체를 복원할 필요가 없습니다.  대신 GetObject 요청을 사용하여 로컬 복사본을 직접 검색할 수 있습니다.

[cols="1a,2a"]
|===
| 객체의 상태 | RestoreObject의 동작 


 a| 
StorageGRID 에 수집되었지만 아직 ILM에서 평가되지 않은 객체 또는 객체가 Cloud Storage 풀에 없습니다.
 a| 
`403 Forbidden` ,  `InvalidObjectState`



 a| 
Cloud Storage Pool에 있는 객체이지만 아직 검색 불가능한 상태로 전환되지 않았습니다.
 a| 
`200 OK`변경 사항이 없습니다.

*참고*: 개체가 검색 불가 상태로 전환되기 전에는 해당 개체를 변경할 수 없습니다. `expiry-date` .



 a| 
객체가 검색 불가능한 상태로 전환되었습니다.
 a| 
`202 Accepted`요청 본문에 지정된 일수 동안 Cloud Storage 풀에 개체의 검색 가능한 사본을 복원합니다.  이 기간이 끝나면 해당 객체는 회수할 수 없는 상태로 돌아갑니다.

선택적으로 다음을 사용하십시오. `Tier` 복원 작업이 완료되는 데 걸리는 시간을 결정하기 위한 요청 요소(`Expedited` , `Standard` , 또는 `Bulk` ).  지정하지 않으면 `Tier` , 그 `Standard` 티어가 사용됩니다.

*중요*: 개체가 S3 Glacier Deep Archive로 전환되었거나 Cloud Storage Pool이 Azure Blob Storage를 사용하는 경우 다음을 사용하여 복원할 수 없습니다. `Expedited` 층.  다음 오류가 반환됩니다. `403 Forbidden` , `InvalidTier` : `Retrieval option is not supported by this storage class` .



 a| 
복구 불가능한 상태에서 복구 중인 객체
 a| 
`409 Conflict` ,  `RestoreAlreadyInProgress`



 a| 
객체가 Cloud Storage Pool에 완전히 복원되었습니다.
 a| 
`200 OK`

*참고:* 개체가 검색 가능한 상태로 복원된 경우 해당 개체를 변경할 수 있습니다. `expiry-date` 새 값으로 RestoreObject 요청을 다시 발행하여 `Days` .  복구 날짜는 요청 시간을 기준으로 업데이트됩니다.

|===