---
permalink: s3/s3-rest-api-supported-operations-and-limitations.html 
sidebar: sidebar 
keywords: s3 rest api supported operations, s3 rest api limitations 
summary: 'StorageGRID 시스템은 대부분의 작업을 지원하고 일부 제한 사항이 있는 Simple Storage Service API(API 버전 2006-03-01)를 구현합니다.  S3 REST API 클라이언트 애플리케이션을 통합할 때 구현 세부 사항을 이해해야 합니다.' 
---
= S3 REST API 구현 세부 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템은 대부분의 작업을 지원하고 일부 제한 사항이 있는 Simple Storage Service API(API 버전 2006-03-01)를 구현합니다.  S3 REST API 클라이언트 애플리케이션을 통합할 때 구현 세부 사항을 이해해야 합니다.

StorageGRID 시스템은 가상 호스팅 스타일 요청과 경로 스타일 요청을 모두 지원합니다.



== 날짜 처리

S3 REST API의 StorageGRID 구현은 유효한 HTTP 날짜 형식만 지원합니다.

StorageGRID 시스템은 날짜 값을 허용하는 모든 헤더에 대해 유효한 HTTP 날짜 형식만 지원합니다.  날짜의 시간 부분은 그리니치 표준시(GMT) 형식으로 지정하거나, 시간대 오프셋 없이 UTC(세계 협정시) 형식으로 지정할 수 있습니다(+0000을 지정해야 함).  만약 당신이 포함하면 `x-amz-date` 요청 헤더에 Date를 추가하면 Date 요청 헤더에 지정된 모든 값이 재정의됩니다.  AWS Signature Version 4를 사용하는 경우 `x-amz-date` 날짜 헤더는 지원되지 않으므로 서명된 요청에 헤더가 있어야 합니다.



== 일반적인 요청 헤더

StorageGRID 시스템은 다음에 의해 정의된 공통 요청 헤더를 지원합니다. https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html["Amazon Simple Storage Service API 참조: 일반 요청 헤더"^] 단, 한 가지 예외가 있습니다.

[cols="1a,2a"]
|===
| 요청 헤더 | 구현 


 a| 
권한 부여
 a| 
AWS Signature Version 2에 대한 전체 지원

다음 예외를 제외하고 AWS Signature 버전 4에 대한 지원:

* 실제 페이로드 체크섬 값을 제공하는 경우 `x-amz-content-sha256` , 값은 검증 없이 허용됩니다. `UNSIGNED-PAYLOAD` 헤더에 제공되었습니다.  당신이 제공할 때 `x-amz-content-sha256` 의미하는 헤더 값 `aws-chunked` 스트리밍(예: STREAMING-AWS4-HMAC-SHA256-PAYLOAD)의 경우 청크 서명은 청크 데이터에 대해 검증되지 않습니다.




 a| 
x-amz-보안-토큰
 a| 
구현되지 않음.  보고 `XNotImplemented` .

|===


== 일반적인 응답 헤더

StorageGRID 시스템은 _Simple Storage Service API Reference_에서 정의한 모든 일반 응답 헤더를 지원하지만, 한 가지 예외가 있습니다.

[cols="1a,2a"]
|===
| 응답 헤더 | 구현 


 a| 
x-amz-id-2
 a| 
사용하지 않음

|===