---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: UploadPart 작업은 객체의 다중 파트 업로드에서 파트를 업로드합니다. 
---
= 업로드파트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UploadPart 작업은 객체의 다중 파트 업로드에서 파트를 업로드합니다.



== 지원되는 요청 헤더

다음 요청 헤더가 지원됩니다.

* `x-amz-checksum-sha256`
* `Content-Length`
* `Content-MD5`




== 서버 측 암호화를 위한 요청 헤더

CreateMultipartUpload 요청에 대해 SSE-C 암호화를 지정한 경우 각 UploadPart 요청에 다음 요청 헤더도 포함해야 합니다.

* `x-amz-server-side-encryption-customer-algorithm`: 지정 `AES256` .
* `x-amz-server-side-encryption-customer-key`: CreateMultipartUpload 요청에서 제공한 것과 동일한 암호화 키를 지정하세요.
* `x-amz-server-side-encryption-customer-key-MD5`: CreateMultipartUpload 요청에서 제공한 것과 동일한 MD5 다이제스트를 지정합니다.



CAUTION: 귀하가 제공한 암호화 키는 결코 저장되지 않습니다.  암호화 키를 잃어버리면 해당 객체도 잃어버리게 됩니다.  고객이 제공한 키를 사용하여 개체 데이터를 보호하기 전에 다음 고려 사항을 검토하십시오.link:using-server-side-encryption.html["서버 측 암호화를 사용하세요"] .

CreateMultipartUpload 요청 중에 SHA-256 체크섬을 지정한 경우 각 UploadPart 요청에 다음 요청 헤더도 포함해야 합니다.

* `x-amz-checksum-sha256`: 이 부분에 대한 SHA-256 체크섬을 지정합니다.




== 지원되지 않는 요청 헤더

다음 요청 헤더는 지원되지 않습니다.

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`




== 버전 관리

다중 파트 업로드는 업로드 시작, 업로드 목록 작성, 파트 업로드, 업로드된 파트 조립, 업로드 완료를 위한 별도의 작업으로 구성됩니다.  CompleteMultipartUpload 작업이 수행되면 개체가 생성되고(해당되는 경우 버전 관리도 수행됨)
