---
permalink: s3/upload-part-copy.html 
sidebar: sidebar 
keywords: UploadPart, UploadPartCopy, multipart uploads, uploads, 
summary: UploadPartCopy 작업은 기존 개체의 데이터를 데이터 소스로 복사하여 개체의 일부를 업로드합니다. 
---
= 업로드파트복사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
UploadPartCopy 작업은 기존 개체의 데이터를 데이터 소스로 복사하여 개체의 일부를 업로드합니다.

UploadPartCopy 작업은 모든 Amazon S3 REST API 동작으로 구현됩니다.  사전 고지 없이 변경될 수 있습니다.

이 요청은 지정된 객체 데이터를 읽고 씁니다. `x-amz-copy-source-range` StorageGRID 시스템 내에서.

다음 요청 헤더가 지원됩니다.

* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-copy-source-if-modified-since`




== 서버 측 암호화를 위한 요청 헤더

CreateMultipartUpload 요청에 대해 SSE-C 암호화를 지정한 경우 각 UploadPartCopy 요청에 다음 요청 헤더도 포함해야 합니다.

* `x-amz-server-side-encryption-customer-algorithm`: 지정 `AES256` .
* `x-amz-server-side-encryption-customer-key`: CreateMultipartUpload 요청에서 제공한 것과 동일한 암호화 키를 지정하세요.
* `x-amz-server-side-encryption-customer-key-MD5`: CreateMultipartUpload 요청에서 제공한 것과 동일한 MD5 다이제스트를 지정합니다.


소스 개체가 고객이 제공한 키(SSE-C)를 사용하여 암호화된 경우, 다음 세 개의 헤더를 UploadPartCopy 요청에 포함해야 합니다. 이렇게 하면 개체를 복호화한 다음 복사할 수 있습니다.

* `x-amz-copy-source​-server-side​-encryption​-customer-algorithm`: 지정 `AES256` .
* `x-amz-copy-source​-server-side-encryption-customer-key`: 소스 객체를 생성할 때 제공한 암호화 키를 지정합니다.
* `x-amz-copy-source​-server-side-encryption-customer-key-MD5`: 소스 객체를 생성할 때 제공한 MD5 다이제스트를 지정합니다.



CAUTION: 귀하가 제공한 암호화 키는 결코 저장되지 않습니다.  암호화 키를 잃어버리면 해당 객체도 잃어버리게 됩니다.  고객이 제공한 키를 사용하여 개체 데이터를 보호하기 전에 다음 고려 사항을 검토하십시오.link:using-server-side-encryption.html["서버 측 암호화를 사용하세요"] .



== 버전 관리

다중 파트 업로드는 업로드 시작, 업로드 목록 작성, 파트 업로드, 업로드된 파트 조립, 업로드 완료를 위한 별도의 작업으로 구성됩니다.  CompleteMultipartUpload 작업이 수행되면 개체가 생성되고(해당되는 경우 버전 관리도 수행됨)
