---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: MIB 파일에는 그리드의 노드에 대한 관리되는 리소스와 서비스 속성에 대한 정의와 정보가 포함되어 있습니다.  StorageGRID 에 대한 개체와 알림을 정의하는 MIB 파일에 액세스할 수 있습니다.  이러한 파일은 그리드를 모니터링하는 데 유용할 수 있습니다. 
---
= MIB 파일 접근
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MIB 파일에는 그리드의 노드에 대한 관리되는 리소스와 서비스 속성에 대한 정의와 정보가 포함되어 있습니다.  StorageGRID 에 대한 개체와 알림을 정의하는 MIB 파일에 액세스할 수 있습니다.  이러한 파일은 그리드를 모니터링하는 데 유용할 수 있습니다.

보다link:using-snmp-monitoring.html["SNMP 모니터링 사용"] SNMP 및 MIB 파일에 대한 자세한 내용은 다음을 참조하세요.



== MIB 파일 접근

MIB 파일에 액세스하려면 다음 단계를 따르세요.

.단계
. *구성* > *모니터링* > *SNMP 에이전트*를 선택합니다.
. SNMP 에이전트 페이지에서 다운로드할 파일을 선택하세요.
+
** *NETAPP-STORAGEGRID-MIB.txt*: 모든 관리 노드에서 액세스할 수 있는 경고 테이블과 알림(트랩)을 정의합니다.
** *ES-NETAPP-06-MIB.mib*: E-Series 기반 어플라이언스에 대한 개체와 알림을 정의합니다.
** *MIB_1_10.zip*: BMC 인터페이스가 있는 기기에 대한 개체와 알림을 정의합니다.
+
[]
====

TIP: 다음 위치에서 모든 StorageGRID 노드의 MIB 파일에 액세스할 수도 있습니다. `/usr/share/snmp/mibs`

====


. MIB 파일에서 StorageGRID OID를 추출하려면:
+
.. StorageGRID MIB 루트의 OID를 가져옵니다.
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
결과: `.1.3.6.1.4.1.789.28669` (`28669` 는 항상 StorageGRID 의 OID입니다.)

.. 전체 트리에서 StorageGRID OID에 대한 Grep(사용) `paste` 줄을 연결하다):
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`






TIP: 그만큼 `snmptranslate` 이 명령에는 MIB를 탐색하는 데 유용한 여러 옵션이 있습니다.  이 명령은 모든 StorageGRID 노드에서 사용할 수 있습니다.



== MIB 파일 내용

모든 객체는 StorageGRID OID에 있습니다.

[cols="1a,1a,2a"]
|===
| 객체 이름 | 객체 ID(OID) | 설명 


| .iso.org.dod.인터넷.  + 민간기업.  + 넷앱.스토리지그리드 | .1.3.6.1.4.1.789.28669  a| 
NetApp StorageGRID 엔터티를 위한 MIB 모듈입니다.

|===


== MIB 객체

[cols="1a,1a,2a"]
|===
| 객체 이름 | 객체 ID(OID) | 설명 


| 활성 알림 개수 | .1.3.6.1.4.1. + 789.28669.1.3  a| 
activeAlertTable에 있는 활성 알림의 수입니다.



| 활성 알림 테이블 | .1.3.6.1.4.1. + 789.28669.1.4  a| 
StorageGRID 의 활성 알림 표입니다.



| 활성 알림 ID | .1.3.6.1.4.1. + 789.28669.1.4.1.1  a| 
알림의 ID입니다.  현재 활성 알림 세트에서만 고유합니다.



| 활성 알림 이름 | .1.3.6.1.4.1. + 789.28669.1.4.1.2  a| 
알림의 이름입니다.



| 활성 알림 인스턴스 | .1.3.6.1.4.1. + 789.28669.1.4.1.3  a| 
알림을 생성한 엔터티의 이름이며 일반적으로 노드 이름입니다.



| 활성 경고 심각도 | .1.3.6.1.4.1. + 789.28669.1.4.1.4  a| 
경고의 심각도.



| 활성 알림 시작 시간 | .1.3.6.1.4.1. + 789.28669.1.4.1.5  a| 
경고가 발생한 날짜와 시간입니다.

|===


== 알림 유형(트랩)

모든 알림에는 다음 변수가 varbind로 포함됩니다.

* 활성 알림 ID
* 활성 알림 이름
* 활성 알림 인스턴스
* 활성 경고 심각도
* 활성 알림 시작 시간


[cols="1a,1a,2a"]
|===
| 알림 유형 | 객체 ID(OID) | 설명 


| 활성사소경고 | .1.3.6.1.4.1. + 789.28669.0.6  a| 
심각도가 낮은 경고



| 활성 주요 알림 | .1.3.6.1.4.1. + 789.28669.0.7  a| 
심각한 경고



| 활성중요경고 | .1.3.6.1.4.1. + 789.28669.0.8  a| 
심각한 심각성을 지닌 경고

|===