---
permalink: monitor/configuring-snmp-agent.html 
sidebar: sidebar 
keywords: snmp agent, mib, trap, inform 
summary: StorageGRID SNMP 에이전트를 구성하여 읽기 전용 MIB 액세스 및 알림을 위해 타사 SNMP 관리 시스템을 사용할 수 있습니다. 
---
= SNMP 에이전트 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID SNMP 에이전트를 구성하여 읽기 전용 MIB 액세스 및 알림을 위해 타사 SNMP 관리 시스템을 사용할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["루트 액세스 권한"] .


.이 작업에 관하여
StorageGRID SNMP 에이전트는 SNMPv1, SNMPv2c, SNMPv3를 지원합니다.  하나 이상의 버전에 대해 에이전트를 구성할 수 있습니다.  SNMPv3의 경우 USM(사용자 보안 모델) 인증만 지원됩니다.

그리드의 모든 노드는 동일한 SNMP 구성을 사용합니다.



== 기본 구성 지정

첫 번째 단계로 StorageGRID SMNP 에이전트를 활성화하고 기본 정보를 제공합니다.

.단계
. *구성* > *모니터링* > *SNMP 에이전트*를 선택합니다.
+
SNMP 에이전트 페이지가 나타납니다.

. 모든 그리드 노드에서 SNMP 에이전트를 활성화하려면 *SNMP 활성화* 확인란을 선택합니다.
. 기본 구성 섹션에 다음 정보를 입력하세요.
+
[cols="1a,2a"]
|===
| 필드 | 설명 


 a| 
시스템 연락처
 a| 
선택 과목.  SNMP 메시지에서 sysContact로 반환되는 StorageGRID 시스템의 기본 연락처입니다.

시스템 연락처는 일반적으로 이메일 주소입니다.  이 값은 StorageGRID 시스템의 모든 노드에 적용됩니다.  *시스템 연락처*는 최대 255자까지 입력 가능합니다.



 a| 
시스템 위치
 a| 
선택 과목.  SNMP 메시지에서 sysLocation으로 반환되는 StorageGRID 시스템의 위치입니다.

시스템 위치는 StorageGRID 시스템의 위치를 ​​식별하는 데 유용한 정보입니다.  예를 들어, 시설의 주소를 사용할 수 있습니다.  이 값은 StorageGRID 시스템의 모든 노드에 적용됩니다.  *시스템 위치*는 최대 255자까지 입력 가능합니다.



 a| 
SNMP 에이전트 알림 활성화
 a| 
** 선택하면 StorageGRID SNMP 에이전트가 트랩 및 알림 알림을 보냅니다.
** 선택하지 않으면 SNMP 에이전트는 읽기 전용 MIB 액세스를 지원하지만 SNMP 알림을 보내지 않습니다.




 a| 
인증 트랩 활성화
 a| 
이 옵션을 선택하면 StorageGRID SNMP 에이전트가 부적절하게 인증된 프로토콜 메시지를 수신하면 인증 트랩을 보냅니다.

|===




== 커뮤니티 문자열을 입력하세요

SNMPv1 또는 SNMPv2c를 사용하는 경우 커뮤니티 문자열 섹션을 작성하세요.

관리 시스템이 StorageGRID MIB를 쿼리하면 커뮤니티 문자열을 보냅니다.  커뮤니티 문자열이 여기에 지정된 값 중 하나와 일치하면 SNMP 에이전트는 관리 시스템에 응답을 보냅니다.

.단계
. *읽기 전용 커뮤니티*의 경우, IPv4 및 IPv6 에이전트 주소에서 읽기 전용 MIB 액세스를 허용하는 커뮤니티 문자열을 선택적으로 입력합니다.
+

TIP: StorageGRID 시스템의 보안을 보장하려면 커뮤니티 문자열로 "public"을 사용하지 마세요.  이 필드를 비워 두면 SNMP 에이전트는 StorageGRID 시스템의 그리드 ID를 커뮤니티 문자열로 사용합니다.

+
각 커뮤니티 문자열은 최대 32자까지 가능하며 공백 문자를 포함할 수 없습니다.

. 추가 문자열을 추가하려면 *다른 커뮤니티 문자열 추가*를 선택하세요.
+
최대 5개의 문자열이 허용됩니다.





== [[select_trap_destination]]트랩 대상 생성

StorageGRID 트랩 또는 알림에 대한 하나 이상의 대상을 정의하려면 다른 구성 섹션의 트랩 대상 탭을 사용합니다.  SNMP 에이전트를 활성화하고 *저장*을 선택하면 StorageGRID 경고가 발생할 때 정의된 각 대상에 알림을 보냅니다.  지원되는 MIB-II 엔터티(예: ifDown 및 coldStart)에 대해서도 표준 알림이 전송됩니다.

.단계
. *기본 트랩 커뮤니티* 필드에는 SNMPv1 또는 SNMPv2 트랩 대상에 사용할 기본 커뮤니티 문자열을 입력할 수도 있습니다.
+
필요에 따라 특정 트랩 대상을 정의할 때 다른("사용자 지정") 커뮤니티 문자열을 제공할 수 있습니다.

+
*기본 트랩 커뮤니티*는 최대 32자까지 가능하며 공백 문자를 포함할 수 없습니다.

. 트랩 대상을 추가하려면 *만들기*를 선택하세요.
. 이 트랩 대상에 사용될 SNMP 버전을 선택하세요.
. 선택한 버전에 대한 트랩 대상 생성 양식을 작성하세요.
+
[role="tabbed-block"]
====
.SNMPv1
--
버전으로 SNMPv1을 선택한 경우 이 필드를 작성하세요.

[cols="1a,2a"]
|===
| 필드 | 설명 


 a| 
유형
 a| 
SNMPv1에 대한 트랩이어야 합니다.



 a| 
주인
 a| 
트랩을 수신하려면 IPv4 또는 IPv6 주소나 정규화된 도메인 이름(FQDN)이 필요합니다.



 a| 
포트
 a| 
다른 값을 사용해야 하는 경우가 아니면 SNMP 트랩의 표준 포트인 162를 사용하세요.



 a| 
규약
 a| 
TCP를 사용해야 하는 경우가 아니면 표준 SNMP 트랩 프로토콜인 UDP를 사용하세요.



 a| 
커뮤니티 스트링
 a| 
기본 트랩 커뮤니티가 지정되어 있으면 이를 사용하거나, 이 트랩 대상에 대한 사용자 지정 커뮤니티 문자열을 입력합니다.

사용자 지정 커뮤니티 문자열은 최대 32자까지 가능하며 공백을 포함할 수 없습니다.

|===
--
.SNMPv2c
--
SNMPv2c를 버전으로 선택한 경우 이 필드를 작성하세요.

[cols="1a,2a"]
|===
| 필드 | 설명 


 a| 
유형
 a| 
목적지가 함정이나 정보 제공에 사용될지 여부.



 a| 
주인
 a| 
트랩을 수신할 IPv4 또는 IPv6 주소 또는 FQDN입니다.



 a| 
포트
 a| 
다른 값을 사용해야 하는 경우가 아니면 SNMP 트랩의 표준 포트인 162를 사용하세요.



 a| 
규약
 a| 
TCP를 사용해야 하는 경우가 아니면 표준 SNMP 트랩 프로토콜인 UDP를 사용하세요.



 a| 
커뮤니티 스트링
 a| 
기본 트랩 커뮤니티가 지정되어 있으면 이를 사용하거나, 이 트랩 대상에 대한 사용자 지정 커뮤니티 문자열을 입력합니다.

사용자 지정 커뮤니티 문자열은 최대 32자까지 가능하며 공백을 포함할 수 없습니다.

|===
--
.SNMPv3
--
버전으로 SNMPv3을 선택한 경우 이 필드를 작성하세요.

[cols="1a,2a"]
|===
| 필드 | 설명 


 a| 
유형
 a| 
목적지가 함정이나 정보 제공에 사용될지 여부.



 a| 
주인
 a| 
트랩을 수신할 IPv4 또는 IPv6 주소 또는 FQDN입니다.



 a| 
포트
 a| 
다른 값을 사용해야 하는 경우가 아니면 SNMP 트랩의 표준 포트인 162를 사용하세요.



 a| 
규약
 a| 
TCP를 사용해야 하는 경우가 아니면 표준 SNMP 트랩 프로토콜인 UDP를 사용하세요.



 a| 
USM 사용자
 a| 
인증에 사용될 USM 사용자입니다.

** *트랩*을 선택한 경우 권한 있는 엔진 ID가 없는 USM 사용자만 표시됩니다.
** *알림*을 선택한 경우 권한 있는 엔진 ID가 있는 USM 사용자만 표시됩니다.
** 사용자가 표시되지 않는 경우:
+
... 트랩 목적지를 만들고 저장합니다.
... 로 가다<<create-usm-users,USM 사용자 생성>> 사용자를 생성합니다.
... 트랩 대상 탭으로 돌아가서 표에서 저장된 대상을 선택하고 *편집*을 선택합니다.
... 사용자를 선택하세요.




|===
--
====
. *만들기*를 선택하세요.
+
트랩 대상이 생성되어 테이블에 추가됩니다.





== 에이전트 주소 생성

선택적으로, 다른 구성 섹션의 에이전트 주소 탭을 사용하여 하나 이상의 "수신 주소"를 지정합니다.  이는 SNMP 에이전트가 쿼리를 수신할 수 있는 StorageGRID 주소입니다.

에이전트 주소를 구성하지 않으면 모든 StorageGRID 네트워크에서 기본 수신 주소는 UDP 포트 161입니다.

.단계
. *만들기*를 선택하세요.
. 다음 정보를 입력하세요.
+
[cols="1a,2a"]
|===
| 필드 | 설명 


 a| 
인터넷 프로토콜
 a| 
이 주소가 IPv4를 사용할지, IPv6를 사용할지 여부입니다.

기본적으로 SNMP는 IPv4를 사용합니다.



 a| 
전송 프로토콜
 a| 
이 주소가 UDP를 사용할지, TCP를 사용할지 여부입니다.

기본적으로 SNMP는 UDP를 사용합니다.



 a| 
StorageGRID 네트워크
 a| 
에이전트가 수신할 StorageGRID 네트워크입니다.

** 그리드, 관리자 및 클라이언트 네트워크: SNMP 에이전트는 세 네트워크 모두에서 쿼리를 수신합니다.
** 그리드 네트워크
** 관리자 네트워크
** 클라이언트 네트워크
+
*참고*: 보안되지 않은 데이터에 클라이언트 네트워크를 사용하고 클라이언트 네트워크에 대한 에이전트 주소를 생성하는 경우 SNMP 트래픽도 보안되지 않을 수 있음을 유의하세요.





 a| 
포트
 a| 
선택적으로 SNMP 에이전트가 수신해야 하는 포트 번호입니다.

SNMP 에이전트의 기본 UDP 포트는 161이지만, 사용하지 않는 포트 번호는 입력할 수 있습니다.

*참고*: SNMP 에이전트를 저장하면 StorageGRID 자동으로 내부 방화벽의 에이전트 주소 포트를 엽니다.  모든 외부 방화벽이 이러한 포트에 대한 액세스를 허용하는지 확인해야 합니다.

|===
. *만들기*를 선택하세요.
+
에이전트 주소가 생성되어 테이블에 추가됩니다.





== [[create-usm-users]]USM 사용자 생성

SNMPv3를 사용하는 경우 기타 구성 섹션의 USM 사용자 탭을 사용하여 MIB를 쿼리하거나 트랩 및 알림을 수신할 권한이 있는 USM 사용자를 정의합니다.


NOTE: SNMPv3 _inform_ 대상에는 엔진 ID가 있는 사용자가 있어야 합니다.  SNMPv3 _trap_ 대상에는 엔진 ID가 있는 사용자가 있을 수 없습니다.

SNMPv1 또는 SNMPv2c만 사용하는 경우에는 이 단계가 적용되지 않습니다.

.단계
. *만들기*를 선택하세요.
. 다음 정보를 입력하세요.
+
[cols="1a,2a"]
|===
| 필드 | 설명 


 a| 
사용자 이름
 a| 
이 USM 사용자를 위한 고유한 이름입니다.

사용자 이름은 최대 32자까지 가능하며 공백 문자를 포함할 수 없습니다.  사용자가 생성된 후에는 사용자 이름을 변경할 수 없습니다.



 a| 
읽기 전용 MIB 액세스
 a| 
이 옵션을 선택하면 이 사용자는 MIB에 대한 읽기 전용 액세스 권한을 갖게 됩니다.



 a| 
권한 있는 엔진 ID
 a| 
이 사용자가 알림 대상에서 사용될 경우, 이 사용자에 대한 권한 있는 엔진 ID입니다.

공백 없이 10~64개의 16진수 문자(5~32바이트)를 입력하세요.  이 값은 알림의 트랩 대상에서 선택될 USM 사용자에게 필요합니다.  이 값은 트랩의 트랩 대상에서 선택될 USM 사용자에게는 허용되지 않습니다.

*참고*: *읽기 전용 MIB 액세스*를 선택한 경우 이 필드는 표시되지 않습니다. 읽기 전용 MIB 액세스 권한이 있는 USM 사용자는 엔진 ID를 가질 수 없기 때문입니다.



 a| 
보안 수준
 a| 
USM 사용자의 보안 수준:

** *authPriv*: 이 사용자는 인증 및 개인 정보 보호(암호화)를 통해 통신합니다.  인증 프로토콜과 비밀번호, 개인정보 보호 프로토콜과 비밀번호를 지정해야 합니다.
** *authNoPriv*: 이 사용자는 인증을 통해 통신하며 개인 정보 보호(암호화 없음)는 필요하지 않습니다.  인증 프로토콜과 비밀번호를 지정해야 합니다.




 a| 
인증 프로토콜
 a| 
항상 지원되는 유일한 프로토콜인 SHA로 설정합니다(HMAC-SHA-96).



 a| 
비밀번호
 a| 
이 사용자가 인증에 사용할 비밀번호입니다.



 a| 
개인정보 보호 프로토콜
 a| 
*authPriv*를 선택하고 항상 AES로 설정한 경우에만 표시됩니다. AES는 지원되는 유일한 개인정보 보호 프로토콜입니다.



 a| 
비밀번호
 a| 
*authPriv*를 선택한 경우에만 표시됩니다.  이 사용자가 개인정보 보호를 위해 사용할 비밀번호입니다.

|===
. *만들기*를 선택하세요.
+
USM 사용자가 생성되어 테이블에 추가됩니다.

. SNMP 에이전트 구성을 완료하면 *저장*을 선택합니다.
+
새로운 SNMP 에이전트 구성이 활성화됩니다.


