---
permalink: monitor/logs-files-reference.html 
sidebar: sidebar 
keywords: log, logs, log files 
summary: StorageGRID 이벤트, 진단 메시지, 오류 조건을 캡처하는 데 사용되는 로그를 제공합니다.  문제 해결을 위해 로그 파일을 수집하여 기술 지원팀에 전달하라는 요청을 받을 수도 있습니다. 
---
= 로그 파일 참조
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 이벤트, 진단 메시지, 오류 조건을 캡처하는 데 사용되는 로그를 제공합니다.  문제 해결을 위해 로그 파일을 수집하여 기술 지원팀에 전달하라는 요청을 받을 수도 있습니다.

로그는 다음과 같이 분류됩니다.

* link:storagegrid-software-logs.html["StorageGRID 소프트웨어 로그"]
* link:deployment-and-maintenance-logs.html["배포 및 유지 관리 로그"]
* link:about-bycast-log.html["bycast.log에 대하여"]



NOTE: 각 통나무 유형에 대해 제공된 세부 정보는 참조용일 뿐입니다.  이 로그는 기술 지원팀의 고급 문제 해결을 위해 사용됩니다.  감사 로그와 애플리케이션 로그 파일을 사용하여 문제 기록을 재구성하는 고급 기술은 이 지침의 범위를 벗어납니다.



== 로그에 접근하세요

로그에 액세스하려면 다음을 수행할 수 있습니다.link:collecting-log-files-and-system-data.html["로그 파일 및 시스템 데이터 수집"] 하나 이상의 노드에서 단일 로그 파일 아카이브로 저장합니다. 또는 기본 관리 노드를 사용할 수 없거나 특정 노드에 연결할 수 없는 경우 다음과 같이 각 그리드 노드의 개별 로그 파일에 액세스할 수 있습니다.

. 다음 명령을 입력하세요: `ssh admin@grid_node_IP`
. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
. 다음 명령을 입력하여 루트로 전환하세요. `su -`
. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.




== Syslog 서버로 로그 내보내기

로그를 syslog 서버로 내보내면 다음과 같은 기능이 제공됩니다.

* S3 및 Swift 요청 외에도 모든 Grid Manager 및 Tenant Manager 요청 목록을 받습니다.
* 감사 로깅 방법으로 인해 발생하는 성능 영향 없이 오류를 반환하는 S3 요청에 대한 가시성이 향상되었습니다.
* 분석하기 쉬운 HTTP 계층 요청 및 오류 코드에 액세스합니다.
* 로드 밸런서에서 트래픽 분류기에 의해 차단된 요청에 대한 가시성이 향상되었습니다.


로그를 내보내려면 다음을 참조하세요.link:../monitor/configure-audit-messages.html["감사 메시지 및 로그 대상 구성"] .



== 로그 파일 범주

StorageGRID 로그 파일 보관소에는 각 범주에 대해 설명된 로그와 메트릭 및 디버그 명령 출력이 포함된 추가 파일이 들어 있습니다.

[cols="1a,3a"]
|===
| 보관 위치 | 설명 


| 심사  a| 
정상적인 시스템 작동 중에 생성된 감사 메시지입니다.



| 베이스-오스-로그  a| 
StorageGRID 이미지 버전을 포함한 기본 운영 체제 정보입니다.



| 묶음  a| 
글로벌 구성 정보(번들).



| 카산드라  a| 
Cassandra 데이터베이스 정보 및 Reaper 복구 로그.



| ec  a| 
현재 노드에 대한 VCS 정보와 프로필 ID별 EC 그룹 정보입니다.



| 그리드  a| 
디버그를 포함한 일반 그리드 로그(`bycast.log` ) 그리고 `servermanager` 로그.



| 그리드.json  a| 
모든 노드에서 공유되는 그리드 구성 파일입니다.  또한, `node.json` 현재 노드에만 적용됩니다.



| 하그룹  a| 
고가용성 그룹 메트릭 및 로그.



| 설치하다  a| 
`Gdu-server`그리고 로그를 설치합니다.



| 람다 중재자  a| 
S3 Select 프록시 요청과 관련된 로그입니다.



| 벌목꾼.로그  a| 
로그 수집과 관련된 디버그 메시지입니다.



| 메트릭  a| 
Grafana, Jaeger, 노드 내보내기 및 Prometheus에 대한 서비스 로그입니다.



| 기타  a| 
다양한 접근 및 오류 로그.



| MySQL  a| 
mariaDB 데이터베이스 구성 및 관련 로그.



| 그물  a| 
네트워킹 관련 스크립트와 Dynip 서비스에서 생성된 로그입니다.



| nginx  a| 
로드 밸런서 및 그리드 페더레이션 구성 파일과 로그.  또한 Grid Manager와 Tenant Manager 트래픽 로그도 포함됩니다.



| nginx-gw  a| 
* `access.log`: 그리드 관리자와 테넌트 관리자 요청 로그 메시지입니다.
+
** 이 메시지에는 다음이 접두사로 붙습니다. `mgmt:` syslog를 사용하여 내보낼 때.
** 이러한 로그 메시지의 형식은 다음과 같습니다. `[$time_iso8601] $remote_addr $status $bytes_sent $request_length $request_time "$endpointId" "$request" "$http_host" "$http_user_agent" "$http_referer"`


* `cgr-access.log.gz`: 인바운드 크로스 그리드 복제 요청.
+
** 이 메시지에는 다음이 접두사로 붙습니다. `cgr:` syslog를 사용하여 내보낼 때.
** 이러한 로그 메시지의 형식은 다음과 같습니다. `[$time_iso8601] $remote_addr $status $bytes_sent $request_length $request_time "$endpointId" "$upstream_addr" "$request" "$http_host"`


* `endpoint-access.log.gz`: 로드 밸런서 엔드포인트에 대한 S3 및 Swift 요청.
+
** 이 메시지에는 다음이 접두사로 붙습니다. `endpoint:` syslog를 사용하여 내보낼 때.
** 이러한 로그 메시지의 형식은 다음과 같습니다. `[$time_iso8601] $remote_addr $status $bytes_sent $request_length $request_time "$endpointId" "$upstream_addr" "$request" "$http_host"`


* `nginx-gw-dns-check.log`: 새로운 DNS 검사 알림과 관련이 있습니다.




| 엔티피  a| 
NTP 구성 파일 및 로그.



 a| 
고아 객체
 a| 
고아 객체와 관련된 로그입니다.



| 운영 체제  a| 
서비스를 포함한 노드 및 그리드 상태 파일 `pid` .



| 다른  a| 
로그 파일 `/var/local/log` 다른 폴더에 수집되지 않은 항목입니다.



| 퍼프  a| 
CPU, 네트워킹, 디스크 I/O에 대한 성능 정보입니다.



| 프로메테우스-데이터  a| 
로그 수집에 Prometheus 데이터가 포함된 경우 현재 Prometheus 메트릭입니다.



| 프로비저닝  a| 
그리드 프로비저닝 프로세스와 관련된 로그입니다.



| 뗏목  a| 
플랫폼 서비스에서 사용되는 Raft 클러스터의 로그입니다.



| ssh  a| 
SSH 구성 및 서비스와 관련된 로그입니다.



| SNMP  a| 
SNMP 알림을 보내는 데 사용되는 SNMP 에이전트 구성입니다.



| 소켓-데이터  a| 
네트워크 디버그를 위한 소켓 데이터입니다.



| 시스템 명령.txt  a| 
StorageGRID 컨테이너 명령의 출력.  네트워킹 및 디스크 사용량과 같은 시스템 정보가 포함되어 있습니다.



| 동기화-복구-패키지  a| 
ADC 서비스를 호스팅하는 모든 관리 노드와 스토리지 노드에서 최신 복구 패키지의 일관성을 유지하는 것과 관련이 있습니다.

|===