---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: StorageGRID 에 대한 클라이언트 연결을 관리하기 위해 로드 밸런서를 사용하는 경우 시스템을 처음 구성한 후와 구성을 변경하거나 확장을 수행한 후에는 로드 밸런싱 작업을 모니터링해야 합니다. 
---
= 부하 분산 작업 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 에 대한 클라이언트 연결을 관리하기 위해 로드 밸런서를 사용하는 경우 시스템을 처음 구성한 후와 구성을 변경하거나 확장을 수행한 후에는 로드 밸런싱 작업을 모니터링해야 합니다.

.이 작업에 관하여
관리 노드나 게이트웨이 노드에서 로드 밸런서 서비스를 사용하거나 외부 타사 로드 밸런서를 사용하여 클라이언트 요청을 여러 스토리지 노드에 분산할 수 있습니다.

부하 분산을 구성한 후에는 개체 수집 및 검색 작업이 스토리지 노드 전체에 균등하게 분산되는지 확인해야 합니다.  요청이 균등하게 분산되면 StorageGRID 부하가 걸리는 상황에서도 클라이언트 요청에 응답성을 유지하고 클라이언트 성능을 유지하는 데 도움이 됩니다.

게이트웨이 노드 또는 관리 노드의 고가용성(HA) 그룹을 활성 백업 모드로 구성한 경우 그룹 내 노드 하나만 클라이언트 요청을 적극적으로 분산합니다.

자세한 내용은 다음을 참조하세요. link:../admin/configuring-client-connections.html["S3 클라이언트 연결 구성"] .

.단계
. S3 클라이언트가 로드 밸런서 서비스를 사용하여 연결하는 경우 관리 노드 또는 게이트웨이 노드가 예상대로 트래픽을 적극적으로 분산하는지 확인하세요.
+
.. *노드*를 선택하세요.
.. 게이트웨이 노드 또는 관리 노드를 선택하세요.
.. *개요* 탭에서 노드 인터페이스가 HA 그룹에 있는지, 노드 인터페이스에 기본 역할이 있는지 확인합니다.
+
기본 역할을 하는 노드와 HA 그룹에 속하지 않은 노드는 클라이언트에 요청을 적극적으로 분산해야 합니다.

.. 클라이언트 요청을 적극적으로 분배해야 하는 각 노드에 대해 다음을 선택하십시오.link:viewing-load-balancer-tab.html["로드 밸런서 탭"] .
.. 지난주 로드 밸런서 요청 트래픽 차트를 검토하여 노드가 적극적으로 요청을 분산했는지 확인하세요.
+
활성 백업 HA 그룹의 노드는 수시로 백업 역할을 수행할 수 있습니다.  그 시간 동안 노드는 클라이언트 요청을 분산하지 않습니다.

.. 지난주 로드 밸런서 수신 요청률 차트를 검토하여 노드의 개체 처리량을 검토합니다.
.. StorageGRID 시스템의 각 관리 노드 또는 게이트웨이 노드에 대해 이 단계를 반복합니다.
.. 선택적으로 트래픽 분류 정책을 사용하여 로드 밸런서 서비스에서 제공되는 트래픽에 대한 보다 자세한 분석을 볼 수 있습니다.


. 이러한 요청이 스토리지 노드에 균등하게 분산되는지 확인하세요.
+
.. *_저장 노드_* > *LDR* > *HTTP*를 선택합니다.
.. *현재 설정된 수신 세션*의 수를 검토하세요.
.. 그리드의 각 저장 노드에 대해 반복합니다.
+
세션 수는 모든 스토리지 노드에서 거의 동일해야 합니다.




