---
permalink: monitor/monitoring-information-lifecycle-management.html 
sidebar: sidebar 
keywords: lifecycle management, lifecycle, monitoring, ILM, information lifecycle management 
summary: '정보 수명 주기 관리(ILM) 시스템은 그리드에 저장된 모든 객체에 대한 데이터 관리를 제공합니다.  그리드가 현재 부하를 처리할 수 있는지, 아니면 더 많은 리소스가 필요한지 파악하려면 ILM 작업을 모니터링해야 합니다.' 
---
= 정보 수명 주기 관리 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
정보 수명주기 관리(ILM) 시스템은 그리드에 저장된 모든 객체에 대한 데이터 관리를 제공합니다.  그리드가 현재 부하를 처리할 수 있는지, 아니면 더 많은 리소스가 필요한지 파악하려면 ILM 작업을 모니터링해야 합니다.

.이 작업에 관하여
StorageGRID 시스템은 활성 ILM 정책을 적용하여 객체를 관리합니다.  ILM 정책과 관련 ILM 규칙은 만들어지는 사본의 수, 생성되는 사본의 유형, 사본을 배치하는 위치, 각 사본을 보관하는 기간을 결정합니다.

객체 수집 및 기타 객체 관련 활동은 StorageGRID ILM을 평가할 수 있는 속도를 초과할 수 있으며, 이로 인해 시스템은 ILM 배치 지침을 거의 실시간으로 이행할 수 없는 객체를 대기열에 추가할 수 있습니다.  StorageGRID 클라이언트 작업을 따라가고 있는지 모니터링해야 합니다.



== Grid Manager 대시보드 탭 사용

.단계
Grid Manager 대시보드의 ILM 탭을 사용하여 ILM 작업을 모니터링합니다.

. 그리드 관리자에 Sign in .
. 대시보드에서 ILM 탭을 선택하고 ILM 대기열(개체) 카드와 ILM 평가 요율 카드의 값을 기록합니다.
+
대시보드의 ILM 대기열(개체) 카드에서 일시적으로 급증이 발생할 수 있습니다.  하지만 대기열이 계속 늘어나고 결코 줄어들지 않는다면 그리드는 효율적으로 운영하기 위해 더 많은 리소스가 필요합니다. 즉, 더 많은 스토리지 노드가 필요하거나, ILM 정책에 따라 개체가 원격 위치에 배치되는 경우 더 많은 네트워크 대역폭이 필요합니다.





== NODES 페이지를 사용하세요

.단계
또한 *NODES* 페이지를 사용하여 ILM 대기열을 조사하세요.


NOTE: *NODES* 페이지의 차트는 향후 StorageGRID 릴리스에서 해당 대시보드 카드로 교체될 예정입니다.

. *노드*를 선택하세요.
. *_그리드 이름_* > *ILM*을 선택합니다.
. ILM 대기열 그래프 위에 커서를 놓으면 특정 시점에서 다음 속성의 값을 확인할 수 있습니다.
+
** *대기 중인 개체(클라이언트 작업에서)*: 클라이언트 작업(예: 수집)으로 인해 ILM 평가를 기다리는 총 개체 수입니다.
** *대기 중인 객체(모든 작업에서)*: ILM 평가를 기다리는 총 객체 수입니다.
** *스캔 속도(객체/초)*: 그리드 내 객체가 스캔되어 ILM 대기열에 추가되는 속도입니다.
** *평가 속도(객체/초)*: 그리드에서 ILM 정책에 따라 객체가 평가되는 현재 속도입니다.


. ILM 대기열 섹션에서 다음 속성을 살펴보세요.
+

NOTE: ILM 대기열 섹션은 그리드에만 포함됩니다.  이 정보는 사이트나 스토리지 노드의 ILM 탭에 표시되지 않습니다.

+
** *스캔 기간 - 추정*: 모든 객체에 대한 전체 ILM 스캔을 완료하는 데 걸리는 예상 시간입니다.
+

NOTE: 전체 검사를 수행해도 ILM이 모든 개체에 적용되었다는 보장은 없습니다.

** *시도된 복구*: 복제된 데이터에 대해 시도된 총 개체 복구 작업 수입니다. 이 수는 스토리지 노드가 고위험 객체를 복구하려고 할 때마다 증가합니다. 전력망이 혼잡해지면 위험성이 높은 ILM 수리가 우선시됩니다.
+

NOTE: 복구 후 복제가 실패하면 동일한 개체 복구가 다시 증가할 수 있습니다.



+
이러한 속성은 스토리지 노드 볼륨 복구 진행 상황을 모니터링할 때 유용할 수 있습니다. 수리 시도 횟수가 더 이상 증가하지 않고 전체 검사가 완료되면 수리가 완료된 것으로 추정됩니다.


