---
permalink: monitor/reviewing-audit-messages.html 
sidebar: sidebar 
keywords: how to review audit messages, how to view audit messages 
summary: 감사 메시지를 통해 StorageGRID 시스템의 세부적인 작업을 더 잘 이해할 수 있습니다.  감사 로그를 사용하여 문제를 해결하고 성과를 평가할 수 있습니다. 
---
= 감사 메시지 검토
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 메시지를 통해 StorageGRID 시스템의 세부적인 작업을 더 잘 이해할 수 있습니다.  감사 로그를 사용하여 문제를 해결하고 성과를 평가할 수 있습니다.

정상적인 시스템 작동 중에 모든 StorageGRID 서비스는 다음과 같이 감사 메시지를 생성합니다.

* 시스템 감사 메시지는 감사 시스템 자체, 그리드 노드 상태, 시스템 전체 작업 활동 및 서비스 백업 작업과 관련이 있습니다.
* 개체 저장소 감사 메시지는 개체 저장소 및 검색, 그리드 노드 간 전송, 검증을 포함하여 StorageGRID 내의 개체 저장소 및 관리와 관련됩니다.
* S3 클라이언트 애플리케이션이 객체를 생성, 수정 또는 검색하기 위한 요청을 하면 클라이언트 읽기 및 쓰기 감사 메시지가 기록됩니다.
* 관리 감사 메시지는 관리 API에 대한 사용자 요청을 기록합니다.


각 관리 노드는 감사 메시지를 텍스트 파일에 저장합니다.  감사 공유에는 활성 파일(audit.log)과 이전 날짜의 압축된 감사 로그가 포함되어 있습니다.  그리드의 각 노드는 노드에서 생성된 감사 정보의 사본도 저장합니다.

관리 노드의 명령줄에서 직접 감사 로그 파일에 액세스할 수 있습니다.

StorageGRID 기본적으로 감사 정보를 보낼 수 있으며, 대상을 변경할 수도 있습니다.

* StorageGRID 기본적으로 로컬 노드 감사 대상으로 설정됩니다.
* Grid Manager 및 Tenant Manager 감사 로그 항목은 스토리지 노드로 전송될 수 있습니다.
* 선택적으로 감사 로그의 대상을 변경하고 감사 정보를 외부 syslog 서버로 보낼 수 있습니다. 외부 syslog 서버가 구성되면 감사 기록의 로컬 로그가 계속 생성되어 저장됩니다.
* link:../monitor/configure-audit-messages.html["감사 메시지 및 로그 대상 구성에 대해 알아보세요."] .


감사 로그 파일, 감사 메시지 형식, 감사 메시지 유형 및 감사 메시지를 분석하는 데 사용할 수 있는 도구에 대한 자세한 내용은 다음을 참조하세요.link:../audit/index.html["감사 로그 검토"] .
