---
permalink: monitor/snmp-alert-notifications.html 
sidebar: sidebar 
keywords: how to use snmp notifications for alerts 
summary: 경고가 발생할 때 StorageGRID SNMP 알림을 보내도록 하려면 StorageGRID SNMP 에이전트를 활성화하고 하나 이상의 트랩 대상을 구성해야 합니다. 
---
= 경고에 대한 SNMP 알림 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
경고가 발생할 때 StorageGRID SNMP 알림을 보내도록 하려면 StorageGRID SNMP 에이전트를 활성화하고 하나 이상의 트랩 대상을 구성해야 합니다.

Grid Manager의 *구성* > *모니터링* > *SNMP 에이전트* 옵션이나 Grid Management API의 SNMP 엔드포인트를 사용하여 StorageGRID SNMP 에이전트를 활성화하고 구성할 수 있습니다. SNMP 에이전트는 SNMP 프로토콜의 세 가지 버전을 모두 지원합니다.

SNMP 에이전트를 구성하는 방법을 알아보려면 다음을 참조하세요.link:using-snmp-monitoring.html["SNMP 모니터링 사용"] .

StorageGRID SNMP 에이전트를 구성한 후에는 두 가지 유형의 이벤트 기반 알림을 보낼 수 있습니다.

* 트랩은 관리 시스템의 확인이 필요하지 않은 SNMP 에이전트가 보내는 알림입니다.  트랩은 StorageGRID 내에서 경고가 발생하는 등의 일이 발생했음을 관리 시스템에 알리는 역할을 합니다.  트랩은 SNMP의 세 가지 버전 모두에서 지원됩니다.
* 인포메이션은 트랩과 유사하지만 관리 시스템의 승인이 필요합니다.  SNMP 에이전트가 일정 시간 내에 확인 응답을 받지 못하면 확인 응답을 받거나 최대 재시도 값에 도달할 때까지 알림을 다시 보냅니다.  Informs는 SNMPv2c 및 SNMPv3에서 지원됩니다.


트랩 및 알림은 기본 또는 사용자 지정 알림이 심각도 수준에 관계없이 트리거될 때 전송됩니다.  경보에 대한 SNMP 알림을 억제하려면 경보에 대한 무음을 구성해야 합니다. 보다 link:silencing-alert-notifications.html["알림음 끄기"] .

StorageGRID 배포에 여러 관리 노드가 포함된 경우 기본 관리 노드는 경고 알림, AutoSupport 패키지, SNMP 트랩 및 정보를 보내는 기본 발신자입니다.  기본 관리 노드를 사용할 수 없게 되면 다른 관리 노드에서 일시적으로 알림을 보냅니다. 보다 link:../primer/what-admin-node-is.html["관리 노드란 무엇인가요?"] .
