---
permalink: monitor/updating-snmp-agent.html 
sidebar: sidebar 
keywords: how to update the SNMP agent 
summary: SNMP 알림을 비활성화하고, 커뮤니티 문자열을 업데이트하고, 에이전트 주소, USM 사용자, 트랩 대상을 추가하거나 제거할 수 있습니다. 
---
= SNMP 에이전트 업데이트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP 알림을 비활성화하고, 커뮤니티 문자열을 업데이트하고, 에이전트 주소, USM 사용자, 트랩 대상을 추가하거나 제거할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["루트 액세스 권한"] .


.이 작업에 관하여
보다link:configuring-snmp-agent.html["SNMP 에이전트 구성"] SNMP 에이전트 페이지의 각 필드에 대한 자세한 내용은 다음을 참조하세요.  각 탭에서 변경한 내용을 적용하려면 페이지 하단의 *저장*을 선택해야 합니다.

.단계
. *구성* > *모니터링* > *SNMP 에이전트*를 선택합니다.
+
SNMP 에이전트 페이지가 나타납니다.

. 모든 그리드 노드에서 SNMP 에이전트를 비활성화하려면 *SNMP 사용* 확인란을 선택 취소하고 *저장*을 선택합니다.
+
SNMP 에이전트를 다시 활성화하면 이전 SNMP 구성 설정이 그대로 유지됩니다.

. 선택적으로 기본 구성 섹션의 정보를 업데이트합니다.
+
.. 필요에 따라 *시스템 연락처*와 *시스템 위치*를 업데이트하세요.
.. 선택적으로, *SNMP 에이전트 알림 사용* 확인란을 선택하거나 선택 취소하여 StorageGRID SNMP 에이전트가 트랩 및 알림 알림을 보낼지 여부를 제어할 수 있습니다.
+
이 확인란의 선택을 취소하면 SNMP 에이전트는 읽기 전용 MIB 액세스를 지원하지만 SNMP 알림을 보내지 않습니다.

.. 선택적으로, StorageGRID SNMP 에이전트가 부적절하게 인증된 프로토콜 메시지를 수신했을 때 인증 트랩을 보낼지 여부를 제어하려면 *인증 트랩 사용* 확인란을 선택하거나 선택 취소합니다.


. SNMPv1 또는 SNMPv2c를 사용하는 경우, 선택적으로 커뮤니티 문자열 섹션에서 *읽기 전용 커뮤니티*를 업데이트하거나 추가합니다.
. 트랩 대상을 업데이트하려면 기타 구성 섹션에서 트랩 대상 탭을 선택하세요.
+
이 탭을 사용하여 StorageGRID 트랩 또는 알림에 대한 하나 이상의 대상을 정의합니다.  SNMP 에이전트를 활성화하고 *저장*을 선택하면 StorageGRID 경고가 발생할 때 정의된 각 대상에 알림을 보냅니다.  지원되는 MIB-II 엔터티(예: ifDown 및 coldStart)에 대해서도 표준 알림이 전송됩니다.

+
입력해야 할 내용에 대한 자세한 내용은 다음을 참조하세요.link:../monitor/configuring-snmp-agent.html#create-trap-destinations["트랩 목적지 만들기"] .

+
** 선택적으로 기본 트랩 커뮤니티를 업데이트하거나 제거합니다.
+
기본 트랩 커뮤니티를 제거하는 경우 먼저 기존 트랩 대상이 사용자 지정 커뮤니티 문자열을 사용하는지 확인해야 합니다.

** 트랩 대상을 추가하려면 *만들기*를 선택하세요.
** 트랩 대상을 편집하려면 라디오 버튼을 선택하고 *편집*을 선택하세요.
** 트랩 대상을 제거하려면 라디오 버튼을 선택하고 *제거*를 선택하세요.
** 변경 사항을 적용하려면 페이지 하단의 *저장*을 선택하세요.


. 에이전트 주소를 업데이트하려면 기타 구성 섹션에서 에이전트 주소 탭을 선택하세요.
+
이 탭을 사용하여 하나 이상의 "수신 주소"를 지정합니다.  이는 SNMP 에이전트가 쿼리를 수신할 수 있는 StorageGRID 주소입니다.

+
입력해야 할 내용에 대한 자세한 내용은 다음을 참조하세요.link:../monitor/configuring-snmp-agent.html#create-agent-addresses["에이전트 주소 생성"] .

+
** 에이전트 주소를 추가하려면 *만들기*를 선택하세요.
** 에이전트 주소를 편집하려면 라디오 버튼을 선택하고 *편집*을 선택하세요.
** 에이전트 주소를 제거하려면 라디오 버튼을 선택하고 *제거*를 선택하세요.
** 변경 사항을 적용하려면 페이지 하단의 *저장*을 선택하세요.


. USM 사용자를 업데이트하려면 기타 구성 섹션에서 USM 사용자 탭을 선택하세요.
+
이 탭을 사용하여 MIB를 쿼리하거나 트랩 및 정보를 수신할 권한이 있는 USM 사용자를 정의합니다.

+
입력해야 할 내용에 대한 자세한 내용은 다음을 참조하세요.link:../monitor/configuring-snmp-agent.html#create-usm-users["USM 사용자 생성"] .

+
** USM 사용자를 추가하려면 *만들기*를 선택하세요.
** USM 사용자를 편집하려면 라디오 버튼을 선택하고 *편집*을 선택하세요.
+
기존 USM 사용자의 사용자 이름은 변경할 수 없습니다.  사용자 이름을 변경해야 하는 경우 기존 사용자를 삭제하고 새 사용자를 만들어야 합니다.

+

NOTE: 사용자의 권한 있는 엔진 ID를 추가하거나 제거하고 해당 사용자가 현재 대상으로 선택된 경우 대상을 편집하거나 제거해야 합니다.  그렇지 않으면 SNMP 에이전트 구성을 저장할 때 유효성 검사 오류가 발생합니다.

** USM 사용자를 제거하려면 라디오 버튼을 선택하고 *제거*를 선택하세요.
+

NOTE: 제거한 사용자가 현재 트랩 대상으로 선택된 경우 대상을 편집하거나 제거해야 합니다.  그렇지 않으면 SNMP 에이전트 구성을 저장할 때 유효성 검사 오류가 발생합니다.

** 변경 사항을 적용하려면 페이지 하단의 *저장*을 선택하세요.


. SNMP 에이전트 구성을 업데이트한 후 *저장*을 선택합니다.

