---
permalink: monitor/using-snmp-monitoring.html 
sidebar: sidebar 
keywords: snmp, monitoring 
summary: 'SNMP(Simple Network Management Protocol)를 사용하여 StorageGRID 모니터링하려면 StorageGRID 에 포함된 SNMP 에이전트를 구성해야 합니다.' 
---
= SNMP 모니터링 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP(Simple Network Management Protocol)를 사용하여 StorageGRID 모니터링하려면 StorageGRID 에 포함된 SNMP 에이전트를 구성해야 합니다.

* link:configuring-snmp-agent.html["SNMP 에이전트 구성"]
* link:updating-snmp-agent.html["SNMP 에이전트 업데이트"]




== 역량

각 StorageGRID 노드는 MIB를 제공하는 SNMP 에이전트 또는 데몬을 실행합니다.  StorageGRID MIB에는 알림에 대한 테이블과 알림 정의가 포함되어 있습니다.  MIB에는 각 노드의 플랫폼 및 모델 번호와 같은 시스템 설명 정보도 포함되어 있습니다.  각 StorageGRID 노드는 MIB-II 객체의 하위 집합도 지원합니다.


NOTE: 보다link:access-snmp-mib.html["MIB 파일 접근"] 그리드 노드에 MIB 파일을 다운로드하려는 경우.

처음에는 모든 노드에서 SNMP가 비활성화되어 있습니다.  SNMP 에이전트를 구성하면 모든 StorageGRID 노드가 동일한 구성을 수신합니다.

StorageGRID SNMP 에이전트는 SNMP 프로토콜의 세 가지 버전을 모두 지원합니다.  쿼리에 대한 읽기 전용 MIB 액세스를 제공하고 관리 시스템에 두 가지 유형의 이벤트 기반 알림을 보낼 수 있습니다.

트랩:: 트랩은 관리 시스템의 확인이 필요하지 않은 SNMP 에이전트가 보내는 알림입니다.  트랩은 StorageGRID 내에서 경고가 발생하는 등의 일이 발생했음을 관리 시스템에 알리는 역할을 합니다.
+
--
트랩은 SNMP의 세 가지 버전 모두에서 지원됩니다.

--
알려줍니다:: 인포메이션은 트랩과 유사하지만 관리 시스템의 승인이 필요합니다.  SNMP 에이전트가 일정 시간 내에 확인 응답을 받지 못하면 확인 응답을 받거나 최대 재시도 값에 도달할 때까지 알림을 다시 보냅니다.
+
--
Informs는 SNMPv2c 및 SNMPv3에서 지원됩니다.

--


트랩 및 알림은 다음과 같은 경우에 전송됩니다.

* 기본 또는 사용자 지정 알림은 모든 심각도 수준에서 트리거됩니다.  경고에 대한 SNMP 알림을 억제하려면 다음을 수행해야 합니다.link:silencing-alert-notifications.html["무음 설정"] 경고를 위해.  알림 알림은 다음에 의해 전송됩니다.link:../primer/what-admin-node-is.html["선호하는 발신자 관리 노드"] .
+
각 알림은 알림의 심각도 수준에 따라 activeMinorAlert, activeMajorAlert, activeCriticalAlert의 세 가지 트랩 유형 중 하나에 매핑됩니다.  이러한 트랩을 트리거할 수 있는 경고 목록은 다음을 참조하세요.link:alerts-reference.html["알림 참조"] .





== SNMP 버전 지원

이 표는 각 SNMP 버전에서 지원되는 사항에 대한 간략한 요약을 제공합니다.

[cols="1a,2a,2a,2a"]
|===
|  | SNMPv1 | SNMPv2c | SNMPv3 


 a| 
쿼리

(GET 및 GETNEXT)
 a| 
읽기 전용 MIB 쿼리
 a| 
읽기 전용 MIB 쿼리
 a| 
읽기 전용 MIB 쿼리



 a| 
쿼리 인증
 a| 
커뮤니티 스트링
 a| 
커뮤니티 스트링
 a| 
사용자 기반 보안 모델(USM) 사용자



 a| 
알림

(함정과 정보)
 a| 
함정만
 a| 
함정과 정보
 a| 
함정과 정보



 a| 
알림 인증
 a| 
각 트랩 대상에 대한 기본 트랩 커뮤니티 또는 사용자 정의 커뮤니티 문자열
 a| 
각 트랩 대상에 대한 기본 트랩 커뮤니티 또는 사용자 정의 커뮤니티 문자열
 a| 
각 트랩 대상에 대한 USM 사용자

|===


== 제한 사항

* StorageGRID 읽기 전용 MIB 액세스를 지원합니다.  읽기-쓰기 접근은 지원되지 않습니다.
* 그리드의 모든 노드는 동일한 구성을 받습니다.
* SNMPv3: StorageGRID TSM(Transport Support Mode)을 지원하지 않습니다.
* SNMPv3: 지원되는 유일한 인증 프로토콜은 SHA(HMAC-SHA-96)입니다.
* SNMPv3: 지원되는 유일한 개인정보 보호 프로토콜은 AES입니다.

