---
permalink: maintain/accessing-server-manager-log-file.html 
sidebar: sidebar 
keywords: storagegrid, server manager, log file 
summary: 서버 관리자를 사용하는 동안 문제가 발생하면 로그 파일을 확인하세요. 
---
= 서버 관리자 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
서버 관리자를 사용하는 동안 문제가 발생하면 로그 파일을 확인하세요.

서버 관리자와 관련된 오류 메시지는 다음 위치에 있는 서버 관리자 로그 파일에 기록됩니다. `/var/local/log/servermanager.log`

이 파일에서 실패와 관련된 오류 메시지를 확인하세요.  필요한 경우 기술 지원팀에 문제를 보고하세요.  기술 지원팀에 로그 파일을 전달해 달라는 요청을 받을 수도 있습니다.



== 오류 상태가 있는 서비스

서비스가 오류 상태에 들어간 것을 감지하면 서비스를 다시 시작해 보세요.

.시작하기 전에
당신은 가지고있다 `Passwords.txt` 파일.

.이 작업에 관하여
서버 관리자는 서비스를 모니터링하고 예기치 않게 중지된 서비스를 다시 시작합니다.  서비스에 오류가 발생하면 서버 관리자는 해당 서비스를 다시 시작하려고 시도합니다.  5분 이내에 서비스를 시작하려는 시도가 3번 실패하면 서비스는 오류 상태가 됩니다.  서버 관리자는 다시 시작을 시도하지 않습니다.

.단계
. 그리드 노드에 로그인하세요:
+
.. 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.


+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .

. 서비스의 오류 상태를 확인하세요. `service _servicename_ status`
+
예를 들어:

+
[listing]
----
service ldr status
----
+
서비스가 오류 상태인 경우 다음 메시지가 반환됩니다. `_servicename_ in error state` . 예를 들어:

+
[listing]
----
ldr in error state
----
+

NOTE: 서비스 상태가 다음과 같은 경우 `disabled` , 지침을 참조하세요link:using-donotstart-file.html["서비스에 대한 DoNotStart 파일 제거"] .

. 서비스를 다시 시작하여 오류 상태를 제거해 보세요. `service _servicename_ restart`
+
서비스가 재시작되지 않으면 기술 지원팀에 문의하세요.

. 명령 셸에서 로그아웃합니다. `exit`

