---
permalink: maintain/all-node-types-replacing-vmware-node.html 
sidebar: sidebar 
keywords: replace VMware node 
summary: VMware에서 호스팅된 실패한 StorageGRID 노드를 복구하는 경우 실패한 노드를 제거하고 복구 노드를 배포합니다. 
---
= VMware 노드 교체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware에서 호스팅된 실패한 StorageGRID 노드를 복구하는 경우 실패한 노드를 제거하고 복구 노드를 배포합니다.

.시작하기 전에
가상 머신을 복원할 수 없고 교체해야 한다는 것을 확인했습니다.

.이 작업에 관하여
VMware vSphere Web Client를 사용하여 먼저 실패한 그리드 노드와 연결된 가상 머신을 제거합니다.  그런 다음 새로운 가상 머신을 배포할 수 있습니다.

이 절차는 그리드 노드 복구 프로세스의 한 단계일 뿐입니다.  노드 제거 및 배포 절차는 관리 노드, 스토리지 노드, 게이트웨이 노드를 포함한 모든 VMware 노드에서 동일합니다.

.단계
. VMware vSphere Web Client에 로그인합니다.
. 실패한 그리드 노드 가상 머신으로 이동합니다.
. 복구 노드를 배포하는 데 필요한 모든 정보를 기록해 두세요.
+
.. 가상 머신을 마우스 오른쪽 버튼으로 클릭하고 *설정 편집* 탭을 선택한 다음 사용 중인 설정을 기록해 둡니다.
.. *vApp 옵션* 탭을 선택하여 그리드 노드 네트워크 설정을 보고 기록합니다.


. 실패한 그리드 노드가 스토리지 노드인 경우, 데이터 저장에 사용된 가상 하드 디스크가 손상되지 않았는지 확인하고 복구된 그리드 노드에 다시 연결할 수 있도록 보관합니다.
. 가상 머신의 전원을 끕니다.
. 가상 머신을 삭제하려면 *작업* > *모든 vCenter 작업* > *디스크에서 삭제*를 선택합니다.
. 교체 노드가 될 새로운 가상 머신을 배포하고 하나 이상의 StorageGRID 네트워크에 연결합니다. 지침은 다음을 참조하세요.link:../vmware/deploying-storagegrid-node-as-virtual-machine.html["StorageGRID 노드를 가상 머신으로 배포"] .
+
노드를 배포할 때 선택적으로 노드 포트를 다시 매핑하거나 CPU 또는 메모리 설정을 늘릴 수 있습니다.

+

NOTE: 새 노드를 배포한 후에는 스토리지 요구 사항에 따라 새 가상 디스크를 추가하고, 이전에 제거된 실패한 그리드 노드에서 보존된 가상 하드 디스크를 다시 연결하거나 두 가지 모두를 수행할 수 있습니다.

. 복구하려는 노드 유형에 따라 노드 복구 절차를 완료합니다.
+
[cols="1a,2a"]
|===
| 노드 유형 | 로 가다 


 a| 
기본 관리 노드
 a| 
link:configuring-replacement-primary-admin-node.html["교체용 기본 관리 노드 구성"]



 a| 
기본이 아닌 관리 노드
 a| 
link:selecting-start-recovery-to-configure-non-primary-admin-node.html["비기본 관리 노드를 구성하려면 복구 시작을 선택하세요."]



 a| 
게이트웨이 노드
 a| 
link:selecting-start-recovery-to-configure-gateway-node.html["게이트웨이 노드를 구성하려면 복구 시작을 선택하세요."]



 a| 
저장 노드
 a| 
link:selecting-start-recovery-to-configure-storage-node.html["스토리지 노드를 구성하려면 복구 시작을 선택하세요."]

|===

