---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: configure ip address, change IP tool, ethernet, dhcp, ha group 
summary: IP 변경 도구를 사용하여 그리드 노드의 IP 주소를 구성하여 네트워크 구성을 수행할 수 있습니다. 
---
= IP 주소 가이드라인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IP 변경 도구를 사용하여 그리드 노드의 IP 주소를 구성하여 네트워크 구성을 수행할 수 있습니다.

그리드 배포 중에 처음 설정된 네트워크 구성을 대부분 변경하려면 IP 변경 도구를 사용해야 합니다.  표준 Linux 네트워킹 명령과 파일을 사용하여 수동으로 변경한 내용은 모든 StorageGRID 서비스에 전파되지 않을 수 있으며, 업그레이드, 재부팅 또는 노드 복구 절차에서 지속되지 않을 수 있습니다.


NOTE: IP 변경 절차는 방해가 되는 절차가 될 수 있습니다.  새로운 구성이 적용될 때까지 그리드의 일부를 사용하지 못할 수도 있습니다.


NOTE: 그리드 네트워크 서브넷 목록만 변경하는 경우 그리드 관리자를 사용하여 네트워크 구성을 추가하거나 변경하세요.  그렇지 않은 경우, 네트워크 구성 문제로 인해 Grid Manager에 접근할 수 없는 경우나 Grid Network 라우팅 변경과 기타 네트워크 변경을 동시에 수행하는 경우 IP 변경 도구를 사용하세요.


TIP: 그리드의 모든 노드에 대한 그리드 네트워크 IP 주소를 변경하려면 다음을 사용하십시오.link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["그리드 전체 변경을 위한 특별 절차"] .



== 이더넷 인터페이스

eth0에 할당된 IP 주소는 항상 그리드 노드의 그리드 네트워크 IP 주소입니다.  eth1에 할당된 IP 주소는 항상 그리드 노드의 관리 네트워크 IP 주소입니다.  eth2에 할당된 IP 주소는 항상 그리드 노드의 클라이언트 네트워크 IP 주소입니다.

StorageGRID 어플라이언스와 같은 일부 플랫폼에서는 eth0, eth1, eth2가 물리적 또는 VLAN 인터페이스의 하위 브리지나 본드로 구성된 집계 인터페이스일 수 있습니다.  이러한 플랫폼에서 *SSM* > *리소스* 탭에는 eth0, eth1 또는 eth2 외에 다른 인터페이스에 할당된 그리드, 관리자 및 클라이언트 네트워크 IP 주소가 표시될 수 있습니다.



== DHCP

DHCP는 배포 단계에서만 설정할 수 있습니다.  구성하는 동안에는 DHCP를 설정할 수 없습니다.  그리드 노드의 IP 주소, 서브넷 마스크, 기본 게이트웨이를 변경하려면 IP 주소 변경 절차를 사용해야 합니다.  IP 변경 도구를 사용하면 DHCP 주소가 고정됩니다.



== 고가용성(HA) 그룹

* 클라이언트 네트워크 인터페이스가 HA 그룹에 포함된 경우 해당 인터페이스의 클라이언트 네트워크 IP 주소를 HA 그룹에 대해 구성된 서브넷 외부의 주소로 변경할 수 없습니다.
* 클라이언트 네트워크 인터페이스에 구성된 HA 그룹에 할당된 기존 가상 IP 주소 값으로 클라이언트 네트워크 IP 주소를 변경할 수 없습니다.
* Grid 네트워크 인터페이스가 HA 그룹에 포함된 경우 해당 인터페이스의 Grid 네트워크 IP 주소를 HA 그룹에 대해 구성된 서브넷 외부의 주소로 변경할 수 없습니다.
* Grid Network 인터페이스에 구성된 HA 그룹에 할당된 기존 가상 IP 주소 값으로 Grid Network IP 주소를 변경할 수 없습니다.

