---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: 'StorageGRID 시스템의 그리드 노드 간에 데이터가 정확하게 동기화되도록 하기 위해 네트워크 시간 프로토콜(NTP) 서버를 추가, 업데이트 또는 제거할 수 있습니다.' 
---
= NTP 서버 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템의 그리드 노드 간에 데이터가 정확하게 동기화되도록 하기 위해 NTP(네트워크 시간 프로토콜) 서버를 추가, 업데이트 또는 제거할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"] .
* 프로비저닝 암호가 있습니다.
* NTP 서버의 IPv4 주소를 구성해야 합니다.




== StorageGRID NTP를 사용하는 방법

StorageGRID 시스템은 NTP(네트워크 시간 프로토콜)를 사용하여 그리드의 모든 그리드 노드 간의 시간을 동기화합니다.

각 사이트에서는 StorageGRID 시스템의 두 개 이상의 노드에 기본 NTP 역할이 할당됩니다.  이들은 최소 4개, 최대 6개의 외부 시간 소스와 서로 동기화됩니다.  StorageGRID 시스템에서 기본 NTP 노드가 아닌 모든 노드는 NTP 클라이언트 역할을 하며 이러한 기본 NTP 노드와 동기화됩니다.

외부 NTP 서버는 이전에 기본 NTP 역할을 할당한 노드에 연결됩니다.  이러한 이유로 기본 NTP 역할을 갖는 노드를 두 개 이상 지정하는 것이 좋습니다.



== NTP 서버 가이드라인

타이밍 문제를 방지하려면 다음 지침을 따르세요.

* 외부 NTP 서버는 이전에 기본 NTP 역할을 할당한 노드에 연결됩니다.  이러한 이유로 기본 NTP 역할을 갖는 노드를 두 개 이상 지정하는 것이 좋습니다.
* 각 사이트에서 최소 2개의 노드가 최소 4개의 외부 NTP 소스에 액세스할 수 있는지 확인하세요.  한 사이트에서 단 하나의 노드만 NTP 소스에 도달할 수 있는 경우, 해당 노드가 다운되면 타이밍 문제가 발생합니다.  또한, 사이트당 두 개의 노드를 기본 NTP 소스로 지정하면 사이트가 그리드의 나머지 부분과 분리되어 있는 경우에도 정확한 타이밍을 보장할 수 있습니다.
* 지정된 외부 NTP 서버는 NTP 프로토콜을 사용해야 합니다.  시간 드리프트 문제를 방지하려면 Stratum 3 이상의 NTP 서버 참조를 지정해야 합니다.



NOTE: 프로덕션 수준 StorageGRID 설치에 대한 외부 NTP 소스를 지정할 때 Windows Server 2016 이전 버전의 Windows에서는 Windows 시간(W32Time) 서비스를 사용하지 마세요.  이전 버전의 Windows에서 제공되는 시간 서비스는 충분히 정확하지 않으며 StorageGRID 포함하여 고정확도 환경에서 사용하도록 Microsoft에서 지원되지 않습니다.  자세한 내용은 다음을 참조하세요. https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura["고정확도 환경을 위한 Windows 시간 서비스 구성을 위한 경계 지원"^] .



== NTP 서버 구성

NTP 서버를 추가, 업데이트 또는 제거하려면 다음 단계를 따르세요.

.단계
. *유지관리* > *네트워크* > *NTP 서버*를 선택합니다.
. 서버 섹션에서 필요에 따라 NTP 서버 항목을 추가, 업데이트 또는 제거합니다.
+
최소 4개의 NTP 서버를 포함해야 하며, 최대 6개까지 서버를 지정할 수 있습니다.

. StorageGRID 시스템의 프로비저닝 암호를 입력한 다음 *저장*을 선택합니다.
+
구성 업데이트가 완료될 때까지 페이지가 비활성화됩니다.

+

NOTE: 새로운 NTP 서버를 저장한 후 모든 NTP 서버가 연결 테스트에 실패하면 진행하지 마세요. 기술 지원팀에 문의하세요.





== NTP 서버 문제 해결

설치 중에 원래 지정된 NTP 서버의 안정성이나 가용성에 문제가 발생하면 추가 서버를 추가하거나 기존 서버를 업데이트 또는 제거하여 StorageGRID 시스템이 사용하는 외부 NTP 소스 목록을 업데이트할 수 있습니다.
