---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storage node decommission, considerations, appliance node clone 
summary: 스토리지 노드를 해제하기 전에 대신 노드를 복제할 수 있는지 고려하세요.  그런 다음 노드를 해제하기로 결정한 경우 해제 절차 중에 StorageGRID 개체와 메타데이터를 관리하는 방식을 검토하세요. 
---
= 스토리지 노드 해체를 위한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드를 해제하기 전에 대신 노드를 복제할 수 있는지 고려하세요.  그런 다음 노드를 해제하기로 결정한 경우 해제 절차 중에 StorageGRID 개체와 메타데이터를 관리하는 방식을 검토하세요.



== 노드를 폐기하는 대신 복제해야 하는 경우

기존 어플라이언스 스토리지 노드를 최신 또는 더 큰 어플라이언스로 교체하려는 경우, 확장 시 새 어플라이언스를 추가한 다음 기존 어플라이언스를 폐기하는 대신 어플라이언스 노드를 복제하는 것을 고려하세요.

어플라이언스 노드 복제를 사용하면 기존 어플라이언스 노드를 동일한 StorageGRID 사이트에 있는 호환되는 어플라이언스로 쉽게 교체할 수 있습니다.  복제 프로세스에서는 모든 데이터를 새 기기로 전송하고, 새 기기를 서비스에 투입하고, 기존 기기를 설치 전 상태로 둡니다.

필요한 경우 어플라이언스 노드를 복제할 수 있습니다.

* 수명이 다한 가전제품을 교체하세요.
* 기존 노드를 업그레이드하여 향상된 어플라이언스 기술을 활용하세요.
* StorageGRID 시스템의 스토리지 노드 수를 변경하지 않고도 그리드 스토리지 용량을 늘릴 수 있습니다.
* RAID 모드를 변경하는 등의 방법으로 저장 효율성을 향상시킵니다.


보다 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["어플라이언스 노드 복제"^] 자세한 내용은.



== 연결된 스토리지 노드에 대한 고려 사항

연결된 스토리지 노드를 해제할 때의 고려 사항을 검토하세요.

* 단일 노드 해체 절차에서 10개가 넘는 스토리지 노드를 해체해서는 안 됩니다.
* 시스템은 항상 다음을 포함하여 운영 요구 사항을 충족할 만큼 충분한 저장 노드를 포함해야 합니다.link:understanding-adc-service-quorum.html["ADC 쿼럼"] 그리고 활동적인link:reviewing-ilm-policy-and-storage-configuration.html["ILM 정책"] .  이러한 제한을 충족하려면 기존 스토리지 노드를 해제하기 전에 확장 작업에서 새 스토리지 노드를 추가해야 할 수도 있습니다.
+
소프트웨어 기반 메타데이터 전용 노드가 포함된 그리드에서 스토리지 노드를 해제할 때는 주의하세요.  객체와 메타데이터를 모두 저장하도록 구성된 모든 노드를 해제하면 그리드에서 객체를 저장하는 기능이 제거됩니다.  보다link:../primer/what-storage-node-is.html#types-of-storage-nodes["저장 노드 유형"] 메타데이터 전용 스토리지 노드에 대한 자세한 내용은 다음을 참조하세요.

* 스토리지 노드를 제거하면 대량의 개체 데이터가 네트워크를 통해 전송됩니다.  이러한 전송은 일반적인 시스템 작동에는 영향을 미치지 않지만 StorageGRID 시스템에서 사용하는 총 네트워크 대역폭에 영향을 미칠 수 있습니다.
* 스토리지 노드 해체와 관련된 작업은 일반 시스템 작업과 관련된 작업보다 우선순위가 낮습니다.  즉, 해체는 정상적인 StorageGRID 시스템 운영을 방해하지 않으며, 시스템이 활동하지 않는 기간 동안 일정을 예약할 필요가 없습니다.  해체는 백그라운드에서 수행되므로 프로세스가 완료되는 데 얼마나 걸릴지 예측하기 어렵습니다.  일반적으로 시스템이 조용하거나 한 번에 하나의 스토리지 노드만 제거되는 경우 해체가 더 빨리 완료됩니다.
* 저장 노드를 해체하는 데는 며칠 또는 몇 주가 걸릴 수 있습니다.  이에 따라 이 절차를 계획하세요.  해체 프로세스는 시스템 운영에 영향을 미치지 않도록 설계되었지만 다른 절차를 제한할 수 있습니다.  일반적으로 그리드 노드를 제거하기 전에 계획된 시스템 업그레이드나 확장을 수행해야 합니다.
* 스토리지 노드가 제거되는 동안 다른 유지 관리 절차를 수행해야 하는 경우 다음을 수행할 수 있습니다.link:pausing-and-resuming-decommission-process-for-storage-nodes.html["해체 절차를 일시 중지하다"] 다른 절차가 완료된 후에 다시 시작하세요.
+

NOTE: *일시 중지* 버튼은 ILM 평가 또는 삭제 코드화된 데이터 폐기 단계에 도달했을 때만 활성화됩니다. 그러나 ILM 평가(데이터 마이그레이션)는 백그라운드에서 계속 실행됩니다.

* 서비스 해제 작업이 실행 중일 때는 어떠한 그리드 노드에서도 데이터 복구 작업을 실행할 수 없습니다.
* 스토리지 노드가 서비스 해제되는 동안에는 ILM 정책을 변경해서는 안 됩니다.
* 데이터를 영구적이고 안전하게 제거하려면 폐기 절차가 완료된 후 스토리지 노드의 드라이브를 지워야 합니다.




== 연결이 끊긴 스토리지 노드에 대한 고려 사항

연결이 끊긴 스토리지 노드를 해제할 때의 고려 사항을 검토하세요.

* 온라인으로 전환하거나 복구할 수 없다는 확신이 없는 한 연결이 끊긴 노드를 절대로 해제하지 마세요.
+

CAUTION: 노드에서 개체 데이터를 복구할 수 있다고 생각되면 이 절차를 수행하지 마세요.  대신 기술 지원팀에 문의하여 노드 복구가 가능한지 확인하세요.

* 연결이 끊긴 스토리지 노드를 해제하면 StorageGRID 다른 스토리지 노드의 데이터를 사용하여 연결이 끊긴 노드에 있던 개체 데이터와 메타데이터를 재구성합니다.
* 두 개 이상의 연결이 끊긴 스토리지 노드를 해제하면 데이터 손실이 발생할 수 있습니다.  충분한 객체 사본, 삭제된 코드 조각 또는 객체 메타데이터가 남아 있지 않으면 시스템이 데이터를 재구성하지 못할 수 있습니다.  소프트웨어 기반 메타데이터 전용 노드가 있는 그리드에서 스토리지 노드를 해제할 때, 객체와 메타데이터를 모두 저장하도록 구성된 모든 노드를 해제하면 그리드에서 모든 객체 스토리지가 제거됩니다.  보다link:../primer/what-storage-node-is.html#types-of-storage-nodes["저장 노드 유형"] 메타데이터 전용 스토리지 노드에 대한 자세한 내용은 다음을 참조하세요.
+

CAUTION: 복구할 수 없는 연결이 끊긴 스토리지 노드가 두 개 이상 있는 경우 기술 지원팀에 문의하여 가장 좋은 대처 방법을 확인하세요.

* 연결이 끊긴 스토리지 노드를 해제하면 StorageGRID 해제 프로세스가 끝난 후 데이터 복구 작업을 시작합니다.  이러한 작업은 연결이 끊긴 노드에 저장된 개체 데이터와 메타데이터를 재구성하려고 시도합니다.
* 연결이 끊긴 스토리지 노드를 해제하면 해제 절차가 비교적 빠르게 완료됩니다.  그러나 데이터 복구 작업은 실행하는 데 며칠 또는 몇 주가 걸릴 수 있으며, 해체 절차에 의해 모니터링되지 않습니다.  이러한 작업은 수동으로 모니터링하고 필요에 따라 다시 시작해야 합니다. 보다 link:checking-data-repair-jobs.html["데이터 복구 작업 확인"] .
* 개체의 유일한 사본을 포함하는 연결이 끊긴 스토리지 노드를 해제하면 해당 개체가 손실됩니다.  데이터 복구 작업은 현재 연결된 스토리지 노드에 복제된 사본이 하나 이상 있거나 삭제 코딩된 조각이 충분히 있는 경우에만 객체를 재구성하고 복구할 수 있습니다.

