---
permalink: maintain/copying-audit-logs-from-failed-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, primary admin node, primary admin node 
summary: 실패한 기본 관리 노드에서 감사 로그를 복사할 수 있는 경우 그리드의 시스템 활동 및 사용 기록을 유지하기 위해 이를 보존해야 합니다.  복구된 기본 관리 노드가 다시 실행되면 보존된 감사 로그를 해당 노드로 복원할 수 있습니다. 
---
= 실패한 기본 관리 노드에서 감사 로그 복사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실패한 기본 관리 노드에서 감사 로그를 복사할 수 있는 경우 그리드의 시스템 활동 및 사용 기록을 유지하기 위해 이를 보존해야 합니다.  복구된 기본 관리 노드가 다시 실행되면 보존된 감사 로그를 해당 노드로 복원할 수 있습니다.

.이 작업에 관하여
이 절차는 실패한 관리 노드의 감사 로그 파일을 별도의 그리드 노드에 있는 임시 위치로 복사합니다.  이렇게 보존된 감사 로그를 대체 관리 노드로 복사할 수 있습니다.  감사 로그는 새 관리 노드에 자동으로 복사되지 않습니다.

장애 유형에 따라 장애가 발생한 관리 노드에서 감사 로그를 복사하지 못할 수도 있습니다.  배포에 관리 노드가 하나만 있는 경우 복구된 관리 노드는 새 빈 파일에 있는 감사 로그에 이벤트를 기록하기 시작하고 이전에 기록된 데이터는 손실됩니다.  배포에 두 개 이상의 관리 노드가 포함된 경우 다른 관리 노드에서 감사 로그를 복구할 수 있습니다.


NOTE: 지금은 실패한 관리 노드에서 감사 로그에 액세스할 수 없더라도 나중에, 예를 들어 호스트 복구 후에 액세스할 수 있을 수 있습니다.

.단계
. 가능하다면 실패한 관리 노드에 로그인하세요.  그렇지 않은 경우 기본 관리 노드나 다른 관리 노드(사용 가능한 경우)에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. AMS 서비스를 중지하여 새 로그 파일을 생성하지 않도록 합니다.``service ams stop``
. 감사 내보내기 디렉토리로 이동합니다.
+
`cd /var/local/log`

. 소스 이름 바꾸기 `audit.log` 파일을 고유한 번호가 매겨진 파일 이름으로 지정합니다.  예를 들어, audit.log 파일의 이름을 다음과 같이 바꾸세요. `2023-10-25.txt.1` .
+
[listing]
----
ls -l
mv audit.log 2023-10-25.txt.1
----
. AMS 서비스를 다시 시작합니다. `service ams start`
. 모든 감사 로그 파일을 별도의 그리드 노드에 있는 임시 위치로 복사할 디렉토리를 만듭니다. `ssh admin@_grid_node_IP_ mkdir -p /var/local/tmp/saved-audit-logs`
+
메시지가 나타나면 admin 비밀번호를 입력하세요.

. 모든 감사 로그 파일을 임시 위치로 복사합니다. `scp -p * admin@_grid_node_IP_:/var/local/tmp/saved-audit-logs`
+
메시지가 나타나면 admin 비밀번호를 입력하세요.

. 루트로 로그아웃합니다: `exit`

