---
permalink: maintain/gathering-required-materials-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recovery, grid node recovery, node recovery 
summary: 유지 관리 절차를 수행하기 전에, 실패한 그리드 노드를 복구하는 데 필요한 재료가 있는지 확인해야 합니다. 
---
= 그리드 노드 복구에 필요한 재료를 모으세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
유지 관리 절차를 수행하기 전에, 실패한 그리드 노드를 복구하는 데 필요한 재료가 있는지 확인해야 합니다.

[cols="1a,2a"]
|===
| 목 | 노트 


 a| 
StorageGRID 설치 아카이브
 a| 
그리드 노드를 복구해야 하는 경우 다음이 필요합니다.<<download-and-extract-install-files-recover,StorageGRID 설치 파일을 다운로드하세요>> 귀하의 플랫폼을 위해.

*참고:* 스토리지 노드에서 실패한 스토리지 볼륨을 복구하는 경우 파일을 다운로드할 필요가 없습니다.



 a| 
서비스 노트북
 a| 
서비스 노트북에는 다음이 포함되어야 합니다.

* 네트워크 포트
* SSH 클라이언트(예: PuTTY)
* link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"]




 a| 
복구 패키지 `.zip` 파일
 a| 
최신 복구 패키지 사본을 얻으세요 `.zip` 파일:
`sgws-recovery-package-_id-revision_.zip`

내용 `.zip` 시스템이 수정될 때마다 파일이 업데이트됩니다. 이러한 변경 사항을 적용한 후에는 복구 패키지의 최신 버전을 안전한 장소에 보관하라는 지시를 받게 됩니다. 최신 사본을 사용하여 그리드 장애를 복구합니다.

기본 관리 노드가 정상적으로 작동하는 경우 Grid Manager에서 복구 패키지를 다운로드할 수 있습니다.  *유지관리* > *시스템* > *복구 패키지*를 선택하세요.

Grid Manager에 액세스할 수 없는 경우 ADC 서비스가 포함된 일부 스토리지 노드에서 암호화된 복구 패키지 사본을 찾을 수 있습니다.  각 스토리지 노드에서 복구 패키지의 다음 위치를 조사하세요. `/var/local/install/sgws-recovery-package-_grid-id_-_revision_.zip.gpg` 가장 높은 개정 번호의 복구 패키지를 사용하세요.



 a| 
`Passwords.txt`파일
 a| 
명령줄에서 그리드 노드에 액세스하는 데 필요한 암호가 포함되어 있습니다. 복구 패키지에 포함되어 있습니다.



 a| 
프로비저닝 암호
 a| 
암호는 StorageGRID 시스템이 처음 설치될 때 생성되고 문서화됩니다.  프로비저닝 암호가 없습니다. `Passwords.txt` 파일.



 a| 
귀하의 플랫폼에 대한 최신 문서
 a| 
자세한 내용은 플랫폼 공급업체의 웹사이트를 참조하세요.

현재 지원되는 플랫폼 버전은 다음을 참조하세요. https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 도구"^] .

|===


== StorageGRID 설치 파일을 다운로드하고 추출합니다.

.[[다운로드 및 추출 설치 파일 복구]]
소프트웨어를 다운로드하고 파일을 추출하십시오.link:recovering-from-storage-node-failures.html["스토리지 노드에서 실패한 스토리지 볼륨 복구"] .

현재 그리드에서 실행 중인 StorageGRID 버전을 사용해야 합니다.

.단계
. 현재 설치된 소프트웨어 버전을 확인하세요.  그리드 관리자 상단에서 도움말 아이콘을 선택하고 *정보*를 선택하세요.
. 로 가다 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["StorageGRID 용 NetApp 다운로드 페이지"^] .
. 현재 그리드에서 실행 중인 StorageGRID 버전을 선택하세요.
+
StorageGRID 소프트웨어 버전은 다음 형식을 갖습니다. `11.x.y` .

. NetApp 계정의 사용자 이름과 비밀번호로 Sign in .
. 최종 사용자 라이선스 계약을 읽고 확인란을 선택한 다음 *동의 및 계속*을 선택하세요.
. 다운로드 페이지의 * StorageGRID 설치* 열에서 다음을 선택하세요. `.tgz` 또는 `.zip` 귀하의 플랫폼에 맞는 파일입니다.
+
설치 보관 파일에 표시된 버전은 현재 설치된 소프트웨어 버전과 일치해야 합니다.

+
사용하다 `.zip` Windows를 사용하는 경우 파일입니다.

+
[cols="1a,2a"]
|===
| 플랫폼 | 설치 아카이브 


 a| 
레드햇 엔터프라이즈 리눅스
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
우분투나 데비안이나 어플라이언스
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 
|===
. 보관 파일을 다운로드하고 압축을 풉니다.
. 플랫폼과 복구해야 할 그리드 노드를 기반으로 필요한 파일을 선택하려면 해당 플랫폼에 맞는 적절한 단계를 따르세요.
+
각 플랫폼에 대한 단계에 나열된 경로는 보관 파일에 의해 설치된 최상위 디렉토리를 기준으로 합니다.

. 당신이 회복하고 있다면link:../rhel/index.html["Red Hat Enterprise Linux 시스템"] , 적절한 파일을 선택하세요.


[cols="1a,1a"]
|===
| 경로 및 파일 이름 | 설명 


| ./rpms/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| ./rpms/NLF000000.txt  a| 
제품에 대한 지원 권한을 제공하지 않는 무료 라이센스입니다.



| ./rpms/ StorageGRID-웹스케일-이미지-_버전_-SHA.rpm  a| 
RHEL 호스트에 StorageGRID 노드 이미지를 설치하기 위한 RPM 패키지입니다.



| ./rpms/ StorageGRID-웹스케일-서비스-_버전_-SHA.rpm  a| 
RHEL 호스트에 StorageGRID 호스트 서비스를 설치하기 위한 RPM 패키지입니다.



| 배포 스크립팅 도구 | 설명 


| ./rpms/configure-storagegrid.py  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./rpms/configure-sga.py  a| 
StorageGRID 어플라이언스의 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./rpms/configure-storagegrid.sample.json  a| 
다음과 함께 사용할 수 있는 구성 파일 예 `configure-storagegrid.py` 스크립트.



| ./rpms/storagegrid-ssoauth.py  a| 
Single Sign-On이 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예시입니다.  이 스크립트는 Ping Federate 통합에도 사용할 수 있습니다.



| ./rpms/configure-storagegrid.blank.json  a| 
사용할 빈 구성 파일 `configure-storagegrid.py` 스크립트.



| ./rpms/extras/ansible  a| 
StorageGRID 컨테이너 배포를 위한 RHEL 호스트를 구성하기 위한 Ansible 역할 및 플레이북의 예입니다.  필요에 따라 역할이나 플레이북을 사용자 정의할 수 있습니다.



| ./rpms/storagegrid-ssoauth-azure.py  a| 
Active Directory 또는 Ping Federate를 사용하여 SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예시입니다.



| ./rpms/storagegrid-ssoauth-azure.js  a| 
동반자가 호출하는 도우미 스크립트 `storagegrid-ssoauth-azure.py` Azure와 SSO 상호 작용을 수행하는 Python 스크립트입니다.



| ./rpms/extras/api-schemas  a| 
StorageGRID 에 대한 API 스키마.

*참고*: 업그레이드를 수행하기 전에 이러한 스키마를 사용하여 업그레이드 호환성 테스트를 위한 비프로덕션 StorageGRID 환경이 없는 경우 StorageGRID 관리 API를 사용하기 위해 작성한 모든 코드가 새 StorageGRID 릴리스와 호환되는지 확인할 수 있습니다.

|===
. 당신이 회복하고 있다면link:../ubuntu/index.html["우분투 또는 데비안 시스템"] , 적절한 파일을 선택하세요.


[cols="1a,1a"]
|===
| 경로 및 파일 이름 | 설명 


| ./debs/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| ./debs/NLF000000.txt  a| 
테스트 및 개념 증명 배포에 사용할 수 있는 비생산용 NetApp 라이선스 파일입니다.



| ./debs/storagegrid-webscale-images-버전-SHA.deb  a| 
Ubuntu 또는 Debian 호스트에 StorageGRID 노드 이미지를 설치하기 위한 DEB 패키지입니다.



| ./debs/storagegrid-웹스케일-이미지-버전-SHA.deb.md5  a| 
파일의 MD5 체크섬 `/debs/storagegrid-webscale-images-version-SHA.deb` .



| ./debs/storagegrid-웹스케일-서비스-버전-SHA.deb  a| 
Ubuntu 또는 Debian 호스트에 StorageGRID 호스트 서비스를 설치하기 위한 DEB 패키지입니다.



| 배포 스크립팅 도구 | 설명 


| ./debs/configure-storagegrid.py  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./debs/configure-sga.py  a| 
StorageGRID 어플라이언스의 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./debs/storagegrid-ssoauth.py  a| 
Single Sign-On이 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예시입니다.  이 스크립트는 Ping Federate 통합에도 사용할 수 있습니다.



| ./debs/configure-storagegrid.sample.json  a| 
다음과 함께 사용할 수 있는 구성 파일 예 `configure-storagegrid.py` 스크립트.



| ./debs/configure-storagegrid.blank.json  a| 
사용할 빈 구성 파일 `configure-storagegrid.py` 스크립트.



| ./debs/extras/ansible  a| 
StorageGRID 컨테이너 배포를 위해 Ubuntu 또는 Debian 호스트를 구성하기 위한 Ansible 역할 및 플레이북의 예입니다.  필요에 따라 역할이나 플레이북을 사용자 정의할 수 있습니다.



| ./debs/storagegrid-ssoauth-azure.py  a| 
Active Directory 또는 Ping Federate를 사용하여 SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예시입니다.



| ./debs/storagegrid-ssoauth-azure.js  a| 
동반자가 호출하는 도우미 스크립트 `storagegrid-ssoauth-azure.py` Azure와 SSO 상호 작용을 수행하는 Python 스크립트입니다.



| ./debs/extras/api-schemas  a| 
StorageGRID 에 대한 API 스키마.

*참고*: 업그레이드를 수행하기 전에 이러한 스키마를 사용하여 업그레이드 호환성 테스트를 위한 비프로덕션 StorageGRID 환경이 없는 경우 StorageGRID 관리 API를 사용하기 위해 작성한 모든 코드가 새 StorageGRID 릴리스와 호환되는지 확인할 수 있습니다.

|===
. 당신이 회복하고 있다면link:../vmware/index.html["VMware 시스템"] , 적절한 파일을 선택하세요.


[cols="1a,1a"]
|===
| 경로 및 파일 이름 | 설명 


| ./vsphere/README  a| 
StorageGRID 다운로드 파일에 포함된 모든 파일을 설명하는 텍스트 파일입니다.



| ./vsphere/NLF000000.txt  a| 
제품에 대한 지원 권한을 제공하지 않는 무료 라이센스입니다.



| ./vsphere/ NetApp-SG-버전-SHA.vmdk  a| 
그리드 노드 가상 머신을 생성하기 위한 템플릿으로 사용되는 가상 머신 디스크 파일입니다.



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
Open Virtualization Format 템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 기본 관리 노드를 배포하기 위한 것입니다.



| ./vsphere/vsphere-비-기본-관리자.ovf ./vsphere/vsphere-비-기본-관리자.mf  a| 
템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 기본이 아닌 관리 노드를 배포하기 위한 것입니다.



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 게이트웨이 노드를 배포하기 위한 것입니다.



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
템플릿 파일(`.ovf` ) 및 매니페스트 파일(`.mf` ) 가상 머신 기반 스토리지 노드를 배포하기 위한 것입니다.



| 배포 스크립팅 도구 | 설명 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
가상 그리드 노드의 배포를 자동화하는 데 사용되는 Bash 셸 스크립트입니다.



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
다음과 함께 사용할 수 있는 구성 파일 예 `deploy-vsphere-ovftool.sh` 스크립트.



| ./vsphere/configure-storagegrid.py  a| 
StorageGRID 시스템 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./vsphere/configure-sga.py  a| 
StorageGRID 어플라이언스의 구성을 자동화하는 데 사용되는 Python 스크립트입니다.



| ./vsphere/storagegrid-ssoauth.py  a| 
SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예시입니다.  이 스크립트는 Ping Federate 통합에도 사용할 수 있습니다.



| ./vsphere/configure-storagegrid.sample.json  a| 
다음과 함께 사용할 수 있는 구성 파일 예 `configure-storagegrid.py` 스크립트.



| ./vsphere/configure-storagegrid.blank.json  a| 
사용할 빈 구성 파일 `configure-storagegrid.py` 스크립트.



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
Active Directory 또는 Ping Federate를 사용하여 SSO(Single Sign-On)가 활성화된 경우 Grid Management API에 로그인하는 데 사용할 수 있는 Python 스크립트 예시입니다.



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
동반자가 호출하는 도우미 스크립트 `storagegrid-ssoauth-azure.py` Azure와 SSO 상호 작용을 수행하는 Python 스크립트입니다.



| ./vsphere/extras/api-schemas  a| 
StorageGRID 에 대한 API 스키마.

*참고*: 업그레이드를 수행하기 전에 이러한 스키마를 사용하여 업그레이드 호환성 테스트를 위한 비프로덕션 StorageGRID 환경이 없는 경우 StorageGRID 관리 API를 사용하기 위해 작성한 모든 코드가 새 StorageGRID 릴리스와 호환되는지 확인할 수 있습니다.

|===
. StorageGRID 어플라이언스 기반 시스템을 복구하는 경우 적절한 파일을 선택하세요.


[cols="1a,1a"]
|===
| 경로 및 파일 이름 | 설명 


| ./debs/storagegrid-webscale-images-버전-SHA.deb  a| 
어플라이언스에 StorageGRID 노드 이미지를 설치하기 위한 DEB 패키지입니다.



| ./debs/storagegrid-웹스케일-이미지-버전-SHA.deb.md5  a| 
파일의 MD5 체크섬 `/debs/storagegridwebscale-
images-version-SHA.deb` .

|===

NOTE: 기기 설치의 경우, 네트워크 트래픽을 피해야 하는 경우에만 이러한 파일이 필요합니다.  어플라이언스는 기본 관리 노드에서 필요한 파일을 다운로드할 수 있습니다.
