---
permalink: maintain/grid-node-decommissioning.html 
sidebar: sidebar 
keywords: storagegrid, decommission, remove grid node 
summary: 노드 해제 절차를 사용하면 하나 이상의 사이트에서 하나 이상의 그리드 노드를 제거할 수 있습니다.  기본 관리 노드를 해제할 수 없습니다. 
---
= 그리드 노드 해체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 해제 절차를 사용하면 하나 이상의 사이트에서 하나 이상의 그리드 노드를 제거할 수 있습니다.  기본 관리 노드를 해제할 수 없습니다.



== 노드를 해제할 때

다음 중 하나라도 해당되는 경우 노드 해제 절차를 사용하세요.

* 확장 시 더 큰 스토리지 노드를 추가했고, 동시에 객체를 보존하면서 하나 이상의 더 작은 스토리지 노드를 제거하려고 합니다.
+

TIP: 오래된 가전제품을 새 가전제품으로 교체하고 싶다면 다음을 고려하세요. https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["어플라이언스 노드 복제"^] 확장 시 새로운 기기를 추가한 다음 기존 기기를 폐기하는 대신.

* 총 저장 공간이 덜 필요합니다.
* 더 이상 게이트웨이 노드가 필요하지 않습니다.
* 더 이상 기본이 아닌 관리 노드가 필요하지 않습니다.
* 귀하의 그리드에는 복구하거나 다시 온라인으로 전환할 수 없는 연결이 끊긴 노드가 포함되어 있습니다.
* 그리드에 보관 노드가 포함되어 있습니다.




== 노드를 해제하는 방법

연결된 그리드 노드나 연결이 끊긴 그리드 노드를 해제할 수 있습니다.

연결된 노드 해제:: 일반적으로 그리드 노드는 StorageGRID 시스템에 연결되어 있고 모든 노드가 정상 상태일 때만 해제해야 합니다(노드 페이지와 노드 해제 페이지에 녹색 아이콘이 표시됨).
+
--
지침은 다음을 참조하세요.link:decommissioning-connected-grid-nodes.html["연결된 그리드 노드 해제"] .

--
연결이 끊긴 노드 해제:: 어떤 경우에는 현재 그리드에 연결되지 않은 그리드 노드(상태가 알 수 없거나 관리상 중단된 노드)를 해제해야 할 수도 있습니다.
+
--
지침은 다음을 참조하세요.link:decommissioning-disconnected-grid-nodes.html["연결이 끊긴 그리드 노드 해제"] .

--




== 노드를 폐기하기 전에 고려해야 할 사항

두 절차를 수행하기 전에 각 노드 유형에 대한 고려 사항을 검토하세요.

* link:considerations-for-decommissioning-admin-or-gateway-nodes.html["관리자 또는 게이트웨이 노드 해제에 대한 고려 사항"]
* link:considerations-for-decommissioning-storage-nodes.html["스토리지 노드 해체에 대한 고려 사항"]

