---
permalink: maintain/how-site-recovery-is-performed-by-technical-support.html 
sidebar: sidebar 
keywords: storagegrid, site recovery, technical support, tech support 
summary: StorageGRID 사이트 전체에 장애가 발생하거나 여러 스토리지 노드에 장애가 발생하는 경우 기술 지원팀에 문의해야 합니다.  기술 지원팀은 고객의 상황을 평가하고 복구 계획을 수립한 다음, 고객의 비즈니스 목표를 충족하고 복구 시간을 최적화하며 불필요한 데이터 손실을 방지하는 방식으로 실패한 노드나 사이트를 복구합니다. 
---
= 기술 지원이 사이트를 복구하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 사이트 전체에 장애가 발생하거나 여러 스토리지 노드에 장애가 발생하는 경우 기술 지원팀에 문의해야 합니다.  기술 지원팀은 고객의 상황을 평가하고 복구 계획을 수립한 다음, 고객의 비즈니스 목표를 충족하고 복구 시간을 최적화하며 불필요한 데이터 손실을 방지하는 방식으로 실패한 노드나 사이트를 복구합니다.


CAUTION: 사이트 복구는 기술 지원을 통해서만 수행할 수 있습니다.

StorageGRID 시스템은 다양한 장애에 대한 복원력이 뛰어나며, 많은 복구 및 유지 관리 절차를 직접 성공적으로 수행할 수 있습니다.  그러나 구체적인 단계는 상황에 따라 달라지기 때문에 간단하고 일반화된 사이트 복구 절차를 만드는 것은 어렵습니다. 예를 들어:

* *귀하의 비즈니스 목표*: StorageGRID 사이트를 완전히 잃은 후에는 비즈니스 목표를 달성하는 가장 좋은 방법을 평가해야 합니다.  예를 들어, 잃어버린 사이트를 그 자리에서 다시 구축하고 싶습니까?  손실된 StorageGRID 사이트를 새로운 위치로 교체하시겠습니까?  모든 고객의 상황은 다르므로 복구 계획은 고객의 우선순위에 맞춰 설계되어야 합니다.
* *실패의 정확한 성격*: 사이트 복구를 시작하기 전에 실패한 사이트의 노드가 손상되지 않았는지 또는 스토리지 노드에 복구 가능한 개체가 있는지 확인하세요.  유효한 데이터가 포함된 노드나 스토리지 볼륨을 다시 빌드하면 불필요한 데이터 손실이 발생할 수 있습니다.
* *활성 ILM 정책*: 그리드의 개체 복사본 수, 유형 및 위치는 활성 ILM 정책에 따라 제어됩니다.  ILM 정책의 세부 사항은 복구 가능한 데이터의 양과 복구에 필요한 구체적인 기술에 영향을 미칠 수 있습니다.
+

CAUTION: 사이트에 객체의 유일한 사본이 포함되어 있고 사이트가 손실되면 객체도 손실됩니다.

* *버킷(또는 컨테이너) 일관성*: 버킷(또는 컨테이너)에 적용된 일관성은 StorageGRID 클라이언트에게 객체 수집이 성공적이었음을 알리기 전에 모든 노드와 사이트에 객체 메타데이터를 완전히 복제하는지 여부에 영향을 미칩니다.  일관성 값이 최종 일관성을 허용하는 경우 사이트 오류로 인해 일부 개체 메타데이터가 손실되었을 수 있습니다.  이는 복구 가능한 데이터의 양과 잠재적으로 복구 절차의 세부 사항에 영향을 미칠 수 있습니다.
* *최근 변경 내역*: 복구 절차의 세부 사항은 장애 발생 당시 유지 관리 절차가 진행 중이었는지 여부나 ILM 정책에 최근 변경 사항이 적용되었는지 여부에 따라 영향을 받을 수 있습니다.  기술 지원팀은 사이트 복구를 시작하기 전에 그리드의 최근 기록과 현재 상황을 평가해야 합니다.



CAUTION: 사이트 복구는 기술 지원을 통해서만 수행할 수 있습니다.

이는 기술 지원팀이 실패한 사이트를 복구하는 데 사용하는 프로세스에 대한 일반적인 개요입니다.

. 기술 지원:
+
.. 실패에 대한 자세한 평가를 내립니다.
.. 귀사의 사업 목표를 검토하기 위해 귀사와 협력합니다.
.. 귀하의 상황에 맞는 복구 계획을 개발합니다.


. 기본 관리 노드에 장애가 발생하면 기술 지원팀에서 복구합니다.
. 기술 지원은 다음 개요에 따라 모든 스토리지 노드를 복구합니다.
+
.. 필요에 따라 스토리지 노드 하드웨어나 가상 머신을 교체합니다.
.. 실패한 사이트에 개체 메타데이터를 복원합니다.
.. 복구된 스토리지 노드에 개체 데이터를 복원합니다.
+

CAUTION: 단일 실패한 스토리지 노드에 대한 복구 절차를 사용하면 데이터 손실이 발생합니다.

+

NOTE: 사이트 전체에 장애가 발생하면 기술 지원팀은 특수 명령을 사용하여 개체와 개체 메타데이터를 성공적으로 복원합니다.



. 기술 지원팀은 다른 실패한 노드를 복구합니다.
+
객체 메타데이터와 데이터가 복구된 후, 기술 지원팀은 표준 절차를 사용하여 실패한 게이트웨이 노드나 기본이 아닌 관리 노드를 복구합니다.



.관련 정보
link:site-decommissioning.html["사이트 폐쇄"]
