---
permalink: maintain/how-your-system-is-affected-when-you-apply-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 핫픽스를 적용하면 StorageGRID 시스템에 어떤 영향이 미치는지 이해해야 합니다. 
---
= 핫픽스를 적용하면 시스템에 어떤 영향이 미치는가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
핫픽스를 적용하면 StorageGRID 시스템에 어떤 영향이 미치는지 이해해야 합니다.



== StorageGRID 핫픽스는 중단되지 않습니다.

StorageGRID 시스템은 핫픽스 프로세스 전반에 걸쳐 클라이언트 애플리케이션에서 데이터를 수집하고 검색할 수 있습니다.  동일한 유형의 모든 노드에 핫픽스를 승인하면(예: 스토리지 노드) 노드가 하나씩 다운되므로 모든 그리드 노드 또는 특정 유형의 모든 그리드 노드를 사용할 수 없는 상황이 발생하지 않습니다.

지속적인 가용성을 위해 ILM 정책에 각 개체의 여러 사본을 저장하도록 지정하는 규칙이 포함되어 있는지 확인하세요.  또한 모든 외부 S3 클라이언트가 다음 중 하나에 요청을 보내도록 구성되어 있는지 확인해야 합니다.

* 고가용성(HA) 그룹 가상 IP 주소
* 고가용성 타사 로드 밸런서
* 각 클라이언트에 대한 다중 게이트웨이 노드
* 각 클라이언트에 대한 여러 스토리지 노드




== 클라이언트 애플리케이션은 단기적인 중단을 경험할 수 있습니다.

StorageGRID 시스템은 핫픽스 프로세스 전반에 걸쳐 클라이언트 애플리케이션에서 데이터를 수집하고 검색할 수 있습니다. 그러나 핫픽스가 해당 노드에서 서비스를 다시 시작해야 하는 경우 개별 게이트웨이 노드 또는 스토리지 노드에 대한 클라이언트 연결이 일시적으로 중단될 수 있습니다.  핫픽스 프로세스가 완료되고 개별 노드에서 서비스가 재개되면 연결이 복구됩니다.

짧은 기간 동안 연결이 끊어지는 것이 용납될 수 없다면 핫픽스를 적용하기 위해 가동 중지 시간을 예약해야 할 수도 있습니다.  선택적 승인을 사용하면 특정 노드가 업데이트되는 시기를 예약할 수 있습니다.


NOTE: 핫픽스 프로세스 중에 자동 장애 조치를 제공하기 위해 여러 게이트웨이와 고가용성(HA) 그룹을 사용할 수 있습니다. 지침을 참조하세요link:../admin/configure-high-availability-group.html["고가용성 그룹 구성"] .



== 경고 및 SNMP 알림이 트리거될 수 있습니다.

서비스가 다시 시작되거나 StorageGRID 시스템이 혼합 버전 환경(일부 그리드 노드는 이전 버전을 실행하고 다른 노드는 이후 버전으로 업그레이드됨)으로 작동하는 경우 경고 및 SNMP 알림이 ​​트리거될 수 있습니다.  일반적으로 이러한 경고와 알림은 핫픽스가 완료되면 사라집니다.



== 구성 변경이 제한됩니다.

StorageGRID 에 핫픽스를 적용할 때:

* 핫픽스가 모든 노드에 적용될 때까지 그리드 구성을 변경하지 마세요(예: 그리드 네트워크 서브넷 지정 또는 보류 중인 그리드 노드 승인).
* 핫픽스가 모든 노드에 적용될 때까지 ILM 구성을 업데이트하지 마세요.

