---
permalink: maintain/linux-adding-interfaces-to-existing-node.html 
sidebar: sidebar 
keywords: add interfaces, add client network interface, add admin network interface 
summary: Linux 노드를 설치한 후 관리 네트워크나 클라이언트 네트워크에 인터페이스를 추가하려면 다음 단계를 따르세요. 
---
= Linux: 기존 노드에 관리자 또는 클라이언트 인터페이스 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux 노드를 설치한 후 관리 네트워크나 클라이언트 네트워크에 인터페이스를 추가하려면 다음 단계를 따르세요.

설치 중에 Linux 호스트의 노드 구성 파일에서 ADMIN_NETWORK_TARGET 또는 CLIENT_NETWORK_TARGET을 구성하지 않은 경우 이 절차를 사용하여 인터페이스를 추가합니다. 노드 구성 파일에 대한 자세한 내용은 Linux 운영 체제에 대한 지침을 참조하세요.

* link:../rhel/index.html["Red Hat Enterprise Linux에 StorageGRID 설치"]
* link:../ubuntu/index.html["Ubuntu 또는 Debian에 StorageGRID 설치"]


이 절차는 노드 내부가 아닌, 새로운 네트워크 할당이 필요한 노드를 호스팅하는 Linux 서버에서 수행합니다.  이 절차는 노드에 인터페이스만 추가합니다. 다른 네트워크 매개변수를 지정하려고 하면 유효성 검사 오류가 발생합니다.

주소 정보를 제공하려면 IP 변경 도구를 사용해야 합니다. 보다 link:changing-nodes-network-configuration.html["노드 네트워크 구성 변경"] .

.단계
. 노드를 호스팅하는 Linux 서버에 로그인합니다.
. 노드 구성 파일을 편집합니다. `/etc/storagegrid/nodes/_node-name_.conf` .
+

NOTE: 다른 네트워크 매개변수를 지정하지 마세요. 그렇지 않으면 검증 오류가 발생합니다.

+
.. 새로운 네트워크 대상에 대한 항목을 추가합니다. 예를 들어:
+
`CLIENT_NETWORK_TARGET = bond0.3206`

.. 선택 사항: MAC 주소에 대한 항목을 추가합니다. 예를 들어:
+
`CLIENT_NETWORK_MAC = aa:57:61:07:ea:5c`



. node validate 명령을 실행합니다.
+
`sudo storagegrid node validate _node-name_`

. 모든 검증 오류를 해결합니다.
. 노드 재로드 명령을 실행합니다.
+
`sudo storagegrid node reload _node-name_`


