---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: '다음을 사용하여 수리 작업 상태를 모니터링할 수 있습니다. `repair-data` 명령줄에서 스크립트를 실행합니다.' 
---
= 수리 데이터 작업 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음을 사용하여 수리 작업 상태를 모니터링할 수 있습니다. `repair-data` 명령줄에서 스크립트를 실행합니다.

여기에는 사용자가 수동으로 시작한 작업이나 StorageGRID 해체 절차의 일부로 자동으로 시작한 작업이 포함됩니다.


NOTE: 볼륨 복원 작업을 실행 중인 경우link:../maintain/restoring-volume.html["Grid Manager에서 작업 진행 상황을 모니터링하고 해당 작업의 기록을 확인합니다."] 대신에.

상태를 모니터링합니다 `repair-data` *복제된 데이터*, *삭제 코드화된(EC) 데이터* 또는 둘 다를 사용하는지 여부에 따라 작업이 결정됩니다.

[role="tabbed-block"]
====
.복제된 데이터
--
* 복제된 수리에 대한 예상 완료율을 얻으려면 다음을 추가합니다. `show-replicated-repair-status` repair-data 명령에 대한 옵션입니다.
+
`repair-data show-replicated-repair-status`

* 수리가 완료되었는지 확인하려면:
+
.. *노드* > *_수리 중인 스토리지 노드_* > *ILM*을 선택합니다.
.. 평가 섹션에서 속성을 검토하세요.  수리가 완료되면 *대기 - 모두* 속성은 0개의 객체를 나타냅니다.


* 수리 과정을 더 자세히 모니터링하려면:
+
.. *지원* > *도구* > *그리드 토폴로지*를 선택하세요.
.. *_grid_* > *_수리 중인 스토리지 노드_* > *LDR* > *데이터 저장소*를 선택합니다.
.. 다음 속성을 조합하여 복제된 수리가 완료되었는지 가능한 한 정확하게 확인합니다.
+

NOTE: 카산드라 불일치가 존재할 수 있으며, 실패한 수리는 추적되지 않습니다.

+
*** *시도된 수리(XRPA)*: 이 속성을 사용하여 복제된 수리의 진행 상황을 추적합니다.  이 속성은 스토리지 노드가 고위험 객체를 복구하려고 할 때마다 증가합니다.  이 속성이 현재 스캔 기간(스캔 기간 - 추정* 속성에서 제공)보다 더 오랫동안 증가하지 않으면 ILM 스캔에서 어떤 노드에서도 복구가 필요한 고위험 개체를 찾지 못했음을 의미합니다.
+

NOTE: 고위험 물건은 완전히 분실될 위험이 있는 물건입니다.  여기에는 ILM 구성을 충족하지 못하는 객체는 포함되지 않습니다.

*** *스캔 기간 - 추정(XSCM)*: 이 속성을 사용하여 이전에 수집된 개체에 정책 변경이 적용되는 시기를 추정합니다.  *시도된 복구* 속성이 현재 스캔 기간보다 더 오랫동안 증가하지 않으면 복제된 복구가 수행되었을 가능성이 높습니다.  검사 기간은 변경될 수 있습니다.  *스캔 기간 - 추정(XSCM)* 속성은 전체 그리드에 적용되며 모든 노드 스캔 기간의 최대값입니다.  그리드의 *스캔 기간 - 예상* 속성 기록을 쿼리하여 적절한 기간을 결정할 수 있습니다.






--
.삭제 코드(EC) 데이터
--
삭제된 데이터의 복구를 모니터링하고 실패했을 수 있는 요청을 다시 시도하려면 다음을 수행합니다.

. 삭제된 데이터 복구 상태를 확인합니다.
+
** *지원* > *도구* > *측정항목*을 선택하면 현재 작업의 예상 완료 시간과 완료율을 볼 수 있습니다. 그런 다음 Grafana 섹션에서 *EC 개요*를 선택합니다. *Grid EC 작업 예상 완료 시간* 및 *Grid EC 작업 완료율* 대시보드를 살펴보세요.
** 이 명령을 사용하여 특정 상태를 확인하세요. `repair-data` 작업:
+
`repair-data show-ec-repair-status --repair-id repair ID`

** 이 명령을 사용하여 모든 수리 내용을 나열합니다.
+
`repair-data show-ec-repair-status`

+
출력에는 다음 정보가 나열됩니다. `repair ID` , 이전에 진행 중이거나 현재 진행 중인 모든 수리에 대해.



. 출력에 수리 작업이 실패한 것으로 표시되면 다음을 사용하십시오. `--repair-id` 수리를 다시 시도하는 옵션입니다.
+
이 명령은 복구 ID 6949309319275667690을 사용하여 실패한 노드 복구를 다시 시도합니다.

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
이 명령은 복구 ID 6949309319275667690을 사용하여 실패한 볼륨 복구를 다시 시도합니다.

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====