---
permalink: maintain/powering-off-and-on-all-nodes-in-grid.html 
sidebar: sidebar 
keywords: storagegrid, recover, power nodes, power on nodes, power off nodes, power down nodes 
summary: 예를 들어, 데이터 센터를 이전하는 경우 StorageGRID 시스템 전체를 종료해야 할 수도 있습니다.  이러한 단계에서는 제어된 종료 및 시작을 수행하기 위해 권장되는 순서에 대한 개략적인 개요를 제공합니다. 
---
= 그리드의 모든 노드 전원을 끄고 켜세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
예를 들어, 데이터 센터를 이전하는 경우 StorageGRID 시스템 전체를 종료해야 할 수도 있습니다.  이러한 단계에서는 제어된 종료 및 시작을 수행하기 위해 권장되는 순서에 대한 개략적인 개요를 제공합니다.

사이트 또는 그리드의 모든 노드의 전원을 끄면 스토리지 노드가 오프라인 상태인 동안 수집된 개체에 액세스할 수 없습니다.



== 서비스를 중지하고 그리드 노드를 종료합니다.

StorageGRID 시스템의 전원을 끄려면 먼저 각 그리드 노드에서 실행 중인 모든 서비스를 중지한 다음 모든 VMware 가상 머신, 컨테이너 엔진 및 StorageGRID 어플라이언스를 종료해야 합니다.

.이 작업에 관하여
먼저 관리 노드와 게이트웨이 노드의 서비스를 중지한 다음, 스토리지 노드의 서비스를 중지합니다.

이 접근 방식을 사용하면 기본 관리 노드를 사용하여 다른 그리드 노드의 상태를 가능한 한 오랫동안 모니터링할 수 있습니다.


NOTE: 단일 호스트에 두 개 이상의 그리드 노드가 포함된 경우 해당 호스트의 모든 노드를 중지할 때까지 호스트를 종료하지 마세요.  호스트에 기본 관리 노드가 포함되어 있는 경우 해당 호스트를 마지막으로 종료합니다.


NOTE: 필요한 경우 다음을 수행할 수 있습니다.link:linux-migrating-grid-node-to-new-host.html["한 Linux 호스트에서 다른 호스트로 노드 마이그레이션"] 그리드의 기능이나 가용성에 영향을 주지 않고 호스트 유지 관리를 수행합니다.

.단계
. 모든 클라이언트 애플리케이션이 그리드에 액세스하는 것을 중지합니다.
. [[log_in_to_gn]]각 게이트웨이 노드에 로그인하세요:
+
.. 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.


+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .

. [[stop_all_services]]노드에서 실행 중인 모든 서비스를 중지합니다. `service servermanager stop`
+
서비스를 종료하는 데 최대 15분이 걸릴 수 있으며, 종료 과정을 모니터링하려면 시스템에 원격으로 로그인해야 할 수도 있습니다.

. 이전 두 단계를 반복하여 모든 스토리지 노드와 기본이 아닌 관리 노드에서 서비스를 중지합니다.
+
이러한 노드의 서비스는 어떤 순서로든 중지할 수 있습니다.

+

NOTE: 당신이 발행하는 경우 `service servermanager stop` 어플라이언스 스토리지 노드에서 서비스를 중지하는 명령을 사용하려면 어플라이언스의 전원을 껐다가 다시 켜서 노드를 다시 시작해야 합니다.

. 기본 관리 노드의 경우 다음 단계를 반복합니다.<<log_in_to_gn,노드에 로그인>> 그리고<<stop_all_services,노드의 모든 서비스 중지>> .
. Linux 호스트에서 실행되는 노드의 경우:
+
.. 호스트 운영체제에 로그인합니다.
.. 노드를 중지합니다. `storagegrid node stop`
.. 호스트 운영체제를 종료합니다.


. VMware 가상 머신에서 실행 중인 노드와 어플라이언스 스토리지 노드의 경우 shutdown 명령을 실행합니다. `shutdown -h now`
+
결과에 관계없이 이 단계를 수행하십시오. `service servermanager stop` 명령.

+
어플라이언스의 경우, 이 명령은 컴퓨트 컨트롤러를 종료하지만 어플라이언스의 전원은 계속 켜져 있습니다.  다음 단계를 완료해야 합니다.

. 어플라이언스 노드가 있는 경우 해당 어플라이언스에 맞는 단계를 따르세요.
+
[role="tabbed-block"]
====
.SG110 또는 SG1100
--
.. 기기의 전원을 끕니다.
.. 파란색 전원 LED가 꺼질 때까지 기다리세요.


--
.SG100 또는 SG1000
--
.. 기기의 전원을 끕니다.
.. 파란색 전원 LED가 꺼질 때까지 기다리세요.


--
.SG6160
--
.. SG6100-CN 저장 컨트롤러의 전원을 끕니다.
.. SG6100-CN 스토리지 컨트롤러의 파란색 전원 LED가 꺼질 때까지 기다리세요.


--
.SGF6112
--
.. 기기의 전원을 끕니다.
.. 파란색 전원 LED가 꺼질 때까지 기다리세요.


--
.SG6000
--
.. 스토리지 컨트롤러 뒷면의 녹색 캐시 활성 LED가 꺼질 때까지 기다리세요.
+
캐시된 데이터를 드라이브에 써야 할 때 이 LED가 켜집니다.  전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

.. 기기의 전원을 끄고 파란색 전원 LED가 꺼질 때까지 기다리세요.


--
.SG5800
--
.. 스토리지 컨트롤러 뒷면의 녹색 캐시 활성 LED가 꺼질 때까지 기다리세요.
+
캐시된 데이터를 드라이브에 써야 할 때 이 LED가 켜집니다.  전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

.. SANtricity System Manager 홈페이지에서 *진행 중인 작업 보기*를 선택합니다.
.. 다음 단계로 넘어가기 전에 모든 작업이 완료되었는지 확인하세요.
.. 컨트롤러 선반의 두 전원 스위치를 모두 끄고 컨트롤러 선반의 모든 LED가 꺼질 때까지 기다립니다.


--
.SG5700
--
.. 스토리지 컨트롤러 뒷면의 녹색 캐시 활성 LED가 꺼질 때까지 기다리세요.
+
캐시된 데이터를 드라이브에 써야 할 때 이 LED가 켜집니다.  전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

.. 기기의 전원을 끄고 모든 LED와 7세그먼트 디스플레이 활동이 멈출 때까지 기다리세요.


--
====
. 필요한 경우 명령 셸에서 로그아웃합니다. `exit`
+
StorageGRID 그리드는 현재 종료되었습니다.





== 그리드 노드 시작


CAUTION: 전체 그리드가 15일 이상 중단된 경우 그리드 노드를 시작하기 전에 기술 지원팀에 문의해야 합니다.  Cassandra 데이터를 재구축하는 복구 절차를 시도하지 마세요.  그렇게 하면 데이터가 손실될 수 있습니다.

가능하다면 다음 순서대로 그리드 노드의 전원을 켜세요.

* 먼저 관리자 노드에 전원을 공급하세요.
* 게이트웨이 노드에 마지막으로 전원을 공급합니다.



NOTE: 호스트에 여러 개의 그리드 노드가 포함된 경우 호스트의 전원을 켜면 노드가 자동으로 다시 온라인 상태가 됩니다.

.단계
. 기본 관리 노드와 기본이 아닌 모든 관리 노드의 호스트 전원을 켭니다.
+

NOTE: 스토리지 노드가 다시 시작될 때까지 관리 노드에 로그인할 수 없습니다.

. 모든 스토리지 노드의 호스트 전원을 켭니다.
+
이 노드의 전원은 원하는 순서대로 켤 수 있습니다.

. 모든 게이트웨이 노드의 호스트 전원을 켭니다.
. 그리드 관리자에 Sign in .
. *노드*를 선택하고 그리드 노드의 상태를 모니터링합니다. 노드 이름 옆에 알림 아이콘이 없는지 확인하세요.


.관련 정보
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["SGF6112 및 SG6160 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["SG110 및 SG1100 서비스 기기"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["SG100 및 SG1000 서비스 기기"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["SG6000 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["SG5800 스토리지 어플라이언스"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["SG5700 스토리지 어플라이언스"^]

