---
permalink: maintain/rebooting-grid-node-from-grid-manager.html 
sidebar: sidebar 
keywords: reboot grid node, tasks tab 
summary: 노드 페이지의 작업 탭에서 개별 그리드 노드를 재부팅할 수 있습니다. 
---
= 작업 탭에서 그리드 노드를 재부팅합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 페이지의 작업 탭에서 개별 그리드 노드를 재부팅할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"] .
* 프로비저닝 암호가 있습니다.
* 기본 관리 노드나 스토리지 노드를 재부팅하는 경우 다음 고려 사항을 검토해야 합니다.
+
** 기본 관리 노드를 재부팅하면 브라우저가 일시적으로 Grid Manager에 액세스할 수 없게 됩니다.
** 특정 사이트에서 두 개 이상의 스토리지 노드를 재부팅하는 경우 재부팅 기간 동안 특정 개체에 액세스하지 못할 수 있습니다.  이 문제는 ILM 규칙이 *이중 커밋* 수집 옵션을 사용하는 경우(또는 규칙이 *균형*을 지정하고 필요한 모든 복사본을 즉시 생성할 수 없는 경우) 발생할 수 있습니다.  이 경우 StorageGRID 새로 수집된 객체를 동일한 사이트의 두 스토리지 노드에 커밋하고 나중에 ILM을 평가합니다.
** 스토리지 노드가 재부팅되는 동안 모든 개체에 액세스할 수 있도록 하려면 노드를 재부팅하기 약 1시간 전에 사이트에서 개체 수집을 중지하세요.




.이 작업에 관하여
StorageGRID 그리드 노드를 재부팅하면 다음을 실행합니다. `reboot` 노드에서 명령을 실행하면 노드가 종료되고 다시 시작됩니다.  모든 서비스가 자동으로 다시 시작됩니다.

* VMware 노드를 재부팅하면 가상 머신도 재부팅됩니다.
* Linux 노드를 재부팅하면 컨테이너도 재부팅됩니다.
* StorageGRID Appliance 노드를 재부팅하면 컴퓨팅 컨트롤러도 재부팅됩니다.



TIP: 두 개 이상의 노드를 재부팅해야 하는 경우 다음을 사용할 수 있습니다.link:../maintain/rolling-reboot-procedure.html["롤링 재부팅 절차"] .

.단계
. *노드*를 선택하세요.
. 재부팅할 그리드 노드를 선택하세요.
. *작업* 탭을 선택하세요.
. *재부팅*을 선택하세요.
+
확인 대화 상자가 나타납니다.  기본 관리 노드를 재부팅하는 경우 서비스가 중지되면 브라우저와 Grid Manager의 연결이 일시적으로 끊어진다는 것을 알려주는 확인 대화 상자가 나타납니다.

. 프로비저닝 암호를 입력하고 *확인*을 선택합니다.
. 노드가 재부팅될 때까지 기다리세요.
+
서비스가 종료되는 데 시간이 걸릴 수 있습니다.

+
노드가 재부팅되면 노드 페이지에 해당 노드에 회색(관리상 다운) 아이콘이 나타납니다.  모든 서비스가 다시 시작되고 노드가 그리드에 성공적으로 연결되면 노드 페이지에 정상 상태(노드 이름 왼쪽에 아이콘 없음)가 표시되어 활성화된 알림이 없고 노드가 그리드에 연결되었음을 나타냅니다.


