---
permalink: maintain/recovering-from-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, primary admin node failure 
summary: '기본 관리 노드 장애로부터 복구하려면 특정 작업 세트를 완료해야 합니다.  기본 관리 노드는 그리드에 대한 구성 관리 노드(CMN) 서비스를 호스팅합니다.' 
---
= 기본 관리 노드 오류에서 복구
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 관리 노드 장애로부터 복구하려면 특정 작업 세트를 완료해야 합니다.  기본 관리 노드는 그리드의 CMN(구성 관리 노드) 서비스를 호스팅합니다.


CAUTION: 오류가 발생한 기본 관리 노드는 즉시 수리하거나 교체해야 합니다. 그렇지 않으면 그리드가 새 객체를 수집하는 기능을 잃을 수 있습니다.  정확한 기간은 객체 수집 속도에 따라 달라집니다. 그리드의 시간 범위를 더 정확하게 평가해야 하는 경우 기술 지원팀에 문의하세요.

기본 관리 노드의 구성 관리 노드(CMN) 서비스는 그리드에 대한 개체 식별자 블록을 발행하는 역할을 합니다.  이러한 식별자는 객체가 수집될 때 객체에 할당됩니다.  식별자를 사용할 수 없으면 새로운 객체를 수집할 수 없습니다.  CMN을 사용할 수 없는 동안에도 개체 수집은 계속될 수 있습니다. 약 1개월 분의 식별자가 그리드에 캐시되어 있기 때문입니다.  그러나 캐시된 식별자가 모두 소진된 후에는 새로운 객체를 추가할 수 없습니다.

기본 관리 노드를 복구하려면 다음 단계를 따르세요.

. link:copying-audit-logs-from-failed-primary-admin-node.html["실패한 기본 관리 노드에서 감사 로그 복사"]
. link:replacing-primary-admin-node.html["기본 관리 노드 교체"]
. link:configuring-replacement-primary-admin-node.html["교체 기본 관리 노드 구성"]
. link:assess-hotfix-requirement-during-primary-admin-node-recovery.html["복구된 기본 관리 노드에 핫픽스 요구 사항이 있는지 확인합니다."]
. link:restoring-audit-log-on-recovered-primary-admin-node.html["복구된 기본 관리 노드에서 감사 로그를 복원합니다."]
. link:restoring-admin-node-database-primary-admin-node.html["기본 관리 노드를 복구할 때 관리 노드 데이터베이스를 복원합니다."]
. link:restoring-prometheus-metrics-primary-admin-node.html["기본 관리 노드를 복구할 때 Prometheus 메트릭 복원"]

