---
permalink: maintain/recovering-from-storage-node-failures.html 
sidebar: sidebar 
keywords: recover, storage node failure, Reaper 
summary: 실패한 스토리지 노드를 복구하는 절차는 실패 유형과 실패한 스토리지 노드의 유형에 따라 달라집니다. 
---
= 스토리지 노드 오류 복구
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실패한 스토리지 노드를 복구하는 절차는 실패 유형과 실패한 스토리지 노드의 유형에 따라 달라집니다.

이 표를 사용하여 실패한 스토리지 노드에 대한 복구 절차를 선택합니다.

[cols="1a,1a,1a"]
|===
| 문제 | 행동 | 노트 


 a| 
* 두 개 이상의 스토리지 노드가 실패했습니다.
* 스토리지 노드 장애 또는 복구 후 15일 이내에 두 번째 스토리지 노드가 장애가 발생했습니다.
+
여기에는 다른 스토리지 노드의 복구가 진행 중인 동안 스토리지 노드에 오류가 발생하는 경우가 포함됩니다.


 a| 
기술 지원팀에 문의하세요.
 a| 
두 개 이상의 스토리지 노드를 복구하거나 15일 이내에 두 개 이상의 스토리지 노드를 복구하면 Cassandra 데이터베이스의 무결성에 영향을 미쳐 데이터 손실이 발생할 수 있습니다.

기술 지원팀은 두 번째 스토리지 노드의 복구를 시작하기에 안전한 시기를 결정할 수 있습니다.

*참고*: ADC 서비스를 포함하는 두 개 이상의 스토리지 노드에 사이트에서 장애가 발생하면 해당 사이트에 대한 보류 중인 플랫폼 서비스 요청이 모두 손실됩니다.



 a| 
사이트의 두 개 이상의 스토리지 노드가 실패했거나 전체 사이트가 실패했습니다.
 a| 
기술 지원팀에 문의하세요. 사이트 복구 절차를 수행해야 할 수도 있습니다.
 a| 
기술 지원팀은 귀하의 상황을 평가하고 복구 계획을 수립합니다. 보다 link:how-site-recovery-is-performed-by-technical-support.html["기술 지원이 사이트를 복구하는 방법"] .



 a| 
어플라이언스 스토리지 노드에 오류가 발생했습니다.
 a| 
link:recovering-storagegrid-appliance-storage-node.html["어플라이언스 스토리지 노드 복구"]
 a| 
어플라이언스 스토리지 노드의 복구 절차는 모든 장애에 대해 동일합니다.



 a| 
하나 이상의 저장 볼륨이 실패했지만 시스템 드라이브는 손상되지 않았습니다.
 a| 
link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["시스템 드라이브가 손상되지 않은 스토리지 볼륨 오류에서 복구"]
 a| 
이 절차는 소프트웨어 기반 스토리지 노드에 사용됩니다.



 a| 
시스템 드라이브에 오류가 발생했습니다.
 a| 
link:reviewing-warnings-for-system-drive-recovery.html["시스템 드라이브 오류 복구"]
 a| 
노드 교체 절차는 배포 플랫폼과 스토리지 볼륨에 오류가 발생했는지 여부에 따라 달라집니다.

|===

NOTE: 일부 StorageGRID 복구 절차에서는 Reaper를 사용하여 Cassandra 복구를 처리합니다.  관련 또는 필요한 서비스가 시작되면 수리는 자동으로 이루어집니다.  스크립트 출력에 "reaper" 또는 "Cassandra repair"가 언급되는 것을 볼 수 있습니다.  복구에 실패했다는 오류 메시지가 나타나면 오류 메시지에 표시된 명령을 실행하세요.
