---
permalink: maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html 
sidebar: sidebar 
keywords: storagegrid, recover, maintenance, maintain, failed storage volumes, failed volumes, cassandra, cassandra rebuild, rebuild cassandra, cassandra database 
summary: 시스템에서 필요하다고 판단하는 경우, 실패한 스토리지 볼륨의 스토리지를 재포맷하고 다시 마운트하고 스토리지 노드에서 Cassandra 데이터베이스를 재구축하는 스크립트를 실행해야 합니다. 
---
= 실패한 스토리지 볼륨을 복구하고 Cassandra 데이터베이스를 재구축합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템에서 필요하다고 판단하는 경우, 실패한 스토리지 볼륨의 스토리지를 재포맷하고 다시 마운트하고 스토리지 노드에서 Cassandra 데이터베이스를 재구축하는 스크립트를 실행해야 합니다.

.시작하기 전에
* 당신은 가지고있다 `Passwords.txt` 파일.
* 서버의 시스템 드라이브는 손상되지 않았습니다.
* 고장의 원인이 확인되었으며, 필요한 경우 교체용 저장 하드웨어를 이미 구입했습니다.
* 교체용 저장소의 전체 크기는 원래 저장소와 동일합니다.
* 스토리지 노드 해체가 진행 중이 아닌지 확인했거나 노드 해체 절차를 일시 중지했습니다. (그리드 관리자에서 *유지관리* > *작업* > *해제*를 선택합니다.)
* 확장이 진행 중이 아님을 확인했습니다. (그리드 관리자에서 *유지관리* > *작업* > *확장*을 선택합니다.)
* 당신은 가지고있다link:reviewing-warnings-about-storage-volume-recovery.html["저장 볼륨 복구에 대한 경고를 검토했습니다."] .


.단계
. 필요에 따라, 이전에 식별하고 마운트 해제한 실패한 스토리지 볼륨과 연관된 실패한 물리적 또는 가상 스토리지를 교체합니다.
+
이 단계에서는 볼륨을 다시 마운트하지 마세요.  저장소가 다시 마운트되어 추가됩니다. `/etc/fstab` 나중의 단계에서.

. 그리드 관리자에서 *NODES*로 이동하세요. `*appliance Storage Node*` > *하드웨어*. 해당 페이지의 StorageGRID Appliance 섹션에서 Storage RAID 모드가 정상인지 확인하세요.
. 실패한 스토리지 노드에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. 텍스트 편집기(vi 또는 vim)를 사용하여 실패한 볼륨을 삭제합니다. `/etc/fstab` 파일을 선택한 다음 파일을 저장합니다.
+

NOTE: 실패한 볼륨에 대한 주석 처리 `/etc/fstab` 파일이 부족합니다.  볼륨을 삭제해야 합니다. `fstab` 복구 프로세스는 모든 라인이 다음과 같은지 확인합니다. `fstab` 파일이 마운트된 파일 시스템과 일치합니다.

. 실패한 모든 저장 볼륨을 다시 포맷하고 필요한 경우 Cassandra 데이터베이스를 다시 빌드합니다.  입력하다: `reformat_storage_block_devices.rb`
+
** 스토리지 볼륨 0이 마운트 해제되면 Cassandra 서비스가 중지되었음을 나타내는 프롬프트와 메시지가 표시됩니다.
** 필요한 경우 Cassandra 데이터베이스를 다시 빌드하라는 메시지가 표시됩니다.
+
*** 경고를 검토하세요.  위 사항 중 어느 것도 해당되지 않으면 Cassandra 데이터베이스를 다시 빌드하세요.  입력: *y*
*** 두 개 이상의 스토리지 노드가 오프라인 상태이거나 지난 15일 동안 다른 스토리지 노드가 재구축된 경우. 입력: *n*
+
스크립트는 Cassandra를 다시 빌드하지 않고 종료됩니다. 기술 지원팀에 문의하세요.



** 스토리지 노드의 각 rangedb 드라이브에 대해 다음 질문이 표시될 때: `Reformat the rangedb drive _<name>_ (device _<major number>:<minor number>_)? [y/n]?` 다음 응답 중 하나를 입력하세요.
+
*** *y* 오류가 있는 드라이브를 다시 포맷합니다.  이렇게 하면 저장 볼륨이 재포맷되고 재포맷된 저장 볼륨이 다음에 추가됩니다. `/etc/fstab` 파일.
*** *n* 드라이브에 오류가 없고 다시 포맷하지 않으려는 경우.
+

NOTE: *n*을 선택하면 스크립트가 종료됩니다.  드라이브를 마운트하세요(드라이브에 있는 데이터가 보존되어야 하는데 실수로 드라이브가 마운트 해제된 경우) 또는 드라이브를 제거하세요.  그런 다음 실행하세요 `reformat_storage_block_devices.rb` 다시 명령을 내리세요.

+

NOTE: 일부 StorageGRID 복구 절차에서는 Reaper를 사용하여 Cassandra 복구를 처리합니다.  관련 또는 필요한 서비스가 시작되면 수리는 자동으로 이루어집니다.  스크립트 출력에 "reaper" 또는 "Cassandra repair"가 언급되는 것을 볼 수 있습니다.  복구에 실패했다는 오류 메시지가 나타나면 오류 메시지에 표시된 명령을 실행하세요.

+
다음 예제 출력에서 드라이브 `/dev/sdf` 다시 포맷해야 하며 Cassandra는 다시 빌드할 필요가 없습니다.

+
[listing]
----
root@DC1-S1:~ # reformat_storage_block_devices.rb
Formatting devices that are not in use...
Skipping in use device /dev/sdc
Skipping in use device /dev/sdd
Skipping in use device /dev/sde
Reformat the rangedb drive /dev/sdf (device 8:64)? [Y/n]? y
Successfully formatted /dev/sdf with UUID b951bfcb-4804-41ad-b490-805dfd8df16c
All devices processed
Running: /usr/local/ldr/setup_rangedb.sh 12368435
Cassandra does not need rebuilding.
Starting services.
Informing storage services of new volume

Reformatting done.  Now do manual steps to
restore copies of data.
----






저장 볼륨이 재포맷되고 다시 마운트되고 필요한 Cassandra 작업이 완료되면 다음을 수행할 수 있습니다.link:../maintain/restoring-volume.html["Grid Manager를 사용하여 개체 데이터 복원"] .
