---
permalink: maintain/recovering-from-storage-volume-failure-where-system-drive-is-intact.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage volume failure, volume failure, system drive intact 
summary: 스토리지 노드의 하나 이상의 스토리지 볼륨에 오류가 발생했지만 시스템 드라이브는 손상되지 않은 경우 소프트웨어 기반 스토리지 노드를 복구하려면 일련의 작업을 완료해야 합니다.  스토리지 볼륨에만 오류가 발생한 경우에도 스토리지 노드는 StorageGRID 시스템에서 계속 사용할 수 있습니다. 
---
= 시스템 드라이브가 손상되지 않은 스토리지 볼륨 오류에서 복구
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드의 하나 이상의 스토리지 볼륨에 오류가 발생했지만 시스템 드라이브는 손상되지 않은 경우 소프트웨어 기반 스토리지 노드를 복구하려면 일련의 작업을 완료해야 합니다.  스토리지 볼륨에만 오류가 발생한 경우에도 스토리지 노드는 StorageGRID 시스템에서 계속 사용할 수 있습니다.


NOTE: 이 복구 절차는 소프트웨어 기반 스토리지 노드에만 적용됩니다.  어플라이언스 스토리지 노드에서 스토리지 볼륨에 오류가 발생한 경우 대신 어플라이언스 절차를 사용하세요.link:recovering-storagegrid-appliance-storage-node.html["어플라이언스 스토리지 노드 복구"] .

이 복구 절차에는 다음 작업이 포함됩니다.

* link:reviewing-warnings-about-storage-volume-recovery.html["저장소 볼륨 복구에 대한 경고 검토"]
* link:identifying-and-unmounting-failed-storage-volumes.html["실패한 스토리지 볼륨 식별 및 마운트 해제"]
* link:recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["볼륨을 복구하고 Cassandra 데이터베이스를 다시 빌드합니다."]
* link:restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["객체 데이터 복원"]
* link:checking-storage-state-after-recovering-storage-volumes.html["저장 상태 확인"]

