---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: 로드 밸런서 서비스에 대한 엔드포인트를 구성하고 포트 리맵의 매핑 대상 포트로 이미 구성된 포트를 사용하려는 경우, 먼저 기존 포트 리맵을 제거해야 엔드포인트가 유효하지 않습니다.  충돌하는 리매핑 포트가 있는 각 관리 노드와 게이트웨이 노드에서 스크립트를 실행하여 노드의 모든 포트 리매핑을 제거해야 합니다. 
---
= 포트 리맵 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로드 밸런서 서비스에 대한 엔드포인트를 구성하고 포트 리맵의 매핑 대상 포트로 이미 구성된 포트를 사용하려는 경우, 먼저 기존 포트 리맵을 제거해야 엔드포인트가 유효하지 않습니다.  충돌하는 리매핑 포트가 있는 각 관리 노드와 게이트웨이 노드에서 스크립트를 실행하여 노드의 모든 포트 리매핑을 제거해야 합니다.

.이 작업에 관하여
이 절차를 수행하면 모든 포트 리맵이 제거됩니다.  일부 리맵을 보관해야 하는 경우 기술 지원팀에 문의하세요.

로드 밸런서 엔드포인트 구성에 대한 자세한 내용은 다음을 참조하세요.link:../admin/configuring-load-balancer-endpoints.html["로드 밸런서 엔드포인트 구성"] .


NOTE: 포트 리맵을 통해 클라이언트 액세스가 가능한 경우, 서비스 손실을 방지하기 위해 클라이언트를 재구성하여 다른 포트를 로드 밸런서 엔드포인트로 사용합니다.  그렇지 않으면 포트 매핑을 제거하면 클라이언트 액세스가 손실되므로 이에 대한 적절한 일정을 잡아야 합니다.


NOTE: 이 절차는 베어 메탈 호스트에 컨테이너로 배포된 StorageGRID 시스템에서는 작동하지 않습니다. 지침을 참조하세요link:removing-port-remaps-on-bare-metal-hosts.html["베어 메탈 호스트에서 포트 리맵 제거"] .

.단계
. 노드에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh -p 8022 admin@node_IP`
+
포트 8022는 기본 OS의 SSH 포트이고, 포트 22는 StorageGRID 실행하는 컨테이너 엔진의 SSH 포트입니다.

.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. 다음 스크립트를 실행합니다. `remove-port-remap.sh`
. 노드를 재부팅합니다. `reboot`
. 명령 셸에서 로그아웃합니다. `exit`
. 충돌하는 재매핑 포트가 있는 각 관리 노드와 게이트웨이 노드에서 이 단계를 반복합니다.

