---
permalink: maintain/rename-grid-site-node-overview.html 
sidebar: sidebar 
keywords: rename grid, rename site, rename node, display name, system name 
summary: 필요에 따라 전체 그리드, 각 사이트 및 각 노드에 대해 그리드 관리자에 표시되는 표시 이름을 변경할 수 있습니다.  표시 이름을 필요할 때마다 안전하게 업데이트할 수 있습니다. 
---
= 이름 바꾸기 절차를 사용하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
필요에 따라 전체 그리드, 각 사이트 및 각 노드에 대해 그리드 관리자에 표시되는 표시 이름을 변경할 수 있습니다.  표시 이름을 필요할 때마다 안전하게 업데이트할 수 있습니다.



== 이름 변경 절차는 무엇입니까?

StorageGRID 처음 설치할 때 그리드, 각 사이트, 각 노드의 이름을 지정합니다.  이러한 초기 이름은 _시스템 이름_으로 알려져 있으며 StorageGRID 전체에서 처음에 표시되는 이름입니다.

시스템 이름은 내부 StorageGRID 작업에 필요하며 변경할 수 없습니다. 하지만 이름 바꾸기 절차를 사용하면 그리드, 각 사이트 및 각 노드에 대한 새로운 _표시 이름_을 정의할 수 있습니다.  이러한 표시 이름은 기본 시스템 이름 대신(또는 어떤 경우에는 기본 시스템 이름에 추가로) 다양한 StorageGRID 위치에 나타납니다.

이름 바꾸기 절차를 사용하여 오타를 수정하고, 다른 명명 규칙을 구현하거나, 사이트와 모든 노드가 이전되었음을 나타냅니다.  시스템 이름과 달리 표시 이름은 StorageGRID 작업에 영향을 주지 않고 필요할 때마다 업데이트할 수 있습니다.



== 시스템 이름과 표시 이름은 어디에 표시되나요?

다음 표는 StorageGRID 사용자 인터페이스와 StorageGRID 파일에서 시스템 이름과 표시 이름이 표시되는 위치를 요약한 것입니다.

[cols="2a,2a,3a"]
|===
| 위치 | 시스템 이름 | 표시 이름 


 a| 
그리드 관리자 페이지
 a| 
항목 이름이 변경되지 않는 한 표시됩니다.
 a| 
항목 이름이 변경되면 시스템 이름 대신 다음 위치에 표시됩니다.

* 계기반
* 노드 페이지
* 고가용성 그룹, 로드 밸런서 엔드포인트, VLAN 인터페이스, 키 관리 서버, 그리드 비밀번호 및 방화벽 제어를 위한 구성 페이지
* 알림
* 스토리지 풀 정의
* 객체 메타데이터 조회 페이지
* 업그레이드, 핫픽스, SANtricity OS 업그레이드, 서비스 중단, 확장, 복구 및 객체 존재 확인을 포함한 유지 관리 절차와 관련된 페이지
* 지원 페이지(로그 및 진단)
* 관리 노드 세부 정보를 위한 표의 관리 노드 호스트 이름 옆에 있는 단일 로그인 페이지




 a| 
*노드* > 노드에 대한 *개요* 탭
 a| 
항상 표시됨
 a| 
항목 이름이 변경된 경우에만 표시됩니다.



 a| 
그리드 관리자의 레거시 페이지(예: *지원* > *그리드 토폴로지*)
 a| 
표시됨
 a| 
표시되지 않음



 a| 
*노드 상태* API
 a| 
항상 돌아왔습니다
 a| 
항목 이름이 변경된 경우에만 반환됩니다.



 a| 
SSH를 사용하여 노드에 액세스할 때 프롬프트 표시
 a| 
항목 이름이 변경되지 않는 한 기본 이름으로 표시됩니다.

`admin@SYSTEM-NAME: ~ $`

항목 이름이 변경될 때 괄호 안에 포함됨:

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`
 a| 
항목 이름이 변경될 때 기본 이름으로 표시됩니다.

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



 a| 
`Passwords.txt`복구 패키지의 파일
 a| 
로 표시됨 `Server Name`
 a| 
로 표시됨 `Display Name`



 a| 
`/etc/hosts`모든 노드의 파일

예를 들어:

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`
 a| 
항상 두 번째 열에 표시됩니다.
 a| 
항목 이름이 변경되면 네 번째 열에 표시됩니다.



 a| 
`topology-display-names.json`AutoSupport 데이터와 함께 포함됨
 a| 
포함되지 않음
 a| 
항목의 이름이 변경되지 않은 경우 비어 있습니다. 그렇지 않은 경우 그리드, 사이트 및 노드 ID를 표시 이름에 매핑합니다.

|===


== 표시 이름 요구 사항

이 절차를 사용하기 전에 표시 이름에 대한 요구 사항을 검토하세요.



=== 노드의 표시 이름

노드의 표시 이름은 다음 규칙을 따라야 합니다.

* StorageGRID 시스템 전체에서 고유해야 합니다.
* StorageGRID 시스템의 다른 항목에 대한 시스템 이름과 동일할 수 없습니다.
* 최소 1자, 최대 32자까지 입력 가능합니다.
* 숫자, 하이픈(-), 대문자, 소문자를 포함할 수 있습니다.
* 문자나 숫자로 시작하거나 끝날 수 있지만, 하이픈으로 시작하거나 끝날 수는 없습니다.
* 모든 것을 숫자로 표현할 수는 없습니다.
* 대소문자를 구분하지 않습니다.  예를 들어, `DC1-ADM` 그리고 `dc1-adm` 중복으로 간주됩니다.


이전에 다른 노드에서 사용했던 표시 이름으로 노드의 이름을 바꿀 수 있지만, 이름 변경으로 인해 표시 이름이나 시스템 이름이 중복되지 않아야 합니다.



=== 그리드 및 사이트의 표시 이름

그리드와 사이트의 표시 이름은 다음과 같은 예외를 제외하고 동일한 규칙을 따릅니다.

* 공백을 포함할 수 있습니다.
* 다음과 같은 특수 문자를 포함할 수 있습니다. `= - _ : , . @ !`
* 하이픈을 포함한 특수 문자로 시작하고 끝날 수 있습니다.
* 숫자나 특수문자만 가능합니다.




== 표시 이름 모범 사례

여러 항목의 이름을 바꾸려는 경우 이 절차를 사용하기 전에 일반적인 명명 체계를 문서화하세요.  고유하고, 일관성 있고, 한눈에 이해하기 쉬운 이름을 만드는 시스템을 고안해 보세요.

조직의 요구 사항에 맞는 명명 규칙을 사용할 수 있습니다.  포함할 내용에 대한 기본적인 제안은 다음과 같습니다.

* *사이트 표시기*: 사이트가 여러 개 있는 경우 각 노드 이름에 사이트 코드를 추가합니다.
* *노드 유형*: 노드 이름은 일반적으로 노드의 유형을 나타냅니다.  다음과 같은 약어를 사용할 수 있습니다. `s` , `adm` , 그리고 `gw` (저장 노드, 관리 노드, 게이트웨이 노드).
* *노드 번호*: 사이트에 특정 유형의 노드가 두 개 이상 있는 경우 각 노드 이름에 고유한 번호를 추가합니다.


시간이 지남에 따라 변경될 가능성이 있는 이름에 구체적인 세부 정보를 추가하기 전에 두 번 생각해 보세요.  예를 들어, 노드 이름에 IP 주소를 포함하지 마세요. 이 주소는 변경될 수 있습니다.  마찬가지로, 장비를 옮기거나 하드웨어를 업그레이드하는 경우 랙 위치나 기기 모델 번호가 변경될 수 있습니다.



=== 표시 이름 예시

StorageGRID 시스템에 세 개의 데이터 센터가 있고 각 데이터 센터에 서로 다른 유형의 노드가 있다고 가정해 보겠습니다.  표시 이름은 다음과 같이 간단할 수 있습니다.

* *그리드*: `StorageGRID Deployment`
* *첫 번째 사이트*: `Data Center 1`
+
** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`


* *두 번째 사이트*: `Data Center 2`
+
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`


* *제3사이트*: `Data Center 3`
+
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`



