---
permalink: maintain/restoring-existing-nodes.html 
sidebar: sidebar 
keywords: recover, restore node to host, node configuration file, start host service 
summary: 실패한 그리드 노드를 새 Linux 호스트로 복원하려면 다음 단계를 수행하여 노드 구성 파일을 복원합니다. 
---
= 그리드 노드를 호스트로 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실패한 그리드 노드를 새 Linux 호스트로 복원하려면 다음 단계를 수행하여 노드 구성 파일을 복원합니다.

. <<restore-validate-grid-nodes,노드 복원 및 검증>>노드 구성 파일을 복원하여.  새로 설치하는 경우 호스트에 설치할 각 그리드 노드에 대한 노드 구성 파일을 만듭니다.  그리드 노드를 대체 호스트로 복원할 때 실패한 그리드 노드의 노드 구성 파일을 복원하거나 교체합니다.
. <<start-storagegrid-host-service,StorageGRID 호스트 서비스 시작>> .
. 필요에 따라,<<recover-nodes-fail-start,시작에 실패한 모든 노드를 복구합니다.>> .


이전 호스트의 블록 스토리지 볼륨이 보존된 경우 추가 복구 절차를 수행해야 할 수도 있습니다.  이 섹션의 명령은 어떤 추가 절차가 필요한지 결정하는 데 도움이 됩니다.



== 그리드 노드 복원 및 검증

실패한 그리드 노드의 그리드 구성 파일을 복원한 다음, 그리드 구성 파일을 검증하고 오류를 해결해야 합니다.

.이 작업에 관하여
호스트에 존재해야 하는 모든 그리드 노드를 가져올 수 있습니다. `/var/local` 이전 호스트의 실패로 인해 볼륨이 손실되지 않았습니다.  예를 들어, `/var/local` Linux 운영 체제에 대한 StorageGRID 설치 지침에 설명된 대로 StorageGRID 시스템 데이터 볼륨에 공유 스토리지를 사용한 경우 볼륨이 여전히 존재할 수 있습니다.  노드를 가져오면 노드 구성 파일이 호스트로 복원됩니다.

누락된 노드를 가져올 수 없는 경우 해당 노드의 그리드 구성 파일을 다시 만들어야 합니다.

그런 다음 그리드 구성 파일의 유효성을 검사하고 StorageGRID 다시 시작하기 전에 발생할 수 있는 네트워킹 또는 스토리지 문제를 해결해야 합니다.  노드의 구성 파일을 다시 만들 때는 복구 중인 노드에 사용된 것과 동일한 이름을 대체 노드에 사용해야 합니다.

자세한 위치에 대한 정보는 설치 지침을 참조하세요. `/var/local` 노드의 볼륨.

* link:../rhel/index.html["Red Hat Enterprise Linux에 StorageGRID 설치"]
* link:../ubuntu/index.html["Ubuntu 또는 Debian에 StorageGRID 설치"]


.단계
. 복구된 호스트의 명령줄에서 현재 구성된 모든 StorageGRID 노드를 나열합니다.``sudo storagegrid node list``
+
그리드 노드가 구성되지 않으면 출력이 없습니다.  일부 그리드 노드가 구성된 경우 다음 형식으로 출력됩니다.

+
[listing]
----
Name               Metadata-Volume
================================================================
dc1-adm1           /dev/mapper/sgws-adm1-var-local
dc1-gw1            /dev/mapper/sgws-gw1-var-local
dc1-sn1            /dev/mapper/sgws-sn1-var-local
dc1-arc1           /dev/mapper/sgws-arc1-var-local
----
+
호스트에 구성되어야 하는 그리드 노드 중 일부 또는 전부가 나열되지 않은 경우, 누락된 그리드 노드를 복원해야 합니다.

. 그리드 노드를 가져오려면 `/var/local` 용량:
+
.. 가져오려는 각 노드에 대해 다음 명령을 실행합니다.``sudo storagegrid node import node-var-local-volume-path``
+
그만큼 `storagegrid node import` 명령은 마지막으로 실행된 호스트에서 대상 노드가 정상적으로 종료된 경우에만 성공합니다.  그렇지 않은 경우 다음과 유사한 오류가 표시됩니다.

+
`This node (_node-name_) appears to be owned by another host (UUID host-uuid).`

+
`Use the --force flag if you are sure import is safe.`

.. 노드가 다른 호스트에 의해 소유되었다는 오류가 표시되면 명령을 다시 실행하세요. `--force` 가져오기를 완료하기 위한 플래그:``sudo storagegrid --force node import node-var-local-volume-path``
+

NOTE: 가져온 모든 노드 `--force` 플래그는 그리드에 다시 합류하기 전에 추가 복구 단계가 필요합니다.link:whats-next-performing-additional-recovery-steps-if-required.html["다음 단계: 필요한 경우 추가 복구 단계 수행"] .



. 그리드 노드가 없는 경우 `/var/local` 볼륨을 복원하려면 노드의 구성 파일을 다시 만듭니다. 자세한 내용은 다음을 참조하세요.
+
** link:../rhel/creating-node-configuration-files.html["Red Hat Enterprise Linux용 노드 구성 파일 생성"]
** link:../ubuntu/creating-node-configuration-files.html["Ubuntu 또는 Debian용 노드 구성 파일 만들기"]
+

NOTE: 노드의 구성 파일을 다시 만들 때는 복구 중인 노드에 사용된 것과 동일한 이름을 대체 노드에 사용해야 합니다.  Linux 배포의 경우 구성 파일 이름에 노드 이름이 포함되어 있는지 확인하세요.  가능하면 동일한 네트워크 인터페이스, 블록 장치 매핑 및 IP 주소를 사용해야 합니다.  이 방법을 사용하면 복구 중에 노드에 복사해야 하는 데이터 양이 최소화되므로 복구 속도가 상당히 빨라질 수 있습니다(어떤 경우에는 몇 주가 아닌 몇 분).

+

NOTE: StorageGRID 노드가 이전에 사용하지 않았던 새로운 블록 장치를 구성 변수의 값으로 사용하는 경우 `BLOCK_DEVICE_` 노드에 대한 구성 파일을 다시 생성할 때는 다음 지침을 따르세요.<<fix-block-errors,누락된 블록 장치 오류 수정>> .



. 복구된 호스트에서 다음 명령을 실행하여 모든 StorageGRID 노드를 나열합니다.
+
`sudo storagegrid node list`

. storagegrid 노드 목록 출력에 이름이 표시된 각 그리드 노드에 대한 노드 구성 파일을 검증합니다.
+
`sudo storagegrid node validate _node-name_`

+
StorageGRID 호스트 서비스를 시작하기 전에 오류나 경고를 모두 해결해야 합니다.  다음 섹션에서는 복구 중에 특별한 의미가 있을 수 있는 오류에 대해 자세히 설명합니다.





=== 누락된 네트워크 인터페이스 오류 수정

호스트 네트워크가 올바르게 구성되지 않았거나 이름이 잘못 입력된 경우 StorageGRID 지정된 매핑을 확인할 때 오류가 발생합니다. `/etc/storagegrid/nodes/_node-name_.conf` 파일.

다음 패턴과 일치하는 오류나 경고가 표시될 수 있습니다.

[listing]
----
Checking configuration file /etc/storagegrid/nodes/<node-name>.conf for node <node-name>...
ERROR: <node-name>: GRID_NETWORK_TARGET = <host-interface-name>
       <node-name>: Interface <host-interface-name>' does not exist
----
이 오류는 그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크에 대해 보고될 수 있습니다.  이 오류는 다음을 의미합니다. `/etc/storagegrid/nodes/_node-name_.conf` 파일은 표시된 StorageGRID 네트워크를 이름이 지정된 호스트 인터페이스에 매핑합니다. `_host-interface-name_` , 하지만 현재 호스트에는 해당 이름의 인터페이스가 없습니다.

이 오류가 발생하면 다음 단계를 완료했는지 확인하십시오.link:deploying-new-linux-hosts.html["새로운 Linux 호스트 배포"] .  모든 호스트 인터페이스에 원래 호스트에서 사용된 것과 동일한 이름을 사용합니다.

호스트 인터페이스의 이름을 노드 구성 파일과 일치시킬 수 없는 경우, 노드 구성 파일을 편집하고 GRID_NETWORK_TARGET, ADMIN_NETWORK_TARGET 또는 CLIENT_NETWORK_TARGET의 값을 변경하여 기존 호스트 인터페이스와 일치시킬 수 있습니다.

호스트 인터페이스가 적절한 물리적 네트워크 포트나 VLAN에 대한 액세스를 제공하는지 확인하고, 인터페이스가 본드나 브리지 장치를 직접 참조하지 않는지 확인하세요.  호스트의 본드 장치 위에 VLAN(또는 다른 가상 인터페이스)을 구성하거나 브리지와 가상 이더넷(veth) 쌍을 사용해야 합니다.



=== 누락된 블록 장치 오류 수정

시스템은 복구된 각 노드가 유효한 블록 장치 특수 파일이나 블록 장치 특수 파일에 대한 유효한 소프트 링크에 ​​매핑되는지 확인합니다.  StorageGRID 잘못된 매핑을 발견하면 `/etc/storagegrid/nodes/_node-name_.conf` 파일에서 블록 장치 누락 오류가 표시됩니다.

이 패턴과 일치하는 오류가 관찰되면:

[listing]
----
Checking configuration file /etc/storagegrid/nodes/<node-name>.conf for node <node-name>...
ERROR: <node-name>: BLOCK_DEVICE_PURPOSE = <path-name>
       <node-name>: <path-name> does not exist
----
그것은 다음을 의미합니다 `/etc/storagegrid/nodes/_node-name_.conf` _node-name_에서 사용하는 블록 장치를 매핑합니다. `PURPOSE` Linux 파일 시스템의 주어진 경로 이름에 대한 경로가 있지만 해당 위치에 유효한 블록 장치 특수 파일이 없거나 블록 장치 특수 파일에 대한 소프트 링크가 없습니다.

다음 단계를 완료했는지 확인하세요.link:deploying-new-linux-hosts.html["새로운 Linux 호스트 배포"] .  모든 블록 장치에 원래 호스트에서 사용된 것과 동일한 영구 장치 이름을 사용합니다.

누락된 블록 장치 특수 파일을 복원하거나 다시 생성할 수 없는 경우 적절한 크기와 저장 범주의 새 블록 장치를 할당하고 노드 구성 파일을 편집하여 값을 변경할 수 있습니다. `BLOCK_DEVICE_PURPOSE` 새로운 블록 장치 특수 파일을 가리킵니다.

다음 표를 사용하여 Linux 운영 체제에 적합한 크기와 저장 범주를 결정하세요.

* link:../rhel/storage-and-performance-requirements.html["Red Hat Enterprise Linux에 대한 스토리지 및 성능 요구 사항"]
* link:../ubuntu/storage-and-performance-requirements.html["Ubuntu 또는 Debian의 저장소 및 성능 요구 사항"]


블록 장치 교체를 진행하기 전에 호스트 스토리지 구성에 대한 권장 사항을 검토하세요.

* link:../rhel/configuring-host-storage.html["Red Hat Enterprise Linux용 호스트 스토리지 구성"]
* link:../ubuntu/configuring-host-storage.html["Ubuntu 또는 Debian에 대한 호스트 스토리지 구성"]



NOTE: 다음으로 시작하는 구성 파일 변수에 대해 새 블록 저장 장치를 제공해야 하는 경우 `BLOCK_DEVICE_` 원래 블록 장치가 실패한 호스트와 함께 손실되었으므로 추가 복구 절차를 시도하기 전에 새 블록 장치가 포맷되지 않았는지 확인하세요.  공유 스토리지를 사용하고 새 볼륨을 생성한 경우 새 블록 장치는 포맷되지 않습니다.  확실하지 않은 경우 새로운 블록 저장 장치 특수 파일에 대해 다음 명령을 실행하세요.

[CAUTION]
====
다음 명령은 새로운 블록 저장 장치에만 실행하세요.  복구 중인 노드에 대한 유효한 데이터가 블록 스토리지에 여전히 포함되어 있다고 생각되는 경우 이 명령을 실행하지 마세요. 그렇지 않으면 장치의 모든 데이터가 손실됩니다.

`sudo dd if=/dev/zero of=/dev/mapper/my-block-device-name bs=1G count=1`

====


== StorageGRID 호스트 서비스 시작

StorageGRID 노드를 시작하고 호스트 재부팅 후 다시 시작되도록 하려면 StorageGRID 호스트 서비스를 활성화하고 시작해야 합니다.

.단계
. 각 호스트에서 다음 명령을 실행합니다.
+
[listing]
----
sudo systemctl enable storagegrid
sudo systemctl start storagegrid
----
. 다음 명령을 실행하여 배포가 진행되는지 확인하세요.
+
[listing]
----
sudo storagegrid node status node-name
----
. 노드가 "실행 중이 아님" 또는 "중지됨" 상태를 반환하는 경우 다음 명령을 실행합니다.
+
[listing]
----
sudo storagegrid node start node-name
----
. 이전에 StorageGRID 호스트 서비스를 활성화하고 시작한 경우(또는 서비스가 활성화되고 시작되었는지 확실하지 않은 경우) 다음 명령도 실행하세요.
+
[listing]
----
sudo systemctl reload-or-restart storagegrid
----




== 정상적으로 시작되지 않는 노드 복구

StorageGRID 노드가 정상적으로 그리드에 다시 가입하지 않고 복구 가능한 것으로 표시되지 않으면 손상되었을 수 있습니다.  노드를 복구 모드로 강제 전환할 수 있습니다.

.단계
. 노드의 네트워크 구성이 올바른지 확인하세요.
+
네트워크 인터페이스 매핑이 잘못되었거나 그리드 네트워크 IP 주소 또는 게이트웨이가 잘못되어 노드가 그리드에 다시 가입하지 못했을 수 있습니다.

. 네트워크 구성이 올바르면 다음을 실행하세요. `force-recovery` 명령:
+
`sudo storagegrid node force-recovery _node-name_`

. 노드에 대한 추가 복구 단계를 수행합니다. 보다 link:whats-next-performing-additional-recovery-steps-if-required.html["다음 단계: 필요한 경우 추가 복구 단계 수행"] .

