---
permalink: maintain/restoring-audit-log-on-recovered-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore audit log, primary admin node 
summary: 실패한 기본 관리 노드의 감사 로그를 보존할 수 있는 경우 복구 중인 기본 관리 노드에 복사할 수 있습니다. 
---
= 복구된 기본 관리 노드에서 감사 로그 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실패한 기본 관리 노드의 감사 로그를 보존할 수 있는 경우 복구 중인 기본 관리 노드에 복사할 수 있습니다.

.시작하기 전에
* 복구된 관리 노드가 설치되어 실행 중입니다.
* 원래 관리 노드가 실패한 후 감사 로그를 다른 위치로 복사했습니다.


.이 작업에 관하여
관리 노드에 장애가 발생하면 해당 관리 노드에 저장된 감사 로그가 손실될 가능성이 있습니다.  실패한 관리 노드에서 감사 로그를 복사한 다음 이 감사 로그를 복구된 관리 노드로 복원하면 데이터 손실을 방지할 수 있습니다.  오류에 따라 오류가 발생한 관리 노드에서 감사 로그를 복사하지 못할 수도 있습니다.  이 경우 배포에 두 개 이상의 관리 노드가 있는 경우 감사 로그가 모든 관리 노드에 복제되므로 다른 관리 노드에서 감사 로그를 복구할 수 있습니다.

관리 노드가 하나뿐이고 실패한 노드에서 감사 로그를 복사할 수 없는 경우, 복구된 관리 노드는 설치가 새로 이루어진 것처럼 감사 로그에 이벤트를 기록하기 시작합니다.

로깅 기능을 복원하려면 최대한 빨리 관리 노드를 복구해야 합니다.

[NOTE]
====
기본적으로 감사 정보는 관리 노드의 감사 로그로 전송됩니다.  다음 중 하나에 해당되는 경우 이 단계를 건너뛸 수 있습니다.

* 외부 syslog 서버를 구성했고 감사 로그가 이제 관리 노드가 아닌 syslog 서버로 전송됩니다.
* 감사 메시지는 이를 생성한 로컬 노드에만 저장되어야 한다고 명시적으로 지정했습니다.


보다link:../monitor/configure-audit-messages.html["감사 메시지 및 로그 대상 구성"] 자세한 내용은.

====
.단계
. 복구된 관리 노드에 로그인하세요.
+
.. 다음 명령을 입력하세요: `ssh admin@recovery_Admin_Node_IP`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.


+
루트로 로그인한 후 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .

. 어떤 감사 파일이 보존되었는지 확인하세요. `cd /var/local/log`
. 보존된 감사 로그 파일을 복구된 관리 노드로 복사합니다. `scp admin@_grid_node_IP_:/var/local/tmp/saved-audit-logs/YYYY* .`
+
메시지가 나타나면 admin 비밀번호를 입력하세요.

. 보안을 위해 복구된 관리 노드에 감사 로그가 성공적으로 복사되었는지 확인한 후 실패한 그리드 노드에서 감사 로그를 삭제합니다.
. 복구된 관리 노드의 감사 로그 파일에 있는 사용자 및 그룹 설정을 업데이트합니다. `chown ams-user: bycast *`
. 루트로 로그아웃합니다: `exit`

