---
permalink: maintain/restoring-prometheus-metrics-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore metrics, restore prometheus, non-primary admin node 
summary: 선택적으로, 실패한 기본 관리 노드가 아닌 곳에서 Prometheus가 유지 관리하는 기록 메트릭을 보관할 수 있습니다. 
---
= 기본이 아닌 관리 노드를 복구할 때 Prometheus 메트릭 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
선택적으로, 실패한 기본 관리 노드가 아닌 곳에서 Prometheus가 유지 관리하는 기록 메트릭을 보관할 수 있습니다.

.시작하기 전에
* 복구된 관리 노드가 설치되어 실행 중입니다.
* StorageGRID 시스템에는 최소 두 개의 관리 노드가 포함되어 있습니다.
* 당신은 가지고있다 `Passwords.txt` 파일.
* 프로비저닝 암호가 있습니다.


.이 작업에 관하여
관리 노드에 장애가 발생하면 관리 노드의 Prometheus 데이터베이스에 유지되는 메트릭이 손실됩니다.  관리 노드를 복구하면 소프트웨어 설치 과정에서 새로운 Prometheus 데이터베이스가 생성됩니다.  복구된 관리 노드가 시작된 후에는 StorageGRID 시스템을 새로 설치한 것처럼 메트릭이 기록됩니다.

기본 관리 노드가 아닌 관리 노드를 복원한 경우 기본 관리 노드(_소스 관리 노드_)에서 복구된 관리 노드로 Prometheus 데이터베이스를 복사하여 이전 메트릭을 복원할 수 있습니다.


NOTE: Prometheus 데이터베이스를 복사하는 데는 1시간 이상 걸릴 수 있습니다.  소스 관리 노드에서 서비스가 중지된 동안에는 일부 Grid Manager 기능을 사용할 수 없습니다.

.단계
. 소스 관리 노드에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.


. 소스 관리 노드에서 Prometheus 서비스를 중지합니다. `service prometheus stop`
. 복구된 관리 노드에서 다음 단계를 완료하세요.
+
.. 복구된 관리 노드에 로그인하세요.
+
... 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
... 다음 명령을 입력하여 루트로 전환하세요. `su -`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.


.. Prometheus 서비스를 중지합니다. `service prometheus stop`
.. SSH 에이전트에 SSH 개인 키를 추가합니다.  입력하다:``ssh-add``
.. SSH 접속 비밀번호를 입력하세요. `Passwords.txt` 파일.
.. 소스 관리 노드에서 복구된 관리 노드로 Prometheus 데이터베이스를 복사합니다. `/usr/local/prometheus/bin/prometheus-clone-db.sh Source_Admin_Node_IP`
.. 메시지가 표시되면 *Enter* 키를 눌러 복구된 관리 노드에서 새 Prometheus 데이터베이스를 삭제하고 싶은지 확인합니다.
+
원래 Prometheus 데이터베이스와 해당 기록 데이터는 복구된 관리 노드에 복사됩니다.  복사 작업이 완료되면 스크립트는 복구된 관리 노드를 시작합니다.  다음 상태가 나타납니다.

+
데이터베이스 복제, 서비스 시작

.. 더 이상 다른 서버에 암호 없이 액세스할 필요가 없으면 SSH 에이전트에서 개인 키를 제거하세요.  입력하다:``ssh-add -D``


. 소스 관리 노드에서 Prometheus 서비스를 다시 시작합니다..`service prometheus start`

