---
permalink: maintain/restoring-network-connectivity-for-isolated-nodes.html 
sidebar: sidebar 
keywords: storagegrid, recover, network connection, restore network connection, isolated node, restore isolated node connection 
summary: 특정 상황에서는 하나 이상의 노드 그룹이 그리드의 나머지 부분과 접촉하지 못할 수도 있습니다.  예를 들어, 사이트 전체 또는 그리드 전체의 IP 주소가 변경되면 노드가 격리될 수 있습니다. 
---
= 격리된 노드의 네트워크 연결 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 상황에서는 하나 이상의 노드 그룹이 그리드의 나머지 부분과 접촉하지 못할 수도 있습니다.  예를 들어, 사이트 전체 또는 그리드 전체의 IP 주소가 변경되면 노드가 격리될 수 있습니다.

.이 작업에 관하여
노드 분리는 다음과 같이 표시됩니다.

* *노드와 통신할 수 없습니다*와 같은 경고(*경고* > *현재*)
* 연결 관련 진단(*지원* > *도구* > *진단*)


격리된 노드가 있는 경우 다음과 같은 결과가 발생합니다.

* 여러 노드가 분리된 경우 Grid Manager에 로그인하거나 액세스할 수 없습니다.
* 여러 노드가 분리된 경우 테넌트 관리자 대시보드에 표시되는 스토리지 사용량 및 할당량 값이 최신이 아닐 수 있습니다.  네트워크 연결이 복구되면 총계가 업데이트됩니다.


격리 문제를 해결하려면 그리드에서 격리된 각 격리된 노드 또는 그룹(기본 관리 노드가 없는 서브넷의 모든 노드)의 한 노드에서 명령줄 유틸리티를 실행합니다.  이 유틸리티는 그리드 내의 격리되지 않은 노드의 IP 주소를 노드에 제공하여 격리된 노드나 노드 그룹이 전체 그리드에 다시 연결할 수 있도록 합니다.


NOTE: 네트워크에서 멀티캐스트 도메인 이름 시스템(mDNS)이 비활성화된 경우, 각 격리된 노드에서 명령줄 유틸리티를 실행해야 할 수도 있습니다.

.단계
일부 서비스만 오프라인이거나 통신 오류를 보고하는 경우에는 이 절차가 적용되지 않습니다.

. 노드에 접근하여 확인하세요 `/var/local/log/dynip.log` 격리 메시지용.
+
예를 들어:

+
[listing]
----
[2018-01-09T19:11:00.545] UpdateQueue - WARNING -- Possible isolation, no contact with other nodes.
If this warning persists, manual action might be required.
----
+
VMware 콘솔을 사용하는 경우 노드가 격리되었을 수 있다는 메시지가 표시됩니다.

+
Linux 배포에서는 격리 메시지가 다음과 같이 나타납니다. `/var/log/storagegrid/node/<nodename>.log` 파일.

. 격리 메시지가 반복적이고 지속되는 경우 다음 명령을 실행하세요.
+
`add_node_ip.py <address>`

+
어디 `<address>` 그리드에 연결된 원격 노드의 IP 주소입니다.

+
[listing]
----
# /usr/sbin/add_node_ip.py  10.224.4.210

Retrieving local host information
Validating remote node at address 10.224.4.210
Sending node IP hint for 10.224.4.210 to local node
Local node found on remote node. Update complete.
----
. 이전에 격리된 각 노드에 대해 다음 사항을 확인하세요.
+
** 노드의 서비스가 시작되었습니다.
** 동적 IP 서비스를 실행한 후 해당 서비스의 상태는 "실행 중"입니다. `storagegrid-status` 명령.
** 노드 페이지에서 노드가 더 이상 그리드의 나머지 부분과 분리되어 나타나지 않습니다.





NOTE: 실행 중이면 `add_node_ip.py` 명령으로 문제가 해결되지 않으면 해결해야 할 다른 네트워크 문제가 있을 수 있습니다.
