---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: 스토리지 노드의 실패한 시스템 드라이브를 복구하기 전에 그리드 노드 복구에 대한 일반적인 경고 및 고려 사항과 다음의 특정 경고를 검토하세요. 
---
= 스토리지 노드 시스템 드라이브 복구에 대한 경고
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드의 실패한 시스템 드라이브를 복구하기 전에 일반적인 내용을 검토하십시오.link:warnings-and-considerations-for-grid-node-recovery.html["그리드 노드 복구에 대한 경고 및 고려 사항"] 그리고 구체적인 경고는 다음과 같습니다.

스토리지 노드에는 개체 메타데이터가 포함된 Cassandra 데이터베이스가 있습니다. 다음과 같은 상황에서는 Cassandra 데이터베이스가 다시 구축될 수 있습니다.

* 저장 노드는 15일 이상 오프라인 상태였던 후 다시 온라인으로 전환됩니다.
* 저장 볼륨에 오류가 발생하여 복구되었습니다.
* 시스템 드라이브와 하나 이상의 스토리지 볼륨에 오류가 발생했지만 복구되었습니다.


Cassandra가 재구축되면 시스템은 다른 스토리지 노드의 정보를 사용합니다. 너무 많은 스토리지 노드가 오프라인인 경우 일부 Cassandra 데이터를 사용하지 못할 수 있습니다. Cassandra가 최근에 재구축된 경우 Cassandra 데이터가 그리드 전체에서 일관성을 유지하지 못할 수 있습니다.  너무 많은 스토리지 노드가 오프라인인 경우 Cassandra를 재구축하거나, 두 개 이상의 스토리지 노드가 15일 이내에 재구축되는 경우 데이터 손실이 발생할 수 있습니다.


CAUTION: 두 개 이상의 스토리지 노드에 오류가 발생하거나 오프라인인 경우 기술 지원팀에 문의하세요. 다음 복구 절차를 수행하지 마세요. 데이터 손실이 발생할 수 있습니다.


CAUTION: 스토리지 노드 장애 또는 복구 후 15일 이내에 두 번째 스토리지 노드 장애가 발생하는 경우 기술 지원팀에 문의하세요.  15일 이내에 두 개 이상의 스토리지 노드에서 Cassandra를 재구축하면 데이터가 손실될 수 있습니다.


NOTE: 사이트에서 두 개 이상의 스토리지 노드에 장애가 발생한 경우 사이트 복구 절차가 필요할 수 있습니다. 보다 link:how-site-recovery-is-performed-by-technical-support.html["기술 지원이 사이트를 복구하는 방법"] .


CAUTION: 이 스토리지 노드가 실패한 스토리지 볼륨이 있는 다른 스토리지 노드가 객체를 검색할 수 있도록 읽기 전용 유지 관리 모드인 경우, 이 실패한 스토리지 노드를 복구하기 전에 실패한 스토리지 볼륨이 있는 스토리지 노드에서 볼륨을 복구합니다. 지침을 참조하세요link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["시스템 드라이브가 손상되지 않은 스토리지 볼륨 오류에서 복구"] .


CAUTION: ILM 규칙이 복제된 복사본을 하나만 저장하도록 구성되어 있고 해당 복사본이 실패한 스토리지 볼륨에 있는 경우 개체를 복구할 수 없습니다.
