---
permalink: maintain/reviewing-ilm-policy-and-storage-configuration.html 
sidebar: sidebar 
keywords: storagegrid, restore, ilm policy, storage configuration 
summary: 스토리지 노드를 해체할 계획이라면 해체 프로세스를 시작하기 전에 StorageGRID 시스템의 ILM 정책을 검토해야 합니다. 
---
= ILM 정책 및 스토리지 구성 검토
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드를 해체할 계획이라면 해체 프로세스를 시작하기 전에 StorageGRID 시스템의 ILM 정책을 검토해야 합니다.

해체 중에는 모든 개체 데이터가 해체된 스토리지 노드에서 다른 스토리지 노드로 마이그레이션됩니다.


NOTE: 해체 중에 적용한 ILM 정책은 해체 후에 적용됩니다.  해체를 시작하기 전과 해체가 완료된 후에 이 정책이 귀하의 데이터 요구 사항을 충족하는지 확인해야 합니다.

각각의 규칙을 검토해야 합니다.link:../ilm/creating-ilm-policy.html["활성 ILM 정책"] StorageGRID 시스템이 스토리지 노드의 서비스 중단을 수용할 수 있을 만큼 올바른 유형과 올바른 위치에 충분한 용량을 계속 유지할 수 있도록 보장합니다.

다음 사항을 고려하세요.

* ILM 평가 서비스에서 ILM 규칙을 충족하도록 개체 데이터를 복사하는 것이 가능할까요?
* 해체가 진행되는 동안 사이트를 일시적으로 사용할 수 없게 되면 어떻게 되나요?  다른 위치에 추가 사본을 만들 수 있나요?
* 해체 과정은 콘텐츠의 최종 배포에 어떤 영향을 미칠까요?  에서 설명한 대로link:consolidating-storage-nodes.html["스토리지 노드 통합"] , 당신은해야합니다link:../expand/index.html["새로운 스토리지 노드 추가"] 오래된 것을 폐기하기 전에.  작은 스토리지 노드를 폐기한 후 더 큰 대체 스토리지 노드를 추가하는 경우, 기존 스토리지 노드는 용량이 거의 가득 차고 새 스토리지 노드에는 콘텐츠가 거의 없을 수 있습니다.  그러면 새로운 객체 데이터에 대한 대부분의 쓰기 작업이 새 스토리지 노드로 전달되어 시스템 작업의 전반적인 효율성이 떨어집니다.
* 시스템은 항상 활성 ILM 정책을 충족할 만큼 충분한 스토리지 노드를 포함합니까?
+

NOTE: 충족될 수 없는 ILM 정책은 백로그와 경고로 이어지고 StorageGRID 시스템의 운영을 중단시킬 수 있습니다.



표에 나열된 영역을 평가하여 해체 프로세스에서 생성될 제안된 토폴로지가 ILM 정책을 충족하는지 확인하세요.

[cols="1a,2a"]
|===
| 평가할 영역 | 고려해야 할 사항 


 a| 
사용 가능한 용량
 a| 
폐기될 스토리지 노드에 현재 저장되어 있는 객체 데이터의 영구 사본을 포함하여 StorageGRID 시스템에 저장된 모든 객체 데이터를 수용할 만큼 충분한 저장 용량이 있을까요?

해체가 완료된 후 적당한 기간 동안 저장된 객체 데이터의 예상되는 증가를 처리할 수 있는 충분한 용량이 있을까요?



 a| 
보관 위치
 a| 
StorageGRID 시스템 전체에 충분한 용량이 남아 있다면, 해당 용량이 StorageGRID 시스템의 비즈니스 규칙을 충족할 만큼 적절한 위치에 있습니까?



 a| 
저장 유형
 a| 
해체가 완료된 후 적절한 유형의 저장 공간이 충분할까요?

예를 들어, ILM 규칙은 콘텐츠가 오래됨에 따라 콘텐츠를 한 유형의 저장소에서 다른 유형의 저장소로 이동할 수 있습니다.  이 경우 StorageGRID 시스템의 최종 구성에서 적절한 유형의 충분한 스토리지가 사용 가능한지 확인해야 합니다.

|===