---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: 스토리지 노드의 실패한 스토리지 볼륨을 복구하기 전에 다음 경고를 검토해야 합니다. 
---
= 저장 볼륨 복구에 대한 경고
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드의 실패한 스토리지 볼륨을 복구하기 전에 다음 경고를 검토하세요.

스토리지 노드의 스토리지 볼륨(또는 rangedb)은 16진수 숫자로 식별되며, 이를 볼륨 ID라고 합니다.  예를 들어, 0000은 첫 번째 권이고, 000F는 열여섯 번째 권입니다.  각 스토리지 노드의 첫 번째 개체 저장소(볼륨 0)는 개체 메타데이터와 Cassandra 데이터베이스 작업에 최대 4TB의 공간을 사용합니다. 해당 볼륨에 남아 있는 공간은 개체 데이터에 사용됩니다.  다른 모든 저장 볼륨은 객체 데이터에만 사용됩니다.

볼륨 0에 오류가 발생하여 복구가 필요한 경우 볼륨 복구 절차의 일부로 Cassandra 데이터베이스가 다시 빌드될 수 있습니다.  다음과 같은 상황에서는 카산드라가 재건될 수도 있습니다.

* 저장 노드는 15일 이상 오프라인 상태였던 후 다시 온라인으로 전환됩니다.
* 시스템 드라이브와 하나 이상의 스토리지 볼륨에 오류가 발생했지만 복구되었습니다.


Cassandra가 재구축되면 시스템은 다른 스토리지 노드의 정보를 사용합니다. 너무 많은 스토리지 노드가 오프라인인 경우 일부 Cassandra 데이터를 사용하지 못할 수 있습니다. Cassandra가 최근에 재구축된 경우 Cassandra 데이터가 그리드 전체에서 일관성을 유지하지 못할 수 있습니다.  너무 많은 스토리지 노드가 오프라인인 경우 Cassandra를 재구축하거나, 두 개 이상의 스토리지 노드가 15일 이내에 재구축되는 경우 데이터 손실이 발생할 수 있습니다.


CAUTION: 두 개 이상의 스토리지 노드에 오류가 발생하거나 오프라인인 경우 기술 지원팀에 문의하세요. 다음 복구 절차를 수행하지 마세요. 데이터 손실이 발생할 수 있습니다.


CAUTION: 스토리지 노드 장애 또는 복구 후 15일 이내에 두 번째 스토리지 노드 장애가 발생하는 경우 기술 지원팀에 문의하세요.  15일 이내에 두 개 이상의 스토리지 노드에서 Cassandra를 재구축하면 데이터가 손실될 수 있습니다.


NOTE: 사이트에서 두 개 이상의 스토리지 노드에 장애가 발생한 경우 사이트 복구 절차가 필요할 수 있습니다. 보다 link:how-site-recovery-is-performed-by-technical-support.html["기술 지원이 사이트를 복구하는 방법"] .


CAUTION: ILM 규칙이 복제된 복사본을 하나만 저장하도록 구성되어 있고 해당 복사본이 실패한 스토리지 볼륨에 있는 경우 개체를 복구할 수 없습니다.

.관련 정보
link:warnings-and-considerations-for-grid-node-recovery.html["그리드 노드 복구에 대한 경고 및 고려 사항"]
