---
permalink: maintain/shutting-down-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, node shutdown, shut down node, node shut down 
summary: 노드의 명령 셸에서 그리드 노드를 종료할 수 있습니다. 
---
= 그리드 노드 종료
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드의 명령 셸에서 그리드 노드를 종료할 수 있습니다.

.시작하기 전에
* 당신은 가지고있다 `Passwords.txt` 파일.


.이 작업에 관하여
이 절차를 수행하기 전에 다음 사항을 검토하세요.

* 일반적으로 중단을 방지하려면 한 번에 두 개 이상의 노드를 종료해서는 안 됩니다.
* 설명서나 기술 지원팀에서 명시적으로 지시하지 않는 한 유지 관리 절차 중에는 노드를 종료하지 마세요.
* 종료 프로세스는 노드가 설치된 위치에 따라 다음과 같이 진행됩니다.
+
** VMware 노드를 종료하면 가상 머신도 종료됩니다.
** Linux 노드를 종료하면 컨테이너도 종료됩니다.
** StorageGRID 어플라이언스 노드를 종료하면 컴퓨팅 컨트롤러도 종료됩니다.


* 사이트에서 두 개 이상의 스토리지 노드를 종료할 계획이라면 노드를 종료하기 전에 약 1시간 동안 해당 사이트에서 객체 수집을 중지하세요.
+
ILM 규칙에서 *이중 커밋* 수집 옵션을 사용하는 경우(또는 규칙에서 *균형* 옵션을 사용하고 필요한 모든 복사본을 즉시 생성할 수 없는 경우), StorageGRID 새로 수집된 모든 객체를 동일한 사이트에 있는 두 개의 스토리지 노드에 즉시 커밋하고 나중에 ILM을 평가합니다.  사이트에서 두 개 이상의 스토리지 노드가 종료되면 종료 기간 동안 새로 수집된 개체에 액세스하지 못할 수 있습니다.  사이트에 사용 가능한 스토리지 노드가 너무 적은 경우에도 쓰기 작업이 실패할 수 있습니다. 보다 link:../ilm/index.html["ILM을 사용하여 객체 관리"] .



.단계
. 그리드 노드에 로그인하세요:
+
.. 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.


+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .

. 모든 서비스를 중지합니다: `service servermanager stop`
+
서비스를 종료하는 데 최대 15분이 걸릴 수 있으며, 종료 과정을 모니터링하려면 시스템에 원격으로 로그인해야 할 수도 있습니다.

. 노드가 VMware 가상 머신에서 실행 중이거나 어플라이언스 노드인 경우 shutdown 명령을 실행합니다. `shutdown -h now`
+
결과에 관계없이 이 단계를 수행하십시오. `service servermanager stop` 명령.

+

NOTE: 당신이 발행한 후 `shutdown -h now` 어플라이언스 노드에서 명령을 실행하려면 노드를 다시 시작하려면 어플라이언스의 전원을 껐다 켜야 합니다.

+
기기의 경우, 이 명령은 컨트롤러를 종료하지만 기기의 전원은 계속 켜져 있습니다.  다음 단계를 완료해야 합니다.

. 기기 노드의 전원을 끄려면 기기에 맞는 단계를 따르세요.
+
[role="tabbed-block"]
====
.SG6160
--
.. SG6100-CN 저장 컨트롤러의 전원을 끕니다.
.. SG6100-CN 스토리지 컨트롤러의 파란색 전원 LED가 꺼질 때까지 기다리세요.


--
.SGF6112
--
.. 기기의 전원을 끕니다.
.. 파란색 전원 LED가 꺼질 때까지 기다리세요.


--
.SG6000
--
.. 스토리지 컨트롤러 뒷면의 녹색 캐시 활성 LED가 꺼질 때까지 기다리세요.
+
캐시된 데이터를 드라이브에 써야 할 때 이 LED가 켜집니다.  전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

.. 기기의 전원을 끄고 파란색 전원 LED가 꺼질 때까지 기다리세요.


--
.SG5800
--
.. 스토리지 컨트롤러 뒷면의 녹색 캐시 활성 LED가 꺼질 때까지 기다리세요.
+
캐시된 데이터를 드라이브에 써야 할 때 이 LED가 켜집니다.  전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

.. SANtricity System Manager 홈페이지에서 *진행 중인 작업 보기*를 선택합니다.
.. 다음 단계로 넘어가기 전에 모든 작업이 완료되었는지 확인하세요.
.. 컨트롤러 선반의 두 전원 스위치를 모두 끄고 컨트롤러 선반의 모든 LED가 꺼질 때까지 기다립니다.


--
.SG5700
--
.. 스토리지 컨트롤러 뒷면의 녹색 캐시 활성 LED가 꺼질 때까지 기다리세요.
+
캐시된 데이터를 드라이브에 써야 할 때 이 LED가 켜집니다.  전원을 끄기 전에 이 LED가 꺼질 때까지 기다려야 합니다.

.. 기기의 전원을 끄고 모든 LED와 7세그먼트 디스플레이 활동이 멈출 때까지 기다리세요.


--
.SG100 또는 SG1000
--
.. 기기의 전원을 끕니다.
.. 파란색 전원 LED가 꺼질 때까지 기다리세요.


--
====

