---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: '해체 사이트 마법사의 3단계 \(ILM 정책 수정\)에서 해당 사이트가 ILM 정책에 의해 참조되는지 확인할 수 있습니다.' 
---
= 3단계: ILM 정책 수정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
해체 사이트 마법사의 3단계(ILM 정책 개정)에서 해당 사이트가 ILM 정책에 해당하는지 확인할 수 있습니다.

.시작하기 전에
당신은 어떻게 하는지 잘 이해하고 있습니다link:../ilm/index.html["ILM으로 객체 관리"] .  스토리지 풀과 ILM 규칙을 만드는 방법과 ILM 정책을 시뮬레이션하고 활성화하는 방법에 익숙합니다.

.이 작업에 관하여
모든 정책(활성 또는 비활성)의 ILM 규칙이 해당 사이트를 참조하는 경우 StorageGRID 해당 사이트를 서비스 해제할 수 없습니다.

ILM 정책이 해체하려는 사이트를 참조하는 경우 해당 정책을 제거하거나 편집하여 다음 요구 사항을 충족해야 합니다.

* 모든 객체 데이터를 완벽하게 보호합니다.
* 해체하려는 사이트를 언급하지 마세요.
* 사이트를 참조하는 스토리지 풀을 사용하거나 모든 사이트 옵션을 사용하지 마세요.
* 해당 사이트를 참조하는 삭제 코딩 프로필을 사용하지 마세요.
* StorageGRID 11.6 또는 이전 설치의 Make 2 Copies 규칙을 사용하지 마세요.



CAUTION: 사이트 제거를 수용하기 위해 단일 사본 ILM 규칙을 만들지 마십시오.  특정 기간 동안 복제된 사본을 하나만 생성하는 ILM 규칙은 데이터가 영구적으로 손실될 위험에 처하게 합니다.  개체의 복제된 사본이 하나만 있는 경우 스토리지 노드에 장애가 발생하거나 심각한 오류가 발생하면 해당 개체는 손실됩니다.  업그레이드 등의 유지 관리 절차가 진행되는 동안에는 해당 객체에 대한 액세스 권한을 일시적으로 잃게 됩니다.


TIP: _연결된 사이트 해제_를 수행하는 경우, 제거하려는 사이트에 있는 개체 데이터를 StorageGRID 어떻게 관리해야 하는지 고려해야 합니다.  데이터 보호 요구 사항에 따라 새로운 규칙은 기존 개체 데이터를 다른 사이트로 이동하거나 더 이상 필요하지 않은 추가 개체 사본을 삭제할 수 있습니다.

새로운 정책을 설계하는 데 도움이 필요하면 기술 지원팀에 문의하세요.

.단계
. 3단계(ILM 정책 개정)에서 폐쇄를 위해 선택한 사이트를 참조하는 ILM 정책이 있는지 확인합니다.
. 정책이 나열되지 않은 경우 *다음*을 선택하여 이동합니다.link:step-4-remove-ilm-references.html["4단계: ILM 참조 제거"] .
. 하나 이상의 _활성_ ILM 정책이 나열된 경우 기존 정책을 각각 복제하거나 폐기되는 사이트를 참조하지 않는 새 정책을 만듭니다.
+
.. 정책 이름 열에서 정책에 대한 링크를 선택합니다.
+
해당 정책의 ILM 정책 세부 정보 페이지가 새 브라우저 탭에 나타납니다.  폐쇄 사이트 페이지는 다른 탭에서 계속 열려 있습니다.

.. 필요에 따라 다음 지침과 지시를 따르세요.
+
*** ILM 규칙으로 작업:
+
**** link:../ilm/creating-storage-pool.html["하나 이상의 스토리지 풀을 만듭니다."]해당 사이트를 참조하지 않는 경우.
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["규칙 편집 또는 교체"]해당 사이트를 참조합니다.
+

NOTE: *2개의 사본 만들기* 규칙은 허용되지 않는 *모든 스토리지 노드* 스토리지 풀을 사용하므로 선택하지 마세요.



*** ILM 정책에 따라 작업:
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["기존 ILM 정책 복제"]또는link:../ilm/creating-ilm-policy.html["새로운 ILM 정책 생성"] .
**** 기본 규칙과 다른 규칙이 사이트를 참조하지 않는지 확인하세요.
+

CAUTION: ILM 규칙이 올바른 순서로 되어 있는지 확인해야 합니다.  정책이 활성화되면 새 개체와 기존 개체는 위에서부터 나열된 순서대로 규칙에 따라 평가됩니다.





.. 테스트 객체를 수집하고 정책을 시뮬레이션하여 올바른 규칙이 적용되는지 확인합니다.
+

CAUTION: ILM 정책의 오류로 인해 복구할 수 없는 데이터 손실이 발생할 수 있습니다.  정책을 활성화하기 전에 정책을 주의 깊게 검토하고 시뮬레이션하여 의도한 대로 작동하는지 확인하세요.

+

CAUTION: 새로운 ILM 정책을 활성화하면 StorageGRID 해당 정책을 사용하여 기존 개체와 새로 수집된 개체를 포함한 모든 개체를 관리합니다.  새로운 ILM 정책을 활성화하기 전에 기존 복제 및 삭제 코드화된 객체의 배치에 대한 변경 사항을 검토하세요.  기존 객체의 위치를 ​​변경하면 새로운 배치를 평가하고 구현할 때 일시적인 리소스 문제가 발생할 수 있습니다.

.. 새로운 정책을 활성화하고 기존 정책은 비활성화합니다.
+
여러 정책을 활성화하려면link:../ilm/creating-ilm-policy.html#activate-ilm-policy["ILM 정책 태그를 만드는 단계를 따르세요."] .

+
연결된 사이트 해제를 수행하는 경우, StorageGRID 새 ILM 정책을 활성화하자마자 선택한 사이트에서 개체 데이터를 제거하기 시작합니다.  모든 개체 사본을 이동하거나 삭제하는 데는 몇 주가 걸릴 수 있습니다.  사이트에 개체 데이터가 여전히 존재하는 동안 안전하게 사이트 해체를 시작할 수 있지만, 실제 해체 절차를 시작하기 전에 사이트에서 데이터를 이동하도록 허용하면(마법사의 5단계에서 *해제 시작*을 선택) 해체 절차가 더 빨리 완료되고 중단과 성능 영향도 줄어듭니다.



. 각 _비활성_ 정책에 대해 이전 단계에서 설명한 대로 먼저 각 정책에 대한 링크를 선택하여 해당 정책을 편집하거나 제거합니다.
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["정책 편집"]따라서 폐쇄될 사이트를 의미하지 않습니다.
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["정책 제거"] .


. ILM 규칙과 정책을 변경하는 작업을 마치면 3단계(ILM 정책 수정)에 더 이상 정책이 나열되어 있지 않아야 합니다. *다음*을 선택하세요.
+
4단계(ILM 참조 제거)가 나타납니다.


