---
permalink: maintain/storagegrid-hotfix-procedure.html 
sidebar: sidebar 
keywords: apply hotfix, install hotfix, replace primary admin node 
summary: 기능 릴리스 사이에 소프트웨어 문제가 감지되어 해결되는 경우 StorageGRID 시스템에 핫픽스를 적용해야 할 수도 있습니다. 
---
= StorageGRID 핫픽스 절차
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기능 릴리스 사이에 소프트웨어 문제가 감지되어 해결되는 경우 StorageGRID 시스템에 핫픽스를 적용해야 할 수도 있습니다.

StorageGRID 핫픽스에는 기능 또는 패치 릴리스 외부에서 제공되는 소프트웨어 변경 사항이 포함되어 있습니다.  동일한 변경 사항이 향후 릴리스에 포함될 예정입니다.  또한 각 핫픽스 릴리스에는 해당 기능 또는 패치 릴리스 내의 모든 이전 핫픽스의 롤업이 포함되어 있습니다.



== 핫픽스 적용 시 고려 사항

다른 유지 관리 절차가 실행 중일 때는 StorageGRID 핫픽스를 적용할 수 없습니다.  예를 들어, 해체, 확장 또는 복구 절차가 실행되는 동안에는 핫픽스를 적용할 수 없습니다.


NOTE: 노드 또는 사이트 서비스 중단 절차가 일시 중지된 경우 핫픽스를 안전하게 적용할 수 있습니다.  또한 StorageGRID 업그레이드 절차의 마지막 단계에서 핫픽스를 적용할 수도 있습니다.  자세한 내용은 StorageGRID 소프트웨어 업그레이드 지침을 참조하세요.

그리드 관리자에 핫픽스를 업로드하면 핫픽스가 기본 관리 노드에 자동으로 적용됩니다.  그런 다음 StorageGRID 시스템의 나머지 노드에 핫픽스 적용을 승인할 수 있습니다.

핫픽스가 하나 이상의 노드에 적용되지 않으면 실패 이유가 핫픽스 진행률 표의 세부 정보 열에 나타납니다.  실패의 원인이 된 문제를 해결한 후 전체 프로세스를 다시 시도해야 합니다.  이전에 핫픽스를 성공적으로 적용한 노드는 후속 적용에서 건너뛰어집니다.  모든 노드가 업데이트될 때까지 필요한 만큼 핫픽스 프로세스를 안전하게 다시 시도할 수 있습니다.  애플리케이션을 완료하려면 모든 그리드 노드에 핫픽스를 성공적으로 설치해야 합니다.

그리드 노드가 새로운 핫픽스 버전으로 업데이트되는 동안 핫픽스의 실제 변경 사항은 특정 유형의 노드의 특정 서비스에만 영향을 미칠 수 있습니다.  예를 들어, 핫픽스는 스토리지 노드의 LDR 서비스에만 영향을 미칠 수 있습니다.



== 복구 및 확장을 위해 핫픽스가 적용되는 방식

그리드에 핫픽스가 적용된 후, 기본 관리 노드는 복구 작업으로 복구된 노드나 확장 작업으로 추가된 모든 노드에 동일한 핫픽스 버전을 자동으로 설치합니다.

하지만 기본 관리 노드를 복구해야 하는 경우 올바른 StorageGRID 릴리스를 수동으로 설치한 다음 핫픽스를 적용해야 합니다.  기본 관리 노드의 최종 StorageGRID 버전은 그리드의 다른 노드 버전과 일치해야 합니다.

다음 예제에서는 기본 관리 노드를 복구할 때 핫픽스를 적용하는 방법을 보여줍니다.

. 그리드가 최신 핫픽스가 적용된 StorageGRID 11._A.B_ 버전을 실행하고 있다고 가정합니다.  "그리드 버전"은 11._A.B.y_입니다.
. 기본 관리 노드에 장애가 발생했습니다.
. StorageGRID 11._A.B_를 사용하여 기본 관리 노드를 다시 배포하고 복구 절차를 수행합니다.
+

NOTE: 그리드 버전과 일치하도록 필요한 경우 노드를 배포할 때 마이너 릴리스를 사용할 수 있습니다. 메이저 릴리스를 먼저 배포할 필요는 없습니다.

. 그런 다음 기본 관리 노드에 핫픽스 11._A.B.y_를 적용합니다.


자세한 내용은 다음을 참조하세요. link:configuring-replacement-primary-admin-node.html["교체용 기본 관리 노드 구성"] .
