---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: '너무 적은 관리 도메인 컨트롤러(ADC) 서비스가 해제된 후 남아 있을 경우 사이트에서 특정 스토리지 노드를 해제하지 못할 수 있습니다.' 
---
= ADC 정족수란 무엇입니까?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
너무 적은 관리 도메인 컨트롤러(ADC) 서비스가 해체 후에 남아 있을 경우, 사이트에서 특정 스토리지 노드를 해체하지 못할 수도 있습니다.

일부 스토리지 노드에서 발견되는 ADC 서비스는 그리드 토폴로지 정보를 유지 관리하고 그리드에 구성 서비스를 제공합니다.  StorageGRID 시스템은 각 사이트에서 항상 일정 수의 ADC 서비스를 사용할 수 있어야 합니다.

노드를 제거하면 ADC 쿼럼이 더 이상 충족되지 않는 경우 스토리지 노드를 서비스 해제할 수 없습니다.  해체 중에 ADC 정족수를 충족하려면 각 사이트에서 최소 3개의 스토리지 노드에 ADC 서비스가 있어야 합니다.  사이트에 ADC 서비스를 갖춘 스토리지 노드가 3개 이상 있는 경우, 해당 노드의 대부분은 서비스 중단 후에도 사용 가능해야 합니다. `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: 소프트웨어 기반 메타데이터 전용 노드가 포함된 그리드에서 스토리지 노드를 해제할 때는 주의하세요.  객체와 메타데이터를 모두 저장하도록 구성된 모든 노드를 해제하면 그리드에서 객체를 저장하는 기능이 제거됩니다.  보다link:../primer/what-storage-node-is.html#types-of-storage-nodes["저장 노드 유형"] 메타데이터 전용 스토리지 노드에 대한 자세한 내용은 다음을 참조하세요.

예를 들어, 현재 사이트에 ADC 서비스가 포함된 스토리지 노드가 6개 있고 3개의 스토리지 노드를 해제하려는 경우를 가정해 보겠습니다.  ADC 정족수 요구 사항으로 인해 다음과 같이 두 가지 해체 절차를 완료해야 합니다.

* 첫 번째 해체 절차에서는 ADC 서비스가 있는 4개의 스토리지 노드가 계속 사용 가능한지 확인해야 합니다. `((0.5 * 6) + 1)` .  즉, 처음에는 두 개의 스토리지 노드만 사용 중지할 수 있습니다.
* 두 번째 해체 절차에서는 ADC 쿼럼이 이제 사용 가능한 상태를 유지하는 데 필요한 ADC 서비스가 세 개뿐이므로 세 번째 스토리지 노드를 제거할 수 있습니다. `((0.5 * 4) + 1)` .


ADC 쿼럼 요구 사항으로 인해 스토리지 노드를 해제해야 하지만 해제할 수 없는 경우 새 스토리지 노드를 추가합니다.link:../expand/index.html["확장"] 그리고 ADC 서비스가 있어야 한다고 명시합니다.  그런 다음 기존 스토리지 노드를 해제합니다.
