---
permalink: maintain/warnings-and-considerations-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, warning 
summary: 그리드 노드에 장애가 발생하면 가능한 한 빨리 복구해야 합니다.  노드 복구를 시작하기 전에 모든 경고와 고려 사항을 검토해야 합니다. 
---
= 그리드 노드 복구에 대한 경고 및 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 노드에 장애가 발생하면 가능한 한 빨리 복구해야 합니다.  노드 복구를 시작하기 전에 모든 경고와 고려 사항을 검토해야 합니다.


CAUTION: StorageGRID 는 서로 협력하는 여러 노드로 구성된 분산 시스템입니다.  그리드 노드를 복원하는 데 디스크 스냅샷을 사용하지 마세요.  대신, 각 노드 유형에 대한 복구 및 유지 관리 절차를 참조하세요.


NOTE: StorageGRID 사이트 전체에 장애가 발생한 경우 기술 지원팀에 문의하세요. 기술 지원팀은 고객과 협력하여 복구되는 데이터 양을 극대화하고 비즈니스 목표를 달성하는 사이트 복구 계획을 개발하고 실행합니다. 보다 link:how-site-recovery-is-performed-by-technical-support.html["기술 지원이 사이트를 복구하는 방법"] .

가능한 한 빨리 실패한 그리드 노드를 복구해야 하는 이유는 다음과 같습니다.

* 그리드 노드에 장애가 발생하면 시스템 및 개체 데이터의 중복성이 감소하여 다른 노드에 장애가 발생할 경우 영구적인 데이터 손실 위험에 노출될 수 있습니다.
* 그리드 노드에 장애가 발생하면 일상 업무의 효율성이 저하될 수 있습니다.
* 그리드 노드에 장애가 발생하면 시스템 운영을 모니터링하는 능력이 저하될 수 있습니다.
* 엄격한 ILM 규칙이 적용되는 경우, 그리드 노드에 오류가 발생하면 500 내부 서버 오류가 발생할 수 있습니다.
* 그리드 노드가 신속하게 복구되지 않으면 복구 시간이 늘어날 수 있습니다.  예를 들어, 복구가 완료되기 전에 정리해야 할 대기열이 생길 수 있습니다.


항상 복구하려는 특정 유형의 그리드 노드에 대한 복구 절차를 따르세요.  복구 절차는 기본 또는 비기본 관리 노드, 게이트웨이 노드, 어플라이언스 노드 및 스토리지 노드에 따라 다릅니다.



== 그리드 노드 복구를 위한 전제 조건

그리드 노드를 복구할 때 다음 조건이 모두 적용된다고 가정합니다.

* 오류가 발생한 물리적 또는 가상 하드웨어가 교체되고 구성되었습니다.
* 교체 어플라이언스의 StorageGRID 어플라이언스 설치 프로그램 버전은 다음에 설명된 대로 StorageGRID 시스템의 소프트웨어 버전과 일치합니다. https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["StorageGRID Appliance 설치 프로그램 버전을 확인하고 업그레이드하세요."^] .
* 기본 관리 노드가 아닌 다른 그리드 노드를 복구하는 경우 복구되는 그리드 노드와 기본 관리 노드 사이에 연결이 있습니다.
* 어플라이언스 스토리지 노드를 복구하는 경우 어플라이언스 설치 중에 원래 어플라이언스와 동일한 스토리지 유형(결합, 메타데이터 전용 또는 데이터 전용)을 지정해야 합니다. 다른 저장 유형을 지정하면 복구가 실패하고 올바른 저장 유형을 지정하여 어플라이언스를 다시 설치해야 합니다.




== 두 개 이상의 그리드 노드를 호스팅하는 서버가 실패할 경우 노드 복구 순서

두 개 이상의 그리드 노드를 호스팅하는 서버에 장애가 발생하면 원하는 순서로 노드를 복구할 수 있습니다. 하지만 실패한 서버가 기본 관리 노드를 호스팅하는 경우 먼저 해당 노드를 복구해야 합니다. 기본 관리 노드를 먼저 복구하면 다른 노드 복구가 기본 관리 노드에 연결하기 위해 기다리는 동안 중단되는 것을 방지할 수 있습니다.



== 복구된 노드의 IP 주소

현재 다른 노드에 할당된 IP 주소를 사용하여 노드를 복구하려고 시도하지 마세요.  새 노드를 배포할 때는 실패한 노드의 현재 IP 주소나 사용되지 않은 IP 주소를 사용하세요.

새 IP 주소를 사용하여 새 노드를 배포한 다음 노드를 복구하는 경우, 새 IP 주소는 복구된 노드에 계속 사용됩니다.  원래 IP 주소로 되돌리려면 복구가 완료된 후 IP 변경 도구를 사용하세요.
