---
permalink: primer/nodes-and-services.html 
sidebar: sidebar 
keywords: services, grid nodes, primary admin, storage, gateway 
summary: StorageGRID 시스템의 기본 구성 요소는 그리드 노드입니다.  노드에는 서비스가 포함되어 있으며, 서비스는 그리드 노드에 일련의 기능을 제공하는 소프트웨어 모듈입니다. 
---
= 그리드 노드 및 서비스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 시스템의 기본 구성 요소는 그리드 노드입니다.  노드에는 서비스가 포함되어 있으며, 서비스는 그리드 노드에 일련의 기능을 제공하는 소프트웨어 모듈입니다.



== 그리드 노드의 유형

StorageGRID 시스템은 4가지 유형의 그리드 노드를 사용합니다.

관리 노드:: 시스템 구성, 모니터링, 로깅 등의 관리 서비스를 제공합니다.  Grid Manager에 로그인하면 관리 노드에 연결됩니다.  각 그리드에는 하나의 기본 관리 노드가 있어야 하며 중복성을 위해 기본이 아닌 추가 관리 노드가 있을 수 있습니다. 모든 관리 노드에 연결할 수 있으며, 각 관리 노드에는 StorageGRID 시스템의 유사한 보기가 표시됩니다.  그러나 유지 관리 절차는 기본 관리 노드를 사용하여 수행해야 합니다.
+
--
관리 노드는 S3 클라이언트 트래픽의 부하를 분산하는 데에도 사용할 수 있습니다.

보다link:what-admin-node-is.html["관리 노드란 무엇인가요?"]

--
저장 노드:: 객체 데이터와 메타데이터를 관리하고 저장합니다.  StorageGRID 시스템의 각 사이트에는 최소 3개의 스토리지 노드가 있어야 합니다.
+
--
보다link:what-storage-node-is.html["저장 노드란 무엇인가요?"]

--
게이트웨이 노드(선택 사항):: 클라이언트 애플리케이션이 StorageGRID 에 연결하는 데 사용할 수 있는 부하 분산 인터페이스를 제공합니다.  로드 밸런서는 클라이언트를 최적의 스토리지 노드로 원활하게 연결하므로 노드나 전체 사이트의 장애가 투명하게 드러납니다.
+
--
보다link:what-gateway-node-is.html["게이트웨이 노드란 무엇인가요?"]

--




== 하드웨어 및 소프트웨어 노드

StorageGRID 노드는 StorageGRID 어플라이언스 노드 또는 소프트웨어 기반 노드로 배포할 수 있습니다.



=== StorageGRID 어플라이언스 노드

StorageGRID 하드웨어 어플라이언스는 StorageGRID 시스템에서 사용하도록 특별히 설계되었습니다.  일부 기기는 저장 노드로 사용할 수 있습니다.  다른 어플라이언스는 관리 노드나 게이트웨이 노드로 사용될 수 있습니다.  어플라이언스 노드를 소프트웨어 기반 노드와 결합하거나 외부 하이퍼바이저, 스토리지 또는 컴퓨팅 하드웨어에 대한 종속성이 없는 완벽하게 설계된 모든 어플라이언스 그리드를 배포할 수 있습니다.

사용 가능한 가전제품에 대해 알아보려면 다음을 참조하세요.

* https://docs.netapp.com/us-en/storagegrid-appliances/["StorageGRID 어플라이언스 문서"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]




=== 소프트웨어 기반 노드

소프트웨어 기반 그리드 노드는 VMware 가상 머신으로 배포되거나 Linux 호스트의 컨테이너 엔진 내에 배포될 수 있습니다.

* VMware vSphere의 가상 머신(VM): 참조link:../vmware/index.html["VMware에 StorageGRID 설치"] .
* Red Hat Enterprise Linux의 컨테이너 엔진 내에서: 참조link:../rhel/index.html["Red Hat Enterprise Linux에 StorageGRID 설치"] .
* Ubuntu 또는 Debian의 컨테이너 엔진 내에서: 참조link:../ubuntu/index.html["Ubuntu 또는 Debian에 StorageGRID 설치"] .


사용하다 https://imt.netapp.com/matrix/#welcome["NetApp 상호 운용성 매트릭스 도구(IMT)"^] 지원되는 버전을 확인합니다.

새로운 소프트웨어 기반 스토리지 노드를 처음 설치하는 동안 해당 노드가 다음 용도로만 사용되도록 지정할 수 있습니다.link:../primer/what-storage-node-is.html#types-of-storage-nodes["메타데이터 저장"] .



== StorageGRID 서비스

다음은 StorageGRID 서비스의 전체 목록입니다.

[cols="2a,3a,2a"]
|===
| 서비스 | 설명 | 위치 


 a| 
계정 서비스 포워더
 a| 
부하 분산 서비스에서 원격 호스트의 계정 서비스를 쿼리할 수 있는 인터페이스를 제공하고 부하 분산 서비스로 부하 분산 엔드포인트 구성 변경에 대한 알림을 제공합니다.
 a| 
관리 노드 및 게이트웨이 노드의 로드 밸런서 서비스



 a| 
ADC(관리 도메인 컨트롤러)
 a| 
토폴로지 정보를 유지 관리하고, 인증 서비스를 제공하며, LDR 및 CMN 서비스의 쿼리에 응답합니다.
 a| 
각 사이트에 ADC 서비스를 포함하는 최소 3개의 스토리지 노드



 a| 
AMS(감사관리시스템)
 a| 
감사된 모든 시스템 이벤트와 거래를 모니터링하고 텍스트 로그 파일에 기록합니다.
 a| 
관리 노드



 a| 
카산드라 리퍼
 a| 
개체 메타데이터의 자동 복구를 수행합니다.
 a| 
저장 노드



 a| 
청크 서비스
 a| 
삭제된 데이터와 패리티 조각을 관리합니다.
 a| 
저장 노드



 a| 
CMN(구성 관리 노드)
 a| 
시스템 전체 구성과 그리드 작업을 관리합니다.  각 그리드에는 CMN 서비스가 하나씩 있습니다.
 a| 
기본 관리 노드



 a| 
DDS(분산 데이터 저장소)
 a| 
Cassandra 데이터베이스와 인터페이스하여 개체 메타데이터를 관리합니다.
 a| 
저장 노드



 a| 
DMV(데이터 무버)
 a| 
데이터를 클라우드 엔드포인트로 이동합니다.
 a| 
저장 노드



 a| 
동적 IP(dynip)
 a| 
동적 IP 변경 사항에 대한 그리드를 모니터링하고 로컬 구성을 업데이트합니다.
 a| 
모든 노드



 a| 
그라파나
 a| 
그리드 관리자에서 메트릭 시각화에 사용됩니다.
 a| 
관리 노드



 a| 
고가용성
 a| 
고가용성 그룹 페이지에 구성된 노드에서 고가용성 가상 IP를 관리합니다.  이 서비스는 keepalived 서비스로도 알려져 있습니다.
 a| 
관리자 및 게이트웨이 노드



 a| 
정체성(idnt)
 a| 
LDAP와 Active Directory의 사용자 ID를 연합합니다.
 a| 
ADC 서비스를 사용하는 스토리지 노드



 a| 
람다 중재자
 a| 
S3 Select SelectObjectContent 요청을 관리합니다.
 a| 
모든 노드



 a| 
로드 밸런서(nginx-gw)
 a| 
클라이언트에서 스토리지 노드로의 S3 트래픽에 대한 부하 분산을 제공합니다.  로드 밸런서 서비스는 로드 밸런서 엔드포인트 구성 페이지를 통해 구성할 수 있습니다.  이 서비스는 nginx-gw 서비스로도 알려져 있습니다.
 a| 
관리자 및 게이트웨이 노드



 a| 
LDR(Local Distribution Router)
 a| 
그리드 내에서 콘텐츠의 저장과 전송을 관리합니다.
 a| 
저장 노드



 a| 
MISCd 정보 서비스 제어 데몬
 a| 
다른 노드의 서비스를 쿼리하고 관리하고, 다른 노드에서 실행 중인 서비스의 상태를 쿼리하는 등 노드의 환경 구성을 관리하기 위한 인터페이스를 제공합니다.
 a| 
모든 노드



 a| 
nginx
 a| 
다양한 그리드 서비스(예: Prometheus 및 Dynamic IP)가 HTTPS API를 통해 다른 노드의 서비스와 통신할 수 있도록 인증 및 보안 통신 메커니즘 역할을 합니다.
 a| 
모든 노드



 a| 
nginx-gw
 a| 
로드 밸런서 서비스에 전원을 공급합니다.
 a| 
관리자 및 게이트웨이 노드



 a| 
NMS(네트워크 관리 시스템)
 a| 
Grid Manager를 통해 표시되는 모니터링, 보고 및 구성 옵션에 전원을 공급합니다.
 a| 
관리 노드



 a| 
고집
 a| 
재부팅 후에도 유지되어야 하는 루트 디스크의 파일을 관리합니다.
 a| 
모든 노드



 a| 
프로메테우스
 a| 
모든 노드의 서비스에서 시계열 지표를 수집합니다.
 a| 
관리 노드



 a| 
RSM(복제 상태 머신)
 a| 
플랫폼 서비스 요청이 각각의 엔드포인트로 전송되도록 보장합니다.
 a| 
ADC 서비스를 사용하는 스토리지 노드



 a| 
SSM(서버 상태 모니터)
 a| 
하드웨어 상태를 모니터링하고 NMS 서비스에 보고합니다.
 a| 
모든 그리드 노드에 인스턴스가 존재합니다.



 a| 
트레이스 수집기
 a| 
기술 지원에 사용할 정보를 수집하기 위해 추적 수집을 수행합니다.  추적 수집 서비스는 오픈 소스 Jaeger 소프트웨어를 사용합니다.
 a| 
관리 노드

|===