---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: 저장 노드는 개체 데이터와 메타데이터를 관리하고 저장합니다.  저장 노드에는 디스크에 있는 개체 데이터와 메타데이터를 저장, 이동, 검증 및 검색하는 데 필요한 서비스와 프로세스가 포함됩니다. 
---
= 저장 노드란 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
저장 노드는 개체 데이터와 메타데이터를 관리하고 저장합니다.  저장 노드에는 디스크에 있는 개체 데이터와 메타데이터를 저장, 이동, 검증 및 검색하는 데 필요한 서비스와 프로세스가 포함됩니다.

StorageGRID 시스템의 각 사이트에는 최소 3개의 스토리지 노드가 있어야 합니다.



== 저장 노드 유형

설치 중에 설치할 스토리지 노드 유형을 선택할 수 있습니다.  이러한 유형은 소프트웨어 기반 스토리지 노드와 해당 기능을 지원하는 어플라이언스 기반 스토리지 노드에서 사용할 수 있습니다.

* 결합된 데이터 및 메타데이터 저장 노드
* 메타데이터 전용 스토리지 노드
* 데이터 전용 스토리지 노드


다음과 같은 상황에서 스토리지 노드 유형을 선택할 수 있습니다.

* 스토리지 노드를 처음 설치할 때
* StorageGRID 시스템 확장 중에 스토리지 노드를 추가하는 경우



NOTE: 스토리지 노드 설치가 완료된 후에는 유형을 변경할 수 없습니다.

데이터 및 메타데이터 저장 노드(결합):: 기본적으로 모든 새 스토리지 노드는 개체 데이터와 메타데이터를 모두 저장합니다.  이러한 유형의 저장 노드를 _결합_ 저장 노드라고 합니다.
메타데이터 전용 스토리지 노드:: 그리드에 많은 수의 작은 객체가 저장되어 있는 경우 메타데이터 전용으로 스토리지 노드를 사용하는 것이 합리적일 수 있습니다.  전용 메타데이터 용량을 설치하면 매우 많은 수의 작은 객체에 필요한 공간과 해당 객체의 메타데이터에 필요한 공간 간의 균형을 더 잘 맞출 수 있습니다.  또한, 고성능 어플라이언스에서 호스팅되는 메타데이터 전용 스토리지 노드는 성능을 높일 수 있습니다.


메타데이터 전용 스토리지 노드에는 특정 하드웨어 요구 사항이 있습니다.

* StorageGRID 어플라이언스를 사용하는 경우, 메타데이터 전용 노드는 12개의 1.9TB 또는 12개의 3.8TB 드라이브가 있는 SGF6112 어플라이언스에서만 구성할 수 있습니다.
* 소프트웨어 기반 노드를 사용하는 경우 메타데이터 전용 노드 리소스는 기존 스토리지 노드 리소스와 일치해야 합니다. 예를 들어:
+
** 기존 StorageGRID 사이트에서 SG6000 또는 SG6100 어플라이언스를 사용하는 경우 소프트웨어 기반 메타데이터 전용 노드는 다음 최소 요구 사항을 충족해야 합니다.
+
*** 128GB 램
*** 8코어 CPU
*** Cassandra 데이터베이스(rangedb/0)용 8TB SSD 또는 동급 스토리지


** 기존 StorageGRID 사이트가 24GB RAM, 8코어 CPU, 3TB 또는 4TB의 메타데이터 스토리지를 갖춘 가상 스토리지 노드를 사용하는 경우, 소프트웨어 기반 메타데이터 전용 노드는 비슷한 리소스(24GB RAM, 8코어 CPU, 4TB의 메타데이터 스토리지(rangedb/0))를 사용해야 합니다.


* 새로운 StorageGRID 사이트를 추가할 때, 새로운 사이트의 총 메타데이터 용량은 최소한 기존 StorageGRID 사이트와 일치해야 하며, 새로운 사이트 리소스는 기존 StorageGRID 사이트의 스토리지 노드와 일치해야 합니다.


메타데이터 전용 노드를 설치하는 경우 그리드에는 데이터 저장을 위한 최소 노드 수도 포함되어야 합니다.

* 단일 사이트 그리드의 경우 최소 두 개의 결합된 스토리지 노드나 데이터 전용 스토리지 노드를 구성합니다.
* 다중 사이트 그리드의 경우 사이트당 하나 이상의 결합형 또는 데이터 전용 스토리지 노드를 구성합니다.



NOTE: 메타데이터 전용 스토리지 노드에는 다음이 포함되어 있습니다.<<ldr-service,LDR 서비스>> S3 클라이언트 요청을 처리할 수 있지만 StorageGRID 성능은 향상되지 않을 수 있습니다.

데이터 전용 스토리지 노드:: 스토리지 노드의 성능 특성이 서로 다른 경우, 데이터 전용으로 스토리지 노드를 사용하는 것이 합리적일 수 있습니다.  예를 들어, 성능을 잠재적으로 높이기 위해 데이터 전용 고용량 회전 디스크 스토리지 노드와 메타데이터 전용 고성능 스토리지 노드를 함께 사용할 수 있습니다.


데이터 전용 노드를 설치할 때 그리드에는 다음이 포함되어야 합니다.

* 그리드당 최소 2개의 결합형 또는 데이터 전용 스토리지 노드
* 사이트당 최소 하나의 결합형 또는 데이터 전용 스토리지 노드
* 사이트당 최소 3개의 결합형 또는 메타데이터 전용 스토리지 노드




== 스토리지 노드를 위한 기본 서비스

다음 표는 스토리지 노드의 주요 서비스를 보여줍니다. 그러나 이 표는 모든 노드 서비스를 나열한 것은 아닙니다.


NOTE: ADC 서비스 및 RSM 서비스와 같은 일부 서비스는 일반적으로 각 사이트의 3개 스토리지 노드에만 존재합니다.

[cols="1a,3a"]
|===
| 서비스 | 주요 기능 


 a| 
계정(acct)
 a| 
세입자 계정을 관리합니다.



 a| 
관리 도메인 컨트롤러(ADC)
 a| 
토폴로지와 그리드 전체 구성을 유지합니다.

*참고*: 데이터 전용 스토리지 노드는 ADC 서비스를 호스팅하지 않습니다.

.세부
[%collapsible]
====
ADC(관리 도메인 컨트롤러) 서비스는 그리드 노드와 노드 간의 연결을 인증합니다.  ADC 서비스는 사이트의 최소 3개 스토리지 노드에 호스팅됩니다.

ADC 서비스는 서비스의 위치와 가용성을 포함한 토폴로지 정보를 유지 관리합니다.  그리드 노드가 다른 그리드 노드로부터 정보를 요청하거나 다른 그리드 노드가 수행해야 할 작업이 있는 경우, 해당 노드는 ADC 서비스에 접속하여 요청을 처리할 최적의 그리드 노드를 찾습니다.  또한 ADC 서비스는 StorageGRID 배포 구성 번들의 사본을 보관하므로 모든 그리드 노드가 현재 구성 정보를 검색할 수 있습니다.

분산되고 고립된 운영을 용이하게 하기 위해 각 ADC 서비스는 인증서, 구성 번들, 서비스 및 토폴로지에 대한 정보를 StorageGRID 시스템의 다른 ADC 서비스와 동기화합니다.

일반적으로 모든 그리드 노드는 최소한 하나의 ADC 서비스에 대한 연결을 유지합니다.  이를 통해 그리드 노드가 항상 최신 정보에 액세스할 수 있습니다.  그리드 노드가 연결되면 다른 그리드 노드의 인증서를 캐시하여 ADC 서비스를 사용할 수 없는 경우에도 시스템이 알려진 그리드 노드로 계속 작동할 수 있도록 합니다.  새로운 그리드 노드는 ADC 서비스를 사용해서만 연결을 설정할 수 있습니다.

각 그리드 노드의 연결을 통해 ADC 서비스는 토폴로지 정보를 수집할 수 있습니다.  이 그리드 노드 정보에는 CPU 부하, 사용 가능한 디스크 공간(저장 장치가 있는 경우), 지원되는 서비스, 그리드 노드의 사이트 ID가 포함됩니다.  다른 서비스는 토폴로지 쿼리를 통해 ADC 서비스에 토폴로지 정보를 요청합니다.  ADC 서비스는 StorageGRID 시스템에서 수신한 최신 정보로 각 쿼리에 응답합니다.

====


 a| 
카산드라
 a| 
개체 메타데이터를 저장하고 보호합니다.

*참고*: 데이터 전용 스토리지 노드는 Cassandra 서비스를 호스팅하지 않습니다.



 a| 
카산드라 리퍼
 a| 
개체 메타데이터의 자동 복구를 수행합니다.

*참고*: 데이터 전용 스토리지 노드는 Cassandra Reaper 서비스를 호스팅하지 않습니다.



 a| 
큰 덩어리
 a| 
삭제된 데이터와 패리티 조각을 관리합니다.



 a| 
데이터 무버(DMV)
 a| 
데이터를 클라우드 스토리지 풀로 이동합니다.



 a| 
분산 데이터 저장소(DDS)
 a| 
개체 메타데이터 저장소를 모니터링합니다.

.세부
[%collapsible]
====
각 스토리지 노드에는 DDS(분산 데이터 저장소) 서비스가 포함되어 있습니다.  이 서비스는 Cassandra 데이터베이스와 인터페이스하여 StorageGRID 시스템에 저장된 개체 메타데이터에 대한 백그라운드 작업을 수행합니다.

DDS 서비스는 StorageGRID 시스템에 수집된 총 객체 수와 시스템의 지원 인터페이스(S3)를 통해 수집된 총 객체 수를 추적합니다.

====


 a| 
정체성(idnt)
 a| 
LDAP와 Active Directory의 사용자 ID를 연합합니다.



 a| 
[[ldr-service]]로컬 배포 라우터(LDR)
 a| 
개체 스토리지 프로토콜 요청을 처리하고 디스크의 개체 데이터를 관리합니다.

.세부
[%collapsible]
====
각 _결합_, _데이터 전용_, _메타데이터 전용_ 스토리지 노드에는 LDR(Local Distribution Router) 서비스가 포함되어 있습니다.  이 서비스는 데이터 저장, 라우팅, 요청 처리를 포함한 콘텐츠 전송 기능을 처리합니다.  LDR 서비스는 데이터 전송 부하와 데이터 트래픽 기능을 처리하여 StorageGRID 시스템의 대부분의 어려운 작업을 수행합니다.

LDR 서비스는 다음과 같은 작업을 처리합니다.

* 쿼리
* 정보 수명 주기 관리(ILM) 활동
* 객체 삭제
* 객체 데이터 저장소
* 다른 LDR 서비스(저장 노드)에서 개체 데이터 전송
* 데이터 저장 관리
* S3 프로토콜 인터페이스


LDR 서비스는 또한 각 S3 객체를 고유한 UUID에 매핑합니다.

객체 저장소:: LDR 서비스의 기본 데이터 저장소는 고정된 수의 개체 저장소(저장 볼륨이라고도 함)로 나뉩니다.  각 개체 저장소는 별도의 마운트 지점입니다.
+
--
스토리지 노드에 저장된 객체는 0000~002F까지의 16진수로 식별되며, 이를 볼륨 ID라고 합니다.  Cassandra 데이터베이스의 개체 메타데이터를 위해 첫 번째 개체 저장소(볼륨 0)에 공간이 예약되어 있습니다. 해당 볼륨에 남아 있는 공간은 개체 데이터에 사용됩니다.  다른 모든 객체 저장소는 복제된 사본과 삭제 코드화된 조각을 포함하는 객체 데이터에만 사용됩니다.

복제된 복사본의 공간 사용을 균일하게 보장하기 위해, 주어진 객체의 객체 데이터는 사용 가능한 저장 공간에 따라 하나의 객체 저장소에 저장됩니다.  객체 저장소가 용량에 가득 차면, 나머지 객체 저장소는 스토리지 노드에 더 이상 공간이 없을 때까지 객체를 계속 저장합니다.

--
메타데이터 보호:: StorageGRID LDR 서비스와 인터페이스하는 Cassandra 데이터베이스에 개체 메타데이터를 저장합니다.
+
--
중복성을 보장하고 손실을 방지하기 위해 각 사이트에 개체 메타데이터 사본 3개가 유지됩니다.  이 복제는 구성할 수 없으며 자동으로 수행됩니다. 자세한 내용은 다음을 참조하십시오. link:../admin/managing-object-metadata-storage.html["개체 메타데이터 저장소 관리"] .

--


====


 a| 
복제 상태 머신(RSM)
 a| 
S3 플랫폼 서비스 요청이 해당 엔드포인트로 전송되도록 보장합니다.



 a| 
서버 상태 모니터(SSM)
 a| 
운영체제와 기반 하드웨어를 모니터링합니다.

|===