---
permalink: primer/what-gateway-node-is.html 
sidebar: sidebar 
keywords: gateway nodes, api gateway 
summary: 게이트웨이 노드는 S3 클라이언트 애플리케이션이 StorageGRID 에 연결하는 데 사용할 수 있는 전용 부하 분산 인터페이스를 제공합니다.  부하 분산은 작업 부하를 여러 스토리지 노드에 분산시켜 속도와 연결 용량을 극대화합니다.  게이트웨이 노드는 선택 사항입니다. 
---
= 게이트웨이 노드란 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
게이트웨이 노드는 S3 클라이언트 애플리케이션이 StorageGRID 에 연결하는 데 사용할 수 있는 전용 부하 분산 인터페이스를 제공합니다.  부하 분산은 작업 부하를 여러 스토리지 노드에 분산시켜 속도와 연결 용량을 극대화합니다.  게이트웨이 노드는 선택 사항입니다.

StorageGRID 로드 밸런서 서비스는 모든 관리 노드와 모든 게이트웨이 노드에서 제공됩니다.  클라이언트 요청에 대한 TLS(전송 계층 보안) 종료를 수행하고, 요청을 검사하고, 스토리지 노드에 대한 새로운 보안 연결을 설정합니다.  로드 밸런서 서비스는 클라이언트를 최적의 스토리지 노드로 원활하게 연결하므로 노드나 전체 사이트의 장애가 투명하게 드러납니다.

게이트웨이 및 관리 노드의 로드 밸런서 서비스에 액세스하는 데 들어오는 클라이언트 요청과 나가는 클라이언트 요청이 사용할 포트 및 네트워크 프로토콜(HTTPS 또는 HTTP)을 정의하기 위해 하나 이상의 로드 밸런서 엔드포인트를 구성합니다.  로드 밸런서 엔드포인트는 클라이언트 유형(S3), 바인딩 모드, 선택적으로 허용 또는 차단된 테넌트 목록도 정의합니다. 보다 link:../admin/managing-load-balancing.html["부하 분산을 위한 고려 사항"] .

필요에 따라 여러 게이트웨이 노드와 관리 노드의 네트워크 인터페이스를 고가용성(HA) 그룹으로 그룹화할 수 있습니다.  HA 그룹의 활성 인터페이스에 장애가 발생하면 백업 인터페이스가 클라이언트 애플리케이션 작업 부하를 관리할 수 있습니다. 보다 link:../admin/managing-high-availability-groups.html["고가용성(HA) 그룹 관리"] .



== 게이트웨이 노드를 위한 기본 서비스

다음 표는 게이트웨이 노드의 주요 서비스를 보여줍니다. 그러나 이 표는 모든 노드 서비스를 나열한 것은 아닙니다.

[cols="1a,2a"]
|===
| 서비스 | 주요 기능 


 a| 
고가용성
 a| 
관리 노드와 게이트웨이 노드 그룹에 대한 고가용성 가상 IP 주소를 관리합니다.

*참고:* 이 서비스는 관리 노드에서도 찾을 수 있습니다.



 a| 
로드 밸런서
 a| 
클라이언트에서 스토리지 노드로의 S3 트래픽에 대해 레이어 7 로드 밸런싱을 제공합니다.  이는 권장되는 부하 분산 메커니즘입니다.

*참고:* 이 서비스는 관리 노드에서도 찾을 수 있습니다.



 a| 
서버 상태 모니터(SSM)
 a| 
운영체제와 기반 하드웨어를 모니터링합니다.

|===