---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 관리 노드는 시스템 구성, 모니터링, 로깅과 같은 관리 서비스를 제공합니다.  관리 노드는 S3 클라이언트 트래픽의 부하를 분산하는 데에도 사용할 수 있습니다.  각 그리드에는 하나의 기본 관리 노드가 있어야 하며 중복성을 위해 기본이 아닌 관리 노드를 원하는 수만큼 가질 수 있습니다. 
---
= 관리 노드란 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 노드는 시스템 구성, 모니터링, 로깅과 같은 관리 서비스를 제공합니다.  관리 노드는 S3 클라이언트 트래픽의 부하를 분산하는 데에도 사용할 수 있습니다.  각 그리드에는 하나의 기본 관리 노드가 있어야 하며 중복성을 위해 기본이 아닌 관리 노드를 원하는 수만큼 가질 수 있습니다.



== 기본 및 비기본 관리 노드 간의 차이점

Grid Manager 또는 Tenant Manager에 로그인하면 관리 노드에 연결됩니다. 모든 관리 노드에 연결할 수 있으며, 각 관리 노드에는 StorageGRID 시스템의 유사한 보기가 표시됩니다. 하지만 기본 관리 노드는 기본이 아닌 관리 노드보다 더 많은 기능을 제공합니다. 예를 들어, 대부분의 유지 관리 절차는 기본 관리 노드에서 수행해야 합니다.

이 표는 기본 및 비기본 관리 노드의 기능을 요약한 것입니다.

[cols="2a,1a,1a"]
|===
| 역량 | 기본 관리 노드 | 기본이 아닌 관리 노드 


 a| 
포함<<ams,AMS>> 서비스
 a| 
예
 a| 
예



 a| 
포함<<cmn,씨엠엔>> 서비스
 a| 
예
 a| 
아니요



 a| 
포함<<nms,NMS>> 서비스
 a| 
예
 a| 
예



 a| 
포함<<prometheus,프로메테우스>> 서비스
 a| 
예
 a| 
예



 a| 
포함<<ssm,SSM>> 서비스
 a| 
예
 a| 
예



 a| 
포함<<load-balancer,로드 밸런서>> 그리고<<high-availability,고가용성>> 서비스
 a| 
예
 a| 
예



 a| 
지원합니다<<mgmt-api,관리 애플리케이션 프로그램 인터페이스>> (관리-API)
 a| 
예
 a| 
예



 a| 
예를 들어 IP 주소 변경 및 NTP 서버 업데이트 등 모든 네트워크 관련 유지 관리 작업에 사용할 수 있습니다.
 a| 
예
 a| 
아니요



 a| 
스토리지 노드 확장 후 EC 리밸런싱을 수행할 수 있습니다.
 a| 
예
 a| 
아니요



 a| 
볼륨 회복 시술에 사용 가능
 a| 
예
 a| 
예



 a| 
하나 이상의 노드에서 로그 파일과 시스템 데이터를 수집할 수 있습니다.
 a| 
예
 a| 
아니요



 a| 
경고 알림, AutoSupport 패키지 및 SNMP 트랩을 전송하고 알려줍니다.
 a| 
네. 역할을 합니다<<preferred-sender,선호하는 발신자>> .
 a| 
네. 대기 발신자 역할을 합니다.

|===


== [[preferred-sender]]선호 발신자 관리 노드

StorageGRID 배포에 여러 관리 노드가 포함된 경우 기본 관리 노드는 경고 알림, AutoSupport 패키지, SNMP 트랩 및 정보를 보내는 기본 발신자입니다.

일반적인 시스템 작동에서는 선호하는 발신자만 알림을 보냅니다. 하지만 다른 모든 관리 노드는 선호하는 발신자를 모니터링합니다. 문제가 감지되면 다른 관리 노드가 _대기 발신자_ 역할을 합니다.

다음의 경우 여러 개의 알림이 전송될 수 있습니다.

* 관리 노드가 서로 "고립"되면 기본 발신자와 대기 발신자가 모두 알림을 보내려고 시도하며 알림 사본이 여러 개 수신될 수 있습니다.
* 대기 발신자가 기본 발신자에게서 문제를 감지하고 알림을 보내기 시작하면 기본 발신자가 알림을 보낼 수 있는 기능을 회복할 수 있습니다. 이런 경우 알림이 중복해서 전송될 수 있습니다. 대기 발신자는 기본 발신자에서 더 이상 오류를 감지하지 못하면 알림 전송을 중단합니다.
+

NOTE: AutoSupport 패키지를 테스트하면 모든 관리 노드가 테스트를 보냅니다.  알림 알림을 테스트할 때는 모든 관리 노드에 로그인하여 연결 상태를 확인해야 합니다.





== 관리 노드를 위한 기본 서비스

다음 표는 관리 노드의 기본 서비스를 보여줍니다. 그러나 이 표는 모든 노드 서비스를 나열한 것은 아닙니다.

[cols="1a,2a"]
|===
| 서비스 | 주요 기능 


 a| 
[[ams]]감사 관리 시스템(AMS)
 a| 
시스템 활동과 이벤트를 추적합니다.



 a| 
[[cmn]]구성 관리 노드(CMN)
 a| 
시스템 전체의 구성을 관리합니다.



 a| 
[[고가용성]]고가용성
 a| 
관리 노드와 게이트웨이 노드 그룹에 대한 고가용성 가상 IP 주소를 관리합니다.

*참고:* 이 서비스는 게이트웨이 노드에서도 찾을 수 있습니다.



 a| 
[[로드 밸런서]]로드 밸런서
 a| 
클라이언트에서 스토리지 노드로의 S3 트래픽에 대한 부하 분산을 제공합니다.

*참고:* 이 서비스는 게이트웨이 노드에서도 찾을 수 있습니다.



 a| 
[[mgmt-api]]관리 애플리케이션 프로그램 인터페이스(mgmt-api)
 a| 
Grid Management API와 Tenant Management API의 요청을 처리합니다.



 a| 
[[nms]]네트워크 관리 시스템(NMS)
 a| 
그리드 관리자에 대한 기능을 제공합니다.



 a| 
[[프로메테우스]]프로메테우스
 a| 
모든 노드의 서비스에서 시계열 지표를 수집하고 저장합니다.



 a| 
[[ssm]]서버 상태 모니터(SSM)
 a| 
운영체제와 기반 하드웨어를 모니터링합니다.

|===