---
permalink: expand/adding-storage-capacity-for-replicated-objects.html 
sidebar: sidebar 
keywords: replication, replicated, copies, capacity, storage nodes, expand, expansion 
summary: '배포에 대한 정보 수명 주기 관리(ILM) 정책에 개체의 복제본을 만드는 규칙이 포함된 경우 추가할 스토리지 양과 새 스토리지 볼륨 또는 스토리지 노드를 추가할 위치를 고려해야 합니다.' 
---
= 복제된 객체에 대한 저장 용량 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
배포에 대한 정보 수명 주기 관리(ILM) 정책에 개체의 복제본을 만드는 규칙이 포함된 경우 추가할 스토리지 용량과 새 스토리지 볼륨 또는 스토리지 노드를 추가할 위치를 고려해야 합니다.

추가 스토리지를 추가할 위치에 대한 지침은 복제된 복사본을 만드는 ILM 규칙을 살펴보세요.  ILM 규칙에 따라 두 개 이상의 개체 복사본이 생성되는 경우 개체 복사본이 만들어진 각 위치에 저장소를 추가하도록 계획하세요.  간단한 예로, 두 사이트 그리드와 각 사이트에 하나의 개체 복사본을 생성하는 ILM 규칙이 있는 경우 다음을 수행해야 합니다.link:../expand/adding-storage-volumes-to-storage-nodes.html["저장 공간 추가"] 그리드의 전체 객체 용량을 늘리기 위해 각 사이트에 추가했습니다.  객체 복제에 대한 정보는 다음을 참조하세요.link:../ilm/what-replication-is.html["복제란 무엇인가"] .

성능상의 이유로, 사이트 전체에서 저장 용량과 컴퓨팅 성능을 균형 있게 유지해야 합니다.  따라서 이 예에서는 각 사이트에 동일한 수의 스토리지 노드를 추가하거나 각 사이트에 추가 스토리지 볼륨을 추가해야 합니다.

버킷 이름과 같은 기준에 따라 객체를 다른 위치에 배치하는 규칙이나 시간 경과에 따라 객체 위치를 변경하는 규칙이 포함된 보다 복잡한 ILM 정책이 있는 경우 확장에 필요한 스토리지 위치에 대한 분석은 비슷하지만 더 복잡해집니다.

전체 저장 용량이 얼마나 빨리 소모되는지 차트로 표시하면 확장 시 얼마나 많은 저장 공간을 추가해야 하는지, 그리고 추가 저장 공간이 언제 필요한지 파악하는 데 도움이 됩니다.  Grid Manager를 사용하여 다음을 수행할 수 있습니다.link:../monitor/monitoring-storage-capacity.html["모니터 및 차트 저장 용량"] .

확장 시기를 계획할 때, 추가 저장 공간을 조달하고 설치하는 데 얼마나 걸릴지도 고려해야 합니다.
