---
permalink: expand/adding-new-site.html 
sidebar: sidebar 
keywords: expand, expansion, new site, add site, guidelines 
summary: 새로운 사이트를 추가하여 StorageGRID 시스템을 확장할 수 있습니다. 
---
= 새로운 사이트 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로운 사이트를 추가하여 StorageGRID 시스템을 확장할 수 있습니다.



== 사이트 추가 지침

사이트를 추가하기 전에 다음 요구 사항과 제한 사항을 검토하세요.

* 확장 작업당 하나의 사이트만 추가할 수 있습니다.
* 동일한 확장의 일부로 기존 사이트에 그리드 노드를 추가할 수 없습니다.
* 모든 사이트에는 최소 3개의 스토리지 노드가 포함되어야 합니다.
* 새로운 사이트를 추가해도 저장할 수 있는 개체 수가 자동으로 늘어나지는 않습니다.  그리드의 총 객체 용량은 사용 가능한 저장 용량, ILM 정책 및 각 사이트의 메타데이터 용량에 따라 달라집니다.
* 새로운 사이트의 크기를 조정할 때는 충분한 메타데이터 용량이 포함되어 있는지 확인해야 합니다.
+
StorageGRID 모든 사이트의 모든 개체 메타데이터 사본을 보관합니다.  새로운 사이트를 추가할 때는 기존 개체 메타데이터를 위한 충분한 메타데이터 용량과 성장에 대비한 충분한 메타데이터 용량이 포함되어 있는지 확인해야 합니다.

+
자세한 내용은 다음을 참조하세요.

+
** link:../admin/managing-object-metadata-storage.html["개체 메타데이터 저장소 관리"]
** link:../monitor/monitoring-storage-capacity.html#monitor-object-metadata-capacity-for-each-storage-node["각 스토리지 노드에 대한 개체 메타데이터 용량 모니터링"]


* 사이트 간의 사용 가능한 네트워크 대역폭과 네트워크 지연 수준을 고려해야 합니다.  모든 개체가 수집된 사이트에만 저장되어 있더라도 메타데이터 업데이트는 사이트 간에 지속적으로 복제됩니다.
* 확장 중에도 StorageGRID 시스템은 계속 작동하므로 확장 절차를 시작하기 전에 ILM 규칙을 검토해야 합니다.  확장 절차가 완료될 때까지 개체 사본이 새 사이트에 저장되지 않도록 해야 합니다.
+
예를 들어, 확장을 시작하기 전에 기본 스토리지 풀(모든 스토리지 노드)을 사용하는 규칙이 있는지 확인하세요.  그렇다면 기존 스토리지 노드를 포함하는 새 스토리지 풀을 만들고 ILM 규칙을 업데이트하여 새 스토리지 풀을 사용해야 합니다.  그렇지 않으면 해당 사이트의 첫 번째 노드가 활성화되자마자 객체가 새 사이트로 복사됩니다.

+
새 사이트를 추가할 때 ILM을 변경하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:../ilm/example-6-changing-ilm-policy.html["ILM 정책 변경 예"] .


