---
permalink: expand/adding-storage-capacity-for-erasure-coded-objects.html 
sidebar: sidebar 
keywords: erasure coding, capacity, storage nodes, ec, expand, expansion 
summary: ILM 정책에 삭제 코드가 적용된 복사본을 만드는 규칙이 포함된 경우 새 스토리지를 추가할 위치와 새 스토리지를 추가할 시기를 계획해야 합니다.  추가하는 저장 용량과 추가 시점은 그리드의 사용 가능한 저장 용량에 영향을 미칠 수 있습니다. 
---
= 삭제된 객체에 대한 저장 용량 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 정책에 삭제 코드가 적용된 복사본을 만드는 규칙이 포함된 경우 새 스토리지를 추가할 위치와 새 스토리지를 추가할 시기를 계획해야 합니다.  추가하는 저장 용량과 추가 시점은 그리드의 사용 가능한 저장 용량에 영향을 미칠 수 있습니다.

저장소 확장을 계획하는 첫 번째 단계는 ILM 정책에서 삭제 코드화된 객체를 생성하는 규칙을 검토하는 것입니다.  StorageGRID 삭제된 모든 객체에 대해 _k+m_개의 조각을 생성하고 각 조각을 다른 스토리지 노드에 저장하므로 확장 후에 최소 _k+m_개의 스토리지 노드에 삭제된 새로운 데이터를 위한 공간이 있는지 확인해야 합니다.  삭제 코딩 프로필이 사이트 손실 보호 기능을 제공하는 경우 각 사이트에 저장소를 추가해야 합니다.  보다link:../ilm/what-erasure-coding-schemes-are.html["삭제 코딩 방식이란 무엇입니까?"] 삭제 코딩 프로필에 대한 정보입니다.

추가해야 하는 노드 수는 확장을 수행할 때 기존 노드가 얼마나 채워졌는지에 따라 달라집니다.



== 삭제된 객체에 대한 저장 용량 추가를 위한 일반적인 권장 사항

자세한 계산을 피하고 싶다면 기존 스토리지 노드가 용량의 70%에 도달하면 사이트당 스토리지 노드를 두 개 추가할 수 있습니다.

이 일반적인 권장 사항은 단일 사이트 그리드와 삭제 코딩이 사이트 손실 보호 기능을 제공하는 그리드 모두에 대해 광범위한 삭제 코딩 체계에 걸쳐 합리적인 결과를 제공합니다.

이 권장 사항을 도출한 요인을 더 잘 이해하거나 사이트에 대한 보다 정확한 계획을 개발하려면 다음을 참조하세요.link:considerations-for-rebalancing-erasure-coded-data.html["삭제된 코드화된 데이터의 재조정을 위한 고려 사항"] .  귀하의 상황에 최적화된 맞춤형 권장 사항을 원하시면 NetApp Professional Services 컨설턴트에게 문의하세요.
