---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 확장 절차를 통해 새로운 관리 노드를 추가하면 AMS 서비스는 시스템에 가입한 후 발생하는 이벤트와 작업만 기록합니다. 필요에 따라 이전에 설치된 관리 노드에서 감사 로그를 새 확장 관리 노드로 복사하여 StorageGRID 시스템의 나머지 부분과 동기화할 수 있습니다. 
---
= 감사 로그 복사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장 절차를 통해 새로운 관리 노드를 추가하면 AMS 서비스는 시스템에 가입한 후 발생하는 이벤트와 작업만 기록합니다. 필요에 따라 이전에 설치된 관리 노드에서 감사 로그를 새 확장 관리 노드로 복사하여 StorageGRID 시스템의 나머지 부분과 동기화할 수 있습니다.

.시작하기 전에
* 관리 노드를 추가하는 데 필요한 확장 단계를 완료했습니다.
* 당신은 가지고있다 `Passwords.txt` 파일.


.이 작업에 관하여
새로운 관리 노드에서 과거 감사 메시지를 사용하려면 기존 관리 노드에서 확장 관리 노드로 감사 로그 파일을 수동으로 복사해야 합니다.

[NOTE]
====
기본적으로 감사 정보는 관리 노드의 감사 로그로 전송됩니다.  다음 중 하나에 해당되는 경우 이 단계를 건너뛸 수 있습니다.

* 외부 syslog 서버를 구성했고 감사 로그가 이제 관리 노드가 아닌 syslog 서버로 전송됩니다.
* 감사 메시지는 이를 생성한 로컬 노드에만 저장되어야 한다고 명시적으로 지정했습니다.


보다link:../monitor/configure-audit-messages.html["감사 메시지 및 로그 대상 구성"] 자세한 내용은.

====
.단계
. 기본 관리 노드에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh _admin@_primary_Admin_Node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. AMS 서비스를 중지하여 새 파일을 생성하지 못하도록 합니다. `service ams stop`
. 감사 내보내기 디렉토리로 이동합니다.
+
`cd /var/local/log`

. 소스 이름 바꾸기 `audit.log` 파일을 복사하여 확장 관리 노드의 파일을 덮어쓰지 않도록 하려면 다음 파일을 확인하세요.
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. 모든 감사 로그 파일을 확장 관리 노드의 대상 위치로 복사합니다.
+
`scp -p * _IP_address_:/var/local/log`

. 암호를 입력하라는 메시지가 표시되면 `/root/.ssh/id_rsa` , 기본 관리 노드에 대한 SSH 액세스 암호를 입력하십시오. `Passwords.txt` 파일.
. 원본을 복원하다 `audit.log` 파일:
+
`mv _new_name_.txt audit.log`

. AMS 서비스를 시작합니다:
+
`service ams start`

. 서버에서 로그아웃:
+
`exit`

. 확장 관리 노드에 로그인하세요.
+
.. 다음 명령을 입력하세요: `ssh admin@_expansion_Admin_Node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. 감사 로그 파일에 대한 사용자 및 그룹 설정을 업데이트합니다.
+
`cd /var/local/log`

+
`chown ams-user:bycast *`

. 서버에서 로그아웃:
+
`exit`


