---
permalink: expand/copying-admin-node-database.html 
sidebar: sidebar 
keywords: copy Admin Node database, alert history, Admin Node expansion 
summary: 확장 절차를 통해 관리 노드를 추가할 때 선택적으로 기본 관리 노드에서 새 관리 노드로 데이터베이스를 복사할 수 있습니다.  데이터베이스를 복사하면 속성, 알림 및 경고에 대한 기록 정보를 보관할 수 있습니다. 
---
= 관리자 노드 데이터베이스 복사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장 절차를 통해 관리 노드를 추가할 때 선택적으로 기본 관리 노드에서 새 관리 노드로 데이터베이스를 복사할 수 있습니다.  데이터베이스를 복사하면 속성, 알림 및 경고에 대한 기록 정보를 보관할 수 있습니다.

.시작하기 전에
* 관리 노드를 추가하는 데 필요한 확장 단계를 완료했습니다.
* 당신은 가지고있다 `Passwords.txt` 파일.
* 프로비저닝 암호가 있습니다.


.이 작업에 관하여
StorageGRID 소프트웨어 활성화 프로세스에서는 확장 관리 노드의 NMS 서비스에 대한 빈 데이터베이스가 생성됩니다.  NMS 서비스가 확장 관리 노드에서 시작되면 현재 시스템에 속해 있거나 나중에 추가된 서버와 서비스에 대한 정보를 기록합니다.  이 관리 노드 데이터베이스에는 다음 정보가 포함되어 있습니다.

* 알림 내역
* 노드 페이지의 레거시 스타일 차트에 사용되는 과거 속성 데이터


관리 노드 데이터베이스가 노드 간에 일관성을 유지하도록 하려면 기본 관리 노드에서 확장 관리 노드로 데이터베이스를 복사하면 됩니다.


NOTE: 기본 관리 노드(__소스 관리 노드__)에서 확장 관리 노드로 데이터베이스를 복사하는 데는 최대 몇 시간이 걸릴 수 있습니다.  이 기간 동안에는 Grid Manager에 접근할 수 없습니다.

데이터베이스를 복사하기 전에 다음 단계를 사용하여 기본 관리 노드와 확장 관리 노드에서 MI 서비스와 관리 API 서비스를 중지합니다.

.단계
. 기본 관리 노드에서 다음 단계를 완료하세요.
+
.. 관리자 노드에 로그인하세요:
+
... 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
... 다음 명령을 입력하여 루트로 전환하세요. `su -`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.


.. 다음 명령을 실행하세요. `recover-access-points`
.. 프로비저닝 암호를 입력하세요.
.. MI 서비스를 중지합니다: `service mi stop`
.. 관리 애플리케이션 프로그램 인터페이스(mgmt-api) 서비스를 중지합니다. `service mgmt-api stop`


. 확장 관리 노드에서 다음 단계를 완료하세요.
+
.. 확장 관리 노드에 로그인하세요.
+
... 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
... 다음 명령을 입력하여 루트로 전환하세요. `su -`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.


.. MI 서비스를 중지합니다: `service mi stop`
.. mgmt-api 서비스를 중지합니다. `service mgmt-api stop`
.. SSH 에이전트에 SSH 개인 키를 추가합니다.  입력하다:``ssh-add``
.. SSH 접속 비밀번호를 입력하세요. `Passwords.txt` 파일.
.. 소스 관리 노드에서 확장 관리 노드로 데이터베이스를 복사합니다. `/usr/local/mi/bin/mi-clone-db.sh _Source_Admin_Node_IP_`
.. 메시지가 표시되면 확장 관리 노드에서 MI 데이터베이스를 덮어쓸지 확인합니다.
+
데이터베이스와 해당 기록 데이터는 확장 관리 노드로 복사됩니다.  복사 작업이 완료되면 스크립트가 확장 관리 노드를 시작합니다.

.. 더 이상 다른 서버에 암호 없이 액세스할 필요가 없으면 SSH 에이전트에서 개인 키를 제거하세요.  입력하다:``ssh-add -D``


. 기본 관리 노드에서 서비스를 다시 시작합니다. `service servermanager start`

