---
permalink: expand/guidelines-for-adding-object-capacity.html 
sidebar: sidebar 
keywords: adding storage capacity, guidelines, storage volumes, expansion 
summary: '기존 스토리지 노드에 스토리지 볼륨을 추가하거나 기존 사이트에 새로운 스토리지 노드를 추가하여 StorageGRID 시스템의 개체 스토리지 용량을 확장할 수 있습니다.  정보 수명 주기 관리(ILM) 정책의 요구 사항을 충족하는 방식으로 저장 용량을 추가해야 합니다.' 
---
= 객체 용량 추가를 위한 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 스토리지 노드에 스토리지 볼륨을 추가하거나 기존 사이트에 새로운 스토리지 노드를 추가하여 StorageGRID 시스템의 개체 스토리지 용량을 확장할 수 있습니다.  정보 수명 주기 관리(ILM) 정책의 요구 사항을 충족하는 방식으로 저장 용량을 추가해야 합니다.



== 스토리지 볼륨 추가를 위한 지침

기존 스토리지 노드에 스토리지 볼륨을 추가하기 전에 다음 지침과 제한 사항을 검토하세요.

* 현재 ILM 규칙을 검토하여 언제, 어디서 적용할지 결정해야 합니다.link:../expand/adding-storage-volumes-to-storage-nodes.html["스토리지 볼륨 추가"] 사용 가능한 저장 공간을 늘리려면link:../ilm/what-replication-is.html["복제된 객체"] 또는link:../ilm/what-erasure-coding-schemes-are.html["삭제된 코드화된 객체"] .
* 개체 메타데이터는 볼륨 0에만 저장되므로 저장소 볼륨을 추가하여 시스템의 메타데이터 용량을 늘릴 수 없습니다.
* 각 소프트웨어 기반 스토리지 노드는 최대 48개의 스토리지 볼륨을 지원할 수 있습니다.  그 이상의 용량을 추가해야 하는 경우 새로운 스토리지 노드를 추가해야 합니다.
* 각 SG6060 기기에 확장 선반을 1개 또는 2개 추가할 수 있습니다.  확장 선반 하나당 저장 용량이 16개 추가됩니다.  두 개의 확장 선반을 모두 설치하면 SG6060은 총 48개의 저장 용량을 지원할 수 있습니다.
* 각 SG6160 기기에 확장 선반을 1개 또는 2개 추가할 수 있습니다.  확장 선반 하나당 저장 용량 60개가 추가됩니다.  두 개의 확장 선반을 모두 설치하면 SG6160은 총 180개의 저장 용량을 지원할 수 있습니다.
* 다른 스토리지 어플라이언스에는 스토리지 볼륨을 추가할 수 없습니다.
* 기존 저장 볼륨의 크기를 늘릴 수 없습니다.
* 시스템 업그레이드, 복구 작업 또는 다른 확장을 수행하는 동안에는 스토리지 노드에 스토리지 볼륨을 추가할 수 없습니다.


스토리지 볼륨을 추가하기로 결정하고 ILM 정책을 충족하기 위해 확장해야 하는 스토리지 노드를 확인한 후 스토리지 노드 유형에 대한 지침을 따르세요.

* SG6060 스토리지 어플라이언스에 하나 또는 두 개의 확장 선반을 추가하려면 다음으로 이동하세요. https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/adding-expansion-shelf-to-deployed-sg6060.html["배치된 SG6060에 확장 선반 추가"^] .
* SG6160 스토리지 어플라이언스에 하나 또는 두 개의 확장 선반을 추가하려면 다음으로 이동하세요. https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/adding-expansion-shelf-to-deployed-sg6160.html["배치된 SG6160에 확장 선반 추가"^]
* 소프트웨어 기반 노드의 경우 다음 지침을 따르세요.link:adding-storage-volumes-to-storage-nodes.html["스토리지 노드에 스토리지 볼륨 추가"] .




== 스토리지 노드 추가 지침

기존 사이트에 스토리지 노드를 추가하기 전에 다음 지침과 제한 사항을 검토하세요.

* 사용 가능한 스토리지를 늘리기 위해 스토리지 노드를 추가할 위치와 시기를 결정하려면 현재 ILM 규칙을 검토해야 합니다.link:../ilm/what-replication-is.html["복제된 객체"] 또는link:../ilm/what-erasure-coding-schemes-are.html["삭제된 코드화된 객체"] .
* 단일 확장 절차에서 10개가 넘는 스토리지 노드를 추가하면 안 됩니다.
* 단일 확장 절차로 여러 사이트에 스토리지 노드를 추가할 수 있습니다.
* 단일 확장 절차로 스토리지 노드와 다른 유형의 노드를 추가할 수 있습니다.
* 확장 절차를 시작하기 전에 복구의 일부로 수행된 모든 데이터 복구 작업이 완료되었는지 확인해야 합니다. 보다 link:../maintain/checking-data-repair-jobs.html["데이터 복구 작업 확인"] .
* 확장을 수행하기 전이나 후에 스토리지 노드를 제거해야 하는 경우, 단일 해체 노드 절차에서 10개가 넘는 스토리지 노드를 해체해서는 안 됩니다.




== 스토리지 노드의 ADC 서비스에 대한 지침

확장을 구성할 때 각각의 새 스토리지 노드에 관리 도메인 컨트롤러(ADC) 서비스를 포함할지 여부를 선택해야 합니다. ADC 서비스는 그리드 서비스의 위치와 가용성을 추적합니다.

* StorageGRID 시스템에는 다음이 필요합니다.link:../maintain/understanding-adc-service-quorum.html["ADC 서비스 정족수"] 각 사이트에서 언제나 이용 가능합니다.
* 각 사이트의 최소 3개 스토리지 노드에는 ADC 서비스가 포함되어야 합니다.
* 모든 스토리지 노드에 ADC 서비스를 추가하는 것은 권장되지 않습니다.  ADC 서비스를 너무 많이 포함하면 노드 간 통신량이 늘어나 속도 저하가 발생할 수 있습니다.
* ADC 서비스를 사용하는 단일 그리드에는 48개를 초과하는 스토리지 노드가 있어서는 안 됩니다.  이는 각 사이트에 3개의 ADC 서비스가 있는 16개 사이트에 해당합니다.
* 일반적으로 새 노드에 대해 *ADC 서비스* 설정을 선택할 때 *자동*을 선택해야 합니다. 새 노드가 ADC 서비스를 포함하는 다른 스토리지 노드를 대체하는 경우에만 *예*를 선택하세요. 남아 있는 ADC 서비스가 너무 적으면 스토리지 노드를 해제할 수 없으므로, 이를 통해 기존 서비스가 제거되기 전에 새로운 ADC 서비스를 사용할 수 있습니다.
* 노드가 배포된 후에는 ADC 서비스를 노드에 추가할 수 없습니다.

