---
permalink: expand/rebalancing-erasure-coded-data-after-adding-storage-nodes.html 
sidebar: sidebar 
keywords: erasure coding, EC, rebalancing, site rebalance procedure 
summary: 스토리지 노드를 추가한 후에는 삭제 코딩 재조정 절차를 사용하여 삭제 코딩된 조각을 기존 및 새 스토리지 노드에 재분배할 수 있습니다. 
---
= 스토리지 노드 추가 후 삭제 코딩된 데이터 재조정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드를 추가한 후에는 EC(삭제 코딩) 재조정 절차를 사용하여 기존 및 새 스토리지 노드 간에 삭제 코딩된 조각을 재분배할 수 있습니다.

.시작하기 전에
* 새로운 스토리지 노드를 추가하기 위한 확장 단계를 완료했습니다.
* 당신은 검토했습니다link:considerations-for-rebalancing-erasure-coded-data.html["삭제된 데이터 재조정을 위한 고려 사항"] .
* 복제된 객체 데이터는 이 절차에 의해 이동되지 않으며 EC 재조정 절차는 삭제 코딩된 데이터를 이동할 위치를 결정할 때 각 스토리지 노드의 복제된 데이터 사용량을 고려하지 않는다는 점을 이해해야 합니다.
* 당신은 가지고있다 `Passwords.txt` 파일.


.이 절차가 실행되면 어떤 일이 발생합니까?
절차를 시작하기 전에 다음 사항을 참고하세요.

* 하나 이상의 볼륨이 오프라인(마운트 해제)이거나 온라인(마운트)이지만 오류 상태인 경우 EC 재조정 절차가 시작되지 않습니다.
* EC 재조정 절차는 일시적으로 많은 양의 저장 공간을 예약합니다.  저장소 알림이 발생할 수 있지만 재조정이 완료되면 해결됩니다.  예약에 필요한 저장 공간이 충분하지 않으면 EC 재조정 절차가 실패합니다.  EC 재조정 절차가 완료되면 절차가 실패했든 성공했든 스토리지 예약이 해제됩니다.
* EC 재조정 절차가 진행되는 동안 볼륨이 오프라인 상태가 되면 재조정 절차가 종료됩니다.  이미 이동된 모든 데이터 조각은 새로운 위치에 그대로 남아 있으며, 데이터는 손실되지 않습니다.
+
모든 볼륨이 다시 온라인 상태가 되면 절차를 다시 실행할 수 있습니다.

* EC 재조정 절차가 실행되는 동안 ILM 작업과 S3 클라이언트 작업의 성능에 영향을 줄 수 있습니다.
+

NOTE: EC 재조정 절차 중에 객체(또는 객체의 일부)를 업로드하는 S3 API 작업이 완료되는 데 24시간 이상 걸리는 경우 실패할 수 있습니다.  해당 ILM 규칙이 수집 시 균형 배치 또는 엄격한 배치를 사용하는 경우 장기 PUT 작업이 실패합니다.  다음 오류가 보고됩니다. `500 Internal Server Error` .

* 이 절차 동안 모든 노드의 저장 용량 제한은 80%입니다.  이 한도를 초과하지만 대상 데이터 파티션 아래에 저장하는 노드는 다음에서 제외됩니다.
+
** 사이트 불균형 값
** 모든 작업 완료 조건
+

NOTE: 대상 데이터 파티션은 사이트의 총 데이터를 노드 수로 나누어 계산합니다.



* *작업 완료 조건*.  다음 중 하나라도 해당되면 EC 재조정 절차가 완료된 것으로 간주됩니다.
+
** 더 이상 삭제된 데이터를 이동할 수 없습니다.
** 모든 노드의 데이터는 대상 데이터 파티션의 5% 편차 내에 있습니다.
** 해당 절차는 30일 동안 진행되었습니다.




.단계
. [[review_object_storage]]재조정하려는 사이트의 현재 개체 스토리지 세부 정보를 검토합니다.
+
.. *노드*를 선택하세요.
.. 사이트에서 첫 번째 스토리지 노드를 선택하세요.
.. *저장소* 탭을 선택하세요.
.. 저장소 노드에서 복제된 데이터와 삭제된 데이터의 현재 양을 확인하려면 커서를 사용된 저장소 - 개체 데이터 차트 위에 올려놓으세요.
.. 사이트의 다른 스토리지 노드를 보려면 이 단계를 반복합니다.


. 기본 관리 노드에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh admin@_primary_Admin_Node_IP_`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. 절차를 시작하세요:
+
`rebalance-data 시작 --사이트 "_사이트 이름_"

+
"_site-name_"에는 새 스토리지 노드를 추가한 첫 번째 사이트를 지정합니다.  넣다 `site-name` 따옴표로 묶어서.

+
EC 재조정 절차가 시작되고 작업 ID가 반환됩니다.

. 작업 ID를 복사합니다.
. [[view-status]]EC 재조정 절차의 상태를 모니터링합니다.
+
** 단일 EC 재조정 절차의 상태를 보려면:
+
`rebalance-data status --job-id _job-id_`

+
을 위한 `_job-id_` , 프로시저를 시작할 때 반환된 ID를 지정합니다.

** 현재 EC 재조정 절차와 이전에 완료된 절차의 상태를 보려면:
+
`rebalance-data status`

+
[NOTE]
====
rebalance-data 명령에 대한 도움말을 보려면:

`rebalance-data --help`

====


. 반환된 상태에 따라 추가 단계를 수행합니다.
+
** 만약에 `State` ~이다 `In progress` EC 리밸런싱 작업은 아직 진행 중입니다.  절차가 완료될 때까지 주기적으로 모니터링해야 합니다.
+
사용하다 `Site Imbalance` 사이트의 저장 노드에서 삭제 코드 데이터 사용량이 얼마나 불균형한지 평가하는 데 유용합니다.  이 값의 범위는 1.0~0이며, 0은 사이트의 모든 스토리지 노드에서 삭제 코딩 데이터 사용량이 완전히 균형을 이룬다는 것을 나타냅니다.

+
EC 재조정 작업은 완료된 것으로 간주되며 모든 노드의 데이터가 대상 데이터 파티션의 5% 편차 내에 있을 때 중지됩니다.

** 만약에 `State` ~이다 `Success` , 선택적으로<<review_object_storage,객체 스토리지 검토>> 사이트의 업데이트된 세부정보를 확인하세요.
+
삭제된 데이터는 이제 사이트의 저장 노드 간에 더 균형 있게 분포되었습니다.

** 만약에 `State` ~이다 `Failure` :
+
... 사이트의 모든 스토리지 노드가 그리드에 연결되어 있는지 확인하세요.
... 이러한 스토리지 노드에 영향을 줄 수 있는 경고를 확인하고 해결합니다.
... EC 재조정 절차를 다시 시작합니다.
+
`rebalance-data start –-job-id _job-id_`

... <<view-status,상태 보기>>새로운 절차의.  만약에 `State` 아직도있다 `Failure` 기술 지원팀에 문의하세요.




. EC 재조정 절차가 너무 많은 부하를 생성하는 경우(예: 수집 작업에 영향을 미치는 경우) 절차를 일시 중지합니다.
+
`rebalance-data pause --job-id _job-id_`

. EC 재조정 절차를 종료해야 하는 경우(예: StorageGRID 소프트웨어 업그레이드를 수행할 수 있도록) 다음을 입력합니다.
+
`rebalance-data terminate --job-id _job-id_`

+

NOTE: EC 재조정 절차를 종료하면 이미 이동된 모든 데이터 조각은 새 위치에 그대로 남아 있습니다.  데이터는 원래 위치로 이동되지 않습니다.

. 두 개 이상의 사이트에서 삭제 코딩을 사용하는 경우, 영향을 받는 다른 모든 사이트에 대해 이 절차를 실행하세요.

