---
permalink: expand/updating-subnets-for-grid-network.html 
sidebar: sidebar 
keywords: expand, expansion, add subnets, Grid Network 
summary: 확장 시 그리드 노드나 새로운 사이트를 추가하는 경우 그리드 네트워크에 서브넷을 업데이트하거나 추가해야 할 수도 있습니다. 
---
= 그리드 네트워크의 서브넷 업데이트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
확장 시 그리드 노드나 새로운 사이트를 추가하는 경우 그리드 네트워크에 서브넷을 업데이트하거나 추가해야 할 수도 있습니다.

StorageGRID 그리드 네트워크(eth0)의 그리드 노드 간 통신에 사용되는 네트워크 서브넷 목록을 유지 관리합니다.  이러한 항목에는 StorageGRID 시스템의 각 사이트에서 그리드 네트워크에 사용되는 서브넷과 그리드 네트워크 게이트웨이를 통해 액세스하는 NTP, DNS, LDAP 또는 기타 외부 서버에 사용되는 서브넷이 포함됩니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["유지 관리 또는 루트 액세스 권한"] .
* 프로비저닝 암호가 있습니다.
* 구성하려는 서브넷의 CIDR 표기법 네트워크 주소가 있습니다.


.이 작업에 관하여
새로운 노드 중 하나에 이전에 사용되지 않은 서브넷의 Grid Network IP 주소가 있는 경우 확장을 시작하기 전에 Grid Network 서브넷 목록에 새 서브넷을 추가해야 합니다.  그렇지 않으면 확장을 취소하고, 새로운 서브넷을 추가한 다음 절차를 다시 시작해야 합니다.

[NOTE]
====
다음 IPv4 주소가 포함된 서브넷은 모든 노드의 그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크에 사용하지 마세요.

* 192,168,130,101
* 192,168,131,101
* 192,168,130,102
* 192,168,131,102
* 198.51.100.2
* 198.51.100.4


예를 들어, 어떤 노드의 그리드 네트워크, 관리 네트워크 또는 클라이언트 네트워크에도 다음 서브넷 범위를 사용하지 마세요.

* 192.168.130.0/24는 이 서브넷 범위에 IP 주소 192.168.130.101 및 192.168.130.102가 포함되어 있기 때문입니다.
* 192.168.131.0/24는 이 서브넷 범위에 IP 주소 192.168.131.101 및 192.168.131.102가 포함되어 있기 때문입니다.
* 198.51.100.0/24는 이 서브넷 범위에 IP 주소 198.51.100.2와 198.51.100.4가 포함되어 있기 때문입니다.


====
.단계
. *유지관리* > *네트워크* > *그리드 네트워크*를 선택하세요.
. CIDR 표기법으로 새로운 서브넷을 추가하려면 *다른 서브넷 추가*를 선택합니다.
+
예를 들어 다음을 입력하세요. `10.96.104.0/22` .

. 프로비저닝 암호를 입력하고 *저장*을 선택합니다.
. 변경 사항이 적용될 때까지 기다린 후 새로운 복구 패키지를 다운로드하세요.
+
.. *유지관리* > *시스템* > *복구 패키지*를 선택하세요.
.. *프로비저닝 암호문구*를 입력하세요.
+

CAUTION: 복구 패키지 파일은 StorageGRID 시스템에서 데이터를 얻는 데 사용할 수 있는 암호화 키와 비밀번호가 포함되어 있으므로 보호되어야 합니다. 기본 관리 노드를 복구하는 데에도 사용됩니다.





지정한 서브넷은 StorageGRID 시스템에 자동으로 구성됩니다.
