---
permalink: expand/vmware-adding-storage-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expand, expansion, storage node, add storage volumes, VMware 
summary: 스토리지 노드에 스토리지 볼륨이 16개 미만인 경우 VMware vSphere를 사용하여 볼륨을 추가하여 용량을 늘릴 수 있습니다. 
---
= VMware: 스토리지 노드에 스토리지 볼륨 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드에 스토리지 볼륨이 16개 미만인 경우 VMware vSphere를 사용하여 볼륨을 추가하여 용량을 늘릴 수 있습니다.

.시작하기 전에
* VMware 배포를 위한 StorageGRID 설치 지침을 확인할 수 있습니다.
+
** link:../vmware/index.html["VMware에 StorageGRID 설치"]


* 당신은 가지고있다 `Passwords.txt` 파일.
* 당신은 가지고있다link:../admin/admin-group-permissions.html["특정 액세스 권한"] .



CAUTION: 소프트웨어 업그레이드, 복구 절차 또는 다른 확장 절차가 활성화되어 있는 동안에는 스토리지 노드에 스토리지 볼륨을 추가하려고 하지 마세요.

.이 작업에 관하여
스토리지 볼륨을 추가하면 잠시 동안 스토리지 노드를 사용할 수 없습니다.  클라이언트 기반 그리드 서비스에 영향을 주지 않으려면 한 번에 하나의 스토리지 노드에서 이 절차를 수행해야 합니다.

.단계
. 필요한 경우 새로운 스토리지 하드웨어를 설치하고 새로운 VMware 데이터스토어를 만듭니다.
. 저장소(개체 저장소)로 사용할 하나 이상의 하드 디스크를 가상 머신에 추가합니다.
+
.. VMware vSphere 클라이언트를 엽니다.
.. 가상 머신 설정을 편집하여 하나 이상의 추가 하드 디스크를 추가합니다.


+
하드 디스크는 일반적으로 가상 머신 디스크(VMDK)로 구성됩니다.  VMDK는 보다 일반적으로 사용되고 관리하기 쉬운 반면, RDM은 더 큰 개체 크기(예: 100MB 이상)를 사용하는 작업 부하에 대해 더 나은 성능을 제공할 수 있습니다.  가상 머신에 하드 디스크를 추가하는 방법에 대한 자세한 내용은 VMware vSphere 설명서를 참조하세요.

. VMware vSphere Client에서 *게스트 OS 다시 시작* 옵션을 사용하거나 가상 머신에 대한 ssh 세션에서 다음 명령을 입력하여 가상 머신을 다시 시작합니다.``sudo reboot``
+

NOTE: 가상 머신을 다시 시작하려면 *전원 끄기* 또는 *재설정*을 사용하지 마세요.

. 스토리지 노드에서 사용할 새 스토리지를 구성합니다.
+
.. 그리드 노드에 로그인하세요:
+
... 다음 명령을 입력하세요: `ssh admin@_grid_node_IP_`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
... 다음 명령을 입력하여 루트로 전환하세요. `su -`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.  루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .


.. 새로운 저장소 볼륨을 구성합니다.
+
`sudo add_rangedbs.rb`

+
이 스크립트는 새로운 저장 볼륨을 찾아 포맷하라는 메시지를 표시합니다.

.. 서식을 적용하려면 *y*를 입력하세요.
.. 볼륨이 이전에 포맷된 경우, 다시 포맷할지 여부를 결정합니다.
+
*** *y*를 입력하여 다시 포맷하세요.
*** *n*을 입력하면 재포맷을 건너뜁니다.




+
그만큼 `setup_rangedbs.sh` 스크립트가 자동으로 실행됩니다.

. 서비스가 올바르게 시작되는지 확인하세요.
+
.. 서버의 모든 서비스 상태 목록을 확인하세요.
+
`sudo storagegrid-status`

+
상태는 자동으로 업데이트됩니다.

.. 모든 서비스가 실행 중이거나 검증될 때까지 기다리세요.
.. 상태 화면을 종료합니다.
+
`Ctrl+C`



. 스토리지 노드가 온라인인지 확인하세요.
+
.. 다음을 사용하여 Grid Manager에 Sign in.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
.. *지원* > *도구* > *그리드 토폴로지*를 선택하세요.
.. *_사이트_* > *_스토리지 노드_* > *LDR* > *스토리지*를 선택합니다.
.. *구성* 탭을 선택한 다음 *기본* 탭을 선택합니다.
.. *저장소 상태 - 원하는* 드롭다운 목록이 읽기 전용 또는 오프라인으로 설정된 경우 *온라인*을 선택합니다.
.. *변경 사항 적용*을 선택하세요.


. 새로운 객체 저장소를 보려면:
+
.. *노드* > *_사이트_* > *_스토리지 노드_* > *스토리지*를 선택합니다.
.. 자세한 내용은 *개체 저장소* 표에서 확인하세요.




.결과
스토리지 노드의 확장된 용량을 활용하여 객체 데이터를 저장할 수 있습니다.
