---
permalink: troubleshoot/searching-for-and-restoring-potentially-lost-objects.html 
sidebar: sidebar 
keywords: how to search lost object, how to restore lost object, how to find lost object 
summary: '*분실된 물건* 경고와 기존 분실된 물건(LOST) 경고가 발생하여 분실 가능성이 있는 것으로 확인된 물건을 찾아 복원하는 것이 가능할 수 있습니다.' 
---
= 분실 가능성이 있는 물건을 검색하고 복구하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*분실된 물건* 경고와 기존 분실된 물건(LOST) 경고가 발생하여 분실 가능성이 있는 것으로 확인된 물건을 찾아 복원하는 것이 가능할 수 있습니다.

.시작하기 전에
* 분실된 모든 객체의 UUID는 다음과 같이 식별됩니다.link:../troubleshoot/investigating-lost-objects.html["분실물을 조사하세요"] .
* 당신은 가지고있다 `Passwords.txt` 파일.


.이 작업에 관하여
이 절차에 따라 그리드의 다른 곳에서 손실된 개체의 복제본을 찾을 수 있습니다.  대부분의 경우, 잃어버린 물건은 찾을 수 없습니다.  그러나 어떤 경우에는 신속한 조치를 취하면 손실된 복제된 객체를 찾아 복원할 수 있습니다.


CAUTION: 이 절차에 대한 도움이 필요하면 기술 지원팀에 문의하세요.

.단계
. 관리 노드에서 감사 로그를 검색하여 가능한 개체 위치를 찾습니다.
+
.. 그리드 노드에 로그인하세요:
+
... 다음 명령을 입력하세요: `ssh admin@grid_node_IP`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
... 다음 명령을 입력하여 루트로 전환하세요. `su -`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.  루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .


.. [[substep-1b]]감사 로그가 있는 디렉토리로 변경합니다.
+
--
감사 로그 디렉토리와 적용 가능한 노드는 감사 대상 설정에 따라 달라집니다.

[cols="1a,2a"]
|===
| 옵션 | 목적지 


 a| 
로컬 노드(기본값)
 a| 
`/var/local/log/localaudit.log`



 a| 
관리 노드/로컬 노드
 a| 
*** 관리 노드(기본 및 비기본): `/var/local/audit/export/audit.log`
*** 모든 노드: `/var/local/log/localaudit.log` 이 모드에서는 파일이 일반적으로 비어 있거나 없습니다.




 a| 
외부 시스템 로그 서버
 a| 
`/var/local/log/localaudit.log`

|===
감사 대상 설정에 따라 다음을 입력합니다. `cd /var/local/log` 또는 `/var/local/audit/export/`

자세한 내용은 다음을 참조하세요.link:../monitor/configure-audit-messages.html#select-audit-information-destinations["감사 정보 대상 선택"] .

--
.. grep을 사용하여 추출하세요link:../audit/object-ingest-transactions.html["잠재적으로 손실된 개체와 관련된 감사 메시지"] 출력 파일로 보냅니다.  입력하다: `grep uuid-value audit_file_name > output_file_name`
+
예를 들어:

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_lost_object.txt
----
.. grep을 사용하여 이 출력 파일에서 위치 손실(LLST) 감사 메시지를 추출합니다.  입력하다: `grep LLST output_file_name`
+
예를 들어:

+
[listing]
----
Admin: # grep LLST /var/local/tmp/messages_about_lost_objects.txt
----
+
LLST 감사 메시지는 이 예제 메시지와 같습니다.

+
[listing]
----
[AUDT:[NOID(UI32):12448208][CBIL(UI64):0x38186FE53E3C49A5]
[UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"][LTYP(FC32):CLDI]
[PCLD(CSTR):"/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA#3tN6"]
[TSRC(FC32):SYST][RSLT(FC32):NONE][AVER(UI32):10][ATIM(UI64):1581535134379225]
[ATYP(FC32):LLST][ANID(UI32):12448208][AMID(FC32):CLSM][ATID(UI64):7086871083190743409]]
----
.. LLST 메시지에서 PCLD 필드와 NOID 필드를 찾으세요.
+
PCLD가 있는 경우 해당 값은 누락된 복제된 개체 복사본에 대한 디스크의 전체 경로입니다.  NOID 값은 객체의 사본을 찾을 수 있는 LDR의 노드 ID입니다.

+
물체의 위치를 찾으면 해당 물체를 복구할 수 있을 수도 있습니다.

.. 이 LDR 노드 ID와 연관된 스토리지 노드를 찾으세요.  그리드 관리자에서 *지원* > *도구* > *그리드 토폴로지*를 선택합니다.  그런 다음 *_데이터 센터_* > *_스토리지 노드_* > *LDR*을 선택합니다.
+
LDR 서비스의 노드 ID는 노드 정보 테이블에 있습니다.  이 LDR을 호스팅하는 스토리지 노드를 찾을 때까지 각 스토리지 노드에 대한 정보를 검토합니다.



. 감사 메시지에 표시된 스토리지 노드에 개체가 있는지 확인합니다.
+
.. 그리드 노드에 로그인하세요:
+
... 다음 명령을 입력하세요: `ssh admin@grid_node_IP`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
... 다음 명령을 입력하여 루트로 전환하세요. `su -`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



.. 해당 객체의 파일 경로가 존재하는지 확인합니다.
+
개체의 파일 경로의 경우 LLST 감사 메시지의 PCLD 값을 사용합니다.

+
예를 들어, 다음을 입력합니다.

+
[listing]
----
ls '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+

NOTE: 명령어에서 특수 문자를 이스케이프하려면 항상 개체 파일 경로를 작은따옴표로 묶어야 합니다.

+
*** 객체 경로를 찾을 수 없으면 객체가 손실되며 이 절차를 사용하여 복원할 수 없습니다. 기술 지원팀에 문의하세요.
*** 객체 경로를 찾았으면 다음 단계로 넘어갑니다.  찾은 객체를 StorageGRID 로 복원해 볼 수 있습니다.




. 객체 경로가 발견된 경우 객체를 StorageGRID 로 복원해 보세요.
+
.. 동일한 스토리지 노드에서 개체 파일의 소유권을 변경하여 StorageGRID 에서 관리할 수 있도록 합니다.  입력하다: `chown ldr-user:bycast 'file_path_of_object'`
.. LDR 콘솔에 접속하려면 localhost 1402로 Telnet을 실행하세요.  입력하다: `telnet 0 1402`
.. 입력하다: `cd /proc/STOR`
.. 입력하다: `Object_Found 'file_path_of_object'`
+
예를 들어, 다음을 입력합니다.

+
[listing]
----
Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'
----
+
발행 `Object_Found` 명령은 그리드에 객체의 위치를 알립니다.  또한 각 정책에 지정된 대로 추가 사본을 만드는 활성 ILM 정책도 트리거합니다.

+

NOTE: 객체를 찾은 스토리지 노드가 오프라인인 경우 온라인 상태인 모든 스토리지 노드에 객체를 복사할 수 있습니다.  온라인 스토리지 노드의 /var/local/rangedb 디렉토리에 객체를 넣습니다.  그런 다음 발행합니다 `Object_Found` 해당 파일 경로를 사용하여 개체에 대한 명령을 실행합니다.

+
*** 객체를 복원할 수 없는 경우 `Object_Found` 명령이 실패합니다. 기술 지원팀에 문의하세요.
*** 객체가 StorageGRID 에 성공적으로 복원되면 성공 메시지가 나타납니다. 예를 들어:
+
[listing]
----
ade 12448208: /proc/STOR > Object_Found '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6'

ade 12448208: /proc/STOR > Object found succeeded.
First packet of file was valid. Extracted key: 38186FE53E3C49A5
Renamed '/var/local/rangedb/1/p/17/11/00rH0%DkRs&LgA%#3tN6' to '/var/local/rangedb/1/p/17/11/00rH0%DkRt78Ila#3udu'
----
+
다음 단계로 넘어가세요.





. 개체가 StorageGRID 에 성공적으로 복원된 경우 새 위치가 생성되었는지 확인하세요.
+
.. 다음을 사용하여 Grid Manager에 Sign in.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
.. *ILM* > *개체 메타데이터 조회*를 선택합니다.
.. UUID를 입력하고 *조회*를 선택하세요.
.. 메타데이터를 검토하고 새로운 위치를 확인하세요.


. 관리 노드에서 이 개체에 대한 ORLM 감사 메시지의 감사 로그를 검색하여 정보 수명 주기 관리(ILM)가 필요에 따라 사본을 배치했는지 확인합니다.
+
.. 그리드 노드에 로그인하세요:
+
... 다음 명령을 입력하세요: `ssh admin@grid_node_IP`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
... 다음 명령을 입력하여 루트로 전환하세요. `su -`
... 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.  루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .


.. 감사 로그가 있는 디렉토리로 변경합니다.  참조하다<<substep-1b,하위 단계 1. b>> .
.. grep을 사용하여 객체와 연관된 감사 메시지를 출력 파일에 추출합니다.  입력하다: `grep uuid-value audit_file_name > output_file_name`
+
예를 들어:

+
[listing]
----
Admin: # grep 926026C4-00A4-449B-AC72-BCCA72DD1311 audit.log > /var/local/tmp/messages_about_restored_object.txt
----
.. grep을 사용하여 이 출력 파일에서 ORLM(Object Rules Met) 감사 메시지를 추출합니다.  입력하다: `grep ORLM output_file_name`
+
예를 들어:

+
[listing]
----
Admin: # grep ORLM /var/local/tmp/messages_about_restored_object.txt
----
+
ORLM 감사 메시지는 이 예제 메시지와 같습니다.

+
[listing]
----
[AUDT:[CBID(UI64):0x38186FE53E3C49A5][RULE(CSTR):"Make 2 Copies"]
[STAT(FC32):DONE][CSIZ(UI64):0][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[LOCS(CSTR):"**CLDI 12828634 2148730112**, CLDI 12745543 2147552014"]
[RSLT(FC32):SUCS][AVER(UI32):10][ATYP(FC32):ORLM][ATIM(UI64):1563398230669]
[ATID(UI64):15494889725796157557][ANID(UI32):13100453][AMID(FC32):BCMS]]
----
.. 감사 메시지에서 LOCS 필드를 찾으세요.
+
LOCS의 CLDI 값은 개체 복사본이 생성된 노드 ID와 볼륨 ID입니다.  이 메시지는 ILM이 적용되었고 그리드의 두 위치에 두 개의 개체 복사본이 생성되었음을 보여줍니다.



. link:resetting-lost-and-missing-object-counts.html["분실 및 누락된 개체 수를 재설정합니다."]그리드 관리자에서.

