---
permalink: troubleshoot/troubleshooting-network-hardware-and-platform-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot network, how to troubleshoot hardware, how to troubleshoot platform 
summary: StorageGRID 네트워크, 하드웨어 및 플랫폼 문제와 관련된 문제의 근원을 파악하는 데 도움이 되는 몇 가지 작업이 있습니다. 
---
= 네트워크, 하드웨어 및 플랫폼 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 네트워크, 하드웨어 및 플랫폼 문제와 관련된 문제의 근원을 파악하는 데 도움이 되는 몇 가지 작업이 있습니다.



== "422: 처리할 수 없는 엔터티" 오류

오류 422: 처리할 수 없는 엔터티는 여러 가지 이유로 발생할 수 있습니다.  오류 메시지를 확인하여 문제의 원인을 확인하세요.

나열된 오류 메시지 중 하나가 나타나면 권장 조치를 취하세요.

[cols="2a,3a"]
|===
| 오류 메시지 | 근본 원인 및 시정 조치 


 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration. Unable to
authenticate, please verify
your username and password:
LDAP Result Code 8 "Strong
Auth Required": 00002028:
LdapErr: DSID-0C090256,
comment: The server requires
binds to turn on integrity
checking if SSL\TLS are not
already active on the
connection, data 0, v3839
---- a| 
Windows Active Directory(AD)를 사용하여 ID 페더레이션을 구성할 때 TLS(전송 계층 보안)에 대해 *TLS 사용 안 함* 옵션을 선택하면 이 메시지가 발생할 수 있습니다.

LDAP 서명을 강제하는 AD 서버에서는 *TLS 사용 안 함* 옵션을 사용할 수 없습니다.  TLS에 대해 *STARTTLS 사용* 옵션이나 *LDAPS 사용* 옵션 중 하나를 선택해야 합니다.



 a| 
[listing]
----
422: Unprocessable Entity

Validation failed. Please check
the values you entered for
errors. Test connection failed.
Please verify your
configuration.Unable to
begin TLS, verify your
certificate and TLS
configuration: LDAP Result
Code 200 "Network Error":
TLS handshake failed
    (EOF)
---- a| 
StorageGRID 에서 ID 연합 또는 클라우드 스토리지 풀에 사용되는 외부 시스템으로 TLS(전송 계층 보안) 연결을 만들 때 지원되지 않는 암호를 사용하려고 하면 이 메시지가 나타납니다.

외부 시스템에서 제공하는 암호를 확인하세요.  시스템은 다음 중 하나를 사용해야 합니다.link:../admin/supported-ciphers-for-outgoing-tls-connections.html["StorageGRID 에서 지원하는 암호"] StorageGRID 관리 지침에 표시된 대로 발신 TLS 연결의 경우.

|===


== [[troubleshoot_MTU_alert]]그리드 네트워크 MTU 불일치 경고

*그리드 네트워크 MTU 불일치* 경고는 그리드 네트워크 인터페이스(eth0)의 최대 전송 단위(MTU) 설정이 그리드 내 노드 간에 크게 다를 때 발생합니다.

.이 작업에 관하여
MTU 설정의 차이는 일부 eth0 네트워크가 점보 프레임으로 구성되어 있음을 나타낼 수 있습니다.  1000보다 큰 MTU 크기 불일치로 인해 네트워크 성능 문제가 발생할 수 있습니다.

.단계
. 모든 노드의 eth0에 대한 MTU 설정을 나열합니다.
+
** 그리드 관리자에 제공된 쿼리를 사용하세요.
** 로 이동 `_primary Admin Node IP address_/metrics/graph` 다음 쿼리를 입력하세요. `node_network_mtu_bytes{device="eth0"}`


. https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["MTU 설정 수정"^]모든 노드의 Grid Network 인터페이스(eth0)에 대해 동일한지 확인하는 데 필요합니다.
+
** Linux 및 VMware 기반 노드의 경우 다음 명령을 사용합니다. `+/usr/sbin/change-ip.py [-h] [-n node] mtu network [network...]+`
+
*예*: `change-ip.py -n node 1500 grid admin`

+
*참고*: Linux 기반 노드에서 컨테이너의 네트워크에 대한 원하는 MTU 값이 호스트 인터페이스에 이미 구성된 값을 초과하는 경우 먼저 호스트 인터페이스에 원하는 MTU 값을 설정한 다음 다음을 사용해야 합니다. `change-ip.py` 컨테이너 내 네트워크의 MTU 값을 변경하는 스크립트입니다.

+
Linux 또는 VMware 기반 노드에서 MTU를 수정하려면 다음 인수를 사용하세요.

+
[cols="1a,2a"]
|===
| 위치적 인수 | 설명 


 a| 
`mtu`
 a| 
설정할 MTU입니다.  1280~9216 범위에 있어야 합니다.



 a| 
`network`
 a| 
MTU를 적용할 네트워크입니다.  다음 네트워크 유형 중 하나 이상을 포함합니다.

*** 그리드
*** 관리자
*** 고객


|===
+
[cols="2a,2a"]
|===
| 선택적 인수 | 설명 


 a| 
`-h, – help`
 a| 
도움말 메시지를 표시하고 종료합니다.



 a| 
`-n node, --node node`
 a| 
노드.  기본값은 로컬 노드입니다.

|===






== 노드 네트워크 수신 프레임 오류 경고

*노드 네트워크 수신 프레임 오류* 경고는 StorageGRID 와 네트워크 하드웨어 간의 연결 문제로 인해 발생할 수 있습니다.  이 경고는 기본 문제가 해결되면 자동으로 사라집니다.

.이 작업에 관하여
*노드 네트워크 수신 프레임 오류* 경고는 StorageGRID 에 연결하는 네트워킹 하드웨어의 다음 문제로 인해 발생할 수 있습니다.

* 전방 오류 정정(FEC)이 필요하지만 사용되지 않습니다.
* 스위치 포트와 NIC MTU 불일치
* 높은 링크 오류율
* NIC 링 버퍼 오버런


.단계
. 네트워크 구성에 따라 이 경고가 발생할 수 있는 모든 원인에 대한 문제 해결 단계를 따르세요.
. 오류의 원인에 따라 다음 단계를 수행하세요.
+
[role="tabbed-block"]
====
.FEC 불일치
--

NOTE: 이러한 단계는 StorageGRID 어플라이언스의 FEC 불일치로 인해 발생한 *노드 네트워크 수신 프레임 오류* 경고에만 적용됩니다.

.. StorageGRID 어플라이언스에 연결된 스위치의 포트 FEC 상태를 확인하세요.
.. 기기에서 스위치까지 케이블의 물리적 무결성을 점검하세요.
.. 경고를 해결하기 위해 FEC 설정을 변경하려면 먼저 StorageGRID Appliance Installer의 링크 구성 페이지에서 어플라이언스가 *자동* 모드로 구성되어 있는지 확인하세요(어플라이언스에 대한 지침 참조:
+
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SG6160"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/changing-link-configuration-of-sgf6112-appliance.html["SGF6112"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/changing-link-configuration-of-sg6000-cn-controller.html["SG6000"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/changing-link-configuration-of-sg5800-controller.html["SG5800"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/changing-link-configuration-of-e5700sg-controller.html["SG5700"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/changing-link-configuration-of-sg110-and-sg1100-appliance.html["SG110 및 SG1100"^]
*** https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/changing-link-configuration-of-services-appliance.html["SG100 및 SG1000"^]


.. 스위치 포트의 FEC 설정을 변경합니다.  가능하다면 StorageGRID 어플라이언스 포트는 FEC 설정을 일치하도록 조정합니다.
+
StorageGRID 어플라이언스에서는 FEC 설정을 구성할 수 없습니다.  대신, 어플라이언스는 연결된 스위치 포트에서 FEC 설정을 검색하고 미러링하려고 시도합니다.  링크가 25GbE 또는 100GbE 네트워크 속도로 강제로 전환되면 스위치와 NIC가 공통 FEC 설정을 협상하지 못할 수 있습니다.  공통 FEC 설정이 없으면 네트워크는 "FEC 없음" 모드로 돌아갑니다.  FEC가 활성화되지 않은 경우 전기적 노이즈로 인해 연결이 오류에 취약해질 수 있습니다.

+

NOTE: StorageGRID 어플라이언스는 FEC를 지원하지 않을 뿐만 아니라 Firecode(FC) 및 Reed Solomon(RS) FEC도 지원합니다.



--
.스위치 포트와 NIC MTU 불일치
--
스위치 포트와 NIC MTU 불일치로 인해 경고가 발생한 경우 노드에 구성된 MTU 크기가 스위치 포트의 MTU 설정과 동일한지 확인하세요.

노드에 구성된 MTU 크기는 노드가 연결된 스위치 포트의 설정보다 작을 수 있습니다.  이 구성에서 StorageGRID 노드가 MTU보다 큰 이더넷 프레임을 수신할 수 있는 경우, *노드 네트워크 수신 프레임 오류* 경고가 보고될 수 있습니다.  이런 일이 발생한다고 생각되면 엔드투엔드 MTU 목표나 요구 사항에 따라 스위치 포트의 MTU를 StorageGRID 네트워크 인터페이스 MTU와 일치하도록 변경하거나, StorageGRID 네트워크 인터페이스의 MTU를 스위치 포트와 일치하도록 변경하세요.


NOTE: 최상의 네트워크 성능을 위해서는 모든 노드가 해당 그리드 네트워크 인터페이스에서 유사한 MTU 값으로 구성되어야 합니다.  *그리드 네트워크 MTU 불일치* 경고는 개별 노드의 그리드 네트워크에 대한 MTU 설정에 상당한 차이가 있는 경우 발생합니다.  MTU 값은 모든 네트워크 유형에서 동일할 필요는 없습니다. 보다 <<troubleshoot_MTU_alert,그리드 네트워크 MTU 불일치 경고 문제 해결>> 자세한 내용은.


NOTE: 또한 참조 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/changing-mtu-setting.html["MTU 설정 변경"^] .

--
.높은 링크 오류율
--
.. FEC가 아직 활성화되어 있지 않으면 활성화합니다.
.. 네트워크 케이블의 품질이 좋고 손상되지 않았거나 제대로 연결되지 않았는지 확인하세요.
.. 케이블에 문제가 없는 경우 기술 지원팀에 문의하세요.
+

NOTE: 전기적 노이즈가 심한 환경에서는 오류율이 높아질 수 있습니다.



--
.NIC 링 버퍼 오버런
--
오류가 NIC 링 버퍼 오버런인 경우 기술 지원팀에 문의하세요.

StorageGRID 시스템이 과부하되어 네트워크 이벤트를 적시에 처리할 수 없는 경우 링 버퍼가 오버런될 수 있습니다.

--
====
. 문제를 모니터링하고 경고가 해결되지 않으면 기술 지원팀에 문의하세요.




== 시간 동기화 오류

그리드에서 시간 동기화 문제가 발생할 수 있습니다.

시간 동기화 문제가 발생하는 경우, Stratum 3 이상의 참조를 제공하는 최소 4개의 외부 NTP 소스를 지정했는지, 그리고 모든 외부 NTP 소스가 정상적으로 작동하고 StorageGRID 노드에서 액세스할 수 있는지 확인하세요.


NOTE: 언제link:../maintain/configuring-ntp-servers.html["외부 NTP 소스 지정"] 프로덕션 수준의 StorageGRID 설치의 경우 Windows Server 2016 이전 버전의 Windows에서는 Windows 시간(W32Time) 서비스를 사용하지 마세요.  이전 버전의 Windows에서 제공되는 시간 서비스는 충분히 정확하지 않으며 StorageGRID 와 같이 정확도가 높은 환경에서는 Microsoft에서 지원하지 않습니다.



== Linux: 네트워크 연결 문제

Linux 호스트에 호스팅된 StorageGRID 노드의 네트워크 연결에 문제가 발생할 수 있습니다.



=== MAC 주소 복제

어떤 경우에는 MAC 주소 복제를 사용하여 네트워크 문제를 해결할 수 있습니다. 가상 호스트를 사용하는 경우 노드 구성 파일에서 각 네트워크의 MAC 주소 복제 키 값을 "true"로 설정합니다. 이 설정을 사용하면 StorageGRID 컨테이너의 MAC 주소가 호스트의 MAC 주소를 사용하게 됩니다. 노드 구성 파일을 생성하려면 다음 지침을 참조하세요.link:../rhel/creating-node-configuration-files.html["레드햇 엔터프라이즈 리눅스"] 또는link:../ubuntu/creating-node-configuration-files.html["우분투 또는 데비안"] .


NOTE: Linux 호스트 OS에서 사용할 별도의 가상 네트워크 인터페이스를 만듭니다.  Linux 호스트 OS와 StorageGRID 컨테이너에 동일한 네트워크 인터페이스를 사용하면 하이퍼바이저에서 혼합 모드가 활성화되지 않은 경우 호스트 OS에 접근하지 못할 수 있습니다.

MAC 복제 활성화에 대한 자세한 내용은 다음 지침을 참조하세요.link:../rhel/configuring-host-network.html["레드햇 엔터프라이즈 리눅스"] 또는link:../ubuntu/configuring-host-network.html["우분투 또는 데비안"] .



=== 난잡한 모드

MAC 주소 복제를 사용하지 않고 하이퍼바이저에서 할당한 MAC 주소 이외의 MAC 주소에 대한 데이터를 모든 인터페이스에서 수신 및 전송하도록 허용하려면 가상 스위치 및 포트 그룹 수준의 보안 속성이 무작위 모드, MAC 주소 변경 및 위조 전송에 대해 *수락*으로 설정되어 있는지 확인하세요.  가상 스위치에 설정된 값은 포트 그룹 수준의 값으로 재정의될 수 있으므로 두 곳의 설정이 동일한지 확인하세요.

Promiscuous Mode 사용에 대한 자세한 내용은 다음 지침을 참조하세요.link:../rhel/configuring-host-network.html["레드햇 엔터프라이즈 리눅스"] 또는link:../ubuntu/configuring-host-network.html["우분투 또는 데비안"] .



== Linux: 노드 상태가 "고아"입니다.

고아 상태의 Linux 노드는 일반적으로 노드의 컨테이너를 제어하는 ​​StorageGrid 서비스나 StorageGRID 노드 데몬이 예기치 않게 종료되었음을 나타냅니다.

.이 작업에 관하여
Linux 노드가 고아 상태라고 보고하는 경우 다음을 수행해야 합니다.

* 오류와 메시지가 있는지 로그를 확인하세요.
* 노드를 다시 시작해 보세요.
* 필요한 경우 컨테이너 엔진 명령을 사용하여 기존 노드 컨테이너를 중지합니다.
* 노드를 다시 시작합니다.


.단계
. 서비스 데몬과 고아 노드의 로그를 확인하여 예기치 않게 종료되는 것과 관련된 명확한 오류나 메시지가 있는지 확인하세요.
. 루트로 또는 sudo 권한이 있는 계정을 사용하여 호스트에 로그인합니다.
. 다음 명령을 실행하여 노드를 다시 시작해 보세요. `$ sudo storagegrid node start node-name`
+
 $ sudo storagegrid node start DC1-S1-172-16-1-172
+
노드가 고아인 경우 응답은 다음과 같습니다.

+
[listing]
----
Not starting ORPHANED node DC1-S1-172-16-1-172
----
. Linux에서 컨테이너 엔진과 모든 제어 storagegrid-node 프로세스를 중지합니다. 예: ``sudo docker stop --time secondscontainer-name``
+
을 위한 `seconds` 컨테이너가 멈출 때까지 기다릴 시간(초)을 입력합니다(일반적으로 15분 이하). 예를 들어:

+
[listing]
----
sudo docker stop --time 900 storagegrid-DC1-S1-172-16-1-172
----
. 노드를 다시 시작합니다. `storagegrid node start node-name`
+
[listing]
----
storagegrid node start DC1-S1-172-16-1-172
----




== Linux: IPv6 지원 문제 해결

Linux 호스트에 StorageGRID 노드를 설치했고 예상대로 노드 컨테이너에 IPv6 주소가 할당되지 않은 경우 커널에서 IPv6 지원을 활성화해야 할 수도 있습니다.

.이 작업에 관하여
그리드 노드에 할당된 IPv6 주소를 보려면:

. *노드*를 선택하고 노드를 선택합니다.
. 개요 탭에서 *IP 주소* 옆에 있는 *추가 IP 주소 표시*를 선택합니다.


IPv6 주소가 표시되지 않고 노드가 Linux 호스트에 설치된 경우 다음 단계에 따라 커널에서 IPv6 지원을 활성화하세요.

.단계
. 루트로 또는 sudo 권한이 있는 계정을 사용하여 호스트에 로그인합니다.
. 다음 명령을 실행하세요. `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@SG:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
결과는 0이어야 합니다.

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+

NOTE: 결과가 0이 아닌 경우 운영 체제 설명서를 참조하여 변경하세요. `sysctl` 설정.  그런 다음 계속하기 전에 값을 0으로 변경하세요.

. StorageGRID 노드 컨테이너를 입력하세요. `storagegrid node enter node-name`
. 다음 명령을 실행하세요. `sysctl net.ipv6.conf.all.disable_ipv6`
+
[listing]
----
root@DC1-S1:~ # sysctl net.ipv6.conf.all.disable_ipv6
----
+
결과는 1이어야 합니다.

+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 1
----
+

NOTE: 결과가 1이 아니면 이 절차는 적용되지 않습니다. 기술 지원팀에 문의하세요.

. 컨테이너에서 나가세요: `exit`
+
[listing]
----
root@DC1-S1:~ # exit
----
. 루트로 다음 파일을 편집하세요. `/var/lib/storagegrid/settings/sysctl.d/net.conf` .
+
[listing]
----
sudo vi /var/lib/storagegrid/settings/sysctl.d/net.conf
----
. 다음 두 줄을 찾아 주석 태그를 제거하세요.  그런 다음 파일을 저장하고 닫습니다.
+
[listing]
----
net.ipv6.conf.all.disable_ipv6 = 0
----
+
[listing]
----
net.ipv6.conf.default.disable_ipv6 = 0
----
. 다음 명령을 실행하여 StorageGRID 컨테이너를 다시 시작합니다.
+
[listing]
----
storagegrid node stop node-name
----
+
[listing]
----
storagegrid node start node-name
----

