---
permalink: troubleshoot/troubleshooting-admin-node-and-user-interface-issues.html 
sidebar: sidebar 
keywords: how to troubleshoot admin node issues, how to troubleshoot user interface issues 
summary: 관리 노드 및 StorageGRID 사용자 인터페이스와 관련된 문제의 근원을 파악하는 데 도움이 되는 여러 작업을 수행할 수 있습니다. 
---
= 관리 노드 및 사용자 인터페이스 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리 노드 및 StorageGRID 사용자 인터페이스와 관련된 문제의 근원을 파악하는 데 도움이 되는 여러 작업을 수행할 수 있습니다.



== 관리자 노드 로그인 오류

StorageGRID 관리 노드에 로그인할 때 오류가 발생하는 경우 시스템에 문제가 있을 수 있습니다.link:../troubleshoot/troubleshooting-network-hardware-and-platform-issues.html["네트워킹"] 또는 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/troubleshooting-hardware-installation-sg100-and-sg1000.html["하드웨어"^] 문제, 문제점link:../primer/what-admin-node-is.html["관리 노드 서비스"] , 또는link:../maintain/recovering-failed-storage-volumes-and-rebuilding-cassandra-database.html["Cassandra 데이터베이스 문제"] 연결된 스토리지 노드에서.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다 `Passwords.txt` 파일.
* 당신은 가지고있다link:../admin/admin-group-permissions.html["특정 액세스 권한"] .


.이 작업에 관하여
관리 노드에 로그인을 시도할 때 다음 오류 메시지가 나타나면 다음 문제 해결 지침을 따르세요.

* `Your credentials for this account were invalid. Please try again.`
* `Waiting for services to start...`
* `Internal server error. The server encountered an error and could not complete your request. Please try again. If the problem persists, contact Technical Support.`
* `Unable to communicate with server. Reloading page...`


.단계
. 10분 정도 기다린 후 다시 로그인해 보세요.
+
오류가 자동으로 해결되지 않으면 다음 단계로 넘어가세요.

. StorageGRID 시스템에 두 개 이상의 관리 노드가 있는 경우 다른 관리 노드에서 Grid Manager에 로그인하여 사용할 수 없는 관리 노드의 상태를 확인해 보세요.
+
** 로그인이 가능하다면 *대시보드*, *노드*, *알림*, *지원* 옵션을 사용하여 오류의 원인을 파악할 수 있습니다.
** 관리 노드가 하나만 있거나 여전히 로그인할 수 없는 경우 다음 단계로 이동하세요.


. 노드의 하드웨어가 오프라인인지 확인합니다.
. StorageGRID 시스템에 대해 SSO(Single Sign-On)가 활성화된 경우 다음 단계를 참조하세요.link:../admin/configuring-sso.html["단일 로그인 구성"] .
+
문제를 해결하려면 단일 관리 노드에 대한 SSO를 일시적으로 비활성화했다가 다시 활성화해야 할 수도 있습니다.

+

NOTE: SSO가 활성화된 경우 제한된 포트를 사용하여 로그인할 수 없습니다.  포트 443을 사용해야 합니다.

. 사용 중인 계정이 페더레이션 사용자에 속하는지 확인하세요.
+
페더레이션 사용자 계정이 작동하지 않는 경우 root와 같은 로컬 사용자로 Grid Manager에 로그인해 보세요.

+
** 로컬 사용자가 로그인할 수 있는 경우:
+
... 알림을 검토하세요.
... *구성* > *액세스 제어* > *ID 페더레이션*을 선택합니다.
... LDAP 서버에 대한 연결 설정을 확인하려면 *연결 테스트*를 클릭하세요.
... 테스트에 실패하면 모든 구성 오류를 해결하세요.


** 로컬 사용자가 로그인할 수 없고 자격 증명이 정확하다고 확신하는 경우 다음 단계로 넘어가세요.


. ssh(Secure Shell)를 사용하여 관리 노드에 로그인합니다.
+
.. 다음 명령을 입력하세요: `ssh admin@Admin_Node_IP`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
.. 다음 명령을 입력하여 루트로 전환하세요. `su -`
.. 나열된 비밀번호를 입력하세요 `Passwords.txt` 파일.
+
루트로 로그인하면 프롬프트가 다음과 같이 변경됩니다. `$` 에게 `#` .



. 그리드 노드에서 실행 중인 모든 서비스의 상태를 확인하세요. `storagegrid-status`
+
nms, mi, nginx, mgmt api 서비스가 모두 실행 중인지 확인하세요.

+
서비스 상태가 변경되면 출력이 즉시 업데이트됩니다.

+
....
$ storagegrid-status
Host Name                      99-211
IP Address                     10.96.99.211
Operating System Kernel        4.19.0         Verified
Operating System Environment   Debian 10.1    Verified
StorageGRID Webscale Release   11.4.0         Verified
Networking                                    Verified
Storage Subsystem                             Verified
Database Engine                5.5.9999+default Running
Network Monitoring             11.4.0         Running
Time Synchronization           1:4.2.8p10+dfsg Running
ams                            11.4.0         Running
cmn                            11.4.0         Running
nms                            11.4.0         Running
ssm                            11.4.0         Running
mi                             11.4.0         Running
dynip                          11.4.0         Running
nginx                          1.10.3         Running
tomcat                         9.0.27         Running
grafana                        6.4.3          Running
mgmt api                       11.4.0         Running
prometheus                     11.4.0         Running
persistence                    11.4.0         Running
ade exporter                   11.4.0         Running
alertmanager                   11.4.0         Running
attrDownPurge                  11.4.0         Running
attrDownSamp1                  11.4.0         Running
attrDownSamp2                  11.4.0         Running
node exporter                  0.17.0+ds      Running
sg snmp agent                  11.4.0         Running
....
. nginx-gw 서비스가 실행 중인지 확인하세요 `# service nginx-gw status`
. [[use_Lumberjack_to_collect_logs]]Lumberjack을 사용하여 통나무를 수집하세요: `# /usr/local/sbin/lumberjack.rb`
+
실패한 인증이 과거에 발생한 경우 --start 및 --end Lumberjack 스크립트 옵션을 사용하여 적절한 시간 범위를 지정할 수 있습니다.  이러한 옵션에 대한 자세한 내용을 보려면 lumberjack -h를 사용하세요.

+
터미널 출력은 로그 아카이브가 복사된 위치를 나타냅니다.

. [[review_logs, start=10]]다음 로그를 검토하세요.
+
** `/var/local/log/bycast.log`
** `/var/local/log/bycast-err.log`
** `/var/local/log/nms.log`
** `**/*commands.txt`


. 관리 노드에서 문제를 발견할 수 없는 경우 다음 명령 중 하나를 실행하여 사이트에서 ADC 서비스를 실행하는 세 개의 스토리지 노드의 IP 주소를 확인하세요.  일반적으로 이는 사이트에 설치된 최초의 3개 스토리지 노드입니다.
+
[listing]
----
# cat /etc/hosts
----
+
[listing]
----
# gpt-list-services adc
----
+
관리 노드는 인증 과정에서 ADC 서비스를 사용합니다.

. 관리 노드에서 ssh를 사용하여 식별한 IP 주소를 사용하여 각 ADC 스토리지 노드에 로그인합니다.
. 그리드 노드에서 실행 중인 모든 서비스의 상태를 확인하세요. `storagegrid-status`
+
idnt, acct, nginx, cassandra 서비스가 모두 실행 중인지 확인하세요.

. 단계를 반복하세요<<use_Lumberjack_to_collect_logs,벌목꾼을 사용하여 통나무를 수집하세요>> 그리고<<review_logs,검토 로그>> 스토리지 노드의 로그를 검토합니다.
. 문제를 해결할 수 없는 경우 기술 지원팀에 문의하세요.
+
수집한 로그를 기술 지원팀에 제공하세요. 참조 link:../monitor/logs-files-reference.html["로그 파일 참조"] .





== 사용자 인터페이스 문제

StorageGRID 소프트웨어를 업그레이드한 후 Grid Manager 또는 Tenant Manager의 사용자 인터페이스가 예상대로 응답하지 않을 수 있습니다.

.단계
. 당신이 사용하고 있는지 확인하십시오link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
. 웹 브라우저 캐시를 지우세요.
+
캐시를 지우면 이전 버전의 StorageGRID 소프트웨어에서 사용하던 오래된 리소스가 제거되고 사용자 인터페이스가 다시 올바르게 작동할 수 있습니다.  자세한 내용은 웹 브라우저의 설명서를 참조하세요.


