---
permalink: troubleshoot/troubleshooting-syslog-server.html 
sidebar: sidebar 
keywords: how to troubleshoot the external syslog server 
summary: 다음 표에서는 외부 syslog 서버와 관련될 수 있는 오류 메시지를 설명하고 해결 조치를 나열합니다. 
---
= 외부 syslog 서버 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 표에서는 외부 syslog 서버와 관련될 수 있는 오류 메시지를 설명하고 해결 조치를 나열합니다.

이러한 오류는 외부 syslog 서버가 올바르게 구성되었는지 확인하기 위해 테스트 메시지를 보내는 데 문제가 있는 경우 외부 syslog 서버 구성 마법사에서 표시됩니다.

런타임에 문제가 보고될 수 있습니다.link:../monitor/alerts-reference.html#audit-and-syslog-alerts["외부 syslog 서버 전달 오류"] 알리다. 이 경고를 받으면 경고의 지침에 따라 테스트 메시지를 다시 보내 자세한 오류 메시지를 받으세요.

감사 정보를 외부 syslog 서버로 보내는 방법에 대한 자세한 내용은 다음을 참조하세요.

* link:../monitor/considerations-for-external-syslog-server.html["외부 syslog 서버 사용 시 고려 사항"]
* link:../monitor/configure-audit-messages.html["감사 메시지 및 외부 syslog 서버 구성"]


[cols="1a,3a"]
|===
| 오류 메시지 | 설명 및 권장 작업 


 a| 
호스트 이름을 확인할 수 없습니다
 a| 
Syslog 서버에 입력한 FQDN을 IP 주소로 확인할 수 없습니다.

. 입력한 호스트 이름을 확인하세요.  IP 주소를 입력한 경우 WXYZ("점분할십진수") 표기법으로 된 유효한 IP 주소인지 확인하세요.
. DNS 서버가 올바르게 구성되었는지 확인하세요.
. 각 노드가 DNS 서버의 IP 주소에 액세스할 수 있는지 확인하세요.




 a| 
연결이 거부되었습니다
 a| 
Syslog 서버에 대한 TCP 또는 TLS 연결이 거부되었습니다.  호스트의 TCP 또는 TLS 포트에서 수신 대기하는 서비스가 없거나 방화벽이 액세스를 차단하고 있을 수 있습니다.

. Syslog 서버에 대한 올바른 FQDN 또는 IP 주소, 포트 및 프로토콜을 입력했는지 확인하세요.
. syslog 서비스의 호스트가 지정된 포트에서 수신 대기하는 syslog 데몬을 실행하고 있는지 확인합니다.
. 방화벽이 노드에서 syslog 서버의 IP 및 포트로의 TCP/TLS 연결에 대한 액세스를 차단하지 않는지 확인합니다.




 a| 
네트워크에 접속할 수 없음
 a| 
Syslog 서버가 직접 연결된 서브넷에 없습니다.  라우터는 나열된 노드에서 Syslog 서버로 테스트 메시지를 전달할 수 없음을 나타내는 ICMP 실패 메시지를 반환했습니다.

. Syslog 서버에 올바른 FQDN 또는 IP 주소를 입력했는지 확인하세요.
. 나열된 각 노드에 대해 그리드 네트워크 서브넷 목록, 관리 네트워크 서브넷 목록 및 클라이언트 네트워크 게이트웨이를 확인하세요.  이러한 인터페이스와 게이트웨이(Grid, Admin 또는 Client)를 통해 트래픽을 syslog 서버로 라우팅하도록 구성되었는지 확인하세요.




 a| 
호스트에 접근할 수 없음
 a| 
Syslog 서버는 직접 연결된 서브넷(나열된 노드가 Grid, Admin 또는 Client IP 주소에 사용하는 서브넷)에 있습니다.  노드는 테스트 메시지를 보내려고 시도했지만 syslog 서버의 MAC 주소에 대한 ARP 요청에 대한 응답을 받지 못했습니다.

. Syslog 서버에 올바른 FQDN 또는 IP 주소를 입력했는지 확인하세요.
. syslog 서비스를 실행하는 호스트가 작동 중인지 확인하세요.




 a| 
연결 시간이 초과되었습니다
 a| 
TCP/TLS 연결을 시도했지만, 오랫동안 syslog 서버로부터 응답을 받지 못했습니다.  라우팅 구성이 잘못되었을 수도 있고 방화벽이 응답을 보내지 않고 트래픽을 삭제했을 수도 있습니다(일반적인 구성).

. Syslog 서버에 올바른 FQDN 또는 IP 주소를 입력했는지 확인하세요.
. 나열된 각 노드에 대해 그리드 네트워크 서브넷 목록, 관리 네트워크 서브넷 목록 및 클라이언트 네트워크 게이트웨이를 확인하세요.  네트워크 인터페이스와 게이트웨이(Grid, Admin 또는 Client)를 사용하여 Syslog 서버로 트래픽을 라우팅하도록 구성되어 있는지 확인하세요. Syslog 서버에 도달할 것으로 예상되는 인터페이스와 게이트웨이입니다.
. 방화벽이 syslog 서버의 IP 및 포트에 나열된 노드에서 TCP/TLS 연결에 대한 액세스를 차단하지 않는지 확인하세요.




 a| 
파트너가 연결을 닫았습니다.
 a| 
Syslog 서버와의 TCP 연결이 성공적으로 설정되었으나 나중에 닫혔습니다.  그 이유는 다음과 같습니다.

* Syslog 서버가 재시작되거나 재부팅되었을 수 있습니다.
* 노드와 syslog 서버의 TCP/TLS 설정이 다를 수 있습니다.
* 중간 방화벽이 유휴 TCP 연결을 닫을 수 있습니다.
* Syslog 서버 포트에서 수신 중인 Syslog가 아닌 서버가 연결을 닫았을 수 있습니다.


이 문제를 해결하려면:

. Syslog 서버에 대한 올바른 FQDN 또는 IP 주소, 포트 및 프로토콜을 입력했는지 확인하세요.
. TLS를 사용하는 경우 syslog 서버도 TLS를 사용하는지 확인하세요.  TCP를 사용하는 경우 syslog 서버도 TCP를 사용하는지 확인하세요.
. 중간 방화벽이 유휴 TCP 연결을 닫도록 구성되지 않았는지 확인하세요.




 a| 
TLS 인증서 오류
 a| 
Syslog 서버에서 수신한 서버 인증서가 귀하가 제공한 CA 인증서 번들 및 클라이언트 인증서와 호환되지 않습니다.

. CA 인증서 번들과 클라이언트 인증서(있는 경우)가 syslog 서버의 서버 인증서와 호환되는지 확인하세요.
. Syslog 서버의 서버 인증서에 있는 ID에 예상 IP 또는 FQDN 값이 포함되어 있는지 확인하세요.




 a| 
전달이 중단되었습니다
 a| 
Syslog 레코드가 더 이상 Syslog 서버로 전달되지 않으며 StorageGRID 에서 그 이유를 감지할 수 없습니다.

이 오류와 함께 제공된 디버깅 로그를 검토하여 근본 원인을 파악해 보세요.



 a| 
TLS 세션이 종료되었습니다
 a| 
Syslog 서버가 TLS 세션을 종료했으며 StorageGRID 그 이유를 감지할 수 없습니다.

. 이 오류와 함께 제공된 디버깅 로그를 검토하여 근본 원인을 파악해 보세요.
. Syslog 서버에 대한 올바른 FQDN 또는 IP 주소, 포트 및 프로토콜을 입력했는지 확인하세요.
. TLS를 사용하는 경우 syslog 서버도 TLS를 사용하는지 확인하세요.  TCP를 사용하는 경우 syslog 서버도 TCP를 사용하는지 확인하세요.
. CA 인증서 번들과 클라이언트 인증서(있는 경우)가 syslog 서버의 서버 인증서와 호환되는지 확인하세요.
. Syslog 서버의 서버 인증서에 있는 ID에 예상 IP 또는 FQDN 값이 포함되어 있는지 확인하세요.




 a| 
결과 쿼리가 실패했습니다
 a| 
Syslog 서버 구성 및 테스트에 사용되는 관리 노드는 나열된 노드에서 테스트 결과를 요청할 수 없습니다.  하나 이상의 노드가 다운되었을 수 있습니다.

. 표준 문제 해결 단계에 따라 노드가 온라인 상태이고 모든 예상 서비스가 실행 중인지 확인하세요.
. 나열된 노드에서 miscd 서비스를 다시 시작합니다.


|===