---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: 객체는 클라이언트 애플리케이션의 읽기 요청, 복제된 객체 데이터의 백그라운드 검증, ILM 재평가, 스토리지 노드 복구 중 객체 데이터 복원 등 여러 가지 이유로 검색될 수 있습니다. 
---
= 손실되거나 누락된 객체 데이터 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
객체는 클라이언트 애플리케이션의 읽기 요청, 복제된 객체 데이터의 백그라운드 검증, ILM 재평가, 스토리지 노드 복구 중 객체 데이터 복원 등 여러 가지 이유로 검색될 수 있습니다.

StorageGRID 시스템은 객체의 메타데이터에 있는 위치 정보를 사용하여 객체를 검색할 위치를 결정합니다. 예상 위치에서 객체의 사본을 찾을 수 없는 경우, 시스템은 ILM 정책에 객체의 사본을 두 개 이상 만드는 규칙이 포함되어 있다고 가정하고 시스템의 다른 곳에서 객체의 다른 사본을 검색하려고 시도합니다.

이 검색이 성공하면 StorageGRID 시스템은 해당 개체의 누락된 사본을 대체합니다. 그렇지 않으면 다음과 같이 *분실된 개체* 경고가 발생합니다.

* 복제된 사본의 경우 다른 사본을 검색할 수 없으면 해당 객체는 손실된 것으로 간주되고 경고가 발생합니다.
* 삭제된 복사본의 경우 예상 위치에서 복사본을 검색할 수 없는 경우 손상된 복사본 감지(ECOR) 속성이 다른 위치에서 복사본을 검색하기 전에 1씩 증가합니다.  다른 사본이 발견되지 않으면 경고가 발생합니다.


*객체 손실* 경고가 발생하면 즉시 모든 경고를 조사하여 손실의 근본 원인을 파악하고 해당 객체가 오프라인 상태이거나 현재 사용할 수 없는 스토리지 노드에 여전히 존재할 수 있는지 확인해야 합니다. 보다 link:../troubleshoot/investigating-lost-objects.html["분실물을 조사하세요"] .

사본이 없는 객체 데이터가 손실된 경우 복구 솔루션은 없습니다. 하지만, 알려진 분실물이 새로 분실된 물건을 가리는 것을 방지하려면 분실물 카운터를 재설정해야 합니다. 보다 link:resetting-lost-and-missing-object-counts.html["분실 및 누락된 개체 수 재설정"] .
