---
permalink: ilm/advantages-disadvantages-and-requirements-for-ec.html 
sidebar: sidebar 
keywords: erasure coding advantages, disadvantages, EC requirements 
summary: 객체 데이터의 손실을 방지하기 위해 복제 또는 삭제 코딩을 사용할지 결정하기 전에 삭제 코딩의 장점, 단점 및 요구 사항을 이해해야 합니다. 
---
= 삭제 코딩의 장점, 단점 및 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
객체 데이터의 손실을 방지하기 위해 복제 또는 삭제 코딩을 사용할지 결정하기 전에 삭제 코딩의 장점, 단점 및 요구 사항을 이해해야 합니다.



== 삭제 코딩의 장점

복제와 비교했을 때, 삭제 코딩은 안정성, 가용성, 저장 효율성이 더 뛰어납니다.

* *신뢰성*: 신뢰성은 장애 허용성, 즉 데이터 손실 없이 견딜 수 있는 동시 장애 수를 기준으로 측정됩니다.  복제를 사용하면 여러 개의 동일한 사본이 서로 다른 노드와 사이트 전체에 저장됩니다.  삭제 코딩을 사용하면 객체가 데이터와 패리티 조각으로 인코딩되어 여러 노드와 사이트에 분산됩니다. 이러한 분산은 사이트와 노드 장애에 대한 보호 기능을 제공합니다.  복제와 비교했을 때, 삭제 코딩은 비슷한 저장 비용으로 더 나은 안정성을 제공합니다.
* *가용성*: 가용성은 스토리지 노드에 장애가 발생하거나 액세스할 수 없게 될 경우 객체를 검색할 수 있는 능력으로 정의할 수 있습니다. 복제와 비교했을 때, 삭제 코딩은 비슷한 저장 비용으로 가용성을 높여줍니다.
* *저장 효율성*: 가용성과 안정성 수준이 비슷할 경우, 삭제 코딩을 통해 보호되는 객체는 복제를 통해 보호되는 동일한 객체보다 디스크 공간을 적게 사용합니다. 예를 들어, 두 사이트에 복제된 10MB 객체는 20MB의 디스크 공간(두 개의 사본)을 사용하는 반면, 6+3 삭제 코딩 방식을 사용하여 세 사이트에 삭제 코딩된 객체는 15MB의 디스크 공간만 사용합니다.
+

NOTE: 삭제된 객체의 디스크 공간은 객체 크기에 저장 오버헤드를 더하여 계산됩니다.  저장 오버헤드 백분율은 패리티 조각 수를 데이터 조각 수로 나눈 값입니다.





== 삭제 코딩의 단점

복제와 비교했을 때, 삭제 코딩에는 다음과 같은 단점이 있습니다.

* 삭제 코딩 방식에 따라 저장 노드와 사이트의 수를 늘리는 것이 좋습니다.  이와 대조적으로, 객체 데이터를 복제하는 경우 각 복사본에 대해 하나의 스토리지 노드만 필요합니다. 보다link:what-erasure-coding-schemes-are.html#erasure-coding-schemes-for-storage-pools-containing-three-or-more-sites["3개 이상의 사이트를 포함하는 스토리지 풀에 대한 삭제 코딩 방식"] 그리고link:what-erasure-coding-schemes-are.html#erasure-coding-schemes-for-one-site-storage-pools["단일 사이트 스토리지 풀을 위한 삭제 코딩 방식"] .
* 저장 공간 확장에 따른 비용과 복잡성이 증가합니다.  복제를 사용하는 배포를 확장하려면 개체 복사본이 생성되는 모든 위치에 스토리지 용량을 추가합니다.  삭제 코딩을 사용하는 배포를 확장하려면 사용 중인 삭제 코딩 방식과 기존 스토리지 노드가 얼마나 가득 찼는지 모두 고려해야 합니다.  예를 들어, 기존 노드가 100% 채워질 때까지 기다리는 경우 최소한 다음을 추가해야 합니다. `k+m` 스토리지 노드는 기존 노드가 70% 채워진 상태에서 확장하면 사이트당 노드를 두 개 추가하면서도 사용 가능한 스토리지 용량을 극대화할 수 있습니다. 자세한 내용은 다음을 참조하세요. link:../expand/adding-storage-capacity-for-erasure-coded-objects.html["삭제된 객체에 대한 저장 용량 추가"] .
* 지리적으로 분산된 사이트에서 삭제 코딩을 사용하면 검색 대기 시간이 늘어납니다.  원격 사이트에 분산되어 삭제 코드가 적용된 객체의 객체 조각을 WAN 연결을 통해 검색하는 데 걸리는 시간은 복제되어 로컬에서 사용 가능한 객체(클라이언트가 연결된 사이트와 동일)의 경우보다 더 오래 걸립니다.
* 지리적으로 분산된 사이트에서 삭제 코딩을 사용하면 검색 및 복구를 위해 WAN 네트워크 트래픽 사용량이 늘어나며, 특히 자주 검색되는 객체나 WAN 네트워크 연결을 통한 객체 복구의 경우 사용량이 늘어납니다.
* 사이트 간에 삭제 코딩을 사용하면 사이트 간 네트워크 지연 시간이 증가함에 따라 최대 개체 처리량이 급격히 감소합니다. 이러한 감소는 TCP 네트워크 처리량의 해당 감소로 인한 것이며, 이는 StorageGRID 시스템이 객체 조각을 얼마나 빨리 저장하고 검색할 수 있는지에 영향을 미칩니다.
* 컴퓨팅 리소스의 사용률이 높아집니다.




== 지우기 코딩을 사용하는 경우

삭제 코딩은 다음 요구 사항에 가장 적합합니다.

* 크기가 1MB보다 큰 객체.
+

NOTE: 삭제 코딩은 1MB보다 큰 객체에 가장 적합합니다.  매우 작은 삭제 코딩된 조각을 관리하는 오버헤드를 피하기 위해 200KB보다 작은 객체에는 삭제 코딩을 사용하지 마세요.

* 자주 검색되지 않는 콘텐츠를 장기 보관하거나 냉장 보관합니다.
* 높은 데이터 가용성과 안정성.
* 전체 사이트 및 노드 장애로부터 보호합니다.
* 저장 효율성.
* 여러 개의 복제된 사본 대신 단일 삭제 코드 사본만으로 효율적인 데이터 보호가 필요한 단일 사이트 배포입니다.
* 사이트 간 지연 시간이 100ms 미만인 다중 사이트 배포.

