---
permalink: ilm/comparing-cloud-storage-pools-to-cloudmirror-replication.html 
sidebar: sidebar 
keywords: cloud storage pools, cloudmirror replication 
summary: Cloud Storage Pools를 사용하기 시작하면 Cloud Storage Pools와 StorageGRID CloudMirror 복제 서비스 간의 유사점과 차이점을 이해하는 것이 도움이 될 수 있습니다. 
---
= 클라우드 스토리지 풀과 CloudMirror 복제 비교
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cloud Storage Pools를 사용하기 시작하면 Cloud Storage Pools와 StorageGRID CloudMirror 복제 서비스 간의 유사점과 차이점을 이해하는 것이 도움이 될 수 있습니다.

[cols="1a,3a,3a"]
|===
|  | 클라우드 스토리지 풀 | CloudMirror 복제 서비스 


 a| 
주된 목적은 무엇입니까?
 a| 
보관 대상으로 작용합니다.  Cloud Storage 풀의 객체 복사본은 객체의 유일한 복사본일 수도 있고, 추가 복사본일 수도 있습니다.  즉, 두 개의 사본을 사이트에 보관하는 대신, StorageGRID 내에 한 개의 사본을 보관하고 나머지 한 개는 Cloud Storage Pool로 보낼 수 있습니다.
 a| 
테넌트가 StorageGRID (소스)의 버킷에서 외부 S3 버킷(대상)으로 객체를 자동으로 복제할 수 있도록 합니다.  독립적인 S3 인프라에서 객체의 독립적인 사본을 생성합니다.



 a| 
어떻게 설정되나요?
 a| 
Grid Manager 또는 Grid Management API를 사용하여 스토리지 풀과 동일한 방식으로 정의됩니다.  ILM 규칙에서 배치 위치로 선택할 수 있습니다.  스토리지 풀은 스토리지 노드 그룹으로 구성되는 반면, 클라우드 스토리지 풀은 원격 S3 또는 Azure 엔드포인트(IP 주소, 자격 증명 등)를 사용하여 정의됩니다.
 a| 
세입자 사용자link:../tenant/configuring-cloudmirror-replication.html["CloudMirror 복제를 구성합니다"] 테넌트 관리자나 S3 API를 사용하여 CloudMirror 엔드포인트(IP 주소, 자격 증명 등)를 정의합니다.  CloudMirror 엔드포인트가 설정된 후에는 해당 테넌트 계정이 소유한 모든 버킷을 CloudMirror 엔드포인트를 가리키도록 구성할 수 있습니다.



 a| 
이를 설정하는 책임은 누구에게 있나요?
 a| 
일반적으로 그리드 관리자
 a| 
일반적으로 세입자 사용자



 a| 
목적지는 어디인가요?
 a| 
* 모든 호환 S3 인프라(Amazon S3 포함)
* Azure Blob Archive 계층
* 구글 클라우드 플랫폼(GCP)

 a| 
* 모든 호환 S3 인프라(Amazon S3 포함)
* 구글 클라우드 플랫폼(GCP)




 a| 
물체가 목적지로 이동하게 하는 원인은 무엇인가?
 a| 
활성 ILM 정책에 하나 이상의 ILM 규칙이 있습니다.  ILM 규칙은 StorageGRID 어떤 객체를 Cloud Storage Pool로 옮길지, 그리고 객체를 언제 옮길지 정의합니다.
 a| 
CloudMirror 엔드포인트로 구성된 소스 버킷에 새 객체를 수집하는 작업입니다.  버킷이 CloudMirror 엔드포인트로 구성되기 전에 소스 버킷에 존재했던 개체는 수정되지 않는 한 복제되지 않습니다.



 a| 
객체는 어떻게 검색되나요?
 a| 
애플리케이션은 Cloud Storage 풀로 이동된 객체를 검색하기 위해 StorageGRID 에 요청을 보내야 합니다.  객체의 유일한 사본이 보관 저장소로 전환된 경우 StorageGRID 객체를 복원하는 프로세스를 관리하여 검색할 수 있도록 합니다.
 a| 
대상 버킷의 미러링된 복사본은 독립적인 복사본이므로 애플리케이션은 StorageGRID 또는 S3 대상에 요청을 보내 객체를 검색할 수 있습니다.  예를 들어, CloudMirror 복제를 사용하여 파트너 조직에 객체를 미러링한다고 가정해 보겠습니다.  파트너는 자체 애플리케이션을 사용하여 S3 대상에서 직접 객체를 읽거나 업데이트할 수 있습니다.  StorageGRID 사용할 필요는 없습니다.



 a| 
목적지에서 직접 읽을 수 있나요?
 a| 
아니요. Cloud Storage Pool로 이동된 객체는 StorageGRID 에서 관리합니다.  읽기 요청은 StorageGRID 로 전달되어야 하며( StorageGRID Cloud Storage Pool에서 검색을 담당합니다).
 a| 
네, 미러링된 사본은 독립적인 사본이기 때문입니다.



 a| 
소스에서 객체가 삭제되면 어떻게 되나요?
 a| 
해당 객체는 클라우드 스토리지 풀에서도 삭제됩니다.
 a| 
삭제 작업은 복제되지 않습니다.  삭제된 개체는 더 이상 StorageGRID 버킷에 존재하지 않지만 대상 버킷에는 계속 존재합니다.  마찬가지로, 대상 버킷의 객체는 소스에 영향을 주지 않고 삭제될 수 있습니다.



 a| 
재해(StorageGRID 시스템이 작동하지 않는 경우) 이후에는 어떻게 객체에 액세스합니까?
 a| 
오류가 발생한 StorageGRID 노드는 복구되어야 합니다.  이 프로세스 동안 복제된 객체의 사본은 Cloud Storage 풀의 사본을 사용하여 복원될 수 있습니다.
 a| 
CloudMirror 대상의 객체 복사본은 StorageGRID 와 독립적이므로 StorageGRID 노드가 복구되기 전에 직접 액세스할 수 있습니다.

|===