---
permalink: ilm/creating-cloud-storage-pool.html 
sidebar: sidebar 
keywords: how to create cloud storage pool 
summary: 클라우드 스토리지 풀은 단일 외부 Amazon S3 버킷이나 다른 S3 호환 공급자 또는 Azure Blob 스토리지 컨테이너를 지정합니다. 
---
= 클라우드 스토리지 풀 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클라우드 스토리지 풀은 단일 외부 Amazon S3 버킷이나 다른 S3 호환 공급자 또는 Azure Blob 스토리지 컨테이너를 지정합니다.

클라우드 스토리지 풀을 생성할 때 StorageGRID 객체를 저장하는 데 사용할 외부 버킷이나 컨테이너의 이름과 위치, 클라우드 공급자 유형(Amazon S3/GCP 또는 Azure Blob 스토리지), StorageGRID 외부 버킷이나 컨테이너에 액세스하는 데 필요한 정보를 지정합니다.

StorageGRID 클라우드 스토리지 풀을 저장하자마자 유효성을 검사하므로 클라우드 스토리지 풀에 지정된 버킷이나 컨테이너가 존재하고 접근 가능한지 확인해야 합니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["필요한 액세스 권한"] .
* 당신은 검토했습니다link:considerations-for-cloud-storage-pools.html["클라우드 스토리지 풀에 대한 고려 사항"] .
* Cloud Storage Pool에서 참조하는 외부 버킷 또는 컨테이너가 이미 존재하며<<service-endpoint-info,서비스 엔드포인트 정보>> .
* 버킷이나 컨테이너에 액세스하려면 다음이 필요합니다.<<authentication-account-info,인증 유형에 대한 계정 정보>> 당신이 선택하게 될 것입니다.


.단계
. *ILM* > *스토리지 풀* > *클라우드 스토리지 풀*을 선택합니다.
. *만들기*를 선택한 후 다음 정보를 입력하세요.
+
[cols="1a,3a"]
|===
| 필드 | 설명 


 a| 
클라우드 스토리지 풀 이름
 a| 
클라우드 스토리지 풀과 그 목적을 간략하게 설명하는 이름입니다.  ILM 규칙을 구성할 때 쉽게 식별할 수 있는 이름을 사용하세요.



 a| 
공급자 유형
 a| 
이 클라우드 스토리지 풀에 사용할 클라우드 공급자는 다음과 같습니다.

** *Amazon S3/GCP*: Amazon S3, Commercial Cloud Services(C2S) S3, Google Cloud Platform(GCP) 또는 기타 S3 호환 공급업체의 경우 이 옵션을 선택하세요.
** *Azure Blob 스토리지*




 a| 
양동이 또는 용기
 a| 
외부 S3 버킷 또는 Azure 컨테이너의 이름입니다.  클라우드 스토리지 풀을 저장한 후에는 이 값을 변경할 수 없습니다.

|===
. [[service-endpoint-info]]공급자 유형 선택에 따라 서비스 엔드포인트 정보를 입력하세요.
+
[role="tabbed-block"]
====
.아마존 S3/GCP
--
.. 프로토콜의 경우 HTTPS 또는 HTTP를 선택하세요.
+

NOTE: 민감한 데이터에는 HTTP 연결을 사용하지 마세요.

.. 호스트 이름을 입력하세요. 예:
+
`s3-_aws-region_.amazonaws.com`

.. URL 스타일을 선택하세요:
+
[cols="1a,3a"]
|===
| 옵션 | 설명 


 a| 
자동 감지
 a| 
제공된 정보를 토대로 어떤 URL 스타일을 사용할지 자동으로 감지해 보세요.  예를 들어 IP 주소를 지정하면 StorageGRID 경로 스타일 URL을 사용합니다.  어떤 특정 스타일을 사용해야 할지 모르는 경우에만 이 옵션을 선택하세요.



 a| 
가상 호스팅 스타일
 a| 
가상 호스팅 스타일 URL을 사용하여 버킷에 액세스합니다.  가상 호스팅 스타일 URL에는 도메인 이름의 일부로 버킷 이름이 포함됩니다.  예: `+https://bucket-name.s3.company.com/key-name+`



 a| 
경로 스타일
 a| 
버킷에 액세스하려면 경로 스타일 URL을 사용하세요.  경로 스타일 URL에는 버킷 이름이 끝에 포함됩니다.  예: `+https://s3.company.com/bucket-name/key-name+`

*참고:* 경로 스타일 URL 옵션은 권장되지 않으며 StorageGRID 의 향후 릴리스에서 더 이상 사용되지 않을 예정입니다.

|===
.. 선택적으로 포트 번호를 입력하거나 기본 포트인 HTTPS의 경우 443, HTTP의 경우 80을 사용하세요.


--
.Azure Blob 스토리지
--
.. 다음 형식 중 하나를 사용하여 서비스 엔드포인트의 URI를 입력하세요.
+
*** `+https://host:port+`
*** `+http://host:port+`




예: `https://_myaccount_.blob.core.windows.net:443`

포트를 지정하지 않으면 기본적으로 HTTPS에는 포트 443이 사용되고 HTTP에는 포트 80이 사용됩니다.

--
====


. [[인증-계정-정보]]*계속*을 선택하세요.  그런 다음 인증 유형을 선택하고 Cloud Storage Pool 엔드포인트에 필요한 정보를 입력합니다.
+
[role="tabbed-block"]
====
.액세스 키
--
_Amazon S3/GCP 또는 기타 S3 호환 공급자의 경우_

.. *액세스 키 ID*: 외부 버킷을 소유한 계정의 액세스 키 ID를 입력하세요.
.. *비밀 액세스 키*: 비밀 액세스 키를 입력하세요.


--
.어디서나 IAM 역할
--
_AWS IAM Roles Anywhere 서비스용_

StorageGRID AWS 보안 토큰 서비스(STS)를 사용하여 AWS 리소스에 액세스하기 위한 단기 토큰을 동적으로 생성합니다.

.. *AWS IAM 역할 어디서나 지역*: 클라우드 스토리지 풀에 대한 지역을 선택합니다. 예를 들어,  `us-east-1` .
.. *신뢰 앵커 URN*: 단기 STS 자격 증명에 대한 요청을 검증하는 신뢰 앵커의 URN을 입력하세요.  루트 또는 중간 CA가 될 수 있습니다.
.. *프로필 URN*: 신뢰할 수 있는 모든 사람이 맡을 수 있는 역할을 나열한 IAM Roles Anywhere 프로필의 URN을 입력합니다.
.. *역할 URN*: 신뢰할 수 있는 모든 사람이 맡을 수 있는 IAM 역할의 URN을 입력하세요.
.. *세션 기간*: 임시 보안 자격 증명과 역할 세션의 기간을 입력하세요.  최소 15분, 최대 12시간을 입력하세요.
.. *서버 CA 인증서* (선택 사항): IAM Roles Anywhere 서버를 확인하기 위한 PEM 형식의 하나 이상의 신뢰할 수 있는 CA 인증서입니다.  생략하면 서버가 검증되지 않습니다.
.. *최종 엔터티 인증서*: 신뢰 앵커가 서명한 X509 인증서의 PEM 형식의 공개 키입니다.  AWS IAM Roles Anywhere는 이 키를 사용하여 STS 토큰을 발급합니다.
.. *최종 엔터티 개인 키*: 최종 엔터티 인증서의 개인 키입니다.


--
.CAP(C2S 접속 포털)
--
_상업용 클라우드 서비스(C2S) S3 서비스_

.. *임시 자격 증명 URL*: StorageGRID CAP 서버에서 임시 자격 증명을 얻는 데 사용할 전체 URL을 입력하세요. 여기에는 C2S 계정에 할당된 모든 필수 및 선택 API 매개변수가 포함됩니다.
.. *서버 CA 인증서*: *찾아보기*를 선택하고 StorageGRID CAP 서버를 확인하는 데 사용할 CA 인증서를 업로드합니다.  인증서는 PEM으로 인코딩되어야 하며 적절한 정부 인증 기관(CA)에서 발급되어야 합니다.
.. *클라이언트 인증서*: *찾아보기*를 선택하고 StorageGRID CAP 서버에 자신을 식별하는 데 사용할 인증서를 업로드합니다.  클라이언트 인증서는 PEM으로 인코딩되어야 하며, 적절한 정부 인증 기관(CA)에서 발급되어야 하며, C2S 계정에 대한 액세스 권한이 부여되어야 합니다.
.. *클라이언트 개인 키*: *찾아보기*를 선택하고 클라이언트 인증서에 대한 PEM 인코딩된 개인 키를 업로드합니다.
.. 클라이언트 개인 키가 암호화되어 있는 경우 클라이언트 개인 키를 해독하기 위한 암호를 입력합니다.  그렇지 않은 경우 *클라이언트 개인 키 암호* 필드를 비워 두세요.



NOTE: 클라이언트 인증서가 암호화되는 경우 암호화에 기존 형식을 사용하세요.  PKCS #8 암호화 형식은 지원되지 않습니다.

--
.Azure Blob 스토리지
--
_Azure Blob Storage의 경우 공유 키만_

.. *계정 이름*: 외부 컨테이너를 소유한 스토리지 계정의 이름을 입력하세요.
.. *계정 키*: 저장소 계정의 비밀 키를 입력하세요.


Azure Portal을 사용하여 이러한 값을 찾을 수 있습니다.

--
.익명의
--
추가 정보는 필요하지 않습니다.

--
====
. *계속*을 선택하세요. 그런 다음 사용하려는 서버 검증 유형을 선택하세요.
+
[cols="1a,2a"]
|===
| 옵션 | 설명 


 a| 
Storage Node OS에서 루트 CA 인증서 사용
 a| 
운영 체제에 설치된 Grid CA 인증서를 사용하여 연결을 보호하세요.



 a| 
사용자 정의 CA 인증서 사용
 a| 
사용자 정의 CA 인증서를 사용합니다.  *찾아보기*를 선택하고 PEM으로 인코딩된 인증서를 업로드합니다.



 a| 
인증서를 확인하지 마세요
 a| 
이 옵션을 선택하면 Cloud Storage Pool에 대한 TLS 연결이 안전하지 않습니다.

|===
. *저장*을 선택하세요.
+
클라우드 스토리지 풀을 저장하면 StorageGRID 다음을 수행합니다.

+
** 버킷이나 컨테이너와 서비스 엔드포인트가 존재하고 사용자가 지정한 자격 증명을 사용하여 접근할 수 있는지 확인합니다.
** 버킷이나 컨테이너에 마커 파일을 작성하여 이를 Cloud Storage 풀로 식별합니다.  이 파일은 절대 제거하지 마십시오. `x-ntap-sgws-cloud-pool-uuid` .
+
Cloud Storage Pool 유효성 검사에 실패하면 유효성 검사가 실패한 이유를 설명하는 오류 메시지가 표시됩니다.  예를 들어, 인증서 오류가 있거나 지정한 버킷이나 컨테이너가 존재하지 않는 경우 오류가 보고될 수 있습니다.



. 오류가 발생하면 다음을 참조하세요.link:troubleshooting-cloud-storage-pools.html["클라우드 스토리지 풀 문제 해결 지침"] , 문제를 해결한 후 클라우드 스토리지 풀을 다시 저장해보세요.

