---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords: edit storage pool 
summary: 스토리지 풀을 편집하여 이름을 변경하거나 사이트 및 스토리지 등급을 업데이트할 수 있습니다. 
---
= 스토리지 풀 편집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 풀을 편집하여 이름을 변경하거나 사이트 및 스토리지 등급을 업데이트할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["특정 액세스 권한"] .
* 당신은 검토했습니다link:guidelines-for-creating-storage-pools.html["스토리지 풀 생성을 위한 지침"] .
* 활성 ILM 정책의 규칙에서 사용되는 스토리지 풀을 편집하려는 경우 변경 사항이 개체 데이터 배치에 어떤 영향을 미칠지 고려해야 합니다.


.이 작업에 관하여
활성 ILM 정책에서 사용되는 스토리지 풀에 새로운 사이트나 스토리지 등급을 추가하는 경우, 새로운 사이트나 스토리지 등급의 스토리지 노드가 자동으로 사용되지 않는다는 점에 유의하세요.  StorageGRID 새로운 사이트 또는 스토리지 등급을 사용하도록 하려면 편집된 스토리지 풀을 저장한 후 새로운 ILM 정책을 활성화해야 합니다.

.단계
. *ILM* > *스토리지 풀*을 선택합니다.
. 편집하려는 스토리지 풀의 확인란을 선택하세요.
+
모든 스토리지 노드 스토리지 풀(StorageGRID 11.6 및 이전 버전)을 편집할 수 없습니다.

. *편집*을 선택하세요.
. 필요에 따라 스토리지 풀 이름을 변경합니다.
. 필요에 따라 다른 사이트와 저장 등급을 선택하세요.
+
스토리지 풀이 삭제 코딩 프로필에 사용되고 해당 변경으로 인해 삭제 코딩 체계가 무효화되는 경우 사이트 또는 스토리지 등급을 변경할 수 없습니다.  예를 들어, 삭제 코딩 프로필에 사용된 스토리지 풀에 현재 사이트가 하나만 있는 스토리지 등급이 포함된 경우 삭제 코딩 방식을 변경하면 삭제 코딩 방식이 무효화되므로 두 개의 사이트가 있는 스토리지 등급을 사용할 수 없습니다.

+

CAUTION: 기존 스토리지 풀에서 사이트를 추가하거나 제거하더라도 기존 삭제 인코딩된 데이터는 이동되지 않습니다.  사이트에서 기존 데이터를 이동하려면 새 스토리지 풀과 EC 프로필을 만들어 데이터를 다시 인코딩해야 합니다.

. *저장*을 선택하세요.


.당신이 완료한 후
활성 ILM 정책에 사용된 스토리지 풀에 새 사이트 또는 스토리지 등급을 추가한 경우 새 ILM 정책을 활성화하여 StorageGRID 새 사이트 또는 스토리지 등급을 사용하도록 합니다.  예를 들어, 기존 ILM 정책을 복제한 다음 복제본을 활성화합니다. 보다 link:working-with-ilm-rules-and-ilm-policies.html["ILM 규칙 및 ILM 정책 사용"] .
