---
permalink: ilm/editing-cloud-storage-pool.html 
sidebar: sidebar 
keywords: edit cloud storage pool 
summary: 클라우드 스토리지 풀을 편집하여 이름, 서비스 엔드포인트 또는 기타 세부 정보를 변경할 수 있습니다. 그러나 클라우드 스토리지 풀의 S3 버킷이나 Azure 컨테이너는 변경할 수 없습니다. 
---
= 클라우드 스토리지 풀 편집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클라우드 스토리지 풀을 편집하여 이름, 서비스 엔드포인트 또는 기타 세부 정보를 변경할 수 있습니다. 그러나 클라우드 스토리지 풀의 S3 버킷이나 Azure 컨테이너는 변경할 수 없습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["특정 액세스 권한"] .
* 당신은 검토했습니다link:considerations-for-cloud-storage-pools.html["클라우드 스토리지 풀에 대한 고려 사항"] .


.단계
. *ILM* > *스토리지 풀* > *클라우드 스토리지 풀*을 선택합니다.
+
클라우드 스토리지 풀 테이블에는 기존 클라우드 스토리지 풀이 나열됩니다.

. 편집하려는 클라우드 스토리지 풀의 확인란을 선택한 다음, *작업* > *편집*을 선택합니다.
+
또는 클라우드 스토리지 풀의 이름을 선택한 다음 *편집*을 선택합니다.

. 필요에 따라 클라우드 스토리지 풀 이름, 서비스 엔드포인트, 인증 자격 증명 또는 인증서 확인 방법을 변경합니다.
+

NOTE: Cloud Storage 풀의 공급자 유형이나 S3 버킷 또는 Azure 컨테이너를 변경할 수 없습니다.

+
이전에 서버 또는 클라이언트 인증서를 업로드한 경우 *인증서 세부 정보* 아코디언을 확장하여 현재 사용 중인 인증서를 검토할 수 있습니다.

. *저장*을 선택하세요.
+
클라우드 스토리지 풀을 저장하면 StorageGRID 버킷이나 컨테이너와 서비스 엔드포인트가 존재하는지, 그리고 사용자가 지정한 자격 증명을 사용하여 이에 접근할 수 있는지 확인합니다.

+
클라우드 스토리지 풀 검증에 실패하면 오류 메시지가 표시됩니다.  예를 들어, 인증서 오류가 있는 경우 오류가 보고될 수 있습니다.

+
지침을 참조하세요link:troubleshooting-cloud-storage-pools.html["클라우드 스토리지 풀 문제 해결"] , 문제를 해결한 후 클라우드 스토리지 풀을 다시 저장해보세요.


