---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 여러 사이트에 데이터를 분산하여 데이터 손실을 방지하기 위해 스토리지 풀을 구성하고 사용합니다.  복제된 사본과 삭제된 사본에는 서로 다른 스토리지 풀 구성이 필요합니다. 
---
= 스토리지 풀 생성을 위한 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
여러 사이트에 데이터를 분산하여 데이터 손실을 방지하기 위해 스토리지 풀을 구성하고 사용합니다.  복제된 사본과 삭제된 사본에는 서로 다른 스토리지 풀 구성이 필요합니다.

보다 link:using-multiple-storage-pools-for-cross-site-replication.html["복제 및 삭제 코딩을 사용하여 사이트 손실 보호를 활성화하는 예"] .



== 모든 스토리지 풀에 대한 지침

* 스토리지 풀 구성을 가능한 한 단순하게 유지하세요.  필요 이상으로 스토리지 풀을 만들지 마세요.
* 가능한 한 많은 노드로 스토리지 풀을 만듭니다.  각 스토리지 풀에는 두 개 이상의 노드가 포함되어야 합니다.  노드가 부족한 스토리지 풀은 노드를 사용할 수 없게 되면 ILM 백로그를 유발할 수 있습니다.
* 동일한 노드가 하나 이상 포함된 겹치는 스토리지 풀을 만들거나 사용하지 마세요.  스토리지 풀이 겹치는 경우, 동일한 노드에 두 개 이상의 개체 데이터 사본이 저장될 수 있습니다.
* 일반적으로 All Storage Nodes 스토리지 풀(StorageGRID 11.6 및 이전 버전)이나 All Sites 사이트를 사용하지 마세요.  이러한 항목은 확장팩에 추가한 모든 새 사이트를 포함하도록 자동으로 업데이트되는데, 이는 원하지 않는 동작일 수 있습니다.




== 복제된 복사본에 사용되는 스토리지 풀에 대한 지침

* 사이트 손실 보호를 위해 다음을 사용합니다.link:what-replication-is.html["복제"] , 하나 이상의 사이트별 스토리지 풀을 지정합니다.link:create-ilm-rule-define-placements.html["각 ILM 규칙에 대한 배치 지침"] .
+
StorageGRID 설치하는 동안 각 사이트에 대해 하나의 스토리지 풀이 자동으로 생성됩니다.

+
각 사이트에 스토리지 풀을 사용하면 복제된 개체 사본이 예상한 위치에 정확하게 배치됩니다(예: 사이트 손실 보호를 위해 각 사이트에 모든 개체의 사본 하나씩).

* 확장에 사이트를 추가하는 경우 새 사이트만 포함하는 새 스토리지 풀을 만듭니다.  그 다음에,link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule["ILM 규칙 업데이트"] 새로운 사이트에 어떤 객체를 저장할지 제어합니다.
* 복사본 수가 스토리지 풀 수보다 적으면 시스템은 복사본을 분산하여 풀 간의 디스크 사용량을 균형 있게 조정합니다.
* 스토리지 풀이 겹치는 경우(동일한 스토리지 노드를 포함하는 경우) 개체의 모든 사본이 하나의 사이트에만 저장될 수 있습니다.  선택한 스토리지 풀에 동일한 스토리지 노드가 포함되지 않도록 해야 합니다.




== 삭제 코드화된 복사본에 사용되는 스토리지 풀에 대한 지침

* 사이트 손실 보호를 위해 다음을 사용합니다.link:what-erasure-coding-is.html["삭제 코딩"] 최소 3개의 사이트로 구성된 스토리지 풀을 만듭니다.  스토리지 풀에 두 개의 사이트만 포함된 경우 해당 스토리지 풀을 삭제 코딩에 사용할 수 없습니다.  두 개의 사이트가 있는 스토리지 풀에는 삭제 코딩 체계를 사용할 수 없습니다.
* 스토리지 풀에 포함된 스토리지 노드 및 사이트의 수는 다음을 결정합니다.link:what-erasure-coding-schemes-are.html["삭제 코딩 방식"] 이용 가능합니다.
* 가능하다면 스토리지 풀에는 선택한 삭제 코딩 방식에 필요한 최소 스토리지 노드 수보다 많은 스토리지 노드가 포함되어야 합니다.  예를 들어, 6+3 삭제 코딩 방식을 사용하는 경우 최소 9개의 스토리지 노드가 필요합니다.  하지만 사이트당 최소한 하나의 추가 스토리지 노드를 갖는 것이 좋습니다.
* 가능한 한 균등하게 여러 사이트에 저장 노드를 분산합니다.  예를 들어, 6+3 삭제 코딩 방식을 지원하려면 3개 사이트에 최소 3개의 스토리지 노드를 포함하는 스토리지 풀을 구성합니다.
* 높은 처리량 요구 사항이 있는 경우, 사이트 간 네트워크 지연 시간이 100ms를 넘으면 여러 사이트를 포함하는 스토리지 풀을 사용하는 것은 권장되지 않습니다.  대기 시간이 증가함에 따라 TCP 네트워크 처리량이 감소하여 StorageGRID 객체 조각을 생성, 배치 및 검색할 수 있는 속도가 급격히 감소합니다.
+
처리량 감소는 객체 수집 및 검색의 최대 달성 가능 속도에 영향을 미치거나(수집 동작으로 균형 또는 엄격을 선택한 경우) ILM 대기열 백로그로 이어질 수 있습니다(수집 동작으로 이중 커밋을 선택한 경우). 보다 link:what-ilm-rule-is.html#ilm-rule-ingest-behavior["ILM 규칙 수집 동작"] .

+

NOTE: 그리드에 사이트가 하나만 포함된 경우 삭제 코딩 프로필에서 모든 스토리지 노드 스토리지 풀(StorageGRID 11.6 및 이전 버전) 또는 모든 사이트 사이트를 사용할 수 없습니다.  이렇게 하면 두 번째 사이트가 추가되어도 프로필이 무효화되는 것을 방지할 수 있습니다.


