---
permalink: ilm/how-object-retention-is-determined.html 
sidebar: sidebar 
keywords: how object retention is determined 
summary: StorageGRID 그리드 관리자와 개별 테넌트 사용자 모두에게 객체를 저장할 기간을 지정할 수 있는 옵션을 제공합니다.  일반적으로 테넌트 사용자가 제공한 보존 지침은 그리드 관리자가 제공한 보존 지침보다 우선합니다. 
---
= 객체 보존이 결정되는 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 그리드 관리자와 개별 테넌트 사용자 모두에게 객체를 저장할 기간을 지정할 수 있는 옵션을 제공합니다.  일반적으로 테넌트 사용자가 제공한 보존 지침은 그리드 관리자가 제공한 보존 지침보다 우선합니다.



== 테넌트 사용자가 객체 보존을 제어하는 방법

테넌트 사용자는 이러한 방법을 사용하여 자신의 객체가 StorageGRID 에 저장되는 기간을 제어할 수 있습니다.

* 그리드에 대해 글로벌 S3 개체 잠금 설정이 활성화된 경우 S3 테넌트 사용자는 S3 개체 잠금이 활성화된 버킷을 생성한 다음 각 버킷에 대해 *기본 보존 기간*을 선택할 수 있습니다.
* 그리드에 대해 글로벌 S3 객체 잠금 설정이 활성화된 경우, S3 테넌트 사용자는 S3 객체 잠금이 활성화된 버킷을 생성한 다음 S3 REST API를 사용하여 해당 버킷에 추가된 각 객체 버전에 대한 보관 기한 및 법적 보존 설정을 지정할 수 있습니다.
+
** 법적 보존 조치가 적용된 객체 버전은 어떠한 방법으로도 삭제할 수 없습니다.
** 개체 버전의 보유 기한에 도달하기 전에는 어떠한 방법으로도 해당 버전을 삭제할 수 없습니다.
** S3 개체 잠금이 활성화된 버킷의 개체는 ILM에 "영구적으로" 보관됩니다.  그러나 보관 기한에 도달한 후에는 클라이언트 요청이나 버킷 수명 주기 만료로 인해 개체 버전이 삭제될 수 있습니다. 보다 link:managing-objects-with-s3-object-lock.html["S3 객체 잠금으로 객체 관리"] .


* S3 테넌트 사용자는 만료 작업을 지정하는 수명 주기 구성을 버킷에 추가할 수 있습니다.  버킷 수명 주기가 존재하는 경우 StorageGRID 클라이언트가 먼저 객체를 삭제하지 않는 한 만료 작업에 지정된 날짜 또는 일수가 충족될 때까지 객체를 저장합니다. 보다 link:../s3/create-s3-lifecycle-configuration.html["S3 수명 주기 구성 만들기"] .
* S3 클라이언트는 객체 삭제 요청을 발행할 수 있습니다.  StorageGRID 객체를 삭제할지 보존할지 결정할 때 항상 S3 버킷 수명 주기나 ILM보다 클라이언트 삭제 요청을 우선시합니다.




== 그리드 관리자가 객체 보존을 제어하는 방법

그리드 관리자는 다음 방법을 사용하여 개체 보존을 제어할 수 있습니다.

* 각 테넌트에 대해 S3 개체 잠금 최대 보존 기간을 설정합니다.  그러면 테넌트 사용자는 각 버킷에 대한 기본 보존 기간을 설정할 수 있습니다.  최대 보존 기간은 해당 버킷에 새로 수집된 모든 객체에도 적용됩니다(객체의 보존 기간).
* ILM 배치 지침을 만들어 객체가 보관되는 기간을 제어합니다.  객체가 ILM 규칙에 따라 일치하는 경우 StorageGRID ILM 규칙의 마지막 기간이 경과할 때까지 해당 객체를 저장합니다.  배치 지침에 "영구"가 지정된 경우 객체는 무기한 보관됩니다.
* 객체 보관 기간을 누가 제어하는지에 관계없이 ILM 설정은 어떤 유형의 객체 사본(복제 또는 삭제 코드)을 저장할지, 그리고 사본이 어디에 위치할지(스토리지 노드 또는 클라우드 스토리지 풀)를 제어합니다.




== S3 버킷 수명 주기와 ILM의 상호 작용 방식

S3 버킷 수명 주기가 구성되면 수명 주기 만료 작업은 수명 주기 필터와 일치하는 개체에 대한 ILM 정책을 재정의합니다.  결과적으로, 객체를 배치하기 위한 ILM 지침이 만료된 후에도 객체가 그리드에 유지될 수 있습니다.



== 객체 보존의 예

S3 객체 잠금, 버킷 수명 주기 설정, 클라이언트 삭제 요청 및 ILM 간의 상호 작용을 더 잘 이해하려면 다음 예를 살펴보세요.



=== 예 1: S3 버킷 수명 주기는 ILM보다 객체를 더 오래 보관합니다.

일엠엠:: 1년(365일) 동안 2부 보관
버킷 수명 주기:: 2년(730일) 후에 객체 만료
결과:: StorageGRID 객체를 730일 동안 저장합니다.  StorageGRID 버킷 수명 주기 설정을 사용하여 객체를 삭제할지 아니면 보존할지 결정합니다.



NOTE: 버킷 수명 주기가 ILM에서 지정한 기간보다 객체를 더 오랫동안 보관해야 한다고 지정하는 경우 StorageGRID 저장할 복사본의 수와 유형을 결정할 때 ILM 배치 지침을 계속 사용합니다.  이 예에서 객체의 두 사본은 366일부터 730일까지 StorageGRID 에 계속 저장됩니다.



=== 예 2: S3 버킷 수명 주기는 ILM보다 먼저 객체를 만료합니다.

일엠엠:: 2년(730일) 동안 2부 보관
버킷 수명 주기:: 1년(365일) 후에 객체 만료
결과:: StorageGRID 365일 후에 해당 객체의 두 사본을 모두 삭제합니다.




=== 예 3: 클라이언트 삭제는 버킷 수명 주기 및 ILM을 재정의합니다.

일엠엠:: 스토리지 노드에 두 개의 사본을 "영구적으로" 저장합니다.
버킷 수명 주기:: 2년(730일) 후에 객체 만료
클라이언트 삭제 요청:: 400일째에 발행됨
결과:: StorageGRID 클라이언트 삭제 요청에 응답하여 400일째에 해당 객체의 두 사본을 모두 삭제합니다.




=== 예제 4: S3 객체 잠금이 클라이언트 삭제 요청을 재정의합니다.

S3 객체 잠금:: 객체 버전의 보관 날짜는 2026-03-31입니다.  법적 보호 조치가 적용되지 않습니다.
ILM 규정 준수:: 스토리지 노드에 두 개의 사본을 "영구적으로" 저장합니다.
클라이언트 삭제 요청:: 2024년 3월 31일 발행
결과:: StorageGRID 보관 기간이 아직 2년이나 남았기 때문에 개체 버전을 삭제하지 않습니다.

