---
permalink: ilm/lifecycle-of-cloud-storage-pool-object.html 
sidebar: sidebar 
keywords: lifecycle of cloud storage pool object 
summary: Cloud Storage Pool을 구현하기 전에 각 유형의 Cloud Storage Pool에 저장된 객체의 수명 주기를 검토하세요. 
---
= Cloud Storage Pool 객체의 수명 주기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cloud Storage Pool을 구현하기 전에 각 유형의 Cloud Storage Pool에 저장된 객체의 수명 주기를 검토하세요.



== S3: 클라우드 스토리지 풀 객체의 수명 주기

이 단계에서는 S3 클라우드 스토리지 풀에 저장된 객체의 수명 주기 단계를 설명합니다.


NOTE: "Glacier"는 Glacier 스토리지 클래스와 Glacier Deep Archive 스토리지 클래스를 모두 지칭하지만, 한 가지 예외가 있습니다. Glacier Deep Archive 스토리지 클래스는 긴급 복원 계층을 지원하지 않습니다.  대량 검색이나 표준 검색만 지원됩니다.


NOTE: Google Cloud Platform(GCP)은 POST 복원 작업을 요구하지 않고도 장기 저장소에서 객체를 검색할 수 있도록 지원합니다.

. * StorageGRID 에 저장된 객체*
+
라이프사이클을 시작하려면 클라이언트 애플리케이션이 StorageGRID 에 객체를 저장합니다.

. *객체가 S3 클라우드 스토리지 풀로 이동되었습니다*
+
** 해당 개체가 S3 클라우드 스토리지 풀을 배치 위치로 사용하는 ILM 규칙과 일치하는 경우, StorageGRID 해당 개체를 클라우드 스토리지 풀에서 지정한 외부 S3 버킷으로 이동합니다.
** 객체가 S3 클라우드 스토리지 풀로 이동되면 클라이언트 애플리케이션은 객체가 Glacier 스토리지로 전환되지 않는 한 StorageGRID 에서 S3 GetObject 요청을 사용하여 객체를 검색할 수 있습니다.


. *객체가 Glacier로 전환됨(회수 불가 상태)*
+
** 선택적으로 객체를 Glacier 저장소로 전환할 수 있습니다.  예를 들어, 외부 S3 버킷은 수명 주기 구성을 사용하여 객체를 즉시 또는 며칠 후에 Glacier 스토리지로 전환할 수 있습니다.
+

NOTE: 객체를 전환하려면 외부 S3 버킷에 대한 수명 주기 구성을 생성해야 하며, Glacier 스토리지 클래스를 구현하고 S3 RestoreObject API를 지원하는 스토리지 솔루션을 사용해야 합니다.

** 전환 중에 클라이언트 애플리케이션은 S3 HeadObject 요청을 사용하여 객체의 상태를 모니터링할 수 있습니다.


. *Glacier 저장소에서 복원된 객체*
+
객체가 Glacier 스토리지로 전환된 경우 클라이언트 애플리케이션은 S3 RestoreObject 요청을 발행하여 검색 가능한 복사본을 S3 클라우드 스토리지 풀로 복원할 수 있습니다.  요청에서는 클라우드 스토리지 풀에서 복사본을 며칠 동안 사용할 수 있는지와 복원 작업에 사용할 데이터 액세스 계층(신속, 표준 또는 대량)을 지정합니다.  검색 가능한 사본의 만료일이 지나면 해당 사본은 자동으로 검색 불가능한 상태로 돌아갑니다.

+

NOTE: StorageGRID 내의 스토리지 노드에도 개체의 사본이 하나 이상 있는 경우 RestoreObject 요청을 실행하여 Glacier에서 개체를 복원할 필요가 없습니다.  대신 GetObject 요청을 사용하여 로컬 복사본을 직접 검색할 수 있습니다.

. *객체 검색됨*
+
개체가 복구되면 클라이언트 애플리케이션은 GetObject 요청을 발행하여 복구된 개체를 검색할 수 있습니다.





== Azure: 클라우드 스토리지 풀 개체의 수명 주기

이 단계에서는 Azure Cloud Storage 풀에 저장된 개체의 수명 주기 단계를 설명합니다.

. * StorageGRID 에 저장된 객체*
+
라이프사이클을 시작하려면 클라이언트 애플리케이션이 StorageGRID 에 객체를 저장합니다.

. *개체가 Azure Cloud Storage 풀로 이동됨*
+
개체가 Azure Cloud Storage Pool을 배치 위치로 사용하는 ILM 규칙과 일치하는 경우 StorageGRID 개체를 Cloud Storage Pool에서 지정한 외부 Azure Blob 스토리지 컨테이너로 이동합니다.

. *객체가 보관 계층으로 전환됨(검색 불가 상태)*
+
개체를 Azure Cloud Storage 풀로 이동한 직후, StorageGRID 자동으로 해당 개체를 Azure Blob Storage 보관 계층으로 전환합니다.

. *아카이브 계층에서 복원된 개체*
+
개체가 보관 계층으로 전환된 경우 클라이언트 애플리케이션은 S3 RestoreObject 요청을 발행하여 검색 가능한 복사본을 Azure Cloud Storage 풀로 복원할 수 있습니다.

+
StorageGRID RestoreObject를 수신하면 해당 개체를 일시적으로 Azure Blob 저장소 Cool 계층으로 전환합니다.  RestoreObject 요청의 만료 날짜에 도달하면 StorageGRID 해당 객체를 다시 Archive 계층으로 전환합니다.

+

NOTE: StorageGRID 내의 스토리지 노드에도 개체의 사본이 하나 이상 있는 경우 RestoreObject 요청을 실행하여 아카이브 액세스 계층에서 개체를 복원할 필요가 없습니다.  대신 GetObject 요청을 사용하여 로컬 복사본을 직접 검색할 수 있습니다.

. *객체 검색됨*
+
개체가 Azure Cloud Storage 풀에 복원되면 클라이언트 애플리케이션은 GetObject 요청을 실행하여 복원된 개체를 검색할 수 있습니다.



.관련 정보
link:../s3/index.html["S3 REST API 사용"]
