---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: 그리드 관리자는 StorageGRID 시스템에 대해 S3 개체 잠금을 활성화하고 규정을 준수하는 ILM 정책을 구현하여 특정 S3 버킷의 개체가 지정된 시간 동안 삭제되거나 덮어쓰여지지 않도록 할 수 있습니다. 
---
= S3 객체 잠금으로 객체 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
그리드 관리자는 StorageGRID 시스템에 대해 S3 개체 잠금을 활성화하고 규정을 준수하는 ILM 정책을 구현하여 특정 S3 버킷의 개체가 지정된 시간 동안 삭제되거나 덮어쓰여지지 않도록 할 수 있습니다.



== S3 객체 잠금이란 무엇인가요?

StorageGRID S3 객체 잠금 기능은 Amazon Simple Storage Service(Amazon S3)의 S3 객체 잠금과 동일한 객체 보호 솔루션입니다.

StorageGRID 시스템에 대해 글로벌 S3 개체 잠금 설정이 활성화된 경우 S3 테넌트 계정은 S3 개체 잠금이 활성화되어 있거나 활성화되지 않은 버킷을 생성할 수 있습니다.  버킷에 S3 객체 잠금이 활성화된 경우 버킷 버전 관리가 필요하며 자동으로 활성화됩니다.

*S3 객체 잠금이 없는 버킷*에는 보존 설정이 지정되지 않은 객체만 있을 수 있습니다.  섭취된 객체에는 보존 설정이 없습니다.

*S3 객체 잠금이 있는 버킷*에는 S3 클라이언트 애플리케이션에서 지정한 보존 설정이 있는 객체와 없는 객체가 있을 수 있습니다.  수집된 일부 객체에는 보존 설정이 있습니다.

*S3 객체 잠금 및 기본 보존 기간이 구성된 버킷*에는 보존 기간이 지정된 객체를 업로드할 수 있으며 보존 기간이 설정되지 않은 새 객체를 업로드할 수 있습니다.  새 개체는 보존 설정이 개체 수준에서 구성되지 않았기 때문에 기본 설정을 사용합니다.

실제로 기본 보존이 구성된 경우 새로 수집된 모든 개체에는 보존 설정이 적용됩니다.  객체 보존 설정이 없는 기존 객체는 영향을 받지 않습니다.



=== 보존 모드

StorageGRID S3 객체 잠금 기능은 객체에 다양한 수준의 보호를 적용하기 위해 두 가지 보존 모드를 지원합니다.  이러한 모드는 Amazon S3 보존 모드와 동일합니다.

* 규정 준수 모드에서:
+
** 해당 객체는 보관 만료일에 도달할 때까지 삭제할 수 없습니다.
** 객체의 보관 기한은 늘릴 수 있지만 줄일 수는 없습니다.
** 해당 날짜에 도달하기 전까지는 객체의 보관 기간을 제거할 수 없습니다.


* 거버넌스 모드에서:
+
** 특별 권한이 있는 사용자는 요청에서 우회 헤더를 사용하여 특정 보존 설정을 수정할 수 있습니다.
** 이러한 사용자는 보관 기한에 도달하기 전에 개체 버전을 삭제할 수 있습니다.
** 이러한 사용자는 객체의 보관 기간을 늘리거나 줄이거나 제거할 수 있습니다.






=== 객체 버전에 대한 보존 설정

S3 객체 잠금이 활성화된 버킷을 생성한 경우 사용자는 S3 클라이언트 애플리케이션을 사용하여 버킷에 추가된 각 객체에 대해 다음과 같은 보존 설정을 선택적으로 지정할 수 있습니다.

* *보존 모드*: 규정 준수 또는 거버넌스.
* *보관 날짜*: 개체 버전의 보관 날짜가 미래인 경우, 개체를 검색할 수는 있지만 삭제할 수는 없습니다.
* *법적 보존*: 객체 버전에 법적 보존을 적용하면 해당 객체가 즉시 잠깁니다.  예를 들어, 조사나 법적 분쟁과 관련된 객체에 대해 법적 보류를 요청해야 할 수도 있습니다.  법적 보존에는 만료일이 없지만, 명시적으로 삭제하기 전까지는 유지됩니다.  법적 보존 기간은 보존 기한과 별개입니다.
+

NOTE: 객체가 법적 보존 상태에 있는 경우, 보존 모드에 관계없이 누구도 객체를 삭제할 수 없습니다.

+
객체 설정에 대한 자세한 내용은 다음을 참조하세요.link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 객체 잠금을 구성합니다."] .





=== 버킷에 대한 기본 보존 설정

S3 객체 잠금이 활성화된 버킷이 생성된 경우 사용자는 선택적으로 버킷에 대해 다음과 같은 기본 설정을 지정할 수 있습니다.

* *기본 보존 모드*: 규정 준수 또는 거버넌스.
* *기본 보존 기간*: 이 버킷에 추가된 새 개체 버전을 보존해야 하는 기간으로, 추가된 날로부터 시작됩니다.


기본 버킷 설정은 자체 보존 설정이 없는 새 개체에만 적용됩니다.  이러한 기본 설정을 추가하거나 변경해도 기존 버킷 개체는 영향을 받지 않습니다.

보다link:../tenant/creating-s3-bucket.html["S3 버킷 생성"] 그리고link:../tenant/update-default-retention-settings.html["S3 객체 잠금 기본 보존 기간 업데이트"] .



== S3 객체 잠금과 레거시 규정 준수 비교

S3 객체 잠금은 이전 StorageGRID 버전에서 사용 가능했던 규정 준수 기능을 대체합니다.  S3 객체 잠금 기능은 Amazon S3 요구 사항을 준수하므로 이제는 "레거시 규정 준수"라고 하는 독점적인 StorageGRID 규정 준수 기능이 더 이상 사용되지 않습니다.


NOTE: 글로벌 규정 준수 설정은 더 이상 사용되지 않습니다.  이전 버전의 StorageGRID 사용하여 이 설정을 활성화한 경우 S3 개체 잠금 설정이 자동으로 활성화됩니다.  StorageGRID 사용하여 기존 호환 버킷의 설정을 계속 관리할 수 있습니다. 그러나 새 호환 버킷을 만들 수는 없습니다.  자세한 내용은 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp 지식 기반: StorageGRID 11.5에서 레거시 호환 버킷을 관리하는 방법"^] .

이전 버전의 StorageGRID 에서 레거시 규정 준수 기능을 사용한 경우 다음 표를 참조하여 StorageGRID 의 S3 개체 잠금 기능과 비교해 보세요.

[cols="1a,1a,1a"]
|===
|  | S3 객체 잠금 | 규정 준수(레거시) 


 a| 
이 기능은 어떻게 전 세계적으로 활성화되나요?
 a| 
그리드 관리자에서 *구성* > *시스템* > *S3 객체 잠금*을 선택합니다.
 a| 
더 이상 지원되지 않습니다.



 a| 
버킷에 대해 이 기능을 어떻게 활성화하나요?
 a| 
사용자는 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 새 버킷을 생성할 때 S3 개체 잠금을 활성화해야 합니다.
 a| 
더 이상 지원되지 않습니다.



 a| 
버킷 버전 관리가 지원되나요?
 a| 
네. 버킷 버전 관리가 필요하며 버킷에 대해 S3 객체 잠금이 활성화되면 자동으로 활성화됩니다.
 a| 
아니요.



 a| 
객체 보존은 어떻게 설정되나요?
 a| 
사용자는 각 개체 버전에 대한 보관 날짜를 설정하거나 각 버킷에 대한 기본 보관 기간을 설정할 수 있습니다.
 a| 
사용자는 버킷 전체에 대한 보존 기간을 설정해야 합니다.  보존 기간은 버킷의 모든 객체에 적용됩니다.



 a| 
보관 기간을 변경할 수 있나요?
 a| 
* 규정 준수 모드에서는 객체 버전의 보관 기한을 늘릴 수는 있지만 줄일 수는 없습니다.
* 거버넌스 모드에서는 특별한 권한이 있는 사용자가 개체의 보존 설정을 줄이거나 제거할 수도 있습니다.

 a| 
버킷의 보관 기간은 늘릴 수 있지만 줄일 수는 없습니다.



 a| 
법적 보류는 어디에서 관리됩니까?
 a| 
사용자는 버킷의 모든 객체 버전에 대해 법적 보류를 설정하거나 해제할 수 있습니다.
 a| 
버킷에 법적 보류가 적용되어 버킷에 있는 모든 객체에 영향을 미칩니다.



 a| 
객체를 삭제할 수 있는 경우는 언제인가요?
 a| 
* 규정 준수 모드에서는 객체가 법적 보존 상태에 있지 않다고 가정하고, 보관 기한에 도달한 후에는 객체 버전을 삭제할 수 있습니다.
* 거버넌스 모드에서는 특별 권한이 있는 사용자가 객체가 법적 보존 상태에 있지 않은 경우, 보관 기한에 도달하기 전에 객체를 삭제할 수 있습니다.

 a| 
버킷이 법적 보존 상태에 있지 않은 경우, 보존 기간이 만료된 후에도 객체를 삭제할 수 있습니다.  객체는 자동 또는 수동으로 삭제할 수 있습니다.



 a| 
버킷 수명 주기 구성이 지원됩니까?
 a| 
예
 a| 
아니요

|===