---
permalink: ilm/manage-ilm-policy-tags.html 
sidebar: sidebar 
keywords: ILM policy tag 
summary: ILM 정책 태그 세부 정보를 보고, 태그를 편집하거나, 태그를 제거할 수 있습니다. 
---
= ILM 정책 태그 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 정책 태그 세부 정보를 보고, 태그를 편집하거나, 태그를 제거할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["필요한 액세스 권한"] .




== ILM 정책 태그 세부 정보 보기

태그에 대한 세부 정보를 보려면:

. *ILM* > *정책 태그*를 선택합니다.
. 표에서 정책 이름을 선택하세요.  태그에 대한 세부 정보 페이지가 나타납니다.
. 세부 정보 페이지에서 할당된 정책의 이전 기록을 볼 수 있습니다.
. 정책을 선택하여 확인하세요.




== ILM 정책 태그 편집


NOTE: 태그 이름과 설명은 세입자에게 표시됩니다.  세입자가 버킷에 할당할 정책 태그를 선택할 때 정보에 입각한 결정을 내리는 데 도움이 되는 값을 선택하세요.  예를 들어, 할당된 정책에 따라 일정 기간이 지나면 객체가 삭제되는 경우 설명에 해당 내용을 포함할 수 있습니다.  이 필드에는 민감한 정보를 포함하지 마세요.

기존 태그에 대한 설명을 편집하려면:

. *ILM* > *정책 태그*를 선택합니다.
. 태그의 확인란을 선택한 다음 *편집*을 선택합니다.
+
또는 태그 이름을 선택하세요.  태그에 대한 세부 정보 페이지가 나타나고, 해당 페이지에서 *편집*을 선택할 수 있습니다.

. 필요에 따라 태그 설명을 변경하세요
. *저장*을 선택하세요.




== ILM 정책 태그 제거

정책 태그를 제거하면 해당 태그가 할당된 모든 버킷에 기본 정책이 적용됩니다.

태그를 제거하려면:

. *ILM* > *정책 태그*를 선택합니다.
. 태그의 확인란을 선택한 다음 *제거*를 선택합니다.  확인 대화 상자가 나타납니다.
+
또는 태그 이름을 선택하세요.  태그에 대한 세부 정보 페이지가 나타나고, 해당 페이지에서 *제거*를 선택할 수 있습니다.

. 태그를 삭제하려면 *예*를 선택하세요.

