---
permalink: ilm/removing-cloud-storage-pool.html 
sidebar: sidebar 
keywords: remove cloud storage pool 
summary: ILM 규칙에서 사용되지 않고 개체 데이터를 포함하지 않는 클라우드 스토리지 풀은 제거할 수 있습니다. 
---
= 클라우드 스토리지 풀 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 규칙에서 사용되지 않고 개체 데이터를 포함하지 않는 클라우드 스토리지 풀은 제거할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["필요한 액세스 권한"] .




== 필요한 경우 ILM을 사용하여 개체 데이터를 이동합니다.

제거하려는 클라우드 스토리지 풀에 개체 데이터가 포함되어 있는 경우 ILM을 사용하여 해당 데이터를 다른 위치로 이동해야 합니다.  예를 들어, 그리드의 스토리지 노드나 다른 클라우드 스토리지 풀로 데이터를 이동할 수 있습니다.

.단계
. *ILM* > *스토리지 풀* > *클라우드 스토리지 풀*을 선택합니다.
. 표의 ILM 사용량 열을 확인하여 클라우드 스토리지 풀을 제거할 수 있는지 확인하세요.
+
ILM 규칙이나 삭제 코딩 프로필에서 사용 중인 클라우드 스토리지 풀은 제거할 수 없습니다.

. 클라우드 스토리지 풀을 사용 중인 경우 *_클라우드 스토리지 풀 이름_* > *ILM 사용량*을 선택합니다.
. link:working-with-ilm-rules-and-ilm-policies.html["각 ILM 규칙을 복제합니다."]현재 제거하려는 Cloud Storage Pool에 객체를 배치합니다.
. 복제한 각 규칙에 의해 관리되는 기존 객체를 이동할 위치를 결정합니다.
+
하나 이상의 스토리지 풀이나 다른 클라우드 스토리지 풀을 사용할 수 있습니다.

. 복제한 각 규칙을 편집합니다.
+
ILM 규칙 생성 마법사의 2단계에서 *복사 위치* 필드에서 새 위치를 선택합니다.

. link:creating-ilm-policy.html["새로운 ILM 정책 만들기"]그리고 기존의 규칙을 복제된 규칙으로 대체합니다.
. 새로운 정책을 활성화합니다.
. ILM이 클라우드 스토리지 풀에서 객체를 제거하고 새 위치에 배치할 때까지 기다립니다.




== 클라우드 스토리지 풀 삭제

클라우드 스토리지 풀이 비어 있고 ILM 규칙에 사용되지 않으면 삭제할 수 있습니다.

.시작하기 전에
* 풀을 사용했을 수 있는 ILM 규칙을 제거했습니다.
* S3 버킷이나 Azure 컨테이너에 아무 개체도 포함되어 있지 않음을 확인했습니다.
+
객체가 포함된 Cloud Storage 풀을 제거하려고 하면 오류가 발생합니다. 보다 link:troubleshooting-cloud-storage-pools.html["클라우드 스토리지 풀 문제 해결"] .

+

NOTE: Cloud Storage 풀을 생성하면 StorageGRID 버킷이나 컨테이너에 마커 파일을 작성하여 이를 Cloud Storage 풀로 식별합니다.  이 파일은 제거하지 마세요. `x-ntap-sgws-cloud-pool-uuid` .



.단계
. *ILM* > *스토리지 풀* > *클라우드 스토리지 풀*을 선택합니다.
. ILM 사용량 열에 Cloud Storage Pool이 사용되지 않음이 표시되면 확인란을 선택합니다.
. *작업* > *제거*를 선택합니다.
. *확인*을 선택하세요.

