---
permalink: ilm/requirements-for-s3-object-lock.html 
sidebar: sidebar 
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy 
summary: 글로벌 S3 개체 잠금 설정을 활성화하기 위한 요구 사항, 규정을 준수하는 ILM 규칙과 ILM 정책을 생성하기 위한 요구 사항, 그리고 StorageGRID S3 개체 잠금을 사용하는 버킷과 개체에 적용하는 제한 사항을 검토해야 합니다. 
---
= S3 객체 잠금 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
글로벌 S3 개체 잠금 설정을 활성화하기 위한 요구 사항, 규정을 준수하는 ILM 규칙과 ILM 정책을 생성하기 위한 요구 사항, 그리고 StorageGRID S3 개체 잠금을 사용하는 버킷과 개체에 적용하는 제한 사항을 검토해야 합니다.



== 글로벌 S3 객체 잠금 설정을 사용하기 위한 요구 사항

* S3 테넌트가 S3 개체 잠금이 활성화된 버킷을 생성하려면 먼저 Grid Manager 또는 Grid Management API를 사용하여 글로벌 S3 개체 잠금 설정을 활성화해야 합니다.
* 글로벌 S3 개체 잠금 설정을 활성화하면 모든 S3 테넌트 계정에서 S3 개체 잠금이 활성화된 버킷을 생성할 수 있습니다.
* 글로벌 S3 개체 잠금 설정을 활성화한 후에는 해당 설정을 비활성화할 수 없습니다.
* 모든 활성 ILM 정책의 기본 규칙이 _준수_되어야 합니다(즉, 기본 규칙은 S3 개체 잠금이 활성화된 버킷의 요구 사항을 준수해야 함). 그렇지 않으면 글로벌 S3 개체 잠금을 활성화할 수 없습니다.
* 글로벌 S3 개체 잠금 설정이 활성화된 경우 정책의 기본 규칙이 규정을 준수하지 않는 한 새 ILM 정책을 만들거나 기존 ILM 정책을 활성화할 수 없습니다.  글로벌 S3 개체 잠금 설정이 활성화되면 ILM 규칙 및 ILM 정책 페이지에 어떤 ILM 규칙이 준수되는지 표시됩니다.




== ILM 규정 준수에 대한 요구 사항

글로벌 S3 개체 잠금 설정을 활성화하려면 모든 활성 ILM 정책의 기본 규칙이 규정을 준수하는지 확인해야 합니다.  규정 준수 규칙은 S3 객체 잠금이 활성화된 버킷과 레거시 규정 준수가 활성화된 기존 버킷의 요구 사항을 모두 충족합니다.

* 최소한 두 개의 복제된 객체 사본이나 하나의 삭제 코드화된 사본을 만들어야 합니다.
* 이러한 사본은 배치 지침의 각 줄 전체 기간 동안 스토리지 노드에 존재해야 합니다.
* 객체 사본은 Cloud Storage 풀에 저장할 수 없습니다.
* 배치 지침의 적어도 한 줄은 *수집 시간*을 참조 시간으로 사용하여 0일부터 시작해야 합니다.
* 배치 지침 중 적어도 한 줄은 "영구"여야 합니다.




== ILM 정책 요구 사항

글로벌 S3 개체 잠금 설정이 활성화되면 활성 및 비활성 ILM 정책에 규정을 준수하는 규칙과 규정을 준수하지 않는 규칙이 모두 포함될 수 있습니다.

* 활성 또는 비활성 ILM 정책의 기본 규칙은 규정을 준수해야 합니다.
* 비준수 규칙은 S3 객체 잠금이 활성화되지 않았거나 기존 규정 준수 기능이 활성화되지 않은 버킷의 객체에만 적용됩니다.
* 규정 준수 규칙은 모든 버킷의 객체에 적용될 수 있습니다. 버킷에 대해 S3 객체 잠금이나 레거시 규정 준수를 활성화할 필요는 없습니다.


link:example-7-compliant-ilm-policy-for-s3-object-lock.html["S3 개체 잠금에 대한 규정 준수 ILM 정책의 예"]



== S3 객체 잠금이 활성화된 버킷에 대한 요구 사항

* StorageGRID 시스템에 대해 글로벌 S3 개체 잠금 설정이 활성화된 경우 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 S3 개체 잠금이 활성화된 버킷을 생성할 수 있습니다.
* S3 객체 잠금을 사용하려면 버킷을 생성할 때 S3 객체 잠금을 활성화해야 합니다.  기존 버킷에 대해 S3 개체 잠금을 활성화할 수 없습니다.
* 버킷에 대해 S3 객체 잠금이 활성화되면 StorageGRID 자동으로 해당 버킷에 대한 버전 관리를 활성화합니다.  버킷에 대한 S3 객체 잠금을 비활성화하거나 버전 관리를 일시 중단할 수 없습니다.
* 선택적으로 테넌트 관리자, 테넌트 관리 API 또는 S3 REST API를 사용하여 각 버킷에 대한 기본 보존 모드와 보존 기간을 지정할 수 있습니다.  버킷의 기본 보존 설정은 자체 보존 설정이 없는 버킷에 추가된 새 객체에만 적용됩니다.  업로드 시 각 객체 버전에 대한 보존 모드와 보존 기간을 지정하여 이러한 기본 설정을 재정의할 수 있습니다.
* 버킷 수명 주기 구성은 S3 객체 잠금이 활성화된 버킷에 대해 지원됩니다.
* S3 개체 잠금이 활성화된 버킷에서는 CloudMirror 복제가 지원되지 않습니다.




== S3 객체 잠금이 활성화된 버킷의 객체에 대한 요구 사항

* 개체 버전을 보호하려면 버킷에 대한 기본 보존 설정을 지정하거나 각 개체 버전에 대한 보존 설정을 지정할 수 있습니다.  객체 수준 보존 설정은 S3 클라이언트 애플리케이션이나 S3 REST API를 사용하여 지정할 수 있습니다.
* 보존 설정은 개별 개체 버전에 적용됩니다.  객체 버전에는 보관 마감일과 법적 보존 설정이 모두 있을 수 있으며, 둘 중 하나만 있을 수도 있고, 둘 다 없을 수도 있습니다.  객체에 대해 보관 기한 또는 법적 보존 설정을 지정하면 요청에 지정된 버전만 보호됩니다.  이전 버전의 개체는 잠긴 상태로 유지되는 동안 해당 개체의 새 버전을 만들 수 있습니다.




== S3 객체 잠금이 활성화된 버킷의 객체 수명 주기

S3 객체 잠금이 활성화된 버킷에 저장된 각 객체는 다음 단계를 거칩니다.

. *객체 수집*
+
S3 객체 잠금이 활성화된 버킷에 객체 버전이 추가되면 보존 설정이 다음과 같이 적용됩니다.

+
** 개체에 대한 보존 설정이 지정된 경우 개체 수준 설정이 적용됩니다.  모든 기본 버킷 설정은 무시됩니다.
** 개체에 대한 보존 설정이 지정되지 않은 경우 기본 버킷 설정이 적용됩니다(있는 경우).
** 객체 또는 버킷에 대한 보존 설정이 지정되지 않으면 해당 객체는 S3 객체 잠금으로 보호되지 않습니다.


+
보존 설정이 적용되면 개체와 S3 사용자 정의 메타데이터가 모두 보호됩니다.

. *객체 보존 및 삭제*
+
StorageGRID 는 각 보호된 개체의 여러 사본을 지정된 보존 기간 동안 저장합니다.  개체 복사본의 정확한 수와 유형, 저장 위치는 활성 ILM 정책의 규정에 따라 결정됩니다.  보호된 객체를 보관 기한에 도달하기 전에 삭제할 수 있는지 여부는 해당 보관 모드에 따라 달라집니다.

+
** 객체가 법적 보존 상태에 있는 경우, 보존 모드에 관계없이 누구도 객체를 삭제할 수 없습니다.




.관련 정보
* link:../tenant/creating-s3-bucket.html["S3 버킷 생성"]
* link:../tenant/update-default-retention-settings.html["S3 객체 잠금 기본 보존 기간 업데이트"]
* link:../s3/use-s3-api-for-s3-object-lock.html["S3 REST API를 사용하여 S3 객체 잠금을 구성합니다."]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html["예 7: S3 개체 잠금에 대한 규정 준수 ILM 정책"]

