---
permalink: ilm/troubleshooting-cloud-storage-pools.html 
sidebar: sidebar 
keywords: cloud storage pool, troubleshoot 
summary: 클라우드 스토리지 풀을 만들거나, 편집하거나, 삭제할 때 발생할 수 있는 오류를 해결하려면 다음 문제 해결 단계를 활용하세요. 
---
= 클라우드 스토리지 풀 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클라우드 스토리지 풀을 만들거나, 편집하거나, 삭제할 때 발생할 수 있는 오류를 해결하려면 다음 문제 해결 단계를 활용하세요.



== 오류가 발생했는지 확인하세요

StorageGRID 알려진 객체를 읽어 모든 Cloud Storage 풀에 대한 간단한 상태 점검을 수행합니다. `x-ntap-sgws-cloud-pool-uuid` 클라우드 스토리지 풀에 액세스할 수 있고 올바르게 작동하는지 확인합니다.  StorageGRID 엔드포인트에서 오류를 발견하면 각 스토리지 노드에서 1분마다 상태 검사를 수행합니다.  오류가 해결되면 상태 검사가 중지됩니다.  상태 검사에서 문제가 감지되면 스토리지 풀 페이지의 클라우드 스토리지 풀 표에 있는 마지막 오류 열에 메시지가 표시됩니다.

이 표는 각 클라우드 스토리지 풀에서 가장 최근에 감지된 오류를 보여주고 오류가 발생한 지 얼마나 되었는지 나타냅니다.

또한, 상태 점검에서 지난 5분 동안 하나 이상의 새로운 Cloud Storage Pool 오류가 발생한 것을 감지하면 *Cloud Storage Pool 연결 오류* 경고가 트리거됩니다.  이 경고에 대한 이메일 알림을 받은 경우 스토리지 풀 페이지로 이동하여(ILM > 스토리지 풀 선택) 마지막 오류 열의 오류 메시지를 검토하고 아래의 문제 해결 지침을 참조하세요.



== 오류가 해결되었는지 확인하세요

기본 문제를 해결한 후 오류가 해결되었는지 확인할 수 있습니다.  클라우드 스토리지 풀 페이지에서 엔드포인트를 선택하고 *오류 지우기*를 선택합니다.  확인 메시지는 StorageGRID Cloud Storage Pool에 대한 오류를 지웠음을 나타냅니다.

기본 문제가 해결된 경우 오류 메시지는 더 이상 표시되지 않습니다.  그러나 기본 문제가 해결되지 않은 경우(또는 다른 오류가 발생한 경우) 몇 분 이내에 마지막 오류 열에 오류 메시지가 표시됩니다.



== 오류: 상태 검사에 실패했습니다.  엔드포인트에서 오류 발생

Cloud Storage Pool에 대해 Amazon S3 버킷을 사용하기 시작한 후 해당 버킷에 대한 기본 보존 기간으로 S3 개체 잠금을 활성화하면 이 오류가 발생할 수 있습니다.  이 오류는 PUT 작업에 다음과 같은 페이로드 체크섬 값이 포함된 HTTP 헤더가 없는 경우 발생합니다. `Content-MD5` .  이 헤더 값은 S3 객체 잠금이 활성화된 버킷에 대한 PUT 작업을 위해 AWS에 필요합니다.

이 문제를 해결하려면 다음 단계를 따르세요.link:editing-cloud-storage-pool.html["클라우드 스토리지 풀 편집"] 아무런 변화도 없이.  이 작업은 Cloud Storage Pool 엔드포인트 구성에서 S3 객체 잠금 플래그를 자동으로 감지하고 업데이트하는 Cloud Storage Pool 구성의 유효성 검사를 트리거합니다.



== 오류: 이 클라우드 스토리지 풀에 예기치 않은 콘텐츠가 포함되어 있습니다.

클라우드 스토리지 풀을 생성, 편집 또는 삭제하려고 할 때 이 오류가 발생할 수 있습니다.  이 오류는 버킷이나 컨테이너에 다음이 포함된 경우 발생합니다. `x-ntap-sgws-cloud-pool-uuid` 마커 파일이 있지만 해당 파일에는 예상 UUID가 포함된 메타데이터 필드가 없습니다.

일반적으로 이 오류는 새로운 클라우드 스토리지 풀을 생성하고 다른 StorageGRID 인스턴스가 이미 동일한 클라우드 스토리지 풀을 사용 중인 경우에만 표시됩니다.

문제를 해결하려면 다음 단계 중 하나를 시도해 보세요.

* 새 클라우드 스토리지 풀을 구성하고 버킷에 다음이 포함된 경우 `x-ntap-sgws-cloud-pool-uuid` 다음 예제와 비슷한 파일 및 추가 개체 키를 사용하여 새 버킷을 만들고 대신 이 새 버킷을 사용합니다.
+
추가 객체 키의 예: `my-bucket.3E64CF2C-B74D-4B7D-AFE7-AD28BC18B2F6.1727326606730410`

* 만약 `x-ntap-sgws-cloud-pool-uuid` 파일이 버킷의 유일한 객체인 경우 이 파일을 삭제하세요.


이러한 단계가 귀하의 시나리오에 적용되지 않으면 지원팀에 문의하세요.



== 오류: Cloud Storage Pool을 생성하거나 업데이트할 수 없습니다.  엔드포인트에서 오류 발생

다음과 같은 상황에서 이 오류가 발생할 수 있습니다.

* 클라우드 스토리지 풀을 생성하거나 편집하려고 할 때.
* 새로운 클라우드 스토리지 풀을 구성하는 동안 S3 객체 잠금과 함께 지원되지 않는 플랫폼, 인증 또는 프로토콜 조합을 선택하는 경우. 보다 link:../ilm/considerations-for-cloud-storage-pools.html["클라우드 스토리지 풀에 대한 고려 사항"] .


이 오류는 연결 또는 구성 문제로 인해 StorageGRID Cloud Storage Pool에 쓸 수 없음을 나타냅니다.

문제를 해결하려면 엔드포인트에서 오류 메시지를 검토하세요.

* 오류 메시지에 다음이 포함되어 있는 경우 `Get _url_: EOF` HTTPS가 필요한 컨테이너나 버킷에 대해 Cloud Storage Pool에 사용된 서비스 엔드포인트가 HTTP를 사용하지 않는지 확인하세요.
* 오류 메시지에 다음이 포함되어 있는 경우 `Get _url_: net/http: request canceled while waiting for connection` 네트워크 구성에서 스토리지 노드가 클라우드 스토리지 풀에 사용되는 서비스 엔드포인트에 액세스할 수 있는지 확인하세요.
* 오류가 지원되지 않는 플랫폼, 인증 또는 프로토콜로 인해 발생한 경우 S3 개체 잠금을 사용하여 지원되는 구성으로 변경하고 새 클라우드 스토리지 풀을 다시 저장해 보세요.
* 다른 모든 엔드포인트 오류 메시지의 경우 다음 중 하나 이상을 시도해 보세요.
+
** Cloud Storage Pool에 입력한 것과 동일한 이름으로 외부 컨테이너나 버킷을 만들고, 새로운 Cloud Storage Pool을 다시 저장해 보세요.
** Cloud Storage Pool에 지정한 컨테이너 또는 버킷 이름을 수정하고 새 Cloud Storage Pool을 다시 저장해 보세요.






== 오류: CA 인증서 구문 분석에 실패했습니다.

클라우드 스토리지 풀을 만들거나 편집하려고 할 때 이 오류가 발생할 수 있습니다.  이 오류는 Cloud Storage Pool을 구성할 때 입력한 인증서를 StorageGRID 구문 분석할 수 없는 경우 발생합니다.

문제를 해결하려면 제공한 CA 인증서에서 문제가 있는지 확인하세요.



== 오류: 이 ID를 가진 클라우드 스토리지 풀을 찾을 수 없습니다.

클라우드 스토리지 풀을 편집하거나 삭제하려고 할 때 이 오류가 발생할 수 있습니다.  이 오류는 엔드포인트가 404 응답을 반환하는 경우 발생하며, 이는 다음 중 하나를 의미할 수 있습니다.

* Cloud Storage Pool에 사용된 자격 증명에는 버킷에 대한 읽기 권한이 없습니다.
* Cloud Storage Pool에 사용된 버킷에는 다음이 포함되지 않습니다. `x-ntap-sgws-cloud-pool-uuid` 마커 파일.


문제를 해결하려면 다음 단계 중 하나 이상을 시도하세요.

* 구성된 액세스 키와 연결된 사용자에게 필요한 권한이 있는지 확인하세요.
* 필요한 권한이 있는 자격 증명을 사용하여 클라우드 스토리지 풀을 편집합니다.
* 권한이 올바르면 지원팀에 문의하세요.




== 오류: 클라우드 스토리지 풀의 내용을 확인할 수 없습니다.  엔드포인트에서 오류 발생

클라우드 스토리지 풀을 삭제하려고 하면 이 오류가 발생할 수 있습니다.  이 오류는 어떤 종류의 연결 또는 구성 문제로 인해 StorageGRID Cloud Storage Pool 버킷의 내용을 읽지 못하고 있음을 나타냅니다.

문제를 해결하려면 엔드포인트에서 오류 메시지를 검토하세요.



== 오류: 이 버킷에 이미 개체가 배치되었습니다.

클라우드 스토리지 풀을 삭제하려고 하면 이 오류가 발생할 수 있습니다.  ILM에서 해당 풀로 이동한 데이터, Cloud Storage 풀을 구성하기 전에 버킷에 있던 데이터 또는 Cloud Storage 풀이 생성된 후 다른 소스에서 버킷에 넣은 데이터가 포함된 경우 Cloud Storage 풀을 삭제할 수 없습니다.

문제를 해결하려면 다음 단계 중 하나 이상을 시도하세요.

* "클라우드 스토리지 풀 객체의 수명 주기"에서 객체를 StorageGRID 로 다시 이동하는 방법에 대한 지침을 따르세요.
* ILM이 나머지 객체가 클라우드 스토리지 풀에 배치되지 않은 것이 확실하다면 버킷에서 해당 객체를 수동으로 삭제하세요.
+

NOTE: ILM에 의해 클라우드 스토리지 풀에 배치된 객체를 수동으로 삭제하지 마세요.  나중에 StorageGRID 에서 수동으로 삭제한 개체에 액세스하려고 하면 삭제된 개체를 찾을 수 없습니다.





== 오류: 프록시가 Cloud Storage Pool에 접근하는 동안 외부 오류가 발생했습니다.

클라우드 스토리지 풀에 사용되는 외부 S3 엔드포인트와 스토리지 노드 간에 투명하지 않은 스토리지 프록시를 구성한 경우 이 오류가 발생할 수 있습니다.  이 오류는 외부 프록시 서버가 Cloud Storage Pool 엔드포인트에 도달할 수 없는 경우 발생합니다.  예를 들어, DNS 서버가 호스트 이름을 확인하지 못할 수도 있고 외부 네트워킹 문제가 있을 수도 있습니다.

문제를 해결하려면 다음 단계 중 하나 이상을 시도하세요.

* 클라우드 스토리지 풀(*ILM* > *스토리지 풀*)의 설정을 확인하세요.
* 스토리지 프록시 서버의 네트워크 구성을 확인하세요.




== 오류: X.509 인증서의 유효 기간이 지났습니다.

클라우드 스토리지 풀을 삭제하려고 하면 이 오류가 발생할 수 있습니다.  이 오류는 올바른 외부 클라우드 스토리지 풀의 유효성을 검사하기 위해 인증에 X.509 인증서가 필요하고 클라우드 스토리지 풀 구성이 삭제되기 전에 외부 풀이 비어 있는 경우 발생합니다.

문제를 해결하려면 다음 단계를 시도해 보세요.

* Cloud Storage Pool에 대한 인증을 위해 구성된 인증서를 업데이트합니다.
* 이 클라우드 스토리지 풀의 인증서 만료 경고가 해결되었는지 확인하세요.


.관련 정보
link:lifecycle-of-cloud-storage-pool-object.html["Cloud Storage Pool 객체의 수명 주기"]
