---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: ILM 규칙에서 마지막 액세스 시간을 참조 시간으로 사용할 수 있습니다.  예를 들어, 지난 3개월 동안 본 객체는 로컬 스토리지 노드에 남겨두고, 최근에 본 적이 없는 객체는 오프사이트 위치로 이동할 수 있습니다.  특정 날짜에 마지막으로 액세스된 개체에만 ILM 규칙을 적용하려면 마지막 액세스 시간을 고급 필터로 사용할 수도 있습니다. 
---
= ILM 규칙에서 마지막 액세스 시간 사용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ILM 규칙에서 마지막 액세스 시간을 참조 시간으로 사용할 수 있습니다.  예를 들어, 지난 3개월 동안 본 객체는 로컬 스토리지 노드에 남겨두고, 최근에 본 적이 없는 객체는 오프사이트 위치로 이동할 수 있습니다.  특정 날짜에 마지막으로 액세스된 개체에만 ILM 규칙을 적용하려면 마지막 액세스 시간을 고급 필터로 사용할 수도 있습니다.

.이 작업에 관하여
ILM 규칙에서 마지막 액세스 시간을 사용하기 전에 다음 사항을 고려하세요.

* 마지막 액세스 시간을 기준 시간으로 사용하는 경우, 객체의 마지막 액세스 시간을 변경해도 ILM 평가가 즉시 실행되지 않는다는 점에 유의하세요.  대신, 객체의 위치가 평가되고 배경 ILM이 객체를 평가할 때 필요에 따라 객체가 이동합니다.  해당 객체에 접근한 후 2주 이상 걸릴 수 있습니다.
+
마지막 액세스 시간을 기준으로 ILM 규칙을 만들 때 이러한 지연 시간을 고려하고 짧은 기간(1개월 미만)을 사용하는 배치는 피하세요.

* 마지막 액세스 시간을 고급 필터나 참조 시간으로 사용하는 경우 S3 버킷에 대한 마지막 액세스 시간 업데이트를 활성화해야 합니다.  당신은 사용할 수 있습니다link:../tenant/enabling-or-disabling-last-access-time-updates.html["세입자 관리자"] 또는link:../s3/put-bucket-last-access-time-request.html["테넌트 관리 API"] .
+

NOTE: S3 버킷의 경우 마지막 액세스 시간 업데이트는 기본적으로 비활성화되어 있습니다.

+

NOTE: 마지막 액세스 시간 업데이트를 활성화하면 성능이 저하될 수 있다는 점을 알아두세요. 특히 작은 개체가 있는 시스템에서는 더욱 그렇습니다.  성능에 영향을 미치는 이유는 StorageGRID 객체를 검색할 때마다 객체를 새로운 타임스탬프로 업데이트해야 하기 때문입니다.



다음 표는 버킷의 모든 객체에 대해 다양한 유형의 요청에 대한 마지막 액세스 시간이 업데이트되는지 여부를 요약한 것입니다.

[cols="1a,1a,1a"]
|===
| 요청 유형 | 마지막 액세스 시간 업데이트가 비활성화된 경우 마지막 액세스 시간이 업데이트되는지 여부 | 마지막 액세스 시간 업데이트가 활성화된 경우 마지막 액세스 시간이 업데이트되는지 여부 


 a| 
객체, 해당 액세스 제어 목록 또는 해당 메타데이터를 검색하라는 요청
 a| 
아니요
 a| 
예



 a| 
객체의 메타데이터 업데이트 요청
 a| 
예
 a| 
예



 a| 
한 버킷에서 다른 버킷으로 객체를 복사하라는 요청
 a| 
* 아니요, 원본 사본의 경우
* 네, 대상 사본의 경우

 a| 
* 네, 원본 사본의 경우
* 네, 대상 사본의 경우




 a| 
멀티파트 업로드 완료 요청
 a| 
네, 조립된 객체의 경우
 a| 
네, 조립된 객체의 경우

|===