---
permalink: ilm/viewing-storage-pool-details.html 
sidebar: sidebar 
keywords: storage pool, view details 
summary: 스토리지 풀의 세부 정보를 확인하여 스토리지 풀이 어디에 사용되는지, 어떤 노드와 스토리지 등급이 포함되어 있는지 확인할 수 있습니다. 
---
= 스토리지 풀 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 풀의 세부 정보를 확인하여 스토리지 풀이 어디에 사용되는지, 어떤 노드와 스토리지 등급이 포함되어 있는지 확인할 수 있습니다.

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["특정 액세스 권한"] .


.단계
. *ILM* > *스토리지 풀*을 선택합니다.
+
스토리지 풀 테이블에는 스토리지 노드를 포함하는 각 스토리지 풀에 대한 다음 정보가 포함되어 있습니다.

+
** *이름*: 스토리지 풀의 고유한 표시 이름입니다.
** *노드 수*: 스토리지 풀에 있는 노드 수입니다.
** *저장소 사용량*: 이 노드의 개체 데이터에 사용된 총 사용 가능 공간의 백분율입니다.  이 값에는 개체 메타데이터가 포함되지 않습니다.
** *총 용량*: 스토리지 풀의 크기로, 스토리지 풀에 있는 모든 노드의 개체 데이터에 사용 가능한 총 공간 양과 같습니다.
** *ILM 사용량*: 스토리지 풀이 현재 어떻게 사용되고 있는지.  스토리지 풀은 사용되지 않을 수도 있고, 하나 이상의 ILM 규칙, 삭제 코딩 프로필 또는 둘 다에 사용될 수도 있습니다.


. 특정 스토리지 풀에 대한 세부 정보를 보려면 해당 이름을 선택하세요.
+
스토리지 풀의 세부 정보 페이지가 나타납니다.

. 스토리지 풀에 포함된 스토리지 노드에 대해 알아보려면 *노드* 탭을 확인하세요.
+
표에는 각 노드에 대한 다음 정보가 포함되어 있습니다.

+
** 노드 이름
** 사이트 이름
** 저장 등급
** 저장소 사용량: 저장소 노드에 사용된 개체 데이터의 총 사용 가능 공간의 백분율입니다.
+

NOTE: 동일한 저장소 사용량(%) 값은 각 저장소 노드의 저장소 사용 - 개체 데이터 차트에도 표시됩니다(노드 > 저장소 노드 > 저장소 선택).



. *ILM 사용량* 탭을 확인하여 스토리지 풀이 현재 ILM 규칙이나 삭제 코딩 프로필에서 사용되고 있는지 확인합니다.
. 선택적으로 *ILM 규칙 페이지*로 이동하여 스토리지 풀을 사용하는 모든 규칙에 대해 알아보고 관리할 수 있습니다.
+
를 참조하십시오link:working-with-ilm-rules-and-ilm-policies.html["ILM 규칙 작업에 대한 지침"] .


