---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: 클라우드 스토리지 풀을 사용하면 ILM을 사용하여 개체 데이터를 StorageGRID 시스템 외부로 이동할 수 있습니다.  예를 들어, 자주 액세스하지 않는 객체를 Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud 또는 Microsoft Azure Blob 스토리지의 Archive 액세스 계층과 같이 비용이 저렴한 클라우드 스토리지로 이동할 수 있습니다.  또는 재해 복구를 강화하기 위해 StorageGRID 객체의 클라우드 백업을 유지하려고 할 수도 있습니다. 
---
= 클라우드 스토리지 풀이란 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클라우드 스토리지 풀을 사용하면 ILM을 사용하여 개체 데이터를 StorageGRID 시스템 외부로 이동할 수 있습니다.  예를 들어, 자주 액세스하지 않는 객체를 Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud 또는 Microsoft Azure Blob 스토리지의 Archive 액세스 계층과 같이 비용이 저렴한 클라우드 스토리지로 이동할 수 있습니다.  또는 재해 복구를 강화하기 위해 StorageGRID 객체의 클라우드 백업을 유지하려고 할 수도 있습니다.

ILM 관점에서 볼 때 클라우드 스토리지 풀은 스토리지 풀과 유사합니다.  두 위치 중 하나에 객체를 저장하려면 ILM 규칙에 대한 배치 지침을 만들 때 풀을 선택합니다.  그러나 스토리지 풀이 StorageGRID 시스템 내의 스토리지 노드로 구성되는 반면, 클라우드 스토리지 풀은 외부 버킷(S3) 또는 컨테이너(Azure Blob 스토리지)로 구성됩니다.

이 표에서는 스토리지 풀과 클라우드 스토리지 풀을 비교하고 주요 유사점과 차이점을 보여줍니다.

[cols="1a,2a,5a"]
|===
|  | 저장 풀 | 클라우드 스토리지 풀 


 a| 
어떻게 만들어지나요?
 a| 
Grid Manager에서 *ILM* > *스토리지 풀* 옵션을 사용합니다.
 a| 
Grid Manager에서 *ILM* > *스토리지 풀* > *클라우드 스토리지 풀* 옵션을 사용합니다.

클라우드 스토리지 풀을 생성하려면 먼저 외부 버킷이나 컨테이너를 설정해야 합니다.



 a| 
풀은 몇 개나 만들 수 있나요?
 a| 
제한 없는.
 a| 
최대 10개.



 a| 
물건은 어디에 저장되나요?
 a| 
StorageGRID 내의 하나 이상의 스토리지 노드에서.
 a| 
StorageGRID 시스템 외부의 Amazon S3 버킷, Azure Blob 스토리지 컨테이너 또는 Google Cloud에 있습니다.

클라우드 스토리지 풀이 Amazon S3 버킷인 경우:

* 선택적으로 버킷 수명 주기를 구성하여 객체를 Amazon S3 Glacier 또는 S3 Glacier Deep Archive와 같은 저비용 장기 저장소로 전환할 수 있습니다.  외부 스토리지 시스템은 Glacier 스토리지 클래스와 S3 RestoreObject API를 지원해야 합니다.
* AWS Secret Region을 지원하는 AWS Commercial Cloud Services(C2S)와 함께 사용할 클라우드 스토리지 풀을 생성할 수 있습니다.


Cloud Storage Pool이 Azure Blob 스토리지 컨테이너인 경우 StorageGRID 해당 개체를 Archive 계층으로 전환합니다.

*참고:* 일반적으로 Cloud Storage Pool에 사용되는 컨테이너에 대해 Azure Blob 저장소 수명 주기 관리를 구성하지 마세요.  Cloud Storage 풀의 객체에 대한 RestoreObject 작업은 구성된 수명 주기의 영향을 받을 수 있습니다.



 a| 
객체의 배치를 제어하는 것은 무엇입니까?
 a| 
활성 ILM 정책의 ILM 규칙입니다.
 a| 
활성 ILM 정책의 ILM 규칙입니다.



 a| 
어떤 데이터 보호 방법을 사용합니까?
 a| 
복제 또는 삭제 코딩.
 a| 
복제.



 a| 
각 객체의 사본은 몇 개까지 허용되나요?
 a| 
다수의.
 a| 
Cloud Storage Pool에 사본 1개, 선택적으로 StorageGRID 에 사본 1개 이상.

*참고:* 한 번에 두 개 이상의 Cloud Storage 풀에 객체를 저장할 수 없습니다.



 a| 
장점은 무엇인가요?
 a| 
언제든지 객체에 빠르게 접근할 수 있습니다.
 a| 
저렴한 보관 비용.

*참고*: FabricPool 데이터는 Cloud Storage Pool에 계층화할 수 없습니다.

|===