---
permalink: ilm/what-erasure-coding-schemes-are.html 
sidebar: sidebar 
keywords: erasure-coding scheme 
summary: 삭제 코딩 방식은 각 객체에 대해 생성되는 데이터 조각 수와 패리티 조각 수를 제어합니다. 
---
= 삭제 코딩 방식이란 무엇인가요?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
삭제 코딩 방식은 각 객체에 대해 생성되는 데이터 조각 수와 패리티 조각 수를 제어합니다.

ILM 규칙을 만들거나 편집할 때 사용 가능한 삭제 코딩 방식을 선택합니다.  StorageGRID 사용하려는 스토리지 풀을 구성하는 스토리지 노드와 사이트 수에 따라 자동으로 삭제 코딩 체계를 생성합니다.



== 데이터 보호

StorageGRID 시스템은 Reed-Solomon 삭제 코딩 알고리즘을 사용합니다.  알고리즘은 객체를 다음과 같이 분할합니다. `k` 데이터 조각 및 계산 `m` 패리티 조각.

그만큼 `k + m = n` 조각들이 퍼져있다 `n` 데이터 보호를 제공하는 저장 노드는 다음과 같습니다.

* 물건을 회수하거나 수리하려면 `k` 조각들이 필요합니다.
* 물체는 최대까지 지속될 수 있습니다 `m` 분실되거나 손상된 조각.  가치가 높을수록 `m` , 실패 허용도가 높아집니다.


최상의 데이터 보호는 스토리지 풀 내에서 가장 높은 노드 또는 볼륨 장애 허용 범위를 갖춘 삭제 코딩 방식을 통해 제공됩니다.



== 저장 오버헤드

삭제 코딩 방식의 저장 오버헤드는 패리티 조각의 수를 나누어 계산됩니다.(`m` ) 데이터 조각의 수에 따라(`k` ).  저장소 오버헤드를 사용하여 각 삭제 코드화된 개체에 필요한 디스크 공간을 계산할 수 있습니다.

`_disk space_ = _object size_ + (_object size_ * _storage overhead_)`

예를 들어, 4+2 방식(저장소 오버헤드가 50%)을 사용하여 10MB 객체를 저장하는 경우, 객체는 15MB의 그리드 저장소를 사용합니다.  동일한 10MB 객체를 6+2 방식(저장소 오버헤드가 33%)을 사용하여 저장하면 객체는 약 13.3MB를 소모합니다.

가장 낮은 총 값을 갖는 삭제 코딩 방식을 선택하십시오. `k+m` 귀하의 요구 사항을 충족합니다.  조각 수가 적은 삭제 코딩 방식은 다음과 같은 이유로 계산 효율성이 더 높습니다.

* 개체당 생성 및 배포(또는 검색)되는 조각이 줄어듭니다.
* 조각 크기가 더 크기 때문에 더 나은 성능을 보입니다.
* 추가해야 할 노드 수가 더 적을 수 있습니다.link:../expand/index.html["더 많은 저장 공간이 필요할 때 확장"]




== 저장 풀에 대한 지침

삭제 코드화된 복사본을 생성하는 규칙에 사용할 스토리지 풀을 선택할 때 스토리지 풀에 대한 다음 지침을 따르세요.

* 스토리지 풀에는 3개 이상의 사이트가 포함되어야 하며, 정확히 1개의 사이트만 포함되어야 합니다.
+

NOTE: 스토리지 풀에 두 개의 사이트가 포함된 경우 삭제 코딩을 사용할 수 없습니다.

+
** <<3개 이상의 사이트를 포함하는 스토리지 풀에 대한 삭제 코딩 방식,3개 이상의 사이트를 포함하는 스토리지 풀에 대한 삭제 코딩 방식>>
** <<단일 사이트 스토리지 풀을 위한 삭제 코딩 방식,단일 사이트 스토리지 풀을 위한 삭제 코딩 방식>>


* 모든 사이트 사이트를 포함하는 스토리지 풀을 사용하지 마세요.
* 저장 풀에는 최소한 다음이 포함되어야 합니다. `_k+m_ +1` 객체 데이터를 저장할 수 있는 저장 노드.
+

NOTE: 저장 노드는 설치 중에 개체 데이터가 아닌 개체 메타데이터만 포함하도록 구성할 수 있습니다. 자세한 내용은 다음을 참조하세요. link:../primer/what-storage-node-is.html#types-of-storage-nodes["저장 노드 유형"] .

+
필요한 최소 저장 노드 수는 다음과 같습니다. `k+m` .  그러나 최소한 하나 이상의 추가 스토리지 노드가 있으면 필요한 스토리지 노드를 일시적으로 사용할 수 없는 경우 수집 실패나 ILM 백로그를 방지하는 데 도움이 될 수 있습니다.





== 3개 이상의 사이트를 포함하는 스토리지 풀에 대한 삭제 코딩 방식

다음 표에서는 3개 이상의 사이트를 포함하는 스토리지 풀에 대해 StorageGRID 가 현재 지원하는 삭제 코딩 체계를 설명합니다.  이러한 모든 제도는 부지 손실에 대한 보호 기능을 제공합니다.  한 사이트가 손실되더라도 해당 객체에 계속 접근할 수 있습니다.

사이트 손실 보호를 제공하는 삭제 코딩 방식의 경우 스토리지 풀의 권장 스토리지 노드 수가 다음을 초과합니다. `_k+m_ +1` 각 사이트에는 최소 3개의 스토리지 노드가 필요하기 때문입니다.

[cols="1a,1a,1a,1a,1a,1a"]
|===
| 삭제 코딩 방식 (_k+m_) | 배포된 사이트의 최소 수 | 각 사이트의 권장 스토리지 노드 수 | 권장되는 총 스토리지 노드 수 | 사이트 손실 보호? | 저장 오버헤드 


 a| 
4+2
 a| 
3
 a| 
3
 a| 
9
 a| 
예
 a| 
50%



 a| 
6+2
 a| 
4
 a| 
3
 a| 
12
 a| 
예
 a| 
33%



 a| 
8+2
 a| 
5
 a| 
3
 a| 
15
 a| 
예
 a| 
25%



 a| 
6+3
 a| 
3
 a| 
4
 a| 
12
 a| 
예
 a| 
50%



 a| 
9+3
 a| 
4
 a| 
4
 a| 
16
 a| 
예
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
3
 a| 
9
 a| 
예
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
3
 a| 
15
 a| 
예
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
3
 a| 
21
 a| 
예
 a| 
17%



 a| 
7+5
 a| 
3
 a| 
5
 a| 
15
 a| 
예
 a| 
71%

|===

NOTE: StorageGRID 사이트당 최소 3개의 스토리지 노드가 필요합니다.  7+5 방식을 사용하려면 각 사이트에 최소 4개의 스토리지 노드가 필요합니다.  사이트당 5개의 스토리지 노드를 사용하는 것이 좋습니다.

사이트 보호 기능을 제공하는 삭제 코딩 방식을 선택할 때 다음 요소의 상대적 중요성을 균형 있게 고려하세요.

* *조각 수*: 일반적으로 총 조각 수가 적을수록 성능과 확장 유연성이 더 좋습니다.
* *오류 허용*: 오류 허용은 더 많은 패리티 세그먼트를 갖는 경우 증가합니다(즉, `m` 더 높은 가치를 갖습니다.)
* *네트워크 트래픽*: 장애로부터 복구할 때 더 많은 조각(즉, 더 높은 총량)을 사용하는 방식을 사용합니다. `k+m` ) 네트워크 트래픽이 증가합니다.
* *저장 오버헤드*: 오버헤드가 높은 스키마는 객체당 더 많은 저장 공간이 필요합니다.


예를 들어, 4+2 방식과 6+3 방식(둘 다 50%의 저장 오버헤드가 있음) 중에서 선택할 때, 추가적인 장애 허용이 필요하다면 6+3 방식을 선택하세요.  네트워크 리소스가 제한된 경우 4+2 방식을 선택하세요.  다른 모든 요소가 동일하다면 총 조각 수가 더 적은 4+2를 선택합니다.


NOTE: 어떤 방식을 사용해야 할지 확실하지 않으면 4+2 또는 6+3을 선택하거나 기술 지원팀에 문의하세요.



== 단일 사이트 스토리지 풀을 위한 삭제 코딩 방식

단일 사이트 스토리지 풀은 해당 사이트에 충분한 스토리지 노드가 있는 경우 3개 이상의 사이트에 대해 정의된 모든 삭제 코딩 체계를 지원합니다.

필요한 최소 저장 노드 수는 다음과 같습니다. `k+m` , 하지만 저장 풀이 있습니다 `k+m +1` 저장 노드를 권장합니다.  예를 들어, 2+1 삭제 코딩 방식에는 최소 3개의 스토리지 노드가 있는 스토리지 풀이 필요하지만, 4개의 스토리지 노드가 권장됩니다.

[cols="1a,1a,1a,1a"]
|===
| 삭제 코딩 방식 (_k+m_) | 최소 스토리지 노드 수 | 권장되는 스토리지 노드 수 | 저장 오버헤드 


 a| 
4+2
 a| 
6
 a| 
7
 a| 
50%



 a| 
6+2
 a| 
8
 a| 
9
 a| 
33%



 a| 
8+2
 a| 
10
 a| 
11
 a| 
25%



 a| 
6+3
 a| 
9
 a| 
10
 a| 
50%



 a| 
9+3
 a| 
12
 a| 
13
 a| 
33%



 a| 
2+1
 a| 
3
 a| 
4
 a| 
50%



 a| 
4+1
 a| 
5
 a| 
6
 a| 
25%



 a| 
6+1
 a| 
7
 a| 
8
 a| 
17%



 a| 
7+5
 a| 
12
 a| 
13
 a| 
71%

|===