---
permalink: fabricpool/best-practices-for-load-balancing.html 
sidebar: sidebar 
keywords: fabricPool, load balancer endpoint, load balancing, Layer 7, best practices, certificate, CA, certificate authority, tls, ssl 
summary: StorageGRID FabricPool 클라우드 계층으로 연결하기 전에 FabricPool 과 함께 로드 밸런서를 사용하는 모범 사례를 검토하세요. 
---
= FabricPool 의 부하 분산을 위한 모범 사례
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID FabricPool 클라우드 계층으로 연결하기 전에 FabricPool 과 함께 로드 밸런서를 사용하는 모범 사례를 검토하세요.

StorageGRID 로드 밸런서 및 로드 밸런서 인증서에 대한 일반 정보를 알아보려면 다음을 참조하세요.link:../admin/managing-load-balancing.html["부하 분산을 위한 고려 사항"] .



== FabricPool 에 사용되는 로드 밸런서 엔드포인트에 대한 테넌트 액세스를 위한 모범 사례

어떤 테넌트가 특정 로드 밸런서 엔드포인트를 사용하여 버킷에 액세스할 수 있는지 제어할 수 있습니다.  모든 테넌트를 허용하거나, 일부 테넌트만 허용하거나, 일부 테넌트를 차단할 수 있습니다.  FabricPool 사용을 위한 부하 분산 엔드포인트를 생성할 때 *모든 테넌트 허용*을 선택합니다.  ONTAP StorageGRID 버킷에 저장된 데이터를 암호화하므로, 이 추가 보안 계층이 제공하는 보안 효과는 거의 없습니다.



== 보안 인증서에 대한 모범 사례

FabricPool 사용을 위해 StorageGRID 로드 밸런서 엔드포인트를 생성할 때 ONTAP StorageGRID 로 인증할 수 있도록 하는 보안 인증서를 제공합니다.

대부분의 경우 ONTAP 과 StorageGRID 간의 연결에는 TLS(전송 계층 보안) 암호화를 사용해야 합니다.  TLS 암호화 없이 FabricPool 사용하는 것은 지원되지만 권장하지는 않습니다.  StorageGRID 로드 밸런서 엔드포인트에 대한 네트워크 프로토콜을 선택할 때 *HTTPS*를 선택합니다.  그런 다음 ONTAP StorageGRID 인증할 수 있도록 보안 인증서를 제공합니다.

부하 분산 엔드포인트의 서버 인증서에 대해 자세히 알아보려면 다음을 참조하세요.

* link:../admin/using-storagegrid-security-certificates.html["보안 인증서 관리"]
* link:../admin/managing-load-balancing.html["부하 분산을 위한 고려 사항"]
* link:../harden/hardening-guideline-for-server-certificates.html["서버 인증서에 대한 강화 지침"]




=== ONTAP 에 인증서 추가

StorageGRID FabricPool 클라우드 계층으로 추가하는 경우 루트 및 모든 하위 인증 기관(CA) 인증서를 포함하여 ONTAP 클러스터에 동일한 인증서를 설치해야 합니다.



=== 인증서 만료 관리


CAUTION: ONTAP 과 StorageGRID 간 연결을 보호하는 데 사용된 인증서가 만료되면 FabricPool 일시적으로 작동을 멈추고 ONTAP StorageGRID 에 계층화된 데이터에 대한 액세스 권한을 일시적으로 잃게 됩니다.

인증서 만료 문제를 방지하려면 다음 모범 사례를 따르세요.

* *로드 밸런서 엔드포인트 인증서 만료* 및 *S3 API용 글로벌 서버 인증서 만료* 알림과 같이 인증서 만료 날짜가 다가옴을 경고하는 알림을 주의 깊게 모니터링하세요.
* 항상 StorageGRID 및 ONTAP 버전의 인증서를 동기화 상태로 유지하세요.  로드 밸런서 엔드포인트에 사용된 인증서를 교체하거나 갱신하는 경우 클라우드 계층에 대해 ONTAP 에서 사용하는 동등한 인증서도 교체하거나 갱신해야 합니다.
* 공개적으로 서명된 CA 인증서를 사용하세요.  CA에서 서명한 인증서를 사용하는 경우 Grid Management API를 사용하여 인증서 순환을 자동화할 수 있습니다.  이를 통해 곧 만료되는 인증서를 중단 없이 교체할 수 있습니다.
* 자체 서명된 StorageGRID 인증서를 생성했고 해당 인증서가 만료되려고 하는 경우, 기존 인증서가 만료되기 전에 StorageGRID 와 ONTAP 에서 모두 인증서를 수동으로 교체해야 합니다.  자체 서명된 인증서가 이미 만료된 경우 액세스 손실을 방지하기 위해 ONTAP 에서 인증서 유효성 검사를 끕니다.
+
보다 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_configure_a_new_StorageGRID_self-signed_server_certificate_on_an_existing_ONTAP_FabricPool_deployment["NetApp 기술 자료: 기존 ONTAP FabricPool 배포에서 새 StorageGRID 자체 서명 서버 인증서를 구성하는 방법"^] 지침을 보려면.


