---
permalink: fabricpool/creating-traffic-classification-policy-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, traffic classification, traffic policy, QoS, quality of service 
summary: 선택적으로 FabricPool 워크로드에 대한 서비스 품질을 최적화하기 위해 StorageGRID 트래픽 분류 정책을 설계할 수 있습니다. 
---
= FabricPool 에 대한 트래픽 분류 정책 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
선택적으로 FabricPool 워크로드에 대한 서비스 품질을 최적화하기 위해 StorageGRID 트래픽 분류 정책을 설계할 수 있습니다.

이 작업에 대한 자세한 내용은 다음을 참조하세요.link:../admin/managing-traffic-classification-policies.html["트래픽 분류 정책 관리"] .  FabricPool 설정 마법사를 사용하여 이 작업을 완료하려면 다음으로 이동하세요.link:use-fabricpool-setup-wizard-steps.html["FabricPool 설정 마법사에 액세스하여 완료합니다."] .

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["루트 액세스 권한"] .


.이 작업에 관하여
FabricPool 에 대한 트래픽 분류 정책을 만드는 모범 사례는 다음과 같이 작업 부하에 따라 달라집니다.

* FabricPool 기본 워크로드 데이터를 StorageGRID 에 계층화하려는 경우 FabricPool 워크로드에 대부분의 대역폭이 있는지 확인해야 합니다.  다른 모든 작업 부하를 제한하기 위해 트래픽 분류 정책을 만들 수 있습니다.
+

NOTE: 일반적으로 FabricPool 읽기 작업이 쓰기 작업보다 우선 순위를 정하는 것이 더 중요합니다.

+
예를 들어, 다른 S3 클라이언트가 이 StorageGRID 시스템을 사용하는 경우 트래픽 분류 정책을 만들어야 합니다.  다른 버킷, 테넌트, IP 서브넷 또는 로드 밸런서 엔드포인트에 대한 네트워크 트래픽을 제한할 수 있습니다.

* 일반적으로 FabricPool 워크로드에는 서비스 품질 제한을 부과해서는 안 됩니다. 다른 워크로드만 제한해야 합니다.
* 다른 작업 부하에 적용된 제한은 해당 작업 부하의 동작을 고려해야 합니다.  부과되는 제한은 그리드의 크기와 용량, 예상 활용도에 따라 달라집니다.


.단계
. *구성* > *네트워크* > *트래픽 분류*를 선택합니다.
. *만들기*를 선택하세요.
. 정책의 이름과 설명(선택 사항)을 입력하고 *계속*을 선택합니다.
. 일치하는 규칙 추가 단계에서는 최소한 하나의 규칙을 추가합니다.
+
.. *규칙 추가*를 선택하세요
.. 유형에서 *로드 밸런서 엔드포인트*를 선택하고 FabricPool 에 대해 생성한 로드 밸런서 엔드포인트를 선택합니다.
+
FabricPool 테넌트 계정이나 버킷을 선택할 수도 있습니다.

.. 이 트래픽 정책으로 다른 엔드포인트의 트래픽을 제한하려면 *역일치*를 선택하세요.


. 선택적으로, 규칙에 따라 일치하는 네트워크 트래픽을 제어하기 위해 하나 이상의 제한을 추가합니다.
+

NOTE: StorageGRID 제한을 두지 않아도 측정 항목을 수집하므로 트래픽 추세를 파악할 수 있습니다.

+
.. *제한 추가*를 선택하세요.
.. 제한하려는 트래픽 유형과 적용할 제한을 선택하세요.


. *계속*을 선택하세요.
. 트래픽 분류 정책을 읽고 검토하세요.  *이전* 버튼을 사용하여 뒤로 돌아가서 필요한 대로 변경하세요.  정책에 만족하면 *저장하고 계속*을 선택하세요.


.완료 후
link:../admin/viewing-network-traffic-metrics.html["네트워크 트래픽 메트릭 보기"]교통 제한이 예상대로 시행되고 있는지 확인하세요.
