---
permalink: fabricpool/creating-load-balancer-endpoint-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, create, creating, certificate 
summary: StorageGRID FabricPool 과 같은 클라이언트 애플리케이션의 작업 부하를 관리하기 위해 로드 밸런서를 사용합니다.  부하 분산은 여러 스토리지 노드에서 속도와 연결 용량을 극대화합니다. 
---
= FabricPool 에 대한 로드 밸런서 엔드포인트 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID FabricPool 과 같은 클라이언트 애플리케이션의 작업 부하를 관리하기 위해 로드 밸런서를 사용합니다.  부하 분산은 여러 스토리지 노드에서 속도와 연결 용량을 극대화합니다.

FabricPool 과 함께 사용하도록 StorageGRID 구성하는 경우 로드 밸런서 엔드포인트를 구성하고 ONTAP 과 StorageGRID 간의 연결을 보호하는 데 사용되는 로드 밸런서 엔드포인트 인증서를 업로드하거나 생성해야 합니다.

FabricPool 설정 마법사를 사용하여 이 작업을 완료하려면 다음으로 이동하세요.link:use-fabricpool-setup-wizard-steps.html["FabricPool 설정 마법사에 액세스하여 완료합니다."] .

.시작하기 전에
* 다음을 사용하여 Grid Manager에 로그인했습니다.link:../admin/web-browser-requirements.html["지원되는 웹 브라우저"] .
* 당신은 가지고있다link:../admin/admin-group-permissions.html["루트 액세스 권한"] .
* 당신은 일반을 검토했습니다link:../admin/managing-load-balancing.html["부하 분산을 위한 고려 사항"] 뿐만 아니라link:best-practices-for-load-balancing.html["FabricPool 의 부하 분산을 위한 모범 사례"] .


.단계
. *구성* > *네트워크* > *로드 밸런서 엔드포인트*를 선택합니다.
. *만들기*를 선택하세요.
. *종료지 세부정보 입력* 단계에서는 다음 필드를 완료하세요.
+
[cols="1a,2a"]
|===
| 필드 | 설명 


 a| 
이름
 a| 
엔드포인트에 대한 설명적 이름입니다.



 a| 
포트
 a| 
부하 분산에 사용하려는 StorageGRID 포트입니다.  이 필드는 처음 만든 엔드포인트의 경우 기본적으로 10433으로 설정되지만, 사용하지 않는 외부 포트는 입력할 수 있습니다.  80 또는 443을 입력하면 엔드포인트는 게이트웨이 노드에만 구성됩니다.  이러한 포트는 관리 노드에서 예약되어 있습니다.

*참고:* 다른 그리드 서비스에서 사용하는 포트는 허용되지 않습니다. 를 참조하십시오link:../network/internal-grid-node-communications.html["네트워크 포트 참조"] .

StorageGRID FabricPool 클라우드 계층으로 연결할 때 ONTAP 에 이 번호를 제공합니다.



 a| 
클라이언트 유형
 a| 
*S3*를 선택하세요.



 a| 
네트워크 프로토콜
 a| 
*HTTPS*를 선택하세요.

*참고*: TLS 암호화 없이 StorageGRID 와 통신하는 것은 지원되지만 권장하지는 않습니다.

|===
. *바인딩 모드 선택* 단계에서는 바인딩 모드를 지정합니다.  바인딩 모드는 모든 IP 주소를 사용하거나 특정 IP 주소와 네트워크 인터페이스를 사용하여 엔드포인트에 액세스하는 방법을 제어합니다.
+
[cols="1a,3a"]
|===
| 방법 | 설명 


 a| 
글로벌(기본값)
 a| 
클라이언트는 게이트웨이 노드나 관리 노드의 IP 주소, 모든 네트워크의 HA 그룹의 가상 IP(VIP) 주소 또는 해당 FQDN을 사용하여 엔드포인트에 액세스할 수 있습니다.

이 엔드포인트의 접근성을 제한할 필요가 없는 한 *전역* 설정(기본값)을 사용하세요.



 a| 
HA 그룹의 가상 IP
 a| 
클라이언트는 이 엔드포인트에 액세스하려면 HA 그룹의 가상 IP 주소(또는 해당 FQDN)를 사용해야 합니다.

이 바인딩 모드를 사용하는 엔드포인트는 모두 동일한 포트 번호를 사용할 수 있습니다. 단, 엔드포인트에 대해 선택한 HA 그룹이 겹치지 않아야 합니다.



 a| 
노드 인터페이스
 a| 
클라이언트는 이 엔드포인트에 액세스하려면 선택한 노드 인터페이스의 IP 주소(또는 해당 FQDN)를 사용해야 합니다.



 a| 
노드 유형
 a| 
선택한 노드 유형에 따라 클라이언트는 이 엔드포인트에 액세스하기 위해 모든 관리 노드의 IP 주소(또는 해당 FQDN) 또는 모든 게이트웨이 노드의 IP 주소(또는 해당 FQDN)를 사용해야 합니다.

|===
. *세입자 접근* 단계에서 다음 중 하나를 선택하세요.
+
[cols="1a,2a"]
|===
| 필드 | 설명 


 a| 
모든 테넌트 허용(기본값)
 a| 
모든 테넌트 계정은 이 엔드포인트를 사용하여 버킷에 액세스할 수 있습니다.

*모든 테넌트 허용*은 FabricPool 에 사용되는 로드 밸런서 엔드포인트에 거의 항상 적합한 옵션입니다.

아직 테넌트 계정을 생성하지 않은 경우 이 옵션을 선택해야 합니다.



 a| 
선택된 세입자 허용
 a| 
선택된 테넌트 계정만 이 엔드포인트를 사용하여 버킷에 액세스할 수 있습니다.



 a| 
선택한 세입자 차단
 a| 
선택된 테넌트 계정은 이 엔드포인트를 사용하여 버킷에 액세스할 수 없습니다.  다른 모든 테넌트는 이 엔드포인트를 사용할 수 있습니다.

|===
. *인증서 첨부* 단계에서 다음 중 하나를 선택하세요.
+
[cols="1a,2a"]
|===
| 필드 | 설명 


 a| 
인증서 업로드(권장)
 a| 
이 옵션을 사용하면 CA 서명 서버 인증서, 인증서 개인 키 및 선택적 CA 번들을 업로드할 수 있습니다.



 a| 
인증서 생성
 a| 
이 옵션을 사용하면 자체 서명된 인증서를 생성할 수 있습니다.  보다link:../admin/configuring-load-balancer-endpoints.html["로드 밸런서 엔드포인트 구성"] 입력해야 할 내용에 대한 자세한 내용은 다음을 참조하세요.



 a| 
StorageGRID S3 인증서 사용
 a| 
이 옵션은 StorageGRID 글로벌 인증서의 사용자 지정 버전을 이미 업로드하거나 생성한 경우에만 사용할 수 있습니다. 보다link:../admin/configuring-custom-server-certificate-for-storage-node.html["S3 API 인증서 구성"] 자세한 내용은.

|===
. *만들기*를 선택하세요.



NOTE: 엔드포인트 인증서에 대한 변경 사항이 모든 노드에 적용되는 데 최대 15분이 걸릴 수 있습니다.
