---
permalink: fabricpool/use-fabricpool-setup-wizard.html 
sidebar: sidebar 
keywords: fabricPool, FabricPool setup wizard, ontap system manager 
summary: FabricPool 설정 마법사를 사용하여 StorageGRID FabricPool 클라우드 계층의 개체 스토리지 시스템으로 구성할 수 있습니다.  설치 마법사를 완료한 후 ONTAP 시스템 관리자에 필요한 세부 정보를 입력할 수 있습니다. 
---
= FabricPool 설정 마법사 사용: 고려 사항 및 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool 설정 마법사를 사용하여 StorageGRID FabricPool 클라우드 계층의 개체 스토리지 시스템으로 구성할 수 있습니다.  설치 마법사를 완료한 후 ONTAP 시스템 관리자에 필요한 세부 정보를 입력할 수 있습니다.



== FabricPool 설정 마법사를 사용하는 경우

FabricPool 설정 마법사는 FabricPool 과 함께 사용하도록 StorageGRID 구성하는 각 단계를 안내하고 ILM 및 트래픽 분류 정책과 같은 특정 엔터티를 자동으로 구성합니다.  마법사를 완료하는 과정의 일부로 ONTAP System Manager에 값을 입력하는 데 사용할 수 있는 파일을 다운로드합니다.  마법사를 사용하면 시스템을 더 빠르게 구성하고 설정이 StorageGRID 및 FabricPool 모범 사례를 준수하는지 확인할 수 있습니다.

루트 액세스 권한이 있다고 가정하면 StorageGRID Grid Manager를 사용할 때 FabricPool 설정 마법사를 완료할 수 있으며, 나중에 언제든지 마법사에 액세스하여 완료할 수 있습니다.  요구 사항에 따라 필수 항목 중 일부 또는 전부를 수동으로 구성한 다음 마법사를 사용하여 ONTAP 에 필요한 값을 단일 파일에 조립할 수도 있습니다.


TIP: 특별한 요구 사항이 있거나 구현에 상당한 사용자 정의가 필요한 경우가 아니면 FabricPool 설정 마법사를 사용하세요.



== 마법사를 사용하기 전에

이러한 필수 단계를 모두 완료했는지 확인하세요.



=== 모범 사례 검토

* 당신은에 대한 일반적인 이해를 가지고 있습니다link:information-needed-to-attach-storagegrid-as-cloud-tier.html["StorageGRID 클라우드 계층으로 연결하는 데 필요한 정보"] .
* 다음 항목에 대한 FabricPool 모범 사례를 검토했습니다.
+
** link:best-practices-for-high-availability-groups.html["고가용성(HA) 그룹"]
** link:best-practices-for-load-balancing.html["부하 분산"]
** link:best-practices-ilm.html["ILM 규칙 및 정책"]






=== IP 주소를 얻고 VLAN 인터페이스를 설정합니다.

HA 그룹을 구성하는 경우 ONTAP 연결할 노드와 사용할 StorageGRID 네트워크를 알 수 있습니다.  또한 서브넷 CIDR, 게이트웨이 IP 주소, 가상 IP(VIP) 주소에 어떤 값을 입력해야 하는지도 알고 있습니다.

FabricPool 트래픽을 분리하기 위해 가상 LAN을 사용하려는 경우 VLAN 인터페이스가 이미 구성되어 있습니다. 보다 link:../admin/configure-vlan-interfaces.html["VLAN 인터페이스 구성"] .



=== ID 페더레이션 및 SSO 구성

StorageGRID 시스템에 ID 페더레이션이나 SSO(Single Sign-On)를 사용하려는 경우 이러한 기능을 활성화해야 합니다. 또한 ONTAP 에서 사용할 테넌트 계정에 대해 루트 액세스 권한이 있는 페더레이션 그룹이 어떤지도 알고 있습니다. 보다link:../admin/using-identity-federation.html["ID 페더레이션 사용"] 그리고link:../admin/configuring-sso.html["단일 로그인 구성"] .



=== 도메인 이름 획득 및 구성

* StorageGRID 에 사용할 정규화된 도메인 이름(FQDN)을 알고 있습니다.  도메인 이름 서버(DNS) 항목은 마법사를 사용하여 만든 HA 그룹의 가상 IP(VIP) 주소에 이 FQDN을 매핑합니다. 보다 link:../fabricpool/configure-dns-server.html["DNS 서버 구성"] .
* S3 가상 호스팅 스타일 요청을 사용하려는 경우 다음이 필요합니다.link:../admin/configuring-s3-api-endpoint-domain-names.html["구성된 S3 엔드포인트 도메인 이름"] .  ONTAP 기본적으로 경로 스타일 URL을 사용하지만 가상 호스팅 스타일 요청을 사용하는 것이 좋습니다.




=== 로드 밸런서 및 보안 인증서 요구 사항 검토

StorageGRID 로드 밸런서를 사용하려는 경우 일반적인 내용을 검토해야 합니다.link:../admin/managing-load-balancing.html["부하 분산을 위한 고려 사항"] .  업로드할 인증서가 있거나 인증서를 생성하는 데 필요한 값이 있습니다.

외부(타사) 로드 밸런서 엔드포인트를 사용하려는 경우 해당 로드 밸런서에 대한 정규화된 도메인 이름(FQDN), 포트 및 인증서가 있어야 합니다.



=== ILM 스토리지 풀 구성 확인

처음에 StorageGRID 11.6 또는 이전 버전을 설치한 경우 사용할 스토리지 풀을 구성했습니다.  일반적으로 ONTAP 데이터를 저장하는 데 사용할 각 StorageGRID 사이트에 대해 스토리지 풀을 만들어야 합니다.


NOTE: 처음에 StorageGRID 11.7 또는 11.8을 설치한 경우에는 이 필수 조건이 적용되지 않습니다.  이러한 버전 중 하나를 처음 설치하면 각 사이트에 대한 스토리지 풀이 자동으로 생성됩니다.



== ONTAP 과 StorageGRID 클라우드 계층 간의 관계

FabricPool 마법사는 하나의 StorageGRID 테넌트, 하나의 액세스 키 세트, 하나의 StorageGRID 버킷을 포함하는 단일 StorageGRID 클라우드 계층을 만드는 과정을 안내합니다.  이 StorageGRID 클라우드 계층을 하나 이상의 ONTAP 로컬 계층에 연결할 수 있습니다.

클러스터의 여러 로컬 계층에 단일 클라우드 계층을 연결하는 것이 일반적으로 가장 좋은 방법입니다.  하지만 요구 사항에 따라 단일 클러스터의 로컬 계층에 대해 두 개 이상의 버킷 또는 두 개 이상의 StorageGRID 테넌트를 사용할 수도 있습니다.  다양한 버킷과 테넌트를 사용하면 ONTAP 로컬 계층 간에 데이터와 데이터 액세스를 분리할 수 있지만 구성 및 관리가 다소 복잡합니다.

NetApp 여러 클러스터의 로컬 계층에 단일 클라우드 계층을 연결하는 것을 권장하지 않습니다.


NOTE: NetApp MetroCluster™ 및 FabricPool Mirror와 함께 StorageGRID 사용하는 모범 사례는 다음을 참조하세요. https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598: ONTAP 의 FabricPool 모범 사례"^] .



=== 선택 사항: 각 로컬 계층에 대해 다른 버킷을 사용하세요.

ONTAP 클러스터의 로컬 계층에 대해 두 개 이상의 버킷을 사용하려면 ONTAP 에 두 개 이상의 StorageGRID 클라우드 계층을 추가합니다.  각 클라우드 계층은 동일한 HA 그룹, 로드 밸런서 엔드포인트, 테넌트 및 액세스 키를 공유하지만 다른 컨테이너( StorageGRID 버킷)를 사용합니다.  다음의 일반적인 단계를 따르세요.

. StorageGRID Grid Manager에서 첫 번째 클라우드 계층에 대한 FabricPool 설정 마법사를 완료합니다.
. ONTAP System Manager에서 클라우드 계층을 추가하고 StorageGRID 에서 다운로드한 파일을 사용하여 필요한 값을 제공합니다.
. StorageGRID Tenant Manager에서 마법사가 생성한 테넌트에 로그인하고 두 번째 버킷을 만듭니다.
. FabricPool 마법사를 다시 완료합니다.  기존 HA 그룹, 로드 밸런서 엔드포인트 및 테넌트를 선택합니다.  그런 다음, 수동으로 만든 새 버킷을 선택합니다.  새 버킷에 대한 새 ILM 규칙을 만들고 해당 규칙을 포함하도록 ILM 정책을 활성화합니다.
. ONTAP 에서 두 번째 클라우드 계층을 추가하지만 새 버킷 이름을 제공합니다.




=== 선택 사항: 각 로컬 계층에 대해 다른 테넌트와 버킷을 사용합니다.

ONTAP 클러스터의 로컬 계층에 대해 두 개 이상의 테넌트와 다양한 액세스 키 세트를 사용하려면 ONTAP 에 두 개 이상의 StorageGRID 클라우드 계층을 추가합니다.  각 클라우드 계층은 동일한 HA 그룹, 로드 밸런서 엔드포인트를 공유하지만 다른 테넌트, 액세스 키 및 컨테이너( StorageGRID 버킷)를 사용합니다.  다음의 일반적인 단계를 따르세요.

. StorageGRID Grid Manager에서 첫 번째 클라우드 계층에 대한 FabricPool 설정 마법사를 완료합니다.
. ONTAP System Manager에서 클라우드 계층을 추가하고 StorageGRID 에서 다운로드한 파일을 사용하여 필요한 값을 제공합니다.
. FabricPool 마법사를 다시 완료합니다.  기존 HA 그룹과 로드 밸런서 엔드포인트를 선택합니다.  새로운 테넌트와 버킷을 만듭니다.  새 버킷에 대한 새 ILM 규칙을 만들고 해당 규칙을 포함하도록 ILM 정책을 활성화합니다.
. ONTAP 에서 두 번째 클라우드 계층을 추가하지만 새로운 액세스 키, 비밀 키 및 버킷 이름을 제공합니다.

